geonetwork/core-geonetwork

- services/src/main/java/org/fao/geonet/api/records/formatters/FormatterApi.java
- services/src/main/java/org/fao/geonet/api/records/formatters/SchemaLocalizations.java
Testing: Load a formatter forcing language to `cat` with http://localhost:8080/geonetwork/srv/api/records/HOM_GEOL_NATURES_FOND_50.xml/formatters/xsl-view?output=pdf&language=cat&approved=true will usually return another language (for me french) depending on the browser Accept-Language header. The language parameter is supposed to force the language (it was working for multilingual metadata field value - but this issue applies mainly to field label). 
Reason was that 2 serviceContexts were created, the first with the language parameter
and the second with the header info. SchemaLocalization getting info from ServletRequestAttribute was wrong.
Fix: Create the correct ServiceContext before formatting.
> PDF / Language parameter does not override Accept-Language header in all cases.

- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
Make styling consistent depending on formatter config:
* when a tab contains only one section - remove unnecessary block
Before:
After:
* when a view has one tab - make styling consistent
Before (border-bottom is not the standard layout):
After:
* when a field is based on a template - create a block with its field
For testing configure the formatter to have advanced view in one tab and INSPIRE view (which use template field mode):
```json
"formatter": {
"list": [
{
"label": "defaultView",
"url": ""
},
{
"label": "full",
"url": "/formatters/xsl-view?root=div&view=advanced&tabs=false"
},
{
"label": "inspire",
"url": "/formatters/xsl-view?root=div&view=inspire&tabs=false"
}
],
"defaultUrl": ""
},
```
* Also add XSL field mode rendering (not used in core GN)
> Formatter / XSL / Improvement when not using tabs

- web-ui/src/main/resources/catalog/views/default/directives/partials/linksbtn.html
Download links are not rendered in record view.
In result view, the button is active and should not.
Before:
After:
> Privileges / When user can't download disable download action

- services/src/main/java/org/fao/geonet/api/regions/RegionsApi.java
Client side cache is set up on angular app side. So we can rely on client side cache for this. 
No need for this check on server side - there is no similar behavior in the API.
Test:
* open https://vanilla.geocat.net/geonetwork/srv/api/regions?categoryId=http%3A%2F%2Fwww.naturalearthdata.com%2Fne_admin%23Country
* and reload (if browser cache is enabled, the content will be null)
> API / Region / Return null.

- web-ui/src/main/resources/catalog/style/gn.less
Fix for https://github.com/geonetwork/core-geonetwork/pull/4527
The mixin causing the error is replaced with plain CSS code.
> Fix for #4527: Replace mixin with plain CSS code

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/csw.js
* If reset batch edit form field with empty content, set the value to no edits (ie. empty array)
* Do not count updates twice. result.updatedMetadata++ was done in case of OVERRIDE and in the update method.
* Do not delete privileges twice. Deletion is handled in BaseAligner.addPrivileges.
> Harvester / CSW / Misc fix.

- web-ui/src/main/resources/catalog/components/common/map/externalviewer.js
- web-ui/src/main/resources/catalog/components/metadataactions/RelatedDirective.js
- web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/locales/en-search.json
* Fix substitutions because url, title can be multilingual
* Fix substitutions because they need to be URL encoded to work
* Add possibility to enable the external viewer only on related panel (as an extra app for vizualisation)
* Add variables to pass language, metadata title (sometimes used for layer label in legend)
> Map / External viewer improvements

- domain/src/main/java/org/fao/geonet/entitylistener/UserNodeIdSetter.java
Error was triggered when synchronizing index on startup and when an error occur 
Then the owner of the record was retrieved and the exception created.
Related to https://github.com/geonetwork/core-geonetwork/pull/4542
> Multi portal mode / User entity listener may be triggered outside a request scope

- web-ui/src/main/resources/catalog/components/edit/multilingualfield/MultilingualFieldDirective.js
- web-ui/src/main/resources/catalog/components/edit/multilingualfield/partials/multilingualfield.html
This contains UX changes for the multilingual fields
1. ordering of nav-pills
Right now the nav-pills ("all french english") at the bottom of a multilingual fields aren't in the same order as the <input> appear in the UI.  This looks "funny."
This PR will put the order of the pills in the same order as in the UI.
It does this by looking at the lang=... attribute of the <input> contained in the element.
NOTE: the angular object goes from from a dictionary to a ["key": key, "value": value] list.
2. control focus when changing languages
Right now when you changes languages (using nav pills), focus() is called on one of the <input> fields.  It most cases this is ok.  However, for some <inputs> this will cause popups to happen.  For example, the Keyword Picker.  This isn't very nice for users. …
> change order of nav-pills in multilingual fields

- web-ui/src/main/resources/catalog/views/default/less/gn_layout_default.less
Using `none` for the background-image variable was causing a 404 in the browser to a non existing page called 'none'.
See the first line of the screenshot
This PR improves the check for the value of the background-image variable, so there is no non existing page anymore.
> Fix for the `none` background image causing a 404 to a non existing page

- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
eg. with this kind of editor config:
```xml
<section name="emodnetQualityTitle">
<section name="emodnetHorAccuracyTitle">
<field xpath="/gmd:MD_Metadata/gmd:dataQualityInfo/*/gmd:report/
gmd:DQ_GriddedDataPositionalAccuracy/gmd:measureDescription"/>
<field xpath="/gmd:MD_Metadata/gmd:dataQualityInfo/*/gmd:report/
gmd:DQ_GriddedDataPositionalAccuracy/gmd:result/*/gmd:value"/>
<field xpath="/gmd:MD_Metadata/gmd:dataQualityInfo/*/gmd:report/
gmd:DQ_GriddedDataPositionalAccuracy/gmd:evaluationMethodDescription"/>
</section>
<section name="emodnetVertAccuracyTitle">
<field xpath="/gmd:MD_Metadata/gmd:dataQualityInfo/*/gmd:report/
gmd:DQ_QuantitativeAttributeAccuracy/gmd:measureDescription"/>
<field xpath="/gmd:MD_Metadata/gmd:dataQualityInfo/*/gmd:report/ …
```
> Formatter / Display a section only if there is something in

- web-ui/src/main/resources/catalog/components/userfeedback/GnmdFeedbackDirective.js
- web-ui/src/main/resources/catalog/components/userfeedback/partials/mdFeedback.html
- web-ui/src/main/resources/catalog/js/search/SearchController.js
- Use metadata rating setting to enable  the metadata rating panel in the metadata detail page instead of the user feedback setting (contact us feature).
- Add var declaration to javascript variable.
> Fixes for metadata rating

- web/src/main/webapp/WEB-INF/data/config/codelist/external/thesauri/place/regions.rdf
Following EUROSTAT guideline (https://ec.europa.eu/eurostat/help/faq/brexit):
* change EU27 to EU27_2007
* add EU27_2020
* clarify labels for EU27* and EU28 with years
For catalogue using this in keywords, the following can be used to update existing records:
```sql
UPDATE metadata SET data = replace(data, '>EU27<', '>EU27_2007<') WHERE data LIKE '%>EU_27<%';
```
> Thesaurus / Regions / Brexit

- schemas/iso19139/src/main/plugin/iso19139/update-fixed-info.xsl
Issue - when have a multilingual field with only the non-default languages, save doesn't save.
To reproduce, you need a multi-lingual document;
1. Run fresh 3.10.x & login
2. add iso 19139 templates and examples
3. create a new record, based on the "Template for Vector data in ISO19139 (multilingual)" template
4. edit the record in XML
5. go to the "abstract" part and delete all the information;
<gmd:abstract gco:nilReason="missing" xsi:type="gmd:PT_FreeText_PropertyType">
<gco:CharacterString/>
</gmd:abstract>
6. Save and edit in Simple mode
7. Change the GERMAN ("Deutsch") abstract  
8. Save
You will notice, that the change is "undone" and you will end up with nothing in the abstract.
This is a port of the HNAP change that fixes this; …
> fix multilingual save issue (iso 19139)

- web-ui/src/main/resources/catalog/components/common/ows/OWSService.js
- web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextService.js
- web-ui/src/main/resources/catalog/style/gn_viewer.less
A group layer is a list of layers combined into one eg.
```xml
<ows-context:Layer name="1,3,0,2,5,4" group="Background layers" hidden="false" opacity="1">
<ows-context:Server service="urn:ogc:serviceType:WMS" version="1.3.0">
<ows-context:OnlineResource
xlink:href="https://bio.discomap.eea.europa.eu/arcgis/services/Internal/Basemap_EU_27_WM_Cached/MapServer/WmsServer"/>
```
This fix
* the getCapabilities parsing which was altered once cached (by making a copy from the cache each time it is requested).
Write group layer in context properly (only first layer of the group was taken into account).
* Fix loading layer when a background is a WMS (spinner was never hidden).
* Set layer name and title properly for background layers.
* Fix display of long …
> Map / Background layer / Add support for WMS group layer

- web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js
- web-ui/src/main/resources/catalog/locales/en-core.json
Metadata batch validation from the Editor Dashboard displays the following message when the process finishes:
Update to display the validation summary report returned:
> Metadata batch validation show validation summary instead of a message with '[Object object]' text

- services/src/main/java/org/fao/geonet/api/processing/ValidateApi.java
Fixes https://github.com/geonetwork/core-geonetwork/issues/4487
But globally there is more testing to do on all calls to process when multithread.
> Validation / Index in current thread to avoid lock

- services/src/main/java/org/fao/geonet/api/cssstyle/CssStyleSettingsService.java
- web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/templates/admin/settings/cssstyle.html
- web-ui/src/main/resources/catalog/views/default/less/gn_layout_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_navbar_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_variables_default.less
- web/src/main/webapp/xslt/base-layout.xsl
This PR adds an option to get a fixed header for GeoNetwork. 
In the admin there is a new setting to fix the header ([Settings] > [User interface] > [Header]), and an extra option to set the height of the header ([Settings] > [CSS & Style] > [Header] > [Height]). This height is needed for when both options for `Fixed Header` and `Show the logo in header` are selected.
> Fixed header option for GeoNetwork

- web-ui/src/main/resources/catalog/views/default/less/gn_navbar_default.less
The menu on smaller screens has some small visual errors (padding and labels). This PR fixes these errors (see screenshots).
**Before the changes** 
**After the changes**
> Fix the menu for smaller screens

- pom.xml
Reducing the number of repositories in the build is an easy way to reduce build times:
* GeoTools repository moved to repo.osgeo.org
* GeoSolutions repository cached by repo.osgeo.org
* Boundless repository no longer available, contents moved to repo.osgeo.org
* Maven Central repository is assumed
* juniversalchardet is in maven central now
Please note that repo.osgeo.org is available to the geonetwork project if we wish to manage our own releases, docker images, or cache third-party dependencies.
> Update repositories used by build

- web-ui/src/main/resources/catalog/style/gn_metadata.less
- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
Does not apply to simple and advanced view making no usage of template field but in custom view if a template field match many elements, all fields are displayed one after the other with no way to make distinction between matching elements.
eg.
```xml
<tab id="sdn-contact" mode="flat">
<section>
<field name="sdn-ResourceProviderTitle"
templateModeOnly="true"
notDisplayedIfMissing="true"
xpath="/gmd:MD_Metadata/gmd:identificationInfo/*/
gmd:pointOfContact[*/gmd:role/*/@codeListValue = 'author']"
del=".">
<template>
<values readonlyIf="count(@xlink:href) > 0">
<key label="organisationName"
xpath="gmd:CI_ResponsibleParty/gmd:organisationName/gco:CharacterString"/>
<key label="country"
xpath="gmd:CI_ResponsibleParty/gmd:contactInfo/
gmd:CI_Contact/gmd:address/gmd:CI_Address/gmd:country/gco:Cha …
```
> Formatter / Template field / Add bottom margin to make distinction of each matching elements.

- web-ui/src/main/resources/catalog/style/gn_metadata.less
Fix when long labels are used in button
After the fix:
> Angular view / Related resources / Fix word wrap on long label button

- web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
Display title, description if any and the link (no title in example below):
> Angular view / Related resource / Add description if any on links.

- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java
Replace oldUuid references by newUuid.
This will update metadata identifier, but also other usages
which may be in graphicOverview URLs, resources identifier
metadata point of truth URL, ...
This is applied when creating records from a template or duplicating
another record.
> Metadata creation / Update UUID references

- web-ui/src/main/resources/catalog/components/thesaurus/ThesaurusDirective.js
This is a minor change the thesaurus keyword picker.
I am re-using this as a component in another component.
a) I've given the ability for it to be in multi-lingual mode without it being in a "proper" multilingual element.  Just add "faux-multilingual='true'".  This defaults to false, so this should NOT be noticed by anyone.
b) I noticed that angular was not being notified of changes to a value - I added a "kicker" so it gets notified.
-----------------------
NORMAL WAY (schmatic)
* note - adding data-gn-multilingual-field actually makes a lot of changes
\<div data-gn-multilingual-field="... config ...">
<input lang="fre" ... />
<input lang="eng" ... />
\</div>
WRONG WAY - if you do this, there are two issues;
a) the two type-ahead inputs are INDEPENDENT (i.e. they can have different …
> git allow keyword picker to be used inside another component

- pom.xml
- web/src/main/webResources/WEB-INF/config-db/jndi.xml
- web/src/main/webResources/WEB-INF/config-db/jndiExamples_tomcat/README.md
- web/src/main/webResources/WEB-INF/config-db/jndiExamples_tomcat/h2_JNDI_Example.xml
- web/src/main/webResources/WEB-INF/config-db/jndiExamples_tomcat/oracle_JNDI_Example.xml
- web/src/main/webResources/WEB-INF/config-db/jndiExamples_tomcat/postgres_JNDI_Example.xml
- web/src/main/webapp/WEB-INF/jetty-env.xml
JNDI support improvements:
- Add examples for Tomcat configuration.
- Change Jetty JNDI to use H2 by default.
- Support different databases (current support was focus on Postgres).
This folder contains JNDI example files for Tomcat for H2, Oracle and Postgres.
* Pick the jndi configuration for the database you want to use and fill the relevant parameters for your database
* Rename the file to geonetwork.xml (or to appName.xml if you use another name)
* Put the file inside `TOMCAT_DIR/conf/Catalina/localhost` 
* Be sure that the jar for the driver you want to use is in `TOMCAT_DIR/lib`
**Note:** replace `TOMCAT_DIR` with Tomcat path.
Check the following links for additional documentation about JNDI configuration in Tomcat:
- https://tomcat.apache.org/tomcat-8.5-doc/jndi-resources-howto.html …
> JNDI support improvements

- web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
Avoid JS error in this case and display the label properly.
Before:
Error:
After:
> Angular view / Associated resource / Layer name may contain quote

- events/src/main/java/org/fao/geonet/events/history/RecordGroupOwnerChangeEvent.java
```
at org.fao.geonet.events.history.RecordGroupOwnerChangeEvent.getPreviousState(RecordGroupOwnerChangeEvent.java:57)
at org.fao.geonet.listener.history.GenericMetadataEventListener.storeContentHistoryEvent(GenericMetadataEventListener.java:88)
at org.fao.geonet.listener.history.GenericMetadataEventListener.handleEvent(GenericMetadataEventListener.java:60)
at org.fao.geonet.listener.history.RecordGroupOwnerChangeListener.onApplicationEvent(RecordGroupOwnerChangeListener.java:49)
at org.fao.geonet.listener.history.RecordGroupOwnerChangeListener.onApplicationEvent(RecordGroupOwnerChangeListener.java:30)
at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
at …
```
> Transfer owner / NPE when history is ON and group owner is null (which is allowed in the DB)

- domain/src/main/java/org/fao/geonet/domain/MetadataCategory.java
I've encountered an issue where metadata full view (iso19139, formatter, xsl-view) would take a long time to load on a large-ish database (10k+). It happened due to metadata to XML serialization propagating like [metadata -> category -> all metadata in that category] and generating thousands of hibernate queries for a single metadata view. Problem was traced to an incorrect exclusion in MetadataCategory with respect to the "getRecords" method. The exclusion was corrected and the fix was tested on a 3.10.2 instance.
> Fix serialization exclusion in MetadataCategory

- pom.xml
- web/src/main/webResources/WEB-INF/config-db/h2.xml
- web/src/main/webResources/WEB-INF/config-db/jdbc.properties
- web/src/main/webResources/WEB-INF/config-db/mysql.xml
- web/src/main/webResources/WEB-INF/config-db/oracle.xml
- web/src/main/webResources/WEB-INF/config-db/postgres-postgis.xml
- web/src/main/webResources/WEB-INF/config-db/postgres.xml
Updated connection settings so that it supports supplying the port and connectionProperties parameter.
Also fixed hard coded configuration port which defaulted to 5432 (postgresql) even though default config db is h2?
Related to issue #4624 
Note: only applied the new connectionProperties to h2 and postgresql database connection.  If other databases require the usage of this new connectionProperties then they will need to be added by someone else as I don't have access to test with some of the other databases at this time.
> Updated connection settings to support port and connectionProperties

- core/src/main/java/jeeves/server/dispatchers/ServiceManager.java
Before, CSV file content was displayed in the browser. 
This will force attachment to be downloaded.
This only applies to remaining Jeeves services - csv.search and harvester log
> Search / CSV export / Trigger download in browser

- web-ui/src/main/resources/catalog/style/gn.less
- web-ui/src/main/resources/catalog/style/gn_editor.less
- web-ui/src/main/resources/catalog/views/default/less/gn_feedback_default.less
This PR improves the styling for all scrollbars in GeoNetwork and increases the width/height so the scrollbar is better clickable.
This PR also addresses the problems in issue: https://github.com/geonetwork/core-geonetwork/issues/4636
> Improve styling for scrollbars

- schemas/iso19139/src/main/plugin/iso19139/loc/por/strings.xml
An XML closing tag was mistakenly translated.
> Fix typo in closing XML tag

- core/src/main/java/org/fao/geonet/kernel/search/IndexAndTaxonomy.java
- core/src/main/java/org/fao/geonet/kernel/search/index/LuceneIndexLanguageTracker.java
- core/src/main/java/org/fao/geonet/kernel/search/index/TaxonomyIndexTracker.java
See #4481 
I've modified `TaxonomyIndexTracker` so that it does a better job of releasing TaxonomyReaders.
During harvesting, `maybeRefresh()` would be called (often).  The "`openIfChanged()`" call would create a new `DirectoryTaxonomyReader`.  However, the old one would not be released.
When you create a `TaxonomyReader`, it will have a ref count of 1.  There wasn't any code that would decrement it so it would always go in the `expiredReader` list.
I've modified this so it would be better at handling the ref counts.  The reference that `TaxonomyIndexTracker` keeps (for `this.taxonomyReader`) is one reference count (the one that is automatically created when you create a `TaxonomyReader`).  If someone calls `aquire()`, then it gets a 2nd reference count.
If `maybeRefresh()` creates …
> fix memory leak due to incorrect ref count handling (#4481)

- web/src/main/webResources/WEB-INF/config-db/database_migration.xml
In database_migration.xml, fixed steps "3.0.0" and "3.1.0" which referenced classes with wrong package names, causing ClassNotFoundException during migration.
> Fixed two classes in database migration with wrong package names

- services/src/main/java/org/fao/geonet/api/records/MetadataUtils.java
Some relations use a query in Lucene that already uses the portal filter, but other relations were retrieving directly the metadata without that filter, so could be retrieved metadata not available in a portal.
> Use portal filter to retrieve associated resources

- pom.xml
- web/src/main/webResources/WEB-INF/config-node/srv.xml
This pull request is add the ability to use env variables to set database connection properties as described in #4643 
Note: This change eliminated the pom setting for <db.config.file>. The reason it has been removed is for 2 reasons.
- As SpEL is being used to supply the db type parameter which is used in the svr.xml. The import does not parse the SpEL commands before the import and so it attempts to load a file called "config-db/#{systemEnvironment['DB_TYPE']?:'h2'}.xml"
- If the database file is specify the db config file in the pom then we are limiting the built war file to only support a single database at runtime.
Here is a list of environment variables that can be set at runtime to connect to a postgres database using SSL mode.
```
DB_TYPE=postgres
DB_NAME=geonetwork …
```
> Updated db connections so that it can be specified as env variables.

- web-ui/src/main/resources/catalog/components/edit/multientrycombiner/MultiEntryCombiner.js
- web-ui/src/main/resources/catalog/components/edit/multientrycombiner/partials/multientrycombiner.html
I've changed how values are sent back to the server - there is more control now.
It used to always send them back like '_lang_eng_14' (based on root_id).
However, you now send a refs dictionary in the json config.  It uses these values instead.
> use more precise references for setting element values on server

- schemas/iso19139/src/main/plugin/iso19139/config/associated-panel/default.json
Only `jpg` format was supported so upload `jpeg` images were not listed while adding overviews
> Editor / Overview / Add JPEG format in file filter.

- core/src/main/java/org/fao/geonet/notifier/MetadataNotifierClient.java
Set encoding to UTF-8 in metadata notifier requests, otherwise the xml special chars like accents are not encoded properly.
> Set encoding to UTF-8 in metadata notifier requests

- schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
- web-ui/src/main/resources/catalog/components/elasticsearch/EsService.js
- web/src/main/webapp/xslt/common/index-utils.xsl
Avoid indexing error on:
* null date
* invalid date
* upper range bound greater than lower
eg.
```
Caused by: java.lang.IllegalArgumentException: min value (696902400000)
is greater than max value (20191028)
org.elasticsearch.index.mapper.MapperParsingException: failed to parse field 
[resourceTemporalDateRange] of type [date_range] in document with id
'3e501c87-9146-4d9b-9237-8165c8f7cd51'. Preview of field's value: 'now'
Caused by: org.elasticsearch.ElasticsearchParseException: 
failed to parse date field [* date de début de période AAAA[-MM-JJ] *] with 
format [date_optional_time||yyyy-MM-dd||yyyy-MM||yyyy||epoch_millis]: 
[failed to parse date field [* date de début de période AAAA[-MM-JJ] *] 
with format [date_optional_time||yyyy-MM-dd||yyyy-MM||yyyy||epoch_millis]] …
```
> Indexing / More robust for date type & lucene expression support

- common/src/main/java/org/fao/geonet/utils/GeonetHttpRequestFactory.java
`GeonetHttpRequestFactory` supports Preemptive Basic Auth for `XmlRequest` using ` HttpClientContext`:
https://github.com/geonetwork/core-geonetwork/blob/a3fbd28483f34d4b76b4a60801b26cf232930da6/common/src/main/java/org/fao/geonet/utils/GeonetHttpRequestFactory.java#L173-L186
But this only works with `XmlRequest`, this pull request add support to use `HttpClientContext` in `HttpUriRequest`, so Preemptive Basic Auth can be supported in services that requires it.
Some usages are for metadata notifier (another PR will improve it) or other external services like DOI that can be configured and potentially requires it.
> Add method to support HttpClientContext for HttpUriRequest requests in GeonetHttpRequestFactory

- services/src/main/java/org/fao/geonet/api/registries/vocabularies/KeywordsApi.java
Fix null pointer exception in thesaurus API when no thesaurus was supplied.
Arrays.asList(thesaurus) throwing null pointer error when thesaurus was null.
> Fix null pointer exception in thesaurus API

- web-ui/src/main/resources/catalog/components/common/map/mapDirective.js
The map editor bbox layer is lost when using a context file to initialise the map. 
The code to create the map, uses a promise:
https://github.com/geonetwork/core-geonetwork/blob/64380c15ad68a5381c8efca35011496664427eae/web-ui/src/main/resources/catalog/components/common/map/mapsManager.js#L243-L285
But the bbox layer is added without using the promise:
https://github.com/geonetwork/core-geonetwork/blob/64380c15ad68a5381c8efca35011496664427eae/web-ui/src/main/resources/catalog/components/common/map/mapDirective.js#L248-L250
When using `osm` (default) is ok as the layer is added to the map, without removing other layers, but when **using a context file**, the map layers are removed, so if the bbox layer was added already, it is removed and the bbox selected by the user is not displayed.
> Map editor - use map promise to add the bbox layer

- common/pom.xml
- csw-server/pom.xml
- schemas/schema-core/pom.xml
This addressed https://github.com/geonetwork/core-geonetwork/issues/4684 by introducing excludes into each dependency on `jdom`.
This is a build change only, addressing a il-advised dependency introduced by jaxen. The project had incorrectly added a dependency on two maven plugins as compile time dependencies dragging them into our codebase. Our build does not have a maven plugin repository available during compile time prevent a complete build from a fresh local maven repository.
> jdom transitive dependency excludes (due to ill-advised jaxen pom)

- schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields.xsl
- web-ui/src/main/resources/catalog/style/gn_editor.less
Updating `labels.xml` with `condition` element:
```
<element name="gmd:EX_GeographicBoundingBox" id="343.0">
<label>Geographic bounding box</label>
<description>Geographic position of the dataset</description>
<condition>mandatory</condition>
</element>
```
Allows to display a mandatory flag for the Bounding Box element:
Added CSS styling can be extended for other section elements if required.
> Support mandatory flag in editor sections. Initially supported for BoundingBox

- web-ui/src/main/resources/catalog/views/default/directives/partials/infolist.html
Tooltip content
* Title has full title 
* Overview as abstract 
It makes the user less blind to what is going to click on when records have long and similar titles
> Home page / Add tooltip on title and overview

- core/src/main/java/org/fao/geonet/kernel/Thesaurus.java
Reverts a change introduced in https://github.com/geonetwork/core-geonetwork/commit/51a9bb99be19c00f8492bf9739109c0b30daec68 that causes validation issues in INSPIRE.
Tests with external and local vocabularies seem fine.
> Don't add '#' to thesaurus url. Related to #3918

- services/src/main/java/org/fao/geonet/api/records/extent/MapRenderer.java
- services/src/main/java/org/fao/geonet/api/records/extent/MetadataExtentApi.java
- services/src/main/java/org/fao/geonet/api/records/formatters/ImageReplacedElementFactory.java
- services/src/main/java/org/fao/geonet/api/regions/RegionsApi.java
- services/src/main/java/org/fao/geonet/services/region/GetMap.java
- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-functions.xsl
* Add new parameter for
* fill color: fillColor
* stroke color: strokeColor
* Draw fill before stroke - rendering of geometry border is better
* Change default colors to make mix of small/large extent more visible (see below)
* Fix buffered image type when the base image was loaded from a URL. Always create an ARGB image. Improves colors & transparency.
* PDF / Fix rendering of images when API /api/regions/geom.png is used - encode " "
* PDF / Fix rendering of an image with URL with parameters - extension not retrieved properly
Eg.
* Before
* Default
* Custom with http://localhost:8080/geonetwork/srv/api/records/93eede6e-c196-40e3-9253-7f2237b49de1/extents.png?fillColor=0,255,0,44&strokeColor=255,255,0,255
>  Extent API / Add color parameters

- web-ui/src/main/resources/catalog/views/default/directives/partials/periodchooser.html
- web-ui/src/main/resources/catalog/views/default/less/gn_search_default.less
- web-ui/src/main/resources/catalog/views/default/templates/advancedSearchForm/defaultAdvancedSearchForm.html
- web-ui/src/main/resources/catalog/views/default/templates/home.html
- web-ui/src/main/resources/catalog/views/default/templates/searchForm.html
GeoNetwork has 2 search boxes on 2 pages: `Home` and `Search`, but they differ in width, and the advanced panel on the `Search` page also has a different width.
This PR changes the width, so all inputs and panels have the same width.
Restructured search boxes, all changes:
- same width on `Home` and `Search` page
- changed order of buttons (advanced is last)
- same width for advanced panel
- improved responsiveness
- removed/cleanup CSS
**Advanced search before**
**Advanced search after**
> Uniform look for search inputs on Home and Search page

- schemas/iso19139/src/main/plugin/iso19139/loc/ara/labels.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/cat/labels.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/chi/labels.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/dut/labels.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/eng/labels.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/fin/labels.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/fre/labels.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/ger/labels.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/ita/labels.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/nor/labels.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/pol/labels.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/por/labels.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/rus/labels.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/slo/labels.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/spa/labels.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/tur/labels.xml
This adds a generic translation for xlink to avoid the error on the console:
`gn-fn-metadata:getLabel | missing translation in schema iso19139 for xlink:type.`
> ISO19139 / Add missing translation

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
This mainly applies when a schema define a custom config for the list of types.
> Editor / Associated panel / Edit link / Init type selector

- pom.xml
xml-commons-resolver (1.2) conflicts with xml-resolver-patched (1.2.1) - same jar different version.
Fixes issue #4661
> Fix dependency issue #4661.  Dependency conflict causing issues on Windows build

- web-ui/src/main/resources/catalog/components/history/partials/history.html
- web-ui/src/main/resources/catalog/templates/admin/dashboard/record-links.html
- web-ui/src/main/resources/catalog/templates/admin/dashboard/versioning.html
This PR replaces: https://github.com/geonetwork/core-geonetwork/pull/4674
The `Record links analysis` and `Versioning` pages had a different looking layout than all the other admin pages. This PR changes that and gives it a more uniform look across all pages in the admin.
**Record links analysis before**
**Record links analysis after**
**Versioning before**
**Versioning after**
> Uniform look for the Statistics pages in the Admin (replaces #4674)

- core/pom.xml
- pom.xml
- web/pom.xml
See proposal [Host Geonetwork artifacts on repo.osgeo.org](https://github.com/geonetwork/core-geonetwork/wiki/Host-Geonetwork-artifacts-on-repo.osgeo.org-(Nexus-Artifactory-Repo)) for details.
Cache remote repositories:
Note replacing [core-maven-repo](https://github.com/geonetwork/core-maven-repo) was not successful and is being cached above.
Build changes and dependency review:
Going to save change to maven-resources-plugin:copy-resources to maven-dependency-plugin:unpack for subsequent PR as it may be quite extensive.
> Shift to new maven repositories (OSGeo)

- pom.xml
- web/src/main/java/org/fao/geonet/proxy/URITemplateProxyServlet.java
- web/src/main/webResources/WEB-INF/web.xml
Currently the GeoNetwork proxy is quite permissive. It is used mainly in
the following cases:
* Map viewer / GetCapabilities document retrieval
* Map viewer / Load a WFS layer
* Map viewer / WMS GetFeatureInfo
* Record view / List atom feed resources
* Editor / Warning if a link return http errors
* Admin / Harvesting / GetCapabilities for CSW to retrieve queryable fields
* Admin / Thesaurus / Add from INSPIRE registry
* ...
Add a configuration to limit its usage to some URL host only.
2 modes are available:
* `NONE`: allow all like before.
* `DB_LINK_CHECK` (default):
* allow all for authenticated user
* allow only host registered in metadata link table
For anonymous user, if the host of the URL requested is not used in any
metadata record links, then a `NotAllowedException` is returned. …
> Proxy / Limit to URL host registered in records.

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
This is fixes two problems;
a) when you first open the online resources edit, the values for title/description are NOT shown on the UI (when open it a second time, they are there).
* cause: scope.isMdMultilingual  was being used before set -- i just changed the order of the code
b) when you edit multilingual online resources, the UI doesn't show existing alternatives.
* cause: linkToEdit[fields[field]][key] -- this should have been v
* for example, this would be ger: DE (key = 'ger', v='DE').  The field has values using "DE" and "EN", etc... (not ger/eng).  I made it so it would handle both.
> fix online resources

- web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
When you choose to display the help in the `Editor` as icons, GeoNetwork displays all the help icons for all multilingual fields in the `Editor`. All these help icons and help texts are the same. This PR displays only the first of all these help icon.
**Before**
**After**
> Display only the first help icon in a multilingual field in the Editor

- schemas/dublin-core/src/main/plugin/dublin-core/index-fields/default.xsl
Fix error in dublin core indexing when a metadata document has more than
one `dc:title`.
```xml
Error on line 57 of default.xsl:
XPTY0004: A sequence of more than one item is not allowed as the first argument of
string() (<dc:title/>, <dc:title/>)
```
> Fix indexing errors with multiple titles in Dublin Core

- services/src/main/java/org/fao/geonet/api/registries/vocabularies/KeywordsApi.java
There is some inconsistency between the uri to reference keywords.
I noticed this when there's a space in the keyword "children's park" the sometime there is a " " and sometimes there is a "%20".
This will try both possibilities.
> fix spaces-in-url keyword encoding

- web-ui/src/main/resources/catalog/components/metadataactions/RelatedResourcesService.js
- web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
The online resources in the metadata window have a fallback that shows a question mark for unknown types. However this icon was shown too often and overriding other icons when the type was known (e.g. downloads). This PR changes the way the fallback is used a little and prevents the override of known types.
**Before**
**After**
> Fix for displaying icons for Online Resources

- web-ui/src/main/resources/catalog/components/thesaurus/ThesaurusDirective.js
This allows multiple free keyword sections.  This is necessary if you want to have keywords of different types (currently not possible).
You can see I've added a keyword ("a") with "Place" type.
However, if I press the "+ Add new keywords" button, it just adds a new "Place" keyword.  I cannot add other types of freetext keywords (i.e. Temporal, etc...).
This seems to be by design.
This PR allow you to add a 
data-always-create-new-freekeyword-section="true"
tag to the element.  Then, when you press the "+ Add new keywords", it will always create a new sections.
Pressing the button (no text, tooltip "keyword", immediately under the keyword) will add a slot to type in another keyword.
End result;
> allow multiple freekeyword sections

- web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
This attribute is needed for some directive like `gnLanguagePicker`.
> Fix related to PR https://github.com/geonetwork/core-geonetwork/pull/3569 to send the element name as as directive parameter

- services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
- services/src/main/java/org/fao/geonet/api/records/model/MetadataStatusResponse.java
- web-ui/src/main/resources/catalog/components/history/partials/historyStep.html
Fixed bug with where the history link to the metadata was not working because it was linking using the id instead of the uuid
This fix also add metadata uuid to the status api results.
This is the link that was not working.
> Fixed bug with history link to the metadata.

- web-ui/src/main/resources/catalog/components/search/mdview/mdviewDirective.js
- web-ui/src/main/resources/catalog/components/userfeedback/GnmdFeedbackDirective.js
- web-ui/src/main/resources/catalog/js/search/SearchController.js
The `isUserFeedbackEnabled` variable is used to trigger the showing of comments (for instance on the homepage). The variable stayed `undefined` and therefore the 'Comments' were not shown and clickable on the homepage.
It seemed the response wasn't received in time, this PR uses `gnConfigService` to solve this.
**The `comments` section on the homepage**
> Improved way of declaring the `isUserFeedbackEnabled` variable

- domain/src/main/java/org/fao/geonet/domain/Group.java
- domain/src/main/java/org/fao/geonet/domain/Localized.java
- domain/src/main/java/org/fao/geonet/domain/Schematron.java
- domain/src/main/java/org/fao/geonet/domain/Source.java
- services/src/main/java/org/fao/geonet/api/sources/SourcesApi.java
- services/src/main/java/org/fao/geonet/guiapi/search/SearchApi.java
- services/src/main/java/org/fao/geonet/guiapi/search/XsltResponseWriter.java
- web-ui/src/main/resources/catalog/templates/top-toolbar.html
- web-ui/src/main/resources/catalog/views/default/less/gn_layout_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_portal_default.less
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v3110/migrate-default.sql
- web/src/main/webapp/xslt/common/base-variables.xsl
- web/src/main/webapp/xslt/ui-search/portal-list.xsl
* Add specific style so it is easier to customize
* Use the background image if set in CSS style config
* Portal / Title / Add tooltip on long portal name
* Portal / Add optional description. One line to describe the portal in the portal page, document page title and top toolbar tooltip
* Portal name can be translated using "{title}|{description}"
* Fix tooltip on top tool bar
* Also increase the size of the label of groups, sources and schematron to 255 (like other localized tables)
> Portal page improvement

- web-ui/src/main/resources/catalog/components/thesaurus/ThesaurusDirective.js
This allows for some "nicer" UX when using the keyword picker.
You can now press enter to select an item.
Simple use case;
a) go to keyword picker
b) start typing something
c) press "tab" to select the first item
d) press "enter" to add to the list
This UX is nice for people doing keyboard based entry (instead of mouse-and-keyboard).
> UX keyword chooser - enter key

- es/.gitignore
- es/es-dashboards/.gitignore
- es/es-dashboards/pom.xml
- pom.xml
Added a maven profile to download elastic search, moved windows and macOS profiles to root pom.xml for consistency.
I also noted that the elasticsearch-7.4.2 folders were not listed in .gitignore.
> Add macOS profile to download elastic search

- web-ui/src/main/resources/catalog/templates/admin/classification/thesaurus.html
Currently the form can be saved, without the mandatory fields filled, displaying an error. 
Updated the form to enabled the `Create` button if the mandatory fields are filled. Also display the error warning in the missing fields.
> New thesaurus form - enable the Create button if the form is filled, display errors in missing fields

- web-ui/src/main/resources/catalog/views/default/less/gn_portal_default.less
- web/src/main/webapp/xslt/ui-search/portal-list.xsl
Related to https://github.com/geonetwork/core-geonetwork/pull/4758
Some improvements where made to the portal page:
- display icon before title and description
- fixed width for the icon section
- removed borders and backgrounds from the icon block
**Before**: https://github.com/geonetwork/core-geonetwork/pull/4758
**After**:
> Improved styling for the portals

- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java
Fix for #4782. This fix will apply the restriction for metadata template.  Metadata was already restricted.
> Restrict template creation based on METADATA_IMPORT_RESTRICT

- core/src/main/java/jeeves/server/dispatchers/guiservices/XmlCacheManager.java
Removing a log.error() call redundant with a log.debug() one.
> xml-cache-manager - Fix double logging trace

- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/locales/en-v4.json
- web-ui/src/main/resources/catalog/views/default/templates/home.html
Home page facet were limited to inspire theme, topic on the left side, resource type on the right side.
With this PR:
* The right side is composed with the last facet declared in the config
* The left side can be a list of one or more facets
> Home page / Add possibility to customize facets.

- web-ui/src/main/resources/catalog/js/admin/ThesaurusController.js
Before the update:
After the update:
> Improve code to handle error responses in thesaurus upload via file or url

- schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields-keywords.xsl
Fix to avoid duplicated thesaurus label in the metadata editor for iso19139 metadata multilingual metadata:
> Avoid duplicated thesaurus label in the metadata editor for iso19139 metadata multilingual metadata

- core/src/main/java/org/fao/geonet/kernel/Thesaurus.java
- core/src/main/java/org/fao/geonet/kernel/ThesaurusManager.java
- services/src/main/java/org/fao/geonet/api/ApiUtils.java
- services/src/main/java/org/fao/geonet/api/registries/vocabularies/KeywordsApi.java
- services/src/test/java/org/fao/geonet/api/ApiUtilsTest.java
- web-ui/src/main/resources/catalog/components/edit/multientrycombiner/MultiEntryCombiner.js
- web-ui/src/main/resources/catalog/components/thesaurus/ThesaurusDirective.js
- web-ui/src/main/resources/catalog/components/thesaurus/ThesaurusService.js
This adds multilingual titles capabilities for thesauri.
Add language-specific titles to the ConceptSchema at the top of your thesaurus;
```xml
<rdf:RDF ...>
<skos:ConceptScheme rdf:about="http://www.thesaurus.gc.ca/#CoreSubjectThesaurus">
<dc:title>Government of Canada Core Subject Thesaurus</dc:title>
**<dc:title xml:lang="en">Government of Canada Core Subject Thesaurus</dc:title>
<dc:title xml:lang="fr">Thésaurus des sujets de base du gouvernement du Canada</dc:title>**
</skos:ConceptScheme>
```
You will see this added to the Thesaurus object;
```json
"multilingualTitles":     [
{
"lang": "fr",
"title": "Thésaurus des sujets de base du gouvernement du Canada"
},
{
"lang": "en",
"title": "Government of Canada Core Subject Thesaurus"
},
{
"lang": "fre",
"title": "Thésaurus des sujets de …
```
> add multilingual titles to thesauri

- web-ui/src/main/resources/catalog/components/common/map/mapService.js
- web-ui/src/main/resources/catalog/components/common/ows/OWSService.js
- web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextService.js
- web-ui/src/main/resources/catalog/components/viewer/projectionSwitcher/ProjectionSwitcher.js
- web-ui/src/main/resources/catalog/locales/en-core.json
Fixes #4800 and #4801 (not a fix per se, but I don't see any other option).
This may happen because none of the matrix sets given in the WMTS capabilities are in a projection defined in the settings.
An error message points the user towards this:
This PR also removes the `extent` restrictions that were sometimes put on map views, and which would prevent the user from panning/zooming out. This does not work well on polar projections and impedes user experience instead of improving it.
Finally a fix for #4802 was introduced as well.
@pvgenuchten could you maybe do a quick review? thanks!
> Map Service / show error when parsing WMTS options failed

- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java
This namespace is added to the metadata to handle the metadata editing logic, and if not removed it's added to the metadata elements processed in update-fixed-info, unless `copy-namespaces="no"` is used, but some code uses `xsl:element` instead if `xsl:copy` and can't be use `copy-namespaces`. 
Adding this to the Java code avoids having to apply the change in the different metadata schemas.
Original result:
```
<gmd:characterSet xmlns:geonet="http://www.fao.org/geonetwork">
<gmd:MD_CharacterSetCode codeListValue="utf8" 
codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_CharacterSetCode"/>
</gmd:characterSet>
```
```
<gmd:characterSet>
<gmd:MD_CharacterSetCode codeListValue="utf8" 
codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists. …
```
> Remove the 'geonet' namespace from the metadata

- web-ui/src/main/resources/catalog/views/default/config.js
- web-ui/src/main/resources/catalog/views/default/module.js
This transaction is to enhance the GN ESRI REST API support to cover one of the commonly used subtype "Map Server" protocol.
Esri supports a various protocol types:
ESRI REST, 
ESRI REST: Feature Server, 
ESRI REST: Image Service,  
ESRI REST: Map Server, 
ESRI REST: Tiled Map Service, 
OGC WMS
More than half of the datasets (maybe close to 80%) from FGP (https://maps.canada.ca/en/index.html)  with the Esri mapping capabilities use the ESRI REST: Map Server protocol instead.
Geonetwork adds the ESRI Rest API support in 3.10, but it only supports one type ESRI REST.
There are a few reports for the issue from the community:
https://gis.stackexchange.com/questions/352239/geonetwork-3-10-esri-rest-map-view-issue
My DFO co-worker Ian @ianwallen also filed an issue against the hnap …
> Enhance ESRI REST API support

- web-ui/src/main/resources/catalog/components/edit/validationreport/ValidationReportDirective.js
- web-ui/src/main/resources/catalog/components/edit/validationreport/partials/validationreport.html
- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
I noticed UX problem with the validation report.  100% of people using thought it was completely broken.
In order to see the errors, the user must know to press the green/red thumbs-up/thumbs-down icons.
I've set this up so that three things are configurable in the directive;
a) the green thumb up "button" state at the beginning
b) the red thumbs down "button" state at the beginning
c) set the "sections" open/closed at the beginning.
I've set them all to false by default so it would function as-is now.
Previously;
a) green thumbs up ---> NO
b) red thumbs up ---> NO
c) sections open --> YES
Settings should be, for user understanding;
a) green thumbs up ---> YES
b) red thumbs up ---> YES
c) sections open --> NO
I've changed this so that if you don't specify the values, you will get the …
> validation report UX

- core/src/main/java/org/fao/geonet/kernel/Thesaurus.java
- core/src/main/java/org/fao/geonet/kernel/ThesaurusManager.java
- schemas/iso19139/src/main/plugin/iso19139/convert/thesaurus-transformation.xsl
This adds more multilingual dublin core items to the Thesaurus.  This is to make the final metatadata record have more info in the keywords section.
For example, in the RDF;
<skos:ConceptScheme rdf:about="http://geonetwork-opensource.org/thesaurus/naturalearth-and-seavox">
<dc:title>Content Scope</dc:title>
<dc:title xml:lang="en">Content Scope EN</dc:title>
<dc:title xml:lang="fr">Content Scope FR</dc:title>
<dc:publisher xml:lang="en">publisher en</dc:publisher>
<dc:publisher xml:lang="fr">publisher en</dc:publisher>
<dc:description></dc:description>
</skos:ConceptScheme>
In the final json output of thesaurus;
...
"dublinCoreMultilingual": [
{ "lang": "fr","tag":"publisher","value": "publisher fr"},
{"lang": "en","tag":"publisher","value": "publisher en"}
]
...
> add dublin core section to thesaurus

- web-ui/src/main/resources/catalog/components/common/savedselections/partials/action.html
- web-ui/src/main/resources/catalog/components/search/formfields/partials/sortByCombo.html
- web-ui/src/main/resources/catalog/components/search/pagination/partials/pagination.html
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/templateswitcher.html
- web-ui/src/main/resources/catalog/components/search/searchmanager/partials/searchresults.html
- web-ui/src/main/resources/catalog/lib/angular.ext/tabs.js
- web-ui/src/main/resources/catalog/views/default/directives/partials/mdactionmenu.html
This PR adds `href=""` to links and dropdowns to make the elements accessible for keyboards. When you want to access elements on a page with `tab` or `arrow` keys a `<a>` needs to have the `href` attribute.
> Make links and dropdowns keyword accessible

- web-ui/src/main/resources/catalog/views/default/directives/partials/infolist.html
Related to https://github.com/geonetwork/core-geonetwork/issues/4864
Small fix for thumbnails on the homepage containing a space in the URL. Fixed by adding `'`s around the `background-image` styling in the thumbnail.
> [#4864] Fix for thumbnails on the homepage containing a space in the URL

- add-schema.sh
When adding schema's to the code using the add-schema.sh, it can cause some unit test to fail.
See discussion on HNAP schema at the following location.
https://github.com/metadata101/iso19139.ca.HNAP/pull/56#discussion_r450872749
There are 2 options for fixing this issue.
**Option 1** 
Updated GeonetTestFixture.deploySchema so that it only deploys the geonetwork core schemas
**Option 2**
Add schema dependencies
Adding the schema dependencies(Option 2) has the benefit that unit test are being executed on the newly added schema. 
The implementation for option 2 is also easier to implement.
This PR is for option 2.
> Add schema dependency to service module so that unit tests will not fail

- services/src/main/java/org/fao/geonet/api/records/editing/InspireValidatorUtils.java
- services/src/main/resources/config-spring-geonetwork.xml
- services/src/test/java/org/fao/geonet/api/records/editing/InspireValidatorUtilsTest.java
- services/src/test/resources/inspire-validator-test-context.xml
- web/src/main/webResources/WEB-INF/config-spring-geonetwork.xml
- web/src/main/webapp/WEB-INF/config-etf-validator.xml
`InspireValidatorUtils` was configured with some properties in the `config-spring-geonetwork.xml` in services JAR. That meant that for any change in the test suites set or conditions it was needed to uncompress the JAR file,
modify `config-spring-geonetwork.xml` and compress the JAR again.
With this commit a new `WEB-INF/config-etf-validator.xml` file is created in `web` project. This is where the `InspireValidatorUtils` are defined now, avoiding the work of changing the services JAR in case the administrator
would need to change this configuration.
Related to #4568.
> Externalize InspireValidatorUtils configuration

- core/src/main/java/org/fao/geonet/kernel/search/LuceneSearcher.java
User may want to set a portal filter to ` _groupPublished:templates _groupOwner:2234` but currently the `_groupOwner` field is removed. 
It is not a security field has user groups will always be added to the query so there is no reason to exclude it from here.
> Search / Allow searches on `_groupOwner`

- web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
The only case using this was `gn-logo-picker` but was applied to the parent div element.
Other directives related to editor usually needs to be applied to the form element. 
eg. to the input for the language picker.
```xml
<for name="dct:language/@rdf:resource" use="data-gn-language-picker">
<directiveAttributes data-prefix="http://id.loc.gov/vocabulary/iso639-1/"/>
</for>
```
Add support for directive attributes too.
Make this the default for a directive acting on an attribute.
> Editor / Attributes / Add support for directive on form element

- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
eg. 
```xml
<dcat:landingPage/>
<dct:language rdf:resource="http://id.loc.gov/vocabulary/iso639-2/fre"/>
<dct:language rdf:resource="http://id.loc.gov/vocabulary/iso639-2/eng"/>
<dcat:distribution>
```
> Language may be encoded using a prefix before language code

- web-ui/src/main/resources/catalog/components/elasticsearch/EsClient.js
- web-ui/src/main/resources/catalog/components/elasticsearch/EsFacet.js
- web-ui/src/main/resources/catalog/components/elasticsearch/EsService.js
- web-ui/src/main/resources/catalog/components/elasticsearch/directives/FacetDirective.js
- web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facets.html
- web-ui/src/main/resources/catalog/components/search/searchfiltertag/SearchFilterTagsDirective.js
- web-ui/src/main/resources/catalog/components/search/searchfiltertag/partials/searchFilterTagsTemplate.html
- web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/locales/en-v4.json
- web-ui/src/main/resources/catalog/style/gn_search.less
* Add support for negative filter
* Use same translation as facets
* Enable it by default.
If a terms aggregation config declare an include element, an input is displayed to filter facet values.
This is enabled by default on tag which can contain lot of values.
Also fix query was not preserved when clicking more
> Active filter & facet filter / Improvements

- core/src/main/java/org/fao/geonet/kernel/Thesaurus.java
- core/src/test/java/org/fao/geonet/kernel/ThesaurusTest.java
- schemas/iso19139/src/main/plugin/iso19139/index-fields/fn.xsl
- web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
- web-ui/src/main/resources/catalog/components/common/savedselections/SavedSelectionsDirective.js
- web-ui/src/main/resources/catalog/components/elasticsearch/EsFacet.js
- web-ui/src/main/resources/catalog/components/elasticsearch/EsService.js
- web-ui/src/main/resources/catalog/components/elasticsearch/directives/FacetDirective.js
- web-ui/src/main/resources/catalog/components/index/IndexRequest.js
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid.html
- web-ui/src/main/resources/catalog/components/search/searchfiltertag/partials/searchFilterTagsTemplate.html
- web-ui/src/main/resources/catalog/components/search/searchmanager/LocationService.js
- web-ui/src/main/resources/catalog/components/utility/UtilityService.js
- web-ui/src/main/resources/catalog/components/utility/partials/typeinspirevalidationwidget.html
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/locales/en-v4.json
- web-ui/src/main/resources/catalog/style/gn_search.less
- web-ui/src/main/resources/catalog/views/default/templates/searchForm.html
- web/src/main/webResources/WEB-INF/data/config/index/records.json
* Suggestions are based on a search on resourceTitle, Abstract, resourceIdentifier and keyword
* 20 Suggestions returned by default.
* Full text search can now make exact phrase match using `"version 17"`
* Base query can now be customized from the admin
* Default score boost down member of a series and old records
* Active filter / Fix JS warning
* Facet tree / Use a less common separator than '/'.
* Facet / Add support to set collapsed state on load
* Facet / Add example for INSPIRE priority dataset
* Fix searching numbers
* Add tooltip with search hints
* Specific css class for the doc score (not displayed by default)
* Indexing / ResourceIdentifier MUST be part of full text search
* Migrate saved selections directive
> Search improvement

- web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facets.html
See https://stackoverflow.com/questions/57367813/2019-chrome-76-approach-to-autocomplete-off
> ES / Facet / Filter / Disable autofill

- core/src/main/java/org/fao/geonet/util/XslUtil.java
- schemas/iso19139/src/main/plugin/iso19139/loc/ara/schematron-rules-url-check.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/cat/schematron-rules-url-check.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/chi/schematron-rules-url-check.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/dut/schematron-rules-url-check.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/eng/schematron-rules-url-check.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/fin/schematron-rules-url-check.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/ger/schematron-rules-url-check.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/ita/schematron-rules-url-check.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/nor/schematron-rules-url-check.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/pol/schematron-rules-url-check.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/por/schematron-rules-url-check.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/rus/schematron-rules-url-check.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/spa/schematron-rules-url-check.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/tur/schematron-rules-url-check.xml
- schemas/iso19139/src/main/plugin/iso19139/schematron/schematron-rules-url-check.sch
- web-ui/src/main/resources/catalog/components/edit/validationreport/partials/validationreport.html
- web-ui/src/main/resources/catalog/style/gn_editor.less
Instead of only marking URL as invalid, 
... report the HTTP status to the
user. Display URL as hyperlink so user can easily check the status.
Break long URL to avoid horizontal scroll.
> Validation report / Link check / Display status.

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java
In the harvesters log files print the date and time in the timezone set in GeoNetwork settings.
If no timezone is defined use the server default timezone.
The format for the date is ISO 8601 with offset: yyyy-MM-dd'T'HH:mm:ss,SSS±hhmm.
New format:
```
2020-07-31T10:55:13,712+0200 INFO  [test1] - Starting harvesting of test1
2020-07-31T10:55:13,817+0200 INFO  [test1] - Started harvesting from node : test1 (LocalFilesystemHarvester)
2020-07-31T10:55:13,927+0200 INFO  [test1] - Ended harvesting from node : test1 (LocalFilesystemHarvester)
```
Old format:
```
2020-07-31 10:55:13,712 INFO  [test1] - Starting harvesting of test1
2020-07-31 10:55:13,817 INFO  [test1] - Started harvesting from node : test1 (LocalFilesystemHarvester)
2020-07-31 10:55:13,927 INFO  [test1] - Ended harvesting from …
```
> Add a localized time format in harvester logs

- core/src/main/java/org/fao/geonet/web/LocaleRedirects.java
See
https://stackoverflow.com/questions/2291236/how-can-i-prevent-spring-security-from-appending-jsessionid-xxx-to-login-redire
https://docs.spring.io/autorepo/docs/spring-security/4.2.x/apidocs/index.html?org/springframework/security/web/firewall/StrictHttpFirewall.html
Invalidate session for the root redirect so there is no need to carry session info using JSESSION id to the next location.
This change is probably related to Spring Security update. Does not affect 3.x.
> URL `/` redirect / Jsessionid appended to URL

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java
- services/src/main/java/org/fao/geonet/api/records/editing/BatchEditsApi.java
The condition in batch edit must return a boolean.
eg.
```xml
[
{
"condition": "count(.//gmd:fileIdentifier[*/text() = 'da165110-88fd-11da-a88f-000d939bc5d8']) > 0",
"xpath": "/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:descriptiveKeywords[1]",
"value": "<gn_add><gmd:descriptiveKeywords xmlns:gmd=\"http://www.isotc211.org/2005/gmd\" xmlns:gco=\"http://www.isotc211.org/2005/gco\"><gmd:MD_Keywords><gmd:keyword><gco:CharacterString>101</gco:CharacterString></gmd:keyword><gmd:type><gmd:MD_KeywordTypeCode codeList=\"./resources/codeList.xml#MD_KeywordTypeCode\" codeListValue=\"theme\"/></gmd:type></gmd:MD_Keywords></gmd:descriptiveKeywords></gn_add>"
},{
"condition": "count(.//gmd:fileIdentifier[*/text() = '78f93047-74f8-4419-ac3d-fc62e4b0477b']) > 0",
"xpath": …
```
> Harvester / CSW / Fix batch edit condition

- web/src/main/webResources/WEB-INF/config-db/defaultJdbcDataSource.xml
Fix for issue #4833
Issue related to
https://stackoverflow.com/questions/28369582/spring-boot-spring-always-assigns-default-value-to-property-despite-of-it-bein
> Fix issued with using jdbc.port value when set.  #4833

- web-ui/src/main/resources/catalog/components/viewer/layermanager/LayerManagerDirective.js
- web-ui/src/main/resources/catalog/components/viewer/layermanager/partials/layermanageritem.html
In the layer manager of the map, the last of the foreground layers has a disabled 'move down' button, it's greyed out and has a 'disabled' cursor image. However, when you click the button, the layer is still moved down and therefore placed underneath a baselayer.
This PR adds a little JS code to prevent this from happening.
> Fix: Prevent the last layer of moving down.

- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java
Fix bug with geonet baseurl not being correct.
It currently generated a baseurl in geonet:info that looks like the following.
`<baseUrl>http://localhost:8080null</baseUrl>`
The baseURL is never initialized.
This update will change it so that the baseurl looks like the following.
`<baseUrl>http://localhost:8080/geonetwork</baseUrl>`
> Fixed bug uninitialized baseURL

- core/src/main/java/org/fao/geonet/kernel/mef/Importer.java
When loading MEF file containing lots of records. The system could generate an error similar to the following.
```
Failed to import MEF file 'export-full-1593552282553.zip'. Check error for details.
iso19139 is not permitted in the database as a non-harvested metadata. Apply a import stylesheet to convert file to allowed schemas
```
This is difficult to identify the file containing the error within the mef zip file.
This change will modify the error so that we get an error similar to the following.
```
Failed to import MEF file 'export-full-1593552282553.zip'. Check error for details.
Failed to import metadata with uuid '6522e8b8-efbc-4030-add5-4838238bb34d'. iso19139 is not permitted in the database as a non-harvested metadata. Apply a import stylesheet to convert file to allowed schemas …
```
> Improve error message when uploading a mef zip file 

- add-schema.sh
Schema plugins now use `project.version` as per https://github.com/geonetwork/core-geonetwork/issues/4914
> Fix for add-schema services snippet #4914

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
- web-ui/src/main/resources/catalog/templates/editor/editor.html
Both the description and resource name (both multilingual) in the online resource editor get cleared when you change the protocol. 
This ONLY happens in ADD mode (in Edit mode, they don't clear).  This is causing users confusion - they don't like those fields to be reset after they've typed them in.
This PR changes that behavior for ADD mode.  I've created another  configuration for the directive so you can control this.
data-clear-form-on-protocol-change="false"
FALSE (default) -> don't clear
TRUE --> clear (old behavior).
NOTE: This changes the default behavior to "don't clear"
> don't clear the multilingual fields when changing protocol

- core/pom.xml
- core/src/main/java/org/fao/geonet/kernel/security/ldap/AbstractLDAPUserDetailsContextMapper.java
- core/src/main/java/org/fao/geonet/kernel/security/ldap/LDAPRole.java
- core/src/main/java/org/fao/geonet/kernel/security/ldap/LDAPRoleConverter.java
- core/src/main/java/org/fao/geonet/kernel/security/ldap/LDAPRoleConverterGroupNameConverter.java
- core/src/main/java/org/fao/geonet/kernel/security/ldap/LDAPRoleConverterGroupNameParser.java
- core/src/main/java/org/fao/geonet/kernel/security/ldap/LDAPUserDetailsContextMapperWithProfileSearchEnhanced.java
- core/src/main/java/org/fao/geonet/kernel/security/ldap/LdapUserDetailsManager.java
- core/src/main/java/org/fao/geonet/kernel/security/ldap/README.md
- core/src/main/java/org/fao/geonet/kernel/security/ldap/SearchingLdapUsernameToDnMapper.java
- core/src/test/java/org/fao/geonet/kernel/security/ldap/LDAPRoleConverterTest.java
- core/src/test/java/org/fao/geonet/kernel/security/ldap/LDAPUserDetailsContextMapperWithProfileSearchEnhancedTest.java
- core/src/test/resources/org/fao/geonet/kernel/security/ldap/LDAPUserDetailsContextMapperWithProfileSearchEnhancedTest-context.xml
- core/src/test/resources/org/fao/geonet/kernel/security/ldap/README.md
- core/src/test/resources/org/fao/geonet/kernel/security/ldap/apache-directory-studio-security-context.xml
- core/src/test/resources/org/fao/geonet/kernel/security/ldap/data.ldif
- core/src/test/resources/org/fao/geonet/kernel/security/ldap/data_for_Apache_Directory_Studio.ldif
I've added more infrastructure to the LDAP system.  I've only made very minor changes to the existing infrastructure, so I think this shouldn't affect anyone.
The new infrastructure;
a) It much easier to understand and modify using strategy objects and spring configuration
b) has a bunch of test case
* test cases run a pre-configured LDAP server
The main difference between this infrastructure and the old infrastructure is that there are much few assumptions about how the LDAP directory is structures (i.e. it searches for users/group instead of assuming where there are in the directory).
I had a very hard time trying to figure out what the old infrastructure actually did - the documentation was missing, confusing, misleading, or wrong.  There were no test cases, and there was too much work …
> New LDAP test cases and infrastructure

- core/src/main/java/jeeves/config/springutil/JeevesContextLoaderListener.java
It would occur when GN failed to startup correctly - in which case jeevesAppContext was null when it tried to destroy the object.  So there should be a check before attempting to destroy.
> Fixed null pointer error on the jeevesAppContext while destroying object

- web-ui/src/main/resources/catalog/components/thesaurus/ThesaurusService.js
There was a minor issue with language detection when the UI language wasn't already apart of the record (i.e. english-only record, with french ui).
See @fxprunayre  comment in https://github.com/geonetwork/core-geonetwork/pull/4766#pullrequestreview-458965663
cf. https://github.com/geonetwork/core-geonetwork/pull/4766
> better error handling for language detection

- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid.html
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/list.html
- web-ui/src/main/resources/catalog/style/gn_search.less
- web-ui/src/main/resources/catalog/views/default/less/gn_infolist_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_results_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_variables_default.less
- web-ui/src/main/resources/catalog/views/default/templates/results.html
Replaces https://github.com/geonetwork/core-geonetwork/pull/4917 and https://github.com/geonetwork/core-geonetwork/pull/4920
This PR restyles the search results. The aim was to simplify the look of the search page. The `List` and `Grid` are rewritten, a lot of information has been removed from the list items to get a cleaner look.
Furthermore, borders are removed from the toolbar (select, re-order) in order to make it lighter and put more focus on the results than on the toolbar.
Changes:
- rewrite cards and list style
- restyled and repositioned the select option (checkbox)
- 3 columns (was 2) on wider screens
- removed some information to declutter the card and list items
- toolbar buttons without borders
**`Grid` view after the changes**
**`List` view after the changes**
> Restyle search results and search results toolbar

- web-ui/src/main/resources/catalog/components/elasticsearch/EsFacet.js
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/views/default/templates/home.html
* Always gives priority to custom config (inspiretheme and topic config was merged into custom)
* Preserve aggregations meta element in response (see https://www.elastic.co/guide/en/elasticsearch/reference/current/agg-metadata.html)
* Add possibility to create a facet with a custom name and properly
target the proper field
eg. Aggregations on a subset of tag field with a custom label
```json
{
"IDP_DPSIR": {
"terms": {
"field": "tag",
"size": 34,
"include": "IDP_DPSIR.*|IDP_dpsir."
},
"meta": {
"field": "tag"
}
},
"IDP_TOPICS": {
"terms": {
"field": "thesaurus_EEAkeywordlist",
"size": 34,
"include": "IDP_topics.*"
},
"meta": {
"field": "tag"
}
}
}
```
> Home / Aggregation config

- web-ui/src/main/resources/catalog/style/gn_infolist.less
- web-ui/src/main/resources/catalog/views/default/less/gn_infolist_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_results_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_variables_default.less
This PR aims to make `Info blocks` on the homepage look more like the blocks on the results page:
- same font size
- same color
- same title background color on hover
> Make Info blocks on the homepage look more like the blocks on the results page

- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/list.html
- web-ui/src/main/resources/catalog/style/gn_search.less
- web-ui/src/main/resources/catalog/views/default/less/gn_results_default.less
Fix for https://github.com/geonetwork/core-geonetwork/pull/4929#issuecomment-674842278
Improved nesting of `<div>`s to solve the overlapping footer issue in the list view on the results page. 
When there's a lot of content in the list view, there will be a scrollbar.
**Screenshot with scrollbar** (dummy links)
Other changes:
- changed padding and background color for the links in the list view.
- no hover background for list dividers in dropdown menu
> Fix: Improved nesting of DIVS to solve issue of overlapping footer in list items on results page

- web-ui/src/main/resources/catalog/components/search/searchfiltertag/SearchFilterTagsDirective.js
- web-ui/src/main/resources/catalog/components/search/searchfiltertag/partials/searchFilterTagsTemplate.html
- web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js
- web-ui/src/main/resources/catalog/style/gn_search.less
It was not possible to remove a filter once "selection only" was selected.
and long selection are truncated
> Active filter / Add support for UUID when only selection is used.

- core/src/main/java/org/fao/geonet/kernel/security/ldap/AbstractLDAPUserDetailsContextMapper.java
- core/src/main/java/org/fao/geonet/kernel/security/ldap/LDAPUserDetailsContextMapperWithProfileSearchEnhanced.java
- core/src/main/java/org/fao/geonet/kernel/security/ldap/LDAPUtils.java
I noticed there were some differences between (Active Directory) AD and the test LDAP that is used in the test cases.
a) I gave more options for full-name CNs for membership searching
b) I am ignoring PartialResultException 
These occur when you search from the very top of the AD LDAP.
Its, basically, a link that says "go get results from over here."
In almost all cases, you don't need to follow these (but it will throw an exception).
Fixed bug - LDAP sets passwords as '' (empty string).  Oracle interprets '' as NULL.  This causes a constraint error since password cannot be null.  I've replaced '' with a random password.
> LDAP changes for AD and other configurations

- core/src/main/java/org/fao/geonet/kernel/GeonetworkDataDirectory.java
If you put this in your geonetwork.xml (tomcat context file - TOMCATHOME/conf/Catalina/localhost/geonetwork.xml)
\<Parameter name="geonetwork.dir" value="C:\\ProgramData\\GeoNetwork\\Data" type="java.lang.String" override="false"/>
It is now read and used to configure the data directory.  Before it was just getting null (and using the default).
This shouldn't cause any backwards compatibility...
> Allow GeoNetwork datadir from tomcat context Parameter

- web-ui/src/main/resources/catalog/components/utility/UtilityService.js
- web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js
In the admin settings page you can open a table of content on the right side of the page (by clicking the button in the lower right corner). Clicking on one of the links takes you the section in the page. This has a smooth scrolling effect. The section ID is added in the url.
However when you refresh the page, or some other browsing on the page and the menu can get stuck. This prevents you from scrolling in the page.
With some trial and error the problem was in the combination of the animation effect and the ID in the url. Somehow the animation and trying to scroll to the section from the url got stuck in some sort of loop. The animation wasn't finished yet and the script for going to the section in the page was already triggered, causing the scrolling to get stuck. _It is difficult to …
> Fix for the Admin Settings getting stuck

- web-ui/src/main/resources/catalog/templates/editor/batchedit.html
- web-ui/src/main/resources/catalog/templates/editor/import.html
- web-ui/src/main/resources/catalog/templates/editor/new-metadata-horizontal.html
- web-ui/src/main/resources/catalog/templates/editor/new-metadata-vertical.html
This PR creates a uniform look and feel for the contribute pages, same (readable) title, all pages now have a heading 1 (`<h1>`) and same nesting of rows and columns.
> Uniform look for the contribute pages

- web-ui/src/main/resources/catalog/templates/top-toolbar.html
- web-ui/src/main/resources/catalog/views/default/less/gn_navbar_default.less
This PR combines the 2 links (`<a>`) in the top menu in to 1. The GeoNetwork logo and name are now combined into one. According to Accessibility guidelines this is the preferred way (do not have 2 links with the same URL).
> [a11y] Combine GN logo and name in one link in the top menu

- web-ui/src/main/resources/catalog/components/edit/multientrycombiner/partials/multientrycombiner.html
Minor change to the UX for multi-entry-combiner.
If there's only one language, don't show the nav pills for language (there's only one so no reason to).
> don't show language nav-pills if only one language(multi-entry-combiner)

- web-ui/src/main/resources/catalog/js/edit/DirectoryController.js
- web-ui/src/main/resources/catalog/locales/en-editor.json
It is possible to enter manually XML for a `template` when managing a new Directory.
However it is possible to enter invalid XML. When this is done, there is no error message. This PR adds an extra fallback option to show the error message. The contents of the message are also changed to reflect the action done better.
Changes:
- added fallback function
- changed error message
> Show an error message when invalid XML is entered for Manage Directory Template

- web-ui/src/main/resources/catalog/js/GnLocale.js
Related to https://github.com/geonetwork/core-geonetwork/pull/4965
> Locale / Avoid double loading / Fix extra ',' causing Wro4J error

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/common.xsl
Only include details from the first contactInfo element when indexing responsible party's to more align with the way 19139 records are indexed until
until gmMetadataContact is reworked to handle 19115-3:2018 responsible parties
Difficult to handle all possible combinations until that rework is done.
> Addresses metadata101/iso19115-3:2018#87

- web-ui/src/main/resources/catalog/views/default/less/gn_navbar_default.less
This PR fixes the misalignement of the Logo image and GeoNetwork name in the menubar. 
This misalignement was cause by PR: https://github.com/geonetwork/core-geonetwork/pull/4950
> [a11y] Fix for aligning logo and GN name

- web-ui/src/main/resources/catalog/views/default/templates/home.html
Adjust typehead home page full text input behavior, to have same as search page behavior.
When we enter text in the main input, we don't want the first suggestion is selected, cause it takes the lead on the "enter" key press over the search action.
We want, when we enter text and we press "enter" that it performs a search with the entered text, and not on the first typehead suggestion.
> homepage: same typeahead option as in search page

- web-ui/src/main/resources/catalog/components/elasticsearch/EsService.js
Base query is combined with facet with AND operator and needs to be grouped first.
> ES / Search / Wrong query results if query base is using OR

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java
If 2 harvesters are harvesting same records, the second one is on update mode and was not applying its configuration (xpath filter and batch were only applied on addMetadata).
Some users are configuring 2 harvesters on same records to add specific privileges on some of them only.
Also in update mode, if remote record was updated, the new version will not apply batch edits.
> Harvester / CSW / Update / Apply xpath filter and batch edits

- web-ui/src/main/resources/catalog/components/common/map/partials/drawbbox.html
- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
- web-ui/src/main/resources/catalog/components/utility/partials/regionpicker.html
- web-ui/src/main/resources/catalog/style/gn.less
- web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
This PR makes some small UI improvements in the selecting of the bounding box in the editor. A toolbar for the map is made and the `draw` button and `projection` switch are added to this new toolbar.
Another 'delete' style is chosen for the input box because the behaviour of the delete is different form the other fields (only the content is deleted and not the whole row).
And when another type of region is selected via the dropdown, the previous search term is deleted from the input to avoid confusion and wrongfully searched extents.
**Before**:
**After**:
Changes: 
- re-order the UI element
- group elements (add elements to a toolbar for the map)
- change delete icons and couple them to the input fields
- delete the previous search item when switching the region type
- another more …
> UI improvements for the bounding box block in the editor:

- web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
PR for adding classes for `TYPE` to related rows and `add to map` buttons in the Detail/Metadata View.
This PR adds classes for `maintype` to the related rows (downloads, etc) and to the `add` buttons on this row. This enables you to target a specific `maintype`.
An example of a class name: 
```
.gn-relation-type-WFS
```
> Add classes to related rows and add to map buttons in the Detail View

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout-custom-fields-keywords.xsl
When using editor configuration for thesaurus with no fieldset, the override label was not taken into account (the thesaurus name was displayed instead)
```xml
<thesaurus key="local.theme.cersat_latency"
fieldset="false"/>
...
<field xpath="/*/mdb:identificationInfo/*/mri:descriptiveKeywords
[contains(*/mri:thesaurusName/*/cit:title/(gcx:Anchor|gco:CharacterString),
'Cersat - Latency')]"
name="eo-latency"/>
```
eg.
> Schema / 19115-3 / Thesaurus / Override label

- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
- web-ui/src/main/resources/catalog/style/gn_metadata.less
- web-ui/src/main/resources/catalog/templates/editor/editorboard.html
- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
`config-editor.xml` can be used to configure table layout in editor
but it was not use in view mode.
eg.
```xml
<tableFields>
<table for="gmd:CI_ResponsibleParty">
<header>
<col label="gmd:organisationName"/>
```
Render element as table in XSL formatter if configured in editing mode.
* Contact
* Online resource
* Custom editor / Instruments & platforms
> Formatter / Render element as table when configured in edit mode

- schemas/iso19110/src/main/plugin/iso19110/formatter/xsl-view/view.xsl
- schemas/iso19110/src/main/plugin/iso19110/index-fields/default.xsl
- schemas/iso19110/src/main/plugin/iso19110/layout/config-editor.xml
- schemas/iso19110/src/main/plugin/iso19110/layout/layout.xsl
- schemas/iso19110/src/main/plugin/iso19110/loc/eng/codelists.xml
- schemas/iso19110/src/main/plugin/iso19110/loc/fre/codelists.xml
- schemas/iso19110/src/main/plugin/iso19110/loc/fre/labels.xml
- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
- web-ui/src/main/resources/catalog/components/catalog/CatalogService.js
- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
- web-ui/src/main/resources/catalog/locales/en-core.json
- web-ui/src/main/resources/catalog/locales/en-editor.json
* Index / Fix invalid feature type when reserved JSON characters are used
* ISO19110 / Full view / Do not display title & feature type description twice
* ISO19110 / Full view / Do not render empty values
* ISO19110 / Full view / Render list of values as table (like Angular view)
* ISO19110 / Full view / Fix right column layout when empty section
* ISO19110 / Full view / Same contact layout as 19139
* ISO19110 / Full view / Translate codelist
* Formatter in Angular app / Add utility directive to convert a landing page link to an Angular app link (to load the target record in the app instead of opening another tab)
> Formatter improvements (ISO19110 mainly)

- web-ui/src/main/resources/catalog/components/edit/fieldduration/partials/fieldduration.html
In view mode, instead of having inputs with disabled state, switch to plain text. 
Before
After
Editing is the same
> Duration / Keep view mode simple

- domain/src/main/java/org/fao/geonet/domain/AbstractMetadata.java
- web/src/main/webResources/WEB-INF/config-db/database_migration.xml
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v3990/UpdateAllSequenceValueToMax.java
Improvement proposed by @ianwallen in
https://github.com/geonetwork/core-geonetwork/pull/4781
With the JPA update in v4, it looks like the sequence were created even with the old
configuration of the domain classes. The migration use the `sequenceName` or `name` attribute to set
the new value.
The process can be triggered from the API documentation page with the
step name `v3990.UpdateAllSequenceValueToMax`.
The process is somehow slow due to the fact that there is no generic SQL
statement for updating the current sequence value. Iterating can take
time. In case of proxy timeout, the process can be restarted and it will
continue.
> DB / Migration / Add step to set sequence value to current.

- schemas/dublin-core/src/main/plugin/dublin-core/formatter/xsl-view/view.xsl
- schemas/dublin-core/src/main/plugin/dublin-core/layout/layout.xsl
- schemas/dublin-core/src/main/plugin/dublin-core/layout/utility-tpl.xsl
- schemas/iso19110/src/main/plugin/iso19110/formatter/xsl-view/view.xsl
- schemas/iso19110/src/main/plugin/iso19110/layout/layout.xsl
- schemas/iso19110/src/main/plugin/iso19110/layout/utility-tpl.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/config-editor.xml
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/utility-tpl-multilingual.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/update-fixed-info.xsl
- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
- schemas/iso19139/src/main/plugin/iso19139/layout/utility-fn.xsl
- schemas/iso19139/src/main/plugin/iso19139/layout/utility-tpl-multilingual.xsl
- services/src/main/java/org/fao/geonet/api/records/formatters/SchemaLocalizations.java
- web-ui/src/main/resources/catalog/js/GnLandingPageLib.js
- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-variables.xsl
- web/src/main/webapp/xslt/common/render-html.xsl
- web/src/main/webapp/xslt/common/utility-tpl.xsl
- web/src/main/webapp/xslt/services/sitemap/sitemap.xsl
Landing page is displayed by default taking into account the Accept-Language of the browser. Then translations are displayed depending on that language if available. A specific language can be forced using the `language` parameter but the user does not know in which languages the record is described by default.
The `language=all` parameter can now be set to return the record description in all languages used in the record. 
All element language is identified by using `xml:lang` attribute.
A language switcher allows to display one language or all translations.
The HTML page meta is improved by providing `link` to all translations page representing the same resource (as described in https://support.google.com/webmasters/answer/189077). Search engine will be aware that different pages …
> Landing page / Improve multilingual support

- web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
In the editor, enable `More details` option to display the attributes.
Some elements display an empty section if the element has no attributes available:
Changed to avoid displaying the attributes block in these cases:
> Avoid empty attribute sections in the metadata editor

- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataIndexer.java
- core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
- es/README.md
- pom.xml
- web/src/main/webResources/WEB-INF/data/config/index/records.json
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v3990/migrate-default.sql
* Indexing / Avoid losing records using a non registered schema.
Instead of only reporting exception in the log, check first that schema
of the record is available. If not create a document with an indexing
error status:
```
2020-09-16 15:38:36,365 ERROR [geonetwork.datamanager] - Record 163548661 / Schema 'iso19115-3' is not registerd in this catalog. Install it or remove those records. Record is indexed indexing error flag.
```
This is useful when using a database with records in non default
standards.
* Indexing / Multithread indexing is not supported.
* Indexing / Explain what to do in case of Limit of total fields has been exceeded.
> Indexing / improvements and doc

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java
Previous implementation with `RollingFileAppender` created a new log file for a harvester if this start running and the execution goes beyond midnight. With this change all the output related to a harvester execution is kept in the same log file.
Reference: https://sourceforge.net/p/geonetwork/mailman/geonetwork-users/thread/CAEOgqt%2BiYnjP%2B8VLuk%3D83qVwitBupJq9Zy_8iQXUsXe6ztGy8w%40mail.gmail.com/#msg37084379
> Don't rotate harvester log files if a harvester is running during midnight

- services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
Add a check at the metadata import API to report a user-friendly message instead of blank to the client console upon the event when importing did not succeeded due to somehow the invalid metadata archive.
Discussed with @ianwallen and we decided to submit this PR to address the importing invalid MEF issue our user reported to us. In a word, if the provided MEF file is invalid, the importing task complete without warning nor any information. GN should warn the user the importing is incomplete with some descriptive information. 
Before the change (note the blank message) at the red circle area:
After the change:
We like this PR, if approved, be ported into 3.10.4 milestone if possible. Thanks!
> User-friendly message for metadata importing

- core/src/main/java/org/fao/geonet/api/records/attachments/ResourceLoggerStore.java
Fixed bug where it was supplying the resourceId which was the simple filename and it would use this to query the database and never found the result because the database contains more than just the base filename. Changed it to get the getId() function which returns the same format as the filename stored in the database.
> Fixed bug with assigning resources to a metadata record.

- web-ui/src/main/resources/catalog/components/cookieWarning/partials/cookieWarning.html
- web-ui/src/main/resources/catalog/views/default/less/gn_layout_default.less
There were small issues with displaying the cookie message, it falls behind the map, and can't be closed with the keyboard. This PR fixes both issues.
**The cookie message after the changes**:
Changes:
- change`<span>` elements into `<button>`s
- add a `z-index` to display the cookie message on top of other elements
> [a11y] Improve the cookie message

- schemas/iso19110/src/main/plugin/iso19110/layout/layout.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout.xsl
- schemas/iso19139/src/main/plugin/iso19139/layout/layout.xsl
This occurs only when adding a new element that uses a directive, causing to add the `geonet:info` information as part of the directive attribute value. In fields using standard HTML controls seem fine.
```
<span data-gn-field-duration-div="136iso191392020-09-22T16:09:082020-09-22T16:38:23n692bc013-e858-4e22-9093-8f05da3b87769fe0d837-...." data-ref="_185"  ...>
```
If the attribute value is used in the directive causes rendering issues.
With this change when adding an element the `geonet:info` information is ignored as expected:
```
<span data-gn-field-duration-div="" data-ref="_185"  ...>
```
> Metadata editor - ignore elements with geonet namespace for render-element value parameter

- web-ui/src/main/resources/catalog/components/metadataactions/RelatedResourcesService.js
- web-ui/src/main/resources/catalog/components/search/searchmanager/LocationService.js
- web-ui/src/main/resources/catalog/components/viewer/ViewerDirective.js
- web-ui/src/main/resources/catalog/components/viewer/partials/mainviewer.html
- web-ui/src/main/resources/catalog/components/viewer/partials/mouseposition.html
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/locales/en-core.json
- web-ui/src/main/resources/catalog/locales/en-search.json
- web-ui/src/main/resources/catalog/style/gn_viewer.less
- web-ui/src/main/resources/catalog/views/default/module.js
* Mouse position is not displayed by default 
* Mouse position is displayed below gazetter
* User can choose projection and format based on projection list
configuration
* WGS84 can be displayed in DD or DMS mode
* `c` shortcut can be used to copy current mouse cursor location
* Coordinates can be used to zoom to location using gazetter
* Map / When loading a map, display legend panel by default
* Home page / Latest maps / Fix click to load the map
> Map / Add mouse position widget.

- web-ui/src/main/resources/catalog/components/common/map/esriService.js
- web-ui/src/main/resources/catalog/components/common/map/mapService.js
- web-ui/src/main/resources/catalog/components/common/map/print/PrintMapDirective.js
- web-ui/src/main/resources/catalog/components/common/map/print/PrintMapService.js
- web-ui/src/main/resources/catalog/components/common/map/print/partials/printmap.html
- web-ui/src/main/resources/catalog/components/viewer/gfi/FeaturesLoader.js
- web-ui/src/main/resources/catalog/components/viewer/gfi/GetFeatureInfoDirective.js
- web-ui/src/main/resources/catalog/components/viewer/layermanager/LayerManagerDirective.js
- web-ui/src/main/resources/catalog/components/viewer/layermanager/partials/layermanageritem.html
- web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextService.js
- web-ui/src/main/resources/catalog/locales/en-search.json
This PR improves the support for ArcGIS layers in the map viewer in the following ways:
* fix broken visibility/opacity changes
* layer title and extent are read from the REST API
* generates a image legend dynamically
* returns results on map click (similar to GetFeatureInfo for WMS layers)
* ArcGIS layers can be read from and written to an OWS context, meaning they will not disappear when reloading the page
* MapFish Print does not support these layers; as such, a warning was added in the print panel when such a layer is present:
* The download option in the layer tree was removed for these layers as data download is not supported yet:
Here is an example URL for testing purposes: https://air.discomap.eea.europa.eu/arcgis/rest/services/AirQuality/AirQualityZones/MapServer (note that this …
> Map / Improve support for ESRI ArcGIS REST layers

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl
> ISO19115-3 / Formatter / Missing uom attribute when rendering Distance.

- schemas/iso19139/src/main/plugin/iso19139/convert/functions.xsl
Fix bug with defaultTitle and defaultAbstract where #lang was being selected based on 2 char lang code when it should be using the gmd:locale
Metadata using #fra with gmd:locale id as fra was failing to translate and defaultTitle and defaultAbstract was always the main language.
Kept old 2 char lang conversion for cases where the gmd:locale is not found.  But not sure if we really need to keep this? I cannot think of any cases where it would be needed.
> ISO19139: Fix bug with defaultTitle and defaultAbstract 

- schemas/iso19139/src/main/plugin/iso19139/formatter/jsonld/iso19139-to-jsonld.xsl
fixes #4872
- if license is a url, use it else introduce it as a creative work (license as text fails in ggl)
- split out contacts to multiple roles (try to use at least 1 creator, recommended by ggl)
> impr iso19139 jsonld formatter

- schemas/iso19115-3.2018/README.md
This is no longer needed as the schema plugin is included in core-geonetwork.
> remove iso19115-3.2017 installation instructions

- web/src/main/webapp/xslt/services/inspire-atom/opensearch.xsl
seems the 'filter' string is not suggested by TG, in stead use {searchTerm?}
/searchhtml?any= currently does not return html, but xml, so using general html search for now, for html results
> impr open search desc

- services/src/main/java/org/fao/geonet/api/records/MetadataUtils.java
Without this fix, if the dataset uuid is empty in the `srv:operatesOn` the Lucene query send empty value for the uuid, retrieving all elements.
> Get related datasets - ignore if the dataset uuid is empty. Related to #4844

- services/src/main/java/org/fao/geonet/api/records/formatters/ImageReplacedElementFactory.java
We encountered the issue on geOrchestra, following an update of spring-security in our proxy placed in front of geonetwork.
Since spring-security 4.2.4, a stricter filter than the default one is defined by default, see the following class:
https://docs.spring.io/spring-security/site/docs/4.2.15.RELEASE/apidocs/org/springframework/security/web/firewall/StrictHttpFirewall.html
> Rejects URLs that are not normalized to avoid bypassing security constraints. There is no way to disable this as it is considered extremely risky to disable this constraint. A few options to allow this behavior is to normalize the request prior to the firewall or using DefaultHttpFirewall instead. Please keep in mind that normalizing the request is fragile and why requests are rejected rather than normalized.
When …
> pdf - normalize URL before openStream()

- web-ui/src/main/resources/catalog/style/gn_viewer.less
> Map / Set background to avoid to display custom catalog background 

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/utility-tpl-multilingual.xsl
- web/src/main/webapp/xslt/common/base-variables-metadata.xsl
* Avoid creating empty language when list of language is built in edit mode (due to geonet:* elements)
* Record isMultilingual only if none default language are defined.
> ISO19115-3 / Fix multilingual editing.

- domain/src/main/java/org/fao/geonet/domain/ISODate.java
- domain/src/test/java/org/fao/geonet/domain/ISODateTest.java
For more information see https://github.com/geonetwork/core-geonetwork/issues/5016
> ISODate UTC timezone fixes

- core/src/main/java/org/fao/geonet/kernel/EditLib.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataUtils.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java
https://github.com/geonetwork/core-geonetwork/blob/582d49f0f5791452a39eaacacce7699e3a807866/core/src/main/java/org/fao/geonet/kernel/EditLib.java#L93-L98
The versions map was done static in https://github.com/geonetwork/core-geonetwork/commit/e8cd87abdf07f7839b65d5c2c326465f30827ea1, what seem fine, but the constructor should not clear it. `EditLib` is instantiated in several places, among others in the CSW harvester when are configured batch editing values. 
https://github.com/geonetwork/core-geonetwork/blob/582d49f0f5791452a39eaacacce7699e3a807866/harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java#L364
The code  cleanups the map with all the edit sessions and if a user was editing the metadata while the harvester is executed and tries to save the metadata, …
> Don't cleanup versions map in EditLib constructor as it's a static resource shared between all the EditLib instances

- core/src/main/java/org/fao/geonet/kernel/IndexMetadataTask.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataIndexer.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java
- core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
- core/src/main/java/org/fao/geonet/kernel/search/index/BatchOpsMetadataReindexer.java
- core/src/main/java/org/fao/geonet/kernel/search/index/IndexingTask.java
- index/src/main/java/org/fao/geonet/index/es/EsRestClient.java
- services/src/main/java/org/fao/geonet/api/es/EsHTTPProxy.java
- services/src/main/java/org/fao/geonet/api/records/editing/MetadataEditingApi.java
- services/src/test/java/org/fao/geonet/services/metadata/BatchOpsMetadatReindexerTest.java
* Avoid lock - when synchronizeDbWithIndex was triggered, editing a metadata was waiting for the lock
* Remove indexing list in data manager - Now EsSearchManager is in charge of indicating if indexing is in progress or not
* Avoid sharing of the batch list of document (may make multithread indexing to work - need more test)
* former forceRefreshReaders now trigger index of one document directly
* batch indexing trigger final batch indexing at the end if needed.
> Indexing / Improvements

- schemas/dublin-core/src/main/plugin/dublin-core/formatter/xsl-view/view.xsl
- schemas/iso19110/src/main/plugin/iso19110/formatter/xsl-view/view.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
- schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
- web-ui/src/main/resources/catalog/components/catalog/CatalogService.js
- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/js/GnSearchModule.js
- web-ui/src/main/resources/catalog/locales/en-v4.json
- web-ui/src/main/resources/catalog/style/gn_metadata.less
- web-ui/src/main/resources/catalog/style/timeline.less
- web-ui/src/main/resources/catalog/views/default/templates/recordView.html
- web/src/main/webResources/WEB-INF/data/config/index/records.json
In ISO19115-3, the resource lifecycle can capture a number of different type of dates (see https://github.com/geonetwork/core-geonetwork/blob/master/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/eng/codelists.xml#L76-L177). Improve the record view in order to display all types of date using a timeline layout and highlight some of them with specific icons.
Also improve temporal extent and add vertical extent.
Add a UI settings to define date format (which will be further improved with https://github.com/geonetwork/core-geonetwork/issues/1970)
@MichelGabriel you may have better ideas for icons & layout?
> Record view / Use timeline to render resource events, temporal extent and vertical extent

- web-ui/src/main/resources/catalog/components/common/map/esriService.js
- web-ui/src/main/resources/catalog/components/common/map/mapService.js
* Fix legend rendering causing `unsafe:data:,` warning in browser when looking for legend.
* Make a 1px image even if layer is not found
* Support various encoding 
* A custom name (not targeting any layers)
* A layer id
* An invalid layer id will render the service
* No layer, render based on the URL 
```xml
<gmd:onLine>
<gmd:CI_OnlineResource>
<gmd:linkage>
<gmd:URL>https://land.discomap.eea.europa.eu/arcgis/rest/services/Land/Major_and_medium_anthropogenic_fragmentation_effective_mesh_density/MapServer</gmd:URL>
</gmd:linkage>
<gmd:protocol>
<gco:CharacterString>ESRI:REST</gco:CharacterString>
</gmd:protocol>
<gmd:name>
<gco:CharacterString>Effective mesh density FG2 (5)</gco:CharacterString>
</gmd:name>
<gmd:function>
<gmd:CI_OnLineFunctionCode …
```
> Map / ESRI REST / Support encoding with or without layer name

- web-ui/src/main/resources/catalog/components/thesaurus/ThesaurusService.js
Don't asume that ThesaususService is always used inside the editor.
> Allow the use of ThesaurusService in search page

- web/src/main/webResources/WEB-INF/data/config/index/records_french.json
Add stop word filter to not take into account "de", "la", "les", "ceci", "cela", ...
> Index / French / Add stop word and fix synonym init.

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
Add missing fields which is used to navigate in the 2 directions for the associated resources (eg. crossReference).
> Associated resources / Link in the 2 directions

- web/src/main/webapp/xslt/services/metadata/relation.xsl
Related to https://github.com/geonetwork/core-geonetwork/pull/2333
Can be tested with http://localhost:8080/geonetwork/srv/api/records/189/related?type=fcats
List of values was not returned.
See https://github.com/geonetwork/core-geonetwork/blob/master/services/src/main/java/org/fao/geonet/api/records/model/related/FCRelatedMetadataItem.java#L254 for the model
> Associated resource / Feature catalog / Missing list of values

- schemas/iso19139/src/main/plugin/iso19139/loc/fre/codelists.xml
Only make sense when the number of values is limited.
> ISO19139 / Codelist / FR / Hierarchy level / Don't use radio mode

- web/src/main/webapp/WEB-INF/config-etf-validator.xml
Class 2b is used for the Monitoring (see https://github.com/inspire-eu-validation/metadata/tree/2.0/monitoring) and checks for spatial scope and priority dataset.
Set TG2 as default.
> Validation / INSPIRE / Add configuration for Conformance Class 2b

- web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facet.html
For keywords, duplicates may popup in facets (due to the KeywordAnalyzer - maybe something to improve). 
User can not really figure out why without having the possibility to see the index value without the client side capitalize filter.
Note that the facet filter is also case sensitive for now (see Elasticsearch doc) but Regex can be use eg. `[Ll]and` even if can be slow.
> Facet / Do not capitalize the title

- core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
- web-ui/src/main/resources/catalog/templates/admin/dashboard/status.html
* Add db id (which will be used to open editor). 
* Add isTemplate field which is checked when opening the editor.
* Add link to the editor in XML mode (usually if there is indexing error, editor XSLT also fails for similar reason. XML mode usually is ok to open whatever messy records eg. invalid date formats)
> Indexing / Error / In case of ES error create a better error document

- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-functions.xsl
- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-variables.xsl
Xslt formatter is not resolving names like: ` <section name="gmd:MD_Metadata">` to display the element label (as the editor does), instead displays the value `gmd:MD_Metadata`.
For example, PDF export:
> Xslt formatter - resolve section names with meteadata element names using labels.xml

- services/src/main/java/org/fao/geonet/api/processing/EmptySlotBatch.java
On some setup INSPIRE validation does not start (at some point? - not sure when/why). Exceptions raised are: 
```
stacktrace: "javax.management.InstanceNotFoundException: 
No MBean with pattern geonetwork:name=batch-etf-inspire,idx=* found for reading attributes
at org.jolokia.handler.ReadHandler.searchMBeans(ReadHandler.java:160)
{"message":"BeanCreationException","code":"runtime_exception",
"description":"Error creating bean with name 'processValidate':
Invocation of init method failed; nested exception is org.springframework.jmx.export.UnableToRegisterMBeanException: 
Unable to register MBean [org.fao.geonet.api.processing.EmptySlotBatch@5998544c] 
with object name [geonetwork:name=' + name + ',idx=empty-slot-0]; nested exception is
javax.management.InstanceAlreadyExistsException: …
```
> Validation / Inspire / Slot name

- csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/FieldMapper.java
Even if a field is not defined in the queryable mapping in `config-csw.xml` we used to support querying by any index fields.
eg. query all public records with `isPublishedToAll` http://localhost:8080/geonetwork/srv/eng/csw?request=GetRecords&service=CSW&version=2.0.2&namespace=xmlns(csw=http://www.opengis.net/cat/csw/2.0.2),xmlns(gmd=http://www.isotc211.org/2005/gmd)&resultType=results&&constraintLanguage=CQL_TEXT&constraint_language_version=1.1.0&typeNames=gmd:MD_Metadata&outputSchema=http://www.isotc211.org/2005/gmd&ElementSetName=full&constraint=isPublishedToAll%3D%27true%27
> CSW / Restore the possibility to query any index fields

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/doi-add.xsl
- schemas/iso19139/src/main/plugin/iso19139/process/doi-add.xsl
As the DOI is a permanent identifier, a common practice is
to store the DOI as a resource identifier instead of
a link in distribution section.
Add support for ISO19115-3 too.
Relates to https://github.com/geonetwork/core-geonetwork/pull/3281
> DOI / Store it as resource identifier.

- web-ui/src/main/resources/catalog/style/gn_metadata_pdf.less
Small fix and style improvements for the PDF output. Sometimes the table cell is empty which results in a lower table row, which in turn breaks the layout (because it's a `<dd>` and `<dl>` looking like a table cell).
This PR adds a minimum height, so the layout stays intact when the cell is empty
**Broken layout**
Changes:
- minimum height for table cells (fix for empty cells)
- border and line-height for contacts
> Small fix and style improvements for the PDF output

- web/src/main/webResources/WEB-INF/config-db/database_migration.xml
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v3103/migrate-default.sql
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v3103/migrate-mysql.sql
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v3103/migrate-oracle.sql
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v3104/migrate-default.sql
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v3110/migrate-default.sql
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v3110/migrate-mysql.sql
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v3110/migrate-oracle.sql
Add missing migration scripts from 3.10.x releases.
Looks like it was not updated in the last releases.
Without these changes if attempting to migrate from 3.10.4 to current master branch there will be some errors.
i.e. 
```
org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PRIMARY_KEY_842 ON PUBLIC.SETTINGS(NAME) VALUES ( /* 138 */ 'system/server/timeZone' )"; SQL statement:
INSERT INTO Settings (name, value, datatype, position, internal) VALUES ('system/server/timeZone', '', 0, 260, 'n') [23505-174]
```
See the following for more details.
https://github.com/geonetwork/core-geonetwork/pull/4817#issuecomment-706148783
> Add missing 3.10 migration script

- core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
- core/src/main/resources/config-spring-geonetwork.xml
- core/src/test/resources/core-repository-test-context.xml
If not using `gn-records`, user may have issue reindexing if restrictions are set on ES side.
> Index / Set default index properly if custom name is used.

- web-ui/src/main/resources/catalog/views/default/module.js
Reported by some users, it may make more sense to display last created records under "latest news" instead of last updated records.
@archaeogeek , @pvgenuchten , do you think it is a better default?
> Home / Latest news = Last created records

- web-ui/src/main/resources/catalog/templates/top-toolbar.html
- web-ui/src/main/resources/catalog/views/default/less/gn_navbar_default.less
This PR fixes the 'empty' user icon on small screens. See https://github.com/geonetwork/core-geonetwork/issues/5145
The top toolbar is reworked so the user name is always shown, the other labels are hidden on smaller screens but the icons stay visible (like the edit toolbar).
This was needed because when an empty string for the gravatar is chosen, there is a blank image used as user icon, this empty blank icon was shown on smaller screens and the label with the user name was hidden, resulting in an empty `menu item.
**The toolbar on small screens after the fix**
> [#5145] Fix for the 'empty' user icon on small screens

- services/src/main/java/org/fao/geonet/api/regions/ListRegionsResponse.java
It looks like some tools used to generate client from the API does not make distinction between `id` and `@id` which BTW was the same thing. So keeping this simple.
```
'@id':
type: string
xml:
attribute: true
id:
type: string
``` 
After
```
RegionResponse: {
type: "object",
properties: {
north: {
type: "number",
format: "double"
},
east: {
type: "number",
format: "double"
},
south: {
type: "number",
format: "double"
},
west: {
type: "number",
format: "double"
},
label: {
type: "object",
additionalProperties: {
type: "string"
}
},
hasGeom: {
type: "boolean",
xml: {
attribute: true
}
},
categoryId: {
type: "string",
xml: {
attribute: true
}
},
id: {
type: "string",
xml: {
attribute: true
}
}
}
},
```
Related to https://github.com/geonetwork/geonetwork-ui/pull/46
> API / Region / Avoid similar property in model

- web-ui/src/main/resources/catalog/components/usersearches/UserSearchesDirective.js
- web-ui/src/main/resources/catalog/components/usersearches/UserSearchesService.js
- web-ui/src/main/resources/catalog/js/CatController.js
Usually portals define a search filter and allow quick access to a subset of records. It is quite similar to a user searches and lots of users are duplicating portal definition in user searches. To avoid this, add an option to append portal list to the usersearches list.
They are also combined in the home page panel.
Portals are only displayed as user searches in the default node srv
> User searches / Add portals with filter in the list.

- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java
Update date format in title to contain the time zone as ISO 8601 GMT.  This will help eliminate confusion as to when the template/metadata was created.
This is related to #4752
Before the change - the title when creating a new metadata record would be something like the following.
`Copy of template Template for Vector data in ISO19139 created at 2020-11-02 15:39:38`
After the change, it should be something similar to the following.
`Copy of template Template for Vector data in ISO19139 created at 2020-11-02T15:39:38Z`
> create metadata/template title - add timezone GMT

- services/src/main/java/org/fao/geonet/api/registries/vocabularies/KeywordsApi.java
- web-ui/src/main/resources/catalog/components/admin/registry/RegistryDirective.js
- web-ui/src/main/resources/catalog/components/admin/registry/RegistryService.js
- web-ui/src/main/resources/catalog/components/admin/registry/partials/registrybrowser.html
- web/src/main/webapp/xslt/services/thesaurus/ldregistry-to-skos.xsl
- web/src/main/webapp/xslt/services/thesaurus/registry-to-skos.xsl
Add support for thesaurus import from LD Registry (https://github.com/UKGovLD/registry-core). Mechanism is similar to re3gistry software. The list of available codelists are retrieved and then imported by conversion to SKOS.
Also fix https://github.com/geonetwork/core-geonetwork/issues/4836 related to re3gistry path.
Support simple flat list of keywords:
and hierarchy:
Thesaurus created is composed of:
* concept scheme
* top concepts
* keywords with narrower/broader relations
> Thesaurus / Import from Linked Data Registry (LDRegistry).

- domain/src/main/java/org/fao/geonet/domain/MessageProducerEntity.java
- web/src/main/webResources/WEB-INF/config-db/database_migration.xml
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v400/UpdateAllSequenceValueToMax.java
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v402/SetSequenceValueToMaxOfMessageProducerEntity.java
In Oracle 11g the identity method for the id column doesn't work and the table isn't create. This commit changes the class to use a sequence instead and adds a migration to set the next value of the sequence to the max value of the id in the table.
The migration reuses part of the login used in `v400.UpdateAllSequenceValueToMax` migration.
Discovered in #5141.
> Use sequence for MessageProducerEntity id

- schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields.xsl
Don't remove geographic description for multilingual data since the widget does not support multilingual data.
For more information on this issue see the following related issue.
https://github.com/metadata101/iso19139.ca.HNAP/issues/122
> Don't remove geographic description for multilingual data 

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
- schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
- web-ui/src/main/resources/catalog/components/catalog/CatalogService.js
- web-ui/src/main/resources/catalog/components/viewer/wfsfilter/WfsFilterDirective.js
* Default is replace wms by wfs in URL and expect to have a feature type with same name as layer
* Force a wfsURL with 'scope'
* Use 'group' to check if a WFS is defined in the same transfert option group in the metadata record.
The benefit of the last mode is that user can use applicationProfile to customize the widget and the indexing:
* column labels
* field with hierarchy
* date graph
eg.
```json
{
"tokenizedFields": {
"PROGRAMMES": ";",
"PARAMETRES": ";",
"SUPPORTS_NIVEAUX_PRELEVEMENT": ";"
},
"fields": [{
"name": "PROGRAMMES",
"label": {
"fr": "Programme de suivi",
"en": "Programme de suivi"
}
}, {
"name": "PARAMETRES",
"label": {
"fr": "Paramètre",
"en": "Paramètre"
}
}, {
"name": "range_Date",
"type": "rangeDate",
"minField": "RESULTAT_DATE_MIN",
"maxField": "RESULTAT_DATE_MAX", …
```
> WFS indexing / Add 3 modes for WFS url detection.

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout.xsl
> Fixes #5186 - gmx:MimeFileType should be gcx:MimeFileType

- services/src/main/java/org/fao/geonet/api/processing/ValidateApi.java
Prior to this fix the report with errors on a metadata record will look like this.
```
{
"errors": [],
"infos": [],
"uuid": "3d420e57-7ecb-47ad-b8d6-068083bd0b63",
"metadata": [
18865,
17847
],
"metadataErrors": {},
"metadataInfos": {
"17847": [
{
"message": "Is invalid",
"date": "2020-11-05T13:53:52"
}
],
"18865": [
{
"message": "Is valid",
"date": "2020-11-05T13:53:57"
}
]
},
"numberOfRecordNotFound": 0,
"numberOfRecordsNotEditable": 0,
"numberOfNullRecords": 0,
"numberOfRecords": 0,
"numberOfRecordsProcessed": 2,
"numberOfRecordsWithErrors": 0,
"startIsoDateTime": "2020-11-05T13:53:48",
"endIsoDateTime": "2020-11-05T13:54:07",
"ellapsedTimeInSeconds": 19,
"totalTimeInSeconds": 19,
"running": false,
"type": "SimpleMetadataProcessingReport"
}
```
Notice that even though there were …
> Fix bug in validation report where errors are not identified as errors

- web-ui/src/main/resources/catalog/components/search/map/MapFieldDirective.js
- web-ui/src/main/resources/catalog/components/search/map/partials/mapfield.html
- web-ui/src/main/resources/catalog/views/default/module.js
This PR adds some (small) improvements to the mini map on the search page.
The changes are:
- extra render option to prevent blank map on startup
- extra option to enable/disable direct search with extent (defaults to `true`)
- add `type="button"` to minimap buttons
> Small improvements to the MiniMap

- web-ui/src/main/resources/catalog/components/viewer/wfs/partials/download.html
When a metadata record has WFS downloads, and if in the WFS capabilities there happen to be double/duplicate keys, the dropdown fails. It's breaks on these duplicate values.
This PR fixes this error by adding a `track by` to distinguish between same keys.
> Fix for WFS download dropdown in Record view

- domain/src/main/java/org/fao/geonet/repository/specification/UserGroupSpecs.java
When loading sample data from a template it set the groupowner to null.
If we then attempt to publish that record it will generate a null pointer because one of the queries does not support null values for the group.
This PR corrects that bug.
In general the groupowner should not be null. Maybe a better fix would be to make the groupowner field not null and correct sample data load to go into a group. That is a bigger fix so in the meantime, this will work.
> Fix null group bug if attempting to publish sample data.

- core/src/main/java/org/fao/geonet/api/records/attachments/StoreUtils.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/draft/DraftMetadataUtils.java
- services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
- services/src/main/java/org/fao/geonet/services/metadata/Create.java
Fixes issue #5214
store.delResources was not passing the correct approved flag.
Also fixed issue related to creating a working copy. It was not copying the resources correctly to the new metadata record. Wrong approved flag was being passed.
> Fix bug related to canceling working copy removes approved resource (#5214)

- services/src/main/java/org/fao/geonet/api/processing/MInspireEtfValidateProcess.java
- services/src/main/java/org/fao/geonet/api/processing/ValidateApi.java
- services/src/main/java/org/fao/geonet/api/records/InspireValidationApi.java
- services/src/main/java/org/fao/geonet/api/records/editing/InspireValidatorUtils.java
- web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/selection-widget.html
- web-ui/src/main/resources/catalog/components/validationtools/GnmdInspireValidationDirective.js
- web-ui/src/main/resources/catalog/components/validationtools/partials/mdValidationTools.html
- web-ui/src/main/resources/catalog/locales/en-v4.json
Current validation mechanism always upload the record first. Default mode is unchanged.
Add a mode parameter to the API (on one record or on a selection) to define the encoding of the record to use:
* By default, ISO19139 are used as is and others like ISO19115-3 are converted to ISO19139 if a formatter is available.
* If mode = csw, a GetRecordById request pointing to the main portal is used.
* If mode = any portal id, then a GetRecordById request is used on this portal.
CSW entry point which may define custom CSW post processing. See https://github.com/geonetwork/core-geonetwork/pull/4493.
When using CSW mode, the record has to be publicly accessible for the validator to retrieve it.
Add also an API operation to clear current validation status.
> INSPIRE Validation / Add support to validate using GetRecordById url

- web-ui/src/main/resources/catalog/style/gn_admin.less
Fix for https://github.com/geonetwork/core-geonetwork/issues/5234
In the latest version(s) of the Chrome browser the CSW Harvester filter settings list was overflowing. This PR adds a small fix to prevent this.
**No more overflow:**
> [#5234] Fix for overflowing CSW Harvester filter list

- web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextService.js
- web-ui/src/main/resources/catalog/components/viewer/wps/WpsService.js
It is usually good practice to indicate CRS of coordinates
```
<wps:DataInputs>
<wps:Input>
<ows:Identifier>bbox</ows:Identifier>
<wps:Data>
<wps:BoundingBoxData dimensions="2" crs="EPSG:4326">
<ows:LowerCorner>0.237 40.562</ows:LowerCorner>
<ows:UpperCorner>14.593 44.55</ows:UpperCorner>
</wps:BoundingBoxData>
</wps:Data>
</wps:Input>
```
Also fix issue on map context loading if layername is undefined.
> Map / WPS / Set crs attribute of wps:BoundingBoxData.

- web-ui/src/main/resources/catalog/components/usersearches/partials/featuredusersearchesbutton.html
- web-ui/src/main/resources/catalog/components/usersearches/partials/featuredusersearchescards.html
- web-ui/src/main/resources/catalog/style/gn_search.less
* If portal use a description, use it as tooltip.
* Adjust menu size to text
.
Before was:
> User search improvement.

- web-ui/src/main/resources/catalog/components/common/map/mapService.js
- web-ui/src/main/resources/catalog/components/viewer/wmsimport/WmsImportDirective.js
Some WMS implementations do not provide capLayer.url and fails with
```
`TypeError: Cannot read property 'slice' of null at Object.createOlWMSFromCap`
```
eg. http://www.ifremer.fr/erddap/wms/HF_600e_f9ff_938e/request?service=WMS&request=GetCapabilities
Fallback to use the capabilities URL provided by the user in that case.
> Map / WMS / Erdapp server support.

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/tpl-csv.xsl
- schemas/iso19139/src/main/plugin/iso19139/layout/tpl-csv.xsl
CSV export uses thesaurus identifier as the name for xml element to create the CSV report. This pull request removes non letter/numbers to avoid invalid xml element names, for example if the identifier has character `:`, that causes an error in the export.
> Metadata CSV export - Remove non letter/number characters in thesaurus identifier processing

- web-ui/src/main/resources/catalog/components/common/map/mapService.js
eg. 
```
<Dimension nearestValue="48" name="time" units="ISO8601" default="2020/01/01 00:00:00.000" multipleValue="49">2001/01/01 00:00:00.000, 2002/01/01 00:00:00.000, 2003/01/01 00:00:00.000, 2004/01/01 00:00:00.000, 2005/01/01 00:00:00.000, 2006/01/01 00:00:00.000, 2007/01/01 00:00:00.000, 2008/01/01 00:00:00.000, 2009/01/01 00:00:00.000, 2010/01/01 00:00:00.000, 2011/01/01 00:00:00.000, 2012/01/01 00:00:00.000, 2013/01/01 00:00:00.000, 2014/01/01 00:00:00.000, 2015/01/01 00:00:00.000, 2016/01/01 00:00:00.000, 2017/01/01 00:00:00.000, 2018/01/01 00:00:00.000, 2019/01/01 00:00:00.000, 2020/01/01 00:00:00.000</Dimension>
```
may then generate invalid GetMap request due to leading space.
Layer time property structure changed but it is not used yet - some layer time directive selector to …
> Map / WMS-T / Fix error due to dates leading space char

- services/src/main/java/org/fao/geonet/api/processing/XslProcessApi.java
- services/src/main/java/org/fao/geonet/api/records/MetadataProcessApi.java
eg. iso19115-3.2018-schemaupgrade
Process was not found because parameter truncated at '.'
> Processing / XSL process name may contains .

- core/src/main/java/org/fao/geonet/kernel/EditLib.java
Eg. before this a ServiceIdentification with a topicCategory was returning NPE.
> Editor / Avoid NPE when saving invalid document for an element not existing in the model

- web-ui/src/main/resources/catalog/components/pages/partials/footer.html
- web-ui/src/main/resources/catalog/components/pages/partials/menu.html
- web-ui/src/main/resources/catalog/components/pages/partials/top.html
This PR removes the unused icons from the links for the static pages. 
The placeholders for the icons were there, but never used. These placeholders were taking up space because of the `.fa-fw` class used. This caused unwanted whitespace at the left side of links.
> Remove unused icons from the static pages links

- web-ui/src/main/resources/catalog/components/search/resultsview/partials/selection-widget.html
The items in action dropdown menu in the results page, for when you have metadata selected, are not aligned properly and consistently. This PR adds a fixed width class to the icons and the same spacing for each label, so icons and labels are aligned the same.
**Before (not aligned)**
**After (aligned)**
> Align icons and labels in selection actions dropdown

- core/src/main/java/org/fao/geonet/kernel/security/keycloak/KeycloakAuthenticationProcessingFilter.java
- core/src/main/java/org/fao/geonet/kernel/security/keycloak/KeycloakUserUtils.java
- core/src/main/java/org/fao/geonet/kernel/security/keycloak/keycloakPreAuthActionsLoginFilter.java
- web/src/main/webapp/WEB-INF/config-security/keycloak.json
- autodetect-bearer-only needs to be set to true 
- query string was not in the redirect url so parameters were being dropped. Added query string to redirect. 
- Fixed bug with creating groups - it was missing labels.
- Fixed bearer token parsing - it was attempting to redirect bearer token request to signin page.
- Reverted this change (thank you @zoran995)
> - In a reverse proxy situation, the request could be http when the server is setup to use https and this was causing issues. Ensure it is using https if the server is configured that way.
> 
> For the reverse proxy issue - this fixed our issue with keycloak but I cannot help but think that this should be fixed at a global level? Or maybe there is already a configuration that would support this situation?
Also including a script that …
> Fixed some keycloak issues when calling API's 

- web-ui/src/main/resources/catalog/js/admin/AdminController.js
- web/src/main/webapp/WEB-INF/config-security/config-security-mapping.xml
Fix permission issue related to guest users. Guest users were not able to update their profile or change their password. 
Fixes issue #5252
Note: '/organization/:tab' was restricted to Editor.  This was also restricting registered users from editing their profile as it would go to the page and then redirect back to the search page.  I did change that to guest as well and to make it works.
I thought that this may have been related to issue #4981 and maybe if the correct user id was in the url it would work. 
I tried adding the username by using a url similar to the following.
`http://localhost:8080/geonetwork/srv/eng/admin.console#/organization/users?userOrGroup=username`
It would display the users profile momentarily and then it was still redirecting the user back to the search page.
> Guest users should be able to update their profile

- common/src/main/java/org/fao/geonet/NodeInfo.java
Fixed issue where links to /accessDenied.jsp/eng/service-not-allowed?referer=UNKNOWN could cause endless redirects as accessDenied.jsp is not a recognized node and should be redirected to /srv
When running the latest master with keycloak of schibboleth when a new user is created it will default to guest.  When a guest users is logged in and they click on to see their profile they get a couple errors.
Clicking on testFirstName testLastName before the fix gives the following.
Clicking on it after the fix give the following.
It is odd that I can always reproduce it locally on my builds but I cannot reproduce the exact issue on the test sites (see other tests below).
Issue seems to be related to accessDenied.jsp not being a real node and in some cases it will keep redirecting to the same …
> Fixed issue with possible endless redirect to  /accessDenied.jsp

- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/editor.html
This PR hides the workflow related messages in the 'contribute dashboard' when the workflow is not enabled in the admin.
**Before**
**After**
> Do not show workflow related messages when workflow is not enabled

- core/src/main/java/org/fao/geonet/constants/Geonet.java
- core/src/main/java/org/fao/geonet/kernel/security/keycloak/KeycloakAuthenticationProcessingFilter.java
- core/src/main/java/org/fao/geonet/kernel/security/keycloak/KeycloakHttpSessionManager.java
- core/src/main/java/org/fao/geonet/kernel/security/keycloak/KeycloakLogoutSuccessHandler.java
- core/src/main/java/org/fao/geonet/kernel/security/keycloak/KeycloakUserUtils.java
- core/src/main/java/org/fao/geonet/kernel/security/keycloak/KeycloakUtil.java
- web/src/main/webapp/WEB-INF/classes/log4j.xml
This commit introduce a new logger specifically used for the security service. We come up with the propose after lengthy discussion with @ianwallen This logger helps the admin to better capture the application's access activities for audit purpose.
The new logger would be in the Geonet.java:
public static final String SECURITY = GEONETWORK + ".security";
Note: merged in recent change @ianwallen added https://github.com/geonetwork/core-geonetwork/issues/5252
> Add a security logger to geonetwork

- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/templates/top-toolbar.html
- web-ui/src/main/resources/catalog/views/default/less/gn_navbar_default.less
This PR uses the label for the portal as name in the `menu`/`navigation` (before it was the GeoNetwork name). This enables the use of a translated labels in the navigation.
**Set the label in the admin:**
**The label in the menu:**
> Use the portal/source label as the name in the menu

- web-ui/src/main/resources/catalog/components/common/languageswitcher/LanguageSwitcherDirective.js
- web-ui/src/main/resources/catalog/components/common/languageswitcher/partials/language-switcher.html
- web-ui/src/main/resources/catalog/templates/top-toolbar.html
The language picker is now a `<select>` element in a form. However this form has no submit button, and accessibility is having difficulties with this absence.
This PR changes the `<select>` (and `<form>`) into a Bootstrap **dropdown**. As a bonus you have a better select style to see the current language.
To customize it, you can choose another template like this:
```html
<div data-gn-language-switcher="lang"
data-langs="langs"
data-lang-labels="langLabels"
data-template-url="../../catalog/views/default/templates/language-switcher-buttongroup.html">
</div>
```
**The 'new' language picker**
Thank you @josegar74 for doing the coding
> [a11y] Change language picker into dropdown

- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v402/migrate-default.sql
Error is:
```
could not execute batch; SQL [insert into GUF_UserFeedbacks_GUF_Rating (GUF_UserFeedback_uuid, detailedRatingList_id) values (?, ?)]; constraint [guf_userfeedbacks_uuid]
```
Probably related to JPA update. Column name is different from 3.x.
V3 is
V4 (after this migration) is
> User feedback / Can't save feedback

- core/src/main/java/org/fao/geonet/kernel/datamanager/IMetadataUtils.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataUtils.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataValidator.java
- services/src/main/java/org/fao/geonet/api/processing/MetadataSearchAndReplace.java
- services/src/main/java/org/fao/geonet/api/processing/ValidateApi.java
- services/src/main/java/org/fao/geonet/api/processing/XslProcessUtils.java
- services/src/main/java/org/fao/geonet/api/processing/report/MetadataProcessingReport.java
- services/src/main/java/org/fao/geonet/api/processing/report/Report.java
- services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
- services/src/main/java/org/fao/geonet/api/records/MetadataSampleApi.java
- services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
- services/src/main/java/org/fao/geonet/api/records/MetadataTagApi.java
- services/src/main/java/org/fao/geonet/api/records/editing/BatchEditsApi.java
- services/src/main/java/org/fao/geonet/api/registries/DirectoryApi.java
Updated validation api so that it supports passing the approved flag so that it is possible to validate approved records only when workflow is enabled and there is a working copy.
Also updated the report so that it indicates uuid of the record and if it is a draft or not.  This also help clarify the report so that we know what record is valid/invalid.
Also fixed bug where numberOfRecords was set to "0"
There was another bug in which all validations seemed to fail with errors if there was a report. It was only checking for the existence of the report instead of check if the report contained failedAssert or failedSchematronVerification errors.
Prior to this update validating a record with a working copy will produce something like the following.
```
{
"errors": [],
"infos": [],
"uuid": …
```
> Updated validation api so that it supports working copy and fixed other validation bugs

- web-ui/src/main/resources/catalog/views/default/directives/partials/mdactionmenu.html
- web-ui/src/main/resources/catalog/views/default/less/gn_view.less
- web-ui/src/main/resources/catalog/views/default/templates/recordView.html
This PR makes the subbar on the record view accessible (by keyboard). 
Changes to make it happen:
- improve focus style (to see which element has the focus)
- add `href` so you can access a link with the `tab` button (delete button)
- change `<i>` into `<span>`
- reorganise buttons to get a logical `tab` order
> [a11y] Make the subbar on the record view accessible (by keyboard)

- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/templates/admin/settings/cssstyle.html
- web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_layout_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_search_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_variables_default.less
Related to https://github.com/geonetwork/core-geonetwork/issues/4865
This PR adds the option to change the background colour of the search blocks on the home and search results page. When no colour is chosen in the admin, the background colour defaults to the same colour as the `body`
**Setting in the admin**
**The coloured search on the homepage**
**The search block on the results page**
> [#4865] Add option setting for changing the background color of the search block

- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataIndexer.java
- services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
In `master` this pull request: https://github.com/geonetwork/core-geonetwork/pull/4817 added support for the metadata delete event to track the metadata history.
In `3.10.x` the event is available, but was not triggered. This pull request triggers the metadata delete event when a metadata is deleted. 
In `3.10.x` there's no event implementation, but custom projects can at least implement it if required.
> Trigger metadata delete event in 3.10.x branch

- web-ui/src/main/resources/catalog/locales/en-core.json
- web-ui/src/main/resources/catalog/locales/fr-core.json
- web/src/main/webapp/WEB-INF/config-summary.xml
There is an untranslated text "sample" on side search module.
The fix is to add the translation to core.json and it will be handled by Angular translation filter factory. It's similar to the "Tout sélectionner" French text in the same JSON file.
> Add translation for "sample" on search module.

- core/src/main/java/jeeves/config/springutil/JeevesContextLoaderListener.java
- pom.xml
- software_development/BUILDING.md
The `master` branch requires JDK 8 for building and running. This PR adds a couple checks to ensure Java 8 is used.
With this PR, when tomcat is configured with Java 11, geonetwork will refuse to start with `geonetwork.log`:
```
2020-10-22 21:18:54,047 FATAL [jeeves.engine] - Raised exception during init
2020-10-22 21:18:54,047 FATAL [jeeves.engine] -    Exception : java.lang.RuntimeException: Java 8 required, cannot start with "11.0.7"
2020-10-22 21:18:54,047 FATAL [jeeves.engine] -    Message   : Java 8 required, cannot start with "11.0.7"
2020-10-22 21:18:54,052 FATAL [jeeves.engine] -    Stack     : java.lang.RuntimeException: Java 8 required, cannot start with "11.0.7"
```
> java 8 only

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/update-fixed-info.xsl
- schemas/iso19139/src/main/plugin/iso19139/update-fixed-info.xsl
Date fields in the metadata editor use the directive `gn-date-picker`, this directive adds for ISO19139 the element `gco:Date` if the time part is set to empy, but `gmd:dateTime` requires `gco:DateTime` (see http://www.datypic.com/sc/niem21/e-gmd_dateTime-1.html). 
Similar stuff happens with the directive if it's configured in the editor views to hide the time part with the attribute `hideTimeInCalendar="true"`.
This pull request updates the update-fixed-info process to use `gco:DateTime` for `gmd:dateTime` and set the time part as `T00:00:00` if it's empty. 
To test add in the data quality section a processstep date/time element.
> ISO19139 / ISO19115-3.2018 - Force gco:DateTime on elements that doesn't support gco:Date

- core/src/main/java/org/fao/geonet/api/records/attachments/StoreUtils.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/IMetadataUtils.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataUtils.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/draft/DraftMetadataUtils.java
- listeners/src/main/java/org/fao/geonet/listener/metadata/draft/DraftUtilities.java
Create replaceDataDir to be used when merging a draft back to approved record. The previous copyDataDir would just copy the data and not remove the records that were deleted in the draft. 
Also added cleanup of draft resources after the draft is merged to the approved record.
Prior to this release it was not possible to remove a resource.
- Enable workflow
- Create new metadata and add thumbnail image (image1)
- Approve/publish the metadata
- Edit metadata - it should create a new working copy
- In the file store remove the image - but keep the thumbnail link in the metadata record.  Thumbnail should show up as broken image.
- Also add a new thumbnail - different image (image2).
- Save the metadata record and approve
2 Bugs that are fixed with these changes.
- The thumbnail in the …
> Fix some working copy merge issues

- inspire-atom/src/main/java/org/fao/geonet/inspireatom/harvester/InspireAtomHarvester.java
- inspire-atom/src/main/java/org/fao/geonet/inspireatom/model/DatasetFeedInfo.java
- inspire-atom/src/main/java/org/fao/geonet/inspireatom/util/InspireAtomUtil.java
- inspire-atom/src/main/java/org/fao/geonet/services/inspireatom/AtomServiceDescription.java
- schemas/iso19139/src/main/plugin/iso19139/extract-datasetinfo-from-service-feed.xsl
- schemas/iso19139/src/main/plugin/iso19139/index-fields/default.xsl
This pull request updates remote INSPIRE Atom feeds processing to extract the dataset feeds directly from the service feeds referenced in the service metadata.
In the previous implementation, dataset feeds were extracted from the dataset metadata referenced in the service metadata, but it's not mandatory that dataset metadata references the feed documents, causing missing values in these cases.
> Update Remote INSPIRE Atom feeds to process dataset feeds from service feeds

- core/src/main/java/org/fao/geonet/api/records/attachments/FilesystemStore.java
> Update file copy so that it will overwrite any existing file which is required when approving a record that was previously published

- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataIndexer.java
- listeners/src/main/java/org/fao/geonet/listener/metadata/draft/ApproveRecord.java
- Throw RecordUpdatedEvent when a draft metadata is approved to notify about the change.
- Throw RecordDeletedEvent when doing a batch delete of metadata records related to a harvester
> Event handling improvements

- web-ui/src/main/resources/catalog/components/common/map/mapService.js
- web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextService.js
- web-ui/src/main/resources/catalog/components/viewer/wfsfilter/WfsFilterDirective.js
- web-ui/src/main/resources/catalog/components/viewer/wfsfilter/partials/wfsfilterfacet.html
When saving or restoring map, the layer is not linked anymore to the corresponding metadata record.
Adding a uuid and label in the OWS context layer extension to preserve this link.
```xml
<ows-context:Layer name="unesco:Unesco_point" hidden="false" opacity="1">
<ows-context:Server service="urn:ogc:serviceType:WMS" version="1.3.0"> 
<ows-context:OnlineResource xlink:href="https://demo.geo-solutions.it:443/geoserver/ows?SERVICE=WMS&"/>
<ows-context:Extension>{
"uuid":"27d794393a02e795416f9801a3685d8b1862dae4",
"label":"Unesco Items"}</ows-context:Extension>
```
If not preserved, then layer contextual menu has no link to metadata 
and WFS filter directive does not work.
> Map / Layer / Preserve link to metadata record.

- web-ui/src/main/resources/catalog/components/search/resultsview/gridRelated.js
- web-ui/src/main/resources/catalog/views/default/templates/gridRelatedList.html
Depending of the origin catalog/portal/remote the link has to be adapted to open the target link in current app or main portal or another window. Relates to https://github.com/geonetwork/core-geonetwork/pull/4608.
This probably does not affect many users. It is in search result with list mode with relation:
> Portal / Related record displayed in search results do not take record origin in account.

- web/src/main/webapp/WEB-INF/config-security/config-security-default.xml
- web/src/main/webapp/WEB-INF/config-security/config-security.xml
Modify spring security so that it can be set at runtime startup by setting -Dgeonetwork.security.type or via env GEONETWORK_SECURITY_TYPE
> Modify spring security so that it can be set at runtime startup

- pom.xml
> Upgrade to GeoTools 24.0 and JTS 1.17.1

- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid.html
- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
Thumbnail API allows to return the overview with a custom size (see https://github.com/geonetwork/core-geonetwork/pull/4593) mainly to avoid to load big images in search results page.
Improve the filter URL to be able to customize easily the size of the image to return and avoid to append this parameter to URL not pointing to a GeoNetwork instance.
> Thumbnail / Improve size filter.

- schemas/README.md
- software_development/BUILDING.md
- web/README.md
- web/pom.xml
Adding some build functionality to make local jetty testing easier to manage.
To reset the database, jcs_cache, images and logs and anything else mentioned by `.gitignore` (helpful when switching branches):
```
mvn clean:clean@reset
```
> Add clean:clean@reset target for web module

- release/README.md
- release/build.xml
- release/pom.xml
- web/src/main/webapp/WEB-INF/server.prop
This is a follow on from web clean:clean@reset activity, noticed the release build was creating some folders that were not being cleaned up.
-----
1. Build geonetwork if you have not done so already
```
mvn clean install -DskipTests
```
2. From the release folder, download jetty (you only need to do this once):
```
mvn process-resources -Djetty-download
```
3. Once the `jetty` folder is in place the release module will package the `zip` installer:
```
mvn package
```
4. The installer is created in `target` folder.
3. To clean up the `jetty` folder:
```
mvn clean:clean@reset
```
> release cleanup

- web-ui/src/main/resources/catalog/components/elasticsearch/EsService.js
- web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facets.html
- web-ui/src/main/resources/catalog/js/CatController.js
Add support for filter to be case insensitive. By default it is case sensitive (as Elasticsearch include parameter works). Add a `meta` > `caseInsensitiveInclude` to turn on case insensitive mode. It will build case insensitive regexp.
Configuration 
```json
'tag.default': {
'terms': {
'field': 'tag.default',
'include': '.*',
'size': 10
},
'meta': {
'caseInsensitiveInclude': true
}
},
```
Do not display filter if the number of items is limited (ie. no more).
Do not display facet if it has no items.
> Facet / Filter / Case insensitive

- core/src/test/java/org/fao/geonet/kernel/DataManagerIntegrationTest.java
- schemas/iso19139/src/main/plugin/iso19139/update-fixed-info.xsl
- services/src/main/java/org/fao/geonet/api/registries/DirectoryEntriesApi.java
Code to calculate the main language locale code reused from https://github.com/metadata101/iso19139.ca.HNAP
> ISO19139 - Preserve locale codes in metadata. Fixes #5060

- web-ui/src/main/resources/catalog/components/elasticsearch/EsFacet.js
- web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js
- web-ui/src/main/resources/catalog/js/CatController.js
Some facet config related to the UI eg. collapsed, userHasRole,
caseInsensitiveInclude were attached to the root of the facet config.
Use the meta properties that can be send to server and returned in
response.
The point here is to converge config between GeoNetwork 4 and GN-UI
See https://github.com/geonetwork/geonetwork-ui/blob/95b73af468363d0bb9da3a11d379a59381ab7955/libs/common/src/lib/services/bootstrap.service.ts#L35-L61
eg.
```
'cat': {
'terms': {
'field': 'cat.keyword',
'size': 10
},
'meta': {
'userHasRole': 'isAdministratorOrMore',
'collapsed': true
}
}
```
> Facet / Configuration / UI props in meta

- services/src/main/java/org/fao/geonet/api/site/SiteApi.java
Fixed broken site logo on fresh install.
Seems like regression from https://github.com/geonetwork/core-geonetwork/pull/5245
In a fresh install the site name is the source.getUuid() not the NodeInfo.DEFAULT_NODE.
Fixed impossible condition with 
`  .setValue(source != null ? `
as that will always be true as identified in previous if statement.
I'm assuming it was supposed to be the following.
`  .setValue(StringUtils.isEmpty(source.getLabel(iso3langCode)) ?`
so that if the translated value is null, it should default to the name
Also cleaned up the code so there was less duplicate code.
> Fixed broken site logo image on fresh installation.

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/onlinesrcList.html
When editing an HNAP record within workingcopy the new thumbnail images added to the metadata don't display.
This is a another patch related to #5299
> Fixed another broken image related to #5299

- release/build.properties
- release/build.xml
- resetReleaseVersions.sh
- update-version.sh
- updateBranchVersions.sh
- updateReleaseVersions.sh
Several "global" properties that are stored as `<property>` elements inside the release `build.xml` file should be stored inside a separate `build.properties` file that can be easily imported by other build files as well (e.g. for the Windows installer).
> Move release build properties to separate file

- services/src/main/java/org/fao/geonet/api/records/MetadataSampleApi.java
When importing the samples & templates for metadata schemas with the related Administration option, it's created a new uuid that is stored in the database, but for templates the uuid is not updated in the xml, so the database record ends with a different uuid than the related xml content:
The code relies in ` dataManager.insertMetadata` that doesn't apply `update-fixed-info` process for templates.
When importing a template with the Metadata Insert option, it handles it properly using the `set-uuid` process:
https://github.com/geonetwork/core-geonetwork/blob/a0d3083673a588cdd51815d3023213d83d15af58/services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java#L846-L850
This pull request updates the import of the samples & templates to unify the behavior.
> Import metadata samples and templates - set the same uuid in the xml and in the database for templates

- core/src/main/java/org/fao/geonet/api/records/attachments/CMISStore.java
- core/src/main/java/org/fao/geonet/resources/CMISConfiguration.java
- core/src/main/java/org/fao/geonet/resources/CMISResources.java
- core/src/main/resources/config-store/config-cmis.xml
Versions states were currently hard coded to use MAJOR version for the version state.
The change make it possible to change the states by using 2 new variables.
`CMIS_VERSIONING_STATE`
Can be a value from the VersioningState Class (NONE, MAJOR, MINOR)
`CMIS_VERSIONING_MAJOR_ON_UPDATE`
Only applies to `MAJOR` - indicates if the next version should be another major version(true) or a minor version(false)
Here are the expected version generations from different software.
`NONE` is the only one that seems to behave differently on different systems.  Possibly different default configurations and interpretations.
It can be tested by uploading the same file multiple times in the metadata file store
Application | Version State | Values
------------ | ------------- | -------------
Alfresco | NONE …
> CMIS: Make version state configurable.

- core/src/main/java/org/fao/geonet/api/records/attachments/CMISStore.java
- core/src/main/java/org/fao/geonet/resources/CMISConfiguration.java
- core/src/main/java/org/fao/geonet/resources/CMISResources.java
- core/src/main/java/org/fao/geonet/resources/CMISUtils.java
- core/src/main/resources/config-store/config-cmis.xml
- services/src/main/java/org/fao/geonet/api/records/MetadataSampleApi.java
Performance changes related to CMIS store implementation.
- Reduced API calls
Reduced API calls by passing object to private function so that they don't need to be fetched again
Remove call to fetch object when it was available in previous calls.
- Modify operational context.
Update default operations context so that some options are turned off to increase performance.
Modify createOperationContext so that it is based on the default context.
- Add Folder caching
CMIS is slow creating multilevel folders.  So added caching to keep track of the last 1000 folders created/used and reuse the object when possible.
Mostly used so that folders are created from previously known folders instead of always attempting to create the full folder.
- Refactored
Moved common code between the Resource and …
> CMIS: Performance improvements.

- web-ui/src/main/resources/catalog/views/default/templates/recordView.html
The code was copied from the metadata logo display in the search page.
> #5212 Fix logo in record view

- web-ui/src/main/resources/catalog/views/default/templates/recordView.html
The code was copied from the metadata logo display in the search page.
> [BP] Fix logo in record view (#5212)

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/linktosibling.html
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/remote-record-selector.html
The popup to link to other resources uses one dropdown for all resources. Searching for the right link can be hard.
This PR changes this dropdown in a paginated list and adds reset options to the search to make searching easier. The rest of the functionality is the same as before.
**Screenshot of the new popup:**
Changes:
- dropdown list changed to paginated list
- add reset search button
- deleting search object resets the search (full list is shown again)
- minor visual improvements
> Improvements to Link to other resources - list of suggested datasets

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl
- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
Some catalogues have various type of thesaurus. Only theme thesaurus type was displayed in full view
Only exclude place keyword which might be displayed next to the extent of the record.
> Formatter / Display all keywords excluding those of type place.

- core/src/main/java/org/fao/geonet/kernel/AccessManager.java
ISO19139 indexing uses `XslUtil.getRecord` to check during service metadata indexing if the metadata referenced in `srv:operatesOn` are also available in the current portal:
https://github.com/geonetwork/core-geonetwork/blob/f7d08216c7973025a347c8f3399f9709ec326035/schemas/iso19139/src/main/plugin/iso19139/index-fields/default.xsl#L1148
This code uses:
https://github.com/geonetwork/core-geonetwork/blob/f7d08216c7973025a347c8f3399f9709ec326035/core/src/main/java/org/fao/geonet/util/XslUtil.java#L789
That uses `AccessManager`  to add the privileges depending on the user session.
Seems when done the indexing in the metadata editor and in other cases, the indexing is synchronous and the user session is available in the `ServiceContext`, but when the indexing is done in a thread, to increase …
> Protect AccessManager code using user session

- core/src/main/java/jeeves/transaction/TransactionManager.java
This is a part of quality assurance pass [checking for session leaks](https://github.com/geonetwork/core-geonetwork/pull/5260). The transaction manager code was not defensive and presented opportunities for exceptions to interrupt transaction commit/rollback or go unreported.
> Log transaction manager notification failures

- core/src/main/java/org/fao/geonet/kernel/search/spatial/SpatialIndexWriter.java
- core/src/test/java/org/fao/geonet/kernel/search/spatial/SpatialIndexWriterTest.java
- csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/CatalogSearcher.java
Looking at resolving https://github.com/geonetwork/core-geonetwork/issues/4811 by accepting a wider range of geometry types, buffering points and linestrings with a small bbox as needed.
Assume the API contract is fine as long as the geometry is contained within the shape provided to the index.
> Use GeometryTransform to convert to multipolygon

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFilesystemHarvester.java
With https://github.com/geonetwork/core-geonetwork/commit/20693c711a6404d49208364adc2a63202d1ec6ad importing subtemplate using local filesystem harvester does not work.
> Harvester / Local file system / Restore possibility to import subtemplates

- web/src/main/webapp/xslt/common/utility-tpl-metadata.xsl
- web/src/main/webapp/xslt/services/metadata/validate-fn.xsl
- web/src/main/webapp/xslt/services/metadata/validate.xsl
Fixed xsl regular expression due to the parser error message change to translate language text. Pass codelist into the validate-fn.xsl to get multilingual support for topic category list.
> Fixed unhandled error and its xsl regular expression. Fixed root element in Schematron title translation.

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout-custom-fields.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/update-fixed-info.xsl
- schemas/iso19139/src/main/plugin/iso19139/extract-gml.xsl
- schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields.xsl
- schemas/iso19139/src/main/plugin/iso19139/update-fixed-info.xsl
this work builds on #5367, the extract-gml (on iso19139) did not consider submission of a point geometry
also preparing some of the cleaning/checking methods for point. #5367 creates a box around a point (previously storing failed) now we can see the extend image as 
Part of solution for #4811
> extend extract-gml to add point as boundingpolygon

- web-ui/src/main/resources/catalog/components/edit/bounding/BoundingDirective.js
- web-ui/src/main/resources/catalog/components/edit/bounding/partials/boundingpolygon.html
- web-ui/src/main/resources/catalog/components/viewer/geometry/GeometryService.js
This PR brings point support to the editor UI for issue #4811 and relates to PRs #5367 and #5374.
Besides `MultiPolygon` and `LineString` geometries, users can now draw/edit `Point` geometries as a "Bounding Polygon" as well.
Most important changes:
- Added Point drawing button next to existing Polygon and Line buttons
- Instead of adding interactions and linking button behavior to it, the UI now adds interactions to the buttons
- Removed Modify button to save space (interaction is now always on)
- Fixed zoom to (enlarged) extent for points
- Fixed GML to text output for points
> Support points in Bounding Polygon editor

- web-ui/src/main/resources/catalog/js/admin/DashboardController.js
Fix tabs for useradmin which were sometimes showing all options when reloading the page.
If you login as a useradmin user and go to the Statistics and Status you should see the following.
Click on any link excep for "record links analysis" i.e. versioning
And the tabs change to the following
Hit reload and it reverts back to the first list.  But it will also show the versioning form.
This fix makes it so that the tabs are displayed correctly.
Updated code so that it is similar to the settings tabs which seems to be cleaner code.
Also added "`$scope.$watchCollection('user', function (n, o) {`" code which seems to be the real fix for this issue.
I also noticed that the dashboard seams to have editor as the default permissions. Maybe that should be changed to useradmin unless we want the …
> Fix tabs for useradmin - Statistics and Status

- web-ui/src/main/resources/catalog/components/admin/BatchService.js
Some processes may have large parameters too long to be posted in URL depending on container config.
```
[WARNING] URI is too large >8192
```
eg. while adding feature catalogue with 128 columns definitions!
```
b_term;Terminus (Oui/Non);C;
c_mode;Mode de transport (MET : métro);C;
c_station;Station (B);C;
....
```
POST parameters in body instead.
Another option would be to increase `jetty.request.header.size`.
> Editor / Suggestions / Too large parameters

- web-ui/src/main/resources/catalog/components/search/formfields/FormFieldsDirective.js
- web-ui/src/main/resources/catalog/js/edit/NewMetadataController.js
- web-ui/src/main/resources/catalog/templates/editor/import.html
- web-ui/src/main/resources/catalog/templates/editor/new-metadata-horizontal.html
- web-ui/src/main/resources/catalog/templates/editor/new-metadata-vertical.html
* Import / Group contains blank value only if admin (like in new
metadata)
* Avoid duplicated empty option in list (add optional first and select first item)
* New metadata / Don't select first user group in the list - let the group combo directive take care of the default based on its config.
> Import & new metadata / Consistent group list.

- schemas/iso19139/src/main/plugin/iso19139/index-fields/language-default.xsl
when multilingual records contains multiple citations, "A sequence of more than one item is not allowed as the first argument of normalize-space()" was thrown. This fixes that. Which causes title element not to be indexed and displayed empty in search results.
> fix xpath to match only the main citation title, not other titles

- common/src/main/java/org/fao/geonet/utils/DateUtil.java
- common/src/test/java/org/fao/geonet/utils/DateUtilTest.java
- schemas/dublin-core/src/main/plugin/dublin-core/index-fields/index.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
- schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
* Dublin core / Multiple title / Only first one indexed (it will be better managed in DCAT2 plugin providing multilingual support).
* Invalid role value `{{role}}` trying to create an invalid field name.
```
GNIDX-XSL||Invalid element name. Invalid QName {{{role}}OrgForResource} (42)
```
* Multiple phones - only the first one is indexed
```
Error on line 1169 of index.xsl:
XTTE0790: A sequence of more than one item is not allowed as the first argument of
gn-fn-index:json-escape() ("02 38 42 24 55", "06 31 14 98 21")
```
* Date parsing - more flexible with support for 20170322, 2015-10-18T19:59:30.2675269Z (nanoseconds)
```
Error parsing ISO DateTimes '20170322'. Error is: Text '20170322' could not be parsed: Unable to obtain ZonedDateTime from TemporalAccessor: {},ISO resolved to …
```
> Indexing / More robust

- add-schema.sh
- schemas/pom.xml
- web/pom.xml
Note use of ``--force`` to allow reuse of previously added remote locations (see "Reactivating" in the sample output below).
Sample run:
```
% ./add-schema.sh iso19139.ca.HNAP https://github.com/metadata101/iso19139.ca.HNAP 3.10.x
```
```
Adding schema from https://github.com/metadata101/iso19139.ca.HNAP, branch  3.10.x to schemas/iso19139.ca.HNAP
Reactivating local git directory for submodule 'schemas/iso19139.ca.HNAP'.
Adding schema iso19139.ca.HNAP to schemas/pom.xml
Adding schema iso19139.ca.HNAP dependency to web/pom.xml for schemaCopy
Adding schema iso19139.ca.HNAP dependency to web/pom.xml for schemaUnpack
Adding schema iso19139.ca.HNAP resources to service/pom.xml
```
> Backport add-schema.sh from master and adapt for 3.10.x branch

- services/src/main/java/org/fao/geonet/api/records/formatters/FormatterApi.java
- services/src/test/java/org/fao/geonet/api/records/formatters/FormatterApiIntegrationTest.java
This check prevented full-view from displaying updated contents after an edit in chrome and edge browsers.
> Avoid request check not modified as unsupported on chrome and edge

- web-ui/src/main/resources/catalog/components/common/map/mapService.js
That may happen on some projects having old ESRI Rest layer implementation and invalid context (eg. Sextant).
> Map / ESRI layer / Warn user in case of invalid configuration

- csw-server/src/main/java/org/fao/geonet/component/csw/GetCapabilities.java
In GeoNetwork GetCapabilities document, keyword list was populated based on the GetDomain operation results. It is currently not yet supported in v4. So an exception like
```
2021-02-11 01:08:53,042 ERROR [geonetwork.csw] - Error getting domain value for specified PropertyName : org.apache.commons.lang.NotImplementedException: CSW GetDomain operation not implemented in ES
```
was raised.
The recommended approach to configure CSW is to use service metadata record (see https://geonetwork-opensource.org/manuals/4.0.x/en/administrator-guide/configuring-the-catalog/csw-configuration.html#service-metadata-record).
> CSW / GetCapabilities / Avoid exception in log due to GetDomain

- core/pom.xml
- harvesters/pom.xml
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/webdav/Harvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/webdav/WAFRemoteFile.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/webdav/WAFRetriever.java
- pom.xml
- web/pom.xml
* Add the ability to harvest a remote WAF server protected with `BASIC` or `DIGEST` authentication.
* User the server's proxy settings if enabled in the Admin Console.
* Update jsoup to `1.13.1` from `0.2.2`
* Add jsoup to managed dependencies in root `pom.xml`
* Remove the dependency from sites where it wasn't used (`web` and `core`)
* Add the dependency to the module where it is required (`harvesters`)
Closes #4050.
> Support WAF with authentication

- .github/FUNDING.yml
This provides some funding links for the GitHub repository:
- GitHub sponsors via osgeo organization
- Link to wiki where we have a heading on financial support
- PayPal
See https://docs.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository for details and background.
> funding links for github repository

- schemas/dublin-core/src/main/plugin/dublin-core/index-fields/index.xsl
Errors with different elements of the DC mapping  (title, overwiew, date...).
Ex. Simple search metadata with the title 'titre'
Any text = 'Titre'
Result with the new mapping:
> Dublin core - Improve mapping indexation

- csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/SearchController.java
Was only applied to GetRecordById
Related to https://github.com/geonetwork/core-geonetwork/commit/95fcefbd1849695ce816e369a5b51a33116c0ed7
Probably forgotten on Elasticsearch migration. Similar to 3.x https://github.com/geonetwork/core-geonetwork/blob/master/csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/SearchController.java#L516-L528
> CSW / GetRecords / Apply postprocessing

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
- schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
- web/src/main/webResources/WEB-INF/data/config/index/records.json
Related to https://github.com/geonetwork/core-geonetwork/wiki/GeoNetwork-UI-and-microservices-codesprint-January-2021#gn4-indexing
* Standard name is multilingual and may have xlink
* `standardVersion` missing in 19115-3
* Metadata and resource charset indexed in `cl_characterSet` and `cl_resourceCharacterSet`
* Resource identifier with link and codespace
* Resource edition in `resourceEdition`
* license
* specificationConformance
> ISO19139/ISO19115-3 index updates to improve build of jsonld/dcat formats

- web-ui/src/main/resources/catalog/js/GnLocale.js
- web-ui/src/main/resources/catalog/js/edit/EditorController.js
For some reason, part of the pop up box for the metadata title is not decoded in editor when cancelling a newly added metadata.
I found the work around is to force decode all metadata title that includes not just accent character, but also white space and etc. The decoded and encoded string looks like :
So as result, the popup will look like:
> Encode metadata title and decode in the translate function.

- web-ui/src/main/resources/catalog/components/filestore/partials/filestore.html
The issue is version number wraps in the table because there is no min width for this entry. So when version number is a decimal number like 11.01. It wraps around.
The solution is to specify this field to be 50px minimum.
> Min width to avoid table data wrapping.

- domain/src/main/java/org/fao/geonet/repository/MetadataStatusRepositoryCustom.java
- domain/src/main/java/org/fao/geonet/repository/MetadataStatusRepositoryImpl.java
- services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
- services/src/main/resources/config-spring-geonetwork.xml
- services/src/test/java/org/fao/geonet/api/records/MetadataWorkflowApiTest.java
- services/src/test/resources/services-web-test-context.xml
- web/src/main/webResources/WEB-INF/config-spring-geonetwork.xml
This is the API information:
Add status Id list into the API. So the RESTful interface will pass this list into search query. This list can be left empty or with some invalid number, or mix with valid and invalid status Id.
The result will only returns good status Ids and ignore invalid ids and emptiness.
Here is the information to test:
curl -X GET "http://localhost:8080/geonetwork/srv/api/0.1/records/status/search?type=event&details=true&uuid=86a9d0b0-fcce-48ed-a124-68061d7b7553&from=0&size=100&statusIds=50&statusIds=51&statusIds=100" -H "accept: application/json" -H "X-XSRF-TOKEN: b172b8fc-4798-4a73-8402-752a35132872"
This is the url of my localhost. So you will need type=event&details=true&uuid=<YOUR_LOCAL_VALID_UUID>. Then put statusId list in. The valid value can be found here …
> Add statusIds list to MetadataWorkflowApi.getStatusByType API

- core/src/main/java/org/fao/geonet/api/records/attachments/AbstractStore.java
- core/src/main/java/org/fao/geonet/api/records/attachments/CMISStore.java
- core/src/main/java/org/fao/geonet/api/records/attachments/FilesystemStore.java
- core/src/main/java/org/fao/geonet/api/records/attachments/FilesystemStoreResource.java
- core/src/main/java/org/fao/geonet/api/records/attachments/FilesystemStoreResourceContainer.java
- core/src/main/java/org/fao/geonet/api/records/attachments/ResourceLoggerStore.java
- core/src/main/java/org/fao/geonet/api/records/attachments/S3Store.java
- core/src/main/java/org/fao/geonet/api/records/attachments/Store.java
- core/src/main/java/org/fao/geonet/resources/CMISConfiguration.java
- core/src/main/java/org/fao/geonet/util/XslUtil.java
- core/src/main/resources/config-store/config-cmis-overrides.properties
- core/src/main/resources/config-store/config-cmis.xml
- domain/src/main/java/org/fao/geonet/domain/MetadataResourceContainer.java
- domain/src/main/java/org/fao/geonet/domain/MetadataResourceExternalManagementProperties.java
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcService.js
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html
- web-ui/src/main/resources/catalog/components/filestore/FileStoreDirective.js
- web-ui/src/main/resources/catalog/components/filestore/partials/filestore.html
- web-ui/src/main/resources/catalog/components/metadatamanager/EditorService.js
- web/src/main/webapp/xslt/common/base-variables-metadata.xsl
- web/src/main/webapp/xslt/ui-metadata/edit/edit.xsl
CMIS - Add logic for displaying a button to go to the main folder.
This will allow the user to go directly to the storage folder related to the related CMIS application and use management feature of the application to upload files, properties.
In some cases if attempting to upload a 100MB data file via a slow or unreliable internet, it could be difficult.  By going to the management tool main folder, a user could use the features of that tool i.e. resume uploads,   performing bulk uploads, and some application can connect to tools such as dropbox or ms onedrive
For Alfresco, this would go to the folder page. 
The resource management url would change to use {type:folder:document} in the url - like the following.
`CMIS_EXTERNAL_RESOURCE_MANAGEMENT_URL=http://localhost:8080/share/page/{type:f …
> CMIS - Add button to go to the main folder.

- services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
We were having problems setting custom UUIDs on new metadata records using the URN templates feature. This one character fix is enough to correct this regression.
> Fix issue using custom UUIDs

- common/src/main/java/org/fao/geonet/exceptions/JeevesException.java
- common/src/main/java/org/fao/geonet/utils/Xml.java
> Admin / Harvester / No harvester in list after error

- core/src/main/java/org/fao/geonet/api/records/attachments/CMISStore.java
- core/src/main/java/org/fao/geonet/api/records/attachments/FilesystemStore.java
- core/src/main/java/org/fao/geonet/api/records/attachments/ResourceLoggerStore.java
- core/src/main/java/org/fao/geonet/api/records/attachments/S3Store.java
- core/src/main/java/org/fao/geonet/api/records/attachments/Store.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java
- core/src/main/java/org/fao/geonet/lib/ResourceLib.java
- core/src/main/java/org/fao/geonet/util/XslUtil.java
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
- schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid.html
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/list.html
- web/src/main/webapp/xslt/common/index-utils.xsl
When running a search, 30 records are displayed per pages (by default). Most of the users are setting thumbnails in records and this will trigger 30 requests to get thumbnails which can be external images or attachements. In quite some situation, thumbnails are beautiful & quite big.
In https://github.com/geonetwork/core-geonetwork/pull/4593 we added the possibility in the API to reduce image size but this only applies to internal attachements.
To limit the number of requests and the overall download bandwidth on each search result page load, this store a small (140px width) image in the index and use dataUrl to display it. 
With this change, a search will be 2 requests (ie. search + related) instead of 32 (search + related + overviews). Search response is a bit bigger but the overall …
> Overview / Stored in index and used as dataURL.

- common/src/main/java/org/fao/geonet/utils/Version.java
- common/src/test/java/org/fao/geonet/utils/VersionTest.java
- web/src/main/java/org/fao/geonet/DatabaseMigration.java
Uses maven version definition and comparison.
This allows schema plugins to more accurately check for compatibility
(see metadata101/iso19139.ca.HNAP#185 for context).
Backport for 3.10.x is available https://github.com/geonetwork/core-geonetwork/pull/5451
> Use maven major, minor, patch, build, qualifier definition for version

- common/src/main/java/org/fao/geonet/utils/Version.java
- common/src/test/java/org/fao/geonet/utils/VersionTest.java
- web/src/main/java/org/fao/geonet/DatabaseMigration.java
Uses maven version definition and comparison.
This allows schema plugins to more accurately check for compatibility 
(see https://github.com/metadata101/iso19139.ca.HNAP/issues/185 for context).
> [BP] Use maven major, minor, patch, build, qualifier definition for version [3.10.x]

- domain/src/main/java/org/fao/geonet/domain/InspireAtomFeed.java
- domain/src/main/java/org/fao/geonet/repository/specification/MetadataSpecs.java
- Update JPA specification to filter metadata with schemas based on iso19139 also.
- Atom feed parse: truncate fields longer than the database related fields.
> INSPIRE Atom fixes

- services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java
Send the attachment content to the client directly without loading the full file in memory first. Also send the `Content-Length` header.
Fixes #5449.
> Stream attachments to the browser without loading them in memory

- web-ui/src/main/resources/catalog/components/common/ows/OWSService.js
Looks like on FF angular copy can be quite slow on large document.
> Map / OWS / speed up WMS capabilities parsing

- web-ui/src/main/resources/catalog/views/default/templates/recordView.html
Use to be text but now is an object (introduced in https://github.com/geonetwork/core-geonetwork/pull/5379/files#diff-936e4fb67d4d170a09c59a025513de797946f33a2e7b19dc5296e35be65ae558R333)
> Record view / Fix resource identifier display

- web-ui/src/main/resources/catalog/templates/signin.html
Anchor doesn't work well with `ng-disable` and can be clicked when disabled.
See https://github.com/angular/angular.js/issues/15260
> Use button to recover the password

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/add-extent-from-geokeywords.xsl
- schemas/iso19139/src/main/plugin/iso19139/process/add-extent-from-geokeywords.xsl
- services/src/main/java/org/fao/geonet/api/registries/vocabularies/KeywordsApi.java
The XSLT powering this button from the geonetwork editor called out to the geonetwork API. This API being called has switched to responding with JSON which XSLT doesn't understand.
This pull request restores a working XML endpoint for it to call. Content negotiation was attempted, but we found this doesn't work with the relevant XSLT processor.
> Fix regression on "Compute extents from keywords" button

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/add-extent-from-geokeywords.xsl
- schemas/iso19139/src/main/plugin/iso19139/process/add-extent-from-geokeywords.xsl
- services/src/main/java/org/fao/geonet/api/registries/vocabularies/KeywordsApi.java
* Modifications to re-enable calculate extents from keywords
* Add content negotiation for /search API.
The .xml endpoint is left around for the sake of an XSLT processor that doesn't send an Accept: HTTP header.
* Tidyup keywords URL called by add-extent-from-geokeywords XSL.
Remove XML-specific registries/vocabularies/search endpoint after finding a better way to call it.
* Suggestion / Add extent from geokeyword / Improve API and support ISO19139 and ISO19115-3.
Co-authored-by: ByronCinNZ <cochranes4@eml.cc>
Co-authored-by: ByronCinNZ <byronc@cochrane-ogs.co.nz>
Co-authored-by: Francois Prunayre <fx.prunayre@gmail.com>
> Fix regression on "Compute extents from keywords" button (#5455)

- services/src/main/java/org/fao/geonet/api/regions/ThesaurusBasedRegionsDAO.java
If configuring more than one ThesaurusBasedRegionsDAO then all cache key are the same for all of them. And http://localhost:8080/geonetwork/srv/api/regions/types reports the keys from the first DAO.
> Thesaurus / Fix same cache key for all ThesaurusBasedRegionsDAO

- web-ui/src/main/resources/catalog/components/common/ows/OWSService.js
- web-ui/src/main/resources/catalog/locales/en-core.json
When you want to add a WMTS layer in the map, you add a URL to a WMTS service. However, when this URL is invalid, nothing happens and the 'wait' icon keeps spinning.
This PR adds a message for when the URL can't be parsed as a WMTS service.
> Add a WMTS error message when the URL can't be parsed

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/common.xsl
- schemas/iso19139/src/main/plugin/iso19139/index-fields/default.xsl
- schemas/iso19139/src/main/plugin/iso19139/index-fields/language-default.xsl
- web-ui/src/main/resources/catalog/components/catalog/CatalogService.js
- web-ui/src/main/resources/catalog/views/default/templates/recordView.html
- web/src/main/webapp/WEB-INF/config-lucene.xml
Implemented option 2 described in #5483, with the changes the metadata detail page displays all the temporal extents defined:
> Index temporal extent period, fix multiple temporal extent display inthe metadata detail page. Fixes #5483

- web-ui/src/main/resources/catalog/templates/editor/top-toolbar.html
This PR changes the `btn-success` class form the `Save` to the more used `Save & close` button.
**Before**
**After**
> Change the `btn-success` class to the more used 'save & close' button

- web-ui/src/main/resources/catalog/js/admin/UserGroupController.js
If the content type includes the charset, the error was not parsed properly, displaying the following error message:
> Fix parse of logo upload in groups management when the content type includes the charset encoding

- web-ui/src/main/resources/catalog/locales/en-search.json
- web-ui/src/main/resources/catalog/views/default/templates/recordView.html
Depending on the profil of the user, the message is adapted. Three possibilities are : 
- the user is not logged (current warning)
- the user is logged as administrator
- the user is logged as registered user or reviewer or editor or user administrator
Related to https://github.com/geonetwork/core-geonetwork/issues/4882. In the present improvement, the message to the registered user, reviewer, editor and user administrator doesn't give information about the existence of the metadata in the catalogue (restriction on the metadata).
> Update message if metadata is not found

- web-ui/src/main/resources/catalog/components/search/formfields/FormFieldsDirective.js
- web-ui/src/main/resources/catalog/templates/admin/classification/thesaurus.html
This fixes the thesaurus UI to use keywords from ISO19115-3.2018 `mri:MD_KeywordTypeCode` rather than ISO19139 `gmd:MD_KeywordTypeCode`.
> Update Thesaurus keywords to ISO19115-3.2018

- core/src/main/java/jeeves/interfaces/ApplicationHandler.java
- core/src/main/java/jeeves/monitor/MonitorManager.java
- core/src/main/java/jeeves/server/JeevesEngine.java
- core/src/main/java/jeeves/server/context/ServiceContext.java
- core/src/main/java/jeeves/server/dispatchers/ServiceManager.java
- core/src/main/java/org/fao/geonet/GeonetContext.java
- core/src/main/java/org/fao/geonet/api/records/attachments/AbstractStore.java
- core/src/main/java/org/fao/geonet/kernel/DataManager.java
- core/src/main/java/org/fao/geonet/kernel/IndexMetadataTask.java
- core/src/main/java/org/fao/geonet/kernel/ThesaurusManager.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataIndexer.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/HarvestManagerImpl.java
- services/src/main/java/org/fao/geonet/api/records/backup/BackupArchiveApi.java
- services/src/test/java/org/fao/geonet/api/records/formatters/groovy/FunctionsTest.java
- web/src/main/java/org/fao/geonet/Geonetwork.java
This pull request is working on addressing issues reported by previous service context PR, which now cleans up service context, and logs some messages when service context is handled in an unexpected way.
* Carefully treating the AppHandler service context created by Jeeves for use during init. This AppHandler service context is now cleaned up during Jeeves shutdown (so it is still available for initialization tasks that have been started in separate threads). I have placed some warnings if this shared AppHandler service context is configured by any of the tasks (as this would result in side effects for other tasks).
* Monitor now maintains a service context for use by the health checks. Previously these were using the Jeeves AppHandler service context
* We noticed during testing that …
> Keep service context independent to address user session null pointer exceptions

- web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/style/gn.less
- web-ui/src/main/resources/catalog/templates/top-toolbar-accessible.html
- web-ui/src/main/resources/catalog/views/default/less/gn_navbar_default.less
- web-ui/src/main/resources/catalog/views/default/templates/index.html
- web/src/main/webapp/xslt/base-layout.xsl
Replaces PR https://github.com/geonetwork/core-geonetwork/pull/5066
This PR adds a new menubar targeted at accessibility. It's clickable and not opening on hover anymore. This means you can now access with a keyboard (`tab`, `arrow` and `enter` keys). 
Extra attention has been paid to the focus state of the elements, it's now more clear which menu item has the focus.
You can activate this toolbar with a setting in the admin:
Changes made:
- settings in admin
- new toolbar HTML file
- fix for logo and name padding glitches
- fix for all menubars on smaller tablet sizes
> [a11y] New version of: Add a new accessible menubar: clickable and keyboard accessible

- core/src/main/java/org/fao/geonet/kernel/datamanager/draft/DraftMetadataManager.java
It caused an error in the schema upgrade process when applied to the draft metadata. Other code using this method with the draft metadata would get the same issue.
> Fix draft metadata manager update method to check if should be applied to the draft metadata or the published metadata.

- common/src/main/java/org/fao/geonet/ZipUtil.java
- common/src/main/java/org/fao/geonet/utils/BinaryFile.java
@juanluisrp @jodygarnett 
This is related to https://github.com/geonetwork/core-geonetwork/issues/5479 that we discussed about memory issue. So the workaround is to have tempFile enabled. I tested from my local and works as expected.
> Update ZipUtil.java to use tempFile configuration to avoid memory issue

- web-ui/src/main/resources/catalog/style/gn.less
- web/src/main/webapp/xslt/common/utility-tpl-metadata.xsl
Fix for #5520
Before
After
See #5520 for other screenshots of the issue.
This fix will better accommodate cases where the schematron name is long.
> Updated schematron name on error messages so that it does not overlap.

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
- schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
If specification date it's empty, it was causing an error in the indexing:
```
ERROR [geonetwork.index] - Document with error #4a03a3a9-32e7-4712-a9ee-c2789266794d: ElasticsearchException[Elasticsearch exception [type=mapper_parsing_exception, reason=failed to parse field [specificationConformance.date] of type [date] in document with id '4a03a3a9-32e7-4712-a9ee-c2789266794d'. Preview of field's value: '']]; nested: ElasticsearchException[Elasticsearch exception [type=illegal_argument_exception, reason=cannot parse empty date]];.
```
> Fix specification conformance indexing if date is empty. Avoid indexing the conformance if title is empty

- web-ui/src/main/resources/catalog/components/common/map/mapService.js
Some services return an empty value in the layer title. Not an expert in WMS, but doesn't seem a good practice as the element is mandatory. In this case it's returned, but empty. See:
http://geodata.rivm.nl/geoserver/wms?request=GetCapabilities&service=WMS&version=1.3.0
```
<Layer queryable="1" opaque="0">
<Name>gcn:depo_ntot_2013</Name>
<Title/>
<Abstract>Grootschalige Depositiekaart NL (2014): stikstof totaal depositie (Ntot) 2013 (berekening 2014)</Abstract>
<KeywordList>
```
In these cases the layer is displayed in the layer TOC panel but without a
Updated to display the layer name in these cases:
label:
> Add WMS layer - use layer name if the layer title is empty

- services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
Logs the real exception and returns a generic error message to the user:
> Generic error  message in 'Upload a file from URL'. Fixes #5535

- web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
Fix for https://github.com/geonetwork/core-geonetwork/pull/5469#discussion_r597593522
Fix for the `gn-status` field in the editor that was inheriting a class that messed up the layout
After the fix
> Fix for the layout of the `gn-status` field in the editor

- web-ui/src/main/resources/catalog/components/edit/datepicker/DatePickerDirective.js
When `gnGlobalSettings.gnCfg.mods.global.timezone` is set to Browser GN was launching
an warning about the timezone not being found:
```
Moment Timezone has no data for Browser. See http://momentjs.com/timezone/docs/#/data-loading/.
``` 
This commit fixes this message and sets properly the time offset suggested in the date picker timezone 
selector when the value for `gnGlobalSettings.gnCfg.mods.global.timezone` is `Browser`.
Before (in a browser in Europe/Madrid timezone):
After:
> Fix time offset when CatalogUiTimezone is Browser

- web/src/main/webapp/xslt/services/thesaurus/registry-to-skos.xsl
Seem the 'registry' part is different in some resgistries, like https://registry.gdi-de.org/codelist that uses 'codelist'.
To test: 
1) Add thesaurus from Registry configuring the url https://registry.gdi-de.org/codelist
2) Select English and German
3) Select the following registry item
4) The vocabulary has the terms from the https://registry.gdi-de.org/codelist registry
> Update check for INSPIRE registry valid items to create the RDF file. Fixes #4836

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/eng/labels.xml
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/fre/labels.xml
Because PNG is a very common image filetype. Implemented as a minor change to the iso19115-3.2018 localization files.
> Add option for PNG images to mcc:fileType 'Recommended values'

- core/src/main/java/org/fao/geonet/constants/Geonet.java
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
- schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
- web-ui/src/main/resources/catalog/js/edit/BatchEditController.js
- web-ui/src/main/resources/catalog/js/edit/EditorController.js
Currently the document standard indexing, used to relate a metadata record with a metadata schema, it's indexed in this template. Example for `iso19139`, see at the end of the snippet:
https://github.com/geonetwork/core-geonetwork/blob/7818588893f5e36581913a40cad73a2bf4906889/schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl#L96-L146
Custom schemas based on `iso19139` must define this full template, even for a the single change of the document standard, making maintenance of the file more difficult to keep in synch the changes with `iso19139`.
With this change, the indexing is done in Java code (as was done for the old `schema` field, to work with any schema without having to explicitly specify the field in the indexing xsl of each schema.
> Index documentStandard field (metadata standard) in Java code and remove the old schema field name, not used anymore.

- core/src/main/java/org/fao/geonet/api/exception/FeatureNotEnabledException.java
- core/src/main/java/org/fao/geonet/api/exception/ForbiddenException.java
- core/src/main/java/org/fao/geonet/api/exception/GeoPublisherException.java
- core/src/main/java/org/fao/geonet/api/exception/NoResultsFoundException.java
- core/src/main/java/org/fao/geonet/api/exception/NotAllowedException.java
- core/src/main/java/org/fao/geonet/api/exception/ResourceAlreadyExistException.java
- core/src/main/java/org/fao/geonet/api/exception/ResourceNotFoundException.java
- core/src/main/java/org/fao/geonet/api/exception/WebApplicationException.java
- core/src/main/java/org/fao/geonet/exceptions/LocalizedException.java
- core/src/main/java/org/fao/geonet/exceptions/LocalizedRuntimeException.java
Fix issue with localized exception where with* functions were returning LocalizedException instead of the class. i.e. ResourceNotFoundException
Fix issue from #5323
The following
https://github.com/geonetwork/core-geonetwork/blob/a2ada8b830d0bdb937e1846432376267d41cd402/core/src/main/java/org/fao/geonet/api/records/attachments/AbstractStore.java#L111-L113
Is throwing an LocalizedException exception instead of a ResourceNotFoundException but since the function throws a generic Exception, the issue was not initially caught.
This fix correct the issue so that the with* functions return the proper exception such as ResourceNotFoundException in the example above.
An attempt was made to use generic class in the abstract class such as the following
`public <T extends LocalizedException> T …
> Fix issue with localized exception where with* functions were returning LocalizedException instead of the class

- web/src/main/webapp/xslt/base-layout-cssjs-loader.xsl
- web/src/main/webapp/xslt/common/base-variables.xsl
`angularjs-recaptcha` loads the recaptcha api.js file if detects it's not loaded already.
If the recaptcha feature is disabled in the settings this is not desirable as does not fit with cookie statements.
This pull request adds a dummy object that `angularjs-recaptcha` checks to decide if the recaptcha api.js file should be loaded, to prevent the file from loading when the function is disabled in settings.
> Avoid loading Recaptcha API by angular-recaptcha if Recaptcha is disabled in the settings

- web-ui/src/main/resources/catalog/components/admin/registry/partials/registrybrowser.html
- web-ui/src/main/resources/catalog/style/gn_admin.less
This PR improves the styling and adds multiple columns to the language list in the `Create Thesaurus Window`. Before this, the list could be very long and pushing other content out of the view
**The list after the changes:**
> Styling and multiple columns for the language list in the `Create Thesaurus Window`

- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/js/LoginController.js
- web-ui/src/main/resources/catalog/style/gn.less
- web-ui/src/main/resources/catalog/templates/top-toolbar-accessible.html
The changes to the accessibility of the menu do prevent to click on the login option to go to the login page. Not going to the login page also prevents a user from registering or asking for a new password.
This PR adds the options to the login menu (when activated in the settings):
- register: open the register page
- forgot password: go to login page and open the 'lost password' panel
**The 'new' login popup**
> Add `register` and `lost password` option to accessible login menu

- web-ui/src/main/resources/catalog/components/utility/partials/batchreport.html
- web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
When a report is shown after a batch operation it can be long (for example for validating) and the modal window it's in 'falls' off the screen. This PR adds a scrollbar and `max-height` for the content of the modal window.
Some extra styles are added to minimize the whitespace some more and improve the display of error messages.
**The modal after the changes**
> Improved Modal dialog for batch reports

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html
To enable the values from the thesaurus, configure in https://github.com/geonetwork/core-geonetwork/blob/master/schemas/iso19139/src/main/plugin/iso19139/config/associated-panel/default.json, the key `thesaurus` with the thesaurus identifier:
```
"fields": {
"protocol": {
"value": "",
"isMultilingual": false,
"required": true,
"tooltip": "gmd:protocol",
"thesaurus": "external.theme.httpinspireeceuropaeumetadatacodelistProtocolValue-ProtocolValue"
},
```
> Add support to retrieve online resource protocol from a vocabulary in the metadata editor online resources panel

- web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/mapconfig.html
- web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/projectionSwitcher.html
- web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
- web-ui/src/main/resources/catalog/templates/admin/settings/system.html
- web-ui/src/main/resources/catalog/templates/admin/settings/ui.html
- web-ui/src/main/resources/catalog/views/default/less/gn_admin_default.less
Improved visual hierarchy in admin settings and user interface settings
Improvements:
- use of `<h1>`, `<h2>` and `<h3>`
- use larger font for headings higher in the hierarchy
- add label after `add` icon and make it a button
- add borders around tables and editors
> Improved visual hierarchy in admin settings and user interface settings

- core/src/main/java/org/fao/geonet/kernel/Thesaurus.java
- core/src/test/java/org/fao/geonet/kernel/AbstractThesaurusBasedTest.java
- core/src/test/java/org/fao/geonet/kernel/AllThesaurusTest.java
- core/src/test/java/org/fao/geonet/kernel/ThesaurusTest.java
- core/src/test/java/org/fao/geonet/kernel/search/TermUriTranslatorTest.java
- core/src/test/java/org/fao/geonet/kernel/search/classifier/TermLabelTest.java
- core/src/test/java/org/fao/geonet/kernel/search/classifier/TermUriTest.java
- services/src/main/java/org/fao/geonet/services/thesaurus/Add.java
- web-ui/src/main/resources/catalog/js/admin/ThesaurusController.js
- web-ui/src/main/resources/catalog/templates/admin/classification/thesaurus.html
Remove hard coded references to `http://custom.shared.obj.ch/concept#`, `http://geonetwork-opensource.org/` and `http://www.mysite.org/thesaurus` which are defaults when creating a local thesaurus from the admin without taking time to customize the value properly.
Defaults are now using the GeoNetwork API path, so the namespace will point to the thesaurus download link.
Also namespace is preserved if you export and import the thesaurus in another instance.
> Thesaurus / Use API path for default namespace.

- services/src/main/java/org/fao/geonet/api/registries/vocabularies/KeywordsApi.java
If a keyword contains a "+" sign, it will be escaped as a space character.
Related: https://github.com/geonetwork/core-geonetwork/pull/5477
> Fix escaped "+" in keyword identifier

- core/src/main/java/jeeves/server/dispatchers/ServiceManager.java
- core/src/main/java/jeeves/server/local/LocalServiceRequest.java
- core/src/main/java/jeeves/server/sources/ServiceRequest.java
Issue found testing https://github.com/geonetwork/core-geonetwork/pull/5526 , although not related to the pull request change, when exporting to MEF format a metadata selection including a file of 3.3 Gb.
The file size should be managed as an `Long`. 
In any case, this code seem only used for `LocalServiceRequest` class, in `ServiceRequest` the method implementation is empty, should be review if `LocalServiceRequest` is used, otherwise to clean up.
> Use long instead of int to retrieve file size in Jeeves ServiceManager

- domain/src/main/java/org/fao/geonet/domain/Setting.java
- domain/src/main/java/org/fao/geonet/domain/SettingToObjectSerializer.java
- web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js
- web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v3110/migrate-default.sql
This PR allows to configure settings to prevent to edit them in the settings UI. Currently we have the setting `system/userFeedback/lastNotificationDate` that was hardcoded in the angularjs settings controller.
It can be relevant for GeoNetwork instances provided in a hosted cloud environment, where it's required that the GeoNetwork administrator can't change certain settings like server configuration: host, port or proxy server settings.
Changing the `editable` field of a setting to the value `false` prevent the setting to be displayed in the settings UI. For example for the server host / protocol /port:
Compared to the default configuration:
> Support for non-editable settings

- schemas/iso19110/src/main/plugin/iso19110/formatter/xsl-view/view.xsl
- schemas/iso19110/src/main/plugin/iso19110/layout/config-editor.xml
- schemas/iso19110/src/main/plugin/iso19110/layout/layout.xsl
- schemas/iso19110/src/main/plugin/iso19110/loc/eng/labels.xml
- schemas/iso19110/src/main/plugin/iso19110/present/metadata-view.xsl
- schemas/iso19110/src/main/plugin/iso19110/schema-suggestions.xml
- schemas/iso19110/src/main/plugin/iso19110/templates/metadata.xml
adds some missing translations
hides generic titles (carierofcharacteristics) and displays more specific (fc_featureattribute)
makes anchors clickable links in formatter
adds definition field when adding listvalue
i tried to use data-gn-anchor-switcher on gfc:code, but it seems not able to store anchors
> Improvements fc editor

- web-ui/src/main/resources/catalog/locales/en-core.json
- web-ui/src/main/resources/catalog/templates/signin.html
It's possible for a logged-in user to visit the `signin` page again. The user would then see the same login options as a not logged-in user. That causes confusion.
This PR shows a logout option for logged-in users, and keeps the login option for other users.
> Add a logout option for a logged-in user

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/config/associated-panel/default.json
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/utility-tpl.xsl
- schemas/iso19139/src/main/plugin/iso19139/layout/utility-tpl.xsl
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html
- web-ui/src/main/resources/catalog/components/metadataactions/RelatedDirective.js
- web-ui/src/main/resources/catalog/components/metadataactions/RelatedResourcesService.js
- web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
- web-ui/src/main/resources/catalog/components/metadatamanager/EditorService.js
- web-ui/src/main/resources/catalog/components/search/formfields/FormFieldsDirective.js
- web-ui/src/main/resources/catalog/components/search/formfields/partials/schemainfocombo.html
- web-ui/src/main/resources/catalog/locales/en-v4.json
- web-ui/src/main/resources/catalog/views/default/less/gn_result_default.less
- web/src/main/webapp/xslt/ui-metadata/edit/edit.xsl
User populates distribution format eg. ESRI Shapefile and Mapinfo MIF/MID 
Then when adding an online source (using the associated resources panel), the list of protocols shows:
* ISO 19139
* First the list of formats defined in distribution. The value is "WWW:DOWNLOAD:ESRI Shapefile"
* then the list of protocols defined in the schema configuration
* ISO 19115-3 (which provides a menu to add new online resource)
*  Access the resource section, contains first as many items as formats declared in distribution section
* KML protocol choices are removed as they have to be declared as a format to be added as online resource.
Record view render format as a badge when defined
* When editing existing online source, don't loose protocol value.
Work done in the context of https://geocat.ch
> Editor / List formats as protocols.

- web/pom.xml
On startup:
```
[INFO] Web overrides =  none
[INFO] web.xml file = /projects/core-geonetwork/web/target/WEB-INF/web.xml
[INFO] Webapp directory = /projects/core-geonetwork/web/target/geonetwork
```
The path ` /projects/core-geonetwork/web/target/WEB-INF/web.xml` is not valid, should be ` /projects/core-geonetwork/web/target/geonetwork/WEB-INF/web.xml`
> Build / Fix path for web.xml for maven Jetty plugin

- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/update-fixed-info.xsl
* Set the update date to the same date as in the database.
* In ISO19115-3, also set record creation date from the database date.
The issue here is that if you duplicate an ISO19115-3 records, the create date of the record is the one from the copy.
This change allow user to remove the creation date in the editor and then the db date is used to set the value. Not an optimal option.
@josegar74 any other suggestion to handle that case?
> Update-fixed-info / Use db dates 

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/present/csw/csw-brief.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/present/csw/csw-full.xsl
- schemas/iso19139/src/main/plugin/iso19139/present/csw/csw-brief.xsl
- schemas/iso19139/src/main/plugin/iso19139/present/csw/csw-full.xsl
The crs definition which was used is an indicator of the crs used in the dataset. However the bbox is 'always'(?) expressed in 4326, so it made no sense to use that crs as indicator for the bounds projection.
Mind that urn:ogc:def:crs:EPSG:6.6:4326 indicates yx axis order
Fixes #5545
> in csw-full xml, record crs should not be linked to bounds crs

- services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
The previous code was deleting the privileges before retrieving the previous value in `setOperations`, sending to the `RecordPrivilegesChangeEvent` a wrong value.
https://github.com/geonetwork/core-geonetwork/blob/489a7dfecb473de1930173f45a97ad59df4956ba/services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java#L266-L277
https://github.com/geonetwork/core-geonetwork/blob/489a7dfecb473de1930173f45a97ad59df4956ba/services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java#L381-L397
> Fix the privileges value before the update for RecordPrivilegesChangeEvent in metadata sharing API

- domain/src/main/java/org/fao/geonet/entitylistener/HarvesterSettingValueSetter.java
- domain/src/main/java/org/fao/geonet/entitylistener/SettingValueSetter.java
This issue was causing that the siteId was not persisted when starting up the application with a new database.
> Fix PreUpdate event in settings listeners. Related to #5476

- web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
Fix for heading / label mixup in User Interface settings
See PR: https://github.com/geonetwork/core-geonetwork/pull/5487
Resolved by splitting the heading into a label within a heading:
`<h2><label> ...... </label></h2>`
> Fix for heading / label mixup in User Interface settings

- web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_variables_default.less
Fix for too small privileges popup (some languages have wider labels than others). Fixed by increasing the default Bootstrap width of medium wide `modals`.
Issue: https://github.com/geonetwork/core-geonetwork/issues/5590
**After the fix**
> [5590] Fix for too small privileges popup in Metadata page

- web-ui/src/main/resources/catalog/views/default/templates/recordView.html
After the a11y changes to the toolbar the `delete` button was accidentally placed on the wrong location. This PR fixes this.
Extra: added `href` to the `rss` button to make it accessible by `tab` key
**Before**
**After**
> Change the order of the buttons in the second toolbar of the metadata view

- web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
**Before:**
**After:**
**To test:**
1. Enable `INSPIRE` in the settings.
2. Create an iso19139 metadata with the default template.
3. Switch to the `INSPIRE` view and find the section `Responsible organization (s)`
> Metadata editor - fix rendering of codelists in template fields

- pom.xml
- web/src/main/java/org/fao/geonet/proxy/URITemplateProxyServlet.java
- web/src/main/webResources/WEB-INF/web.xml
- web/src/main/webapp/WEB-INF/config-security/config-security-core.xml
- web/src/main/webapp/WEB-INF/config-security/config-security-mapping.xml
In order to expose one or more microservice (See https://github.com/geonetwork/geonetwork-microservices) behing GeoNetwork, a proxy is set to redirect all calls made to `/api' to the microservices.
eg. with OGC API Records
Configuration for microservices in order to use the GeoNetwork URL in response of `servletRequest.getRequestURL()`, `X-Forwarded-*` headers are set:
```
server.forward-headers-strategy: FRAMEWORK
gn.baseurl: http://localhost:8080/geonetwork/api
```
In the long run, we will have to define a strategy to move part of the API calls to the microservice gateway (and/or the other way around).
> Proxy / Add proxy for microservices.

- web-ui/src/main/resources/catalog/js/CatController.js
Some numbers are displayed on home page and admin home page with the total number of records. If a filter is set in the UI configuration eg.
```json
'filters': [
{
"query_string": {
"query": "isHarvested:false"
}
}
],
```
the filter was not applied.
> UI config / Apply filter to main statistics

- web-ui/src/main/resources/catalog/components/viewer/gfi/GetFeatureInfoDirective.js
It does not really make sense to query the background layers. By default it does nothing because of usage of OSM layer but if the default map is based on one or more WMS/ArcGIS layers then they appear in GFI results.
Exclude all background layers when querying the map.
> Map / GetFeatureInfo / Don't query background

- web-ui/src/main/resources/catalog/components/edit/bounding/partials/boundingpolygon.html
- web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
Related to https://github.com/geonetwork/core-geonetwork/pull/5399
I don't know if that PR has to go first (thought it was already merged)
This PR creates a uniform view for the 'draw geometry' maps in the editor.
**The view after the changes**
**It now has the same look as the 'draw box' map**
> Uniform view for the bounding geometries in the Editor

- services/src/main/java/org/fao/geonet/api/regions/RegionsApi.java
- services/src/main/java/org/fao/geonet/api/regions/ThesaurusBasedRegionsDAO.java
- web-ui/src/main/resources/catalog/components/utility/UtilityService.js
Regions thesaurus is available in English and French, the metadata editor widget to search for regions return empty values if the UI is used in other languages.
This pull request, uses the values in the default values (English) in these cases:
> Use default language for regions if not available in the UI language

- healthmonitor/src/main/java/org/fao/geonet/monitor/health/IndexReadOnlyHealthCheck.java
- healthmonitor/src/main/java/org/fao/geonet/monitor/health/NoIndexErrorsHealthCheck.java
- web-ui/src/main/resources/catalog/js/admin/DashboardStatusController.js
- web-ui/src/main/resources/catalog/locales/en-v4.json
- web-ui/src/main/resources/catalog/templates/admin/dashboard/status.html
- web/src/main/webapp/WEB-INF/config/config-service-monitoring.xml
* When index is in readonly mode (eg. when disk usage is too high), new record will not be created properly - at least added in db but not indexed. No error where reported at GN level, only in logs. Add a specific health check indicating if index is in read only mode (search are still working - only operation requiring indexing may fail).
* Add indicator about number of records in db and in index in order to check if there is any synchronization issue between index and database.
> Index health check improvements

- software_development/DEVELOPMENT.md
Fix some small typing errors in the `Development` document
> Fix typos in `Development` document

- web/src/main/java/org/fao/geonet/DatabaseMigration.java
Only commit the database migration connection when the connections is not autocommit=true.
When using a JNDI connection the connection obtained from the ((JpaTransactionManager) bean).getDataSource()
has autoCommit set to true and cause this error:
```
java.lang.RuntimeException: org.postgresql.util.PSQLException: Cannot commit when autoCommit is enabled.
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
```
> Fix autocommit error when using a JNDI connection

- add-schema.sh
Schema `groupId` added in `services/pom.xml` should be `org.geonetwork-opensource.schemas`, not `org.geonetwork-opensource`.
> Fix add-schema script

- web-ui/src/main/resources/catalog/views/default/templates/home.html
The homepage was missing icons for the topics, this PR fixes this.
**The missing icons**
Fixes:
- removed to `toLowerCase` on icon class names
- changed check on a key name
> Fix for missing icons for the topics on the homepage

- web-ui/src/main/resources/catalog/components/search/searchmanager/LocationService.js
When loading page with param old path is '' and restoreSearch must not be called as it clear params.
Test:
* Do a search with full text search
* Reload page
* Expected : params are preserved.
> Search / Reload page with param does not restore query

- web-ui/src/main/resources/catalog/templates/top-toolbar.html
> Use display catalogue name in the header setting to display/hide the catalogue name in small devices

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/ISO19139/toISO19139.xsl
Current mapping may produce invalid ISO19139 record
```xml
<mri:status>
<mcc:MD_ProgressCode codeList="http://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#MD_ProgressCode"
codeListValue="obsolete"/>
</mri:status>
<mri:status>
<mcc:MD_ProgressCode codeList="http://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#MD_ProgressCode"
codeListValue="superseded"/>
</mri:status>
```
produce 19139 with `obsolete superseded` instead of 2 gmd:status element
```xml
<gmd:status>
<gmd:MD_ProgressCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_ProgressCode"
codeListValue="obsolete superseded">obsolete superseded</gmd:MD_ProgressCode>
</gmd:status>
```
> ISO19139 / Mapping / Codelist may have multiple values

- web-ui/src/main/resources/catalog/templates/editor/import.html
This PR restyles the list of imported files a bit, main feature is to truncate file names, so the filename don't 'break' through the boundaries of the list they're in.
Additional changes:
- reduce whitespace and padding
- wider column for the options
**The new file list**
> Restyling of the imported file list

- schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields-keywords.xsl
When defined the thesaurus titles with multilingual values:
```
<dc:title>GEMET - INSPIRE themes, version 1.0</dc:title>
<dc:title xml:lang="en">INSPIRE themes</dc:title>
<dc:title xml:lang="sv">INSPIRE thema</dc:title>
```
The non-multilingual value is used for the thesaurus name element, as usual. With this change, in the metadata editor the thesaurus section is labeled as `INSPIRE themes` in English and `INSPIRE thema` in Swedish, instead of `GEMET - INSPIRE themes, version 1.0`. 
For other UI languages not defined in the thesaurus it is displayed the non-multilingual title `GEMET - INSPIRE themes, version 1.0`.
> Use thesaurus multilingual value for thesaurus, if available, to display the title in the metadata editor

- web-ui/src/main/resources/catalog/views/default/less/gn_admin_default.less
This PR fixes the harvester badge displaying on new line on (really) small screens.
**The badge on a new line**
> Fix for harvester badge displaying on new line

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFilesystemHarvester.java
Script option can be unsecured and needs improvement to limit to scripts that have been checked by catalog admin.
@cmangeat not sure if you have resource to improve that (as it is used in geocat.ch) and limit it to scripts that are defined in the data directory only ? We will turn it off for now in coming release.
> Harvester / Localfile / Disable script option.

- core/src/main/java/org/fao/geonet/kernel/mef/Importer.java
Test case:
1) Backup a catalogue with templates using http://localhost:8080/geonetwork/doc/api/index.html#/records/trigger
2) Download the catalogue backup http://localhost:8080/geonetwork/doc/api/index.html#/records/downloadBackup
3) Import the catalogue backup in other instance --> An error `Metadata is not supported. UUID is not defined.` is reported
This is caused in https://github.com/geonetwork/core-geonetwork/blob/54b3ac3411b40c3da5c9de438fbe6ea37b1d2471/core/src/main/java/org/fao/geonet/MetadataResourceDatabaseMigration.java#L163-L165 when importing templates, as usually the `gmd:fileIdentifier` is empty for templates.
Updated the code in the import process to catch the exception and ignore it, as it's not really an error, otherwise the import process stops and the rest of the …
> Metadata import - catch update metadata resources link exception with metadata templates and avoid stopping the import process

- web-ui/src/main/resources/catalog/components/edit/FieldsModule.js
- web-ui/src/main/resources/catalog/components/edit/multientrycombiner/MultiEntryCombinerOnlineResourcesDescription.js
- web-ui/src/main/resources/catalog/components/edit/multientrycombiner/partials/multientrycombiner_onlineresourcesdescription.html
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html
- web-ui/src/main/resources/catalog/components/thesaurus/ThesaurusDirective.js
- web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
Add a new `gnMultientryCombinerOnlineResourcesDescription` for use in the add online resource
panel. It allows to show one original field as multiple fields, combining the values of
these ones back into the original one when the resource is added.
Check the comments in about the usage.
This directive allows for a single metadata-field to be broken up into multiple fields on the add online resource dialog.
In the metadata schema, this is just a string.
However, it is to be formatted like;
`"Government of Canada; Organization of Public Services and Procurement Canada; Defence and Marine Procurement"`
The first bit `"Government of Canada"` is HARD CODED
The second bit `"Canadian Environmental Assessment Agency"` is a Thesaurus Keyword Picker
The third bit "Defence and Marine Procurement" is …
> Add a new directive for combining add online resource fields

- web/src/main/webapp/xslt/common/index-utils.xsl
The anchor may be used for multilingual purpose when UI is in a language not defined in record but available in thesaurus. eg. Here for russian
> Index / Keyword / Add link property if the keyword is in a thesausur

- web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
In the editor the arrow of the panels is always the same, when it's collapsed or not.
This PR fixes it, the arrow is different now when the panel is collapsed.
**Before**
**After**
> Fix for the panel arrow in the collapsed state in the Editor

- web-ui/src/main/resources/catalog/components/utility/UtilityService.js
eg. split a field with "SPW - DGO3 - DEE - DPP" by a separator " - "
```json
'custodianOrgForResource_tree': {
'terms': {
'field': 'custodianOrgForResource_tree',
'include': 'SPW.*',
'size': 35,
"order" : { "_key" : "asc" }
},
"meta": {
"treeKeySeparator": " - "
}
},
```
> Aggregation / Tree / Substitute separator even if not translated.

- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
Current lang variable in redirecting url consists of three characters (i.e. eng, fre) which is not integrated well with other system. isoLang variable is added to retrieve such language code (i.e. en, fr).
> Add isoLang (i.e. en, fr) into a link.

- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
- web/src/main/webapp/xslt/common/utility-tpl.xsl
* Replace recursive xslt templates to add breaklines and hyperlinks in metadata detail page (full view), to use pattern matching to avoid stack overflow for texts with many breaklines
* Update templates to manage breaklines to preserve all the breaklines
https://github.com/geonetwork/core-geonetwork/pull/5446
Co-authored-by: Jose García <josegar74@gmail.com>
Co-authored-by: Francois Prunayre <fx.prunayre@gmail.com>
> Formatter / Improve rendering of line breaks, hyperlinks and email links

- web/src/main/webapp/WEB-INF/config-security/config-security-keycloak.xml
When using Geonetwork integrated with Keycloak, the CSRF token is not set, resulting in security vulnerabilities.
This adds csrfFilter to lists of filters that missed it.
Same as #5672 just for 4.0.x
> Keycloak set csrf

- web/src/main/webapp/WEB-INF/config-security/config-security-keycloak.xml
When using Geonetwork integrated with Keycloak, the CSRF token is not set, resulting in security vulnerabilities. 
This adds csrfFilter to lists of filters that missed it.
> Keycloak set csrf 3.12.x

- web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js
- web-ui/src/main/resources/catalog/components/metadataactions/partials/statusupdater.html
* Status change / Don't assign task to someone if notification level is admin 
* Fix popup label 'mdstatus-undefined' for tasks
* Use full width for the form
> Status change / Improvements

- common/src/main/java/org/fao/geonet/utils/Xml.java
- core/src/main/java/org/fao/geonet/kernel/EditLib.java
- core/src/main/java/org/fao/geonet/util/XslUtil.java
- schemas/config-editor.xsd
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/config-editor.xml
- schemas/iso19139/src/main/plugin/iso19139/index-fields/index-subtemplate.xsl
- schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
- schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields-keywords.xsl
- schemas/iso19139/src/main/plugin/iso19139/layout/layout.xsl
- web-ui/src/main/resources/catalog/components/edit/FieldsDirective.js
- web-ui/src/main/resources/catalog/components/edit/bounding/BoundingDirective.js
- web-ui/src/main/resources/catalog/components/edit/directoryentryselector/DirectoryEntrySelector.js
- web-ui/src/main/resources/catalog/components/edit/directoryentryselector/partials/directoryentryselector.html
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
- web-ui/src/main/resources/catalog/components/metadatamanager/EditorService.js
- web-ui/src/main/resources/catalog/components/thesaurus/ThesaurusDirective.js
- web-ui/src/main/resources/catalog/components/thesaurus/ThesaurusService.js
- web-ui/src/main/resources/catalog/components/thesaurus/partials/keywordselector.html
- web-ui/src/main/resources/catalog/lib/bootstrap.ext/typeahead.js/typeahead.bundle.js
- web/src/main/webapp/xslt/ui-metadata/edit/edit.xsl
- web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
* Side panel can now contain sections
* Add possibility to use the virtual all thesaurus to populate simple keyword structure 
* Add xpath mode to gnKeywordSelector directive
* Fix XML API edits (trim XML snippet, detect self closing tags, ignore gn_delete tag)
* Add a new taginput mode to be able to populate contact like keywords
To enable it use the following configuration.
```xml
<for name="dct:creator" addDirective="data-gn-directory-entry-selector">
data-template-type="contact"
data-element-xpath="./dcat:Dataset/dct:creator"
data-max-tags="1"
data-insert-modes="tags"
data-values="xpath::string-join(.//dct:creator/@xlink:href, '◿')"
data-default-role="creator"
data-transformation="contact-from-iso19139-to-foaf-agent"/>
</for>
```
In this mode, encoding is made …
> Editor improvements related to DCAT support

- core/src/main/java/org/fao/geonet/kernel/ApplicableSchematron.java
- core/src/main/java/org/fao/geonet/kernel/SchematronValidator.java
- doi/src/main/java/org/fao/geonet/doi/client/DoiClient.java
- doi/src/main/java/org/fao/geonet/doi/client/DoiManager.java
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/eng/schematron-rules-datacite.xml
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/fre/schematron-rules-datacite.xml
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/doi-add.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/schematron/schematron-rules-datacite.sch
- schemas/iso19139/src/main/plugin/iso19139/loc/eng/schematron-rules-datacite.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/fre/schematron-rules-datacite.xml
- schemas/iso19139/src/main/plugin/iso19139/process/doi-add.xsl
- schemas/iso19139/src/main/plugin/iso19139/schematron/schematron-rules-datacite.sch
- web-ui/src/main/resources/catalog/components/history/partials/historyStep.html
* Improve insert point when using online resource. Some records may not have gmd:onLine. Insert into first distribution section and add an extra transfert option for the DOI.
* ISO19115-3 / Add example to insert DOI in online resource (default is resource identifier)
* Add hyperlink in validation status response to easily preview the Datacite format
* Avoid hardcoded API - user may be using test env depending on configuration.
* Add Datacite schematron for easier check (XSD parser error are not that easy to solve by users).
* Check schematron rules from admin task management (Then XSD parser is used, so user will be able to easily identify which mandatory fields are missing first).
> DOI / Improvements

- workers/wfsfeature-harvester/src/main/java/org/fao/geonet/harvester/wfsfeatures/worker/EsWFSFeatureIndexer.java
- workers/wfsfeature-harvester/src/main/java/org/fao/geonet/harvester/wfsfeatures/worker/OwsUtils.java
Follow up of https://github.com/geonetwork/core-geonetwork/pull/5679 after testing mapserver
* Add Instant type support
* Handle error
```
2021-05-14 14:16:54,947 WARN  [geonetwork.harvest.wfs.features] - Error while creating document for surval_30140_all_point_19_12_2017 feature 7169. Exception is: Parsing failed for FeatureCollection: java.lang.RuntimeException: Unable to set property: boundedBy for eobject: {http://www.opengis.net/wfs/2.0}FeatureCollectionType
```
Relates to https://osgeo-org.atlassian.net/browse/GEOT-6682 - we probably have to update GeoTools too...
> Harvesting / WFS / Attributes / Instant type support

- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/views/default/less/gn_map_default.less
- web/src/main/webapp/xslt/base-layout.xsl
In GeoNetwork the height of the map is calculated assuming the footer is always present. However, in the admin it's possible to disable the footer. This results in the map having whitespace at the bottom
This PR adds a setting and styling for the map height when there is no footer.
**Before**
**After**
> Fix map height when there is no footer

- core/src/main/java/org/fao/geonet/kernel/setting/SettingManager.java
Password encryptor is initialised in `GeoNetwork.start` due to a dependency on `GeonetworkDataDirectory`.
Some beans, like `OpenApiConfig` or `SettingManager` `@PostConstruct` retrieve settings before the password encryptor is initialised, causing the value to be `null`. This causes that in Swagger UI the server gets a wrong value (null://null/:null). 
This PR returns in these cases the `storedValue`, that has the correct value. It doesn't solve the case for encrypted settings if would be required  before the password encryptor is initialised (not the case in the current code).
In the long term, initialisation of components should be moved outside of `GeoNetwork.start` to use Spring features, but will require some major refactor on some components.
> Fix retrieval of settings during the application startup if the encryptor is not initialised

- web-ui/src/main/resources/catalog/components/elasticsearch/EsFacet.js
- web-ui/src/main/resources/catalog/components/elasticsearch/directives/FacetDirective.js
- web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facet.html
- web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js
- web-ui/src/main/resources/catalog/components/search/searchmanager/partials/searchresults.html
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/js/admin/HarvestSettingsController.js
- web-ui/src/main/resources/catalog/locales/en-v4.json
- web-ui/src/main/resources/catalog/style/gn.less
- web-ui/src/main/resources/catalog/style/gn_search.less
- web-ui/src/main/resources/catalog/templates/admin/harvest/harvest-settings.html
- web-ui/src/main/resources/catalog/views/default/less/gn_admin_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_view.less
- web-ui/src/main/resources/catalog/views/default/templates/home.html
- web/src/main/webapp/xslt/base-layout-cssjs-loader.xsl
This PR adds a more visual summary (totals/graphs) to the harvest pages. 
After harvesting the harvest results are displayed more graphically:
Further improvements:
- settings/history/results in tabs
- added extra information in harvester list
- added extra classes to buttons
- Editor board / Fix facet on datestamp
> Harvester / Add visual summary (totals/graphs)

- web-ui/src/main/resources/catalog/components/elasticsearch/directives/FacetDirective.js
- web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facet-temporalrange.html
* Refresh range when manually changing inputs.
* Reset range when filter directive clear filters 
* Avoid error when config is minimal (ie. with no meta)
eg. 
```
"dateStamp" : {
"auto_date_histogram" : {
"field" : "dateStamp",
"buckets": 50
}
}
```
Also require https://github.com/geonetwork/core-geonetwork/pull/5646 which fix vega lib loading in editor board.
> Aggs / Temporal range improvements

- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/js/LoginController.js
- web-ui/src/main/resources/catalog/js/edit/EditorController.js
* Don't lose tab when signin is required. http://localhost:8080/geonetwork/srv/fre/catalog.edit#/metadata/1321?tab=xml should redirect to signin and then redirect to editor in XML (was default view).
* Add possibility to open editor using UUID.
> Editor / Open action improvements

- web-ui/src/main/resources/catalog/views/default/less/gn_admin_default.less
The admin pages have a padding for the content, the `Content Statistics` page with the Kibana dashboard doesn't need it. This PR removes this padding.
**Before**
**After**
> Statistics page in the admin without padding/whitespace

- services/src/main/java/org/fao/geonet/api/registries/DirectoryApi.java
.cgp file does not sound to be used when reading Shapefile. Add an option to set charset.
eg. to load shapefile
```
curl \
-H "Cookie: $COOKIE" \
-H "X-XSRF-TOKEN: $TOKEN" \
-H 'Content-Type: multipart/form-data' \
-H 'Accept: application/json' \
-F file=@g1g21.zip \
-X POST "$CATALOG/srv/api/registries/actions/entries/import/spatial?uuidAttribute=GMDNR&uuidPattern=geocatch-subtpl-extent-hoheitsgebiet-%7B%7Buuid%7D%7D&descriptionAttribute=GMDNAME&geomProjectionTo=EPSG%3A4326&lenient=true&onlyBoundingBox=false&process=build-extent-subtemplate&schema=iso19139&uuidProcessing=OVERWRITE&charset=UTF-8"
```
> Directory / Import entries from shape / Add charset parameters

- web-ui/src/main/resources/catalog/components/search/searchmanager/partials/searchresults.html
Issue introduced in https://github.com/geonetwork/core-geonetwork/pull/5646/files#r641479542
Before 
After (when selection is on, link is an icon on the right side)
> Search results / Adapt template if selection is on or not

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
Only applies to ISO19115-3 when linking to application for now but depends on the schema config.
Also fix title field name setter.
> Editor / Associated resource / Set description based on selected records

- web-ui/src/main/resources/catalog/components/search/resultsview/partials/selection-widget.html
- web-ui/src/main/resources/catalog/js/admin/DashboardRecordLinkController.js
* Fix selection of a set of records / validateMdLinks has one argument which is the bucket.
See https://github.com/geonetwork/core-geonetwork/blob/main/web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js#L160
* Fix table loading
> Link validation improvements

- healthmonitor/src/main/java/org/fao/geonet/monitor/health/DashboardAppHealthCheck.java
Don't use the proxy for health check which requires authenticated user and always return 200
> HealthCheck / Dashboard / Use config URL

- web-ui/src/main/resources/catalog/components/common/scrollspy/ScrollSpyDirective.js
Not sure since when but scroll spy does not work anymore in editor. Probably due to a change in DOM structure.
Tested in editor and settings ok.
> Scroll spy / Editor / Fix empty in editor

- web-ui/src/main/resources/catalog/components/elasticsearch/directives/FacetDirective.js
- web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facet-temporalrange.html
Also add a reset button (also available by double click the lower chart in vega default actions)
```
'resourceTemporalDateRange': {
'gnBuildFilterForRange': {
field: "resourceTemporalDateRange",
buckets: 2021 - 1990,
dateFormat: 'YYYY',
dateSelectMode: 'years',
vegaDateFormat: '%Y',
from: 1990,
to: 2021,
// buckets: 2021 - 2000,
// dateFormat: 'YYYY-MM-DD',
// vegaDateFormat: '%Y-%M-%D',
// from: 2000,
// to: 2021,
// mark: 'area'
},
'meta': {
'vega': 'timeline'
}
}
```
> Facet / Temporal range / Fix selection when using custom format eg. YYYY

- web-ui/src/main/resources/catalog/views/default/less/gn_admin_default.less
The admin of GeoNetwork has a left sidebar with animation. The animation and fast sequence of opening and closing can distract users. This PR removes the animation and adds tooltips for the labels
**The 'new' style**
> Remove left sidebar animation in Admin

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html
When you want to add an online resource and you open the 'online resource panel' only a button with an icon is shown.
This PR shows a label at the moment the dialog is opened, this button starts disabled, when you start typing the url, the button will be enabled.
> Show label on add resource button when the dialog is opened

- web-ui/src/main/resources/catalog/components/search/mdview/mdviewModule.js
On old record, groupOwner may also be null and current can be null in non debug mode
Related https://github.com/geonetwork/core-geonetwork/pull/5721
> Group / Restore possibility to use group logo / In non debug mode avoid JS error

- web-ui/src/main/resources/catalog/components/edit/fieldupload/FieldUploadDirective.js
When using the character `&` in the directive text fields, it was not encoded when added to the xml snippet that is created for the metadata element, causing an error.
> Fix encoding issue in field upload directive

- core/src/main/java/org/fao/geonet/lib/NetLib.java
A symptom was WFS harvesting was failing with obscure numberFormatException while parsing proxy port. This was only occurring if settings was saved and NetLib called. eg. https://github.com/geotools/geotools/blob/main/modules/plugin/http-commons/src/main/java/org/geotools/http/commons/MultithreadedHttpClient.java#L111 expects null and not ""
> Proxy / Properly unset properties if no proxy used.

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/onlinesrcList.html
- web-ui/src/main/resources/catalog/components/index/partials/datafilterview.html
- web-ui/src/main/resources/catalog/components/viewer/ViewerDirective.js
- web-ui/src/main/resources/catalog/components/viewer/wfsfilter/WfsFilterDirective.js
- web-ui/src/main/resources/catalog/components/viewer/wfsfilter/partials/wfsfilterfacet.html
Give more visibility to the WFS feature harvester. From the editor, user can trigger WFS feature indexing. Once complete, they can preview the layer on the map. If the feature type is not found, the widget is not displayed.
The same directive is used in the map viewer:
> WFS feature harvester / Manage from editor.

- web/src/main/webapp/xslt/common/utility-tpl.xsl
Issue introduced in https://github.com/geonetwork/core-geonetwork/pull/5446
An XSL formatter applied to a multilingual record always display all languages.
eg. 
http://localhost:8080/geonetwork/srv/api/records/b07a4589-159b-4c3a-b1e7-dbdad11f7e62/formatters/xsl-view?view=advanced&language=fre MUST display French and fallback to main language
> Formatter / Multilingual support / Can't define the language anymore

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html
See: https://github.com/metadata101/iso19139.ca.HNAP/issues/95#issuecomment-834367770
When adding an `online resource` for the HNAP profile the description block is not indented like the rest, this PR fixes this.
**The not indented block**
> Fix for indenting the 'online resource description`

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
To disable the automatic processing, configure in the schemas file `config/associated-panel/default.json` the setting `loadMapCapabilities` to false, any other value will allow the OGC Capabilities layer processing:
```json
{
"config": {
"display": "radio",
"loadMapCapabilities": "false",
```
No changes are required in the schemas, as by default the map layers processing is enabled.
GeoNetwork adds the layer name in the `gmd:name` field, this is a convention used in GeoNetwork, but some schemas like https://github.com/metadata101/iso19139.ca.HNAP use other convention that causes the online resource to be broken when edited if the GeoNetwork process the OGC layers.
This is a temporary fix to avoid the previous issue, until the online resource panel is extended to provide the flexibility to …
> Metadata editor - option to disable OGC Capabilites layer processing in the online resource panel.

- core/src/main/java/org/fao/geonet/api/records/attachments/CMISStore.java
- core/src/main/java/org/fao/geonet/api/records/attachments/FilesystemStore.java
- core/src/main/java/org/fao/geonet/api/records/attachments/JCloudStore.java
- core/src/main/java/org/fao/geonet/api/records/attachments/S3Store.java
As identified in PR 5686, the file stores can be cleaner by autowiring the settingManager.
This PR is to refactor the code to autiwire the settingManager bean.
Please back port this change to 3.12.x
> Refactor - autowire settingManager bean to make code cleaner.

- web-ui/src/main/resources/catalog/templates/top-toolbar-accessible.html
This PR is the same as PR #5630 but applies changes to the main branch instead of the 3.12.x branch.
Looks like some changes were skipped as part of #5518 and it was still referencing old variables that existed prior to #4931
This fixes the login link so that it works correctly with keycloak.
The changes that had been applied to top-toolbar.html for #4931 have been applied to top-toolbar-accessible.html
I applied the changes to 3.12.x branch as that was the branch I was working on and I'm not sure if the 3.12.x changes have been merged into main yet. If needed, I can change the PR so that it is against main.
> Fix bug in keycloak signin link

- web-ui/src/main/resources/catalog/templates/top-toolbar-accessible.html
Looks like some changes were skipped as part of #5518 and it was still referencing old variables that existed prior to #4931
This fixes the login link so that it works correctly with keycloak.
The changes that had been applied to top-toolbar.html for #4931 have been applied to top-toolbar-accessible.html
I applied the changes to 3.12.x branch as that was the branch I was working on and I'm not sure if the 3.12.x changes have been merged into main yet.  If needed, I can change the PR so that it is against main.
> Fix bug in signin link - for SSO

- core/src/main/java/org/fao/geonet/kernel/WatchListNotifier.java
- core/src/main/resources/org/fao/geonet/api/Messages.properties
- core/src/main/resources/org/fao/geonet/api/Messages_fre.properties
- core/src/test/resources/WEB-INF/config.properties
- schemas-test/src/main/webapp/WEB-INF/config.properties
- schemas/iso19115-3.2018/src/main/test/resources/metadata-for-editing.xml
- schemas/iso19115-3.2018/src/main/test/resources/metadata-iso19139-for-editing.xml
- services/src/main/webapp/WEB-INF/config.properties
- services/src/test/resources/WEB-INF/config.properties
- web/src/main/webResources/WEB-INF/config.properties
While testing https://github.com/geonetwork/core-geonetwork/pull/5686 I noticed that the metadata tile and uuid from the email messages was null causing the messages not to be parsed correctly.
This change updates the index names to the newer elastic search index names.
Note that I also changed the following.
`    api/records/{{index:uuid}}`
as I'm assuming this uses the same index.  But I'm not exactly sure where this is used so I'm not sure if that changes is correct.
> Updated the index fieldname to match the es index names.

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
- schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
Before was not displayed at all.
Also improve indexing warning message in case of invalid bounds.
> Indexing / Temporal extent / Add support for now in range upper bound.

- web-ui/src/main/resources/catalog/js/CatController.js
Fixes https://github.com/geonetwork/core-geonetwork/issues/5660
Solve use case: search with a word in the non default lang title return no result
Then the question is what to do next eg. index translation in any field, choose language to search on depending on UI ...
> Search / Add all title's translations in the default search

- web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facets.html
- web-ui/src/main/resources/catalog/style/gn_search.less
The filter box in the facet list on the search page is displayed on 2 lines, this PR displays it on 1 line
**Before: 2 lines**
**After: 1 line**
> Fix: Display the facet filter on a single row

- web-ui/src/main/resources/catalog/style/gn_search.less
- web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_variables_default.less
It can happen that group names are long and can't be displayed on 2 lines because it's one big string without spaces. These long group names push the rest of the content out of the popup.
This PR adds a scrollbar whenever a long group name pushed everything too much to the right.
> Add a scrollbar to the privileges popup when group names are too long

- services/src/main/java/org/fao/geonet/api/users/UsersApi.java
Test to reproduce the issue:
1) Create a group `groupA`.
2) Create a some users in the `groupA` group, including a user with `UserAdmin` profile.
3) Create a user not assigned to any group.
4) Login as `UserAdmin` user in `groupA`
5) Go to the user management --> User created in step 3 is listed, but should not be.
> Users without groups assigned are listed in the users lists for any UserAdmin

- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
Some schemas based on iso19139 add a text as part of the codelist elements: 
```
<gmd:status>
<gmd:MD_ProgressCode codeListValue="completed" codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml#MD_ProgressCode">compleet</gmd:MD_ProgressCode>
</gmd:status>
```
This causes that the full view display for the elements the `codeListValue` translation and also the text value:
With this change, only  the `codeListValue` translation is displayed:
> iso19139 full view - codelist elements - display the codelistValue translation only if the element has a text also

- web-ui/src/main/resources/catalog/js/GnLocale.js
Update locale loader to support relative url with locate type as in previous 3.x versions. This is useful for custom views that provide their own locales.
```
module.config(['$LOCALES', function($LOCALES) {
$LOCALES.push('../../catalog/views/myview/locales/|core'');
}]);
```
To check about using the translation packs, but for now the translation packs configuration is packaged in the services jar, requiring a custom build to change it.
https://github.com/geonetwork/core-geonetwork/blob/dd0ff029a1ae5d240d72dbe025fa7db453818491/services/src/main/resources/config-spring-geonetwork.xml#L167
> Locale loader: fix to load translation files using the format relativepath|type

- pom.xml
- services/src/main/java/org/fao/geonet/api/OpenApiController.java
- services/src/main/java/org/fao/geonet/api/languages/LanguagesApi.java
- workers/wfsfeature-harvester/src/main/java/org/fao/geonet/harvester/wfsfeatures/WFSHarvesterApi.java
Was mainly related to isRestController checking for non null ResponseBody and also some controllers not listed in https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-common/src/main/java/org/springdoc/core/OpenAPIService.java#L216-L218 (not sure why).
Related 
* https://github.com/geonetwork/core-geonetwork/pull/5631
* https://github.com/geonetwork/core-geonetwork/issues/5432
@ianwallen I took some time to have a look to the missing API methods. It should be better now.
Maybe you can check this PR when you've a moment, thanks?
It fixes missing GET|DELETE /records/uuid and missing /languages/*
> OpenAPI / Restore missing operations from the doc.

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
This avoid to download the file and allows to check if URL is responding or not.
> Editor / Online source / Check URL with a HEAD call

- services/src/main/java/org/fao/geonet/api/records/formatters/FormatterApi.java
- services/src/main/java/org/fao/geonet/api/records/formatters/Resource.java
- services/src/main/java/org/fao/geonet/api/sld/SldApi.java
Correct the OpenAPI document so that it does not generate errors that were identified in #5431
The corrections was the following.
- Hide some API's from the swagger document. If the api's should be visible then we will need to update them so that /{portal} is not in the mapping.
- Added logic to handle api extension field.  Other option could have been to remove the {extension} from the mapping.
> Correct the OpenAPI document so that it does not generate errors

- web-ui/src/main/resources/catalog/js/admin/CategoriesController.js
- web-ui/src/main/resources/catalog/js/edit/EditorController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/locales/en-editor.json
- web-ui/src/main/resources/catalog/style/gn_admin.less
- web-ui/src/main/resources/catalog/templates/admin/classification/categories.html
Before this PR you could delete a `category` without confirmation, so an accidental delete wasn't far away. The same could happen when you were editing a metadata record, the `cancel` option cancelled immediately.
This PR adds 2 confirm actions.
**Confirm modal for a `Category`**
> Add confirm to delete Category and Cancel edits to metadata

- core/src/main/java/org/fao/geonet/kernel/security/SecurityProviderConfiguration.java
- core/src/main/java/org/fao/geonet/kernel/security/keycloak/KeycloakConfiguration.java
- core/src/main/java/org/fao/geonet/kernel/security/shibboleth/ShibbolethUserConfiguration.java
- core/src/main/java/org/fao/geonet/util/XslUtil.java
- core/src/main/resources/org/fao/geonet/api/Messages.properties
- core/src/main/resources/org/fao/geonet/api/Messages_fre.properties
- services/src/main/java/org/fao/geonet/api/users/PasswordApi.java
- services/src/main/java/org/fao/geonet/api/users/RegisterApi.java
- services/src/main/java/org/fao/geonet/api/users/UsersApi.java
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/js/LoginController.js
- web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html
- web-ui/src/main/resources/catalog/templates/signin.html
- web/src/main/webapp/xslt/base-layout-cssjs-loader.xsl
- web/src/main/webapp/xslt/common/base-variables.xsl
The user profile editing needs to be disabled if login user is Keycloak/"none local user" and the application authentication is done via keycloak. The editing should happen in Keycloak instead of Geonetwork.
Here is the example:
As result, the enable/disable will still allowed. There are two extra env variable to pass into SecurityConfiguration as control flag: UPDATEPROFILE and UPDATEGROUP
> User Profile Readonly for keycloak users 

- web-ui/src/main/resources/catalog/js/CatController.js
Update doc url to point to 3.10.x documents for the 3.10.x branch.
Related to #5366
This PR only affects the 3.10.x branch. Other branches should point to different versions.
> Update doc url to point to 3.10.x documentation

- web-ui/src/main/resources/catalog/style/gn.less
- web-ui/src/main/resources/catalog/templates/top-toolbar-accessible.html
- web-ui/src/main/resources/catalog/templates/top-toolbar.html
- web-ui/src/main/resources/catalog/views/default/less/gn_navbar_default.less
Somewhat related to https://github.com/geonetwork/core-geonetwork/pull/5663
The menu on the editor page couldn't be scrolled which meant that the menu options further down the menu couldn't be scrolled. This was caused by the fixed navigation.
This PR makes the `Editor` menu scrollable on small screens. However, this means the 2 menubars on the `Editor` page are not fixed anymore on small screens.
> Make the editor menu scrollable on small screens

- inspire-atom/src/main/java/org/fao/geonet/inspireatom/util/InspireAtomUtil.java
The requests to describe a local INSPIRE Atom dataset return a 404, for example:
http://localhost:8080/geonetwork/srv/atom/describe/dataset?spatial_dataset_identifier_code=fb0b0639-1d91-4fb5-b53d-47e32f35df6e&language=de
This is caused by the changes in the `operatesOn` format to track remote links. See https://github.com/geonetwork/core-geonetwork/blob/c170ffac76995b5c857c5adbccfe0a09041ca382/schemas/iso19139/src/main/plugin/iso19139/index-fields/default.xsl#L1125-L1213
> Update the filter for INSPIRE Atom dataset feed to support the remote operatesOn indexing format

- web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
- web-ui/src/main/resources/catalog/components/elasticsearch/EsService.js
- web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js
- web-ui/src/main/resources/catalog/components/search/searchoptions/SearchOptionsDirective.js
- web-ui/src/main/resources/catalog/components/search/searchoptions/SearchOptionsModule.js
- web-ui/src/main/resources/catalog/components/search/searchoptions/partials/searchoptions.html
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/js/GnModule.js
- web-ui/src/main/resources/catalog/locales/en-v4.json
- web-ui/src/main/resources/catalog/locales/fr-v4.json
- web-ui/src/main/resources/catalog/style/gn_search.less
- web-ui/src/main/resources/catalog/views/default/module.js
- web-ui/src/main/resources/catalog/views/default/templates/searchForm.html
Enables to have two search options 
- exactMatch (cf https://github.com/geonetwork/core-geonetwork/pull/5072/files)
- title only (it will look for all the resourceTitleObject language keys => so the search value will be checked in all avalaible languages)
> Add search options

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
In some cases, an overview may be targeting another record in the same catalogue (eg. export/import a record with a new UUID).
When removing an overview in the duplicated record, removing the overview was removing the original record attachement (if user has privilege to do so). 
Check that the target overview is related to current record under editing and if not, only remove the link in the XML (not the attachement).
> Overview / Removal / Do not delete attachement from other records

- core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
If added twice, the index value will be an array and cardinality of indexingDate is 1..1. Must be a string.
> Indexing / Do not add twice indexingDate field

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
The point here is to allow user to make more strict search using phrase query (with `"`) or use query expression (with `q()`) or define where to use wildcard.
Before
After with phrase query
After with query expression `q(+resourceTitleObject.default:("corine land cover 2012" AND "version 18"))`
> Editor / Associated resources / Do not add wildcard on all search

- web-ui/src/main/resources/catalog/components/elasticsearch/EsFacet.js
- web-ui/src/main/resources/catalog/components/elasticsearch/LuceneQueryParser.js
- web-ui/src/main/resources/catalog/views/default/templates/home.html
Elastic provide support of script in aggregation config using painless
language. See https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-aggregation-script
For example, the resource identifier is using a predefined scheme eg. `eurostat_v_4258_100_k_gisco-mreg-2021_i_2021_v01_r01` and user wants to build a facet on the first part of the identifier. The script can extract it and build an aggregation on it. Then the configuration needs to indicate which field has to be used using `meta.field` and if a wildcard mode is required.
```json
'facetConfig': {
"OrgForResource": {
"terms" : {
"script": {
"inline": "doc['resourceIdentifier.code'].size() == 0 ? 'http' : …
```
> Aggregation / Add terms script support

- schemas/csw-record/src/main/plugin/csw-record/index-fields/index.xsl
- schemas/dublin-core/src/main/plugin/dublin-core/index-fields/index.xsl
- schemas/iso19110/src/main/plugin/iso19110/index-fields/index.xsl
Affects only dublincore and ISO19110.
This can trigger exception when loading advanced view.
> Indexing / documentStandard is not an array.

- web-ui/src/main/resources/catalog/views/default/templates/page.html
GeoNetwork has an option to add static pages via the `API`. One of the options is to upload a static `html` page and and the link in menubar.
However this static page is displayed without a layout, so it doesn't really fit with the rest of GeoNetwork.
This PR add a `container`, `row` and `column`
**Before**
**After**
> Add a Bootstrap layout and column to a static page

- web-ui/src/main/resources/catalog/templates/top-toolbar-accessible.html
- web-ui/src/main/resources/catalog/templates/top-toolbar.html
Fix bug with login url not encoding the redirect url.
Before the fix if going to the map page and then reloading the page, it would generate a login link similar to the following.
http://localhost:8080/geonetwork/signin#/map?_csrf=b273c38d-d29c-4e26-ab4c-261c36ee74d3&redirectUrl=http://localhost:8080/geonetwork/srv/eng/catalog.search#/map
After the fix the url will look like this.
http://localhost:8080/geonetwork/signin#/map?_csrf=b273c38d-d29c-4e26-ab4c-261c36ee74d3&redirectUrl=http%3A%2F%2Flocalhost%3A8080%2Fgeonetwork%2Fsrv%2Feng%2Fcatalog.search%23%2Fmap
Without this fix extracting the redirectUrl would be incorrect as it would stop at the #.
Please backport this to 3.12.x
> Escape login redirect url for keycloak

- web-ui/src/main/resources/catalog/views/default/less/gn_infolist_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_layout_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_topics_default.less
- web-ui/src/main/resources/catalog/views/default/templates/home.html
This PR restyles the topics on the homepage. The old styling had its issues, especially the responsiveness proved to be tricky. These topics are restyled, better responsive, numbers are on a different row (so no more badges on another row). Colours are the same.
Some additional changes:
- toggle the type looks the same as other toggle options
- cleanup and simplify css/less
- no columns, each block is full width
**Some screenshots of the new style**
> Restyle topics on the Home page

- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/templates/top-toolbar-accessible.html
- web-ui/src/main/resources/catalog/templates/top-toolbar.html
Related to https://github.com/geonetwork/core-geonetwork/issues/4224
This PR makes small adjustments to UI settings in the Admin:
- recordview always enabled
- signin/signout combined in `authorisation`
- translation for all settings
**The newly combined `signin`/`signout`**
> Small adjustments to UI settings in the Admin

- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataOperations.java
- domain/src/main/java/org/fao/geonet/repository/OperationAllowedRepository.java
- domain/src/main/java/org/fao/geonet/repository/OperationAllowedRepositoryCustom.java
- domain/src/main/java/org/fao/geonet/repository/OperationAllowedRepositoryCustomImpl.java
- domain/src/test/java/org/fao/geonet/repository/OperationAllowedRepositoryTest.java
Remove deleteAllByMetadataIdExceptGroupId from custom implementation and use the repository @query instead.
For some reason the older logic was causing transaction issues #5674
> Move deleteAllByMetadataIdExceptGroupId to @query. Fixes #5674

- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
Search field is not `tag` anymore can be `tag.default` or one of the field `langfre`, `key`, ...
> Record view / Advanced / Fix search by keyword links

- web-ui/src/main/resources/catalog/components/elasticsearch/directives/FacetDirective.js
- web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facets.html
- web-ui/src/main/resources/catalog/views/default/module.js
- web-ui/src/main/resources/catalog/views/default/templates/home.html
A number of facet are translated client side. When using filter option, it triggers server side filter call using Elasticsearch API. In some case (eg. groupOwner filter) we don't want to filter on id or key but on the label.
Add possibility to:
* sort by translation
* filter on translation
eg. configuration for a groupOwner facet:
```
'groupOwner': {
'terms': {
'field': 'groupOwner',
'size': 80,
'include': '.*',
order : { _key : asc }
},
'meta': {
'orderByTranslation': true,
'displayFilter': true,
'filterByTranslation': true,
'collapsed': true
}
},
```
> Facet / Add translation sort and filtering support.

- domain/src/main/java/org/fao/geonet/entitylistener/HarvesterSettingValueSetter.java
…ter passwords
Application completely fails to start due to encryption errors
```
2021-07-21 09:11:50,530 INFO  [geonetwork.encryptor] - Password database encryptor initialized - Keep the file /data/dev/gn/eea/web/src/main/webapp/WEB-INF/data/config/encryptor.properties safe and make a backup. When upgrading to a newer version of GeoNetwork the file must be restored, otherwise GeoNetwork will not be able to decrypt passwords already stored in the database.
2021-07-21 09:11:55,023 ERROR [jeeves.engine] - Raised exception while starting the application. Fix the error and restart.
2021-07-21 09:11:55,023 ERROR [jeeves.engine] -    Handler   : org.fao.geonet.Geonetwork
2021-07-21 09:11:55,023 ERROR [jeeves.engine] -    Exception : org.jasypt.exceptions.EncryptionOperationNotPossibleException …
```
> Encryption / Application fails to start if encryption error on harvester passwords

- web/src/main/java/org/fao/geonet/EncryptorInitializer.java
Refactor encryptor to use sql variable binding
Also move initialization of "updates = new HashMap<>();" outside the try block otherwise if the try fails, it could end up using incorrect "updates" values in next statements.
> Refactor encryptor to use sql variable binding

- web-ui/src/main/resources/catalog/js/admin/LogoSettingsController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/style/gn_admin.less
- web-ui/src/main/resources/catalog/templates/admin/settings/logo.html
The logo list in the admin settings can grow very large. This PR restyles the list a bit and adds a couple of views for the icon height: `small`, `medium` and `large`. Furthermore a filter option is added to filter the logos on their name.
On larger screens the list is displayed on 2 columns.
**Screenshot of 2 columns**
**Screenshot of medium height icons on smaller screen**
> Restyle the logo list in the Settings

- web-ui/src/main/resources/catalog/views/default/templates/home.html
User may want to customize rendering depending on facet key.
eg. upper casing scripted agg bucket value
> Home page / Facet / Add CSS class

- web-ui/src/main/resources/catalog/style/gn_metadata.less
Not all texts can be displayed on multiple lines automatically, for instance with log links without spaces and `-` characters. When this happens the text breaks out of the table.
This PR adds a line of `css` to break words inside table cells when needed.
**Before:**
**After:**
> Break words in table on the record view page

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/onlinesrcList.html
Do not show DOI or WFS harvester widget if fields are null.
> Editor / Associated resource / Check null protocol or url

- web-ui/src/main/resources/catalog/components/search/mdview/mdviewModule.js
- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
- web-ui/src/main/resources/catalog/components/utility/partials/recordOriginLogo.html
- web-ui/src/main/resources/catalog/views/default/templates/recordView.html
Related to https://github.com/geonetwork/core-geonetwork/pull/5742
Add utility directive to reuse group logo anywhere eg. in search results
using 
```html
<div data-gn-record-origin-logo="md"/>
```
> Record view / Group not set in prod mode

- web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
- web-ui/src/main/resources/catalog/components/elasticsearch/EsFacet.js
- web-ui/src/main/resources/catalog/components/search/mdview/mdviewModule.js
- web-ui/src/main/resources/catalog/components/search/mdview/mdviewService.js
- web-ui/src/main/resources/catalog/components/search/searchmanager/LocationService.js
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/views/default/templates/recordView.html
When a catalogue manage a variety of projects, partners, standards or types of records, it may make sense to configure different default views based on record properties because each records may have different goals.
```json
"list": [{
"label": "defaultView",
"views": [ {
"if": {"standardName": "ISO 19115-3 - Emodnet Checkpoint - Targeted Data Product"},
"url" : "/formatters/xsl-view?root=div&view=advanced"
}, {
"if": {
"standardName": [
"ISO 19115:2003/19139 - EMODNET - BATHYMETRY",
"ISO 19115:2003/19139 - EMODNET - HYDROGRAPHY"]
},
"url" : "/formatters/xsl-view?root=div&view=emodnetHydrography"
}],
"url" : ""
```
Supported by https://sextant.ifremer.fr/Donnees/Catalogue
> Record view / Add conditional formatter support

- web-ui/src/main/resources/catalog/components/search/mdview/mdviewDirective.js
- web-ui/src/main/resources/catalog/components/search/mdview/partials/morelikethis.html
* Can browse more similar records (until limit is reached)
* Use overview dataurl when available
* Fix status badge
* Stop browsing if no more similar records
Default configuration is quite open, a more strict one can be (if catalogue is in english and titles are really similar):
```json
'moreLikeThisConfig': {
"more_like_this" : {
"fields" : [
"resourceTitleObject.langeng"
],
"like" : null,
"min_term_freq" : 1,
"min_word_length" : 3,
"max_query_terms" : 35,
"analyzer": "english",
"minimum_should_match": "70%"
}
}
```
> Record view / More like this improvements.

- schemas/dublin-core/src/main/plugin/dublin-core/update-fixed-info.xsl
- schemas/iso19110/src/main/plugin/iso19110/update-fixed-info.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/update-fixed-info.xsl
Make things consistent based on https://github.com/geonetwork/core-geonetwork/commit/f38ae66b84a2ccc93fb2de9efabbac164dc0c492
'If true, the schemaLocation attribute in root element of the metadata is removed during validation and on metadata save.'.
> Plugin / SchemaLocation is removed on save in ISO19139 (not in other plugins).

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
- schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
- web-ui/src/main/resources/catalog/views/default/templates/recordView.html
Also avoid error when description is multilingual.
Make ISO19139 and 19115-3 consistent.
Add link to CRS details if any.
> Record view / Fix display of CRS label.

- schemas/iso19139/src/main/plugin/iso19139/update-fixed-info-keywords.xsl
In principle it should not happen unless editor plays with the XML view.
Now, save will take into account the first all thesaurus block and will not fail if many.
> Editor / Avoid error if records contains multiple all thesaurus block

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/oaipmh/Harvester.java
- schemas/dublin-core/src/main/plugin/dublin-core/extract-gml.xsl
- schemas/dublin-core/src/main/plugin/dublin-core/extract-relations.xsl
- schemas/dublin-core/src/main/plugin/dublin-core/formatter/xsl-view/view.xsl
- schemas/dublin-core/src/main/plugin/dublin-core/index-fields/index.xsl
- schemas/dublin-core/src/main/plugin/dublin-core/layout/config-editor.xml
- schemas/dublin-core/src/main/plugin/dublin-core/layout/layout.xsl
- schemas/dublin-core/src/main/plugin/dublin-core/loc/eng/strings.xml
- schemas/dublin-core/src/main/plugin/dublin-core/loc/fre/strings.xml
- schemas/dublin-core/src/main/plugin/dublin-core/process/thumbnail-remove.xsl
* Add support for overview.
* Use API instead of deprecated resources.get to identify file to download.
* Make advanced view more consistent with other schemas (overview, extent, tags)
* Fix ordering on datestamp
* Improve indexing in case of error of types:
```
2021-08-02 10:10:28,482 ERROR [geonetwork.index] - Document with error #oai:archimer.ifremer.fr:62447: ElasticsearchException[Elasticsearch exception [type=mapper_parsing_exception, reason=failed to parse field [geom] of type [geo_shape]]]; nested: ElasticsearchException[Elasticsearch exception [type=parse_exception, reason=expected word but found: '{']];.
2021-08-02 10:39:58,194 ERROR [geonetwork.index] - Parsing invalid JSON node {"default":"JERICO-NEXT TNA FOULSTOP "Fouling Protection for Marine Optical Systems""} for property …
```
> Dublin core / Improvements

- web-ui/src/main/resources/catalog/components/search/searchoptions/partials/searchoptions.html
- web-ui/src/main/resources/catalog/components/usersearches/partials/featuredusersearchesbutton.html
- web-ui/src/main/resources/catalog/locales/en-core.json
- web-ui/src/main/resources/catalog/style/gn_search.less
- web-ui/src/main/resources/catalog/views/default/less/gn_layout_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_search_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_variables_default.less
- web-ui/src/main/resources/catalog/views/default/module.js
- web-ui/src/main/resources/catalog/views/default/templates/advancedSearchForm/defaultAdvancedSearchForm.html
- web-ui/src/main/resources/catalog/views/default/templates/home.html
- web-ui/src/main/resources/catalog/views/default/templates/searchForm.html
Small UI improvements to the (advanced) search on the search page in order to get a more uniform view for the search input and the advanced search options.
Changes:
- advanced form is absolute positioned
- search option are now in the advanced search form
- advanced search now labelled 'search options'
- all buttons now have the default style (can be changed through the variables)
- new icon for the advanced panel (like Gmail options)
a11y change:
- removed the `enter` key binding to the search: now you can open the advanced search with the keyboard
**Screenshot of the new style**
> Small UI improvements to the (advanced) search on the search page

- services/src/main/java/org/fao/geonet/api/records/formatters/XsltFormatter.java
- web/src/main/webapp/xslt/base-layout-cssjs-loader.xsl
Relates to https://github.com/geonetwork/core-geonetwork/pull/5888 and specifically to https://github.com/geonetwork/core-geonetwork/pull/5888/commits/aa976e8e64bb8788d617fb165befb3cfeb70dd11.
PDF print was not able to load CSS due to use of relative path with '../..'.
Using complete URL was fixing the issue but was also causing a new issue when you start the app on a port which is not the one define in database. The app was not able to load resources.
Restore relative path for HTML page and cleanup the relative path for the PDF mode.
> Resources / Load using relative path (and fix PDF missing CSS resources)

- web/src/main/webapp/xslt/base-layout-nojs.xsl
Avoid ` - ` as page header on simple HTML page eg. http://localhost:8080/geonetwork/srv/api/sources
> HTML / Page tab title empty

- web-ui/src/main/resources/catalog/components/viewer/wfsfilter/partials/wfsfilterfacet.html
Before
After with running WFS or not accessible
> Data / WFS harvester / Don't diplay widget if WFS is down

- web-ui/src/main/resources/catalog/components/search/resultsview/SelectionDirective.js
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/selection-widget.html
- web-ui/src/main/resources/catalog/components/validationtools/GnmdInspireValidationDirective.js
- web-ui/src/main/resources/catalog/components/validationtools/partials/mdValidationTools.html
- web-ui/src/main/resources/catalog/locales/en-v4.json
- web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v406/migrate-default.sql
More and more often, end user define a custom INSPIRE portal for being harvested by INSPIRE geoportal. The INSPIRE portal first filter records in the scope of the Directive and may also define post processing to adapt record encoding to INSPIRE rules (see. CSW post processing https://github.com/geonetwork/core-geonetwork/pull/4493).
A nodeid parameter is added to the INSPIRE validation configuration:
If the nodeid parameter is not set, then the record XML is sent to the validator for validation. If defined, then the GetRecordById URL of the record in this node is sent to the validator which retrieve the XML (see https://github.com/geonetwork/core-geonetwork/pull/5227).
Validation is available:
* in editor
* With no nodeid declared
* With a nodeid declared in config 
* on a selection
Also …
> INSPIRE / Validation from a portal endpoint.

- services/src/main/java/org/fao/geonet/api/ApiUtils.java
- services/src/main/java/org/fao/geonet/api/sources/SourcesApi.java
eg.
* go to the API path serving HTML, 
* then go to the main app which is using the same API path but processing the JSON response.
* Browser history back will return to the JSON output instead of the HTML one.
Use the Vary header to indicate to the browser that the cache depends
on Accept header.
It mainly affects portal landing page
http://localhost:8080/geonetwork/srv/api/sources
which I think is the main one served and used in both HTML and JSON format by the browser app.
> API / Avoid browser cache issue when the same API Path output various formats

- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid.html
- web-ui/src/main/resources/catalog/style/gn.less
- web-ui/src/main/resources/catalog/views/default/less/gn_card_default.less
Relates to https://github.com/geonetwork/core-geonetwork/pull/5759.
Also the ng-class key can't contains expression. Use array mode for this.
> Record status / Highlight superseded record like obsolete one.

- web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facet.html
Avoids having an empty () on parent groups
> Search / Facet / Remove count if undefined

- web/src/main/java/org/fao/geonet/EncryptorInitializer.java
Encryptor env variable should be uppercase as this it the general standard for env variables otherwise it will not find the variable on unix
> Encryptor env variable should be uppercase

- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid4maps.html
Was ok on main page, but in the map viewer > map tab > load map, the user was moving to the record view.
> Map list / Open map in the viewer, not the record view

- web-ui/src/main/resources/catalog/views/default/directives/partials/infolist.html
This PR adds a title to an info block: this will show the full name when a long a long name is truncated (see screenshot).
> Add a title to an info block

- core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
- schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
- services/src/main/resources/config-spring-geonetwork.xml
- web-ui/src/main/resources/catalog/views/default/templates/recordView.html
- web/src/main/webapp/xslt/common/index-utils.xsl
Add support for indeterminate position and calendar era attributes in temporal ranges
Before
After
> Record view / ISO / Temporal range details support.

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/onlinesrc-remove.xsl
- schemas/iso19139/src/main/plugin/iso19139/process/onlinesrc-remove.xsl
Apply `normalize-space` to both sides of the comparison, otherwise if the resource name has extra spaces between words, the comparison was not matching the resource.
> Remove metadata online resource - fix resource name comparison

- web-ui/src/main/resources/catalog/components/edit/topiccategory/TopicCategoryDirective.js
- web-ui/src/main/resources/catalog/components/edit/topiccategory/partials/topiccategory.html
When the tooltips are enabled in the metadata editor with the mode (`displayTooltipsMode`) as `icon`, the topic categories directive was not displaying the tooltip icon next to the field.
With this change, the icon is displayed, similar as for other fields in the editor:
> Display topic categories tooltips in the metadata editor when tooltips are enabled

- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java
Applies to `3.12.x` and `3.10.x` branches.
> Fix editing of directory entries templates. Fixes #5936

- web-ui/src/main/resources/catalog/style/gn_editor.less
The issue is this padding-bottom property was overwritten by each other.
So the result is the side bar shrank and the user has to scroll down/up in order to browse the whole drop down menu of "Add resource".
> "padding-bottom: 150px" for ".gn-editor-sidebar" CSS class.

- web-ui/src/main/resources/catalog/views/default/less/gn_topics_default.less
Long titles on the `Topic` blocks (on the homepage) without spaces were not displayed correctly, the change in this PR will fix this.
**Before**
**After**
> Small fix for long titles on `Topic` blocks

- core/src/main/java/jeeves/server/dispatchers/ServiceManager.java
- core/src/main/java/org/fao/geonet/api/records/attachments/CMISStore.java
- core/src/main/java/org/fao/geonet/api/records/attachments/JCloudStore.java
- core/src/main/java/org/fao/geonet/constants/Geonet.java
- services/src/main/java/org/fao/geonet/api/ApiUtils.java
- services/src/main/java/org/fao/geonet/api/records/MetadataApi.java
- services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
- services/src/main/java/org/fao/geonet/api/records/editing/MetadataEditingApi.java
- services/src/main/java/org/fao/geonet/api/records/formatters/FormatterApi.java
- services/src/main/java/org/fao/geonet/api/records/formatters/SchemaLocalizations.java
- services/src/main/java/org/fao/geonet/api/regions/RegionsApi.java
- services/src/main/java/org/fao/geonet/api/site/SiteApi.java
- services/src/main/java/org/fao/geonet/api/tools/i18n/LanguageUtils.java
- services/src/main/java/org/fao/geonet/api/tools/i18n/TranslationApi.java
ServiceContext makes use of `?` when the current language cannot be determined. This occurs when a ServiceContext has been generated for use in a background process and does not have direct access to an HTTPRequest (from the user initiating the activity).
This pull request asks AbstractStore implementations to check for both `?` and `null`, and make use of the default language when running in a background process.
See https://github.com/geonetwork/core-geonetwork/issues/5939 for background information.
> Check for Service Context language placeholder in AbstractStore implementations

- core/pom.xml
- core/src/main/java/org/fao/geonet/languages/IsoLanguagesMapper.java
- core/src/main/java/org/fao/geonet/util/XslUtil.java
- pom.xml
- services/src/main/java/org/fao/geonet/api/records/CatalogApi.java
- services/src/main/java/org/fao/geonet/api/records/formatters/FormatterApi.java
- services/src/main/java/org/fao/geonet/api/records/formatters/SchemaLocalizations.java
- services/src/main/java/org/fao/geonet/api/tools/i18n/LanguageUtils.java
- services/src/main/java/org/fao/geonet/api/tools/i18n/TranslationApi.java
I had noticed that there were a few cases where languages were being converted from  iso639-2/T iso639-2/B but there were not handling all languages.  Applied a new consistent converted using the nv-i18n library.
> Used nv-i18n library to add better support for iso639-2/T iso639-2/B support

- web/src/main/java/org/fao/geonet/EncryptorInitializer.java
- web/src/main/java/org/fao/geonet/Geonetwork.java
- web/src/main/webResources/WEB-INF/config-db/database_migration.xml
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v3110/MigrateEncryptor.java
Fixes migration issue from #5863 by only allowing the encryptor to be run once during migration.
> Add logic to only run encryptor once on password during the migration.

- web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/views/api/index_debug.html
- web-ui/src/main/resources/catalog/views/default/module.js
Currently the add to map feature for WMS layers expects the layer name defined in the online resource name of the metadata.  
Sometimes the layer name in the WMS service is not descriptive, like ESRI WMS that uses a number and users encode the layer name as part of the online resource url instead.
Example (`layers` parameter has the layer name):
https://maps-cartes.ec.gc.ca/arcgis/services/CriticalHabitatAlanticHabitatEnPerilAtlantique/MapServer/WMSServer?request=GetCapabilities&service=WMS&layers=16&legend_format=image/png&feature_info_type=text/html
This PR allows to configure both modes:
- Resource name (default)
- URL
Should be configured the url parameters with the layer name
> Configure how to extract the WMS layer name from metadata online resources to add them to the map viewer

- web-ui/src/main/resources/catalog/components/admin/harvester/partials/account.html
Chrome autocompletes the harvester credentials, seem as the username field is hidden by default, the heuristic used, autocompletes the previous field: **XPath Filter**.  The main problem with this, apart of the wrong value in the field, is that when the harvested is edited again and saved, causes an error.
This change prevents the autocomplete in the harvester credentials.
> Fix credentials autocomplete in harvesters

- web/src/main/webapp/xslt/common/index-utils.xsl
The original regular expression matched invalid values like `2021-04-207`, causing the metadata indexing to fail, not being searchable.
@fxprunayre in the function comments indicates `epoch_millis`, can you confirm if that is matched with the expression `$value castable as xs:dateTime`?
> Fix gn-fn-index:is-isoDate - invalid dates like 2021-04-207 match, causing indexing errors

- web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html
There is a bug in the keycloak mode user profile page where the user group information are missing. The issue is because the logic control flag been place improperly. So this pull request will fix it.
Here is the fixed example:
Logged in user is not admin:
Logged in user is admin:
> Unblock missing user/group information from user profile

- events/src/main/java/org/fao/geonet/events/md/MetadataPreRemove.java
- services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
The issue is we are customizing the recordDeletedEvent or MetadataRemove event listener to prevent the deletion if some condition is not met. Once the transaction failed, metadata will remain. However all store resources are deleted and there is no way to revert back. I attempt to put the store.delete after the metadataManager.deleteMetadata but it will mess up the transaction.
https://github.com/geonetwork/core-geonetwork/blob/fc7551adf9a4b5932033d160e0bbd0df70bde94f/services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java#L193-L195
So I decided to add new MetadataPreRemove event type and will use this event listener to do the transaction handling.
> MetadataPreRemove before backup operation.

- services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
This pull request gives the client side ability to pass attachment copying parameter to instruct skipping attachment copying or not.
If approved, please backport to 3.12
> option for duplicate API to copy attachments or not

- services/src/main/java/org/fao/geonet/api/processing/XslProcessApi.java
When the workflow is enabled the batch processing works fine in these cases:
- records are in draft
- records approved without working copy
But it's not working fine If the metadata is approved and has a working copy. In this case it's processing all the records, but updating **only** the approved version, not the draft version.
This PR updates the batch processing API to handle both versions of the metadata. For now, in the total number of records are counted the approved and draft versions. This is something to improve in the report, but will require some refactor of the current report.
> Update XslProcessApi to process the draft copies for the metadata in a workflow

- web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionsDirective.js
This fix is related to https://github.com/geonetwork/core-geonetwork/issues/5963
The cause is when working copy gets approved, the draft (work copying) will get removed from server side. However the Angular is still trying to pass parameter draft=y (for example: http://localhost:8080/geonetwork/srv/eng/qi?_uuid=8fc530bf-d954-4afd-8f10-43dfced9f6c3&fast=index&_content_type=json&buildSummary=false&_draft=y) to the search engine. As result it is not searchable and page will be stuck.
I modify the Angular code to check if the returning metadata status from the HTTP response if it's "approved", then force the draft parameter to be "n". In reality, once any record is approved, the draft will not exist anymore.
> Reset search parameter after metadata status change to "approved"

- web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
Original issue:
https://github.com/metadata101/iso19139.ca.HNAP/pull/240
Issue brief description:
Some metadata template uses ISO_639_2T language code which is not supported in Geonetwork. For example:
https://github.com/metadata101/iso19139.ca.HNAP/blob/b37d4f95091af69974c0036d05f5100a28a6db92/src/main/plugin/iso19139.ca.HNAP/templates/hnaplevel1-french.xml#L15-L17
https://github.com/metadata101/iso19139.ca.HNAP/blob/b37d4f95091af69974c0036d05f5100a28a6db92/src/main/plugin/iso19139.ca.HNAP/templates/hnaplevel1-english.xml#L121-L125
The consequence is multilingual field is not recognized and its correct language tab cannot be rendered. Here is the example in French profile, but English tab is always showing to the user.
In order to eliminate such language inconsistent issue, this pull …
> Convert iso639_2T to iso639_2B in form-builder

- web-ui/src/main/resources/catalog/components/doi/partials/doiwidget.html
Change the links by actual buttons so `ngClickAndSpin` directive is not executed when
the user clicks a disabled button. With the links the action was triggered even when
the component is `disabled`.
> Change the links to buttons so ngClickAndSpin is actually disabled in DOI widget html template

- web/src/main/webapp/WEB-INF/config-security/config-security-keycloak.xml
Fixed issue with missing keycloakSecurityContextRequestFilter that was causing keycloak not to refresh the keycloak session  correctly.
Before this fix, if a user logged in via keycloak and browsed for a while, the keycloak session would be removed but the geonetwork session would still be active.  So it would loose the SSO capabilities.
Oddly the documentation on keycloak 11 does not include adding the bean and that is why it was previously missed.
https://www.keycloak.org/docs/11.0/securing_apps/#xml-configuration
The newer documentation include the addition of the bean.
https://www.keycloak.org/docs/latest/securing_apps/#xml-configuration
Please backport this to 3.12.x
> Fixed token refresh issue with keycloakSecurityContextRequestFilter

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/datacite/view.xsl
- schemas/iso19139/src/main/plugin/iso19139/formatter/datacite/view.xsl
This will align the formatter with the fields that the schematron considers as valid creators.
> Datacite formatter - process for creators only point of contacts with roles pointOfContact and custodian

- services/src/main/java/org/fao/geonet/api/userfeedback/UserFeedbackAPI.java
When multiple recipients are selected in the send feedback form they are
received in the backend as a list of email addresses separated by comma.
This change fixes the way the parameter was handled when multiple repipients
were added.
> Fix feedback email with multiple recipients

- web-ui/src/main/resources/catalog/js/admin/CSWSettingsController.js
- web-ui/src/main/resources/catalog/js/admin/SourcesController.js
The code to retrieve the service metadata title was using the old query API, causing the title not being displayed:
> Fix the display of the service metadata title for CSW and portals

- csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/SearchController.java
The ElementSet strategy 'context' was using an invalid variable with the name of elements to filter from the metadata for the CSW response, causing that all the metadata elements were returned.
> Fix the list of elements to process in CSW ElementSet strategy 'context'

- listeners/src/main/java/org/fao/geonet/listener/metadata/draft/RetireRecord.java
- services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
- web-ui/src/main/resources/catalog/views/default/directives/partials/mdactionmenu.html
- Enable the option for approved metadata.
- Don't allow to publish retired metadata.
- Unpublish metadata when retired.
> Metadata retired status support

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/fromJsonLdEsri.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/fromJsonOpenDataSoft.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/protocol-mapping.xsl
In the `ISO19115-3` schema, the PR improves the transformation from Opendatasoft API.
- add the mimetype in the protocol, so it can be used in the UI eg `WWW:DOWNLOAD:application/json`
- add the fields if available in the description
> Add mimetype in WWW:DOWNLOAD protocol on opendatasoft harveting

- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v3110/UpdateMetadataStatus.java
The FK for the column `relatedMetadataStatusId` is not added when migrating from a 3.10 database. Hibernate tries to create it, but fails due to the key changes.
> Metadata status migration - add FK for relatedMetadataStatusId

- services/src/main/java/org/fao/geonet/api/userfeedback/UserFeedbackAPI.java
Related to #5260
Test case:
1) Enable user feedback in the settings
2) Add comments to a metadata
3) Go to the home page and select the `Comments` panel: without the fix, metadata titles are not displayed.
> Update user feedback API to create a ServiceContext, otherwise the metadata titles retrieved from the Lucene index are not retrieved

- services/src/main/java/org/fao/geonet/api/records/extent/MetadataExtentApi.java
- services/src/main/java/org/fao/geonet/api/regions/RegionsApi.java
- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-functions.xsl
Use the Region API - Map projection setting on the region's geometry rendering services.
* If a `mapsrs` parameter is received in the URL then use it.
* If no `mapsrs` is received then use the `region/getmap/mapproj` setting value.
* If no `mapsrs` parameter and no `region/getmap/mapproj` is defined then use EPSG:4326.
> Use the Map projection Region API setting in Regions/geometry related services

- services/src/main/java/org/fao/geonet/api/users/RegisterApi.java
- web-ui/src/main/resources/catalog/templates/new-account.html
When a (future) user was using the 'self' registration option, the `surname` and `country` were not stored. This PR fixes this so `surname` and `country` are correctly registered and saved.
**The register (new account) page**
> Fix the registration of the `surname` and `country` for the 'self' registration process

- web-ui/src/main/resources/catalog/templates/admin/report/report-filedownload-metadata.html
- web-ui/src/main/resources/catalog/templates/admin/report/report-fileupload-metadata.html
- web-ui/src/main/resources/catalog/templates/admin/report/report-internal-metadata.html
- web-ui/src/main/resources/catalog/templates/admin/report/report-updated-metadata.html
- web-ui/src/main/resources/catalog/templates/admin/report/report-users.html
- web-ui/src/main/resources/catalog/views/default/less/gn_admin_default.less
This PR fixes UI problems with buttons not fitting inside panel headers on different admin pages.
**Category before**
**and after**
**A report page before**
**and after**
> Add styles and classes to fix the button bars not really fitting inside the headers on admin pages

- services/src/main/java/org/fao/geonet/api/regions/RegionsApi.java
> Configuration option to restrict the map services supported in map extent API (geom.png) the usage of non-predefined map services. 

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/fromJsonLdEsri.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/fromJsonOpenDataSoft.xsl
Add a link to the landing page of the source metadata for ESRI and Opendatasoft harvesting.
The protocol used to distinguish the resource is `WWW:LINK:LANDING_PAGE`
```xml
<mrd:onLine>
<cit:CI_OnlineResource xmlns:cit="http://standards.iso.org/iso/19115/-3/cit/2.0">
<cit:linkage>
<gco:CharacterString xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0">https://metropole-europeenne-de-lille.opendatasoft.com/explore/dataset/bornes-dateliers-velos-a-lille/information/</gco:CharacterString>
</cit:linkage>
<cit:protocol>
<gco:CharacterString xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0">WWW:LINK:LANDING_PAGE</gco:CharacterString>
</cit:protocol>
<cit:name>
<gco:CharacterString xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0">Landing Page</gco:CharacterString> …
```
> Opendata harvesting: add a resource for the landing page

- web-ui/src/main/resources/WEB-INF/classes/web-ui-wro-sources.xml
- web-ui/src/main/resources/catalog/lib/bootstrap.ext/tagsinput/bootstrap-tagsinput.js
Remove the `htmlEncode` part for the label, this `htmlEncode` puts 'url safe' characters in the label. For instance 'Maps & graphics' turns into 'Maps &amp; graphics'. 
This PR fixes this by removing the encoding for the label and let GeoNetwork minimize the script.
**Screenshot of the encoding error**
> Fix encoding for tags input labels

- services/src/test/java/org/fao/geonet/api/records/extent/MetadataExtentApiTest.java
Since the settings for regions API map projection is used now if no `mapsrs` is passed
in the request and because the default value of the setting is EPSG:3857 the tests were failing.
This fix the test passing the `mapsrs=EPSG:4326` parameter that is the projection used
in the pre-generated test images.
> Fix MetadataServiceApiTest tests

- web-ui/src/main/resources/catalog/js/admin/LogoSettingsController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/style/gn_admin.less
- web-ui/src/main/resources/catalog/templates/admin/settings/logo.html
When you click on the delete logo button in the logo page in the settings, it immediately deletes the logo. You get no second changes.
This PR adds a confirm popup in between, to ask if you really want to delete the logo.
> Add a confirm popup when deleting a logo

- web-ui/src/main/resources/catalog/js/admin/LogoSettingsController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/style/gn_admin.less
- web-ui/src/main/resources/catalog/templates/admin/settings/logo.html
`3.12.x` version of https://github.com/geonetwork/core-geonetwork/pull/6067
When you click on the delete logo button in the logo page in the settings, it immediately deletes the logo. You get no second changes.
This PR adds a confirm popup in between, to ask if you really want to delete the logo.
> [3.12.x] Add a confirm popup when deleting a logo

- web-ui/src/main/resources/catalog/js/admin/UserGroupController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/style/gn_admin.less
- web-ui/src/main/resources/catalog/templates/admin/usergroup/groups.html
- web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html
Use a custom dialog to ask for users / groups delete instead of the browser confirm dialog to unify the behaviour with other pages in the application.
> User custom dialog to ask for users / groups delete confirmation

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/jsonld/iso19115-3.2018-to-jsonld.xsl
- schemas/iso19139/src/main/plugin/iso19139/formatter/jsonld/iso19139-to-jsonld.xsl
For these values:
```
WestBoundLongitude: -8.8
NorthBoundLatitude: 60.87
EastBoundLongitude: -0.71
SouthBoundLatitude: 54.63
```
The previous code for jsonld formatter was outputting:
```
"spatialCoverage": {
"@type":"Place"
,"geo": {
"@type":"GeoShape",
"box": "-8.80 -0.71 54.63 60.87"
}
}
```
With the fix, the correct order (S,W,N,E) is output:
```
"spatialCoverage": {
"@type":"Place"
,"geo": {
"@type":"GeoShape",
"box": "54.63,-8.8,60.87,-0.71"
}
}
```
> Fix coordinate order in jsonld GeoShape element

- services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
The status change date is filled for all type of statuses, but it was returned only for `task` statuses.
@fxprunayre is there any reason for that? Otherwise, please check the proposed change, thanks.
> Metadata get status service - return the status change date for all types of statuses

- pom.xml
It was found that the fix to address CVE-2021-44228 in Apache Log4j `2.15.0` was incomplete
in certain non-default configurations.
As far as we know GeoNetwork doesn't use any of these pattern layouts but anyway this
commit updates log4j to `2.16.0` that fixes the new CVE-2021-45046 disabling access to
JNDI by default and removing the message lookups feature.
> Bump log4j-core and log4j-api from 2.15.0 to 2.16.0

- core/src/main/java/org/fao/geonet/kernel/security/SecurityProviderConfiguration.java
- core/src/main/java/org/fao/geonet/kernel/security/SecurityProviderUtil.java
- core/src/main/java/org/fao/geonet/kernel/security/keycloak/KeycloakUtil.java
- domain/src/main/java/org/fao/geonet/domain/mapservices/MapService.java
- services/src/main/java/org/fao/geonet/api/mapservices/MapServicesApi.java
- web-ui/src/main/resources/catalog/components/common/map/mapService.js
- web-ui/src/main/resources/catalog/components/utility/CORSInterceptor.js
- web-ui/src/main/resources/catalog/components/viewer/layermanager/LayerManagerDirective.js
- web/src/main/java/org/fao/geonet/proxy/URITemplateProxyServlet.java
- web/src/main/webResources/WEB-INF/config-spring-geonetwork.xml
Add proxy mapviewer support for connecting to a secured map.
There are 2 methods for connecting to mapviewer securely.  
- Proxy which is simpler to implement however requires more hops to get the data so it is a little more slower. It is also the only option when connecting using basic auth for security reasons.
- Client side which is the faster option however more difficult to implement.
The first release will only include the proxy option and the client side option will be a separate PR in the future.
In our case, both geoserver and geonetwork are secured by keycloak security so we generally focused on using bearer token for the request. This allowed for better SSO integration.  Have not fully tested using basic authentication however that should work with mapservers that support basic …
> Add proxy level security support for map services

- schemas/iso19115-3.2018/src/main/resources/config-spring-geonetwork.xml
The section for the DOI-get query was missing for this standard. Inserting these lines, it will be possible to create DOI.
> Add the doi-get query for ISO19115-3.2018 standard

- web-ui/src/main/resources/catalog/js/edit/EditorBoardController.js
- web-ui/src/main/resources/catalog/js/edit/EditorController.js
Issue Description:
The exception thrown in metadata editor/editorBoard was not captured the correct returned JSON path. The example JSON looks like. It should be reason.data->{code, description, message}. There is an unknown "error" object in the controller.
There is no specific way to reproduce such exception. The exception can happens randomly for example, the backend store throws timeout or service not available. But there is some workaround to reproduce such issue. Go to this line of code
https://github.com/geonetwork/core-geonetwork/blob/695c20e34b54b5760ce80c68c84cff0a26a1abc1/services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java#L192-L196
Place manual exception throwing code:
Build your project and go to editor board and delete any records:
Since there is …
> Error message JSON path fixes in Editor Angular Controllers

- web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/views/default/less/gn_map_default.less
- web-ui/src/main/resources/catalog/views/default/module.js
- web-ui/src/main/resources/catalog/views/default/templates/results.html
The PR allows displaying the map in the left column of the search UI via a setting `showMapInFacet`.
> Enable to display map in left column of search UI

- README.md
Update the build status badge using the one provided by Github Actions.
> Replace Travis badge by Github Actions Badge

- services/src/main/java/org/fao/geonet/api/groups/GroupsApi.java
Test case:
1) Create a new group
2) Create a user and assign it as `editor` in the previous group
3) Login as the previous user and create a metadata
4) Login as an `administrator` user and try to delete the group. An error message should be displayed to indicate the user to transfer the metadata ownership
> Don't allow to delete a group if owns metadata

- web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js
Select the current node if defined in the configuration, otherwise the first one.
To test:
1) Create an UI configuration: `internaldata`
2) Reload the page with the node `srv` : http://localhost:8080/geonetwork/srv/eng/admin.console?debug#/settings/ui --> `srv` UI should be selected
3) Change the node in the url to use `internaldata`: http://localhost:8080/geonetwork/internaldata/eng/admin.console?debug#/settings/ui --> `internaldata` UI should be selected
> Update UI configuration selected by default: 

- web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionsDirective.js
- web-ui/src/main/resources/catalog/js/admin/AdminToolsController.js
- web-ui/src/main/resources/catalog/templates/admin/tools/transferownership.html
Currently the transfer ownership page doesn't sort the `Source group` and `Target group & editor' fields` This is a bit problematic in catalogues with a huger number of groups / users as difficult the selection of the user/group to transfer the ownership.
With this change, the values are displayed sorted.
Updated also the angular directive `gnTransferOwnership` used in the Editor board.
> Sort groups and users in transfer ownership

- pom.xml
CVE-2021-44832: Apache Log4j2 vulnerable to RCE via JDBC Appender when attacker controls configuration.
This issue does not impact default configurations of Log4j2 and requires an attacker to have control over the Log4j2 configuration, which reduces the likelihood of being exploited.
> Bump log4j2 from 2.17.0 to 2.17.1

- web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
- web-ui/src/main/resources/catalog/components/utility/UtilityService.js
This is a follow up of https://github.com/geonetwork/core-geonetwork/pull/4611 which only partially fixed the issue (only for WMS and WMTS).
This PR introduces a new `escapeQuote` filter and uses it on all types of links displayed in the metadata view:
This fix has been done against 3.12.x for easier backporting in the customer project and will be ported to the `main` branch afterwards.
> Metadata view / correctly escape quotes in links title to avoid runtime error

- web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
Followup of https://github.com/geonetwork/core-geonetwork/pull/6095
This PR fixes an overlook on my side which would cause FILE resources names to not be displayed correctly if they contain single quotes.
To clarify: the `toJson` filter will actually output the string value enclosed by double quotes.
> Metadata view / correctly escape quotes for file resources as well

- core/src/main/java/org/fao/geonet/constants/Geonet.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataIndexer.java
- web-ui/src/main/resources/catalog/js/admin/HarvestSettingsController.js
In the Harvester admin page show the harvester records filtering by `_harvesterUuid` instead of `_siteId`.
> Harvester results - filter by harvester uuid instead of site id. Fixes #5530

- web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
- web-ui/src/main/resources/catalog/components/utility/UtilityService.js
Port of https://github.com/geonetwork/core-geonetwork/pull/6095 and https://github.com/geonetwork/core-geonetwork/pull/6121
This is a failsafe solution for avoiding unescaped chars breaking the angularjs expression.
> Port from 3.12: Metadata view / correctly escape quotes in links title to avoid runtime error

- web-ui/src/main/resources/catalog/js/CatController.js
The code added in https://github.com/geonetwork/core-geonetwork/pull/5820 uses the xml formatter for the full view, this seem not correct as the UI doesn't show correctly the metadata information when selecting the Full view in the metadata detail page.
> Fix the metadata full view formatter url

- web-ui/src/main/resources/catalog/components/admin/harvester/HarvesterDirective.js
- web-ui/src/main/resources/catalog/components/admin/harvester/partials/csw-filter.html
- web-ui/src/main/resources/catalog/js/admin/HarvestSettingsController.js
Related to https://github.com/geonetwork/core-geonetwork/pull/5687
GeoNetwork CSW allows to use Lucene fields queryables, not advertised in the Capabilities document. With this change the user can select one of the advertised queryables or write a custom value in the CSW filter fields:
> CSW harvester add typeahead support for filter field names

- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
Without the fix, the full view formatter displays the role code instead of the translation:
After the change:
> Fix to display the role translation instead of the role code in the iso19139 full view formatter

- web-ui/src/main/resources/catalog/js/CatController.js
Removing items in sort by or hits per page in the UI configuration doesn't work. 
Instead of removing the item, it's replaced with the last element in the default UI configuration. For example for sort b , replaces by the "removed" element with the entry `popularity`.
https://github.com/geonetwork/core-geonetwork/blob/829a6f691097a32f5f3685e4a01e6205fa1481ef/web-ui/src/main/resources/catalog/js/CatController.js#L509-L512
> Fix removal of sort by and hits per page elements in the UI configuration

- doi/src/main/java/org/fao/geonet/doi/client/DoiClient.java
- doi/src/main/java/org/fao/geonet/doi/client/DoiManager.java
- doi/src/main/java/org/fao/geonet/doi/client/DoiSettings.java
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/doi-add.xsl
- schemas/iso19139/src/main/plugin/iso19139/process/doi-add.xsl
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v406/migrate-default.sql
Update the code to use the DOI proxy url (https://doi.org/) or the value of new `system/publication/doi/doipublicurl` setting if defined for the DOI resource in the metadata:
```
<gmd:identifier>
<gmd:MD_Identifier>
<gmd:code>
<gmx:Anchor xlink:href="ValueOf('system/publication/doi/doipublicurl'|https:/doi.org)/DOI-PREFIX/DOI">
DOI-PREFIX/DOI
</gmx:Anchor>
</gmd:code>
</gmd:MD_Identifier>
</gmd:identifier>
...
<gmd:onLine>
<gmd:CI_OnlineResource>
<gmd:linkage>
<gmd:URL>ValueOf('system/publication/doi/doipublicurl'|https:/doi.org)/DOI-PREFIX/DOI</gmd:URL>
</gmd:linkage>
<gmd:protocol>
```
> DOI - add identifier / online resource url using the DOI proxy url

- core/src/main/java/org/fao/geonet/resources/CMISConfiguration.java
Updated CMIS connection so that server will still start when CMIS server is down and it will reconnect once the server is up.
Before this fix, if CMIS server was down, the geonetwork server will fail to start which can cause issues in the deployment process.
With this fix, the server will start and will continue to generate errors indicating that the CMIS server is unavailable until this issue is fixed.
> Fix issue with CMIS connection during startup

- web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v300/migrate-default.sql
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v406/migrate-default.sql
The expression was wrong, but in previous versions of Quartz didn't fail. Since the update to version `2.3.2`, if enabled this harvester (**it is disabled by default**), after restarting GeoNetwork an exception occurs that prevents it to start up.
To solve the issue, can be issued the following SQL manually and then restart GeoNetwork:
```
UPDATE Settings SET value = '0 0 0 * * ?' WHERE name = 'system/inspire/atomSchedule' and value = '0 0 0/24 ? * *';
```
Thanks @juanluisrp for checking the cause of the issue.
> Fix the cron expression for the INSPIRE ATOM harvester

- web/src/main/webResources/WEB-INF/urlrewrite.xml
Links such as http://localhost:8080/geonetwork?uuid=aaa-bbb-ccc were not redirecting anymore to http://localhost:8080/geonetwork/srv/fre/catalog.search#/metadata/aaa-bbb-ccc. This is fixed by this PR.
> URL rewrite / Make "/geonetwork?uuid=..." links work again

- web-ui/src/main/resources/catalog/components/common/map/mapService.js
- web-ui/src/main/resources/catalog/components/viewer/wfs/WfsService.js
* In the Related resources Download button for WFS online resources use `typeNames`
instead of `typeName` if the service version is >= "2.0.0"
* Apply this fix to the WFS layer loader in the map too.
Fixes #6087 (https://github.com/geonetwork/core-geonetwork/issues/6087).
> Use typeNames in the WFS URL when version is >= "2.0.0"

- web-ui/src/main/resources/catalog/style/gn.less
The alert message in the online resource popup is displayed below the popup on smaller, less higher screens, this PR has a fix to display the alert message on top of the popup.
**Before**
**After**
> FIX: Display the alert message within the online resource popup

- services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
Similar to the changes done in https://github.com/geonetwork/core-geonetwork/pull/5811, but for transfer ownership.
When the workflow is enabled the transfer ownership works fine in these cases:
- records are in draft
- records approved without working copy
But it's not working fine If the metadata is approved and has a working copy. In this case it's processing all the records, but updating only the working copy version, not the approved version.
This PR updates the transfer ownership API to handle both versions of the metadata. For now, in the total number of records are counted the approved and draft versions. This is something to improve in the report, but will require some refactor of the current report.
---
Test case:
1. On a published record, create and save a working copy.
2. in …
> Update transfer ownership to handle when the metadata workflow is enabled the approved version of the metadata with a working copy

- web-ui/src/main/resources/catalog/components/metadataactions/RelatedObserverDirective.js
A test case:
1) Use a custom view that uses tabs in the metadata detail page, like: https://github.com/osgeonl/geonetwork-dutch-skin
2) Create a metadata with online resources
3) Request the metadata detail page:
http://localhost:8080/geonetwork/srv/eng/catalog.search?#/metadata/UUID?tab=contact
With the previous code, the tab for downloads was selected by default, ignoring the parameter `tab` to select the tab with the contact details.
> Metadata detail page - fix trigger metadata tab selection

- services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
With the workflow enabled for certain groups, when trying to publish a metadata that is in a group that doesn't have the workflow enabled a `NullPointerException` is thrown when the publication code tries to check if the metadata status is `Retired`. Related to https://github.com/geonetwork/core-geonetwork/pull/5943.
Test case:
1) Enable the workflow for certain groups
2) Create a metadata in a group that doesn't have the workflow enabled
3) Publish the metadata --> An error is displayed with the message  `NullPointerException`.
> Metadata publish - check if the metadata owner group has the workflow enabled

- web-ui/src/main/resources/catalog/components/metadatamanager/EditorService.js
- web-ui/src/main/resources/catalog/js/edit/EditorController.js
This PR intends to fix conflicts in catalogs which contain records with integer UUIDs.
* record A has UUID `ABC-DEF` and ID `123`
* record B has UUID `123` and ID `6789`
* when opening the editor for record A with the URL `/geonetwork/srv/fre/catalog.edit#/metadata/123`, the editor form will actually contain record B's fields.
Granted, `123` does not really feel _unique_ (as in UUID), but it is a valid use case nonetheless.
What this PR does:
* boot the ES query on the `id` field to preferably match records based on ID instead of UUID (for retrocompatibility reasons)
* use the fact that `00000123` will be cast to `123` when comparing IDs, but will stay as `00000123` when comparing UUIDs.
> Editor / Avoid conflicts between ID and UUID when editing records

- core/src/main/java/org/fao/geonet/kernel/security/keycloak/keycloakPreAuthActionsLoginFilter.java
- web/src/main/webapp/WEB-INF/config-security/config-security-keycloak.xml
Keycloak backchannel logout was not working due CSRF issue.
This PR fixes the issue by registering the keycloak endpoints to the CSRF bean.
Please backport to 3.12.x
> Fix bug with Keycloak backchannel logout not working due to CSRF issue.

- web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionsDirective.js
- web-ui/src/main/resources/catalog/components/metadataactions/partials/statusupdater.html
The dialog assigns a default status of `0` that is replaced when the current metadata status is received, but if this request takes a bit, the user can click the button to change the status, setting an invalid status to the metadata.
This pull request, disables the button until a valid value is received.
> Metadata status dialog - disable button until receiving the current metadata status value

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/ger/schematron-rules-datacite.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/ger/schematron-rules-datacite.xml
Add the German translations of the Datacite schematron rules for iso19139 and
iso19115-3.2018 schema plugins.
> Add German translations for Datacite schematron rules

- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
- web-ui/src/main/resources/catalog/components/utility/partials/hideshowpassword.html
- web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html
Add a button to toggle the visibility of the user password in the users create and reset password forms, to facilitate the configuration of the user password.
> Users form - add button to toggle password fields visibility

- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataIndexer.java
- events/src/main/java/org/fao/geonet/events/md/MetadataIndexStarted.java
This event allows to implement new classes to  add additional information to be indexed, without requiring to change the indexing code in `BaseMetadataIndexer`.
> Add event allowing to  index additional information

- inspire-atom/pom.xml
- pom.xml
Refactor hibernate version to a property:
* Use `5.4.33.Final` in all the hibernate components.
* Remove specific hibernate-core from inspire-atom project.
> Bump hibernate deps from 5.4.24.Final to 5.4.33.Final

- core/src/main/java/jeeves/server/sources/http/JeevesServlet.java
It seems `JeevesServlet` is only used to initialise the old Jeeves services, there is no servlet mapping defined in `web.xml` for this servlet, so probably the `execute` method could be even removed.
For now, fixing the language cookie configuration, although doesn't seem used that code
> Configure HttpOnly for language cookie and fix the cookie path. Fixes #6151

- web-ui/src/main/resources/catalog/style/gn.less
When the function is used with the input box 'hidden' the input box is not really hidden (this prevents copying) but the input is moved outside the view(port). However, it turned out it wasn't moved far enough in case the recordview page was too high (over 10000px high)
This PR fixes the problem by moving the input very far to the left.
> [Fix] Fix for the copy2clipboard function

- services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
We should not be allowed to transfer the groupowner to a reserved groups such as Intranet.  These groups are only used to grant permissions and not for metadata ownership.
Fix for issue #6189
> Don't allow transfer ownership to reserved groups.

- services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
Related to #6144
---
Test case:
1. On a published record, create and save a working copy. 
2. In the metadata detail page, in the Manage record menu choose Transfer Ownership
4. Choose any user to transfer ownership to
5. In the editor board --> it's displayed the old owner (wrong)
The ownership it is transferred, but the Lucene index is not refreshed properly.
With the PR the new owner is displayed.
> Reindex the working copy when transferred the ownership of a single metadata. Related to #6144

- services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsActionsApi.java
With the metadata workflow enabled, generating a thumbnail with a map doesn't work for metadata working copies.
---
Test case:
1) Enable the workflow
2) Create a metadata (optionally add a WMS service layer)
3) Save & Close it
4) Approve the metadata
5) Edit the metadata to create a working copy
3) In the metadata editor, select **Associated resources** > **Link an online resource** > **Add a thumbnail** > **Generate thumbnail using the view service**,  and select the map extent for the image, clicking **Generate thumbnail**
**Result NOT OK**: the thumbnail image is not generated and not displayed in the metadata file store 
---
Expected result, fixed in the pull request: the thumbnail image is generated and displayed in the metadata file store.
---
The code had a bug that was using the …
> Fix the thumbnail generator using the metadata view services for metadata working copies

- core/src/main/java/jeeves/server/dispatchers/ServiceManager.java
- services/src/main/java/org/fao/geonet/guiservices/util/GetCsvFileName.java
- web/src/main/webapp/WEB-INF/config/config-service-csv.xml
The issue when export as csv
The exported file was in browsing mode:
The user has to use browser's feature to download the file which defeats the purpose of "export". The fix is limited within 3.12 because main branch 4.0 contains different csv service module https://github.com/geonetwork/core-geonetwork/blob/368661c023a3c2648f709dfe284f3185c3bc661b/services/src/main/java/org/fao/geonet/api/records/CatalogApi.java#L465-L533 This feature is relative big and it's not backportable into 3.12. So this short quick fix applies to 3.12 only.
> Export metadata as csv to download (not in browsing mode)

- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
The default icon if the control is of type `password` should have the style `fa fa-eye`:
, but instead it was `fa fa-eye-slash`.
Related to https://github.com/geonetwork/core-geonetwork/pull/6140/, this PR sets the initial button icon depending on the related control type.
> Users form - add button to toggle password fields visibility - fix initial button icon

- web-ui/src/main/resources/catalog/js/GnLoginModule.js
- web-ui/src/main/resources/catalog/js/LoginController.js
Test case related to https://github.com/geonetwork/core-geonetwork/pull/6191
Switch to French UI and send a forgot request password request, the message was displayed in English
> Add Accept-Language header in login controller requests, to set the correct language in the requests done in the login page

- web-ui/src/main/resources/catalog/components/history/partials/historyStep.html
Fix for the `View Previous Version` button for viewing Metadata history.
The link was still using the old formatting which resulted in a malformed url, resulting in an `XML` file with an error, not a file with the history.
> Fix for the `View Previous Version` button for viewing Metadata history

- core/src/main/java/org/fao/geonet/kernel/security/keycloak/KeycloakUtil.java
Fixed issue with getting keycloak token from upgraded security context that was implemented in  PR 6134
It was using the old security context which failed to get the token.
> Fixed issue with getting keycloak token for mapserver proxy from security context.

- web-ui/src/main/resources/catalog/lib/angular.ext/template/tabset.html
- web-ui/src/main/resources/catalog/views/default/templates/home.html
[a11y] Fix for making the tabs on the homepage a11y compliant by adding/removing WAI-ARIA roles
> [a11y] Fix for making the tabs on the homepage a11y compliant

- web-ui/src/main/resources/catalog/views/default/templates/home.html
- web-ui/src/main/resources/catalog/views/default/templates/index.html
Make the search box on the homepage and the footer `a11y` compliant on the homepage.
> [a11y] Make search and footer a11y compliant on the homepage

- web-ui/src/main/resources/catalog/components/catalog/CatalogService.js
- web-ui/src/main/resources/catalog/components/common/map/mapService.js
- web-ui/src/main/resources/catalog/components/common/map/print/PrintMapDirective.js
- web-ui/src/main/resources/catalog/components/common/map/print/PrintMapService.js
- web-ui/src/main/resources/catalog/components/elasticsearch/EsService.js
- web-ui/src/main/resources/catalog/components/search/searchmanager/LocationService.js
- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
- web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextService.js
- web-ui/src/main/resources/catalog/components/viewer/wps/WpsService.js
* Print / fix legend URL sanitizing
* Date picker / avoid running init multiple times
The init function cannot be called more than once and is only called when a config is available
This could result in infinite loops when the date picker is provided with invalid dates
* WPS / invert lat/lon values in bbox data since we're using EPSG:4326
* Switch to Fontawesome v4.7.0
* Search / avoid reloading search when coming from elsewhere if not needed
Previously the search request was always sent again even though parameters
did not change.
* Map / correctly identify WPS processes linked to a layer
* Map / call feedLayerMd when only a md uuid is present
This fixes a regression in https://github.com/geonetwork/core-geonetwork/pull/5307 where a layer with a metadata uuid (i.e. whose metadata was …
> Backports from Sextant

- web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/mapconfig.html
- web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js
This PR allows to select the map context files for the maps in the viewer / search and editor defined in metadata records.
To create these records:
1) In the map viewer, customise the background layers and and extent.
2) In the Maps option select `Save` and configure the metadata title and abstract, click `Save as public record`
2) Go to the UI settings and select the metadata with the map context file to use.
@fxprunayre please check if the protocol filter is ok or should be supported additional values, thanks.
> Allow to configure the map context files for maps (viewer / search / editor) from map context files defined in the metadata online resources

- web-ui/src/main/resources/catalog/style/gn.less
Fix for the alert info message displayed in the footer and sometimes accidentally falling partly outside the popup (smaller screens). This error happens with the info alert for the thumbnail upload tab.
Introduced by https://github.com/geonetwork/core-geonetwork/pull/6109
The PR above causing this should have targeted the warning messages only, not all messages
**Screenshot of the error:**
> Fix for the alert info message displayed in footer and sometimes outside the popup

- web-ui/src/main/resources/catalog/templates/top-toolbar-accessible.html
When ["[FP] Add register and lost password option to accessible login menu - port to main branch (#5968)"](https://github.com/geonetwork/core-geonetwork/commit/a7a80cea6f9f04d6d7ca113caaccfa78ce06733c#diff-64259a4a55847210b6b13c310f9b6175ab291be028046ef8f0aa5e5ecf56ebb8) was done, it reverted some changes.  This FP will put changes back in the main branch.  Without it, keycloak login does not work correctly.
> [FP] Fix bug in signin link (#5630)

- core/src/main/java/org/fao/geonet/util/XslUtil.java
- core/src/test/java/org/fao/geonet/util/XslUtilTest.java
Follow up of https://github.com/titellus/core-geonetwork/pull/80.
eg. while moving content from CMS (which quite often allow HTML content in articles) to the catalogue we can build XSL conversions. It can be useful to preserve some basic layout (at least new lines) in text.
> XSLT / Utility to parse HTML

- schemas/iso19139/src/main/plugin/iso19139/config/associated-panel/default.json
- web-ui/src/main/resources/catalog/components/common/ows/OWSDirective.js
- web-ui/src/main/resources/catalog/components/common/ows/OWSService.js
- web-ui/src/main/resources/catalog/components/common/ows/partials/layer.html
- web-ui/src/main/resources/catalog/components/common/ows/partials/layersTree.html
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcService.js
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html
- web-ui/src/main/resources/catalog/locales/en-editor.json
- web-ui/src/main/resources/catalog/style/gn_editor.less
A metadata schema configuration setting has been added to configure how to add the WMS layer names to the online resources:
- `resourcename`: (Default value) adds the layer names to the name and description fields of the online resources.
- `url`: adds the layer names to url parameter defined in the following UI setting
See the metadata schema configuration setting:
https://github.com/geonetwork/core-geonetwork/pull/6195/files#diff-0cf19d65aac74977b4f108e7dc593e3cf403af32b212e4595fc2bdee132f1c3a
Additionally has been updated the WMS layer widget to display the layer structure:
For example, in the `url` mode for the previous screenshot the following URL is generated using the layer name:
https://maps-cartes.ec.gc.ca/arcgis/services/BC_CriticalHabitat_CB_HabitatEssentiel/MapServer/WMSServer? …
> Metadata editor - allow to add WMS layer names in the URL

- web-ui/src/main/resources/catalog/components/catalog/CatalogService.js
- web-ui/src/main/resources/catalog/components/metadataactions/RelatedDirective.js
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/views/default/templates/index.html
Do not limit filtering on protocol. Allow same filter as in associated resource panel.
eg.
```
'collectionTableConfig': {
'labels': 'title,cl_status,format,download,WMS,WFS,Atom,Links,Legend',
'columns': 'resourceTitle,cl_status[0].key,format,link/protocol:WWW:DOWNLOAD.*,link/protocol:OGC:WMS,link/protocol:OGC:WFS,
link/protocol:atom:feed,link/protocol:WWW:LINK.* AND -function:legend,
link/protocol:WWW:LINK.* AND function:legend'
},
```
Also avoid reloading search when coming from record view.
> Record view / Series / Table of links use filter. 

- core/src/main/java/org/fao/geonet/kernel/setting/Settings.java
- services/src/main/java/org/fao/geonet/api/users/UsersApi.java
- services/src/test/java/org/fao/geonet/api/site/SiteApiTest.java
- services/src/test/java/org/fao/geonet/api/users/UsersApiTest.java
- services/src/test/resources/services-web-test-context.xml
- web-ui/src/main/resources/catalog/js/admin/UserGroupController.js
- web-ui/src/main/resources/catalog/locales/en-v4.json
- web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v407/migrate-default.sql
A new settings allows administrator to reset local user password (feature which was removed in https://github.com/geonetwork/core-geonetwork/pull/5550). Therefor some catalogue setup not having mail server available (and users who don't have access to the database) can't reset password anymore (the only workaround is to drop the user and recreate it). 
This setting is not added to the database by default (for security
reason - see https://github.com/geonetwork/core-geonetwork/pull/5550).
Add it, only if you don't have mail server or if it is difficult to
access to the database.
> Admin / Password reset by admin.

- domain/src/main/java/org/fao/geonet/domain/Setting.java
- domain/src/main/java/org/fao/geonet/domain/SettingToObjectSerializer.java
- web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js
- web-ui/src/main/resources/catalog/templates/admin/settings/system.html
- web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v407/migrate-default.sql
See #5565
A test case:
- Settings > Security panel, **should not** display the setting to define the password pattern. It should be similar to this panel:
> [FP] Support for non-editable settings

- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/table.html
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/locales/en-v4.json
- web-ui/src/main/resources/catalog/views/default/less/gn_card_default.less
Replaces: https://github.com/geonetwork/core-geonetwork/pull/6170
Adding of a 3rd list type for the search results, a table, for a more compact view
**Select the table view**
**Table view**
> New search result list type: Table

- web/src/main/webapp/WEB-INF/classes/cache.ccf
cf georchestra/geonetwork#87, we've been carrying this as a local patch since some years.
otherwise at startup this assumes / is writable which probably works on windows..
```
08:37:24.793 [Catalina-utility-1] ERROR org.apache.jcs.auxiliary.disk.indexed.IndexedDiskCache - Region [xlink] Failure initializing for fileName: xlink and root directory: jcs_caching
java.io.FileNotFoundException: /jcs_caching/xlink.data (No such file or directory)
08:37:24.819 [Catalina-utility-1] ERROR org.apache.jcs.auxiliary.disk.indexed.IndexedDiskCache - Region [SpatialFilterCache] Failure initializing for fileName: SpatialFilterCache and root directory: jcs_caching
java.io.FileNotFoundException: /jcs_caching/SpatialFilterCache.data (No such file or directory)
08:37:24.820 [Catalina-utility-1] ERROR …
```
> Point jcs DiskPath to a dir where java can write

- web-ui/src/main/resources/catalog/components/usersearches/partials/usersearchespanel.html
- web-ui/src/main/resources/catalog/templates/editor/editorboard.html
- web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_facets_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_view.less
- web-ui/src/main/resources/catalog/views/default/templates/results.html
- web-ui/src/main/resources/catalog/views/default/templates/searchForm.html
Replaces: https://github.com/geonetwork/core-geonetwork/pull/6107
When all options are selected in the admin pages, the top of the search page and editor board can be become a little cluttered. This PR reorders the different elements a bit to get a cleaner, more minimal look.
Placing the buttons in the right column enables them to be more responsive and look the same on all screen sizes
Reordered elements:
- user search list to left column
- contribute buttons in (new) right column
- only search input left on top
Small changes:
- color the 'favourite' icon
**2 screenshot for 2 screen sizes**
> Reordering elements on search page and editor board

- web-ui/src/main/resources/catalog/components/utility/DraftValidationWidget.js
- web-ui/src/main/resources/catalog/components/utility/partials/draftvalidationwidget.html
The code to retrieve the metadata draft copy information was using the old query service from GeoNetwork 3.x versions.
To test:
1) Enable the workflow
2) Create a metadata, approve it and edit it again to create a working copy
3) Access to the editor board.
Previously in the application log an error like the following was displayed:
```
06:24:50,883 ERROR [jeeves.service] - (C) Exc : java.lang.UnsupportedOperationException: Use ES search instead. metadatakatalogen | 2022-04-12 06:24:50,845 ERROR [jeeves.service] - Exception when executing service metadatakatalogen | 2022-04-12 06:24:50,883 ERROR [jeeves.service] - (C) Exc : java.lang.UnsupportedOperationException: Use ES search instead.
```
With the fix, no error should be displayed.
> Update DraftValidationWidget to use an ElasticSearch query

- services/src/main/java/org/fao/geonet/api/records/MetadataUtils.java
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/onlinesrcList.html
- web-ui/src/main/resources/catalog/locales/en-v4.json
When 2 records A and B points to the same parent C. The associated panel will list A and B as siblings.
Therefore when editing A or B, user has no privilege to remove the relation in the siblings to the parent.
Also fix list of related records when a record has both siblings and aggregatedResource (only the last category was listed).
> Editor / Associated resource / Don't allow removal of siblings relation.

- web-ui/src/main/resources/catalog/components/search/formfields/FormFieldsDirective.js
Related to https://github.com/titellus/core-geonetwork/pull/108 and https://github.com/geonetwork/core-geonetwork/pull/6232
Test:
* Create 2 harvesters with different group
* Reload
* Both display the group of the first one displayed (they have correct one in db config)
When the ownerGroup prop is updated by the harvester panel, we have to update the selectedGroup.
> Admin / Harvester / Properly set group in scope property

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
Fixes adding online resources to iso19115-3 and dublin core metadata.
Related to #6195
> Metadata editor / Fix initialise the default configuration to handle WMS resources, when it's not defined in the schema configuration. 

- services/src/main/java/org/fao/geonet/api/AllRequestsInterceptor.java
Heritrix is the Internet Archive's open-source, extensible, web-scale, archival-quality web crawler project.
Add this crawler to the list of bots that shouldn't create a session.
Heritrix user-agent string is like this:
```
Mozilla/5.0 (compatible; heritrix/0.11.0 +PROJECT_URL_HERE)
```
Ref: https://github.com/internetarchive/heritrix3
> Add Heritrix to the list of bots that shouldn't create a session

- web/src/main/webapp/xslt/services/suggestions.xsl
Affects GeoNetwork 3.X versions, the xslt was not encoding the character `\` creating an invalid json output.
Potentially, there are other characters that can have a similar issue.
> Fix search suggestions output when a suggestion contains the character \

- core/src/main/java/org/fao/geonet/kernel/security/keycloak/KeycloakAuthenticationProcessingFilter.java
- core/src/main/java/org/fao/geonet/kernel/security/keycloak/keycloakPreAuthActionsLoginFilter.java
Harden keycloak redirect url after login so that it will only perform redirects to the existing server.  Login redirects should always go back to the server.
> Ensure that keycloak login redirects only go the the current server.

- services/src/main/java/org/fao/geonet/api/GlobalExceptionController.java
The runtime error will always throw 500 with stack trace instead of 400 BAD_REQUEST
The issue is related to https://github.com/geonetwork/core-geonetwork/blob/cb92fe7fc08aad84e9cceea4d861bed4e1265365/services/src/main/java/org/fao/geonet/api/GlobalExceptionController.java#L170
The exception handler should check the content like this method https://github.com/geonetwork/core-geonetwork/blob/cb92fe7fc08aad84e9cceea4d861bed4e1265365/services/src/main/java/org/fao/geonet/api/GlobalExceptionController.java#L182
The way I attempt to reproduce the issue is to manually throw some RuntimeException in https://github.com/geonetwork/core-geonetwork/blob/cb92fe7fc08aad84e9cceea4d861bed4e1265365/services/src/main/java/org/fao/geonet/api/records/CatalogApi.java#L603
and insert the code like:
Then invoke …
> check content type for runtime exception

- web-ui/src/main/resources/catalog/components/utility/UtilityService.js
- web-ui/src/main/resources/catalog/js/edit/ImportController.js
- web-ui/src/main/resources/catalog/js/edit/NewMetadataController.js
- web-ui/src/main/resources/catalog/templates/editor/import.html
- web-ui/src/main/resources/catalog/templates/editor/new-metadata-horizontal.html
- web-ui/src/main/resources/catalog/templates/editor/new-metadata-vertical.html
With the original code, the cancel button in the create or import metadata pages displayed the Editor board page, but the search is not executed, causing an empty results page.
This change returns to the previous page in the navigation history. When returning to the editor board the search is preserved, displaying the results.
> Cancelling from import or add new record results in a blank editor board

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/schematron/schematron-rules-iso.sch
Fixes https://github.com/geonetwork/core-geonetwork/issues/6281
During validation, the metadocument contains geonet:info. Be sure to select the identifier only for the check.
> Standards / ISO19115-3 / Validation / Avoid exception on geographicIdentifier

- services/src/main/java/org/fao/geonet/api/GlobalExceptionController.java
In theory, NumberFormatException is type of RuntimeException and should be caught by this handler
https://github.com/geonetwork/core-geonetwork/blob/e58ee2b7a64760239cd816f2f71748d33f5822ba/services/src/main/java/org/fao/geonet/api/GlobalExceptionController.java#L164-L165
It should be either caught with Exception or RuntimeException. However it isn't the case for this API call:
This pull request can fix this issue but it doesn't tell the root cause of it. The issue is also reported: https://github.com/geonetwork/core-geonetwork/pull/6279
> NumberFormatException handling

- web/src/main/webapp/xslt/services/inspire-atom/describe.xsl
Some elements like `link` or `category` were getting an empty (invalid) namespace declaration inline:
```
<link xmlns=""  href=https://...
```
This change fixes the issue.
> Remote ATOM feeds: fix atom describe output to remove a wrong empty namespace in some elements.

- services/src/main/java/org/fao/geonet/api/records/InspireValidationApi.java
- web-ui/src/main/resources/catalog/components/validationtools/GnmdInspireValidationDirective.js
Returning text if an exception occurred, for example no quotas available in the INSPIRE Validator, the `ApiError` returned can not be converted to text format, throwing an additional exception that hides the original exception.
Without the change:
----
A way to test, without requiring that the INSPIRE validator quotas are exceeeded is to modify this method:
https://github.com/geonetwork/core-geonetwork/blob/3851ea69eb33fc4f9b5bdb5dad0872de5ede0dd8/services/src/main/java/org/fao/geonet/api/records/InspireValidationApi.java#L195
To thrown an exception:
```
if (true) {
throw new Exception("Test custom INSPIRE validator error");
}
```
----
Identified in the back port  https://github.com/geonetwork/core-geonetwork/pull/5995, happens  only in `3.12.x` branch, `main` branch …
> Update INSPIRE Validation API to return JSON format.

- core/src/main/java/org/fao/geonet/kernel/setting/HarvesterSettingsManager.java
- domain/src/main/java/org/fao/geonet/repository/GeonetRepositoryFactoryBean.java
- domain/src/main/java/org/fao/geonet/repository/HarvesterSettingRepositoryImpl.java
This causes an error when configuring the harvester password in the credentials section and the harvester is updated. 
Error:
```
<?xml version="1.0" encoding="UTF-8"?>
<error id="error">
<message>Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; nested exception is org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1</message>
<class>ObjectOptimisticLockingFailureException</class>
<stack>
<at class="org.springframework.orm.jpa.vendor.HibernateJpaDialect" file="HibernateJpaDialect.java" line="320" method="convertHibernateAccessException" />
<at class="org.springframework.orm.jpa.vendor.HibernateJpaDialect" file="HibernateJpaDialect.java" line="244" …
```
> Update the harvester setting repository to remove the hierarchical delete of the harvester settings.

- core/src/main/java/org/fao/geonet/util/XslUtil.java
This can be useful in formatter where we only have UUID in sourceinfo
```xsl
<xsl:variable name="sourceName"
select="utils:getNodeName(/root/info/record/sourceinfo/sourceid, $language, false())"/>
```
> XSL / Utility / Get source name by UUID

- web/src/main/webapp/xslt/services/inspire-atom/describe.xsl
Related to #6288
With the fix some namespaces were not handled, rendering in the output only the element content, without the element tag:
```
<updated>2020-07-29T01:00:00Z</updated>
50.73 3.3 50.73 7.24 53.6 7.24 53.6 3.3 50.73 3.3
<category term="https://www.opengis.net/def/crs/EPSG/0/3035" label="ETRS89-extended / LAEA Europe"/>
```
With the fix:
```
<updated>2020-07-29T01:00:00Z</updated>
<georss:polygon>50.73 3.3 50.73 7.24 53.6 7.24 53.6 3.3 50.73 3.3</georss:polygon>
<category term="https://www.opengis.net/def/crs/EPSG/0/3035" label="ETRS89-extended / LAEA Europe"/>
```
> Remote ATOM feeds: fix atom describe output to remove a wrong empty namespace in some elements - handle additional namespaces. 

- core/src/main/java/org/fao/geonet/kernel/datamanager/draft/DraftMetadataUtils.java
- services/src/main/java/org/fao/geonet/api/records/editing/MetadataEditingApi.java
> Metadata workflow: cancelling the metadata editor when editing a working copy always removes the working copy

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/ISO19139/mapping/core.xsl
Even if the ISO19115 defintion of dateStamp is "Date that the metadata was created", it is used mainly as revision date (at least by GeoNetwork). Fix the ISO19139 to ISO19115-3 mapping to set the revision date (instead of creation date).
> Standard / ISO19115-3 / Mapping ISO19139 / Datestamp is revision date

- services/src/main/java/org/fao/geonet/api/records/editing/MetadataEditingApi.java
The metadata approved version requires to be reindexed to display the metadata status as Approved with working copy submitted, otherwise it was displayed as Approved with working copy.
Test case:
1. Go to an approved record and edit it. Save your edits
2. Record shows as "Approved with working copy" in the contribute facet
3. In Working copy edit view, make changes, choose Save and submit
4. In the contribute tab the record should be visible as "Approved with working copy submitted" but it just says "Approved with working copy", although the status shows as submitted when you view the working copy
> Metadata workflow: metadata save and submit was displaying the metadata in a wrong status.

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/add-wms-and-legend-from-esrirest.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/suggest.xsl
- web-ui/src/main/resources/catalog/locales/en-editor.json
When using ESRI to distribute data over geoservices, most of the time the metadata record also reference a WMS endpoint and a link to the legend. Add a simple suggestion to add those links easily.
In one click, 
is updated with
> Standard / ISO19115-3 / Suggestion / Add WMS and legend when ESRI-REST service defined

- web-ui/src/main/resources/catalog/components/edit/multientrycombiner/MultiEntryCombiner.js
- web-ui/src/main/resources/catalog/components/edit/multientrycombiner/partials/multientrycombiner.html
The thesaurus picker directive supports an attribute to configure the number of suggestions to display. 
This change updates the  multicombiner directive allowing to configure the number of suggestions to display for  the elements of type `thesaurus`, that are rendered with the thesaurus picker directive.
> Update multicombiner directive to allow to configure the number of suggestions for the elements that use the thesaurus keyWord picker component

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/ogcwxs/Harvester.java
Fixes https://github.com/geonetwork/core-geonetwork/issues/6273
In that case a NPE was reported in the log with no clear explanation about the issue.
Report error properly so user can try to understand why the capabilities document can't be converted.
eg. a rejected parameter
a version 2.0.0 capabilities (not supported)
> Harvester / OGC / SOS / Do not add version parameter and improve error reporting

- web-ui/src/main/resources/catalog/js/admin/DashboardWfsIndexingController.js
- workers/wfsfeature-harvester/src/main/java/org/fao/geonet/harvester/wfsfeatures/worker/EsWFSFeatureIndexer.java
* Improve logging message (and cleanup)
* Validate geometry before applying precision model (which will fails) and report the error. The feature will be indexed with no geometry
* Handle error on bulk response. Sometimes Elasticsearch fails to index geometry and user can only find the cause in Elasticsearch logs.
Testing can be done with https://sextant.ifremer.fr/Donnees/Catalogue#/metadata/08d2834a-28ed-43d5-8f2c-4bcafdbc445d. The polygon layer contains one invalid geometry.
> Harvester / WFS features / Improvements

- services/src/main/java/org/fao/geonet/services/thesaurus/Add.java
- web-ui/src/main/resources/catalog/js/admin/ThesaurusController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/templates/admin/classification/thesaurus.html
Follow up of https://github.com/geonetwork/core-geonetwork/pull/6283.
By default the thesaurus namespace will be defined based on configuration to simplify creation process for user and make all namespaces more consistent. User can still customize the namespace if needed.
> Admin / Thesaurus / By default use suggested namespace.

- core/pom.xml
- core/src/main/java/org/fao/geonet/kernel/thumbnail/ThumbnailMaker.java
- domain/src/test/java/org/fao/geonet/GeonetworkH2TestEmbeddedDatabaseConfigurer.java
- pom.xml
- services/src/main/java/org/fao/geonet/api/records/formatters/cache/FilesystemStore.java
- web/pom.xml
- web/src/main/webResources/WEB-INF/config-db/h2.xml
- web/src/main/webResources/WEB-INF/config-db/jndiExamples_tomcat/h2_JNDI_Example.xml
- web/src/main/webapp/WEB-INF/classes/log4j.xml
- web/src/main/webapp/WEB-INF/jetty-env.xml
Library reported as having security alerts have been updated and this is a follow up of https://github.com/geonetwork/core-geonetwork/pull/6104.
H2 version 2 can't read a version 1 database.
> Between version `1.4.200` and version `2.0.202` there have been considerable changes, such that a simple update is not possible. The official way to upgrade is to do a BACKUP of your existing database USING YOUR CURRENT VERSION OF H2. Then create a fresh database USING THE NEW VERSION OF H2, then perform a SCRIPT to load your data.
If the catalogue is not using H2 as the main database (as recommended in https://geonetwork-opensource.org/manuals/4.0.x/en/maintainer-guide/production-use/index.html#database), before starting the application remove:
* JS/CSS cache database in $DATA_DIR/wro4j-cache.mv.db …
> Security / Libraries update.

- core/src/main/java/org/fao/geonet/util/XslUtil.java
Test case:
1) Create a service metadata
2) In Contains operations section add a WMS service URL 
3) Click in the suggestions panel, selecting the following one to add the operations from the WMS service
4) Expected: The metadata is updated with the operations from the WMS service. 
The method to retrieve the WMS service capabilities is the one updated in this code change.
> Use SAXBuilder in XslUtil method to retrieve the xml content from an URL

- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataStatus.java
Previously the updated method call was using the date in UTC, while other places setting the date were using the system date.
This was causing when a working copy is created and later used the Save and submit option in the metadata editor, the submitted status had a previous date than the draft status, if GeoNetwork uses a different timezone than UTC. For example:
- draft status --> change date: 12:32:01
- submitted status --> change date: 10:33:10 (should be 12:33:10)
The metadata status is reported wrongly as draft instead of submitted.
> Make consistent the date set in metadata status change date.

- web/src/main/webapp/WEB-INF/classes/ESAPI.properties
ESAPI Logger configuration has changed in 2.2.1.0 (and later).
This fixes this error:
```
ESAPI: Attempting to load validation.properties via the classpath.
ESAPI: validation.properties could not be loaded by any means. fail..
Caught java.lang.IllegalArgumentException;
exception message was: java.lang.IllegalArgumentException: Failed to load ESAPI.properties as a classloader resource.
Error at xsl:value-of on line 52 of error.xsl:
Exception in extension function org.owasp.esapi.errors.ConfigurationException:
java.lang.ClassNotFoundException: org.owasp.esapi.reference.Log4JLogFactory LogFactory
class (org.owasp.esapi.reference.Log4JLogFactory) must be in class path.
2022-05-17 17:36:18,578 ERROR [jeeves] - Exception in extension function
org.owasp.esapi.errors.ConfigurationException: …
```
> Fix ESAPI Logger configuration

- schemas/dublin-core/src/main/java/org/fao/geonet/schema/dublincore/DublinCoreSchemaPlugin.java
- schemas/dublin-core/src/main/plugin/dublin-core/layout/config-editor.xml
In the editor, only parent (isPartOf) is currently supported for Dublin Core records.
> Dublin core / Do not propose associations not supported

- core/src/main/java/org/fao/geonet/constants/Geonet.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/draft/DraftMetadataIndexer.java
- web-ui/src/main/resources/catalog/components/elasticsearch/EsFacet.js
- web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js
- web-ui/src/main/resources/catalog/components/search/mdview/mdviewService.js
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/editor.html
- web-ui/src/main/resources/catalog/views/default/templates/recordView/recordView.html
The backend code always edits the working copy (independently of receiving the identifier of the approved or working copy), but the UI stores the information of the approved version and causes the following error:
```
angular.js?v=0340653132a9d5190768df9193cb149c80f92e7e:14199 SyntaxError: Unexpected token u in JSON at position 0
at JSON.parse (<anonymous>)
at Object.onFormLoad (EditorService.js:415:37)
at refreshForm (EditorService.js:319:24)
at Object.refreshEditorForm (EditorService.js:331:16)
at EditorService.js:163:22
at angular.js?v=0340653132a9d5190768df9193cb149c80f92e7e:11728:13
at processQueue (angular.js?v=0340653132a9d5190768df9193cb149c80f92e7e:16696:28)
at angular.js?v=0340653132a9d5190768df9193cb149c80f92e7e:16712:27
at Scope.$eval …
```
> Metadata workflow: update edit button to use in the link the metadata identifier of the working copy when a metadata has a working copy

- workers/camelPeriodicProducer/src/main/java/org/fao/geonet/camelPeriodicProducer/MessageProducerFactory.java
- workers/camelPeriodicProducer/src/main/resources/config-spring-geonetwork.xml
See https://github.com/georchestra/georchestra/issues/3629 for the
motivation behind this change.
Tests: runtime into a tomcat servlet container, touch'ing web.xml from
GN do not produce the stacktrace about jmx mbeans anymore, and the
webapp successfully redeploys itself.
> wfs-harvesters - properly shutdown quartz

- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid.html
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/list.html
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/table.html
- web-ui/src/main/resources/catalog/views/default/directives/partials/linksbtn.html
When the record is draft, simply add the label to the edit button. The layout is overlapping quite often in list and grid mode
Before
After
> Search results / Draft / Improve edit action layout.

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/fromJsonDkan.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/protocol-mapping.xsl
- web/src/main/webapp/xsl/conversion/import/DKAN-to-ISO19115-3-2018.xsl
Can be tested using the following parameters:
* Url: https://opendata.hautsdefrance.fr/?q=api/3/action/current_package_list_with_resources
* loop element: `/result/0`
* record id path: `id`
* conversion: `DKAN-to-ISO19115-3-2018`
And leave other parameters empty.
> JSON Harvester / Add XSL transformation for harvesting DKAN catalogs

- web-ui/src/main/resources/catalog/components/search/searchoptions/partials/searchoptions.html
- web-ui/src/main/resources/catalog/locales/en-v4.json
- web-ui/src/main/resources/catalog/views/default/less/gn_search_default.less
The advanced search options have all the radios in 1 big row, but they are in fact 2 lists of options.
This PR re-orders the list of language radio options to create a visual hierarchy.
**Before**:
**After**:
> Create hierarchy in the language elements on the advanced search options

- web-ui/src/main/resources/catalog/components/metadataactions/RelatedDirective.js
- web-ui/src/main/resources/catalog/components/metadataactions/RelatedResourcesService.js
- web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
- web-ui/src/main/resources/catalog/views/default/templates/recordView/related.html
More and more record are linking to remote resources (eg. documents, datasets, oceanographic cruises, sensors). This adds the possibility to group associated resources by types.
Before:
After:
or in title mode
> Record view / Associated resources / Group by type.

- web-ui/src/main/resources/catalog/style/gn.less
Affected by https://github.com/geonetwork/core-geonetwork/commit/4b1cfae728780ad5dbf8b9dd48a19f4389a32e47 scale prefix depending on language was missing.
Before
After in French
and English
> Record view / Scale prefix is missing.

- web-ui/src/main/resources/catalog/views/default/directives/partials/mdactionmenu.html
Test case:
1) Login as administrator and configure in the settings page the DOI publication.
2) Create an iso19139 metadata.
3) In the metadata detail page, open the Manage record menu --> DOI publication option is disabled (OK)
4) Select the Publish option --> DOI publication option is disabled (NO OK)
With the fix, after selecting the Publish option, the DOI publication option is enabled.
> Fix DOI publication task enabling after publishing the metadata

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/onlinesrc-add.xsl
- schemas/iso19139/src/main/plugin/iso19139/process/onlinesrc-add.xsl
When adding new link, if the current record contains empty (ie. no url, no name, no protocol) then the `updateKey` used for updating a link trigger insertion of the added link in those empty element.
Checking that the `updateKey` is not empty to add the link once and in the correct position.
Test
* Create a record with a link with no url, no name, no protocol
* Add a new link - it will be inserted twice 
This usually does not happen often but can be when using a template with empty links by default.
> Editor / Online source added in empty links.

- core/src/main/java/org/fao/geonet/constants/Edit.java
- core/src/main/java/org/fao/geonet/kernel/AccessManager.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataOperations.java
- core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java
- core/src/main/java/org/fao/geonet/kernel/setting/Settings.java
- services/src/main/java/org/fao/geonet/api/ApiUtils.java
- services/src/main/java/org/fao/geonet/api/es/EsHTTPProxy.java
- services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
- web-ui/src/main/resources/catalog/components/common/share/ShareDirective.js
- web-ui/src/main/resources/catalog/components/common/share/ShareService.js
- web-ui/src/main/resources/catalog/components/common/share/partials/panel.html
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/locales/en-v4.json
- web-ui/src/main/resources/catalog/views/default/directives/partials/mdactionmenu.html
- web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v421/migrate-default.sql
Test:
* Create Group A, Group B
* Create User 1, Editor in Group A, Reviewer in Group B
* Create new record in Group A
* Allow editing to Group B
* Connect as User 1
* Privileges popup allows checking All/Intranet/Guest groups but API will skip them (see https://github.com/geonetwork/core-geonetwork/blob/main/services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java#L271-L272)
Some API call returns
```
"description": "User not allowed to publish the metadata 127.
You need to be administrator, 
or reviewer of the metadata group 
or reviewer with edit privilege on the metadata."
```
See https://github.com/geonetwork/core-geonetwork/commit/36a2a588ebd236dd86eb504c5eeb78c21cdd9f96
Privileges management popup check if user is Reviewer in groupOwner or in groups with editing …
> Sharing / Who can publish?

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl
- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
The code didn't use that information, so the full formatter used the first label found for elements with the same name configured in the file `labels.xml` with different context:
```
<element name="gmd:language" context="gmd:MD_Metadata">
<label>Taal van de metadata</label>
<description>Taal waarin de metadata is beschreven.</description>
<condition>mandatory</condition>
</element>
<element name="gmd:language" context="gmd:MD_DataIdentification">
<label>Taal van de bron</label>
<description>De taal waarin eventuele tekst in de bron is opgenomen. Verplicht als de dataset  tekstuele informatie bevat. </description>
<condition>mandatory</condition>
</element>
```
The `context` attribute can contain a full xpath also, but in the formatter, using `gn-fn-metadata:getXPath(.)` doesn´t return the …
> Use parent element to retrieve labels in the schemas that use the context attribute

- web-ui/src/main/resources/WEB-INF/classes/web-ui-wro-sources.xml
- web-ui/src/main/resources/catalog/components/userfeedback/GnUserfeedbackDirective.js
- web-ui/src/main/resources/catalog/components/userfeedback/partials/userfeedbacknew.html
- web-ui/src/main/resources/catalog/locales/en-search.json
- web-ui/src/main/resources/catalog/views/default/less/gn_feedback_default.less
- web/src/main/webapp/xslt/base-layout-cssjs-loader.xsl
This PR improves the messages when adding new feedback by using `ngMessages`. Messages are shown inline, and the `Save` is enabled when everything is valid.
An additional check is done on the 'review' input, a check on the maximum characters.
> Add inline messages for the Add Feedback form

- web-ui/src/main/resources/catalog/components/userfeedback/partials/userfeedbacknew.html
Hiding the fields trigger the validation, it is required to use `data-ng-if` directive instead of `data-ng-hide`
> User metadata feedback - fix related to #6341 to don't include  unrequired fields when the user is logged.

- web/src/main/java/org/fao/geonet/proxy/URITemplateProxyServlet.java
The targetUri property of proxyURITemplateProxyServlet can be now defined externally to `web.xml`. The value defined externally will override the one defined in `web.xml`.
The lookup order in that case would be:
1.  `${GEONETWORK_APP_NAME}_${SERVLET_NAME}_TARGETURI}`: look for an environment variable, for example `MYWEBAPP_MICROSERVICESPROXY_TARGETURI`
2. `${GEONETWORK_APP_NAME}.${SERVLET_NAME}.targetUri`: Look for a system property, for example `mywebapp.MicroservicesProxy.targetUri`
3. `${GEONETWORK_APP_NAME}.${SERVLET_NAME}.targetUri`: Look for a property in `config.properties`, for example `mywebapp.MicroservicesProxy.targetUri`
4. `GEONETWORK_${SERVLET_NAME}_TARGETURI`: Look for an environment variable starting by GEONETWORK, for example `GEONETWORK_MICROSERVICESPROXY_TARGETURI`
5. …
> Externalise the configuration of targetUri property

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/ISO19139/mapping/core.xsl
The 'ISO19139-to-ISO19115-3-2018' XSLT copies the name of the old metadata standard into the converted record.
Into an 'iso19115-3' record it inserts:
```
<mdb:metadataStandard>
<cit:CI_Citation>
<cit:title>
<gco:CharacterString>ISO 19115:2003/19139</gco:CharacterString>
</cit:title>
<cit:edition>
<gco:CharacterString>1.0</gco:CharacterString>
</cit:edition>
</cit:CI_Citation>
</mdb:metadataStandard>
```
It should be inserting this:
```
<mdb:metadataStandard>
<cit:CI_Citation>
<cit:title>
<gco:CharacterString>ISO 19115-3:2018</gco:CharacterString>
</cit:title>
<cit:edition>
<gco:CharacterString>1.0</gco:CharacterString>
</cit:edition>
</cit:CI_Citation>
</mdb:metadataStandard>
```
Without this fix, when there are a lot of records to upgrade, it is very laborious. Every record has to be …
> iso19139-to-iso19115-3-2018 xslt converter outputs the wrong metadata standard name

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/ISO19139/mapping/core.xsl
Enable fixed default metadata std name for iso19115-3 conversion
But if the source metadata name is not the standard iso19139, it will pass it through instead
This is a backport of PR#6354 for 3.12.x branch
> Backport: iso19139-to-iso19115-3-2018 xslt converter outputs the wrong metadata standard name

- web-ui/src/main/resources/catalog/components/metadataactions/partials/recordsTable.html
- web-ui/src/main/resources/catalog/style/gn.less
No reason to use success for format. Use same color as in record view for datasets
Add (restore) status badge with color
> Record view / Series / Members table / Format and status using badge

- schemas/config-editor.xsd
- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
- web/src/main/webapp/xslt/ui-metadata/form-configurator.xsl
- web/src/main/webapp/xslt/ui-metadata/menu-builder.xsl
- web/src/main/webapp/xslt/ui-metadata/menu-fn.xsl
Editor configuration allows to conditionnaly display elements or not. Condition based on session info (eg. user profile) was only allowed for `view` and `tab` elements. Apply condition on the current record and on session for all elements (`field`, `section`, `text`, `directive`, `action`).
Example:
* Display a view for admin only
```xml
<view name="custom-view"
displayIfServiceInfo="count(session[profile = 'Administrator']) = 1"
```
* Display help text for non geographic dataset
```xml
<text if="count(gmd:MD_Metadata/gmd:hierarchyLevel[*/@codeListValue =
'nonGeographicDataset']) = 1"
ref="eea-conformity-help"/>
```
* Display an action if the element does not exist and user is admin
```xml
<action   type="add"
btnLabel="eea-add-identifier" …
```
> Editor / Configuration / Add condition on element and session for all.

- web-ui/src/main/resources/catalog/js/edit/NewMetadataController.js
- web-ui/src/main/resources/catalog/templates/editor/new-metadata-horizontal.html
- web-ui/src/main/resources/catalog/templates/editor/new-metadata-vertical.html
Instead of manually computing types, use an aggregation.
Improve translation and sorting.
If only one template, one group and no custom UUID directly jump to editor.
> New metadata / Use facet to compute types

- common/pom.xml
- common/src/main/java/org/fao/geonet/utils/Diff.java
- core/pom.xml
- core/src/main/java/org/fao/geonet/kernel/thumbnail/ThumbnailMaker.java
- pom.xml
- schemas/dublin-core/pom.xml
- services/pom.xml
- services/src/main/java/org/fao/geonet/api/records/formatters/FormatterApi.java
- services/src/main/java/org/fao/geonet/api/records/formatters/ImageReplacedElementFactory.java
- web/pom.xml
Initially focused on using dependency exclusion to swap iText to OpenPDF for map fish print.
Also found flying-saucer-pdf-itext5 was in use and changed to flying-saucer-pdf-openpdf.
The older iText library has known security vulnerabilities, OpenPDF is a drop-in replacement (forking from iText 4.2.0 to maintain an open-source license).
References:
* https://github.com/LibrePDF/OpenPDF
* https://github.com/flyingsaucerproject/flyingsaucer
Notes:
- The version dependency print-lib 2.1.6 used does not appear in maven central and may be a fork created for core-geonetwork. This version has a dependency on iText 5.5.13 and may need to be adjust to the OpenPDF (iText 4.2.0 API).
- print-lib 2.0.0 uses the iText 2.1.5 API
- Newer versions of print-lib are available that make use of jasper reports …
> Switch from itext to openpdf for PDF map rendering

- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
- web/src/main/webapp/WEB-INF/oasis-catalog.xml
Related to https://github.com/geonetwork/core-geonetwork/pull/6355.
```
Error at xsl:variable on line 399 column 97 of render-layout.xsl:
XPST0081: XPath syntax error at char 143 on line 399 in {...Record, @displayIfServiceIn...}:
Undeclared namespace prefix {gn-fn-metadata}
Error at xsl:variable on line 415 column 97 of render-layout.xsl:
XPST0081: XPath syntax error at char 143 on line 415 in {...Record, @displayIfServiceIn...}:
Undeclared namespace prefix {gn-fn-metadata}
```
> Formatter / Full view / Add function for conditional element.

- schemas/iso19139/src/main/plugin/iso19139/formatter/citation/view.xsl
- web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionsDirective.js
Avoid error on ISO19139 records
```
Error at xsl:call-template on line 117 column 69 of view.xsl:
XTSE0650: No template exists named get-iso19115-3.2018-localised
```
due to 19115-3 dependency.
For testing enable citation in UI config
```json
'recordview': {
'showCitation': {
'enabled': true,
```
Also fix formats duplicated
> Record view / Citation / ISO19139 fix

- doi/src/main/java/org/fao/geonet/doi/client/DoiBuilder.java
- doi/src/main/java/org/fao/geonet/doi/client/DoiClient.java
- doi/src/main/java/org/fao/geonet/doi/client/DoiManager.java
- doi/src/main/java/org/fao/geonet/doi/client/DoiSettings.java
- doi/src/main/resources/config-spring-geonetwork.xml
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/datacite/view.xsl
- schemas/iso19139/src/main/plugin/iso19139/formatter/datacite/view.xsl
- services/src/main/java/org/fao/geonet/api/records/DoiApi.java
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v421/migrate-default.sql
When creating a DOI, the DOI id was created using `https://doi.org/{{prefix}}/{{uuid}}`
@pvgenuchten tested to customize the DataCite prefix in https://github.com/geonetwork/core-geonetwork/pull/6148
but as discussed it can be more flexible to add a new settings to customize the DOI with a pattern.
Default is `{{uuid}}` but the DOI structure can be customized with database id and/or record group eg. `example-{{groupOwner}}-{{id}}` or simply `{{id}}`. Some users complain about the length of current DOI - so instead of relying on https://shortdoi.org/ user could use the internal db id if it is unique in the prefix scope ...
An API operation to check the DOI created is added.
> DOI / Configure DOI URL pattern

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/ogcwxs/Harvester.java
- web-ui/src/main/resources/catalog/js/admin/HarvestSettingsController.js
Eg. when running harvesting with 19139 to 115-3 conversion, the record was registered with 19139 schema (with indexing error). The conversion was also only applied to the service record and not its datasets.
Also fix the lists of template which were not listing 115-3 templates (cl_hierarchyLevel field is 19139 specific, resourceType works with all ISO schemas).
> Harvester / OGC WxS / After applying conversion, update schema

- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
Replaces: https://github.com/geonetwork/core-geonetwork/pull/6212
Small fix to make the copy button from the copy2clipboard option accessible by adding `href`
> [a11y] Small fix to make the copy button from the copy2clipboard option accessible

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/onlinesrcList.html
This code change, hides the DOI publication option in the metadata editor, when the metadata workflow is enabled for a metadata, as only approved / published metadata can request DOI publication. 
To publish DOI of a metadata in the workflow, first should be approved / published. This action in the metadata editor should not be available.
> Disable the DOI publication in the metadata editor for metadata using the metadata workflow

- core/pom.xml
- core/src/main/java/org/fao/geonet/kernel/thumbnail/ThumbnailMaker.java
- pom.xml
- services/pom.xml
- services/src/main/java/org/fao/geonet/api/records/formatters/FormatterApi.java
- services/src/main/java/org/fao/geonet/api/records/formatters/ImageReplacedElementFactory.java
- services/src/main/java/org/fao/geonet/api/standards/StandardsApi.java
- web/pom.xml
Backport of https://github.com/geonetwork/core-geonetwork/pull/6343
Original PR from @jodygarnett.
> [BP] Switch from iText to OpenPDF for PDF map rendering

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/fromJsonDkan.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/fromJsonOpenDataSoft.xsl
- Opendatasoft
ensure languages are iso3 code (was indexing in langfr instead of langfre)
- DKAN
Trim extra space on keywords (was disturbing the indexing).
> JSON Harvesters: Fix ODS and DKAN issues

- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
The toggle button stopped working due to a change in the DOM structure so no sections were selected
> Fix the `toggle all sections` button in the editor.

- web-ui/src/main/resources/catalog/components/edit/datepicker/DatePickerDirective.js
- web-ui/src/main/resources/catalog/components/edit/datepicker/partials/datepicker.html
- web-ui/src/main/resources/catalog/style/gn_editor.less
Add a configuration parameter to show / hide the date mode selector. To use it for example in iso19139 metadata for the data information dates, to hide the selector, update the following code:
https://github.com/geonetwork/core-geonetwork/blob/3d16732759f656ff1aa7108a6c6bbd80498b6ae8/schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields-date.xsl#L135-L141
```
<div data-gn-date-picker="{gco:Date|gco:DateTime}" 
data-gn-field-tooltip="{$tooltip}" 
data-label="" 
data-element-name="{name(gco:Date|gco:DateTime)}" 
data-element-ref="{concat('_X', gn:element/@ref)}" 
data-hide-date-mode="true"
data-hide-time="{if ($viewConfig/@hideTimeInCalendar = 'true') then 'true' else 'false'}"> 
</div> 
```
This is useful to force the widget to support only date / datetime format, excluding …
> Update datepicker widget to configure the display of the date mode selector

- pom.xml
The dependency adds some additional dependencies, causing this type of errors:
```
java.lang.NoSuchMethodError: org.apache.logging.log4j.util.StackLocatorUtil.getCallerClassLoader(I)Ljava/lang/ClassLoader;
```
Related to https://github.com/geonetwork/core-geonetwork/pull/6392
> Exclude log4j-1.2-api dependency from MapFish

- inspire-atom/src/main/java/org/fao/geonet/inspireatom/util/InspireAtomUtil.java
For example: http://geodata.nationaalgeoregister.nl/atom/index.xml, contain some entries like the following with an empty value for `inspire_dls:spatial_dataset_identifier_code`:
```
<entry>
<id>https://geodata.nationaalgeoregister.nl/rvo-schelpdierpercelen/atom/rvo-schelpdierpercelen.xml</id>
<title type="text" xml:lang="nl">RVO - Schelpdierpercelen - Parent Feed (CRS)</title>
<summary type="text" xml:lang="nl">Atom feed voor de download van dataset RVO - Schelpdierpercelen</summary>
<category term="http://www.opengis.net/def/crs/EPSG/0/28992" label="Amersfoort / RD New"/>
<georss:polygon>50.6 3.1 50.6 7.3 53.7 7.3 53.7 3.1 50.6 3.1</georss:polygon>
<link href="https://www.nationaalgeoregister.nl/geonetwork/srv/dut/xml.metadata.get?uuid=" rel="describedby" type="application/xml"/>
<link …
```
> Remote INSPIRE Atom - skip processing dataset feed entries without an identifier

- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v421/migrate-default.sql
- web/src/main/webapp/WEB-INF/data/config/codelist/external/thesauri/place/regions.rdf
"The Republic of Türkiye changed its official name from The Republic of
Turkey on 26 May 2022 in a request submitted to the Secretary-General by
the country's Minister of Foreign Affairs."
cf. https://www.un.org/en/about-us/member-states/turkiye
> Thesaurus / Regions / Turkey is now Türkiye

- services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
Issue introduced by https://github.com/geonetwork/core-geonetwork/commit/28b22da39ffc32824faf47b0f00dc0788df61831#diff-fd5c78f078bd1495f232ed345a67141aea9d5c2dc34075ab6ff34b772f4b7c0aR420
See the doc - settings generateUuid is disabled to use custom identifier
https://geonetwork-opensource.org/manuals/3.10.x/fr/administrator-guide/managing-metadata-standards/metadata-identifier.html
> Metadata template identifier / Always generate UUID

- web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/views/default/templates/footer.html
This change adds a new configuration option to allow display/hide the application version and links in the footer.
**With the option disabled:**
**With the option enabled:**
> Configuration option to display the application version and links to the About, GitHub and API pages in the footer

- web-ui/src/main/resources/catalog/components/edit/validationreport/ValidationReportDirective.js
XSD rules are a bit technical for most end users, and the errors reported are usually covered by the schematron rules defined in the schemas, that are more clear to review by users. 
This change moves the position of the `xsd` validation from the top to the bottom (of the mandatory rules) to faciliate the review of the validation errors.
> Move xsd validation to the bottom of the mandatory rules, displaying first the schematron rules

- core/src/main/java/org/fao/geonet/kernel/GeonetworkDataDirectory.java
When using a config property for setting the directories GN must search for
`<webappName>.propert`y name and if not found it must look for `geonetwork.property`.
This commit adds this `geonetwork.property` lookup.
This PR aligns the behaviour of GN with the [documentation](https://geonetwork-opensource.org/manuals/trunk/en/install-guide/customizing-data-directory.html#advanced-data-directory-configuration):
> All sub-directories could be configured separately using Java system property. For example, to put index directory in a custom location use:
> 
> * `<webappName>.lucene.dir` and if not set using:
> * `geonetwork.lucene.dir`
> Fix lookup of data directory sub-properties

- core/src/main/java/org/fao/geonet/api/records/attachments/AbstractStore.java
- services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java
Geonetwork resource upload API does support filename contains semicolon.
Semi colon is not well recognized by spring framework path therefore the resource is not pulled correctly in the GET api.
This code change intention is to prevent the user to upload such file at the first place.
> Block filename contains semicolon.

- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
Increase the number of users displayed in the users dropdown in the versioning log page.
The original value was 5 and that's increased to 100. The dropdown has a max height defined, so a scrollbar will appear when the list of users is large.
**Before**:
**After**:
> Increase the number of users in dropdown in the versioning log page

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl
- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
* Avoid empty keyword in view mode
* Allow to override thesaurus title using field name
```
<field xpath=".//mri:descriptiveKeywords[*/mri:thesaurusName]" name="verticalDatum"/>
```
* Consistent rendering in ISO19139 and 115-3
> Standard / ISO / Keyword configuration and labels

- core/src/main/java/org/fao/geonet/kernel/mef/Importer.java
- services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
Test case:
1) Import a valid xml or MEF file, checking the Validate option.
2) In the editor boards, the metadata validation icon should be green, but without this change the icon is displayed as gray (no validation tested)
In the original code the Validate option was used to discard the metadata if not valid, but the metadata status when the metadata is valid was not stored.
> Metadata import - store the validation status when the validation option is selected

- web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js
- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
- web-ui/src/main/resources/catalog/components/utility/partials/indexerrorpanel.html
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/templates/admin/admin.html
- web-ui/src/main/resources/catalog/templates/editor/editorboard.html
- web-ui/src/main/resources/catalog/views/default/templates/home.html
- web-ui/src/main/resources/catalog/views/default/templates/results.html
* Add a link to documentation
* Do not display search errors when the panel is already here
* For admin display a link to status page
* Display panel in all pages
> Search / Improve error panel when Elasticsearch is down

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
- schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
With the original code if identifier parameter of the `xlink:href` for a GetRecordsById contains an `_` character, the identifier was not extracted properly:
```
<srv:operatesOn 
xlink:href="https://SERVER/csw?service=CSW&request=GetRecordById&version=2.0.2&
outputSchema=http://www.isotc211.org/2005/gmd&elementSetName=full&id=maaamet_geoloogiline_baaskaart"/>
```
The value extracted was `maaamet` instead of `maaamet_geoloogiline_baaskaart`
> Fix the operatesOn indexing when the xlink:href it's a GetRecordById, with the identifier contanining an underscore character

- web-ui/src/main/resources/catalog/components/usersearches/partials/portalswitcher.html
If catalog contains only one portal, then:
* the link back to the main node is not displayed.
* portal switcher label is displayed
Before
After link to main node is displayed
> Top toolbar / Portal switcher / Display main node when only one portal

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/ogcwxs-info-injection.xsl
When harvesting a WMS service with the OGCWxS harvester and:
1) The "GetCapabilities" response has "&lt;AccessConstraints&gt;NONE&lt;/AccessConstraints&gt;"
2) There is an "&lt;MD_LegalConstraints&gt;" element in the record template
The harvester outputs two "&lt;MD_LegalConstraints&gt;": a "no conditions apply" from 1) and the element from 2)
This is a problem because it is outputting two legally contradictory "&lt;MD_LegalConstraints&gt;" elements.
This fix makes sure if the GetCaps "&lt;AccessConstraints&gt;" is set to "NONE" then the template can override this with a more informative value. 'NONE' is geoserver's default value for this field.
Also I have updated the old iso19139 "MD_RestrictionCode" values with iso19115 values.
> Fix for OCGWxS harvester resource constraint errors

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFsHarvesterFileVisitor.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/simpleUrl/Harvester.java
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/fromJsonUdata.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/udata-licenses.xsl
- web/src/main/webapp/xsl/conversion/import/udata-to-ISO19115-3-2018.xsl
udata is a catalog software used mainly by [data.gouv.fr](https://www.data.gouv.fr/en/). Source code is here: https://github.com/opendatateam/udata
This PR simply adds a transformation to be used by the JSON harvester. To test, use the following parameters:
* URL: https://www.data.gouv.fr/api/1/datasets/?page_size=100
* loop element: `/data`
* path to number of record: `/total`
* path to record id: `id`
* transformation to ISO: `udata-to-ISO19115-3-2018`
Not supported yet:
* ~spatial extent~ won't do as we need a geojson to GML transformation first
* ~temporal coverage~ done
* ~expanding license information~ done
Note that udata's pagination cannot be used by the harvester currently as udata expects a _page number_ query parameter instead of a _from_ parameter.
> Support harvesting udata catalog (e.g. data.gouv.fr)

- web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js
The metadata status is set to the value 0 (unknown status) instead of the value 100 that corresponds to the DOI request.
Test case:
1) Login as admin user, go to the settings and enable the metadata workflow and configure the DOI publication panel.
2) Create an iso19139 valid metadata.
3) Complete the following steps in sequence without refreshing the page:
- Chose Manage Record > Directly approve metadata (status is set to `Approved`)
- Chose Manage Record > Publish
- Chose Manage Record > DOI creation request
Result:
- Record status is now `Unknown`.
Expected:
- Record status is `Approved`.
Workaround:
- Refresh page between steps in 3)
> Fix inconsistent metadata status when requesting the DOI publication after the metadata approval and publication

- web/src/main/webapp/xslt/common/index-utils.xsl
`resourceTemporalExtentDetails` field used to display temporal range in record view was not populated when range is using only year or year-month notation.
```json
"resourceTemporalExtentDateRange": [
{
"gte": "2004-12-31T23:00:00.000Z",
"lte": "2020-12-31T23:00:00.000Z"
}
],
"resourceTemporalExtentDetails": [
{
"start": {
"date": "2005"
},
"end": {
"date": "2021"
}
}
],
```
> Index / Temporal range / Handle cases for year and year month only

- core/src/main/java/org/fao/geonet/kernel/EditLib.java
- core/src/test/java/org/fao/geonet/kernel/EditLibIntegrationTest.java
2 issues fixed:
* API / XPath editing / Delete non existent node
Using XPath API to update a record was creating empty node when deleting non existent node (usually when xpath contains filter with no match). In deletion mode, we should never try to create elements corresponding to the requested XPath if there is no match.
* API / XPath editing / gn_replace_all mode may keep empty elements.
Issue introduced in
https://github.com/geonetwork/core-geonetwork/pull/6423.
Symptoms : edit a record with a topic category, switch to xml view
Empty `<gmd:topicCategory/>` elements are in the record.
When `gn_replace_all` is used the `gn_delete` steps was not take into
account.
> API / XPath editing / Delete and replace_all fix

- web/src/main/webapp/xml/csw/record-to-csw-capabilities.xsl
Fix
```
<ows:Operation name="GetRecordById">
<ows:DCP>
<ows:HTTP>
<ows:Get xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="$https://metawal.wallonie.be/geonetwork/inspire/fre/csw"/>
....
<inspire_com:ResourceLocator>
<inspire_com:URL>{$endPointValue}?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetCapabilities</inspire_com:URL>
<inspire_com:MediaType>application/xml</inspire_com:MediaType>
</inspire_com:ResourceLocator>
```
https://github.com/SPW-DIG/metawal-core-geonetwork/issues/762
> CSW - Fix typo (variable endPointValue)

- web-ui/src/main/resources/catalog/js/edit/DirectoryController.js
Fix https://github.com/geonetwork/core-geonetwork/issues/6447
Load of templates of subtemplates when trying to add a new entry from templates.
> fix: entries list in registry board

- web-ui/src/main/resources/catalog/components/metadataactions/partials/metadataCard.html
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid4maps.html
- web-ui/src/main/resources/catalog/components/usersearches/partials/featuredusersearchescards.html
- web-ui/src/main/resources/catalog/style/gn_icons.less
- web-ui/src/main/resources/catalog/views/default/directives/partials/infolist.html
- web-ui/src/main/resources/catalog/views/default/templates/home.html
- web-ui/src/main/resources/catalog/views/default/templates/recordView/metadata.html
- web-ui/src/main/resources/catalog/views/default/templates/recordView/recordView.html
- web-ui/src/main/resources/catalog/views/default/templates/recordView/spatial.html
- web-ui/src/main/resources/catalog/views/default/templates/recordView/type-dataset.html
- web-ui/src/main/resources/catalog/views/default/templates/results.html
- web/src/main/webapp/xslt/base-layout-cssjs-loader.xsl
- web/src/main/webapp/xslt/ui-search/portal-list.xsl
This PR adds a new stylesheet for printing via the browser and adds Bootstrap classes to hide certain parts/components of the layout.
These Bootstrap classes are used to have more control via the HTML
The Bootstrap framework already has styles for printing that are automatically used when printing. Some of these styles have been overridden:
- to show the logo
- to hide some link urls
> Add print styles and stylesheet to GeoNetwork

- cachingxslt/pom.xml
- core/pom.xml
- pom.xml
- workers/pom.xml
The log from the libraries using log2j 1.2 should work fine, using the log4j 1.x bridge.
Related to #6397
Before the change:
After the change:
> log4j2 upgrade - add dependency exclusions to avoid including log4j 1.2.17.

- pom.xml
izpack installer was removed in https://github.com/geonetwork/core-geonetwork/pull/4961
When merged, should be closed also https://github.com/geonetwork/core-geonetwork/pull/6388
> Remove unused izpack-standalone-compiler dependency

- docs/schema-doc/src/main/resources/config-editor-to-rst.xsl
Links to the schema docs sections were not generated properly, causing a wrong rendering as text:
> Fix links not generated properly in schema docs

- web-ui/src/main/resources/catalog/style/gn.less
- web-ui/src/main/resources/catalog/views/default/templates/results.html
[a11y] `TAB` order of the row tools on the search page
The focus/tab order of the elements on the toolbar on the search page wasn't correct.
This PR will fix the order of elements in the DOM and therefore the order of focus (when the `TAB` key is used)
> [a11y] `TAB` order of the row tools on the search page

- core/src/main/java/org/fao/geonet/constants/Geonet.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataIndexer.java
- domain/src/main/java/org/fao/geonet/domain/UserSavedSelection.java
- domain/src/main/java/org/fao/geonet/repository/UserSavedSelectionRepository.java
- services/src/main/java/org/fao/geonet/api/selections/UserSelectionsApi.java
- services/src/test/java/org/fao/geonet/api/selections/UserSelectionsApiTest.java
- web/src/main/webResources/WEB-INF/data/config/index/records.json
A new `userSavedCount` field is added to the records in the index. It contains the amount of users that saved the record in at least one selection. This also adds indexation of records whenever they are added/removed to saved selections.
Note that records are not indexed when a whole selection is cleared or deleted.
Fixes https://github.com/geonetwork/core-geonetwork/issues/6509
> User Saved Selections / index amount of users that saved a record

- core/src/main/java/org/fao/geonet/constants/Geonet.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java
- core/src/test/java/org/fao/geonet/kernel/datamanager/BaseMetadataManagerTest.java
- core/src/test/resources/org/fao/geonet/kernel/doi-metadata.iso19139.xml
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/duplicate-metadata.xsl
- schemas/iso19139/src/main/plugin/iso19139/duplicate-metadata.xsl
This change adds support for an optional xslt process `duplicate-metadata.xsl` in the metadata schemas to update a metadata when it is duplicated or used to create a child. 
It currently adds support for ISO19139 and ISO19115-3.2018 schemas to remove the DOI elements in duplicate metadata, but can be extended to process any additional element that should not be available in duplicate metadata.
----
Schemas extending ISO19139 should add a file `duplicate-metadata.xsl` with the following content to reuse the code from ISO19139:
```
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0">
<xsl:import href="../iso19139/duplicate-metadata.xsl"/>
</xsl:stylesheet>
```
Similar for schemas extending ISO19115-3.2018:
```
<xsl:stylesheet …
```
> Support for a process to update the metadata content when creating a duplicate

- core/src/test/resources/org/fao/geonet/api/Messages.properties
- core/src/test/resources/org/fao/geonet/api/Messages_fre.properties
Related to this change https://github.com/geonetwork/core-geonetwork/pull/6508
Causing to fail the test in https://github.com/geonetwork/core-geonetwork/pull/6507
In `main` the related it's executed as an integration test, running `mvn verify -Pit` in the `core` module.
> Add Message.properties files to core tests to avoid the failure of test that use code retrieving messages from that files

- workers/pom.xml
`log4j-slf4j18-impl` was declared more than once in the `workers/pom.xml` file. Removed the extra declarations.
Remove the version of the dependencies that have been already declared in the `managedDependencies`of the parent pom.xml file.
> Remove duplicated dependencies declaration

- core/src/main/java/org/fao/geonet/api/records/attachments/CMISStore.java
- core/src/main/java/org/fao/geonet/resources/CMISConfiguration.java
- core/src/main/resources/config-store/config-cmis-overrides.properties
- core/src/main/resources/config-store/config-cmis.xml
- domain/src/main/java/org/fao/geonet/domain/MetadataResourceExternalManagementProperties.java
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/ogcwxs-info-injection.xsl
- web-ui/src/main/resources/catalog/components/filestore/partials/filestore.html
- web-ui/src/main/resources/catalog/components/usersearches/partials/portalswitcher.html
- web-ui/src/main/resources/catalog/style/gn.less
This feature is to support variety of status which is retrievable from the backend thru cmis and have the front end icon display accordingly.
I added the the property in the configuration and front end logic to parse the related icons. The implementation is just rough in for all other developers to detailed in their own system.
> Add validation status to cmis store and configuration

- web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
No tooltip available before so long description was not available to end user
> Record view / Files / Display full description in tooltip

- web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js
Without the change, clicking the button `Test mail configuration` in the `Settings` > `Feedback` section didn't show any feedback to the user when the mail was sent successfully.
With the change an alert info message is displayed:
To test:
1) Configure a mail server configuration in the settings
2) Save the configuration
3) Click the button `Test mail configuration`. If the mail configuration is correct, an info alert with the text `Mail sent to ....` should be displayed.
> Display successful test mail sent message

- web-ui/src/main/resources/catalog/components/catalog/CatalogService.js
A record may have no link defined.
> Record view / Link tables / Avoid errors on record with no links

- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid4maps.html
Use https://github.com/geonetwork/core-geonetwork/pull/6433 to easily get maps in home page (as in search results).
For test:
* sign in
* map
* save map as metadata record
* move to home page
* click the map
```
lib.js?v=d814a8f1ca72b1bba0068f1e19a916d05c913a14:133 TypeError: Cannot read properties of undefined (reading 'url')
at y (gn_search_default.js:107:124)
```
> Home / Map / Fix link adding the map to the map

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/utility-tpl.xsl
- schemas/iso19139/src/main/plugin/iso19139/layout/utility-tpl.xsl
Support protocol encoded using Anchor. Maybe related to INSPIRE encoding rules or to format encoding (see https://github.com/geonetwork/core-geonetwork/pull/6411). This configuration is used by the geopublication process mainly.
> Standard / Protocol extraction when using Anchor.

- web/src/main/webResources/WEB-INF/data/config/index/records.json
As we provide dynamic mapping on a number of fields, more than one match rule can match. 
In such case, the first one declared in schema takes priority (and could trigger Elasticsearch error eg. when object is provided and keyword is expected - if a thesaurus end up considered as an Org).
Move `*Org*` rule to the bottom. `th_*` is more specific and a thesaurus with `Org` in key should not be matched to an Org field.
> Index / Schema / First field match in mapping

- web-ui/src/main/resources/catalog/style/gn.less
This is based on previous pull request https://github.com/geonetwork/core-geonetwork/pull/4642
The side bar thickness is still very thin and not very user friendly 
It is currently set as 6px and looks like:
Here is what 12px looks like:
The 12px looks more like what typical web page scroll bar. For example, GitHub's
> Adjust side bar thickness to 12px

- core/src/main/java/org/fao/geonet/util/MailSender.java
- core/src/main/java/org/fao/geonet/util/MailUtil.java
To establish a SSL/TLS connection not vulnerable to man-in-the-middle attacks,
it’s essential to make sure the server presents the right certificate.
The certificate’s hostname-specific data should match the server hostname.
> Enable server hostname verification on this SSL/TLS connection.

- index/src/main/java/org/fao/geonet/index/es/EsRestClient.java
Fixes https://github.com/geonetwork/core-geonetwork/issues/6478
On client side, this is set here https://github.com/geonetwork/core-geonetwork/blob/main/web-ui/src/main/resources/catalog/components/elasticsearch/EsFacet.js#L319-L324
Probably in all places we have to track total hits for metadata record searches.
> Search / Track total hits

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/fromJsonLdEsri.xsl
This prevented harvested ESRI records from showing up in the search
> JSON Harvester / fix language in ESRI JSON transformation

- web-ui/src/main/resources/catalog/views/default/templates/recordView/featurecatalogue.html
Use the same layout for related metadata for feature catalog
For test, associate a feature catalogue to a record and open that record in view mode.
> Record view / Feature catalogue / Fix link to record

- pom.xml
- release/build.xml
- web/pom.xml
- web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v421/migrate-default.sql
`jetty:run` works fine, Deploy on Tomcat also but not deploy on Jetty which fails with:
```
java.lang.NoSuchMethodError: org.apache.logging.slf4j.Log4jLoggerFactory.<init>(Lorg/apache/logging/slf4j/Log4jMarkerFactory;)V
at org.apache.logging.slf4j.SLF4JServiceProvider.initialize(SLF4JServiceProvider.java:54)
at org.slf4j.LoggerFactory.bind(LoggerFactory.java:153)
at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:141)
at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:419)
at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:405)
at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:354)
at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:156)
at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory. …
```
> Deploy / On Jetty app fails to start due to logging

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/onlinesrcList.html
- web-ui/src/main/resources/catalog/style/gn.less
Due to dropdown li tag. This entry will always have a clickable mouse icon when hovering on it.
This change convert the tag from li to span to disable such behavior.
> change li to span tag

- csw-server/src/test/java/org/fao/geonet/component/csw/CswTransactionIntegrationTest.java
- web/src/main/webapp/xml/csw/filter-to-lucene.xsl
Otherwise the CSW query returns the approved metadata and it's working copy (for metadata that is approved and has a working copy).
Test case:
1) With the workflow disabled: create an iso19139 metadata with the default template, change the title only.
2) Query in the UI for ISO19115
http://localhost:8080/geonetwork/srv/eng/catalog.search#/search?resultType=details&sortBy=relevance&from=1&to=20&fast=index&_content_type=json&any=ISO19115
Lucene query generated:
```
+(_op0:0 _op0:-1 _op0:1 _op0:2 _owner:1 _dummy:0) +any:iso19115 +_isTemplate:n +(_draft:n _draft:e) _locale:eng
```
3) Query in CSW for ISO19115
http://localhost:8080/geonetwork/srv/eng/csw?request=GetRecords&service=CSW&version=2.0.2&resultType=results&constraintLanguage=CQL_TEXT&constraint_language_version=1.1.0&outputSchema=Iso …
> CSW queries should use the draft filter

- web-ui/src/main/resources/catalog/components/elasticsearch/directives/FacetDirective.js
- web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facet-cards.html
- web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facet.html
- web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facetDecorator.html
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/style/gn_search.less
- web-ui/src/main/resources/catalog/views/default/less/gn_topics_default.less
- web-ui/src/main/resources/catalog/views/default/templates/home.html
Currently only home page aggregations INSPIRE themes, ISO topics and resource type are illustrated with an icon. This PR makes it more generic so that we can configure the way we want to decorate an aggregation in the home page or in other pages.
A decorator can be used to add an icon or image next to an aggregation. The decorator is configured in the `meta` properties of the facet:
```js
"resourceType": {
"terms": {
"field": "resourceType",
"size": 10
},
"meta": {
"decorator": {
"type": "icon",
"prefix": "fa fa-2x pull-left gn-icon-"
}
}
```
Decorator types are:
* Fixed icon. eg. adding a tag icon to all values
```js
decorator: {
type: 'icon',
prefix: "fa fa-fw fa-tag "
}
```
* Icon defined in a CSS class name using the value. eg. used for resource types `gn-icon-dataset`
```js …
```
> Search / Aggregation / Add decorator

- services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
- services/src/main/java/org/fao/geonet/api/records/model/MetadataBatchSubmitParameter.java
- services/src/test/java/org/fao/geonet/api/records/MetadataWorkflowApiTest.java
- web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js
- web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionsDirective.js
- web-ui/src/main/resources/catalog/components/metadataactions/partials/batchsubmit.html
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/selection-widget.html
- web-ui/src/main/resources/catalog/js/edit/EditorBoardController.js
- web-ui/src/main/resources/catalog/locales/en-core.json
- web-ui/src/main/resources/catalog/locales/en-search.json
Analogue to https://github.com/geonetwork/core-geonetwork/pull/5430.
This feature allows users with `Editor`/`Reviewer` profiles to submit for review several metadata records at once from the `Editor board`,  when the metadata workflow is enabled.
A report with the summary of the results is displayed when the process is finished:
> Metadata workflow - Bulk metadata submit

- web-ui/src/main/resources/catalog/templates/admin/classification/thesaurus.html
#6543 reformatted the html, but the thesaurus admin page had the wrong structure, causing the output after reformatting to move the `div` containers for the page dialogs to the wrong position, which prevented the dialogs from being displayed.
> Fix add thesaurus dialogs - related to #6543 due to a previous wrong html structure in the thesaurus management page

- web-ui/src/main/resources/catalog/components/utility/UtilityService.js
- web-ui/src/main/resources/catalog/views/default/templates/recordView/summary.html
- web/src/main/webapp/xslt/common/index-utils.xsl
Do not use date format from config for year only.
If start = end, just display one element.
Better parsing of empty values while indexing.
> Record view / Date range / Display year only.

- web-ui/src/main/resources/catalog/views/default/less/gn_result_default.less
Issue was mainly on long resource identifier
Not sure about the need of the negative margin-left causing issue on Français on the screenshot below @MichelGabriel ?
After the change
> Record view / Break work on list of items

- web-ui/src/main/resources/catalog/components/catalog/CatalogService.js
Thanks @fxprunayre for pointing about the fix.
See https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group
> Change regular expression using lookbehind not supported in Safari browser

- core/src/main/java/org/geonetwork/http/SessionTimeoutCookieFilter.java
This was introduced in https://github.com/geonetwork/core-geonetwork/pull/6163 and prevents the UI code to display the warning message about session expiration.
> Remove HttpOnly for session timeout cookies, otherwise can't be processed in the UI code

- services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
- services/src/main/java/org/fao/geonet/api/records/model/MetadataPublicationNotificationInfo.java
- web-ui/src/main/resources/catalog/locales/en-admin.json
Metadata publication / unpublication, in batch publication mode send thee mail notifications in recordProfileReviewer level only to the metadata group owner reviewers instead of all reviewers
Related to #6457
Test case:
1) Login as admin user
2) In the Settings, configure the mail server
3) In the Settings, Configure the metadata privileges, configure the notification level to `Notify the reviewers part of the record group owner`
4) Create the groups: groupA / groupB
5) Create the users: reviewerA as reviewer in groupA / reviewerB as reviewer  in groupB, assigning a mail address
6) Create an iso19139 metadata in groupA
7) Create an iso19139 metadata in groupB
8) In the editor board select the 2 metadata and select `Publish`
**Expected:** a mail with the metadata in groupA publication is …
> Metadata publication / unpublication - fix mail notifications in recordProfileReviewer level

- web-ui/src/main/resources/catalog/style/gn_search.less
- web-ui/src/main/resources/catalog/views/default/less/gn_card_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_results_default.less
Replaces PR https://github.com/geonetwork/core-geonetwork/pull/6402
Tools menu was opening to right which resulted in the dropdown displayed partially outside of the screen. This PR opens the submenu to the left and adds some padding to the list items
**Before**
**After**
> Fix for the tools in the table search result opening to the right

- web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js
`$scope.user.isAdministratorOrMore()` sometimes returns an error `is not a function` while loading the settings.
It seems the code to load the settings is executed sometimes before the `$scope.user`  it is initialised.
Removed the check, if the user is not allowed, the API returns a 403 error.
Related to https://github.com/geonetwork/core-geonetwork/pull/6569
The backport of the previous PR to `3.12.x` includes already the change.
> Remove check of user profile in API requests. If not allowed will return a 403 error

- web-ui/src/main/resources/catalog/templates/admin/harvest/harvest-settings.html
This option is relevant only for 1 time harvesting, for example to import the metadata from an older catalogue. 
This change restricts it to the `Administrator` users.
> Harvesters - display the button to assign the harvested records to the local node only to 'Administrator' users

- services/src/main/resources/config-spring-geonetwork.xml
- web/src/main/webResources/WEB-INF/config-spring-geonetwork.xml
Currently the translations pack configuration is packaged in the `services` module jar. This makes difficult to override the configuration, for example when using custom UI views or for some schemas, like [HNAP](https://github.com/metadata101/iso19139.ca.HNAP) where the codelist keys differ from the standard iso19139 codelist keys.
In this PR, the configuration is moved to a plain text configuration file in  the `web` module.
In the `services` module there are other properties that can be suitable to change also, like:
https://github.com/geonetwork/core-geonetwork/blob/cd8b267c8f638fbfedbd3ccf8aa2f458bd59a159/services/src/main/resources/config-spring-geonetwork.xml#L54-L79
Other modules probably have similar properties.
> Move translation packs configuration to the web module

- schemas/iso19115-3.2018/src/main/java/org/fao/geonet/schema/iso19115_3_2018/ISO19115_3_2018SchemaPlugin.java
- schemas/iso19139/src/main/java/org/fao/geonet/schema/iso19139/ISO19139SchemaPlugin.java
Previously these values were set as `null`, displaying that text in the user interface.
For example, for a service referencing a remote dataset using `srv:operatesOn`, the dataset info was displayed like:
With the change, the following code works fine, displaying the url value:
https://github.com/geonetwork/core-geonetwork/blob/6e2f05ecc93f6c82a6f3ebb095ba33f45a304ef0/web-ui/src/main/resources/catalog/components/metadataactions/partials/metadataCard.html#L24
> Set title / url for associated resources to empty string if not defined

- web-ui/src/main/resources/catalog/templates/admin/admin.html
Fix duplicate quote causing a missing closing `div` element (see https://github.com/geonetwork/core-geonetwork/compare/main...GeoCat:core-geonetwork:fix-adminpagetemplate?expand=1#diff-b652c183f5bfce4e864a0d281b04c90eee40b95b481470a8a40e3a68e280c65fL52)
The error was before applying prettier (duplicated quote), but seem prettier removed the closing `div` due to this error:
`<div class="main"">`
> Fix wrong html in the admin page template

- web-ui/src/main/resources/catalog/components/metadataactions/RelatedDirective.js
Related to https://github.com/geonetwork/core-geonetwork/pull/6328
When no initiativeType was provided, related records were not displayed.
For testing:
* create a dataset
* associate record with no initiativeTypes
* check record view.
> Record view / Associated / Support empty initiativeType

- web-ui/src/main/resources/catalog/components/search/formfields/partials/sortByCombo.html
- web-ui/src/main/resources/catalog/components/search/pagination/partials/pagination.html
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/style/gn.less
- web-ui/src/main/resources/catalog/views/default/templates/results.html
* Do not display side column if no filter and no facet
* Do not display page combo, if no page options.
* Do not display full text field if not enable.
For example, creating a minimal app with the following config:
```json
{
"mods": {
"header": {
"enabled": false
},
"footer": {
"enabled": false
},
"search": {
"searchOptions": {
"fullText": false
},
"facetConfig": {},
"sortbyValues": [],
"resultViewTpls": [],
"isFilterTagsDisplayedInSearch": false,
"showBatchDropdown": false
}
}
}
```
to simply list results full screen:
> UI config / Properly hide empty options

- web-ui/src/main/resources/catalog/components/elasticsearch/EsService.js
Related to this change https://github.com/geonetwork/core-geonetwork/pull/6555
It seems `sortOrder` can be `undefined`, causing a Javascript error preventing to display the directory entries list.
To test:
1) Login as `Administrator` user.
2) Load the iso19139 templates
3) Go to `Contribute` > `Editor board` > `Manage directory`, select `Templates`
An spinning image is displayed instead of the templates and a javascript error is shown.
> Fix directory entries list

- web-ui/src/main/resources/catalog/components/elasticsearch/EsFacet.js
Clicking on a warning was not setting the filter properly.  Configure the field to use for the filter as we have here 2 facets on the same field but with 2 differents includes.
> Admin / Status / Fix facet config for warning

- web-ui/src/main/resources/catalog/style/gn_icons.less
* Make distinction between static/interactive map
* Add icon for publication
@MichelGabriel you can check this and don't hesitate to suggest better option for example "collectionSession" (which comes from a sample records that maybe we should remove to keep things simple).
> Resource type icons

- schemas/config-editor.xsd
- web/src/main/webapp/xslt/ui-metadata/menu-builder.xsl
Add option to hide tab if display condition does not match instead of only disabled it.
eg. content section hidden for service metadata record
```xml
<tab id="contentInfo"
displayIfRecord="not(mdb:MD_Metadata/mdb:identificationInfo/srv:SV_ServiceIdentification)"
hideIfNotDisplayed="true">
```
Co-authored-by: CMath04 <mathieu.chaussier@gim.be>
> Editor / Configuration / Hide tab if condition rule is false

- web-ui/src/main/resources/WEB-INF/classes/web-ui-wro-sources.xml
- web-ui/src/main/resources/catalog/components/viewer/gfi/FeaturesTable.js
- web-ui/src/main/resources/catalog/lib/bootstrap-table-angular.js
- web/src/main/webapp/xslt/base-layout-cssjs-loader.xsl
* Update bootstrap-table to `v1.21.1` from `v1.12`
* Since bootstrap-table-angular module has been removed in `v1.13.1` add the extension code to GN.
* `resetWidth` method has been deleted from bootstrap-table and have been merged into
`resetView` method (https://github.com/wenzhixin/bootstrap-table/pull/4687)
> Update bootstrap-table to v1.21.1

- services/src/main/java/org/fao/geonet/api/uisetting/UiSettingApi.java
- web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/templates/admin/settings/ui.html
This pull request updates the UI settings management for users with `UserAdmin` profile. Currently users with the profile `UserAdmin` can delete *any* UI configuration.
This change disables the delete for button in the UI for the default UI `srv`.
Also updates the backend code to delete UI, so `UserAdmin` users can only delete UI's related to portals associated to their groups.
An improvement for another pull request, would be to disable also the button in the UI settings configuration in these cases.
> Update UI settings management for UserAdmin users 

- web/src/main/webapp/WEB-INF/classes/log4j2-dev.xml
- web/src/main/webapp/WEB-INF/classes/log4j2.xml
```
2022-10-26 15:28:35,416 main ERROR FileManager (./logs/${ctx:logfile}) java.io.IOException: The filename, directory name, or volume label syntax is incorrect java.io.IOException: The filename, directory name, or volume label syntax is incorrect
at java.io.WinNTFileSystem.canonicalize0(Native Method)
at java.io.WinNTFileSystem.canonicalize(WinNTFileSystem.java:485)
at java.io.File.getCanonicalPath(File.java:626)    
```
Add a default value when the context does not set the variable.
Before
After an harvester-default.log is created instead.
> Logging / Avoid exception on windows

- services/src/main/java/org/fao/geonet/api/records/MetadataUtils.java
Currently, if a metadata has a working copy, it's displayed twice in the relations panel, one for the approved copy and another for the working copy:
This change filters the metadata to display these records once.
> Update metadata relation queries with the workflow filters

- schemas/config-editor.xsd
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout.xsl
- schemas/iso19139/src/main/plugin/iso19139/layout/layout.xsl
- web/src/main/webapp/xslt/common/functions-metadata.xsl
Related to https://github.com/geonetwork/core-geonetwork/pull/4343
Flat mode exceptions are used in view guided by the XML document (not the XSD). It allows to display + action to create non mandatory elements.
If an element have the same name in various places in the model, use includeFrom and excludeFrom attribute to only enable + on those elements.
eg.
* Allow adding description in resource identifier only (not in CRS identifier)
* Allow adding contact everywhere but not in maintenance section.
```xml
<for name="mcc:description"
includeFrom="/mdb:MD_Metadata/mdb:identificationInfo/mri:MD_DataIdentification/mri:citation/cit:CI_Citation/cit:identifier/mcc:MD_Identifier"/>
<for name="gmd:contact"
excludeFrom="gmd:MD_MaintenanceInformation"/>
```
Also add support to select by XPath and not …
> Editor / Configuration / Allow to include elements from flatModeExceptions

- schemas/config-editor.xsd
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/config-editor.xml
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout-custom-fields.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout.xsl
- schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
- schemas/iso19139/src/main/plugin/iso19139/layout/layout.xsl
- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
- web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
- web/src/main/webapp/xslt/ui-metadata/form-configurator.xsl
eg. in simple view,
* do not allow collapsing main section ie. identification and content info
* collapse the metadata section by default which contains advanced element (probably not modified compared to the template values).
```xml
<tab id="default" default="true" mode="flat">
<section xpath="/mdb:MD_Metadata/mdb:identificationInfo" collapsible="false"/>
<section xpath="/mdb:MD_Metadata/mdb:contentInfo" collapsible="false"/>
<section name="metadata" collapsed="true">
```
Collapsing all sections, also collapse inner section and take into account collapsed states.
```xml
<section name="metadata" collapsed="true">
<text>
<div class="row">
<div class="col-sm-12">
<div class="alert alert-info">Describe here whatever you want</div>
</div>
</div>
</text>
```
To simplify editor configuration in …
> Editor configuration improvements

- web-ui/src/main/resources/WEB-INF/classes/web-ui-wro-sources.xml
- web-ui/src/main/resources/catalog/components/viewer/gfi/FeaturesTable.js
- web-ui/src/main/resources/catalog/lib/bootstrap-table-angular.js
- web/src/main/webapp/xslt/base-layout-cssjs-loader.xsl
* Update bootstrap-table to v1.21.1
* Since bootstrap-table-angular module has been removed in v1.13.1 add the code to GN.
* `resetWidth` method has been deleted from bootstrap-table and have been merged into `resetView` method (https://github.com/wenzhixin/bootstrap-table/pull/4687)
> [BP] Update bootstrap-table to v1.21.1 (#6628)

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/present/metadata-rdf.xsl
- schemas/iso19139/src/main/plugin/iso19139/layout/tpl-rdf.xsl
- schemas/iso19139/src/main/plugin/iso19139/present/metadata-rdf.xsl
Uploaded thumbnail files to GeoNetwork can contain spaces in the file names. This changes encodes the spaces in the `foam:thumbnail` elements of the metadata RDF export.
Additionally the geometry element has been updated from :
```
<dct:spatial xmlns:dct="http://purl.org/dc/terms/">
<ogc:Polygon xmlns:ogc="http://www.opengis.net/rdf#">
<ogc:asWKT rdf:datatype="http://www.opengis.net/rdf#WKTLiteral">
<http://www.opengis.net/def/crs/OGC/1.3/CRS84>
Polygon((3.254 50.735, 3.254 53.561, 7.244 53.561, 7.244 50.735, 3.254 50.735))
</ogc:asWKT>
</ogc:Polygon>
</dct:spatial>
```
to
```
<dct:spatial xmlns:dct="http://purl.org/dc/terms/">
<ogc:Polygon xmlns:ogc="http://www.opengis.net/rdf#">
<geo:asWKT rdf:datatype="http://www.opengis.net/rdf#wktLiteral">
Polygon((3.254 50.735, 3.254 53.561, 7.244 …
```
> RDF export: Encode spaces in foaf:thumbnail urls and update geometry field

- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
Related https://github.com/geonetwork/core-geonetwork/pull/6629
It does not apply to formatter which is not collapsible. Set default values.
Avoid error
```
Error at xsl:param on line 549 of render-layout.xsl:
XTDE0610: A value must be supplied for the parameter because the default value is not a
valid instance of the required type
```
> Formatter / Set default value for collapsed state

- services/src/main/java/org/fao/geonet/api/records/MetadataApi.java
The metadata API request to retrieve the attributes from a linked feature catalog metadata returns an error due to a wrong parameter value to retrieve the related resources.
http://localhost:8080/geonetwork/srv/api/records/09d1f035-d8e0-410d-a6b6-5fdac3496021/featureCatalog?_content_type=json
```
2022-10-07 07:27:45,888 ERROR [geonetwork.api] - Failed: Not enough search results (0) available to meet request for 2.
java.lang.Exception: Failed: Not enough search results (0) available to meet request for 2.
at org.fao.geonet.kernel.search.LuceneSearcher.present(LuceneSearcher.java:1259)
at org.fao.geonet.api.records.MetadataUtils.search(MetadataUtils.java:423)
at org.fao.geonet.api.records.MetadataUtils.search(MetadataUtils.java:369)
at …
```
> Fix retrieve related resources in metadata API request to retrieve the attributes from a linked feature catalog metadata

- web-ui/src/main/resources/catalog/js/admin/MapServerController.js
- web-ui/src/main/resources/catalog/js/admin/MetadataIdentifierTemplatesController.js
- web-ui/src/main/resources/catalog/js/admin/SourcesController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/style/gn_admin.less
- web-ui/src/main/resources/catalog/templates/admin/metadata/metadata-identifier-templates.html
- web-ui/src/main/resources/catalog/templates/admin/settings/mapservers.html
- web-ui/src/main/resources/catalog/templates/admin/settings/sources.html
Delete map server, sources and metadata template identifiers actions were not requesting confirmation, updated to display a confirmation dialog.
Also sources and metadata template identifiers pages were displaying the `Delete` button when creating a new source.
Fixed sources page logic:
- Cleanup the form when a source is deleted.
- Make identifier and name mandatory.
- Don't allow to change the identifier when editing a source, as it's used as the internal key.
> Map servers / sources / metadata template identifiers - delete confirmation dialog and fixes in display delete button in sources page

- web-ui/src/main/resources/WEB-INF/classes/web-ui-wro-sources.xml
Related to https://github.com/geonetwork/core-geonetwork/pull/4576
Error reported
```
TypeError: Cannot read properties of undefined (reading 'guess')
```
> JS / Moment / Timezone lib missing when 3D mode enabled

- web-ui/src/main/resources/WEB-INF/classes/web-ui-wro-sources.xml
In `3.12.x`, enabling the 3d mode in the UI settings:
, the following error happens, preventing to load the application:
```
Uncaught TypeError: Class constructors cannot be invoked without 'new'
at lib3d.js?v=ff01ad3afbd8bf0fe6cbc0f240246ff6ec82705f:7920:1
lib3d.js?v=ff01ad3afbd8bf0fe6cbc0f240246ff6ec82705f:3888 Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.5.2/$injector/modulerr?p0=gn_search_dutch&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.5.2%2F%24injector%2Fmodulerr%3Fp0%3Dgn_search%26p1%3DError%253A%2520%255B%2524injector%253Amodulerr%255D%2520http%253A%252F%252Ferrors.angularjs.org%252F1.5.2%252F%2524injector%252Fmodulerr%253Fp0%253Dgn_mdview%2526p1%253DError%25253A%252520%25255B%25252
```
In the application log:
```
Oct …
```
> Add bootstrap-table-export to wro lib module and fix file path in lib3d to use the file in dist folder

- web-ui/src/main/resources/WEB-INF/classes/web-ui-wro-sources.xml
- web-ui/src/main/resources/catalog/components/viewer/gfi/FeaturesTable.js
Backport of https://github.com/geonetwork/core-geonetwork/pull/6657
In `3.12.x` this change is not required: https://github.com/geonetwork/core-geonetwork/pull/6657/files#diff-59b6828a9edbc4aa28dd85b9a3b4210eb04fa85f31a6572ca44cf99e5fe2b677
Fixed also the download icon (not related to the the upgrade of boostrap-table, the issue existed previously).
Previously:
After:
> [BP] Fix boostrap-table styling

- web/src/test/resources/org/fao/geonet/kernel/schema/inspire-valid-iso19139.xml
Update the URLs causing the test to fail. Using https on the original URLs didn't work, it seems some issues with the certificate.
> Fix schematron unit test

- web-ui/src/main/resources/WEB-INF/classes/web-ui-wro-sources.xml
- web-ui/src/main/resources/catalog/style/gn_viewer.less
Related to https://github.com/geonetwork/core-geonetwork/pull/6628
This pull request contains 2 changes:
1. Update the wro configuration to process only the main styling file for `bootstrap-table`, see additional information in https://github.com/geonetwork/core-geonetwork/pull/6656#issuecomment-1307149067
2. Remove a styling causing a wrong rendering of the table with the updated version.
Previously:
Test case:
1) Load the iso19139 samples
2) With the admin user in the `Hydrological Basins in Africa` select the option to index the data features 
Check the features table layout.
> Fix boostrap-table styling

- web-ui/src/main/resources/catalog/components/edit/directoryentryselector/DirectoryEntrySelector.js
- web-ui/src/main/resources/catalog/components/elasticsearch/EsFacet.js
Fix the option to only display valid subtemplates in the editor entry selector.
- only search for valid metadata if set (`showValidOnly`)
- fix the display in the list with the correct icon and color
> Fix showValidOnly option in editor entry selector

- web-ui/src/main/resources/catalog/components/edit/FieldsDirective.js
Related to #6627
The upgrade of boostrap, includes this change, that is causing that the close button in the popup, as it's not part of the allowed elements (https://getbootstrap.com/docs/3.4/javascript/#js-sanitizer):
* Fixed a XSS vulnerability (CVE-2019-8331) in our tooltip and popover plugins by implementing a new HTML sanitizer
Previously:
After:
This pull request changes the element from a `button` to an `a` element and adds dynamically the click event to handle the closing of the tooltip, readding again the button:
> Fix close button in the metadata editor tooltips. 

- web-ui/src/main/resources/catalog/components/search/formfields/FormFieldsDirective.js
The `schemaInfoCombo` directive is used in the online resources dialog to display the protocols. It displays the protocols defined in a metadata schema and if the metadata has distribution formats are listed also, adding a header to distinguish the values:
These header values are displayed even if the metadata has no distribution formats or a schema disables that option. With this change in this case, no header entries are displayed:
> Update schemaInfoCombo to only display the section headers if a list of extra options is provided

- core/src/main/java/org/fao/geonet/api/tools/i18n/TranslationPackBuilder.java
- core/src/main/java/org/fao/geonet/kernel/EditLib.java
- core/src/main/java/org/fao/geonet/kernel/mef/MEFLib.java
- core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
- core/src/main/java/org/fao/geonet/kernel/setting/HarvesterSettingsManager.java
- core/src/main/java/org/fao/geonet/util/xml/NamespaceUtils.java
- core/src/main/java/org/geonetwork/map/wms/SLDUtil.java
- core/src/test/java/org/geonetwork/map/wms/SLDUtilTest.java
- csw-server/src/main/java/org/fao/geonet/component/csw/CatalogDispatcher.java
- csw-server/src/main/java/org/fao/geonet/component/csw/DescribeRecord.java
- csw-server/src/main/java/org/fao/geonet/component/csw/GetCapabilities.java
- csw-server/src/main/java/org/fao/geonet/kernel/csw/CatalogConfiguration.java
- csw-server/src/main/java/org/fao/geonet/kernel/csw/CatalogConfigurationGetRecordsField.java
- csw-server/src/main/java/org/fao/geonet/kernel/csw/services/AbstractOperation.java
- csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/FieldMapper.java
- estest/src/test/java/org/fao/geonet/index/es/IndexationTest.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java
- services/src/main/java/org/fao/geonet/api/records/MetadataSavedQueryApi.java
- services/src/main/java/org/fao/geonet/api/records/MetadataUtils.java
- services/src/main/java/org/fao/geonet/api/records/formatters/groovy/util/Summary.java
- services/src/main/java/org/fao/geonet/api/sld/SldApi.java
- workers/camelPeriodicProducer/src/main/java/org/fao/geonet/camelPeriodicProducer/MessageProducerService.java
This pr replaces the Map usages by using the interface instead of concrete implementations like HashMap. This improves the flexibility and interchangeability of the code base and reduces the dependencies of implementations.
> Use Map interface instead of implementations

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout-custom-fields-keywords.xsl
- schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields-keywords.xsl
Currently, if a record contains an empty keyword in a thesaurus block, the picker does not initialized properly.
For test, create a thesaurus block with one keyword set and an empty one
```xml
<mri:keyword>
<gco:CharacterString>Energy</gco:CharacterString>
</mri:keyword>
<mri:keyword>
<gco:CharacterString></gco:CharacterString>
</mri:keyword>
```
This should not happen when using the editor, but when importing records (or running SQL update) we could end up with this.
> Editor / ISO / Empty keywords are ignored for picker config.

- core/src/main/java/org/fao/geonet/kernel/mef/Importer.java
Before, no information provided on which records have error in the MEF so hard to find it.
After, report the UUID
Can happen when MEF file does not contains metadata.xml file or when the file content is not supported by current catalogue (eg. custom subtemplate)
> MEF Import / Add UUID reference when error happens loading file

- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v402/migrate-default.sql
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v406/migrate-default.sql
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v407/migrate-default.sql
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v421/migrate-default.sql
Tested this type of queries:
```
INSERT INTO Settings (name, value, datatype, position, internal) 
SELECT distinct 'system/inspire/remotevalidation/apikey', '', 0, 7213, 'y' from Settings 
WHERE NOT EXISTS (SELECT name FROM Settings WHERE name = 'system/inspire/remotevalidation/apikey');
```
- Postgres: Ok
- MySql: Ok (tested the `INSERT` in mysql console, as trying to startup the application I got some issues trying to override the parameter `lower-case-table-names ` in the Docker container)
- H2: Ok
> Migration - don't add settings backported to 3.12.x when migrating from a 3.12.x version

- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v400/UpdateAllSequenceValueToMax.java
Optimisation related to https://github.com/geonetwork/core-geonetwork/pull/5003 for Postgres
The current migration is very slow with large databases (hours). Using `setval` works in Postgres and it's almost inmediate.
> Optimise UpdateAllSequenceValueToMax when using a Postgres database

- web-ui/src/main/resources/catalog/templates/admin/classification/thesaurus.html
It was like
Center and space below added.
> Admin / Thesaurus / Fix layout of pagination

- web-ui/src/main/resources/catalog/components/admin/uiconfig/UiConfigDirective.js
- web-ui/src/main/resources/catalog/js/CatController.js
When choosing an option to customize, add it to the form and unselect it from the list. 
If the user swith to the JSON form and come back, he will have the possibility to add it back (without reloading the page or selecting another one).
Also fix JS error, if user set config to 
```json
{
"mods": {}
}
```
> UI Settings / Unselect added option once added to the form

- schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
Some metadata schemas based on ISO19139 store the date type with the value in the attribute `codeListValue` and also as a text, for example, see `creatie` in the following snippet:
```
<gmd:date>
<gmd:CI_Date>
<gmd:date>
<gco:Date>2022-06-15</gco:Date>
</gmd:date>
<gmd:dateType>
<gmd:CI_DateTypeCode codeList="https://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode" 
codeListValue="creation">creatie</gmd:CI_DateTypeCode>
</gmd:dateType>
</gmd:CI_Date>
</gmd:date>
```
The current code was not processing properly the dates, causing in the Admin console > status panel some error entries like the following, with valid dates:
```
Warning / Date creation with value '2022-06-15' was not a valid date format.
```
> ISO19139 - Fix indexing of dates when the date element contains the date type as a text value

- core/src/main/java/org/fao/geonet/kernel/security/openidconnect/GeonetworkOAuth2LoginAuthenticationFilter.java
- core/src/main/java/org/fao/geonet/kernel/security/openidconnect/LoggingOidcAuthorizationCodeAuthenticationProvider.java
- core/src/main/java/org/fao/geonet/kernel/security/openidconnect/OAuth2SecurityProviderUtil.java
- core/src/main/java/org/fao/geonet/kernel/security/openidconnect/OIDCConfiguration.java
- core/src/main/java/org/fao/geonet/kernel/security/openidconnect/OidcUser2GeonetworkUser.java
- core/src/main/java/org/fao/geonet/kernel/security/openidconnect/SimpleOidcUser.java
- core/src/main/java/org/fao/geonet/kernel/security/openidconnect/SimpleOidcUserFactory.java
- core/src/test/java/org/fao/geonet/kernel/security/openidconnect/SimpleOidcUserFactoryTest.java
This PR has two minor items - both to do with the OIDC (oauth2 -  open id connect) login;
1. I added a bit more logging for the OIDC configuration (only shown when `OPENIDCONNECT_LOGSENSITIVE_INFO` is `true`). This is helpful for debugging issues and to verify the configuration when troubleshooting.
2. I added better support for updating some of the user information (most notably first and last name) based on the `USERINFO` map (and not just the ID Token). This is more robust since many systems do not put the first/last name in the ID Token (only in the `userinfo` endpoint map).
> OIDC: added logging and better user updating

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/config-editor.xml
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
- web-ui/src/main/resources/catalog/components/search/mdview/mdviewModule.js
- web-ui/src/main/resources/catalog/locales/en-v4.json
- web-ui/src/main/resources/catalog/style/gn_metadata.less
- web-ui/src/main/resources/catalog/views/default/directives/partials/attributetable.html
- web-ui/src/main/resources/catalog/views/default/templates/recordView/featurecatalogue.html
- web-ui/src/main/resources/catalog/views/default/templates/recordView/type-dataset.html
- web-ui/src/main/resources/catalog/views/default/templates/recordView/type-series.html
The metadata page for a feature catalog can be long and contain many tables. This PR adds a table of contents in order to jump to the table of interest.
**Table closed**
**Table open**
> Table of Contents for the Feature Catalog page

- web-ui/src/main/resources/catalog/components/edit/multientrycombiner/partials/multientrycombiner_onlineresourcesdescription.html
We need configuration to the numberOfSuggestions to control the popup numbers of this field in online resource window.
The configuration for example can be passed from
https://github.com/metadata101/iso19139.ca.HNAP/blob/3b4137b971142bd133040a2e6b36c20595bc6671/src/main/plugin/iso19139.ca.HNAP/config/associated-panel/default.json#L44-L49
From the screenshot above, i changed the format and numberOfSuggestions.
The numberOfSuggestions is missing from this UI component which wont take this configuration. So this PR is to add such configuration.
**Also if anyone can give me direction if we can have an option to show "ALL" and which UI component/Javascript to look into**?
> add numberofsuggestions to multientrycombiner_onlineresourcesdescription

- core/src/main/java/org/fao/geonet/kernel/ThesaurusManager.java
- core/src/main/java/org/fao/geonet/util/XslUtil.java
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
- schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
Some records may not encode thesaurus identifier like in
```xml
<gmd:thesaurusName>
<gmd:CI_Citation>
<gmd:title>
<gmx:Anchor xlink:href="http://inspire.ec.europa.eu/theme">GEMET - INSPIRE themes, version 1.0</gmx:Anchor>
</gmd:title>
<gmd:date>
<gmd:CI_Date>
<gmd:date>
<gco:Date>2008-06-01</gco:Date>
</gmd:date>
<gmd:dateType>
<gmd:CI_DateTypeCode codeListValue="publication"
codeList="https://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode"/>
</gmd:dateType>
</gmd:CI_Date>
</gmd:date>
</gmd:CI_Citation>
</gmd:thesaurusName>
```
In this case, the thesaurus field name is based on the title even if the thesaurus is loaded in the catalogue. Add a check to retrieve thesaurus identifier from the thesaurus title to build consistent field name whatever the encoding is. …
> Indexing / Thesaurus field name if no thesaurus identifier

- web-ui/src/main/resources/catalog/js/edit/NewMetadataController.js
Currently the new metadata page displays a label **N/A** for templates that have no resource type value.
With the change a label **Other** is displayed, similar to `3.12.x` version.
> New metadata - improve the metadata template type display label when the template has no resource type defined

- core/src/main/java/org/fao/geonet/resources/CMISConfiguration.java
Add option to parse secondary properties names for (CmisMetadataUUIDPropertyName ExternalResourceManagementValidationStatusPropertyName) from a more human readable name
> Add option to parse secondary properties names from a more human readable name

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/datacite/view.xsl
On Datacite formatter http://localhost:8080/geonetwork/srv/api/records/ce6234fe-783b-405d-ad2e-c65a32f06fc8/formatters/datacite?output=xml
Error reported:
```
Error at xsl:value-of on line 165 column 43 of view.xsl:
XPST0003: XPath syntax error at char 1 on line 165 in {$$doiId}:
expected "<name>", found "$"
```
Related to https://github.com/geonetwork/core-geonetwork/pull/6347
> Formatter / ISO19115-3 / DOI / Fix invalid variable name

- csw-server/src/main/java/org/fao/geonet/kernel/csw/CatalogConfiguration.java
- csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/SortByParser.java
- csw-server/src/test/java/org/fao/geonet/kernel/csw/services/getrecords/es/CswFilter2EsTestConfiguration.java
- csw-server/src/test/java/org/fao/geonet/kernel/csw/services/getrecords/es/CswSortBy2EsTest.java
- web/src/main/webapp/WEB-INF/config-csw.xml
Add the possibility to configure the default sort option (ie. score) for GetRecords operation.
This can help solving issue when the catalogue is harvested with no sort order defined and record which may appear multiple times on various pages (due to index changes occuring during indexing).
Related to https://github.com/geonetwork/core-geonetwork/pull/6223
> CSW / GetRecords / Add default sort configuration.

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
Indexing was failing when more than one default language was defined for the resource
Error reported:
```
Error on line 395 of index.xsl:
XTTE0790: A sequence of more than one item is not allowed as the second argument of
gn-fn-index:add-codelist-field() (<lan:MD_CharacterSetCode/>, <lan:MD_CharacterSetCode/>) 
```
eg. when importing https://sextant.ifremer.fr/Donnees/Catalogue#/metadata/ff8d8cd6-c753-4581-99a3-af23fe4c996b and converting it to ISO19115-3.
> Standard / ISO19115-3 / Index properly multiple characterSet

- schemas/dublin-core/src/main/plugin/dublin-core/formatter/citation/base.xsl
- schemas/dublin-core/src/main/plugin/dublin-core/formatter/citation/view.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/citation/base.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/citation/common.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/citation/view.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/eng/strings.xml
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/fre/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/formatter/citation/base.xsl
- schemas/iso19139/src/main/plugin/iso19139/formatter/citation/view.xsl
- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
- schemas/iso19139/src/main/plugin/iso19139/loc/eng/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/fre/strings.xml
Follow up of https://github.com/titellus/core-geonetwork/pull/41
The main goal here is to be able to add citation in other pages eg.
landing page. The citation formatter is reworked so that it can be
imported and used (like JSON-LD formatter).
eg.
```xsl
<xsl:include href="../../formatter/citation/base.xsl"/>
<xsl:include href="../../../iso19115-3.2018/formatter/citation/common.xsl"/>
<xsl:variable name="citationInfo">
<xsl:call-template name="get-iso19139-citation">
<xsl:with-param name="metadata" select="$metadata"/>
<xsl:with-param name="language" select="$language"/>
</xsl:call-template>
</xsl:variable>
<xsl:apply-templates mode="citation" select="$citationInfo"/>
```
Also add the possibility to have an additional citation in the HTML
format. The additional citation is stored in the …
> Citation / Refactor to be able to use it in other XSLT

- core/src/main/java/org/fao/geonet/api/records/attachments/CMISStore.java
- core/src/main/java/org/fao/geonet/resources/CMISResources.java
- core/src/main/java/org/fao/geonet/resources/CMISUtils.java
Updated folder cache logic to improve performance - there were some areas that were not using the folder cache and can to make things faster.
Using subFolder.createFolder instead of createPath seems seems faster.
Don't always create missing folders when looking up the cache in some cases it is ok to generate a resource not found error.
Also fixed some unhandled errors from the cache system
> Updated folder cache logic to improve performance

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
When creating an iso19139 metadata the following error is logged. 
```
angular.js?v=8c345ce00e4a76478767ac2d698810682180b3c3:14199 TypeError: Cannot read properties of null (reading 'filter')
at OnlineSrcDirective.js:82:47
at processQueue (angular.js?v=8c345ce00e4a76478767ac2d698810682180b3c3:16696:28)
at angular.js?v=8c345ce00e4a76478767ac2d698810682180b3c3:16712:27
at Scope.$eval (angular.js?v=8c345ce00e4a76478767ac2d698810682180b3c3:17994:28)
at Scope.$digest (angular.js?v=8c345ce00e4a76478767ac2d698810682180b3c3:17808:31)
at Scope.$apply (angular.js?v=8c345ce00e4a76478767ac2d698810682180b3c3:18102:24)
at done (angular.js?v=8c345ce00e4a76478767ac2d698810682180b3c3:12082:47)
at completeRequest (angular.js?v=8c345ce00e4a76478767ac2d698810682180b3c3:12291:7)
at …
```
> Fix JS error when the relations for a metadata return null when no relations of a type exists

- services/src/main/java/org/fao/geonet/api/records/MetadataUtils.java
Avoid to display "null" as title.
eg. when a relation is set with the following encoding
```xml
<gmd:aggregationInfo>
<gmd:MD_AggregateInformation>
<gmd:aggregateDataSetIdentifier>
<gmd:MD_Identifier>
<gmd:code>
<gmx:Anchor xlink:href="http://www.eea.europa.eu/publications/trends-and-projections-in-the">http://www.eea.europa.eu/publications/trends-and-projections-in-the</gmx:Anchor>
</gmd:code>
</gmd:MD_Identifier>
</gmd:aggregateDataSetIdentifier>
<gmd:associationType>
<gmd:DS_AssociationTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#DS_AssociationTypeCode" codeListValue="crossReference"/>
</gmd:associationType>
</gmd:MD_AggregateInformation>
</gmd:aggregationInfo>
```
Use the link as title instead.
Before
After
> Record view / Associated resources / Remote records may have null as title
