geonetwork/core-geonetwork

- SECURITY.md
Feedback based on developer list dicsussion.
> Revise security policy with public forum examples of email list and issue tracker

- web-ui/src/main/resources/catalog/components/history/partials/historyStep.html
> History / Display close task only when it applies

- services/src/main/java/org/fao/geonet/api/records/CatalogApi.java
Fix
```xml
<description>java.util.HashMap cannot be cast to java.lang.String</description>
```
> Selection / PDF / Fix errors due to index schema changes

- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid.html
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/list.html
> Search results - metadata with a working copy display a label 'Working copy' if the metadata has a draft copy, even for public users.

- web-ui/src/main/resources/catalog/components/viewer/searchlayerformap/SearchLayerForMapDirective.js
Similar to https://github.com/geonetwork/core-geonetwork/pull/5611
> Map / Apply filter to layer search

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
* Remove extra `request=` parameters
* Use the configuration from the settings
> Fix Thumbnail generator

- core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
- schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
Same as https://github.com/geonetwork/core-geonetwork/pull/5699
Also fix link indexing.
> Index / Avoid error on multiple results in DQ conformance.

- docs/changes3.10.0-0.txt
- docs/changes3.10.1-0.txt
- docs/changes3.10.2-0.txt
- docs/changes3.10.3-0.txt
- docs/changes3.10.4-0.txt
- docs/changes3.10.5-0.txt
- docs/changes3.10.6-0.txt
- docs/changes3.12.0-0.txt
- docs/changes3.6.0-0.txt
- docs/changes3.8.0-0.txt
- docs/changes3.8.1-0.txt
- docs/changes3.8.2-0.txt
- docs/changes3.8.3-0.txt
Fix for issue #5622
Add changes logs from other release so that we can see the full history.
> Add missing change logs for past releases.

- schemas/iso19139/src/main/plugin/iso19139/index-fields/default.xsl
problem occurs if record both has a title as well as identifier has a citation with title
> fix duplicate string in normalize-space 

- schemas/iso19139/src/main/plugin/iso19139/formatter/jsonld/iso19139-to-jsonld.xsl
- schemas/iso19139/src/main/plugin/iso19139/formatter/jsonld/view.xsl
- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
This makes life easier for plugin extending iso19139.
Also fix issue introduced in https://github.com/geonetwork/core-geonetwork/commit/528a0732ac28f456ce996c8e55ad034e529bfb5b."
> ISO19139 / Formatter / Support isoType in template match for plugins

- web-ui/src/main/resources/catalog/js/admin/DashboardStatusController.js
> Admin / Status / Fix facet more

- web-ui/src/main/resources/catalog/components/viewer/wmsimport/WmsImportDirective.js
The list of services was not taking care of the UI configuration filter.
> Map / Service list / Add UI configuration filter if any

- csw-server/src/main/java/org/fao/geonet/component/csw/GetRecords.java
Sample query http://localhost:8080/geonetwork/srv/deu/csw?maxRecords=1000&startPosition=1&request=GetRecords&service=CSW&version=2.0.2&resultType=results&namespace=xmlns(csw=http://www.opengis.net/cat/csw/2.0.2)&typeNames=csw:Record&constraintLanguage=FILTER&constraint_language_version=1.0.0&elementSetName=full&sortBy=title:A&constraint=%3Cogc:Filter%20xmlns:ogc=%22http://www.opengis.net/ogc%22%3E%3Cogc:PropertyIsEqualTo%3E%3Cogc:PropertyName%3EgroupOwner%3C/ogc:PropertyName%3E%3Cogc:Literal%3E5%3C/ogc:Literal%3E%3C/ogc:PropertyIsEqualTo%3E%3C/ogc:Filter%3E&sortBy=title:D
> CSW / Restore possibility to store by any index fields

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/update-fixed-info.xsl
- schemas/iso19139/src/main/plugin/iso19139/update-fixed-info.xsl
> GML / Add required id attribute to TimePeriod

- web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html
> Fix related to #5804: replace ng-if with ng-show, as ng-if creates a child scope that causes a side effect with ngSearchForm directive. 

- web-ui/src/main/resources/catalog/locales/en-v4.json
To avoid "code postal" in French
FacetTranslator search for
* facetKey-facetValue first eg. format-zip
* facetValue eg. zip
* and if not translation found, fallback to value.
> Facet / Translation / Distinction between zip code and ZIP format

- csw-server/src/main/java/org/fao/geonet/component/csw/Transaction.java
- web-ui/src/main/resources/catalog/style/gn_metadata.less
* https://github.com/geonetwork/core-geonetwork/issues/4156
* https://github.com/geonetwork/core-geonetwork/pull/5879
> 3.12.x cherry pick for 4.0.6

- schemas/iso19139/src/main/plugin/iso19139/layout/layout.xsl
- web-ui/src/main/resources/catalog/components/edit/topiccategory/TopicCategoryDirective.js
- web-ui/src/main/resources/catalog/components/edit/topiccategory/TopicCategoryService.js
Schema plugin may be extending topic category list. Load proper codelist based on current editing session
> Editor / ISO topic category / Return list corresponding to schema plugins.

- services/src/main/java/org/fao/geonet/api/records/CatalogApi.java
- web/src/main/webapp/xslt/base-layout-cssjs-loader.xsl
- web/src/main/webapp/xslt/services/pdf/metadata-fop.xsl
> Search results / PDF / Missing title in TOC

- web-ui/src/main/resources/catalog/views/default/templates/recordView.html
Related to index change for multilingual support.
> Record view / Fix display of topic category.

- web-ui/src/main/resources/catalog/components/search/mdview/mdviewDirective.js
- web-ui/src/main/resources/catalog/components/search/mdview/mdviewModule.js
- web-ui/src/main/resources/catalog/components/search/mdview/mdviewService.js
- web-ui/src/main/resources/catalog/components/utility/UtilityService.js
Also refactor getFormatterForRecord and add support to get property by path eg. standardName.default.
> Record view / Preserve debug mode in links

- services/src/main/java/org/fao/geonet/api/reports/ReportDownloads.java
- services/src/main/java/org/fao/geonet/api/reports/ReportInternalMetadata.java
- services/src/main/java/org/fao/geonet/api/reports/ReportUpdatedMetadata.java
- services/src/main/java/org/fao/geonet/api/reports/ReportUploads.java
- services/src/main/java/org/fao/geonet/api/reports/ReportUsers.java
- services/src/main/java/org/fao/geonet/api/reports/ReportUtils.java
Use a constant for all CSV admin export. Add quotes like in records CSV exports.
> Admin / Reports / Consistent CSV format with other exports.

- schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
Similar to https://github.com/geonetwork/core-geonetwork/pull/5883
> ISO19139 / CRS indexing fails on multilingual records

- web-ui/src/main/resources/catalog/components/search/searchfiltertag/SearchFilterTagsDirective.js
- web-ui/src/main/resources/catalog/components/search/searchfiltertag/partials/searchFilterTagsTemplate.html
- web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js
- web-ui/src/main/resources/catalog/locales/en-v4.json
* Render range based on timezone configuration (instead of the lucene
expression) - it was odd to have always Zulu time
is now
* Fix removal of range
* When active display a proper label
is now
* Fix removal of geometry filter
> Search / Active filter / Misc improvements.

- web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js
- web-ui/src/main/resources/catalog/components/search/searchoptions/SearchOptionsDirective.js
- web-ui/src/main/resources/catalog/components/search/searchoptions/partials/searchoptions.html
- web-ui/src/main/resources/catalog/components/usersearches/UserSearchesDirective.js
- web-ui/src/main/resources/catalog/components/usersearches/partials/usersearchespanel.html
- web-ui/src/main/resources/catalog/js/edit/EditorBoardController.js
- web-ui/src/main/resources/catalog/style/gn.less
- web-ui/src/main/resources/catalog/templates/editor/editorboard.html
- web-ui/src/main/resources/catalog/views/default/templates/advancedSearchForm/defaultAdvancedSearchForm.html
Harmonisation of the search functions between search page and editor
- Add user searches into the editor
- Add search options into the editor
- Apply same look and feel
> Update search options of the editor 

- web-ui/src/main/resources/catalog/components/elasticsearch/EsService.js
- web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js
This Pr adds and reads queryParams for both titleOnly and exactMatch options.
> feat(Search): add options to permalink

- csw-server/pom.xml
- csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/FilterParser.java
- csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/SearchController.java
- csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/es/CswFilter2Es.java
- csw-server/src/test/java/org/fao/geonet/kernel/csw/services/getrecords/IdentityFieldMapper.java
- csw-server/src/test/java/org/fao/geonet/kernel/csw/services/getrecords/es/CswFilter2EsTest.java
- csw-server/src/test/java/org/fao/geonet/kernel/csw/services/getrecords/es/CswFilter2EsTestConfiguration.java
- csw-server/src/test/java/org/fao/geonet/kernel/csw/services/getrecords/es/EsJsonHelper.java
- pom.xml
BBOX was handled like other Geometries, which causes an exception.
* Some refactoring.
* Adding a test framework for Elasticsearch queries, adding tests for the CSW2ES.
* Fixing https://github.com/geonetwork/core-geonetwork/issues/5910.
> Handle BBOX Filter correctly, add tests

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout-custom-fields-keywords.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/eng/strings.xml
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/fre/strings.xml
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/add-extent-from-geokeywords.xsl
- schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields-keywords.xsl
- schemas/iso19139/src/main/plugin/iso19139/loc/eng/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/fre/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/process/add-extent-from-geokeywords.xsl
- web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
- web/src/main/webapp/xslt/ui-metadata/form-configurator.xsl
* Add support to add an extent for a particular keyword
* Compute one extent based on all keywords
* Fix gcx:Anchor support
> Editor / ISO / Compute extent from one keyword or add one extent from all keywords

- web-ui/src/main/resources/catalog/views/default/module.js
Propagate the removal as it's causing a bug now.
> fix(ui): metadata.getId() has been removed

- core/src/main/java/org/fao/geonet/kernel/AccessManager.java
- core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java
- domain/src/main/java/org/fao/geonet/repository/UserRepositoryCustom.java
- domain/src/main/java/org/fao/geonet/repository/UserRepositoryImpl.java
- domain/src/test/java/org/fao/geonet/repository/UserRepositoryTest.java
- services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
Backport of https://github.com/geonetwork/core-geonetwork/pull/5971 for `3.12.x`
> Fix workflow mail notifications for metadata with a working copy (3.12.x)

- core/src/main/java/org/fao/geonet/util/XslUtil.java
- schemas/iso19139/src/main/plugin/iso19139/convert/functions.xsl
Updated default language so that is comes from common java location.
Also removed global language variable from functions.xsl as it is not good practice to put global variables in a functions library.
> Updated default language so that is comes from common java location.

- core/src/main/java/org/fao/geonet/kernel/setting/Settings.java
- services/src/main/java/org/fao/geonet/api/records/editing/InspireValidatorUtils.java
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v3122/migrate-default.sql
See https://github.com/INSPIRE-MIF/helpdesk-validator/issues/594 for details.
> [BP] INSPIRE / Validation / Add API Key. (#5975)

- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
> Dublin core / Editor / Fix autocomplete for subtemplates.

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/fromJsonLdEsri.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/fromJsonOpenDataSoft.xsl
For OpenDataSoft records:
* Correctly harvests keywords and themes
* Infer download links from metadata (geo or not, shapefile or not...)
* Slightly better feature attributes labels
For ESRI records:
* correctly harvest keywords and themes
* infer download link protocols
Result (ODS):
> JSON Harvester / Improve ESRI and OpenDataSoft harvesting

- web-ui/src/main/resources/catalog/templates/admin/usergroup/groups.html
- web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html
Similar code as in the categories maintenance filter.
> Allow to reset the users / groups filters

- core/src/main/java/jeeves/server/dispatchers/ServiceManager.java
- core/src/main/java/jeeves/server/local/LocalServiceRequest.java
- core/src/main/java/jeeves/server/sources/http/HttpServiceRequest.java
Test case: Select metadata records and export to PDF.
1) Without the fix the PDF output is opened in the browser tab of the application
2) With the fix the PDF is downloaded.
> Fix method signature in HttpServiceRequest, Related to #5534

- web-ui/src/main/resources/catalog/templates/admin/usergroup/groups.html
> Don't display the delete button when creating a new group

- web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/views/default/less/gn_map_default.less
- web-ui/src/main/resources/catalog/views/default/module.js
- web-ui/src/main/resources/catalog/views/default/templates/results.html
> [BP]  Enable to display map in left column of search UI (#6080)

- web/src/main/webapp/xml/csw/record-to-csw-capabilities.xsl
- Fix language code for conformity reports
- Processs 976/2009 report
> Service record for CSW capabilities - INSPIRE improvements

- domain/src/main/java/org/fao/geonet/repository/reports/MetadataReportsQueries.java
- services/src/main/java/org/fao/geonet/api/reports/ReportInternalMetadata.java
- services/src/main/java/org/fao/geonet/api/reports/ReportUpdatedMetadata.java
Updated the reports to:
- Add metadata change date to the report.
- Exclude metadata templates.
> Metadata update and internal reports updates

- web-ui/src/main/resources/catalog/components/common/map/mapService.js
Related to https://github.com/geonetwork/core-geonetwork/pull/6031
> Fix check for layer already in map - case insensitive check of the url

- pom.xml
- services/src/main/java/org/fao/geonet/services/metadata/BatchOpsMetadataReindexer.java
- services/src/main/java/org/fao/geonet/services/metadata/Publish.java
> [BP] Update libs reported by github security. See 6aecf968

- web-ui/src/main/resources/catalog/templates/top-toolbar-accessible.html
Port to `main` branch of the commits:
- ada4fd27a52d6a78b2d01fbe8b4690fc02b4c5b9
- 255e113636577ea8448e67150d37d9d848e65ca5
> [FP] Add register and lost password option to accessible login menu - port to main branch

- web-ui/src/main/resources/catalog/components/metadatamanager/EditorService.js
Followup of #6147, fixes runtime error when editing subtemplates
> Editor / fix subtemplate editing

- services/src/main/java/org/fao/geonet/api/userfeedback/UserFeedbackUtils.java
- web-ui/src/main/resources/catalog/components/userfeedback/GnUserfeedbackDirective.js
- web-ui/src/main/resources/catalog/components/userfeedback/partials/userfeedback.html
- web-ui/src/main/resources/catalog/components/userfeedback/partials/userfeedbackfull.html
- web-ui/src/main/resources/catalog/components/userfeedback/partials/userfeedbacknew.html
- web-ui/src/main/resources/catalog/views/default/templates/recordView.html
* User feedback / Fix average calculation. Do not start with a 0 star rating.
* User feedback / More consistent layout. Hide actions when not applying.
* User feedback / Special fix for Michel's browser ;). Cleaner approach though.
> [BP] User feedback improvements (#5443)

- services/src/main/java/org/fao/geonet/api/site/SiteApi.java
It returns an invalid error as it's not counting the metadata working copies when the metadata workflow is enabled.
Test case (without the PR):
1) Enable the metadata workflow
2) Create a metadata record
3) In the Admin console > Statistics and status > Records in index/db reports `OK`
4) Approve and edit the metadata
5) In the Admin console > Statistics and status > Records in index/db reports `ERROR` (wrong)
The PR counts the metadata working copy fixing the previous issue.
> Update index synchronized with database service to count metadata working copies when the metadata workflow is enabled

- web-ui/src/main/resources/catalog/templates/top-toolbar-accessible.html
In order to make the menubar accessible menu items and submenus have new/added roles
> [a11y] Adding/Removing the correct WAI-ARIA roles to the menu

- web-ui/src/main/resources/catalog/locales/en-editor.json
The text 
needs to be more precised.
> remove Thumbnail recommended text.

- web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facet.html
- web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facets.html
- web-ui/src/main/resources/catalog/locales/en-v4.json
- web-ui/src/main/resources/catalog/style/gn_search.less
- web-ui/src/main/resources/catalog/views/default/less/gn_search_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_variables_default.less
[a11y] Improve the accessibility of the facet tree in the search results page
Changes:
- color for count label (more color contrast)
- color for links (more color contrast)
- added title for toggle button
- add `aria-label` for the filter input
> [a11y] Improve the accessibility of the facet tree in the search results page

- services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
- services/src/main/java/org/fao/geonet/api/records/model/MetadataBatchApproveParameter.java
- web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js
- web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionsDirective.js
- web-ui/src/main/resources/catalog/components/metadataactions/partials/batchapprove.html
- web-ui/src/main/resources/catalog/components/search/resultsview/SelectionDirective.js
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/selection-widget.html
- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
- web-ui/src/main/resources/catalog/components/utility/partials/batchreport-workflow.html
- web-ui/src/main/resources/catalog/locales/en-core.json
- web-ui/src/main/resources/catalog/locales/en-search.json
- web-ui/src/main/resources/catalog/style/gn.less
> [FP] Metadata workflow - Bulk metadata approval

- schemas/iso19139/src/main/plugin/iso19139/loc/fre/codelists.xml
Make the translations similar to the ones provided for iso19115.3.
> Update French translations for iso19139 topic categories

- web/src/main/webapp/xml/csw/record-to-csw-capabilities.xsl
Related to this commit: https://github.com/geonetwork/core-geonetwork/commit/2396d0a2f84b4e87cea8d2d966d4fc2b8e6dcfc8
> [FP] Record to CSW Capabilities - Handle dates with gco:Date for INSPIRE MetadataDate element

- web-ui/src/main/resources/catalog/components/catalog/CatalogService.js
- web-ui/src/main/resources/catalog/js/search/SearchController.js
- web-ui/src/main/resources/catalog/locales/en-v4.json
- web-ui/src/main/resources/catalog/views/default/templates/home.html
- web/src/main/webapp/xml/csw/record-to-csw-capabilities.xsl
- Use connect point url for CSW capabilities end-points
- Display portal information in the home page
> Update usage of portal service metadata

- web/src/main/webapp/doc/api/index.html
Sort tags and operations in swagger so that it produces consistent layout.
Fixed the following sorting issue #5810
> Swagger - Sort tags and operations

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/CswParams.java
Fix for https://github.com/geonetwork/core-geonetwork/pull/6223#pullrequestreview-930354862
> Harvester / CSW / Add sortby option / Fix default and empty value save

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java
> Harvester of type Geonetwork using MEF format doesn't update the server in the online resource links for uploaded files/thumbnails 

- web-ui/src/main/resources/catalog/templates/editor/import.html
> Import / After import, add link to view record

- web-ui/src/main/resources/catalog/components/search/formfields/FormFieldsDirective.js
Test:
* Create a harvester with a group, save
* Reload page, the group owner is wrong.
> Admin / Harvester / Properly set group on page load

- core/src/main/java/org/fao/geonet/kernel/mef/MEF2Visitor.java
> Import / MEF / Add missing space in message.

- web-ui/src/main/resources/catalog/js/CatController.js
Similar to https://github.com/geonetwork/core-geonetwork/pull/6091 for
- List of templates for search results
- List of download formatter for record view
- List of formatter for record view
- List of link types
- List of map projections to display bounding box coordinates in
> Fix removal of elements in the UI configuration

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
> Add index field resourceTypeName (iso19115-3)

- web-ui/src/main/resources/catalog/templates/admin/dashboard/record-links.html
> Admin / Link analysis / Fix translation

- web/src/main/webapp/WEB-INF/config-csw.xml
cf. https://github.com/geonetwork/core-geonetwork/blob/main/schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl#L1014
> CSW / Fix mapping for protocol.

- web-ui/src/main/resources/catalog/js/edit/BatchEditController.js
- web-ui/src/main/resources/catalog/templates/editor/import.html
- web-ui/src/main/resources/catalog/templates/editor/new-metadata-horizontal.html
- web-ui/src/main/resources/catalog/templates/editor/new-metadata-vertical.html
* Batch editing / Search and replace allow one change at a time.
Changes was displayed twice.
* New record / Hide panel when user is not editor in any group.
eg. create a userAdmin. This user will get API error when trying to import or create new records and the alert is displayed with the form. Hide the form.
> Editor board minor fixes

- services/src/test/java/org/fao/geonet/api/site/SiteApiTest.java
- services/src/test/java/org/fao/geonet/api/users/UsersApiTest.java
With [BP] Admin / Password reset by admin the tests startet to fails. This
fixes the failing tests.
Ref https://github.com/geonetwork/core-geonetwork/commit/038994992a6f50808f068f85831d0c5af069cdbe
> Fix tests that started failing on passwords BP

- web-ui/src/main/resources/catalog/components/metadataactions/RelatedResourcesService.js
- web-ui/src/main/resources/catalog/components/metadataactions/partials/relatedSimpleList.html
- web-ui/src/main/resources/catalog/locales/en-core.json
> Add child icon for related resources

- core/src/main/java/org/fao/geonet/kernel/search/EsFilterBuilder.java
Fixes https://github.com/geonetwork/core-geonetwork/issues/6289
> Portal / Fix operation with permission filter

- web-ui/src/main/resources/catalog/components/edit/directoryentryselector/partials/directoryentrylistselector.html
Button is clickable even if style is disabled.
> Editor / Directory / Fix disabled button when role isn't selected

- web-ui/src/main/resources/catalog/js/edit/NewMetadataController.js
- web-ui/src/main/resources/catalog/templates/editor/new-metadata-horizontal.html
- web-ui/src/main/resources/catalog/templates/editor/new-metadata-vertical.html
* Fix filtering
* Reset filter on type change
* Make more consistent horizontal and vertical forms.
> New metadata / Fix filter when lot of templates.

- services/src/main/java/org/fao/geonet/api/records/editing/MetadataEditingApi.java
Test case:
1) Edit an approved record to get a working copy- workflow status of master record is "approved", status shown in contribute tab is "approved with working copy"
2) Edit the working copy and choose "save and submit"- workflow status of working copy is "submitted", workflow status of master record is "approved", status shown in contribute tab is "approved with working copy submitted"
3) Edit the working copy and choose "save and approve"- workflow status of master record is "approved", workflow status of working copy is "approved", workflow status shown in contribute tab is "statusWorkflow-22" --> NO OK
With the fix, the approved version is replaced with the working copy and the status is displayed properly.
> Metadata workflow: fix save and approve action in the metadata editor, that wasn't replacing the approved version with the working copy changes

- core/src/main/java/org/fao/geonet/kernel/setting/Settings.java
- services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/templates/admin/settings/system.html
- web-ui/src/main/resources/catalog/templates/editor/editorboard.html
- web-ui/src/main/resources/catalog/templates/top-toolbar-accessible.html
- web-ui/src/main/resources/catalog/templates/top-toolbar.html
- web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v3125/migrate-default.sql
Backport of b43cff2465beecff16ea53f33f033f070cbc19c1, related to #6200
> [BP] Configuration of the user profile authorized to import metadata

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/add-info-from-wms.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/add-wms-and-legend-from-esrirest.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/process-utility.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/spatineo-registration.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/suggest.xsl
- schemas/iso19139/src/main/plugin/iso19139/process/add-info-from-wms.xsl
* Port ISO19139 version to ISO19115-3
* Add a limit to not encode all CRS (some WMS server list all EPSG codes which will produce huge metadata records)
* Fix exception on spatineo registration for multilingual records.
> Editor / Suggestions / Add info from WMS.

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/spatineo-registration.xsl
- services/src/main/java/org/fao/geonet/api/records/MetadataAssociatedApi.java
- web-ui/src/main/resources/catalog/components/metadatamanager/EditorService.js
- web-ui/src/main/resources/catalog/components/search/mdview/mdviewService.js
- web-ui/src/main/resources/catalog/js/edit/NewMetadataController.js
- web-ui/src/main/resources/catalog/locales/en-v4.json
- web-ui/src/main/resources/catalog/style/gn_metadata.less
* Associated resources / Avoid JS errors on dublin core records
* Missing translation key
* Record view / Add space after association
* Cleaning / Unused code.
* New metadata / Hide map static type
* Translations / Missing key
> Minor fixes

- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataIndexer.java
- core/src/main/java/org/fao/geonet/resources/Resources.java
- core/src/main/java/org/fao/geonet/util/XslUtil.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java
When harvester use a logo not in PNG format, the logo URL is wrong in the index.
Set the logo in the source entity (like for portal).
Add XSL utility to get the source logo properly.
> Harvester / Logo may not be a png.

- core/src/main/java/org/fao/geonet/kernel/security/keycloak/KeycloakAuthenticationProcessingFilter.java
Update keycloak locale detection so that it supports LanguageTag formats such as en-CA
> Update locale parsing from keycloak token to support different formats.

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index-subtemplate.xsl
Entry title is: `org (name or email)`
Follow up of https://github.com/geonetwork/core-geonetwork/pull/6292
> ISO19115-3 / Directory / Avoid duplicated org name in title

- web-ui/src/main/resources/catalog/js/admin/UserGroupController.js
Depends on loading time, usually english works fine but when switching language app settings are not yet loaded.
> Admin / User / Config not always loaded in prod mode

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl
Do not render extent which may be used to describe data quality scope, ...
> Standard / ISO19115-3 / Render extent from identification section only

- .gitignore
- domain/src/main/java/org/fao/geonet/domain/ISODate.java
- domain/src/test/java/org/fao/geonet/domain/ISODateTest.java
- software_development/BUILDING.md
- web/README.md
- web/pom.xml
Resolves https://github.com/geonetwork/core-geonetwork/issues/6373
Resolves https://github.com/geonetwork/core-geonetwork/issues/6375
> ISODate shortDate test case correction for locale timezone senstivity

- common/pom.xml
- common/src/main/java/org/fao/geonet/utils/Diff.java
- core/pom.xml
- core/src/main/java/org/fao/geonet/kernel/thumbnail/ThumbnailMaker.java
- pom.xml
- schemas/dublin-core/pom.xml
- services/pom.xml
- services/src/main/java/org/fao/geonet/api/records/formatters/FormatterApi.java
- services/src/main/java/org/fao/geonet/api/records/formatters/ImageReplacedElementFactory.java
- web/pom.xml
Backport of https://github.com/geonetwork/core-geonetwork/pull/6343
> [BP] Switch from iText to OpenPDF for PDF map rendering (4.0.x)

- .github/workflows/sonarcloud.yml
- pom.xml
Add Workflow and pom properties to enable  SonarCloud analysis.
> Add github workflow and properties for SonarCloud.

- core/src/main/java/org/fao/geonet/api/records/attachments/CMISStore.java
- core/src/main/java/org/fao/geonet/resources/CMISResources.java
We have a requirement to extend some of the CMIS private methods for custom enhancements so changing some of the methods to protected.
> Change some of the CMIS private methods to protected

- services/src/main/java/org/fao/geonet/api/reports/ReportDownloads.java
- services/src/main/java/org/fao/geonet/api/reports/ReportInternalMetadata.java
- services/src/main/java/org/fao/geonet/api/reports/ReportUpdatedMetadata.java
- services/src/main/java/org/fao/geonet/api/reports/ReportUploads.java
- services/src/main/java/org/fao/geonet/api/reports/ReportUtils.java
Modify retrieveMetadataTitle aiming to retreive other field value from the index.
> Improve report - refactor retrieveMetadataTitle 

- inspire-atom/src/main/java/org/fao/geonet/inspireatom/harvester/InspireAtomHarvester.java
If referenced by more than 1 feed, ignore the other feeds.
Related to https://github.com/geonetwork/core-geonetwork/pull/6118, that should not be required with this change.
> Remote INSPIRE Atom - A metadata should be referenced by 1 feed. 

- web-ui/src/main/resources/catalog/components/viewer/ViewerDirective.js
- web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextService.js
> Map viewer - zoom to full extent to the map context full extent if defined, instead of the projection extent.

- core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
- web-ui/src/main/resources/catalog/components/elasticsearch/EsFacet.js
- web-ui/src/main/resources/catalog/components/elasticsearch/LuceneQueryParser.js
- web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facets.html
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/js/admin/DashboardStatusController.js
- web-ui/src/main/resources/catalog/js/admin/HarvestSettingsController.js
- web-ui/src/main/resources/catalog/locales/en-v4.json
- web-ui/src/main/resources/catalog/templates/admin/dashboard/status.html
- web-ui/src/main/resources/catalog/templates/admin/harvest/harvest-settings.html
- web-ui/src/main/resources/catalog/views/default/less/gn_admin_default.less
- web/src/main/webResources/WEB-INF/data/config/index/records.json
* Add search box for indexing errors
* Add aggregation on error type
* Harvester / Add facet on indexing errors
* Index schema / Type for indexing error fields
* Indexing / Cleaning some old stuff eg. _text_ field does not exist anymore
* Fix no match when facet contains "
> Admin / Indexing error improvements

- web-ui/src/main/resources/catalog/js/edit/EditorBoardController.js
Make number of records per page consistent in all app.
> Editor board / Search / Same hits per page config

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/jsonld/iso19115-3.2018-to-jsonld.xsl
- schemas/iso19139/src/main/plugin/iso19139/formatter/jsonld/iso19139-to-jsonld.xsl
Fix invalid JSON when description element is not in link
> Formatter / JSONLD / Online source / Fix when empty description.

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFsHarvesterFileVisitor.java
- web-ui/src/main/resources/catalog/js/admin/HarvestSettingsController.js
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/filesystem.html
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/filesystem.js
> Harvester / LocalFileSystem / Add batch edits.

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/ogcwxs/Harvester.java
Tested with http://tiles.craig.fr/ortho/wmts/1.0.0/WMTSCapabilities.xml.
> Harvester / WMTS / Fix error on GetCapabilities.

- pom.xml
- workers/camelPeriodicProducer/pom.xml
- workers/pom.xml
This reverts commit aee1134c053a0bdce7ac31c4471600e86ec5a7fc.
> Revert "Bump camel.version from 2.25.1 to 2.25.4 (#6364)"

- web-ui/src/main/resources/catalog/components/catalog/CatalogService.js
- web-ui/src/main/resources/catalog/components/common/map/mapService.js
- web-ui/src/main/resources/catalog/components/search/mdview/mdviewService.js
- web-ui/src/main/resources/catalog/components/search/resultsview/ResultsviewDirective.js
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid.html
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid4maps.html
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/list.html
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/table.html
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/views/default/directives/partials/linksbtn.html
Reuse the same config in various places to have the same definition
of links, download and layers.
Add the possibility to customize link button groups.
> Search results / Improve button link config

- core/src/main/java/org/fao/geonet/util/XslUtil.java
untested yet, but you get the idea. From #6486
> lowercase extension before matching it against a lowercase regex (#6486)

- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
Only temporal range using beginPosition and endPosition was displayed.
> Record view / Full / Display temporal range using gml:end/begin element

- web-ui/src/main/resources/catalog/components/edit/geopublisher/GeoPublisherDirective.js
- web-ui/src/main/resources/catalog/templates/admin/settings/mapservers.html
Also fix display of exception message in editor geopublication panel.
> Admin / MapServers / Fix button label.

- web-ui/src/main/resources/catalog/views/default/less/gn_print_default.less
Related to and fix for PR: https://github.com/geonetwork/core-geonetwork/pull/6517
Somehow the the print less file wasn't added to the PR, this fixes it.
> [FIX] Add missing print stylesheet

- web-ui/src/main/resources/catalog/components/search/facets/partials/facet-daterange.html
- web-ui/src/main/resources/catalog/views/default/directives/partials/dateRangeFilter.html
> Advanced search - datepicker doesn't work.

- core/src/main/java/jeeves/config/springutil/JeevesDelegatingFilterProxy.java
- web/src/main/webResources/WEB-INF/web.xml
This remove some code that is not needed anymore since the multi-node support has been
replaced by the portals functionality.
> Remove non-needed code since multi-node support is not available

- web-ui/src/main/resources/catalog/components/viewer/wfs/partials/processform.html
Typo introduced in https://github.com/geonetwork/core-geonetwork/pull/6543
> HTML / Remove uneeded attribute

- web-ui/src/main/resources/catalog/views/default/templates/recordView/type-dataset.html
eg. dublin core records
So don't display map.
> Record view / Records may not have extent

- web-ui/src/main/resources/catalog/locales/en-admin.json
> i18n / No . needed in button label

- web-ui/src/main/resources/catalog/components/edit/directoryentryselector/DirectoryEntrySelector.js
- web-ui/src/main/resources/catalog/components/elasticsearch/EsFacet.js
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/js/edit/DirectoryController.js
* Fix load more in directory facet (and in editor directory panel)
* Move the configuration in the gnGlobalConfig
Thanks @fgravin https://github.com/geoadmin/geocat/commit/bfff48fa3180c8e751ce6bb72fc4d4d29079443b
> Directory / Facet / Fix loadmore

- web-ui/src/main/resources/catalog/components/viewer/wfsfilter/partials/wfsfilterfacet.html
When selecting filter, highlight the facet name (like in main search).
> Record view / Data preview / Highlight current filter.

- web/src/main/webResources/WEB-INF/data/config/index/records.json
> Index field data types - Define resourceTypeName type

- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/editor.html
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid.html
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid4maps.html
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/list.html
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/table.html
- web-ui/src/main/resources/catalog/views/default/templates/recordView/title.html
Break title in record view and search results.
> Search results / Title may be long.

- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/views/default/directives/directive.js
- web-ui/src/main/resources/catalog/views/default/directives/partials/mdactionmenu.html
> Use function to build formatter (xml, pdf, dcat,...)

- web-ui/src/main/resources/catalog/components/admin/registry/RegistryService.js
Not sure if related to last update https://inspire.ec.europa.eu/news/update-inspire-registry-re3gistry-software-v2 but it looks like the API changed.
> Thesaurus / Import from Re3gistry failing

- core/src/main/java/org/fao/geonet/util/SpatineoUtil.java
- core/src/test/java/org/fao/geonet/util/SpatineoUtilTest.java
Related to https://github.com/geonetwork/core-geonetwork/pull/6298
> Add proxy to Spatineo registration service

- schemas/iso19139/src/main/plugin/iso19139/index-fields/index-subtemplate.xsl
- Remove indexing of `any` field, as it's copied from `resourceTitleObject`
- Add index DQ report
> ISO19139 subtemplates indexing updates

- web-ui/src/main/resources/catalog/js/admin/MapServerController.js
- web-ui/src/main/resources/catalog/js/admin/MetadataIdentifierTemplatesController.js
- web-ui/src/main/resources/catalog/js/admin/SourcesController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/style/gn_admin.less
- web-ui/src/main/resources/catalog/templates/admin/metadata/metadata-identifier-templates.html
- web-ui/src/main/resources/catalog/templates/admin/settings/mapservers.html
- web-ui/src/main/resources/catalog/templates/admin/settings/sources.html
> [BP] Map servers / sources / metadata template identifiers - delete confirmation dialog and fixes in display delete button in sources page

- web/src/main/webResources/WEB-INF/data/config/index/records.json
See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/analysis-lang-analyzer.html#dutch-analyzer
> Indexing / Adding dutch analyzer

- workers/wfsfeature-harvester/src/main/java/org/fao/geonet/harvester/wfsfeatures/worker/EsWFSFeatureIndexer.java
- workers/wfsfeature-harvester/src/main/java/org/fao/geonet/harvester/wfsfeatures/worker/WFSHarvesterRouteBuilder.java
Relevant to apply to GeoNetwork @jahow ?
> Harvester / WFS / limit concurrent indexation to 5

- web-ui/src/main/resources/catalog/components/viewer/ViewerDirective.js
> Map / doSync has no parameters

- web-ui/src/main/resources/catalog/js/admin/DashboardWfsIndexingController.js
Test: 
* set filter
* update a schedule
* list is refreshed and current filter was not applied
@julsbreakdown do you mind if I backport this change you made on project ?
> Harvester / WFS feature / Apply current filter after config change

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index-subtemplate.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/config-editor.xml
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/schema-ident.xml
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/update-fixed-info-subtemplate.xsl
- web-ui/src/main/resources/catalog/components/edit/directoryentryselector/DirectoryEntrySelector.js
- web-ui/src/main/resources/catalog/components/edit/directoryentryselector/partials/directoryentrylistselector.html
- web-ui/src/main/resources/catalog/components/edit/directoryentryselector/partials/directoryentryselector.html
* Add possibility to add from a XML snippet from config editor
* ISO19115-3 / Fix limitation due to suggestion not able to choose from Individual or Party. Use a snippet instead.
Before
After it adds a default contact with organisation name and email
* ISO19115-3 / Add proper default role depending on type
* XLink / Cleanup duplicated buttons.
Sample configuration to also add a contact selector inside a form (and not only general config). This config also use an ISO19139 directory for contact converted to ISO19115-3 when inserted.
```xml
<action type="add"
name="empty"
addDirective="data-gn-directory-entry-selector"
or="contact"
in="/mdb:MD_Metadata">
data-template-add-snippet="&lt;cit:CI_Responsibility
xmlns:cit='http://standards.iso.org/iso/19115/-3/cit/2.0' …
```
> Editor / Add from directory improvements

- domain/src/main/java/org/fao/geonet/domain/Localized.java
- domain/src/main/java/org/fao/geonet/domain/Source.java
- services/src/main/java/org/fao/geonet/api/sources/SourcesApi.java
- web-ui/src/main/resources/catalog/components/search/resultsview/SelectionDirective.js
- web-ui/src/main/resources/catalog/components/usersearches/partials/portalswitcher.html
- web-ui/src/main/resources/catalog/js/admin/SourcesController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/templates/admin/settings/sources.html
This Pull request add a new setting in _Admin > Settings > Sources_ that allows to choose if a portal must be displayed in the portal switcher that exists in the top toolbar.
> New setting for showing/hiding a portal in the top toolbar 

- core/pom.xml
- core/src/main/java/org/fao/geonet/api/records/attachments/FMEStore.java
Add upload file support for https://github.com/geonetwork/core-geonetwork/pull/6688
> Datastore / Metadata files / FME API Support / Add upload file support

- web-ui/src/main/resources/catalog/components/elasticsearch/directives/FacetDirective.js
- web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facet-cards.html
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/style/gn_search.less
- web-ui/src/main/resources/catalog/views/default/less/gn_topics_default.less
Follow-up of https://github.com/geonetwork/core-geonetwork/pull/6556
Add icon for resource type, catalogue (using logos), harvested and record type facets.
> Editor board / Facet / Configure decorator.

- web-ui/src/main/resources/catalog/templates/admin/metadata/metadata-identifier-templates.html
- web/src/main/webapp/WEB-INF/data/data/resources/config/manual.json
> Admin / Metadata identifier / Add link to doc.

- web/src/main/webapp/xml/csw/record-to-csw-capabilities.xsl
Fixes https://github.com/geonetwork/core-geonetwork/issues/6744
> CSW / GetCapabilities created from service metadata record had incorrect Transaction endpoint

- web-ui/pom.xml
- web-ui/src/test/jasmine/README
- web/src/main/webapp/xslt/base-layout-cssjs-loader.xsl
Remove unused or duplicated resources.
> Module / web-ui / Cleaning

- core/src/main/java/org/fao/geonet/util/XslUtil.java
- lower severity of language iso code mismatch
- add relevant parameters to log messages
Backport of https://github.com/geonetwork/core-geonetwork/pull/5751.
> [BP] XSL / improve log messages #5751

- common/src/main/java/org/fao/geonet/utils/IO.java
- core/src/main/java/org/fao/geonet/kernel/backup/ArchiveAllMetadataJob.java
- core/src/main/java/org/fao/geonet/kernel/mef/MEF2Exporter.java
- core/src/main/java/org/fao/geonet/kernel/mef/MEFExporter.java
- core/src/main/java/org/fao/geonet/resources/S3Resources.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/wfsfeatures/Harvester.java
- services/src/main/java/org/fao/geonet/api/records/CatalogApi.java
- services/src/main/java/org/fao/geonet/api/records/MetadataApi.java
- services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
- services/src/main/java/org/fao/geonet/api/records/MetadataUtils.java
- services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsActionsApi.java
- services/src/main/java/org/fao/geonet/api/records/formatters/FormatterAdminApi.java
- services/src/main/java/org/fao/geonet/api/records/formatters/PDF.java
- services/src/main/java/org/fao/geonet/guiapi/search/XsltResponseWriter.java
- services/src/main/java/org/fao/geonet/services/rdf/GetPublicMetadataAsRdf.java
- services/src/main/java/org/fao/geonet/services/resources/DownloadArchive.java
Delete temporary files when they aren't used anymore instead of keeping them on disk.
Related to https://github.com/geonetwork/core-geonetwork/issues/4598
> Improve temporary file management

- services/src/main/java/org/fao/geonet/api/users/UsersApi.java
- services/src/test/java/org/fao/geonet/api/users/UsersApiTest.java
Related to https://github.com/geonetwork/core-geonetwork/pull/5560
> [FP] Update user - verify user groups when updating a user by a UserAdmin. Fixes #5537

- core/src/main/java/org/fao/geonet/util/XslUtil.java
- csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/es/CswFilter2Es.java
- csw-server/src/test/java/org/fao/geonet/kernel/csw/services/getrecords/es/CswFilter2EsTest.java
- csw-server/src/test/java/org/fao/geonet/kernel/csw/services/getrecords/es/EsJsonHelper.java
Related to https://github.com/geonetwork/core-geonetwork/pull/6736
> CSW / Test / Updates for multilingual search support

- core/src/main/java/org/fao/geonet/kernel/Thesaurus.java
> Thesarus manager: don't create non-multilingual title/description if multilingual elements are defined

- web-ui/src/main/resources/catalog/components/edit/bounding/partials/boundingpolygon.html
Move bounding polygon user actions above the map like for bounding box
> Editor / Bounding polygon / More consistent layout

- services/src/main/java/org/fao/geonet/api/userfeedback/UserFeedbackAPI.java
Currently user could trigger a notification with a dummy UUID.
> API / User feedback only allowed on record user can view

- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v423/migrate-default.sql
Related to https://github.com/geonetwork/core-geonetwork/pull/6772
> Conversion / Don't set extension in conversion id.

- services/src/main/java/org/fao/geonet/api/processing/XslProcessApi.java
Update fixed info may apply some more transformation to the process requested. Apply it by default so end user will preview what will be saved in the database if the process is triggered.
http://localhost:8080/geonetwork/srv/api/processes/empty?uuids=d492f46a-b864-4bc6-9655-22cc611b2e36&applyUpdateFixedInfo=true
> API / XSL process / Apply update fixed info on preview

- web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js
- web-ui/src/main/resources/catalog/views/default/directives/partials/mdactionmenu.html
Follow up of https://github.com/geonetwork/core-geonetwork/pull/6708
> Record view / Remove create child option

- web/src/main/java/org/fao/geonet/proxy/URITemplateProxyServlet.java
Follow up of https://github.com/geonetwork/core-geonetwork/pull/6765
@josegar74 I found why the proxy was not working in your report https://github.com/geonetwork/core-geonetwork/pull/6765#pullrequestreview-1250054265
If no property set in env, we have to fallback to web.xml (like other properties).
Did some cleanup of the creation of the httpClient.
> Proxy / Add a custom proxy for secured Elasticsearch instances / Fallback to web.xml config.

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java
The original code was assigning a variable `mdUuid`, never used.
Changed the code so that if the harvester has set up an xslt process and this process changes the metadata uuid, that uuid takes precedence over the original metadata uuid or the metadata uuid to be assigned, depending on the uuid override policy.
> CSW Harvester / Add metadata - fix code to assign the metadata uuid, if changed in the xslt filter process

- web/src/main/webapp/xslt/common/index-utils.xsl
main language have to be added (default ?) if not already
cf. https://github.com/geonetwork/core-geonetwork/pull/6790/commits/2be3de4a76df0ac93f6a99d8d4690670772b1adb  (resolved comment)
> avoid md main language to be indexed twice

- web/src/main/webResources/WEB-INF/config-db/database_migration.xml
> Fix Pages API in migrated databases - add migration configuration. 

- core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
- web-ui/src/main/resources/catalog/locales/en-v4.json
- web-ui/src/main/resources/catalog/style/gn_metadata.less
- web-ui/src/main/resources/catalog/views/default/templates/recordView/title.html
eg. importing https://metawal.wallonie.be/geonetwork/srv/eng/catalog.search#/metadata/b795de68-726c-4bdf-a62a-a42686aa5b6f
> Record view / Display alternate title if any.

- web-ui/src/main/resources/catalog/views/default/less/gn_result_default.less
> Record view / Align thumbnail with the optional label

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/collection-updater.xsl
- schemas/iso19139/src/main/plugin/iso19139/process/collection-merge-utility.xsl
- schemas/iso19139/src/main/plugin/iso19139/process/collection-updater.xsl
- services/src/main/java/org/fao/geonet/api/records/formatters/FormatterApi.java
- services/src/main/java/org/fao/geonet/api/records/formatters/FormatterConstants.java
Follow up of https://github.com/geonetwork/core-geonetwork/pull/6368
* Processing / Collection updater : add publication date and fix error on multilingual records
The main goal here is to highlight in the series the last datasets published
* Formatter can contains "." but not "/".
* ISO19115-3 / Malformed JSON with empty overview description
> Standard / ISO / Collection updater / Add publication date and minor fixes

- common/src/main/java/org/fao/geonet/utils/Xml.java
- common/src/test/java/org/fao/geonet/utils/XmlTest.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/simpleurl/RDFUtils.java
Fix RDF document detection for https://data.spatialhub.scot/catalog.rdf.
> Harvester / DCAT / Improve RDF doc detection.

- core/src/main/java/org/fao/geonet/kernel/datamanager/IMetadataValidator.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataValidator.java
- services/src/main/java/org/fao/geonet/api/processing/ValidateApi.java
Enhancement based on issue #6899
Update validation report to include more information in the report.
- Include uuid of the record in the report
- Include errors in the report
Validation report will look something like the following
> Update validation report to include more information in the report.

- core/src/main/java/org/fao/geonet/kernel/datamanager/IMetadataValidator.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataValidator.java
- services/src/main/java/org/fao/geonet/api/processing/ValidateApi.java
- services/src/main/java/org/fao/geonet/services/metadata/ValidationService.java
[BP] Update validation report to include more information in the report. 
- Include uuid of the record in the report
- Include errors in the report
Back port for PR #6900 
Enhancement for #6899
> [BP] Update validation report to include more information in the report. #6900

- docs/schema-doc/src/main/resources/config-editor-doc.xsl
- schemas/config-editor.xsd
This is replacing the earlier pull request submitted in the documentation repository.
It includes a commit regarding spelling improvements and a commit for adding a warning at the top of the page to prevent others from making the same error as me and change the file in the wrong place.
> Editor / Schema documentation / Spelling imrpovements

- docs/schema-doc/src/main/resources/config-editor-doc.xsl
- docs/schema-doc/src/main/resources/config-editor-to-rst.xsl
- schemas/config-editor.xsd
- schemas/iso19139/src/main/plugin/iso19139/schema-ident.xml
Follow up of https://github.com/geonetwork/core-geonetwork/pull/6944.
To update the schema doc in the doc:
```
cd docs/schema-doc
mvn clean install
cd ../manual
make html_eng
```
> Doc / Fix warning

- web-ui/src/main/resources/catalog/components/viewer/baselayerswitcher/partials/baselayerswitcher.html
- web-ui/src/main/resources/catalog/components/viewer/layermanager/LayerManagerDirective.js
- web-ui/src/main/resources/catalog/components/viewer/layermanager/partials/layerdimensions.html
- web-ui/src/main/resources/catalog/components/viewer/layermanager/partials/layermanager.html
- web-ui/src/main/resources/catalog/components/viewer/layermanager/partials/layermanageritem.html
- web-ui/src/main/resources/catalog/components/viewer/wmsimport/WmsImportDirective.js
- web-ui/src/main/resources/catalog/locales/en-v4.json
- web-ui/src/main/resources/catalog/style/gn_viewer.less
Add support for WMS time and elevation dimension visualisation. For now, only support list of times (not range/interval).
* Support time and elevation dimension types
* Navigation using first/previous/next/last action and play/pause/stop
* Filter values to only browse/animate a subset
* Select value with slider control
To avoid too many button in the layer row
Consistently highlight current layer and current background layer:
and organize tools in groups in layer panel
Information panel also contains easy access to:
* zoom to extent
* metadata link
* copy/paste server URL and layer name
* download checker
> Map / WMS Time and elevation.

- schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
> ISO19139 / Editor / Fieldset on resource usage and userContactInfo

- schemas/iso19139/src/main/plugin/iso19139/formatter/iso19115-3.2018/view.xsl
- services/src/test/java/org/fao/geonet/api/records/MetadataAssociatedApiTest.java
- services/src/test/java/org/fao/geonet/api/records/formatters/FormatterAdminApiIntegrationTest.java
* Issue related to search results hits order
* add ISO19115-3 formatter for ISO19139
> Test / Fixes

- schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
Processor is a contact used in source process step section.
> ISO19139 / Editor / Fieldset on processor

- csw-server/src/main/java/org/fao/geonet/component/csw/Transaction.java
When running INSERT/UPDATE/DELETE CSW transaction are not registered in the record history.
Test:
* enable history
* http://localhost:8080/srv/eng/admin.console#/settings/csw-test
* run the sample transaction queries
* check the history
> CSW / Transactions are not in history.

- web-ui/src/main/resources/catalog/components/common/share/ShareDirective.js
- web-ui/src/main/resources/catalog/components/common/share/partials/panel.html
- web-ui/src/main/resources/catalog/style/gn.less
On Firefox, + and - icon do not display when updating privileges for a selection.
See https://bugzilla.mozilla.org/show_bug.cgi?id=765035 https://www.w3.org/TR/CSS2/generate.html#before-after-content
Replace CSS after by icon checking input validity.
> Sharing / Batch mode / Fix +/- icon on Firefox.

- web/src/main/webResources/WEB-INF/config-spring-geonetwork.xml
> i18n / Fix loading of languages for ICE, KOR and CZE

- services/src/main/java/org/fao/geonet/api/links/LinksApi.java
- web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
- web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js
- web-ui/src/main/resources/catalog/js/admin/DashboardRecordLinkController.js
When requesting link report for a large set of records in a selection, request URI may be too long depending on proxy. Use POST instead of GET.
API change:
* Move POST /links to POST /links/analyze to analyze a set of records
* Move POST /links/analyze to POST /links/analyzeurl to analyze a URL
> Admin / Link analysis / Use POST.

- services/src/test/java/org/fao/geonet/api/links/LinksApiTest.java
Follow up of https://github.com/geonetwork/core-geonetwork/pull/7022
> Admin / Link analysis / Use POST / Fix test

- doi/src/main/java/org/fao/geonet/doi/client/BaseDoiClient.java
- doi/src/main/java/org/fao/geonet/doi/client/DoiBuilder.java
- doi/src/main/java/org/fao/geonet/doi/client/DoiDataciteClient.java
- doi/src/main/java/org/fao/geonet/doi/client/DoiManager.java
- doi/src/main/java/org/fao/geonet/doi/client/DoiMedraClient.java
- doi/src/main/java/org/fao/geonet/doi/client/IDoiClient.java
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/datacite/view.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/eu-po-doi/base.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/eu-po-doi/view.xsl
- schemas/iso19139/src/main/plugin/iso19139/formatter/datacite/view.xsl
- schemas/iso19139/src/main/plugin/iso19139/formatter/eu-po-doi/view.xsl
- services/src/test/java/org/fao/geonet/api/records/formatters/FormatterAdminApiIntegrationTest.java
See http://ra.publications.europa.eu/schema/OP/DOIMetadata/1.0/OP_DOIMetadata_1.0.xsd
The format is composed of an enveloppe for DOI registration which can contain one or more Datacite resources. The XML document can be uploaded with a webform or send to a B2B endpoint.
Formatters is accessible at http://localhost:8080/geonetwork/srv/api/records/28a5cf37-95d5-4758-9204-9eada51ebb8a/formatters/eu-po-doi?output=xml
```xml
<eu:DOIRegistrationMessage xmlns:eu="http://ra.publications.europa.eu/schema/doidata/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ra.publications.europa.eu/schema/doidata/1.0 http://ra.publications.europa.eu/schema/OP/DOIMetadata/1.0/OP_DOIMetadata_1.0.xsd">
<eu:Header>
<eu:FromCompany>European Environment Agency</eu:FromCompany> …
```
> DOI / Add European Union Publication Office format for DOI.

- schemas/iso19139/src/main/plugin/iso19139/loc/dut/schematron-rules-iso.xml
Backport of some translations from Vlaanderen catalogues
> Standard / ISO19139 / Schematron / NL translation

- web-ui/src/main/resources/catalog/style/inspire/iti-i18n-code.css
This affect home page facet summary not displaying label in Dutch.
Before
After 
To test, create a record with INSPIRE themes and switch UI to dutch.
> i18n / NL / INSPIRE Themes / Fix language code

- pom.xml
- web-ui/src/main/resources/catalog/components/common/scrollspy/partials/scrollspy.html
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/style/gn.less
- web-ui/src/main/resources/catalog/style/gn_editor.less
- workers/camelPeriodicProducer/pom.xml
Probably related to the Spring upgrade in #7023
> Fix workers module tests

- web-ui/src/main/resources/catalog/components/common/multiselect/partials/multiselect.html
- web-ui/src/main/resources/catalog/components/edit/FieldsDirective.js
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/fileUploader.html
- web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html
Fix for broken icons in the editor, admin pages, file uploader and multiselect
Related to: https://github.com/geonetwork/core-geonetwork/pull/7007
> Fix broken icons

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/schematron/criteria-type.xml
This was caused a javascript error in the administration page to configure the criteria that apply to the metadata validation rules.
> Add criteria-type.xml for iso19115-3.2018

- web-ui/src/main/resources/catalog/components/search/searchmanager/LocationService.js
- web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js
- web-ui/src/main/resources/catalog/components/search/searchoptions/SearchOptionsDirective.js
Similar as #7109 for `main` branch.
> Fix selection / filter Only my records

- core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java
To solve the issue of https://github.com/geonetwork/core-geonetwork/issues/6797
> 3.12.x.handle.undeclared throwable exception

- web-ui/src/main/resources/catalog/components/elasticsearch/directives/FacetDirective.js
Replace https://github.com/geonetwork/core-geonetwork/pull/7134 and follow up of https://github.com/geonetwork/core-geonetwork/pull/7104
> Workflow / Facets / Generic translations

- web/src/main/webapp/WEB-INF/classes/setup/sql/data/loc-fin-default.sql
- web/src/main/webapp/WEB-INF/classes/setup/sql/data/loc-ger-default.sql
- web/src/main/webapp/WEB-INF/classes/setup/sql/data/loc-por-default.sql
- web/src/main/webapp/WEB-INF/classes/setup/sql/data/loc-spa-default.sql
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v425/migrate-default.sql
> Update metadata status values translations

- core/src/main/java/org/fao/geonet/kernel/security/openidconnect/bearer/GeonetworkJwtAuthenticationProvider.java
Someone mentioned that there was a missing class referenced here;
https://github.com/geonetwork/core-geonetwork/blob/6db5d0486bc5da737301b0ceea36bfc8b8c301db/web/src/main/webapp/WEB-INF/config-security/config-security-openidconnectbearer.xml#L134
This was forgotten in the commits.
For reference, the original PR is here:
https://github.com/geonetwork/core-geonetwork/pull/6494
> missed file in pull/6494

- web-ui/src/main/resources/catalog/components/viewer/layermanager/partials/layermanageritem.html
- web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextService.js
Minor formatting changes.
I was automatically being applied by IDE during build.
> Minor formatting changes.

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/config-editor.xml
> Standard / ISO19115-3 / Editor / Expand abstract for multilingual records

- web-ui/src/main/resources/catalog/style/gn_metadata.less
> Record view / Citation / Improve layout

- core/src/test/resources/WEB-INF/config.properties
- core/src/test/resources/config-spring-geonetwork.xml
- services/src/test/resources/WEB-INF/config.properties
- workers/camelPeriodicProducer/src/test/resources/WEB-INF/config.properties
- workers/camelPeriodicProducer/src/test/resources/camel-test-config.xml
Follow up of https://github.com/geonetwork/core-geonetwork/pull/7169.
> Test / Fix for default language.

- software_development/TOOLS.md
Updated the OpenJDK8 link to Adoptium archive.
> Updated Java 8 download link

- web/src/main/webapp/WEB-INF/data/config/codelist/external/thesauri/place/regions.rdf
Related to https://github.com/geonetwork/core-geonetwork/issues/7207
> Thesaurus / Region / Use ISO format for date

- core/src/main/java/org/fao/geonet/kernel/SpringLocalServiceInvoker.java
- core/src/test/java/org/fao/geonet/GeonetTestFixture.java
- core/src/test/java/org/fao/geonet/kernel/AbstractIntegrationTestWithMockedSingletons.java
- core/src/test/java/org/fao/geonet/kernel/ElasticSearchIndexingTest.java
- core/src/test/java/org/fao/geonet/kernel/LocalXLinksInMetadataIntegrationTest.java
- core/src/test/java/org/fao/geonet/kernel/LocalXLinksUpdateDeleteTest.java
- core/src/test/resources/mocked-core-repository-test-context.xml
- core/src/test/resources/org/fao/geonet/kernel/forest.xml
- core/src/test/resources/org/fao/geonet/kernel/holocene.xml
- web/src/main/webResources/WEB-INF/data/config/index/records.json
ignore holocene and BC date when building resourceTemporalExtentDetails index
> Ignore holocene and BC date in resourceTemporalExtentDetails index

- workers/camelPeriodicProducer/src/test/java/org/fao/geonet/camelPeriodicProducer/MessageProducerControllerTest.java
- workers/camelPeriodicProducer/src/test/java/org/fao/geonet/camelPeriodicProducer/MessageProducerTest.java
- workers/camelPeriodicProducer/src/test/java/org/fao/geonet/camelPeriodicProducer/TestCamelNetwork.java
Improve scheduling of tests to reduce race conditions.
> camel tests, avoid side effects

- web-ui/src/main/resources/catalog/components/common/openlayers/olMapDirective.js
> avoid race condition, resize map once target size ok

- inspire-atom/src/main/java/org/fao/geonet/services/inspireatom/AtomServiceDescription.java
> Use Apache Commons StringUtils to join keywords in atom service description

- web-ui/src/main/resources/catalog/components/common/map/wmsQueue.js
> Map viewer / 'Default map' javascript error

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/add-wms-and-legend-from-esrirest.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/create-featurecatalogue-from-wfs.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/spatineo-registration.xsl
See https://github.com/geonetwork/core-geonetwork/blob/main/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/schema/standards.iso.org/19115/-3/mdb/2.0/metadataBase.xsd#L33-L37.
> Standard / ISO19115-3 / Processing / Metadata contact lost.

- web-ui/src/main/resources/catalog/components/common/map/mapService.js
WMS service layers that define the time dimension using an interval do not load correctly. Not only that the time slider doesn't render correctly, but the layer itself doesn't load
For example: https://geo.weather.gc.ca/geomet?lang=en&service=WMS&request=GetCapabilities&layers=GEPS.DIAG.24_PRMM.ERGE1
```
<Dimension name="time" units="ISO8601" default="2023-08-17T00:00:00Z" nearestValue="0">2023-08-17T00:00:00Z/2023-09-01T00:00:00Z/PT12H</Dimension>
```
This pull request adds some basic support for intervals. With these changes:
[wms-time-slider-supporting-intervals.webm](https://github.com/geonetwork/core-geonetwork/assets/1695003/6f26750d-d26c-4224-99e1-31035e3af25f)
> WMS time dimension - basic support for time intervals

- services/src/main/java/org/fao/geonet/api/records/formatters/FormatterApi.java
- web-ui/src/main/resources/catalog/components/search/searchmanager/LocationService.js
> Full view on working copy fails

- services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java
Try to improve memory usage when downloading attachments. In some cases, records with many thumbnails looks to have difficulties to be printed to PDF.
> API / Attachements / Stream files to servlet response

- core/src/main/java/org/fao/geonet/kernel/datamanager/draft/DraftMetadataUtils.java
- core/src/test/resources/org/fao/geonet/api/Messages.properties
- core/src/test/resources/org/fao/geonet/api/Messages_fre.properties
- services/src/main/java/org/fao/geonet/api/records/editing/MetadataEditingApi.java
- web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
- web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties
Refactor hard-coded messages to pull from resource files.
> Use resource files for messages

- web-ui/src/main/resources/catalog/components/edit/editorhelper/EditorHelperDirective.js
- web-ui/src/main/resources/catalog/components/edit/editorhelper/partials/editorhelper.html
> Metadata editor / recommended values for fields show an empty value.

- web-ui/src/main/resources/catalog/js/admin/UserGroupController.js
> Notifications / Errors / Fix message on group creation

- inspire-atom/src/main/java/org/fao/geonet/inspireatom/util/InspireAtomUtil.java
- inspire-atom/src/main/java/org/fao/geonet/services/inspireatom/AtomPredefinedFeed.java
Backport to `3.12.x` branch of https://github.com/geonetwork/core-geonetwork/pull/7305
> [BP] INSPIRE ATOM - retrieve the metadata ATOM feed using only the resourc…   …e identifier

- web-ui/src/main/resources/catalog/locales/en-editor.json
Fixes https://github.com/geonetwork/core-geonetwork/issues/7330
> Batch editing / Update xpath spec link

- web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/locales/ca-admin.json
- web-ui/src/main/resources/catalog/locales/cs-admin.json
- web-ui/src/main/resources/catalog/locales/da-admin.json
- web-ui/src/main/resources/catalog/locales/de-admin.json
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/locales/es-admin.json
- web-ui/src/main/resources/catalog/locales/fi-admin.json
- web-ui/src/main/resources/catalog/locales/fr-admin.json
- web-ui/src/main/resources/catalog/locales/is-admin.json
- web-ui/src/main/resources/catalog/locales/it-admin.json
- web-ui/src/main/resources/catalog/locales/ko-admin.json
- web-ui/src/main/resources/catalog/locales/nl-admin.json
- web-ui/src/main/resources/catalog/locales/pt-admin.json
- web-ui/src/main/resources/catalog/locales/ru-admin.json
- web-ui/src/main/resources/catalog/locales/sk-admin.json
- web-ui/src/main/resources/catalog/locales/sv-admin.json
- web-ui/src/main/resources/catalog/locales/zh-admin.json
The setting was removed in #7138
> Remove configuration for the UI setting 'isMenubarAccessible'

- schemas/iso19110/src/main/plugin/iso19110/index-fields/index.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
- schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
- web/src/main/webapp/xslt/common/index-utils.xsl
Follow https://github.com/geonetwork/core-geonetwork/pull/7294
Clarify usage of the function which can return an element or text. Previous usage was sometimes expecting JSON even if not asking for it but `value-of` was skipping the element output.
> Indexing / Do not create empty object if no text

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/eng/labels.xml
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/fre/labels.xml
* Remove non existing element
* More consistent label with JS app label and facet name
> Standard / ISO / Labels improvements

- schemas/iso19110/src/main/plugin/iso19110/index-fields/index.xsl
- web-ui/src/main/resources/catalog/locales/en-v4.json
- web-ui/src/main/resources/catalog/views/default/templates/recordView/technical.html
- web-ui/src/main/resources/catalog/views/default/templates/recordView/type-dataset.html
* Index and display resourceEdition
* Index properly date time
* Set version data as the revision date (so it is displayed in record view)
* Index producer as feature catalog contact and metadata contact
* Record view / Do not display spatial section if no information
* Record view / Fix identifier translation in title attribute
> Standard / ISO19110 improvements

- services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
Related to #7074, to fill information for submitter, reviewer and publisher user
> Send metadata mail notifications for public metadata when is re-approved - fill information for submitter, reviewer and publisher user

- services/src/main/java/org/fao/geonet/api/ApiUtils.java
- services/src/main/java/org/fao/geonet/api/records/MetadataApi.java
- services/src/main/java/org/fao/geonet/api/related/Related.java
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcService.js
- web-ui/src/main/resources/catalog/components/metadataactions/RelatedDirective.js
- web-ui/src/main/resources/catalog/components/metadataactions/RelatedResourcesService.js
- web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
- web-ui/src/main/resources/catalog/components/search/resultsview/gridRelated.js
- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
[BP] Fix working copy display so that links go to working copy data instead of the approved version when using workflow.
Backport of PR #7248 which fixes issue #7247
> [BP] Fix working copy display so that links go to working copy

- .github/workflows/docs.yml
- .github/workflows/linux.yml
- .gitignore
- docs/manual/docs/index.fr.md
- docs/manual/docs/index.md
- docs/manual/mkdocs.yml
See https://github.com/geonetwork/core-geonetwork/pull/7411
> [backport 4.2.x] Add documentation to GitHub workflows

- core/src/main/java/org/fao/geonet/kernel/EditLib.java
- services/src/test/java/org/fao/geonet/services/metadata/BatchEditsServiceTest.java
eg. The following was failing to remove `gco:nilReason` attribute:
```json
{
"field":"XPath_1",
"insertMode":"gn_delete",
"xpath":".//gmd:pointOfContact[gmd:CI_ResponsibleParty/gmd:contactInfo/*/gmd:address/*/gmd:electronicMailAddress/gco:CharacterString = 'copernicus@eea.europa.eu']/@gco:nilReason[. = 'withheld']",
"condition":"",
"value":"",
"isXpath":true}
```
Follow up of https://github.com/geonetwork/core-geonetwork/pull/6423
> API / Batch editing / XPath / Add support for attribute with namespace.

- software_development/BUILDING.md
> Fixed broken links and formatting in BUILDING.md

- web/src/main/webapp/xslt/common/utility-tpl.xsl
Fixed issue reported in https://github.com/metadata101/iso19139.ca.HNAP/issues/360
> Fix url link in full view. bracket ") " could be included in link

- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/views/default/directives/partials/mdactionmenu.html
Fix publish link
Re-apply changes for PR #7009 that was broken when PR #7148 was merged in commit 1021055f2545b44db979bbc2ca613409635b5104
> Fix publish link

- docs/manual/docs/administrator-guide/configuring-the-catalog/inspire-configuration.md
- docs/manual/docs/administrator-guide/configuring-the-catalog/map-server-configuration.md
- docs/manual/docs/administrator-guide/configuring-the-catalog/system-configuration.md
- docs/manual/docs/administrator-guide/managing-classification-systems/managing-categories.md
- docs/manual/docs/administrator-guide/managing-users-and-groups/authentication-mode.md
- docs/manual/docs/annexes/standards/iso19115-3.2018.md
- docs/manual/docs/help/index.md
- docs/manual/docs/install-guide/configuring-database.md
- docs/manual/docs/install-guide/installing-from-source-code.md
- docs/manual/docs/install-guide/installing-from-war-file.md
- docs/manual/docs/overview/change-log/version-3.0.1.md
- docs/manual/docs/overview/change-log/version-3.2.0.md
- docs/manual/docs/overview/change-log/version-4.2.0.md
- docs/manual/docs/overview/index.md
- docs/manual/docs/tutorials/inspire/download-atom.md
- docs/manual/docs/tutorials/inspire/download-geoserver.md
- docs/manual/docs/tutorials/inspire/index.md
- docs/manual/docs/tutorials/inspire/view-geoserver.md
- docs/manual/docs/tutorials/inspire/view-mapserver.md
- docs/manual/docs/user-guide/associating-resources/linking-online-resources.md
- docs/manual/docs/user-guide/describing-information/index.md
- docs/manual/docs/user-guide/describing-information/inspire-editing.md
- docs/manual/docs/user-guide/harvesting/index.md
- docs/manual/docs/user-guide/workflow/batchupdate-from-admin.md
* Absolute links to user manual were replaced with relative links between pages
* Links to external tools were updated from http to https (except for http://www.jasypt.org/)
* Where appropriate information associated with the links was updated (Oracle JDK availability, Apache and Jetty compatibility)
* Only markdown links were updated, xsd use of xlink https://inspire.ec.europa.eu remains unchanged
This has been tested with mkdocs locally to ensure the new relative links function.
> Check http links in documentation

- pom.xml
- web/src/main/resources/jolokia-access.xml
- web/src/main/webapp/WEB-INF/config-security/config-security-core.xml
Avoid authenticated user to access more info than needed.
> Security / Jolokia update.

- docs/manual/docs/overview/change-log/latest/index.md
- docs/manual/docs/overview/change-log/stable/index.md
- docs/manual/docs/overview/change-log/version-4.2.7.md
- docs/manual/docs/overview/change-log/version-4.4.1.md
- docs/manual/mkdocs.yml
> Changelog / 441 and 427.

- web-ui/src/main/resources/catalog/views/default/templates/recordView/categories.html
> Record view / Topic category / Translations

- .github/PULL_REQUEST_TEMPLATE.md
As discussed in last PSC meeting, invite contributor to inform about supporting organizations.
Approach similar to QGIS (https://github.com/qgis/QGIS/blob/0dcbea8674ee7196989c36a99f8b507e878db73b/.github/workflows/pr-needs-documentation.yml#L42-L70) which also add those information in the changelog
> Github / PR template / Add funded by

- web-ui/src/main/resources/catalog/components/common/openlayers/olMapDirective.js
- web-ui/src/main/resources/catalog/views/default/templates/recordView/type-series.html
> Update files with Prettier formatting

- .github/workflows/linux.yml
- pom.xml
- release/README.md
- release/build.xml
- release/pom.xml
- web/pom.xml
Backport of https://github.com/geonetwork/core-geonetwork/pull/7619 for 3.12.x branch
> 3.12.x build stability for -Drelease QA testing

- .github/workflows/backport.yml
- software_development/GITHUB.md
The project makes use of backport tags, but relies on manual cherry picking of commits to prior branches, which can cause problems when branches have diverged. This PR automates the task of doing that cherry-pick, creating a PR of the result if it can be cleanly done. 
Uses [backport.yml](https://github.com/m-kuhn/backport):
> Backport is a JavaScript GitHub Action to backport a pull request by simply adding a label to it.
> 
> It can backport rebased and merged pull requests with a single commit and squashed and merged pull requests. 
Combined with our QA checks this should provide less hands-on work for our developer team.
> backport workflow to respond to PR tags

- CONTRIBUTING.md
> [Backport 4.2.x] document `backport 4.2.x`

- .github/workflows/sonarcloud.yml
> [Backport 4.2.x] Bump actions/cache from 3 to 4

- services/src/main/java/org/fao/geonet/api/records/model/Direction.java
Move Direction as an reference object in the open api specification.
> Move Direction as an reference object in the open api specification.

- services/src/main/java/org/fao/geonet/api/records/model/Direction.java
> [Backport 4.2.x] Move Direction as a reference object in the open api specification.

- domain/src/main/java/org/fao/geonet/domain/MetadataStatus.java
- services/src/main/java/org/fao/geonet/api/records/model/related/RelatedResponse.java
> [Backport 4.2.x] Miscellaneous code cleanup with MetadataStatus and RelatedResponse

- docs/manual/docs/overview/change-log/latest/index.md
- docs/manual/docs/overview/change-log/version-4.4.2.md
- docs/manual/mkdocs.yml
> Change log for version 4.4.2

- .github/workflows/codeql-analysis.yml
> [Backport 4.2.x] Bump github/codeql-action from 2 to 3

- docs/manual/mkdocs.yml
Update copyright year to 2024.
> Docs / Update copyright year

- docs/manual/mkdocs.yml
> [Backport 3.12.x] Docs / Update copyright year

- docs/manual/mkdocs.yml
> [Backport 4.2.x] Docs / Update copyright year

- docs/manual/docs/maintainer-guide/updating/index.md
> [Backport 4.2.x] accidental localhost link in docs

- services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java
> [Backport 4.2.x] Fix MIME-types on attachments as some were incorrect

- services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java
> [Backport 3.12.x] Fix MIME-types on attachments as some were incorrect

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
> [Backport 4.2.x] Metadata editor / Fix javascript error when editing a metadata

- web/src/main/webapp/xslt/ui-metadata/edit/edit-embedded.xsl
Follow up of https://github.com/geonetwork/core-geonetwork/pull/7591#issuecomment-1910496386
Fix form content when adding 
* a resource maintenance and then User defined maintenance frequency
* or temporal resolution in ISO19115-3
> Editor / Fix add element attribute

- web/src/main/webapp/xslt/skin/default/skin.xsl
> [Backport 3.12.x] Fix pdf link issue

- services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java
- services/src/main/java/org/fao/geonet/api/registries/vocabularies/KeywordsApi.java
> [Backport 4.2.x] Fix spring doc for attachment and keyword to better identify files resources being returned.

- services/src/main/java/org/fao/geonet/api/OpenApiConfig.java
> [Backport 4.2.x] Update Springdoc so that it supports Map objects in the request parameters.

- core/pom.xml
- pom.xml
- services/pom.xml
- web/pom.xml
> [Backport 4.2.x] Bump commons-fileupload from 1.3.3 to 1.5

- core/pom.xml
- pom.xml
- services/pom.xml
- web/pom.xml
> [Backport 3.12.x] Bump commons-fileupload from 1.3.3 to 1.5

- docs/manual/docs/customizing-application/adding-static-pages.md
- docs/manual/docs/customizing-application/configuring-search-fields.md
- docs/manual/docs/customizing-application/editor-ui/creating-custom-editor.md
Backport #7696
**Authored by:** @archaeogeek
> [Backport 4.2.x] Addressing docs translation glitch #7687- fixes adding-static-pages and configuring-search-fields

- docs/manual/docs/administrator-guide/managing-users-and-groups/index.md
Backport #7686
**Authored by:** @MichelGabriel
> [Backport 4.2.x] Add a role and feature matrix to the GeoNetwork documentation

- csw-server/src/main/java/org/fao/geonet/csw/common/requests/CatalogRequest.java
Same as https://github.com/geonetwork/core-geonetwork/pull/5497 which was missing in main.
Fix harvester with basic auth.
> CSW / Enable preemptive for csw requests with credentials (#5497)

- .github/workflows/linux.yml
> [Backport 4.2.x] Bump stCarolas/setup-maven from 4 to 5

- common/pom.xml
- pom.xml
- web-ui/src/main/resources/catalog/components/metadatamanager/EditorService.js
> [Backport 4.2.x] Bump org.json:json from 20140107 to 20240205

- common/pom.xml
- pom.xml
> [Backport 3.12.x] Bump org.json:json from 20140107 to 20240205

- pom.xml
- web-ui/pom.xml
> [Backport 3.12.x] Remove unused jslint-maven-plugin

- pom.xml
- web-ui/pom.xml
> [Backport 4.2.x] Remove unused jslint-maven-plugin

- core/src/main/java/org/fao/geonet/kernel/mef/Importer.java
Test case:
1) Load ISO19139 samples
2) Export to ZIP the sample `Hydrological Basins in Africa (Sample record, please remove!)`
3) Import the MEF (ZIP) file with the option `Generate UUID for inserted metadata`
- Without the change: the metadata gets a new UUID, but the resource URL uses the original metadata UUID (NO OK)
- With the change: the metadata gets a new UUID and the resource URL uses the new UUID value.
Used analog code as when duplicating a metadata in https://github.com/geonetwork/core-geonetwork/blob/1eb773cc132281b62ffeb99f8975fa03cc9b9395/core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java#L472-L480
---
Sonarlint improvements applied also.
> Use the generated metadata UUID for resource links when importing metadata with the option 'Generate UUID'

- core/src/main/java/org/fao/geonet/kernel/mef/Importer.java
> [Backport 4.2.x] Use the generated metadata UUID for resource links when importing metadata with the option 'Generate UUID'

- services/src/main/java/org/fao/geonet/api/es/EsHTTPProxy.java
> [Backport 4.2.x] Separate docs for _search and _msearch

- web/src/main/webapp/xslt/ui-metadata/edit/edit.xsl
This can facilitate customization of the style of the editor.
Previously only the tab identifier was provided making more difficult to define global editor styles common for all tabs and was not providing simple way to customize the side panel.
> Editor / Add view name class to facilitate custom styling

- docs/manual/docs/customizing-application/configuring-search-fields.md
- web/src/main/webResources/WEB-INF/data/config/index/records.json
Backport https://github.com/geonetwork/core-geonetwork/pull/7697
> [Backport 4.2.x] Index / Add danish language.

- core/src/main/java/org/fao/geonet/kernel/mef/Importer.java
Backport https://github.com/geonetwork/core-geonetwork/pull/7714
> [Backport 3.12.x] Use the generated metadata UUID for resource links when importing metadata with the option 'Generate UUID'

- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataOperations.java
> [Backport 4.2.x] Create a metadata / Add dynamic and download privileges to the users in the same group

- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataOperations.java
> [Backport 3.12.x] Create a metadata / Add dynamic and download privileges to the users in the same group

- docs/manual/docs/customizing-application/search-ui/enrichview.md
- docs/manual/docs/customizing-application/search-ui/loadview.md
- docs/manual/docs/install-guide/configuring-database.md
- docs/manual/docs/install-guide/map-print-setup.md
- docs/manual/docs/user-guide/publishing/managing-privileges.md
To address https://github.com/geonetwork/core-geonetwork/issues/7666
> Addressing docs-glitches in remaining files

- docs/manual/docs/administrator-guide/managing-users-and-groups/authentication-mode.md
- docs/manual/docs/administrator-guide/managing-users-and-groups/creating-group.md
- docs/manual/docs/customizing-application/search-ui/enrichview.md
- docs/manual/docs/customizing-application/search-ui/loadview.md
- docs/manual/docs/install-guide/configuring-database.md
- docs/manual/docs/install-guide/installing-from-war-file.md
- docs/manual/docs/install-guide/map-print-setup.md
- docs/manual/docs/overview/change-log/version-4.0.2.md
- docs/manual/docs/tutorials/introduction/deployment/index.md
- docs/manual/docs/user-guide/publishing/managing-privileges.md
> [Backport 4.2.x] Address remaining two-character literal doc translation glitch

- docs/manual/docs/administrator-guide/configuring-the-catalog/csw-configuration.md
- docs/manual/docs/administrator-guide/configuring-the-catalog/inspire-configuration.md
- docs/manual/docs/administrator-guide/managing-users-and-groups/authentication-mode.md
- docs/manual/docs/administrator-guide/managing-users-and-groups/creating-group.md
- docs/manual/docs/customizing-application/search-ui/enrichview.md
- docs/manual/docs/customizing-application/search-ui/loadview.md
- docs/manual/docs/install-guide/configuring-database.md
- docs/manual/docs/install-guide/map-print-setup.md
- docs/manual/docs/tutorials/introduction/deployment/index.md
- docs/manual/docs/user-guide/publishing/managing-privileges.md
- docs/manual/docs/user-guide/workflow/life-cycle.md
- docs/manual/mkdocs.yml
Backport fixes for https://github.com/geonetwork/core-geonetwork/issues/7666 to the 3.12.x branch.
I had to cherry-pick these from a number of pull-requests due to some disorganization / communication challenges (sorry!)
> [Backport 3.12.x] Backport doc-glitch fixes to 3.12.x branch 

- core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
- core/src/main/java/org/fao/geonet/kernel/search/index/OverviewIndexFieldUpdater.java
Error was Validation Failed: 1: script or doc is missing.
Related to ES8 migration https://github.com/geonetwork/core-geonetwork/pull/7599
> API / Category / Fix update fields

- web-ui/src/main/resources/catalog/js/admin/ReportController.js
> [Backport 4.2.x] Reports / Fix extract user groups for non-admin users

- schemas/iso19139/src/main/plugin/iso19139/loc/ger/labels.xml
> [Backport 4.2.x] Fix ISO19139 German labels

- web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html
> [Backport 4.2.x] Fix HTML syntax in users.html

- web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html
> [Backport 3.12.x] Fix HTML syntax in users.html

- services/src/main/java/org/fao/geonet/api/sources/SourcesApi.java
Fix duplicate GET operation on /{portal}/api/sources
There are 2 GET operation on /{portal}/api/sources with the following titles.
"Get all sources"  
"Get portal list"  - This seems to be the one that is missing the mapping. So I added the mapping "/subportal" and this will create a new api endpoint "/{portal}/api/sources/subportal"
I'm not sure how this was working with these duplicates GET operations on the same endpoint?  
I did find the following reference in the code.
https://github.com/geonetwork/core-geonetwork/blob/68cb69aaac8f394818323fb1144e2a7baf4e75f0/web-ui/src/main/resources/catalog/js/admin/CSWTestController.js#L53
This seems to indicate that it was expecting the endpoint to be /subportal because I cannot find any other reference.
So this fix was to add the missing …
> Fix duplicate GET operation on /{portal}/api/sources and missing /subportal endpoint

- services/src/main/java/org/fao/geonet/api/records/MetadataApi.java
- services/src/test/java/org/fao/geonet/api/records/MetadataApiTest.java
> [Backport 4.2.x] Spit getRecordAs @RequestMapping into getRecordAsJson and getRecordAsXML in order to fix duplicate operation Id

- services/src/main/java/org/fao/geonet/api/sources/SourcesApi.java
> [Backport 4.2.x] Fix duplicate GET operation on /{portal}/api/sources and missing /subportal endpoint

- services/src/main/java/org/fao/geonet/api/records/model/related/FCRelatedMetadataItem.java
- services/src/main/java/org/fao/geonet/api/records/model/related/RelatedResponse.java
- services/src/main/java/org/fao/geonet/api/records/model/validation/Report.java
> [Backport 4.2.x] Fix SpringDoc duplicate Schema name

- services/src/main/java/org/fao/geonet/api/records/model/MetadataStatusDto.java
- services/src/main/java/org/fao/geonet/api/records/model/MetadataStatusResponse.java
- services/src/main/java/org/fao/geonet/api/records/model/MetadataWorkflowStatusResponse.java
Fix missing MetadataStatusResponse and MetadataWorkflowStatusResponse in  open api spec
The reason the response was missing was because MetadataStatusResponse was extending MetadataStatus which contains a bunch of objects that caused issues with spring docs. This fix removes the extends and moves the required fields into MetadataStatusResponse
After this fix there will be a new component in the open api spec
```
MetadataWorkflowStatusResponse:
type: object
example: null
properties:
currentStatus:
$ref: '#/components/schemas/MetadataStatusResponse'
hasEditPermission:
type: boolean
example: null
reviewers:
type: array
example: null
items:
$ref: '#/components/schemas/User'
status:
type: array
example: null
items:
$ref: '#/components/schemas/StatusValue'
```
> Fix missing MetadataStatusResponse and MetadataWorkflowStatusResponse in  open api spec

- schemas/iso19139/src/main/plugin/iso19139/loc/ger/labels.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/ger/strings.xml
> Additional ISO19139 German translations

- schemas/iso19139/src/main/plugin/iso19139/loc/ger/labels.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/ger/strings.xml
> [Backport 4.2.x] Additional ISO19139 German translations

- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
> [Backport 4.2.x] Record view / Don't add the associated resources in the metadata static page, this page doesn't include JS libs

- docs/manual/docs/customizing-application/editor-ui/creating-custom-editor.md
> Docs custom editor minor typo fixes

- .gitignore
- es/README.md
- es/docker-compose.yml
Follow up of #7599
Updated the docker compose in `es` module to use Elasticsearch and Kibana 8 for development.
> Update docker compose in es module to Elasticsearch 8

- es/README.md
Follow up of #7817 to improve the `README.md` instructions.
> Improve Elasticsearch manual installation to disable security for development

- schemas/config-editor.xsd
Doc improvements based on feedback https://github.com/geonetwork/core-geonetwork/issues/7775
> Doc / Editor configuration improvements

- schemas/config-editor.xsd
> [Backport 4.2.x] Doc / Editor configuration improvements

- schemas/config-editor.xsd
> [Backport 3.12.x] Doc / Editor configuration improvements

- services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
> [Backport 4.2.x] Trigger metadata unpublish event when unpublishing using the privileges dialog

- workers/wfsfeature-harvester/src/main/java/org/fao/geonet/harvester/wfsfeatures/worker/EsWFSFeatureIndexer.java
ES8 BulkIngester takes care of it.
Can be tested with River basin of africa, https://sextant.ifremer.fr/Donnees/Catalogue#/metadata/cf5048f6-5bbf-4e44-ba74-e6f429af51ea
> Harvester / WFS / No need to manually managed commit interval

- web-ui/src/main/resources/catalog/js/admin/HarvestSettingsController.js
> [Backport 4.2.x] Harvesters / Reset harvester history pagination when selecting a harvester

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
- schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
> [Backport 4.2.x] Record view / ISO19139 / ISO19115-3.2008 display the unit part in @uom attribute, not the full url

- common/src/main/java/org/fao/geonet/Logger.java
- common/src/main/java/org/fao/geonet/utils/Log.java
- core/src/main/java/jeeves/server/context/BasicContext.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/BaseAligner.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFilesystemHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFsHarvesterFileVisitor.java
- web-ui/src/main/resources/catalog/components/admin/harvester/partials/privileges.html
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v3110/UpdateMetadataStatus.java
> [Backport 4.2.x] Harvester / Localfilesystem / Log properly to harvester log file.

- web/src/main/webapp/WEB-INF/config-etf-validator.xml
- web/src/main/webapp/xslt/services/thesaurus/registry-to-skos.xsl
Required for datasets in the context of https://inspire.ec.europa.eu/metadata-codelist/IACSData
> INSPIRE / Add testsuite for IACS

- web/src/main/webapp/WEB-INF/config-etf-validator.xml
- web/src/main/webapp/xslt/services/thesaurus/registry-to-skos.xsl
> [Backport 4.2.x] INSPIRE / Add testsuite for IACS

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/citation/base.xsl
- schemas/iso19139/src/main/plugin/iso19139/formatter/citation/base.xsl
> [Backport 4.2.x] Standards / Formatter / Citation / Pick latest date

- web-ui/src/main/resources/catalog/js/admin/HarvestSettingsController.js
Backport https://github.com/geonetwork/core-geonetwork/pull/7765
> [Backport 3.12.x] Harvesters / Reset harvester history pagination when selecting a harvester

- web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
- web/src/main/webapp/xslt/ui-metadata/form-configurator.xsl
Similar to process or suggest button.
```xml
<tab id="sextant-associated-resources">
<section>
<action type="associatedResource"
name="sextant-linkToPlatform"
btnClass="fa fa-ship"
process="siblings">
<directiveAttributes>{"fields": {"associationType": "crossReference", "initiativeType": "platform" },
"sources": {"doiapi": {"url": "https://api.datacite.org/dois",
"params": {"prefix": "10.17600", "query": "titles.title:{query}"}}
}}</directiveAttributes>
</action>
<action type="associatedResource"
name="sextant-linkToStudy"
btnClass="fa fa-book"
process="siblings">
<directiveAttributes>{"fields": { "associationType": "crossReference", "initiativeType": "study" },
"sources": {"doiapi": {"url": "https://api.datacite.org/dois",
"params": {"prefix": "", "query": "titles.title:{query}"}}, …
```
> Editor / Associated resource / Add button icon configuration.

- workers/wfsfeature-harvester/src/main/java/org/fao/geonet/harvester/wfsfeatures/worker/EsWFSFeatureIndexer.java
Example harvesting OGC service https://sextant.ifremer.fr/services/wms/environnement_marin and indexing feature type surval_parametre_polygone.
491 features are reported to be indexed in the UI and the following WARNING appear during harvesting:
```
2024-01-15T15:40:10,400 WARN  [geonetwork.harvest.wfs.features] - Feature ms:surval_parametre_polygone#521/id:surval_parametre_polygone.60007755: Cannot apply precision reducer on invalid geometry. Check the geometry validity. The feature will be indexed but with no geometry.
```
The feature with invalid geometry are indexed but without other attributes (because geometry is first attribute to be parsed and the break move to next feature). Use continue to parse other feature attributes (which will have an empty geometry but will be reported in …
> Harvesting / WFS Features / Do not skip attributes even if geom is invalid

- docs/manual/docs/contributing/doing-a-release.md
GeoNetwork 4.2 release page updates.
> Documentation / GeoNetwork 4.2 doing a release fixes

- docs/manual/docs/contributing/doing-a-release.md
GeoNetwork 3.12 release page updates.
> Documentation / GeoNetwork 3.12 doing a release fixes

- docs/changes/changes3.12.12-0.txt
- docs/changes/changes4.2.9-0.txt
- docs/manual/docs/overview/change-log/archive/index.md
- docs/manual/docs/overview/change-log/latest/index.md
- docs/manual/docs/overview/change-log/maintenance/index.md
- docs/manual/docs/overview/change-log/stable/index.md
- docs/manual/docs/overview/change-log/version-3.12.12.md
- docs/manual/docs/overview/change-log/version-4.2.9.md
- docs/manual/docs/overview/change-log/version-4.4.3.md
- docs/manual/mkdocs.yml
> Release notes for GeoNetwork 4.4.3.

- docs/changes/changes3.12.12-0.txt
- docs/changes/changes4.2.9-0.txt
- docs/manual/docs/overview/change-log/archive/index.md
- docs/manual/docs/overview/change-log/maintenance/index.md
- docs/manual/docs/overview/change-log/stable/index.md
- docs/manual/docs/overview/change-log/version-3.12.12.md
- docs/manual/docs/overview/change-log/version-4.2.9.md
- docs/manual/mkdocs.yml
> Release notes for GeoNetwork 4.2.9 / 3.12.12 versions (4.2.x branch)

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
- schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
> [Backport 4.2.x] ISO19139 / Index online resources application profile element encoded as anchor

- core/src/main/java/org/fao/geonet/kernel/security/openidconnect/bearer/UserInfoCache.java
- core/src/test/java/org/fao/geonet/kernel/security/openidconnect/bearer/UserInfoCacheTest.java
Backport #7810
**Authored by:** @joachimnielandt
> [Backport 4.2.x] OpenID / Cleaning up cached tokens

- docs/manual/docs/overview/change-log/maintenance/index.md
> [Backport 4.2.x] Fill in 4.2.x releases for maintenance page

- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
Error is
```
java.lang.IllegalArgumentException: 'https://secure.geonames.org/searchJSON?lang=eng&style=full&type=json&maxRows=10&name_startsWith=saint pierre de genebroz&username=georchestra' is invalid. Error is: 'Illegal character in query at index 101: https://secure.geonames.org/searchJSON?lang=eng&style=full&type=json&maxRows=10&name_startsWith=saint pierre de genebroz&username=georchestra'
at org.fao.geonet.proxy.URITemplateProxyServlet.isUrlAllowed (URITemplateProxyServlet.java:491)
at org.fao.geonet.proxy.URITemplateProxyServlet.service (URITemplateProxyServlet.java:402)
at javax.servlet.http.HttpServlet.service (HttpServlet.java:790)
```
Also properly select first location search service if not default defined.
> Editor / GeoNames search failing with space

- core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
- schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
- services/src/main/java/org/fao/geonet/api/records/extent/MapRenderer.java
- web-ui/src/main/resources/catalog/views/default/config.js
- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-functions.xsl
* Handle geom field like other array fields to better support multiple geometries
* Add support for point (if bounding box south=north, west=east)
* Add support for point in extent API - the map background use needs to provide large scale details
* Consistent styling when highlighting point or geom (stroke color was not the same)
> Indexing / Improve geometry indexing and display

- domain/src/main/java/org/fao/geonet/repository/specification/LinkSpecs.java
> [Backport 4.2.x] Optimise query used to retrieve metadata links results

- domain/src/main/java/org/fao/geonet/repository/specification/LinkSpecs.java
> [Backport 3.12.x] Optimise query used to retrieve metadata links results

- schemas/iso19139/src/main/plugin/iso19139/extract-relations.xsl
- schemas/iso19139/src/main/plugin/iso19139/process/onlinesrc-add.xsl
- schemas/iso19139/src/main/plugin/iso19139/process/onlinesrc-remove.xsl
- schemas/iso19139/src/main/plugin/iso19139/process/thumbnail-add.xsl
- schemas/iso19139/src/main/plugin/iso19139/process/thumbnail-remove.xsl
- services/src/main/java/org/fao/geonet/api/records/model/related/RelatedItem.java
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcService.js
@josegar74 @ianwallen 
This is for PR https://github.com/geonetwork/core-geonetwork/pull/7431 which we discussed that we will make PR to 4.2 branch and will continue investigate the issue with the latest main branch.
I have tested this code and it works. You can verify again from your end
> [Backport 4.2.x] Passing key into update/remove process xslt for iso 19139 to fix issue with updating/deleting resources with same url

- services/src/main/java/org/fao/geonet/api/userfeedback/UserFeedbackAPI.java
> [Backport 4.2.x] Feedback / Fix email to multiple recipients

- services/src/test/java/org/fao/geonet/api/links/LinksApiTest.java
Related to changes in #7878 to process the links in a thread
> Fix LinksApiTest integration test. 

- web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
Fixed typo in metadata_approved_published_record_text.
> Fix typo in Messages.properties for metadata_approved_published_record_text

- web/src/main/webapp/WEB-INF/classes/log4j2-dev.xml
- web/src/main/webapp/WEB-INF/classes/log4j2-index.xml
- web/src/main/webapp/WEB-INF/classes/log4j2.xml
> [Backport 4.2.x] Configure harvesters log to avoid application log duplicated in harvester_default.log file.

- core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java
> [Backport 4.2.x] Send email notification after workflow events have been processed

- core/src/main/java/org/fao/geonet/kernel/datamanager/IMetadataStatus.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataStatus.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/draft/DraftMetadataUtils.java
- core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java
- core/src/main/java/org/fao/geonet/kernel/metadata/StatusActions.java
- listeners/src/main/java/org/fao/geonet/listener/metadata/draft/ApprovePublishedRecord.java
- listeners/src/main/java/org/fao/geonet/listener/metadata/draft/ApproveRecord.java
- services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
- services/src/main/java/org/fao/geonet/api/records/editing/MetadataEditingApi.java
> [Backport 4.2.x] Fix issue with saving metadata status causes indexing of metadata which causes issues for db rollbacks

- pom.xml
- services/src/main/java/org/fao/geonet/api/OpenApiController.java
Backport https://github.com/geonetwork/core-geonetwork/pull/7596
> [Backport 4.2.x] Upgrade springdoc to 1.7.0 (#7596)

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/config-editor.xml
> [Backport 4.2.x] Standard / ISO19115-3 / Use anchor encoding for IACS keywords

- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
> [Backport 4.2.x] Search / May fail with random_score depending on ES config

- domain/src/main/java/org/fao/geonet/repository/MetadataValidationRepositoryCustom.java
> [Backport 4.2.x] API / Import does not overwrite metadata if any validation status

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout.xsl
> [Backport 4.2.x] Standard / ISO19115-3 / Editor / Uom encoding support

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/UriMapper.java
> [Backport 3.12.x] Fix harvester URIMapper to handle local metadata

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/UriMapper.java
> [Backport 4.2.x] Fix harvester URIMapper to handle local metadata

- docs/manual/docs/overview/change-log/version-3.0.0.md
- docs/manual/docs/overview/change-log/version-3.4.1.md
- docs/manual/docs/user-guide/harvesting/harvesting-geonetwork.md
- docs/manual/docs/user-guide/workflow/batchediting.md
- docs/manual/docs/user-guide/workflow/batchupdate-from-admin.md
- docs/manual/docs/user-guide/workflow/batchupdate-xsl.md
- docs/manual/docs/user-guide/workflow/batchupdate.md
- docs/manual/docs/user-guide/workflow/batchupdate/index.md
- docs/manual/docs/user-guide/workflow/index.md
- docs/manual/mkdocs.yml
Addresses some of the pages reported #7766, please see that ticket for context.
Funded by GeoCat on behalf of GeoCat Live.
> Update revise use of empty or mostly empty pages

- docs/manual/docs/overview/change-log/version-3.0.0.md
- docs/manual/docs/overview/change-log/version-3.4.1.md
- docs/manual/docs/user-guide/harvesting/harvesting-geonetwork.md
- docs/manual/docs/user-guide/workflow/batchediting.md
- docs/manual/docs/user-guide/workflow/batchupdate-from-admin.md
- docs/manual/docs/user-guide/workflow/batchupdate-xsl.md
- docs/manual/docs/user-guide/workflow/batchupdate.md
- docs/manual/docs/user-guide/workflow/batchupdate/index.md
- docs/manual/docs/user-guide/workflow/index.md
- docs/manual/mkdocs.yml
> [Backport 4.2.x] Update revise use of empty or mostly empty pages

- schemas/iso19139/src/main/plugin/iso19139/extract-relations.xsl
- schemas/iso19139/src/main/plugin/iso19139/process/onlinesrc-add.xsl
- schemas/iso19139/src/main/plugin/iso19139/process/onlinesrc-remove.xsl
- schemas/iso19139/src/main/plugin/iso19139/process/thumbnail-add.xsl
- schemas/iso19139/src/main/plugin/iso19139/process/thumbnail-remove.xsl
- services/src/main/java/org/fao/geonet/api/records/model/related/RelatedItem.java
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcService.js
This is for backporting the change in this pull request https://github.com/geonetwork/core-geonetwork/pull/7740
> [Backport 3.12.x] Passing key into update/remove process xslt for iso 19139 to fix issue with updating/deleting resources with same url

- schemas/config-editor.xsd
Related to https://github.com/geonetwork/core-geonetwork/issues/7941
> Doc / Editor configuration / Subtemplate insert mode

- pom.xml
- Spring Framework: 5.3.33
- Spring Security: 5.8.11
> GeoNetwork 4.4.x minor versions library updates

- schemas/config-editor.xsd
> [Backport 4.2.x] Doc / Editor configuration / Subtemplate insert mode

- web/src/main/webResources/WEB-INF/urlrewrite.xml
- web/src/main/webapp/xslt/services/inspire-atom/opensearch.xsl
- web/src/main/webapp/xslt/services/inspire-atom/opensearchdescription.xsl
Backport https://github.com/geonetwork/core-geonetwork/pull/7565
> [Backport 4.2.x] INSPIRE Atom feeds / Fix link to atom search endpoint

- web-ui/src/main/resources/catalog/components/elasticsearch/EsFacet.js
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/editor.html
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/locales/ca-core.json
- web-ui/src/main/resources/catalog/locales/cs-core.json
- web-ui/src/main/resources/catalog/locales/da-core.json
- web-ui/src/main/resources/catalog/locales/de-core.json
- web-ui/src/main/resources/catalog/locales/en-core.json
- web-ui/src/main/resources/catalog/locales/es-core.json
- web-ui/src/main/resources/catalog/locales/fi-core.json
- web-ui/src/main/resources/catalog/locales/fr-core.json
- web-ui/src/main/resources/catalog/locales/is-core.json
- web-ui/src/main/resources/catalog/locales/it-core.json
- web-ui/src/main/resources/catalog/locales/ko-core.json
- web-ui/src/main/resources/catalog/locales/nl-core.json
- web-ui/src/main/resources/catalog/locales/pt-core.json
- web-ui/src/main/resources/catalog/locales/ru-core.json
- web-ui/src/main/resources/catalog/locales/sk-core.json
- web-ui/src/main/resources/catalog/locales/sv-core.json
- web-ui/src/main/resources/catalog/locales/zh-core.json
Backport https://github.com/geonetwork/core-geonetwork/pull/7910
> [Backport 4.2.x] Editor board / Use metadata database change date instead of the metadata dateStamp (xml)

- csw-server/src/main/java/org/fao/geonet/component/csw/GetRecordById.java
- csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/SearchController.java
Backport https://github.com/geonetwork/core-geonetwork/pull/7890
> [Backport 4.2.x] CSW server / Use portal filter in GetRecordById requests

- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
Backport https://github.com/geonetwork/core-geonetwork/pull/7881
> [Backport 4.2.x] Editor / GeoNames search failing with space

- web-ui/src/main/resources/catalog/js/edit/BatchEditController.js
- web-ui/src/main/resources/catalog/js/edit/EditorBoardController.js
> [Backport 4.2.x] Update the default sort field name in editor board and batch editor.

- web/src/main/webResources/WEB-INF/web.xml
> [Backport 4.2.x] Remove unused JeevesDelegatingFilterProxy servlet parameter 'loginService' configuration

- web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties
This is the French translation part for PR https://github.com/geonetwork/core-geonetwork/pull/7892
> French translation update for metadata_approved_published_record_text

- services/src/main/java/org/fao/geonet/api/reports/ReportUsers.java
> [Backport 4.2.x] Report users - Display profile for Administrator / Guest profiles that are not related to groups

- web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties
> [Backport 4.2.x] French translation update for metadata_approved_published_record_text

- csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/SearchController.java
Backport https://github.com/geonetwork/core-geonetwork/pull/7977
> [Backport 4.2.x] fix for nextrecord in csw getrecord response when using pagination

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/citation/common.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/citation/view.xsl
- schemas/iso19139/src/main/plugin/iso19139/formatter/citation/view.xsl
- web-ui/src/main/resources/catalog/components/viewer/wps/WpsDirective.js
Related to https://github.com/geonetwork/core-geonetwork/pull/7929.
> Test / Fix formatter test.

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/update-fixed-info.xsl
Element visibility can also be configured in https://github.com/geonetwork/core-geonetwork/blob/main/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/schema-ident.xml#L129-L163
> Standards / ISO19115-3 / Cleanup project specific template

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/ISO19139/utility/create19115-3Namespaces.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/config-editor.xml
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/evaluate.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout-custom-fields.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout.xsl
Also remove gts namespace which is ISO19139.
Test:
* Create an ISO19115-3 record
* Add `xmlns:dqm="http://standards.iso.org/iso/19157/-2/dqm/1.0" ` in child element
* Save - namespace should be only in `MD_Metadata`
> Standard / ISO19115-3 / Ensure dqm namespace is on top of the document

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/update-fixed-info.xsl
> [Backport 4.2.x] Standards / ISO19115-3 / Cleanup project specific template

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/evaluate.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/fre/labels.xml
> [Backport 4.2.x] Standard / ISO19115-3 / Feature catalogue improvements

- core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
- schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
- services/src/main/java/org/fao/geonet/api/records/extent/MapRenderer.java
- web-ui/src/main/resources/catalog/views/default/config.js
- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-functions.xsl
Backport https://github.com/geonetwork/core-geonetwork/pull/7882
> [Backport 4.2.x] Indexing / Improve geometry indexing and display

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
- schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
- web-ui/src/main/resources/catalog/locales/en-core.json
- web-ui/src/main/resources/catalog/views/default/templates/recordView/metadata.html
- web-ui/src/main/resources/catalog/views/default/templates/recordView/technical.html
> [Backport 4.2.x] Record view / Add service type info and metadata standard name

- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
Backport of https://github.com/geonetwork/core-geonetwork/pull/8003
> [Backport 4.2.x] ISO19139 metadata full view / display citation titles

- web-ui/src/main/resources/catalog/views/default/module.js
> Search tab map is blank on first page load. 

- web-ui/src/main/resources/catalog/components/common/map/mapService.js
Fixes #8025
Without the fix:
With the fix:
> Map viewer / ESRIREST layers / Scale the layer extent to show the symbology of the features in the corners of the extent.

- web-ui/src/main/resources/catalog/views/default/module.js
> [Backport 4.2.x] Search tab map is blank on first page load. 

- web-ui/src/main/resources/catalog/components/common/map/mapService.js
> [Backport 4.2.x] Map viewer / ESRIREST layers / Scale the layer extent to show the symbology of the features in the corners of the extent.

- core/src/main/java/org/fao/geonet/util/MailUtil.java
Avoid displaying mail server configuration and other detailed information in the log.
```
DEBUG: JavaMail version 1.5.6
DEBUG: successfully loaded resource: /META-INF/javamail.default.providers
DEBUG: Tables of loaded providers
...
```
> Mail / Log / Remove debug level

- core/src/test/resources/org/fao/geonet/api/Messages.properties
- core/src/test/resources/org/fao/geonet/api/Messages_fre.properties
- web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
- web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties
> [Backport 4.2.x] Synchronize Messages.properties from web and test

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
> [Backport 4.2.x] Standard / ISO19115-3 / Avoid indexing error on multilingual feature catalogue

- web-ui/src/main/resources/catalog/js/CatController.js
> [Backport 4.2.x] Editor / Map / Use main context to have a better default on new extent

- web-ui/src/main/resources/catalog/views/default/directives/directive.js
> [Backport 4.2.x] Record view / Fix JS error related to publication options display.

- web-ui/src/main/resources/catalog/views/default/less/gn_search_default.less
> [Backport 4.2.x] search menu size

- web-ui/src/main/resources/catalog/js/admin/UserGroupController.js
> [Backport 4.2.x] Users / reset form status when creating a user

- web-ui/src/main/resources/catalog/components/common/map/mapService.js
- web-ui/src/main/resources/catalog/components/utility/CORSInterceptor.js
- web-ui/src/main/resources/catalog/components/viewer/wmsimport/WmsImportDirective.js
> [Backport 4.2.x] WMS GetMap HEAD request error response - check response status defined

- web-ui/src/main/resources/catalog/components/viewer/ViewerDirective.js
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/locales/en-v4.json
- web-ui/src/main/resources/catalog/views/default/less/gn_map_default.less
> [Backport 4.2.x] Map / Add scale.

- web/src/main/java/org/fao/geonet/proxy/URITemplateProxyServlet.java
> HTTP proxy servlet / update error messages

- web/src/main/java/org/fao/geonet/proxy/URITemplateProxyServlet.java
> [Backport 4.2.x] HTTP proxy servlet / update error messages

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl
- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
> [Backport 4.2.x] Record view / ISO19139 / ISO19115-3.2008 display the unit part in @uom attribute - avoid duplicated value

- docs/manual/docs/user-guide/associating-resources/doi.md
> [Backport 4.2.x] Documentation / Add information about the type of users that can request a DOI

- core/src/main/java/org/fao/geonet/util/XslUtil.java
- web-ui/src/main/resources/catalog/components/metadatamanager/EditorService.js
refer to issue https://github.com/geonetwork/core-geonetwork/issues/8059
> Be able to edit metadata when backend store is not available

- core/src/main/java/org/fao/geonet/util/XslUtil.java
- web-ui/src/main/resources/catalog/components/metadatamanager/EditorService.js
> [Backport 4.2.x] Be able to edit metadata when backend store is not available

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
- schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
- web-ui/src/main/resources/catalog/components/search/mdview/mdviewDirective.js
> [Backport 4.2.x] Indexing / ISO / Properly index all keywords even if in different thesaurus block

- web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionsDirective.js
> [Backport 4.2.x] Editor / Group owner change / Fix label on error

- services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
> [Backport 4.2.x] Editor / Groupowner change error

- docs/manual/docs/administrator-guide/managing-metadata-standards/configure-validation.md
> [Backport 4.2.x] Remove link from admin-guide to schematron details as inappropriate

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
Fixes https://github.com/geonetwork/core-geonetwork/issues/8112
Then we can discuss if we want to support multiple websites for contact and how to display them.
> Indexing / ISO19115-3 / Avoir error on multiple contact website

- web-ui/src/main/resources/catalog/components/common/map/mapService.js
- web-ui/src/main/resources/catalog/components/search/formfields/FormFieldsDirective.js
- web-ui/src/main/resources/catalog/components/viewer/ViewerDirective.js
- web-ui/src/main/resources/catalog/components/viewer/wps/partials/recentprocesses.html
- web-ui/src/main/resources/catalog/locales/en-search.json
Display message instead of an empty panel
Follow up of https://github.com/geonetwork/core-geonetwork/pull/7842
Also fix wps type for URL tab.
> Map / WPS / Add message for no recent process.

- web-ui/src/main/resources/catalog/templates/admin/harvest/type/arcsde.js
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/geoPREST.js
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/geonetwork20.js
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/oaipmh.js
> [Backport 4.2.x] Harvesters / remove unused groupsCopyPolicy property

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
> [Backport 4.2.x] Indexing / ISO19115-3 / Avoir error on multiple contact website

- docs/manual/docs/administrator-guide/configuring-the-catalog/portal-configuration.md
Add example for Keyword filtering for Sub Portal configuration.
> Update portal-configuration.md - Keyword filtering example

- core/src/test/resources/org/fao/geonet/api/Messages.properties
- core/src/test/resources/org/fao/geonet/api/Messages_fre.properties
- doi/src/main/java/org/fao/geonet/doi/client/BaseDoiClient.java
- doi/src/main/java/org/fao/geonet/doi/client/DoiDataciteClient.java
- doi/src/main/java/org/fao/geonet/doi/client/DoiManager.java
- doi/src/main/java/org/fao/geonet/doi/client/DoiMedraClient.java
- web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
- web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties
> [Backport 4.2.x] Update DOI exceptions to be multilingual exceptions

- services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
> [Backport 4.2.x] update last changed date when restore metadata

- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/list.html
- web-ui/src/main/resources/catalog/style/gn.less
- web-ui/src/main/resources/catalog/views/default/less/gn_card_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_results_default.less
When viewing search results in list view there are issues with the display of category icons.
Icons are hidden by the record's status label covering them.
Some icons are using white as their color resulting in the icons blending in the with backgrounds until they are hovered where the background color changes. These icons also have spacing inconsistent with the rest of the icons.
This PR aims to fix these issues by:
- Changing the status label from absolute position to a flex element in the footer
- Changing the color and display of icons to be consistent
These changes result in the following:
> Fix issues with category icons in search results list view

- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/list.html
- web-ui/src/main/resources/catalog/style/gn.less
- web-ui/src/main/resources/catalog/views/default/less/gn_card_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_results_default.less
> [Backport 4.2.x] Fix issues with category icons in search results list view

- core/src/main/java/org/fao/geonet/api/records/attachments/AbstractStore.java
- core/src/main/java/org/fao/geonet/api/records/attachments/CMISStore.java
- core/src/main/java/org/fao/geonet/api/records/attachments/FilesystemStore.java
- core/src/main/java/org/fao/geonet/api/records/attachments/JCloudStore.java
- core/src/main/java/org/fao/geonet/api/records/attachments/ResourceLoggerStore.java
- core/src/main/java/org/fao/geonet/api/records/attachments/S3Store.java
- core/src/main/java/org/fao/geonet/api/records/attachments/Store.java
- listeners/src/main/java/org/fao/geonet/listener/metadata/draft/DraftUtilities.java
Backport #8100 
This pull request as some short term relief for issue https://github.com/geonetwork/core-geonetwork/issues/7952
> [Backport 4.2.x] Delete draft resource at the end of draft util transaction.

- web-ui/src/main/resources/catalog/components/metadataactions/partials/associatedResourcesContainer.html
Allows easier customization of the layout of the panel
eg. do not display type of relation blocks when associated resources are all on the same level (here parent and associated resources)
> Editor / Associated panel / CSS class by type

- web-ui/src/main/resources/catalog/components/metadataactions/partials/transferownership.html
> [Backport 4.2.x] Transfer ownership / fix translation key for Save button

- web-ui/src/main/resources/catalog/components/viewer/gfi/FeaturesTable.js
Fixes https://github.com/geonetwork/core-geonetwork/issues/8143
> Map / Feature table / Missing translation

- web-ui/src/main/resources/catalog/components/viewer/gfi/FeaturesTable.js
> [Backport 4.2.x] Map / Feature table / Missing translation

- web-ui/src/main/resources/catalog/views/default/less/gn_card_default.less
> Map list / Improve layout of card / Removing padding

- web-ui/src/main/resources/catalog/views/default/less/gn_result_default.less
> [Backport 4.2.x] Fix issue with Map Attribution not being toggled correctly in data preview.

- web-ui/src/main/resources/catalog/components/common/map/mapService.js
- web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextService.js
> [Backport 4.2.x] Map viewer / fix TMS layer persistence in map context

- web-ui/src/main/resources/catalog/components/viewer/layermanager/partials/layermanageritem.html
> [Backport 4.2.x] Map viewer / Add layer with styles from a metadata doesn't show the styles selector

- core/src/test/resources/org/fao/geonet/api/Messages.properties
- core/src/test/resources/org/fao/geonet/api/Messages_fre.properties
- services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
- web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
- web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties
> [Backport 4.2.x] Metadata workflow API / Update security exceptions to use translations

- common/src/main/java/org/fao/geonet/utils/Xml.java
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/citation/common.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/citation/view.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl
- schemas/iso19139/src/main/plugin/iso19139/formatter/citation/view.xsl
- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
- services/src/main/java/org/fao/geonet/api/records/editing/MetadataEditingApi.java
- services/src/main/java/org/fao/geonet/api/records/formatters/XsltFormatter.java
- services/src/test/resources/org/fao/geonet/api/records/formatters/iso19115-3.2018-citation-html.html
- services/src/test/resources/org/fao/geonet/api/records/formatters/iso19139-citation-html.html
- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
- web/src/main/webapp/xslt/base-layout.xsl
- web/src/main/webapp/xslt/common/render-html.xsl
- web/src/main/webapp/xslt/ui-metadata/edit/edit-embedded.xsl
- web/src/main/webapp/xslt/ui-metadata/form-builder-xml.xsl
- web/src/main/webapp/xslt/ui-metadata/menu-builder.xsl
> [Backport 4.2.x] API / XSL / Use XSL output configuration (formatter, editor)

- web-ui/src/main/resources/catalog/components/edit/crsselector/partials/crsselector.html
> [Backport 4.2.x] Editor / CRS search / Fix duplicated icon

- services/src/main/java/org/fao/geonet/api/registries/vocabularies/KeywordsApi.java
- web-ui/src/main/resources/catalog/components/elasticsearch/directives/FacetDirective.js
- web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facet-cards.html
- web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facet.html
- web-ui/src/main/resources/catalog/components/utility/UtilityService.js
- web-ui/src/main/resources/catalog/js/CatController.js
> [Backport 4.2.x] Improve tooltips for facet filter items

- services/src/main/java/org/fao/geonet/api/regions/metadata/MetadataRegionSearchRequest.java
Fix test for https://github.com/geonetwork/core-geonetwork/pull/8191/files
> Metadata extents API - fix service for metadata with working copy - test

- core/src/main/java/org/fao/geonet/util/XslUtil.java
While indexing, a number of log error can be reported:
```
2024-06-18T17:11:21,679 ERROR [geonetwork] - Failed to get index field 'resourceTitleObject' value on '10.17600/14000100', caused by Document with id 10.17600/14000100 not found
```
This is due to either remote record links not present in index eg. DOI or to an empty index and document search returns no document at starts.
It is triggered mainly in https://github.com/geonetwork/core-geonetwork/blob/main/web/src/main/webapp/xslt/common/index-utils.xsl#L141 but the `recordLink` field is currently not used in main UI.
Related to https://github.com/geonetwork/core-geonetwork/commit/e60699688eb3883ef582bdea76cb503b83ad92a4 and https://github.com/geonetwork/core-geonetwork/commit/20cc13b72f2645a416f7731bedff27909d727e37
> Indexing / Lower severity of getIndexField

- services/src/main/java/org/fao/geonet/api/records/extent/MetadataExtentApi.java
- services/src/main/java/org/fao/geonet/api/regions/metadata/MetadataRegionSearchRequest.java
> [Backport 4.2.x] Metadata extents API - fix service for metadata with working copy

- release-build.sh
- release-publish.sh
- release-restore.sh
Minor fixes in version number in tag, publish and md5.
> Release script improvement

- es/README.md
- es/docker-compose.yml
- es/es-dashboards/README.md
- pom.xml
> Elasticsearch / Update to 8.14.0.

- docs/manual/docs/overview/change-log/version-3.8.0.md
- docs/manual/docs/overview/change-log/version-4.0.0-alpha.1.md
Backport #7938
**Authored by:** @bernhardreiter
> [Backport 4.2.x] docs: fix image links in change-log(version-3.8.0.md and 4.0.0-alpha.1

- SECURITY.md
> [Backport 4.2.x] Update SECURITY.md

- services/src/main/java/org/fao/geonet/api/ApiUtils.java
> [Backport 4.2.x] Fix canViewRecord function so that it returned the workflow record.

- web-ui/src/main/resources/catalog/components/admin/harvester/partials/extras.html
- web-ui/src/main/resources/catalog/views/default/directives/partials/mdactionmenu.html
- web-ui/src/main/resources/catalog/views/default/templates/recordView/technical.html
> [Backport 4.2.x] Double translation can lead to infinite stack

- services/src/main/java/org/fao/geonet/api/processing/ProcessApi.java
> [Backport 4.2.x] API / Client code generation / Avoid reserved word

- core/src/main/java/org/fao/geonet/api/records/attachments/CMISStore.java
- core/src/main/java/org/fao/geonet/api/records/attachments/FilesystemStore.java
- core/src/main/java/org/fao/geonet/api/records/attachments/JCloudStore.java
- core/src/main/java/org/fao/geonet/api/records/attachments/S3Store.java
- listeners/src/main/java/org/fao/geonet/listener/metadata/draft/DraftUtilities.java
> [Backport 4.2.x] Add info logs to make transaction of working copy merge more traceable

- pom.xml
- Spring Framework: 5.3.36
- Spring Security: 5.7.12
> GeoNetwork 4.2.x minor versions library updates

- web-ui/src/main/resources/catalog/components/edit/bounding/partials/boundingpolygon.html
> [Backport 4.2.x] Editor / Bounding  polygon not saved

- web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facet-temporalrange.html
- web-ui/src/main/resources/catalog/components/ng-skos/templates/skos-concept-thesaurus.html
- web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html
- web-ui/src/main/resources/catalog/templates/formatter-viewer.html
- web-ui/src/main/resources/catalog/views/default/directives/partials/attributetable.html
Required by https://github.com/geonetwork/core-geonetwork/pull/8015
> Fix wrong HTML self closing tags

- web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facet-temporalrange.html
- web-ui/src/main/resources/catalog/components/ng-skos/templates/skos-concept-thesaurus.html
- web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html
- web-ui/src/main/resources/catalog/templates/formatter-viewer.html
- web-ui/src/main/resources/catalog/views/default/directives/partials/attributetable.html
- web-ui/src/main/resources/catalog/views/default/templates/recordView/type-series.html
> [Backport 4.2.x] Fix wrong HTML self closing tags

- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
> [Backport 4.2.x] Standard / ISO19139 / Formatter / Do not display extent if none available

- web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js
> [Backport 4.2.x] Fix infinite "Please wait" message on error

- schemas/config-editor.xsd
- web/src/main/webapp/xslt/ui-metadata/form-configurator.xsl
> [Backport 4.2.x] Editor / Configuration / Improve deletion in forEach section

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/iso19139/view.xsl
`xmlns:srv` was declared 2 times.
Fixes https://github.com/geonetwork/core-geonetwork/issues/8221
Related to https://github.com/geonetwork/core-geonetwork/commit/27a69dfa7c0214b4e3c9971b2e652dbba9742d36#diff-1f83f3131214c0592eea4a9f65ed3a58a889689a64e9f07bc0753544c0427b29
> Standard / ISO19115-3 / Formatter / Fix namespace declaration

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/iso19139/view.xsl
> [Backport 4.2.x] Standard / ISO19115-3 / Formatter / Fix namespace declaration

- services/src/main/java/org/fao/geonet/api/records/MetadataApi.java
> [Backport 4.2.x] Fix issue with working copy not being returned from getRecordAS api

- services/src/main/java/org/fao/geonet/api/records/CatalogApi.java
- services/src/main/java/org/fao/geonet/guiapi/search/XsltResponseWriter.java
- web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js
Fixes #7969.
Backport of #8262.
> [Backport 4.2.x] Use UI language for metadata selection export to CSV/PDF

- web-ui/src/main/resources/catalog/components/common/alert/AlertDirective.js
- web-ui/src/main/resources/catalog/components/common/map/mapService.js
- web-ui/src/main/resources/catalog/components/search/resultsview/SelectionDirective.js
- web-ui/src/main/resources/catalog/components/search/searchmanager/LocationService.js
- web-ui/src/main/resources/catalog/components/viewer/ViewerDirective.js
- web-ui/src/main/resources/catalog/components/viewer/wmsimport/WmsImportDirective.js
- web-ui/src/main/resources/catalog/js/edit/DirectoryController.js
- web-ui/src/main/resources/catalog/views/default/module.js
Backport of https://github.com/geonetwork/core-geonetwork/pull/8267
> [Backport 4.2.x] Zoom to map popup remains active on non-map pages.

- web-ui/src/main/resources/catalog/components/userfeedback/GnUserfeedbackDirective.js
- web-ui/src/main/resources/catalog/components/userfeedback/GnmdFeedbackDirective.js
- web-ui/src/main/resources/catalog/js/LoginController.js
> [Backport 4.2.x] Fix a problem with recaptcha not shown sometimes

- schemas/iso19139/src/main/plugin/iso19139/extract-relations.xsl
- schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
- schemas/iso19139/src/main/plugin/iso19139/process/onlinesrc-add.xsl
- schemas/iso19139/src/main/plugin/iso19139/process/onlinesrc-remove.xsl
Backport #8281
**Authored by:** @fxprunayre, @ianwallen
> [Backport 4.2.x] Standard / ISO19139 / Fix removal of online source when multiple transfer options block are used.

- services/src/main/java/org/fao/geonet/api/records/CatalogApi.java
> [Backport 4.2.x] Update batch PDF export to skip working copies

- web-ui/src/main/resources/catalog/style/gn_metadata.less
Related to https://github.com/geonetwork/core-geonetwork/pull/5879#issuecomment-2269506779
> Record view / Improve layout of table (eg. quality measures)

- schemas/iso19139/src/main/plugin/iso19139/loc/fre/labels.xml
> [Backport 4.2.x] Standard / ISO19139 / i18n / Missing french translation

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java
Backport #8303
**Authored by:** @rime1014
> [Backport 4.2.x] harvesting CSW: changed loglevel for invalid metadata to info

- web-ui/src/main/resources/catalog/components/search/mdview/mdviewModule.js
> [Backport 4.2.x] Set UUID correctly in "recordNotFound" message

- web-ui/src/main/resources/catalog/components/metadataactions/partials/recordLinkButton.html
> [BP] Record view / display WMS resources button label to open the link when the map viewer is not enabled

- CITATION.cff
This file is for zenodo registration to provide GeoNetwork with a DOI. 
- I chose Citation.cff as the gihub metadata document
- Once merged we can test if `Citation.cff` support is good enough registration, or if we need to generate a `zenodo.json` file.
- Filled in the PSC as authors, some other major contributors, along with Titellus, CamptoCamp, GeoCat and OSGeo.
- You can edit using [cffinit tool](https://citation-file-format.github.io/cff-initializer-javascript/#/) if you like.
Reference:
- https://citation-file-format.github.io
- https://wiki.osgeo.org/wiki/DOI#DOI_available_for_OSGeo_Projects
- https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files
> Repository Citation.cff metadata for DOI registration with Zenodo

- CITATION.cff
> [Backport 4.2.x] Repository Citation.cff metadata for DOI registration with Zenodo

- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
Backport #8320
**Authored by:** @tobias-hotz
> [Backport 4.2.x] Fix Clipboard copy/paste on Firefox

- core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java
> [Backport 4.2.x] Workflow / update notification level based on user profile when cancelling a submission

- web-ui/src/main/resources/catalog/components/common/map/mapService.js
> [Backport 4.2.x] Editor / Dublin core / Fix extent coordinates

- inspire-atom/src/main/java/org/fao/geonet/inspireatom/util/InspireAtomUtil.java
> [Backport 4.2.x] INSPIRE Atom harvester / process only public datasets by resource identifier

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/ISO19139/toISO19139.xsl
> [Backport 4.2.x] Standard / ISO19115-3 / Formatters / ISO19139 / Ignore mcc linkage for overview

- core/src/main/java/org/fao/geonet/kernel/GeonetworkDataDirectory.java
- core/src/test/java/org/fao/geonet/kernel/AbstractGeonetworkDataDirectoryTest.java
> API / Improve parameter check for XSL conversion.

- listeners/src/main/java/org/fao/geonet/listener/metadata/draft/ApprovePublishedRecord.java
- web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js
> [Backport 4.2.x] publish status not refreshing fix

- schemas/iso19139/src/main/plugin/iso19139/process/thumbnail-add.xsl
- schemas/iso19139/src/main/plugin/iso19139/process/thumbnail-remove.xsl
> [Backport 4.2.x] iso19139 - Update thumbnail add/update and remove to support index update/removal

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java
> [Backport 4.2.x] CSW Harvester / Avoid increment 2 metrics for a single metadata in certain conditions

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/linkToMd.html
> [Backport 4.2.x] Editor / Associated resource / Avoid empty label

- web-ui/src/main/resources/catalog/js/admin/SourcesController.js
- web-ui/src/main/resources/catalog/templates/admin/settings/sources.html
> [Backport 4.2.x] Admin / Source / Improve dirty state

- core/src/main/java/org/fao/geonet/web/GeoNetworkStrictHttpFirewall.java
- web/src/main/webapp/WEB-INF/config-security/config-security-core.xml
> [Backport 4.2.x] Special characters in the cookie causing 400 bad requests from Spring Security

- core/src/main/java/org/fao/geonet/kernel/GeonetworkDataDirectory.java
- core/src/test/java/org/fao/geonet/kernel/AbstractGeonetworkDataDirectoryTest.java
> [Backport 4.2.x] API / Improve parameter check for XSL conversion.

- web-ui/src/main/resources/catalog/views/default/less/gn_result_default.less
- web-ui/src/main/resources/catalog/views/default/templates/recordView/thumbnails.html
Backport #8290
**Authored by:** @MichelGabriel
> [Backport 4.2.x] [a11y] Put the image name in the `alt` attribute of the thumbnail on the metadata page

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/fromJsonOpenDataSoft.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/odstheme-mapping.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/protocol-mapping.xsl
Follow up of https://github.com/geonetwork/core-geonetwork/pull/7059
* Add elements taking into account the API version 1 or 2
* Do not put free text in an ISO field which is an enumeration (which avoids to mix facet icons and translations for topic category) 
*  Provide a mapping based on default ODS values for french and english 
* Add a dedicated keyword block with the free text values
@tkohr, @jahow any feedbacks ?
> Harvester / Simple URL / ODS / Improve mapping

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/eng/labels.xml
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/fre/labels.xml
> Standard / ISO19115-3 / Label improvement.

- pom.xml
Running the integration tests in MacOS with ARM processor, it tries to download a wrong version of Elasticsearch, as doesn't identify properly the system:
https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.14.0-linux-x86_64.tar.gz
Added a new profile to detect the MacOs for ARM based processors. With the new profile downloads the correct version:
https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.14.3-darwin-aarch64.tar.gz
Test case (In Apple ARM computer):
1) Run the integration tests: `mvn install -P it`
- Without the fix, the build fails with:
```
...
plugin:6.28:runforked (start-elasticsearch) on project gn-domain: Elasticsearch [0]: Cannot execute command '[bin/elasticsearch-plugin, list]' in directory '/PATH/domain/target/elasticsearch0'
[ERROR] …
```
> Add build profile for MacOS ARM

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/eng/labels.xml
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/fre/labels.xml
> [Backport 4.2.x] Standard / ISO19115-3 / Label improvement.

- pom.xml
> [Backport 4.2.x] Add build profile for MacOS ARM

- .gitignore
> GIT / .gitignore

- .gitignore
> [Backport 4.2.x] GIT / .gitignore

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java
> [Backport 4.2.x] GeoNetwork harvester - avoid double counting of updated metadata.

- web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facet.html
- web-ui/src/main/resources/catalog/components/search/mdview/partials/keywordBadges.html
> [Backport 4.2.x] Don't capitalize the labels for the facet filter values

- web-ui/src/main/resources/catalog/views/default/less/gn_map_default.less
Backport #8399
**Authored by:** @MichelGabriel
> [Backport 4.2.x] Fix the width of the projection switcher

- web-ui/src/main/resources/catalog/components/edit/fieldduration/partials/fieldduration.html
- web-ui/src/main/resources/catalog/components/thesaurus/ThesaurusDirective.js
- web-ui/src/main/resources/catalog/components/thesaurus/partials/keywordselector.html
> [Backport 4.2.x] Metadata editor / Add required indicator to keyword selector and fix the required indicator for the field duration directive

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
- schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
> [Backport 4.2.x] Metadata indexing / ISO19139 / ISO19115-3.2018 / Escape graphic overview file name for JSON

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcService.js
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/linkToMd.html
- web-ui/src/main/resources/catalog/components/viewer/gfi/partials/featurestables.html
- web-ui/src/main/resources/catalog/components/viewer/wfsfilter/partials/wfsfilterfacet.html
- web-ui/src/main/resources/catalog/templates/admin/settings/ui.html
- web-ui/src/main/resources/catalog/views/default/templates/recordView/technical.html
Test case:
1. Build the project: `mvn install -DskipTests`.
2. Check changed files with `git status`.
- Without the change: several files in the `web-ui` are reported with changes.
- With the change: no files are reported with changes.
> Javascript / HTML formatting fixes related to Prettier

- csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/es/CswFilter2Es.java
- csw-server/src/test/java/org/fao/geonet/kernel/csw/services/getrecords/es/CswFilter2EsTest.java
- csw-server/src/test/java/org/fao/geonet/kernel/csw/services/getrecords/es/EsJsonHelper.java
> CSW / Fix parsing date values for filters

- web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
eg. when using thesaurus for a field in a table, the field was not displayed.
```xml
<tableFields>
<table fieldset="false" for="mac:MI_Instrument">
<header>
<col label="mac:MI_Instrument"/>
<col label="mac:MI_Platform"/>
<col/>
</header>
<row>
<col xpath="mac:identifier/*/mcc:code"
use="data-gn-keyword-picker">
<directiveAttributes data-thesaurus-key="local.theme.cersat_sensor"/>
</col>
<col xpath="mac:mountedOn/*/mac:identifier/*/mcc:code"
use="data-gn-keyword-picker">
<directiveAttributes data-thesaurus-key="local.theme.cersat_platform"/>
</col>
<col del=".."/>
</row>
</table>
```
Follow up of https://github.com/geonetwork/core-geonetwork/pull/8016
> Editor / Table mode / Fix field using directive

- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java
- web-ui/src/main/resources/catalog/locales/en-admin.json
> [Backport 4.2.x] Update list of metadata import restrictions so that it will work even it there are spaces in the list.

- schemas/iso19115-3.2018/src/main/java/org/fao/geonet/schema/iso19115_3_2018/ISO19115_3_2018SchemaPlugin.java
> [Backport 4.2.x] Standard / ISO19115-3 / Only search for associated record with UUID

- services/src/main/java/org/fao/geonet/api/identifiers/IdentifiersApi.java
> Fixed description for getIdentifiers in IdentifierApi

- docs/manual/docs/administrator-guide/configuring-the-catalog/user-interface-configuration.md
Backport #8425
**Authored by:** @michikommader
> [Backport 4.2.x] Improve administrator guide UI configuration documentation

- csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/es/CswFilter2Es.java
- csw-server/src/test/java/org/fao/geonet/kernel/csw/services/getrecords/es/CswFilter2EsTest.java
- csw-server/src/test/java/org/fao/geonet/kernel/csw/services/getrecords/es/EsJsonHelper.java
> [Backport 4.2.x] CSW / Fix parsing date values for filters

- services/src/main/java/org/fao/geonet/api/es/EsHTTPProxy.java
> [Backport 4.2.x] Elasticsearch / API / Allow ndjson for _msearch endpoint

- schemas/iso19139/src/main/plugin/iso19139/process/thumbnail-remove.xsl
> [Backport 4.2.x] Allow removal of empty graphic overviews

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/simpleurl/Harvester.java
> [Backport 4.2.x] Harvester / Simple URL / Fix multiple URL alignement

- web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js
> [Backport 4.2.x] Fix saving UI settings without changes

- core/src/main/java/org/fao/geonet/api/records/attachments/CMISStore.java
- core/src/main/java/org/fao/geonet/api/records/attachments/FilesystemStore.java
- core/src/main/java/org/fao/geonet/api/records/attachments/JCloudStore.java
- core/src/main/java/org/fao/geonet/api/records/attachments/S3Store.java
> [Backport 4.2.x] Add better logging when resources are deleted to make it clear what metadata record the resource was deleted from

- core/src/test/resources/org/fao/geonet/api/Messages.properties
- core/src/test/resources/org/fao/geonet/api/Messages_fre.properties
- services/src/main/java/org/fao/geonet/api/users/validation/UserRegisterDtoValidator.java
- web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
- web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties
> [Backport 4.2.x] Avoid duplicate validation message when trying to register a user with existing email

- web-ui/src/main/resources/catalog/views/default/templates/home.html
> [Backport 4.2.x] Update home page "browse by" to display facet as label if there is only one (#8426)

- core/src/main/java/org/fao/geonet/kernel/datamanager/draft/DraftMetadataUtils.java
> [Backport 4.2.x] Delete date not being copied causing duplicate

- docs/manual/docs/overview/authors.md
> update PSC details in user guide

- docs/manual/docs/overview/change-log/history/index.md
- docs/manual/docs/overview/change-log/index.md
- docs/manual/docs/overview/change-log/version-4.2.11.md
- docs/manual/mkdocs.yml
> Release / 4.2.11 / Changelog.

- docs/manual/docs/overview/change-log/history/index.md
- docs/manual/docs/overview/change-log/index.md
- docs/manual/docs/overview/change-log/version-4.2.11.md
- docs/manual/docs/overview/change-log/version-4.4.6.md
- docs/manual/mkdocs.yml
> Release / 4.4.6 / Changelog.

- core/src/main/java/org/fao/geonet/util/XslUtil.java
> [Backport 4.2.x] Indexing / Lower severity of getIndexField

- core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java
> [Backport 4.2.x] Metadata status changes notification mails improvements

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
- schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
> [Backport 4.2.x] ISO19139 / ISO19115.3 / Index resource date fields as defined in the metadata.

- docs/manual/docs/user-guide/publishing/managing-privileges.md
- Remove outdated Featured privilege.
- Add Editing privilege and update the related rules description.
> Documentation / Update managing privileges page

- docs/manual/docs/user-guide/publishing/managing-privileges.md
> [Backport 4.2.x] Documentation / Update managing privileges page

- docs/manual/docs/user-guide/workflow/life-cycle.md
> Documentation / Metadata workflow improvements

- web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
> [Backport 4.2.x] option to force xsd schema check for required field

- schemas/iso19139/src/main/plugin/iso19139/layout/layout.xsl
- web-ui/src/main/resources/catalog/components/edit/multientrycombiner/partials/multientrycombiner.html
- web-ui/src/main/resources/catalog/components/edit/multientrycombiner/partials/multientrycombiner_onlineresourcesdescription.html
- web-ui/src/main/resources/catalog/components/thesaurus/ThesaurusDirective.js
- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
- web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
> [Backport 4.2.x] Add option to mock a dropdown for keywordPickers

- core/src/main/java/org/fao/geonet/kernel/SchemaManager.java
- core/src/main/java/org/fao/geonet/kernel/XmlSerializer.java
- core/src/main/java/org/fao/geonet/kernel/mef/ExportFormat.java
- core/src/main/java/org/fao/geonet/kernel/schema/MetadataSchema.java
- core/src/main/java/org/fao/geonet/kernel/schema/MetadataSchemaOperationFilter.java
- core/src/test/java/org/fao/geonet/kernel/XmlSerializerIntegrationTest.java
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/link-utility.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/schema-ident.xml
- schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
- schemas/iso19139/src/main/plugin/iso19139/schema-ident.xml
- services/pom.xml
- services/src/main/java/org/fao/geonet/api/es/EsHTTPProxy.java
- web/src/main/webapp/xml/validation/schemaPlugins/schema-ident.xsd
> [Backport 4.2.x] Extend ElasticSearch proxy to filter out elements defined in the schema filters configurations

- pom.xml
Improve known CVE for version 4.4 on spring security. https://hub.docker.com/layers/library/geonetwork/4.4.6/images/sha256-48ce3a84a796b1732ca79934a6c33f074eeec4dfde2d92e7d2feaa72ac675c9e?context=explore
Other critical CVE analysis:
* spring-web critical CVE does not look to apply in GeoNetwork context 
* activemq is more difficult to update https://mvnrepository.com/artifact/org.apache.activemq/activemq-core (also relates to Camel)
* mapfish print (update in progress)
Funded by BRGM
> Lib / Spring / Minor version update

- web-ui/src/main/resources/catalog/components/utility/UtilityService.js
- web-ui/src/main/resources/catalog/js/LoginController.js
- web-ui/src/main/resources/catalog/js/admin/ReportController.js
> [Backport 4.2.x] Sort groups alphabetically on the new account and report pages

- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
> [Backport 4.2.x] Metadata editor / Regions picker display empty entry form the metadata regions dao

- web-ui/src/main/resources/catalog/components/edit/directoryentryselector/DirectoryEntrySelector.js
- web-ui/src/main/resources/catalog/js/edit/DirectoryController.js
> [Backport 4.2.x] Directory entries / Fix parsing of sorting configuration

- web-ui/src/main/resources/catalog/components/filestore/FileStoreDirective.js
Related to #8427
Fixes the following errors in the application log file, when the application uses the `FileStoreDirective` directive:
```
Nov 26, 2024 2:44:08 PM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: /catalog/components/filestore/FileStoreDirective.js:96: ERROR - this language feature is only supported in es6 mode: const declarations. Use --language_in=ECMASCRIPT6 or ECMASCRIPT6_STRICT to enable ES6 features.
const sizes = ["Bytes", "KB", "MB", "GB", "TB"];
^
Nov 26, 2024 2:44:08 PM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: /catalog/components/filestore/FileStoreDirective.js:97: ERROR - this language feature is only supported in es6 mode: const declarations. Use --language_in=ECMASCRIPT6 or ECMASCRIPT6_STRICT to enable ES6 features.
const i …
```
> Remove usage of ECMASCRIPT6 const keyword

- web-ui/src/main/resources/catalog/components/filestore/FileStoreDirective.js
> [Backport 4.2.x] Remove usage of ECMASCRIPT6 const keyword

- core/src/main/java/org/fao/geonet/api/records/attachments/AbstractStore.java
- core/src/main/java/org/fao/geonet/api/records/attachments/CMISStore.java
- core/src/main/java/org/fao/geonet/api/records/attachments/JCloudStore.java
- core/src/main/java/org/fao/geonet/api/records/attachments/S3Store.java
- core/src/main/java/org/fao/geonet/resources/JCloudConfiguration.java
- core/src/main/resources/config-store/config-jcloud-overrides.properties
- core/src/main/resources/config-store/config-jcloud.xml
> [Backport 4.2.x] Add better Jcloud versioning supports

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/eng/codelists.xml
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/fre/codelists.xml
> [Backport 4.2.x] ISO19115.3-2008 / Fix typo in facsimile codelist value

- web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
- web/src/main/webapp/xslt/ui-metadata/menu-builder.xsl
> [Backport 4.2.x] Fix wrong HTML self-closed elements

- schemas/iso19110/src/main/plugin/iso19110/index-fields/index.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
- web-ui/src/main/resources/catalog/views/default/templates/recordView/featurecatalogue.html
> [Backport 4.2.x] ISO19110 / ISO19115-3.2008 / Fix indexing of multiple feature type aliases

- domain/pom.xml
- pom.xml
Backported change from a4db92ab14f849e393b69c08db3761216b971378
> Update ehcache and activemq libraries

- web/src/main/webapp/xslt/common/utility-tpl.xsl
> [Backport 4.2.x] Formatters / Properly detect URL ending in 1,2,3 or 5

- web-ui/src/main/resources/catalog/components/admin/schematron/partials/criteria-viewer.html
Fix font size related to JQuery update
> Admin / Schematron / Fix icon in rules

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/eng/schematron-rules-url-check.xml
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/fre/schematron-rules-url-check.xml
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/ger/schematron-rules-url-check.xml
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/schematron/schematron-rules-url-check.sch
> ISO19115-3.2008 - Add URL check schematron

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/eng/schematron-rules-url-check.xml
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/fre/schematron-rules-url-check.xml
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/ger/schematron-rules-url-check.xml
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/schematron/schematron-rules-url-check.sch
> [Backport 4.2.x] ISO19115-3.2008 - Add URL check schematron

- services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
> [Backport 4.2.x] Return xml inside JSON status

- domain/src/main/java/org/fao/geonet/domain/StatusValue.java
- listeners/src/main/java/org/fao/geonet/listener/history/AttachmentAddedListener.java
- listeners/src/main/java/org/fao/geonet/listener/history/AttachmentDeletedListener.java
- listeners/src/main/java/org/fao/geonet/listener/history/RecordCategoryChangeListener.java
- listeners/src/main/java/org/fao/geonet/listener/history/RecordCreatedListener.java
- listeners/src/main/java/org/fao/geonet/listener/history/RecordDeletedListener.java
- listeners/src/main/java/org/fao/geonet/listener/history/RecordGroupOwnerChangeListener.java
- listeners/src/main/java/org/fao/geonet/listener/history/RecordImportedListener.java
- listeners/src/main/java/org/fao/geonet/listener/history/RecordOwnerChangeListener.java
- listeners/src/main/java/org/fao/geonet/listener/history/RecordPrivilegesChangeListener.java
- listeners/src/main/java/org/fao/geonet/listener/history/RecordProcessingChangeListener.java
- listeners/src/main/java/org/fao/geonet/listener/history/RecordRestoredListener.java
- listeners/src/main/java/org/fao/geonet/listener/history/RecordUpdatedListener.java
- listeners/src/main/java/org/fao/geonet/listener/history/RecordValidationTriggeredListener.java
- services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
> [Backport 4.2.x] Move StatusValue.Events to an enum class

- services/src/main/java/org/fao/geonet/api/site/SiteApi.java
- services/src/test/java/org/fao/geonet/api/site/SiteApiTest.java
> [Backport 4.2.x] Fix set site settings in swagger_ui so it function correctly.

- web-ui/src/main/resources/catalog/style/gn_metadata.less
> [Backport 4.2.x] Record view / Improve layout of table (eg. quality measures)

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
- schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
- web-ui/src/main/resources/catalog/components/search/mdview/mdviewDirective.js
- web-ui/src/main/resources/catalog/components/search/mdview/partials/qualitymeasures.html
- web-ui/src/main/resources/catalog/locales/en-v4.json
- web-ui/src/main/resources/catalog/views/default/templates/recordView/type-dataset.html
- web/src/main/webResources/WEB-INF/data/config/index/records.json
> [Backport 4.2.x] Record view / DQ / Add measure date information

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
> [Backport 4.2.x] Standard / ISO19115-3 / Quality report / Index descriptive results

- docs/manual/docs/administrator-guide/managing-users-and-groups/creating-group.md
Backport #8592
**Authored by:** @PeterParslow
> [Backport 4.2.x] Update creating-group.md

- core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
- web-ui/src/main/resources/catalog/views/default/templates/recordView/lineage.html
> [Backport 4.2.x] Record view / fix javascript error when a metadata has multiple lineage source descriptions

- core/src/test/resources/org/fao/geonet/api/Messages_fre.properties
- web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties
> [Backport 4.2.x] French translation for user registered message

- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataOperations.java
> [Backport 4.2.x] Fix privileges cannot be unset

- core/src/main/java/org/fao/geonet/kernel/SelectionManager.java
- services/src/main/java/org/fao/geonet/api/es/EsHTTPProxy.java
> [Backport 4.2.x] Batch selection is not in sync between search results and record view.

- services/src/main/java/org/fao/geonet/api/ApiUtils.java
- services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
> [Backport 4.2.x] Update getRecordStatusHistory and getRecordStatusHistoryByType to support getting working copy records history.

- core/src/main/java/org/fao/geonet/api/records/attachments/AbstractStore.java
- core/src/main/java/org/fao/geonet/util/LimitedInputStream.java
- datastorages/jcloud/src/main/java/org/fao/geonet/api/records/attachments/JCloudStore.java
> [Backport 4.2.x] Fix jcloud content length is inaccurate

- domain/src/main/java/org/fao/geonet/repository/SourceRepository.java
- services/src/main/java/org/fao/geonet/api/sources/SourcesApi.java
- services/src/test/java/org/fao/geonet/api/sources/SourcesApiTest.java
- web-ui/src/main/resources/catalog/components/usersearches/UserSearchesDirective.js
- web-ui/src/main/resources/catalog/components/usersearches/UserSearchesService.js
- web-ui/src/main/resources/catalog/js/admin/CSWTestController.js
> [Backport 4.2.x] Add get /api/sources/{sourceIdentifier} to be able to get a source by id.

- web-ui/src/main/resources/catalog/js/admin/CategoriesController.js
- web-ui/src/main/resources/catalog/js/admin/UserGroupController.js
> Sort categories list by translation in the categories and groups pages

- web-ui/src/main/resources/catalog/js/admin/CategoriesController.js
- web-ui/src/main/resources/catalog/js/admin/UserGroupController.js
> [Backport 4.2.x] Sort categories list by translation in the categories and groups pages

- pom.xml
Just keeping up with recent releases
> Update to GeoTools 32.2

- core/src/main/java/org/fao/geonet/api/records/attachments/AbstractStore.java
- core/src/test/java/org/fao/geonet/api/records/attachments/FilesystemStoreTest.java
> [Backport 4.2.x] URL Decode filename for resources uploaded by url

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/eng/labels.xml
> Standard / 19115-3 / Update labels.xml

- web-ui/src/main/resources/catalog/components/filestore/FileStoreDirective.js
> [Backport 4.2.x] Restore metadata file store multiple files upload

- web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_dut.properties
> [Backport 4.2.x] Add Dutch messages.properties file.

- web-ui/src/main/resources/catalog/components/filestore/FileStoreDirective.js
> [Backport 4.2.x] Pasting text in the metadata editor uploads an image to the catalogue store

- core/src/test/resources/org/fao/geonet/api/Messages.properties
- core/src/test/resources/org/fao/geonet/api/Messages_fre.properties
- services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
- web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
- web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_dut.properties
- web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties
> [Backport 4.2.x] Fix only record owners can access workflow status API

- web-ui/src/main/resources/catalog/components/search/resultsview/ResultsviewDirective.js
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid.html
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/list.html
> [Backport 4.2.x] Search result record abstract parsing improvement

- web-ui/src/main/resources/catalog/components/filestore/FileStoreDirective.js
- web-ui/src/main/resources/catalog/components/filestore/partials/dataUploaderButton.html
- web-ui/src/main/resources/catalog/style/gn_editor.less
> [Backport 4.2.x] Metadata editor / add visual indication when dragging a file to upload

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/dut/codelists.xml
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/dut/labels.xml
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/dut/schematron-rules-datacite.xml
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/dut/schematron-rules-url-check.xml
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/dut/strings.xml
> [Backport 4.2.x] Add Dutch translations of the iso19115-3.2018 metadata schema

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/ISO19139/mapping/CI_ResponsibleParty.xsl
> [Backport 4.2.x] Conversion from ISO19139 to ISO19115-3.2018: Manage organisation name with Anchor

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/IHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/CswHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Harvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geoPREST/GeoPRESTHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geoPREST/Harvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/GeonetHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Harvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/oaipmh/Harvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/oaipmh/OaiPmhHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/ogcwxs/Harvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/simpleurl/Harvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/simpleurl/SimpleUrlHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/thredds/Harvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/thredds/ThreddsHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/webdav/Harvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/webdav/WebDavHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/wfsfeatures/Harvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/wfsfeatures/WfsFeaturesHarvester.java
- harvesters/src/test/java/org/fao/geonet/kernel/harvest/harvester/geoPREST/HarvesterTest.java
- harvesters/src/test/java/org/fao/geonet/kernel/harvest/harvester/simpleurl/HarvesterTest.java
> [Backport 4.2.x] Fix harvesting errors not always being reported

- core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
- web-ui/src/main/resources/catalog/components/metadataactions/RelatedDirective.js
> [Backport 4.2.x] Add byte data to metadata summary page for its children thumbnails

- services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
> [Backport 4.2.x] Fix jsonLocTranslator in MetadataWorkflowApi

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/simpleurl/Aligner.java
> [Backport 4.2.x] CSW and Simple URL harvesters: translate the metadata on metadata updates if translations are configured

- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
Backport https://github.com/geonetwork/core-geonetwork/pull/8713
> [Backport 4.2.x] Fix username not set in link to profile

- docs/manual/docs/contributing/doing-a-release.md
- docs/manual/docs/maintainer-guide/updating/index.md
> document the manual steps still required with script assistance

- web-ui/src/main/resources/catalog/views/default/templates/recordView/tabbed.html
- web-ui/src/main/resources/catalog/views/default/templates/recordView/type-dataset.html
- web-ui/src/main/resources/catalog/views/default/templates/recordView/type-series.html
> [Backport 4.2.x] Hide contactForResource header when there are none

- core/src/main/java/org/fao/geonet/kernel/security/openidconnect/bearer/AudienceAccessTokenValidator.java
Backport #8709
**Authored by:** @xiechangning20
> [Backport 4.2.x] Fix bearer token API access from a different application

- web-ui/src/main/resources/catalog/components/userfeedback/partials/mdFeedback.html
> [Backport 4.2.x] Translate roles in the feedback form

- core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
> [Backport 4.2.x] Avoid null pointer when indexing overview data

- web-ui/src/main/resources/catalog/components/viewer/wmsimport/partials/styles.html
> [Backport 4.2.x] Map viewer / show style selection menu on the right to avoid cropping it

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/ISO19139/fromISO19139.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/fromISO19139-with-languages-refactor.xsl
By reading the code, seems that theses four lines can be removed... Doing so many times could help: beginning today.
> remove dead code

- web/src/main/webResources/WEB-INF/config-db/database_migration.xml
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v4213/migrate-default.sql
Add missing SQL migration to 4.2.13 version.
> Add SQL migration to 4.2.13 version

- services/src/main/java/org/fao/geonet/api/es/EsHTTPProxy.java
- web-ui/src/main/resources/catalog/js/edit/NewMetadataController.js
> [Backport 4.2.x ] Search / Avoid breaking search when schema not indexed or not available

- workers/wfsfeature-harvester/src/main/java/org/fao/geonet/harvester/wfsfeatures/WFSHarvesterApi.java
> [Backport 4.2.x] API / WFSHarvesterApi / Restrict to Editor

- web-ui/src/main/resources/catalog/components/pages/partials/menu-page.html
> [Backport 4.2.x] Fix submenu still displays with no children

- core/src/test/resources/WEB-INF/config.properties
- docs/manual/docs/install-guide/installing-index.md
- docs/manual/docs/tutorials/introduction/deployment/deploy.md
- index/src/main/java/org/fao/geonet/index/es/EsRestClient.java
- pom.xml
- schemas-test/src/main/webapp/WEB-INF/config.properties
- services/src/main/webapp/WEB-INF/config.properties
- services/src/test/resources/WEB-INF/config.properties
- web/src/main/webResources/WEB-INF/config.properties
- web/src/main/webResources/WEB-INF/web.xml
> [Backport 4.2.x] Allow to configure the Elasticsearch connection in environment variables

- core/src/main/java/org/fao/geonet/kernel/security/keycloak/KeycloakPreAuthActionsLoginFilter.java
- core/src/main/java/org/fao/geonet/kernel/security/openidconnect/GeonetworkOidcPreAuthActionsLoginFilter.java
- core/src/main/java/org/fao/geonet/web/GeoNetworkPortalFilter.java
- web/src/main/webResources/WEB-INF/web.xml
Backport #8769
**Authored by:** @xiechangning20
> [Backport 4.2.x] Update the excludedPaths from portalCheckFilter in web.xml to be sharable for other configs

- core/src/main/java/org/fao/geonet/kernel/WatchListNotifier.java
- core/src/main/java/org/fao/geonet/util/LocalizedEmailComponent.java
- core/src/test/resources/org/fao/geonet/api/Messages.properties
- core/src/test/resources/org/fao/geonet/api/Messages_fre.properties
- web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
- web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_dut.properties
- web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties
> [Backport 4.2.x] Fix localized watchlist emails

- web-ui/src/main/resources/catalog/components/common/savedselections/SavedSelectionsDirective.js
> [Backport 4.2.x] Fix map list "add to map" function

- core/src/main/java/org/fao/geonet/kernel/setting/Settings.java
- core/src/test/resources/org/fao/geonet/api/Messages.properties
- services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/templates/admin/settings/system.html
- web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v4213/migrate-default.sql
> [Backport 4.2.x] setting option to enable/disable backup during delete record

- web-ui/src/main/resources/catalog/components/common/savedselections/SavedSelectionsDirective.js
Related to https://github.com/geonetwork/core-geonetwork/pull/8774
> Remove ES 6 code and prettier formatting.

- web-ui/src/main/resources/catalog/components/common/savedselections/SavedSelectionsDirective.js
> [Backport 4.2.x] Remove ES 6 code and prettier formatting.

- core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java
- domain/src/main/java/org/fao/geonet/domain/StatusValueNotificationLevel.java
- services/src/main/java/org/fao/geonet/util/MetadataPublicationMailNotifier.java
- web-ui/src/main/resources/catalog/locales/en-admin.json
> [Backport 4.2.x] Add new recordProfileUserAdmin notification level

- web-ui/src/main/resources/catalog/components/search/mdview/mdviewDirective.js
- web-ui/src/main/resources/catalog/components/search/mdview/partials/social.html
- web-ui/src/main/resources/catalog/views/default/templates/recordView/share.html
> [Backport 4.2.x] Record view / fix permalink option.

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/webdav/Harvester.java
> [Backport 4.2.x] WebDav harvester / update database change date when updating a metadata.

- web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
- web-ui/src/main/resources/catalog/components/search/mdview/mdviewDirective.js
- web-ui/src/main/resources/catalog/components/search/mdview/partials/contact.html
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
> [Backport 4.2.x] Contact full view vs icon view configuration on record summary page

- web-ui/src/main/resources/catalog/components/search/mdview/partials/social.html
- web-ui/src/main/resources/catalog/views/default/templates/footer.html
- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
Even if the old Twitter bird icon is nicer...
And maybe we should remove all the social stuff from GeoNetwork or make it configurable for the social networks to support, without having to change the html files...
> Minor upgrade of FontAwesome to version 6.4.2 and update Twitter icon

- web-ui/src/main/resources/catalog/components/search/mdview/partials/social.html
- web-ui/src/main/resources/catalog/views/default/templates/footer.html
- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
> [Backport 4.2.x] Minor upgrade of FontAwesome to version 6.4.2 and update Twitter icon

- pom.xml
This is a minor update: [release notes](https://github.com/geotools/geotools/releases/tag/32.3)
> Update to GeoTools 32.3

- web-ui/src/main/resources/catalog/style/gn.less
> [Backport 4.2.x] Update z-index for citation buttons

- web/src/main/webResources/WEB-INF/web.xml
> [Backport 4.2.x] Fix typo in ESFeaturesProxy configuration

- es/README.md
- es/docker-compose.yml
This syncs docker-compose.yml and README with 045cd1736df pom.xml es.version update by @fxprunayre.
> ES 7.17.15 sync with pom.xml es.version property

- wro4j/pom.xml
Trivy is reporting 3 critical vulnerability
```
Java (jar)
==========
Total: 3 (CRITICAL: 3)
┌────────────────────────────────────────────────────────┬──────────────────┬──────────┬──────────┬───────────────────┬───────────────┬─────────────────────────────────────────────────────────┐
│                        Library                         │  Vulnerability   │ Severity │  Status  │ Installed Version │ Fixed Version │                          Title                          │
├────────────────────────────────────────────────────────┼──────────────────┼──────────┼──────────┼───────────────────┼───────────────┼─────────────────────────────────────────────────────────┤
│ org.jyaml:jyaml (jyaml-1.3.jar)                        │ CVE-2020-8441    │ CRITICAL │ affected │ 1.3               │ …
```
> Security / Exclude properly unused handlebars dependency from WRO4J

- common/src/main/java/org/fao/geonet/utils/Log.java
- docs/manual/docs/install-guide/logging.md
- web/src/main/webapp/WEB-INF/classes/log4j2-dev.xml
- web/src/main/webapp/WEB-INF/classes/log4j2-index.xml
- web/src/main/webapp/WEB-INF/classes/log4j2-test.xml
- web/src/main/webapp/WEB-INF/classes/log4j2.xml
[Documentation](https://docs.geonetwork-opensource.org/4.4/install-guide/logging/#customising-the-log-file-location) and other `log4j2-*.xml` files ([`log4j2-index.xml`](https://github.com/geonetwork/core-geonetwork/blob/3c6b329eff2a0b98777fc4e48f91193485d36349/web/src/main/webapp/WEB-INF/classes/log4j2-dev.xml#L11-L12), [`log4j2-index.xml`](https://github.com/geonetwork/core-geonetwork/blob/3c6b329eff2a0b98777fc4e48f91193485d36349/web/src/main/webapp/WEB-INF/classes/log4j2-index.xml#L11-L12))  in the projects set the log directory as `${sys:log_dir:-log_dir}/logs/`. This commit does the same to the default log configuration.
> Fix the logs directory

- common/src/main/java/org/fao/geonet/utils/Log.java
- docs/manual/docs/install-guide/logging.md
- web/src/main/webapp/WEB-INF/classes/log4j2-dev.xml
- web/src/main/webapp/WEB-INF/classes/log4j2-index.xml
- web/src/main/webapp/WEB-INF/classes/log4j2-test.xml
- web/src/main/webapp/WEB-INF/classes/log4j2.xml
> [Backport 4.2.x] Fix the logs directory

- web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
- web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_dut.properties
> [Backport 4.2.x] Fix metadata feedback email text

- pom.xml
- Update Spring Security to version 5.7.14
> Library updates for 4.2.x branch

- core/src/main/java/org/fao/geonet/util/MailUtil.java
Backport #8801
**Authored by:** @joachimnielandt
> [Backport 4.2.x] Set UTF-8 on sent mails

- .github/workflows/linux.yml
- .gitignore
- web-ui/src/main/resources/catalog/components/search/resultsview/ResultsviewDirective.js
- web-ui/src/main/resources/catalog/js/CatController.js
> [Backport 4.2.x] Workflow to account for formatting changes in CatCongtroller.js and ResultsviewDirective.js

- services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java
> [Backport 4.2.x] Fix content type and filename for resized image attachments

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/dcat/dcat-core-distribution.xsl
- services/src/test/resources/org/fao/geonet/api/records/formatters/iso19115-3.2018-dcat-service-core.rdf
- Distributions are not added for data services (See https://semiceu.github.io/DCAT-AP/releases/3.0.0/#DataService)
Follow up: https://github.com/geonetwork/core-geonetwork/pull/8642
> Formatter / DCAT / Data services doesn't have distributions

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/dcat/dcat-core-resource.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/dcat/dcat-variables.xsl
- services/src/test/resources/org/fao/geonet/api/records/formatters/iso19115-3.2018-dcat-dataset-core.rdf
- services/src/test/resources/org/fao/geonet/api/records/formatters/iso19115-3.2018-dcat-dataset.xml
- services/src/test/resources/org/fao/geonet/api/records/formatters/iso19115-3.2018-eu-dcat-ap-dataset-core-multipleAccrualPeriodicityAllowed.rdf
- services/src/test/resources/org/fao/geonet/api/records/formatters/iso19115-3.2018-eu-dcat-ap-dataset-core.rdf
- services/src/test/resources/org/fao/geonet/api/records/formatters/iso19115-3.2018-eu-dcat-ap-hvd-dataset-core.rdf
- services/src/test/resources/org/fao/geonet/api/records/formatters/iso19115-3.2018-eu-dcat-ap-mobility-dataset-core.rdf
- services/src/test/resources/org/fao/geonet/api/records/formatters/iso19115-3.2018-eu-geodcat-ap-dataset-core.rdf
* If record is children do not duplicate it in siblings
* Use specialized relations instead of generic dct:references
* Improve mapping for media type
Funded by Service Public de Wallonie
> Formatter / DCAT / Improve dct:references and mime type mapping

- web-ui/src/main/resources/catalog/components/edit/validationreport/ValidationReportDirective.js
> [Backport 4.2.x] Validation report / Show schema validation after optional rules

- web-ui/src/main/resources/catalog/components/common/map/mapService.js
- web-ui/src/main/resources/catalog/components/common/savedselections/SavedSelectionsDirective.js
- web-ui/src/main/resources/catalog/views/default/module.js
Backport https://github.com/geonetwork/core-geonetwork/pull/8866
> [Backport 4.2.x] Fix WMS cannot be added to map via map list

- core/src/main/java/org/fao/geonet/kernel/datamanager/draft/DraftMetadataUtils.java
Backport https://github.com/geonetwork/core-geonetwork/pull/8460
> [Backport 4.2.x] Delete resources when a new working copy is cancelled

- services/src/main/java/org/fao/geonet/api/userfeedback/UserFeedbackAPI.java
> [Backport 4.2.x] Fix url is not multilingual in rating email

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/ISO19139/mapping/core.xsl
For example, when importing  https://sextant.ifremer.fr/geonetwork/srv/api/records/ffab290d-decd-4a92-bc8c-94da8c6a45dd/formatters/xml associated resource are not properly encoded
```xml
<mri:metadataReference>1aaaea8c-8724-465f-831c-5d1e67bacefe</mri:metadataReference>
```
instead of
```xml
<mri:metadataReference uuidref="1aaaea8c-8724-465f-831c-5d1e67bacefe"/>
```
Also improve remote associated resources mapping eg. 
```xml
<gmd:aggregationInfo>
<gmd:MD_AggregateInformation>
<gmd:aggregateDataSetIdentifier>
<gmd:MD_Identifier>
<gmd:code>
<gmx:Anchor xlink:href="https://doi.org/10.17600/18001575" xlink:title="CALADU_2021">https://doi.org/10.17600/18001575</gmx:Anchor>
```
https://sextant.ifremer.fr/geonetwork/srv/api/records/45218382-4036-4c14-b09c-c3bef3484e80/formatters/xml
Only `href` …
> Standard / ISO19115-3 / From ISO19139 conversion / Fix metadatareference

- web-ui/src/main/resources/catalog/style/gn.less
> [Backport 4.2.x] Fix image modal style for small images

- services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java
> [Backport 4.2.x] Resume attachment downloads

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
- schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
- web-ui/src/main/resources/catalog/views/default/templates/recordView/processsteps.html
Backport of https://github.com/geonetwork/core-geonetwork/pull/8874
> [Backport 4.2.x] Lineage / handle process steps with multiple sources

- translationproviders/src/main/java/org/fao/geonet/translations/libretranslate/LibreTranslateClient.java
> [Backport 4.2.x] Update LibreTranslate client to fix issues with character encoding (#8954)

- core/src/main/java/org/fao/geonet/kernel/datamanager/IMetadataManager.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/IMetadataValidator.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataValidator.java
> [Backport 4.2.x] Fix batch validation and editor validation do not output the same result

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl
- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
> [Backport 4.2.x] Metadata page / Improve distribution section in full view

- web-ui/src/main/resources/catalog/components/search/searchfiltertag/SearchFilterTagsDirective.js
Fixes #8974
See test case in the ticket.
> Facets / Fix removal of values encoded as 0 in facet filter objects

- web-ui/src/main/resources/catalog/components/search/searchfiltertag/SearchFilterTagsDirective.js
> [Backport 4.2.x] Facets / Fix removal of values encoded as 0 in facet filter objects

- services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java
> [Backport 4.2.x] Fix attachment download for jcloud

- .gitmodules
- plugins/datahub-integration/pom.xml
- plugins/datahub-integration/src/main/java/org/fao/geonet/datahub/DatahubController.java
- web-ui/src/main/resources/catalog/js/admin/SourcesController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/locales/fr-admin.json
- web-ui/src/main/resources/catalog/templates/admin/settings/sources.html
This PR is about the suggestion of @KoalaGeo  here : https://github.com/geonetwork/geonetwork-ui/issues/1271
In this PR I changed the gnui version from v2.5.0 to v2.6.0 and the front is able to display it  : <img width="1544" height="479" alt="image" src="https://github.com/user-attachments/assets/c360dec1-fcc2-42fd-940a-58cd70a0b491" />
> fix GNUI version and display it

- core/src/main/java/org/fao/geonet/kernel/security/openidconnect/GeonetworkOAuth2LoginAuthenticationFilter.java
Added logs for identity of OIDC login
Added a generic try & catch block,  and logs the related login error
- [ ✔️] I have read the [contribution guidelines](https://github.com/geonetwork/core-geonetwork/blob/main/CONTRIBUTING.md)
> Added logs for identity of OIDC login

- schemas/dublin-core/src/main/plugin/dublin-core/loc/fre/labels.xml
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/fre/codelists.xml
- schemas/iso19115-3.2018/src/test/resources/metadata-for-editing-light.xml
- schemas/iso19115-3.2018/src/test/resources/metadata-for-editing.xml
- schemas/iso19115-3.2018/src/test/resources/metadata-iso19139-for-editing.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/fre/codelists.xml
Update translation to be more consistent.
Before the update 
After the update
> Update nonGeographicDataset French translation

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/fre/codelists.xml
> Standard / ISO19115-3 / Fix typos in French codelists descriptions

- web-ui/src/main/resources/catalog/locales/en-core.json
Fixes #9007 
Adds an entry for Danish in en-core.json.
Danish is already supported in other parts of the application:
https://github.com/geonetwork/core-geonetwork/blob/f7b49c84cf863a26675151a1fdc0b06cfa38567f/web-ui/src/main/resources/catalog/js/CatController.js#L103
https://github.com/geonetwork/core-geonetwork/blob/f7b49c84cf863a26675151a1fdc0b06cfa38567f/web-ui/src/main/resources/catalog/js/CatController.js#L1777
https://github.com/geonetwork/core-geonetwork/tree/f7b49c84cf863a26675151a1fdc0b06cfa38567f/web-ui/src/main/resources/catalog/locales (da-xxx files)
> Add key "dan" for "Dansk" (Danish)

- web-ui/src/main/resources/catalog/locales/en-core.json
Backport #9008
**Authored by:** @heidivanparys
> [Backport 4.2.x] Add key "dan" for "Dansk" (Danish)

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/simpleurl/RDFUtils.java
- harvesters/src/main/resources/harvester-resources/simpleUrl/sparql/extract-resources-no-records.rq
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/fromSPARQL-DCAT.xsl
* RDF documents providing DCAT dataset may not declare any Catalog object. Add support for this by making the catalog identifier optional 
* Improve DCAT mapping, add support for
* dct:creator
* dct:publisher
* dct:PeriodOfTime
* dct:spatial
* dct:keyword
* dct:accessRights
* dct:license
* dct:isPartOf
* dct:reference
* dct:hasPart
* pav:previousVersion
* dct:format 
* dct:bibliographicCitation
* improve dcat:distribution and contact mapping which could be using vcard or foaf.
Can be tested with record like https://data.jrc.ec.europa.eu/dataset/98336641-fd1c-4992-8c7b-c470dd5eb81e.rdf
Harvester config:
```json
{"@id":"2539","@type":"simpleurl","owner":["209878"],"ownerGroup":[2],"ownerUser":["undefined"],"site":{"name":"JRC","uuid":"75a8c506-4a55-4efd-aa95-cfd5b66e37c4","account":{"use":fa …
```
> Harvester / Simple URL / DCAT support improvements

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/duplicate-metadata.xsl
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/templates/geodata.xml
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/templates/map.xml
- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/templates/service.xml
- schemas/iso19115-3.2018/src/test/java/org/fao/geonet/schema/DuplicateRecordXslProcessTest.java
- schemas/iso19115-3.2018/src/test/java/org/fao/geonet/schema/LanguageXslProcessTest.java
- schemas/iso19115-3.2018/src/test/resources/metadata.xml
> [Backport 4.2.x] Standard / ISO19115-3 / Duplicate record / Remove record date.

- schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/dcat/dcat-utils.xsl
Required for the rdf-localised template, for example when processing prov:wasGeneratedBy.
> DCAT formatter / Add prov namespace in dcat-utils.xsl

- core/src/main/java/org/fao/geonet/kernel/SchematronValidatorExternalMd.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataValidator.java
> [Backport 4.2.x] Corrected the formatting on validation log messages.

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/database/DatabaseHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/database/DatabaseHarvesterAligner.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/database/DatabaseHarvesterParams.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/database/DatabaseHarvesterUtil.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/database/DatabaseMetadataRetriever.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/database/DatabaseMetadataRetrieverFactory.java
- harvesters/src/test/java/org/fao/geonet/kernel/harvest/harvester/database/DatabaseHarvesterUtilTest.java
- web-ui/src/main/resources/catalog/locales/en-admin.json
> [Backport 4.2.x] Database harvester / support qualified table names (schema.table) and improve sanitize of table / field names
