geonetwork/core-geonetwork

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/datacite/view.xsl
schemas/iso19139/src/main/plugin/iso19139/formatter/datacite/view.xsl

When creator name is not an individual or a service, use the organisation (mandatory from an ISO point of view) as the creator name with type Organizational. Note: The creator name can't be multilingual but the affiliation will be.

Formatter / Datacite / Creator can be organizational.

---

web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/editor.html

The current create child action displayed for all records (except template) really only applies, as it is now, to ISO19139 records which in `update-fixed-info` add an element `gmd:parentIdentifier` to the new record created. 
When a child/parent relation is defined between records (sometimes named groups/series/collections/products, ...), current practice is to mainly use `aggregationInfo` in ISO19139 and `associatedResource` in ISO19115-3 instead of the `parentIdentifier`. Also when creating links, some users prefer to link in direction:
* from series `isComposedOf` dataset
* from dataset `partOfSeamlessDatabase` series
Also most of the time, when user creates a new child in a series they often simply copy/paste an existing one which will probably share most of the descriptors.
So this …

Editor board / Remove create child action

---

core/src/main/java/org/fao/geonet/kernel/AddElemValue.java
core/src/test/java/org/fao/geonet/kernel/EditLibIntegrationTest.java
core/src/test/resources/WEB-INF/config.properties

When using `gn_delete` tag, always consider it as an XML mode to properly check that we are in deletion mode in EditLib.
Fix wrong test and test various type of config can be self closing tag or not `<gn_delete/>` or `<gn_delete></gn_delete>`.
Issue was noticed using the following config
```json
{"field":"Distribution / Remove an online resource by URL","insertMode":"gn_delete","xpath":"/gmd:MD_Metadata/gmd:distributionInfo/*/gmd:transferOptions/*/gmd:onLine[starts-with(*/gmd:linkage/gmd:URL, \"http://www.eea.europa.eu/data-and-maps/data\") or starts-with(*/gmd:linkage/gmd:URL, \"https://cmshare.eea.europa.eu/\")]","value":"","isXpath":true}
```
which was removing the first `gmd:onLine` when none were matching because it was not detecting deletion mode.

API / Batch edit / Delete with a non matching XPath can remove unwanted elements

---

schemas/iso19139/src/main/plugin/iso19139/convert/thesaurus-transformation.xsl

This is needed for user relying on XLink for keywords. In particular for those targeting INSPIRE conformity. Indeed classification of service is expected to be encoded using an `Anchor`.
Validation error:
```
The metadata record set has 1 record(s) with errors for this assertion.
XML document 'file.xml', record 'a5135c62-aae0-49ab-92ec-b23fbff3bd96':
At least one keyword shall be given with a child Anchor including an xlink:href attribute
or CharacterString with one of the language-natural keyword values as defined in
"Classification of Spatial Data Services" Part D 4. Please note that the URIs of all
code list values from the INSPIRE Registry shall be referenced using the http protocol.
```
Valid fragments:
```xml
<gmd:keyword xsi:type="gmd:PT_FreeText_PropertyType">
<gmx:Anchor …
```

Vocabularies / Add XLink mode producing Anchor encoding

---

web-ui/src/main/resources/catalog/components/metadataactions/partials/recordLinkButton.html

The link button in the 'related' part of the detail view wasn't accessible by keyboard (using the `TAB` button). This PR fixes this by adding a `href` attribute

[a11y] Make the record link button in the record view accessible

---

web-ui/src/main/resources/catalog/views/default/directives/partials/mdactionmenu.html

Follow up of https://github.com/geonetwork/core-geonetwork/pull/6517
If user want to configure the default PDF export based on the browser print capability, configure the downloadFormatter for PDF without URL:
```js
downloadFormatter: [
{
label: "exportMEF",
url: "/formatters/zip?withRelated=false",
class: "fa-file-zip-o"
},
{
label: "exportPDF",
class: "fa-file-pdf-o"
},
```
To be discussed: this should be the default ?

Record view / PDF export based on browser capability

---

web-ui/src/main/resources/catalog/components/common/map/mapService.js

Most of the time only a bounding box is provided in metadata records but sometimes bounding polygons are also used. Add the possibility to return the bounding polygon if available for a metadata record. For the time being, this is only rendered in the record view. 
For search results, only the bounding box is rendered (as bounding polygon can increase a lot the search response size). If some user wants to highlight polygons in the small map, they can add the `shape` field in the `gnESFacet` include list.
Test record https://www.geocat.ch/geonetwork/srv/api/records/3ff2557b-5465-460f-958a-7b1c7eb4058d/formatters/iso19139?output=xml&approved=true

Record view / Display bounding polygon if set

---

web-ui/src/main/resources/catalog/components/elasticsearch/directives/FacetDirective.js
web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facet-cards.html
web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facet-tab.html
web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facet.html
web-ui/src/main/resources/catalog/js/CatController.js
web-ui/src/main/resources/catalog/views/default/templates/home.html

Only terms aggregation was supported.
Example:
```json
{
"mods": {
"home": {
"facetConfig": {
"availableInServices": {
"filters": {
"filters": {
"availableInViewService": {
"query_string": {
"query": "+linkProtocol:/OGC:WMS.*/"
}
},
"availableInDownloadService": {
"query_string": {
"query": "+linkProtocol:/OGC:WFS.*/"
}
}
}
},
"meta": {
"decorator": {
"type": "icon",
"prefix": "fa fa-2x pull-left ",
"map": {
"availableInViewService": "fa-globe",
"availableInDownloadService": "fa-download"
}
}
}
},
```
render as
User may configure a custom facet with some include/exclude config to
only collect statistics on some values eg.
```json
{
"onlySomeGroup": {
"terms": {
"field": "groupOwner",
"include": "101|102"
},
"meta": {
"orderByTranslation": true,
"field": "groupOwner"
}
},
```
In this case, …

Aggregation improvements

---

core/src/main/java/org/fao/geonet/kernel/security/GeonetworkAuthenticationProvider.java
services/src/main/java/org/fao/geonet/api/users/UsersApi.java
services/src/main/java/org/fao/geonet/api/users/validation/UserDtoValidator.java

When pre-creating users for other authentication methods such as keycloak, passwords are not required so we should allow null passwords.

Allow for null passwords when creating user via api.

---

domain/src/main/java/org/fao/geonet/domain/InspireAtomFeed.java
domain/src/main/java/org/fao/geonet/repository/specification/MetadataSpecs.java

- Update JPA specification to filter metadata with schemas based on iso19139 also.
- Atom feed parse: truncate fields longer than the database related fields.
Related to https://github.com/geonetwork/core-geonetwork/pull/5472

[FP] INSPIRE Atom fixes

---

web-ui/src/main/resources/catalog/js/edit/DirectoryController.js

Group is mandatory so select the preferred or the first one. If there is only one group, the group combo is not displayed and it was not possible to create a new entry.

Directory / Select preferredGroup or the first one

---

web-ui/src/main/resources/catalog/components/elasticsearch/EsFacet.js
web-ui/src/main/resources/catalog/components/elasticsearch/LuceneQueryParser.js
web-ui/src/main/resources/catalog/components/elasticsearch/directives/FacetDirective.js
web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facet-tab.html
web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facet.html
web-ui/src/main/resources/catalog/components/search/searchfiltertag/SearchFilterTagsDirective.js
web-ui/src/main/resources/catalog/components/search/searchfiltertag/partials/searchFilterTagsTemplate.html
web-ui/src/main/resources/catalog/js/CatController.js
web-ui/src/main/resources/catalog/templates/admin/admin.html
web-ui/src/main/resources/catalog/views/default/module.js

Some inconsistencies which may require some more work:
* Histogram aggregation can also produce unexpected results. When clicking on a range, the histogram is computed for that range and the records on the set may be smaller or different depending on the interval. Maybe we should not reload histogram facet like for term agg ?

Search / Aggregations minor improvements

---

web-ui/src/main/resources/catalog/components/common/openlayers/olProfileDirective.js
web-ui/src/main/resources/catalog/components/common/openlayers/olProfileService.js

Closure was removed in https://github.com/geonetwork/core-geonetwork/commit/13c503a4b74e46ad188337f45c4f5e9f410bd5c1 but not all usages.

Map / Profile directive / remove goog calls

---

core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java

When a field only contains one value, Elasticsearch makes it a string by default. Force it to always be indexed as array (some client apps don't want to rework the response).

Index / Force linkProtocol to be an array

---

web/src/main/webapp/xslt/common/index-utils.xsl

Some metadata producers encode multilingual content without using `gco:CharacterString` or `gcx:Anchor` for the main language. eg.
```xml
<gmd:title xsi:type="gmd:PT_FreeText_PropertyType">
<gmd:LocalisedCharacterString locale="#FR">GEOLOGIE DES SONDAGES</gmd:LocalisedCharacterString>
<gmd:LocalisedCharacterString locale="#EN">GEOLOGIE DES SONDAGES</gmd:LocalisedCharacterString>
<gmd:LocalisedCharacterString locale="#DE">GEOLOGIE DES SONDAGES</gmd:LocalisedCharacterString>
<gmd:LocalisedCharacterString locale="#IT">GEOLOGIE DES SONDAGES</gmd:LocalisedCharacterString>
<gmd:LocalisedCharacterString locale="#RM">GEOLOGIE DES …
```

Indexing / Multilingual records / Ensure default field contains a value

---

web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js
web-ui/src/main/resources/catalog/components/utility/UtilityService.js
web-ui/src/main/resources/catalog/js/CatController.js
web-ui/src/main/resources/catalog/views/api/index.html
web-ui/src/main/resources/catalog/views/api/index_debug.html
web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v423/migrate-default.sql
web/src/main/webapp/xslt/base-layout-cssjs-loader.xsl

Follow up of https://github.com/geonetwork/core-geonetwork/pull/5579.
The same URL is used in sitemap and on client side permalink popup. Default permalink is a link pointing to the API (and not the client app with the UUID after the # which makes the information not available server side and no redirect easy to setup).
The permalink points to an HTML page containing the JSON-LD representation needed for structured data indexing for SEO.
Also relate to discussion in https://github.com/geonetwork/core-geonetwork/issues/6553
The next step is probably to use the point of truth defined in the metadata record if any instead (eg. DOI).

Permalink / Set link URL as in sitemap.

---

web-ui/src/main/resources/catalog/components/search/mdview/mdviewService.js

* When computing stats on members, only return the UUID of each records in top_hits (https://www.elastic.co/guide/en/elasticsearch/reference/8.5/search-aggregations-metrics-top-hits-aggregation.html#_example_6)
* Only request stats when there is at least one record in an associated types
This reduce a lot response time and size for collecting statistics. Associated records details were already available using the search API (only the UUID is used to find which records are in which categories).
Example for a serie having 100 members

Record view / Series member statistics improvement

---

services/src/main/java/org/fao/geonet/api/reports/ReportDownloads.java

The file download report displays some information about the related file upload, but if the file was uploaded to a metadata before the feature to track file uploads / downloads was implemented, can happen that there is no file upload.
This code change, checks if the file upload is present to retrieve the related information instead of causing an exception.

Report file download - check if related file upload is available

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/dispatcher.xsl
schemas/iso19139/src/main/plugin/iso19139/layout/dispatcher.xsl
web/src/main/webapp/xslt/ui-metadata/form-configurator.xsl

* Standard / ISO19115-3 / Formatter / Fix citation
* Standard / ISO19115-3 / Indexing / Index also link which can be in a distributor.
* Editor / Configuration / Override label is optional.
Sample configuration:
```
<action type="add" name=" " btnLabel="Add the resource identifier"
if="count(*/mdb:identificationInfo/*/mri:citation/*/cit:identifier) = 0"
or="identifier" in="/*/mdb:identificationInfo/*/mri:citation/*">
<template>
<snippet>
<cit:identifier>
<mcc:MD_Identifier>
<mcc:code>
<gco:CharacterString>https://data.organisation.net/geo/code-year-edition</gco:CharacterString>
</mcc:code>
</mcc:MD_Identifier>
</cit:identifier>
</snippet>
</template>
</action>
<field xpath="/*/mdb:identificationInfo/*/mri:citation/*/cit:identifier/*/mcc:code"
name="Resource identifier"
del="../.."/>
``` …

Standard / ISO19115-3 and editor config improvement

---

web-ui/src/main/resources/catalog/components/common/map/mapService.js

Test case:
1) Load the `iso19139` sample metadata
2) In the search page, do an empty search. In the Javascript console appears the following error and not all the metadata results bounding boxes are rendered in the search map:
```
lib.js?v=577a655b8e2174e205ebbb6e236357f799970a5c:133 TypeError: Cannot read properties of null (reading 'addEventListener')
at q (lib.js?v=577a655b8e2174e205ebbb6e236357f799970a5c:669:25851)
at e.listenGeometriesChange_ (lib.js?v=577a655b8e2174e205ebbb6e236357f799970a5c:669:474835)
at new e (lib.js?v=577a655b8e2174e205ebbb6e236357f799970a5c:669:474535)
at Object.getBboxFeatureFromMd (gn_search_default.js?v=577a655b8e2174e205ebbb6e236357f799970a5c&:604:44)
at gn_search_default.js?v=577a655b8e2174e205ebbb6e236357f799970a5c&:1258:262
at …
```

Fix retrieve of  metadata bbox to display in the search map when the metadata doesn't have a bounding box

---

schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl

eg. load this multilingual record https://sextant.ifremer.fr/Donnees/Catalogue#/metadata/59403137-7fc9-45b7-9b1b-e63883f3c4b8
Turn off table rendering for CI_ResponsibleParty in config-editor.
Check the formatter http://localhost:8080/geonetwork/srv/api/records/59403137-7fc9-45b7-9b1b-e63883f3c4b8/formatters/xsl-view?language=all&tab=default. Organisation name and address are displayed in both languages as text instead of `div`s with `xml:lang` attribute
After

Formatter / Multilingual / Organisation name not translated.

---

csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/es/CswFilter2Es.java
web/src/main/webapp/WEB-INF/config-csw.xml

Most of the mapping done between OGC CSW queryable to Elasticsearch index fields was targeting `.default` properties (which means the default record language).
eg. Loading https://www.geocat.ch/geonetwork/srv/api/records/87380db7-36c1-4ae6-b9fe-2fe49799707a/formatters/iso19139?output=xml&approved=true
and using query like
```xml
<csw:GetRecords xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" service="CSW" version="2.0.2" maxRecords="10" startPosition="1" outputFormat="application/xml" outputSchema="http://www.opengis.net/cat/csw/2.0.2" resultType="results">
<csw:Query typeNames="csw:Record">
<csw:ElementSetName>summary</csw:ElementSetName>
<csw:Constraint version="1.1.0">
<ogc:Filter xmlns:ogc="http://www.opengis.net/ogc">
<ogc:PropertyIsLike escapeChar="\" singleChar="_" wildCard="%"> …
```

CSW / Improve search on multilingual content.

---

wro4j/src/main/java/org/fao/geonet/wro4j/GeonetWro4jFilter.java

Some bots are spamming application with calls like `/geonetwork/static/dut/qi?....`
In such case, WRO4J log the exception about the invalid cache key
```
2022-12-15T09:28:56,639 ERROR [ro.isdc.wro.http.WroFilter] - Exception occured
ro.isdc.wro.WroRuntimeException: Cannot build valid CacheKey from request: /geonetwork/static/dut/qi
at ro.isdc.wro.manager.ResourceBundleProcessor.getSafeCacheKey(ResourceBundleProcessor
```
But it also chain to other filters by default "The default implementation proceeds with filter chaining when exception is thrown." which in the above URL may also match the `GenericFilter` which tries to do something. Also raised in https://github.com/wro4j/wro4j/issues/1013, it does not make sense to chain filter in case of exception in our case. Return 404.

WRO4J / Do not chain filters on exception

---

core/src/main/java/org/fao/geonet/lib/NetLib.java
pom.xml
services/pom.xml
services/src/main/java/org/fao/geonet/api/records/extent/BaseMapRenderer.java
services/src/main/java/org/fao/geonet/api/records/extent/BaseMapRenderingEngine.java
services/src/main/java/org/fao/geonet/api/records/extent/GetMapBaseMapRenderer.java
services/src/main/java/org/fao/geonet/api/records/extent/MapRenderer.java
services/src/main/java/org/fao/geonet/api/records/extent/WMTSBaseMapRenderer.java
services/src/main/java/org/fao/geonet/api/records/extent/WMTSClient.java
services/src/test/java/org/fao/geonet/api/records/extent/GetMapBaseMapRendererTest.java
services/src/test/java/org/fao/geonet/api/records/extent/WMTSBaseMapRendererTest.java
web/src/main/webResources/WEB-INF/config-spring-geonetwork.xml

NOTE: I noticed that the https proxy settings where NOT being set anywhere - so I update them at the same time as the http settings - see NetLib.java.
NOTE: this also updates GT to a newer version (required for recent changes to the GT WMTS code).  This will need to go to 28.0 when Geotools releases it.  This is a minor upgrade.
This allows for WMTS background maps for /extents.png and /geom.png - currently only WMS GetMap is supported.
For backwards compatibility, I didn't change how to WMS GetMap is used.  
If you want to use WMTS, you need to configure with a little JSON string like this (config-spring-geonetwork.xml);
```
<util:map id="regionGetMapBackgroundLayers">
<entry key="osm" value="\${map.bbox.background.service}"/>
<entry key='myserver.wmts.basemap'
value='{ …
```

changes for WMTS /extents.png and /geom.png

---

core/src/main/java/org/fao/geonet/api/records/attachments/CMISStore.java

When create a metadata in cmis mode, for error like this:
The issue is backend cmis resource were not created.

create resource folder if missing during metadata loading.

---

web-ui/src/main/resources/catalog/components/search/mdview/partials/keywordBadges.html

Test case:
1) Create a multilingual iso19139 metadata with the main language as English and add a free-text keyword, filling the English and French entries with different values.
2) With the English UI, in the metadata detail page, filter by the keyword value --> Search results display the metadata (ok)
3) With the French UI, in the metadata detail page, filter by the keyword value --> Search results doesn't display the metadata (no ok)

Fix keyword badges filters with multilingual metadata

---

services/src/main/java/org/fao/geonet/api/users/UsersApi.java

Update userapi so that it will allow administrators to pre-create/update user profile information when using service provider
In certain cases (i.e. migration) administrators may need to pre-create users to assign metadata to users. Also updated the profile comparisons so that they are safe comparisons

Update userapi so that it will allow administrators to pre-create/update user profile information when using service provider

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/collection-updater.xsl
schemas/iso19139/src/main/plugin/iso19139/process/collection-merge-utility.xsl
schemas/iso19139/src/main/plugin/iso19139/process/collection-updater.xsl

Extent can contains boxes, geographic desc, polygons or temporal extent. Previous mechanism was not able to properly group elements when an extent contains more than one type. Improve that by processing each types rather than trying to group the extent container element.
Follow up of https://github.com/geonetwork/core-geonetwork/pull/6368.
Series updated by this process will have one extent block with the list of unique extents - geographicElement or temporalElement.
Sort by merging key

Standard / ISO / Collection updater / Better grouping of various type of extent.

---

web-ui/src/main/resources/catalog/components/common/map/print/PrintMapDirective.js

Using the `moveend` event instead of `change:resolution` which is triggered during animation but not at the end (cf. https://github.com/openlayers/openlayers/issues/7402#issuecomment-340776170).
The scale of the PDF was not updated.
Test:
* map > print the map
* zoom in
* print the map - both maps have same extent.

Map / PDF / Extent not always correct

---

web-ui/src/main/resources/catalog/components/elasticsearch/directives/FacetDirective.js

Currently the status workflow facet in the Editor board displays the codes instead of the labels.
With this change, the correct labels are displayed:

Fix status workflow facet labels

---

web-ui/src/main/resources/catalog/components/search/resultsview/ResultsviewDirective.js

When the metadata extent has a much bigger extent than the search map extent (for example, when the map covers a country area and the metadata covers the full world), the search map is not displayed properly:
With this fix, in these cases, the search map zooms to the map extent:

Search map - if the metadata results extent is bigger than the map view extent, zoom to the view extent

---

web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
web-ui/src/main/resources/catalog/components/utility/UtilityService.js
web-ui/src/main/resources/catalog/js/admin/DashboardStatusController.js
web-ui/src/main/resources/catalog/locales/en-v4.json
web-ui/src/main/resources/catalog/templates/admin/dashboard/status.html

While fixing indexing errors, user may need to easily get the UUID of affected records. Add a button to easily copy the list of UUID in current search.

Admin / Indexing errors / Add copy uuids to clipboard.

---

.gitignore
pom.xml
web-ui/src/main/resources/catalog/templates/admin/harvest/type/oaipmh.js
web/pom.xml
web/src/main/webResources/WEB-INF/web.xml
web/src/main/webResources/WEB-INF/wro-maven.properties
web/src/main/webapp/WEB-INF/wro-sources-maven.xml
wro4j/Readme.md
wro4j/src/main/java/org/fao/geonet/wro4j/DiskbackedCache.java
wro4j/src/main/java/org/fao/geonet/wro4j/GeonetLessCompilerProcessor.java
wro4j/src/main/java/org/fao/geonet/wro4j/GeonetWro4jFilter.java
wro4j/src/main/java/org/fao/geonet/wro4j/GeonetWroModelFactory.java
wro4j/src/main/java/org/fao/geonet/wro4j/GeonetworkMavenNoTestsWrojManagerFactory.java
wro4j/src/main/java/org/fao/geonet/wro4j/GeonetworkWrojManagerFactory.java
wro4j/src/main/java/org/fao/geonet/wro4j/TemplatesUriLocator.java

WRO4J cache is store in an H2 database in the data directory of the catalogue. It is populated on demand when clients (ie. browser) request CSS or JS resources. Building the resources can take a bit of time on first load. To improve user experience on first load of the application, this proposal build the main resources and populate a prebuilt cache for the current version.
Use the `wro4j-prebuild-cache` maven profile for building the WRO4J cache in build time:
```shell
mvn clean install -Pwro4j-prebuild-cache
```
When the catalog starts, the prebuilt cache (stored in `WEB-INF/prebuilt`) is replaced in the data directory if:
* the data directory doesn't contain a wro4j-cache database
* or the git version stored in the data directory (in `git.properties`) doesn't match the GeoNetwork's git …

JS & CSS / Cache / Add a profile to prebuilt the wro4j-cache

---

core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java

Optimisation to ignore the mail notification logic on metadata status changes, when there are no users to notify.

Metadata status change: don't execute mail notification logic if there are no users to notify

---

web-ui/src/main/resources/catalog/components/common/share/ShareDirective.js
web-ui/src/main/resources/catalog/components/common/share/partials/panel.html

The check all action was inverted.
Set the initial value depending on the max number of checked operations.
Issue introduce with https://github.com/geonetwork/core-geonetwork/pull/6693 and changes on the order of execution of directive.

Sharing / Fix check all options.

---

web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/editor.html

This PR makes the toolbar on the editor dashboard accessible by keyboard. The `privileges` and `delete` button didn't get the keyboard focus when using the `TAB` key on the page
Done:
Add `href` to the `<a>` element to make the link accessible by keyboard

[a11y] Make the toolbar on the editor dashboard accessible by keyboard

---

schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl

eg. https://beta.metadata.vlaanderen.be/srv/dut/catalog.search#/metadata/9f0ef2ea-49a3-454e-9685-8cace422cd11
```xml
<gmd:distributionFormat>
<gmd:MD_Format>
<gmd:name>
<gmx:Anchor xlink:href="http://publications.europa.eu/resource/authority/file-type/SHP">Esri Shape</gmx:Anchor>
</gmd:name>
<gmd:version gco:nilReason="unknown">
<gco:CharacterString/>
</gmd:version>
</gmd:MD_Format>
</gmd:distributionFormat>
```

Standard / ISO19139 / Indexing distribution format encoded using Anchor

---

web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v400/migrate-db-default.sql
web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v400/migrate-db-sqlserver.sql

Using the Pages API with a migrated database from 3.x, returns the following error:
```
{"message":"HttpMessageNotWritableException","code":"runtime_exception","description":"Could not write JSON: could not extract ResultSet; nested exception is com.fasterxml.jackson.databind.JsonMappingException: could not extract ResultSet (through reference chain: java.util.ArrayList[0]->org.fao.geonet.api.pages.PageJSONWrapper[\"sections\"])"}% 
```
It seems due to the JPA upgrade in GeoNetwork 4, the columns of the `SPG_Sections` table have change:
Migrated database:
New database:
This pull request adds the migration script to rename the columns.
Users that have already migrated to version 4.2.x, should apply the SQL manually,

Fix Pages API in migrated databases

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/tpl-csv.xsl
schemas/iso19139/src/main/plugin/iso19139/layout/tpl-csv.xsl

Resource identifier is quite often used by end users for managing datasets and frequently ask for them in the CSV export for further analysis.

Export / CSV / Add resource identifier.

---

schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl

It makes it more consistent with 19115-3.

Standard / ISO19139 / Indexing / Add ordering instruction

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index-subtemplate.xsl
schemas/iso19139/src/main/plugin/iso19139/index-fields/index-subtemplate.xsl
web-ui/src/main/resources/catalog/locales/en-editor.json

Event if not recommended from an INSPIRE point of view, some subtemplates may contain only organisation name without individual or mail. In such case an empty () was added in the title.
Before
After
Also clarify label - directory entry can add contact or organisation

Subtemplate / Indexing / Do not add () on title if no name and no mail.

---

pom.xml
web/src/main/webResources/WEB-INF/data/config/index/records.json

Some request may not work on long abstract for example due to this parameter:
```
GET gn-records/_search
{
"query": {
"query_string": {
"fields": ["resourceAbstractObject.langfre.keyword"],
"query": "*bisse*"
}
},
"_source": ["resourceAbstractObject.langfre"]
}
```
See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/ignore-above.html.
It does not affect full text search which does analysis but more some advanced query on more precise fields like the one above.

Indexing / Add option to configure ignore_above.

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/utility-tpl.xsl

ISO19115-3 record may contain a feature catalogue embedded. Be sure the main resource type is indexed first as we use it for the main icon cf. https://github.com/geonetwork/core-geonetwork/blob/main/web-ui/src/main/resources/catalog/views/default/templates/recordView/title.html#L3
and we may use other resource   types in search (eg. when linking a feature catalogue)
Also fix display of title in the editor toolbar for feature catalogue
And fallback to first typename if no `cat:name` element.
Test record:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<mdb:MD_Metadata xmlns:mdb="http://standards.iso.org/iso/19115/-3/mdb/2.0"
xmlns:cat="http://standards.iso.org/iso/19115/-3/cat/1.0"
xmlns:gfc="http://standards.iso.org/iso/19110/gfc/1.1" …
```

Standard / ISO19115-3 / Index main resource type first

---

web-ui/src/main/resources/catalog/js/edit/BatchEditController.js
web-ui/src/main/resources/catalog/locales/en-v4.json
web-ui/src/main/resources/catalog/templates/editor/batchedit.html

This allows to only trigger the edit based on a condition eg. insert a distributor if none present
The parameter was already defined in the API (and used frequently in the harvester batch editing)

Batch editing / Add condition API parameter.

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/link-utility.xsl

If records contains multiple quality reports, indexing error are reported
eg.
```xml
<mdb:dataQualityInfo>
<mdq:DQ_DataQuality>
<mdq:scope>
<mcc:MD_Scope>
<mcc:level>
<mcc:MD_ScopeCode codeList="http://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#MD_ScopeCode"
codeListValue="series"/>
</mcc:level>
</mcc:MD_Scope>
</mdq:scope>
<mdq:standaloneQualityReport>
<mdq:DQ_StandaloneQualityReportInformation>
<mdq:reportReference>
<cit:CI_Citation>
<cit:onlineResource>
<cit:CI_OnlineResource>
<cit:linkage>
<gco:CharacterString>http://www.osi-saf.org/</gco:CharacterString>
</cit:linkage>
<cit:protocol>
<gco:CharacterString>WWW:LINK</gco:CharacterString>
</cit:protocol>
<cit:name>
<gco:CharacterString>Radiative fluxes over Indian Ocean from METEOSAT-8 data, validation …
```

Standard / ISO19115-3 / Indexing multiple quality reports

---

core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java

Was done only when a batch of records was indexed.
To test: 
* import a document with overview, 
* check the doc in the index http://localhost:9200/gn-records/_doc/6244937d-1c2c-47f5-bdf1-33ca01ff1715 (it use to have only overview url and not the base64 encoded small image)

Indexing / Build overview data also when commiting one document

---

web/src/main/webapp/WEB-INF/classes/log4j2.xml
workers/wfsfeature-harvester/src/main/java/org/fao/geonet/harvester/wfsfeatures/worker/EsWFSFeatureIndexer.java
workers/wfsfeature-harvester/src/main/java/org/fao/geonet/harvester/wfsfeatures/worker/WFSClientWithStrategyInvestigator.java
workers/wfsfeature-harvester/src/main/java/org/fao/geonet/harvester/wfsfeatures/worker/WFSHarvesterExchangeState.java

* Avoid NPE on Instant type - set field value to null
```
"Feature BIGOOD_prelevements#45581/id:fid-65ee4ab8_185f3393a14_3211: 
Cannot read attribute SAMPLING_DATE, value Instant{}.
Exception is: null"
```
* Set log level to debug so that user can get some info in the log about the progress (at some point we may make dedicated log file like in other harvester)
* Fix sonarlint reports

Harvester / WFS features / Debug, Instant NPE, cleanup.

---

core/src/main/java/org/fao/geonet/web/CORSResponseFilter.java
web/src/main/webResources/WEB-INF/web.xml

* CORS Filter / Unset list of host when db settings is empty
When saving from the admin > settings, the value of the settings is set to "" and not null. Reset CORS config when list of hosts is cleared on db mode.
* CORS / Set headers before rewriting URL
We may have to rewrite old URL forwarding to new URLs and in such case we need to set CORS header first before the rewrite is made.
If not, website on another domain may get a CORS error due to unset header on rewritten resources.

CORS Filter improvements

---

web-ui/src/main/resources/catalog/templates/admin/classification/thesaurus.html

When clicking related keywords, popup was not updated properly

Admin / Thesaurus / Fix navigation between keywords

---

.github/workflows/linux.yml

Ubuntu 18.04 is deprecated and it will be removed from Github actions.
This commit repaces it by Ubuntu 22.04.
See https://github.com/actions/runner-images/issues/6002 for more info.

Update GH Actions base image to Ubuntu 22.04

---

web/src/main/webResources/WEB-INF/data/config/index/records.json

cf. https://en.wikipedia.org/wiki/English_terms_with_diacritical_marks

need ascii folding for en

---

harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java

The code was commented, pending to migrate it to use ElasticSearch to find the metadata identifiers that have an specific resource identifier.

CSW harvester - migrate to ElasticSearch the found duplicated resource feature

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout-custom-fields.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/schematron/schematron-rules-iso.sch

Editing an ISO19115-3 metadata with multiple `gex:polygon` inside the element `gex:geographicElement/gex:EX_BoundingPolygon` (what is valid according to the xsd):
https://github.com/geonetwork/core-geonetwork/blob/41a435f181177021ff1d7b2bd80d4eb3b73ab7b5/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/schema/standards.iso.org/19115/-3/gex/1.0/extent.xsd#L20-L32
```
<gex:geographicElement>
<gex:EX_BoundingPolygon>
<gex:polygon>
<gml:MultiSurface srsName="urn:ogc:def:crs:EPSG:6.6:4326">
<gml:surfaceMember>
<gml:Polygon srsName="urn:ogc:def:crs:EPSG:6.6:4326">
<gml:exterior>
<gml:LinearRing srsName="urn:ogc:def:crs:EPSG:6.6:4326">
<gml:posList srsDimension="2">21.736539949711826 5.635986328125005 -14.271037745292759 22.73895263671875 -5.453326108568561 53.779449462890604 …
```

ISO19115-3 / Metadata editor / Support gex:EX_BoundingPolygon with multiple gex:polygon elements

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/schema-ident.xml
schemas/iso19139/src/main/plugin/iso19139/schema-ident.xml

Test case:
1) Import the provided metadata containing 
```
<mdb:contact gco:nilReason="withheld">
```
2) Publish it
3) With a logged user, request the XML document and check that the metadata contains the element and it's content.
4) With an unlogged user request the XML document and check that the metadata does not contain the element and it's content --> NO OK: without the fix, this is not the case.
---
Test metadata: [contact-withheld.txt](https://github.com/geonetwork/core-geonetwork/files/10802123/contact-withheld.txt)

Update metadata schemas xpath filters to avoid skipping the elements at the first level

---

schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl

Fix the indexing of the alternate title for a resource.
Fixes #6859.

Schema plugins / iso19139 / Fix alt title indexing

---

web-ui/src/main/resources/catalog/views/default/directives/directive.js

The reset search fields was not resetting the values of the date filters in the advanced search form.
Update the directive to listen to the `resetSelection` event and clear the date fields:

Advanced search form: reset date filter fields

---

core/src/main/java/org/fao/geonet/util/LogUtil.java
harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java
inspire-atom/src/main/java/org/fao/geonet/inspireatom/harvester/InspireAtomHarvester.java

Related to https://github.com/geonetwork/core-geonetwork/pull/6395
The code to initialise the INSPIRE Atom harvester log was not updated to use log4j2, causing an exception when trying to execute it.

Update INSPIRE Atom harvester log configuration to use log4j2

---

services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java

We don't really know when this could happen (eg. timeout on validation?).
Fixes https://github.com/geonetwork/core-geonetwork/issues/6864
In that case, history was not displayed

Workflow / Avoid NPE on null current validation state

---

web-ui/src/main/resources/catalog/components/elasticsearch/directives/FacetDirective.js

Previously, the INSPIRE Themes in the Home page were displayed always in English:
With the fix, the INSPIRE Themes in the Home page were displayed in the UI language:

Fix language in the directive to display facet cards

---

web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-functions.xsl

**Previously:**
The metadata full view relations doesn't display the metadata related titles.
**With the change:**
---
@fxprunayre the fallback call to `util:getIndexField` to get the `metadataDefaultTitle` it seems exactly the same as the original one to get the title. That's not related to the pull request, but something we should check to fix.

Metadata full view - fix display of related metadata titles

---

web-ui/src/main/resources/catalog/components/metadataactions/RelatedResourcesService.js

was causing a template error in the console because of the name used for translation

fix related template if resource has no name

---

services/src/main/java/org/fao/geonet/api/records/MetadataApi.java

Some third party app may be increasing popularity. Return new value on POST and add a GET to retrieve the current popularity.
If not, a new search is required to retrieve the new value.

API / Record / Popularity / GET

---

web/src/main/webResources/WEB-INF/data/config/index/records.json

Add possibility to search by feature type or column name in full text search
eg. Load a feature catalogue from https://sdi.eea.europa.eu/catalogue/srv/eng/catalog.search#/search?query_string=%7B%22resourceType%22:%20%7B%22featureCatalog%22:%20true%7D%7D and search for a column or a type

Index / Feature catalogue / Add type and column names in full text search.

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/common.xsl
schemas/iso19139/src/main/plugin/iso19139/index-fields/default.xsl

For some unclear reason the resources `revision` date month and year were indexed in the fields `createDateMonth` and `createDateYear`. 
The `publication` date month and year were not indexed.
This code changes updates the indexing of iso19139 and iso19115.3-2008 schemas to fix previous issues.

Fix indexing of resource date month / year in iso19139 and iso19115.3-2008 schemas (3.12.x)

---

web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/fileUploader.html
web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/onlinesrcList.html
web-ui/src/main/resources/catalog/components/utility/partials/linklabel.html
web-ui/src/main/resources/catalog/style/gn.less
web-ui/src/main/resources/catalog/style/gn_editor.less

Some users are reporting that it is hard to find link as we don't display the full URL (only in tooltip). Also if the URL ends with a "/" the URL is not displayed as we were displaying the last token after the last "/". So it may be more relevant to display the full URL ? @MichelGabriel any advices ?
Before
After 
We used to display it in one line expanding the item on hover which was also not optimal ...

Editor / Online links / Display full URL.

---

web-ui/src/main/resources/catalog/components/metadataactions/RelatedDirective.js
web-ui/src/main/resources/catalog/components/metadataactions/partials/metadataCard.html
web-ui/src/main/resources/catalog/style/gn.less

Add badge to card layout so that it is similar to search results.
Avoid overlapping watermark on title - move it to the right side
when using config:
```
recordview: {
showStatusWatermarkFor: "obsolete",
```

Record view / Related records / Status badge.

---

services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java

* User has to be at least Editor to search status
* Administrator can search for all
* Other users must use `record` or `uuid` parameters on record they can edit.

Workflow / Restrict search by status to record that user can edit

---

core/src/main/java/org/fao/geonet/api/records/attachments/CMISStore.java
core/src/main/java/org/fao/geonet/resources/CMISConfiguration.java
core/src/main/java/org/fao/geonet/resources/CMISUtils.java

Cmis performance enhancements
- As CMIS calls are slow - reduce cmis calls when inserting and updating properties during adding and updating resources.
- Increase MaxItemsPerPage to 1000 to increase performance when there are over 100 attachments.
- Fix bug with setting IncludeRelationships to none
- Calculate default validation Status once and move to configuration.
- Fixed bug where primary properties were not being copied during resource copy.
- Other minor fixes.

Cmis performance enhancements

---

core/src/main/java/org/fao/geonet/kernel/SchemaManager.java
core/src/main/java/org/fao/geonet/kernel/XmlSerializer.java
core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataUtils.java
core/src/main/java/org/fao/geonet/kernel/mef/ExportFormat.java
core/src/main/java/org/fao/geonet/kernel/schema/MetadataSchema.java
core/src/main/java/org/fao/geonet/kernel/schema/MetadataSchemaOperation.java
core/src/main/java/org/fao/geonet/kernel/schema/MetadataSchemaOperationFilter.java
core/src/main/java/org/fao/geonet/kernel/search/LuceneSearcher.java
core/src/test/java/org/fao/geonet/kernel/XmlSerializerIntegrationTest.java
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/schema-ident.xml
schemas/iso19139/src/main/plugin/iso19139/schema-ident.xml
web/src/main/webapp/xml/validation/schemaPlugins/schema-ident.xsd

Similar to https://github.com/geonetwork/core-geonetwork/pull/6869, but for `3.12.x` to support `withheld` filter elements in Lucene query output.
Also includes:
- Add support for `authenticated` operation in metadata operation filters.
- Fix in the metadata operation filters XPATH expressions in `iso19139` and `iso19115-3.2008` schemas.
- Fix in MEF export formats to withheld elements.
A test case:
1) Edit https://github.com/geonetwork/core-geonetwork/blob/3.12.x/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/update-fixed-info.xsl  and add the following template to withheld all contacts, except the Identification Info > Point of Contact (Contact for the resource).
```xml
<xsl:template match="mdb:contact|cit:citedResponsibleParty|mrd:distributorContact" priority="10">
<xsl:copy> …
```

Support withheld to filter out elements defined in the schema filters configurations in Lucene query output

---

cachingxslt/pom.xml
common/pom.xml
core/pom.xml
pom.xml
web/pom.xml
workers/pom.xml

While ``main`` has made the leap to Log4j 2.x series to work with a supported logging framework; the 3.12.x is presently using the Log4J 1.2 API which has reached end-of-life.
This pull request demonstrates that ``reload4j`` is a suitable drop-in replacement.
I encourage you to read about http://reload4j.qos.ch - the library is supported / maintained by the original author of Log4J 1.x series. Who is also the author of slf4j etc...

reload4j drop-in replacement for Log4J 1.2 API use in 3.12.x branch

---

web-ui/src/main/resources/catalog/components/elasticsearch/EsService.js

In custom UI views, sometimes is required to store information in the url hash, but should be excluded from the queries.
This changes allows to configure additional fields to exclude from the search.
**Example usage** 
In `config.js` of a view, can inject the service to add extra fields that need to be stored in the url hash, but should be excluded from the queries.
```
module.run([
...
"gnESService",
function (
...
gnESService
) {
gnESService.addExcludeField('myCustomField');
...
```

Search / allow to configure additional fields to exclude from searches

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl

If the ElasticSearch field `linkProtocol ` is used for facet filter, it displays the empty value:

Avoid index empty values of online resources protocols. 

---

web/pom.xml

On some build environments `git.properties` was not created and wro4j cache initialization relying on it was triggerring a null pointer exception.
When building activating the `verbose` mode on those environments was also fixing the issue but sounds better to update. 
Updating the `git-commit-id-maven-plugin` fix the issue.

Build / git.properties file not created

---

.github/workflows/mvn-dep-tree.yml

This is a GitHub Action that will generate a complete dependency graph for a Maven project and submit the graph to the GitHub repository so that the graph is complete and includes all the transitive dependencies.

Send Maven dependency tree to Github

---

web/src/main/webapp/xml/csw/test/csw-GetRecordsFilterService.xml
web/src/main/webapp/xml/csw/test/csw-GetRecordsNoFilterValidate.xml

When using `escapeChar` with `PropertyIsLike`, the character should be used to escape the wildcards.

Update CSW GetRecords samples. Fixes #6935

---

web-ui/src/main/resources/catalog/views/default/templates/recordView/footer.html

Currently accessing the metadata detail page for unlogged users, there is a failing request:
https://SERVER/geonetwork/srv/api/records/status/search?type=workflow&type=task&type=event&record=1782&from=0&size=5
```
{"message":"Access denied","code":"forbidden","description":"Access is denied. To access, try again with a user containing more priviledges."}
```
This is related to the record history, should not be requested for users not authorised to view that information.

Record view / don't call records history when not authorised

---

web-ui/src/main/resources/catalog/views/default/directives/directive.js
web-ui/src/main/resources/catalog/views/default/templates/advancedSearchForm/defaultAdvancedSearchForm.html

Currently only was supporting the field `resourceTemporalDateRange`. A new property `fieldName` should be specified with the date field name to query.
This change allows for example to extend the advanced search form to query ranges with other date fields like `creationDateForResource`:
```
<div
data-ng-if="searchObj.params.creationDateForResource"
data-gn-date-range-filter="creationDateForResource"
data-field-name="'creationDateForResource'"
data-field="searchObj.params.creationDateForResource"
class="gn-search-filter-datepicker"
></div>
```

Extend date range filter directive to configure the date field to use

---

web-ui/src/main/resources/catalog/js/LoginController.js
web-ui/src/main/resources/catalog/js/admin/UserGroupController.js

change the method for the password's minLength to be max so if a bigger value than 6 is retrieved from "system.security.passwordEnforcement.minLength" this is taken into account. previously this was set to min, so if you wanted the user to have a password with a minimum length bigger than 6 you had to make code changes. also added a comment to highlight this.

change the method for the password's minLength

---

core/src/main/java/org/fao/geonet/MetadataResourceDatabaseMigration.java

Remove requirement for gmd:fileDescription so that thumbnail urls are transformed when migrating records.

---

web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties

This PR relates to the messages that are triggered when creating a new user with an email or username that already exists. By making the message identical in both cases, and not including the actual value, it makes it much harder for bad actors to enumerate through the users.

Changed the messages about existing users or emails to be identical, to make it harder to enumerate through users

---

web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
web-ui/src/main/resources/catalog/components/viewer/ViewerDirective.js
web-ui/src/main/resources/catalog/components/viewer/partials/mainviewer.html
web-ui/src/main/resources/catalog/js/CatController.js
web-ui/src/main/resources/catalog/locales/en-admin.json

This PR adds a setting to make the map accessible. The setting is off by default.
The accessible map caused some confusion to users because you first need the focus on the map before you can interact with it. Zooming in and out with the mouse doesn't work without the map having focus.
The new setting reverts the map to the old situation by default (direct interaction) and can be switched on to have keyboard interaction when the map has the focus.

Map accessibility setting

---

core/src/main/java/jeeves/services/RegExpReplace.java
core/src/main/java/org/fao/geonet/kernel/security/openidconnect/OidcUser2GeonetworkUser.java
core/src/main/java/org/fao/geonet/kernel/security/openidconnect/SimpleOidcUser.java
domain/src/main/java/org/fao/geonet/domain/Group.java

While integrating GeoNetwork with ACM/IDM, an OpenID connect flavor for Flanders/Belgium, we encountered some issues extending the default OpenID connect implementation of GeoNetwork.   
This PR is for enabling better extendability when it is needed to integrate OpenID with other implementations.

Implement a more extendable openid connect security

---

web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
web-ui/src/main/resources/catalog/components/metadataactions/partials/relatedDropdown.html
web-ui/src/main/resources/catalog/components/metadataactions/partials/relatedSimpleList.html
web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid.html
web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/list.html
web-ui/src/main/resources/catalog/views/default/less/gn_card_default.less

instead of one icon per records with type as tooltip (eg. https://metawal.wallonie.be/geonetwork/srv/eng/catalog.search#/search?query_string=%7B%22resourceType%22:%7B%22series%22:true%7D%7D).
Also applied to dropdown directive for users who use that directive eg.

Search results / List / Associated resource group by title.

---

schemas/config-editor.xsd
web/src/main/webapp/xslt/ui-metadata/form-configurator.xsl
web/src/main/webapp/xslt/ui-metadata/menu-fn.xsl

Add the possibility to create one section per matching elements and then continue configuring some (or all) of the child elements.
eg.
```xml
<section forEach="/gmd:MD_Metadata/gmd:distributionInfo">
<text><h2>Distribution</h2></text>
<section forEach="*/gmd:transferOptions/*/gmd:onLine" name="A link" del=".">
<field xpath="*/gmd:linkage"/>
<field xpath="*/gmd:name" or="name" in="*"/>
</section>
<text><hr/></text>
</section>
```
creates:
This was only feasible previously for simple field using template mode (cf. https://geonetwork-opensource.org/manuals/4.0.x/en/customizing-application/editor-ui/creating-custom-editor.html#adding-a-template-based-field) and was not supporting nested context. 
Inspired by https://github.com/GIM-be/core-geonetwork/commit/f67a1bec22815633126e8ad1430cb30f5b83a …

Editor / Configuration / Add for each support.

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/config-editor.xml

By default, do not configure usage of directory for reference system. Most of the users populate the reference system from the EPSG database (like in ISO19139 editor)
Before
After

Standard / ISO19115-3 / Editor / Reference system from EPSG database

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/extract-uuid.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout-custom-fields.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/update-fixed-info.xsl

* Preserve creation date
eg. while running CSW transaction, the newRecord and createDate flag is not set. More carefully check creation and revision dates and avoid removal of creation date.
```xml
<csw:Transaction service="CSW" version="2.0.2" xmlns:csw="http://www.opengis.net/cat/csw/2.0.2"
xmlns:gml="http://www.opengis.net/gml" xmlns:mmi="http://standards.iso.org/iso/19115/-3/mmi/1.0"
xmlns:mcc="http://standards.iso.org/iso/19115/-3/mcc/1.0"
xmlns:msr="http://standards.iso.org/iso/19115/-3/msr/2.0"
xmlns:mac="http://standards.iso.org/iso/19115/-3/mac/2.0"
xmlns:cit="http://standards.iso.org/iso/19115/-3/cit/2.0"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0"
xmlns:cat="http://standards.iso.org/iso/19115/-3/cat/1.0" …
```

Standard / ISO19115-3 / Do not alter creation date and allow editing of metadata identifier descriptors

---

web-ui/src/main/resources/catalog/components/common/map/mapService.js

In GeoServer, GetCapabilities may declare layer and style name with namespace when querying the global capabilities but not when querying a workspace capabilities (not sure if this has changed recently or if it a configuration?).
Make style name search more efficient to match style with namespace or not. Some past saved map have been saved with workspace URL with style name with namespace and they now failed to load properly.
Can be tested with:
```xml
<ows-context:OWSContext xmlns:ows-context="http://www.opengis.net/ows-context" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:ows="http://www.opengis.net/ows" version="0.3.1" id="ows-context-ex-1-v3">
<ows-context:General>
<ows:BoundingBox crs="EPSG:3857">
<ows:LowerCorner>-9018920.965841427 -2676700.413346952</ows:LowerCorner> …
```

Map / Context / Style may or may not declare namespace.

---

web-ui/src/main/resources/catalog/components/viewer/gfi/GetFeatureInfoDirective.js
web-ui/src/main/resources/catalog/components/viewer/gfi/partials/featurestables.html

Before, a map with many layers could create many tabs making results hard to read. Also tab was not displaying the same name as in layer manager (style was missing if set).
After:
* Do not display tab if layer has no match
* Add a tab with a summary
* Add a title with full layer name (including style - like in layer manager)

Map / Feature table improvement.

---

schemas/iso19115-3.2018/src/main/java/org/fao/geonet/schema/iso19115_3_2018/ISO19115_3_2018SchemaPlugin.java
schemas/iso19139/src/main/java/org/fao/geonet/schema/iso19139/ISO19139SchemaPlugin.java

This code changes aligns the retrieval of related datasets with indexing strategy.
https://github.com/geonetwork/core-geonetwork/blob/8dd81c5a276437dca2783044aada937772b45308/schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl#L1226-L1246
GeoNetwork uses `uuidref` to store the reference in `srv:operatesOn`, but that's just a convention, other systems usually store the reference in `xlink:href` url.
Without the change the related dataset information is not displayed unless the `uuidref` is the uuid of the dataset metadata, but as indicated that is not always the case.

ISO19139 / ISO19115-3.2008 / use also xlink:href element to identify related datasets 

---

services/src/main/java/org/fao/geonet/api/reports/ReportDownloads.java

The check to verify if the user related to the download exists, was using a wrong variable causing in certain cases a `NullPointerException`.

Metadata file downloads report - fix check to retrieve user related information

---

schemas/config-editor.xsd
schemas/dublin-core/src/main/plugin/dublin-core/layout/config-editor.xml
schemas/iso19110/src/main/plugin/iso19110/layout/config-editor.xml
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/config-editor.xml
schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
services/src/main/java/org/fao/geonet/api/records/editing/MetadataEditingApi.java
web-ui/src/main/resources/catalog/components/metadatamanager/EditorService.js
web-ui/src/main/resources/catalog/js/edit/EditorController.js
web/src/main/webapp/xslt/common/base-variables-metadata.xsl

In `config-editor.xml` add the possibility to define the default view to use (without naming it default). `currTab` parameter is not set to `simple` or `default` by default. Use the tab set as default in the view defined as default to create the default editor form.
Disable the default view if not used.
eg.
```xml
<view name="vl"
default="true"
class="gn-label-above-input gn-indent-bluescale"
displayTooltips="true">
<tab id="vl-identificationTab" default="true" mode="flat">
<section xpath="/gmd:MD_Metadata/gmd:identificationInfo/*/gmd:citation"/>
</tab>
...
<view name="default" disabled="true"
...
```

Editor / Improve default tab configuration.

---

schemas/config-editor.xsd
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout-custom-fields-keywords.xsl
schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields-keywords.xsl
web-ui/src/main/resources/catalog/components/thesaurus/ThesaurusDirective.js

To disable navigation in GEMET use the `browsable` attribute for example, use:
```xml
<thesaurus key="external.theme.gemet"
fieldset="false"
browsable="false"
transformations="to-iso19139-keyword-with-anchor"/>
```
By default, SKOS browser is displayed as before.

Editor / Thesaurus / Add option to display or not the SKOS browser.

---

web/src/main/webapp/xslt/ui-metadata/form-builder.xsl

This issue caused at least for the directive `gnCheckboxWithNilreason` to not select the proper value. 
The html contains breaklines in the supplied value, which causes the directive to not select the correct value:
With the change, the value is selected correctly.

Metadata editor / normalize the values provided to AngularJs directives

---

web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js

When the metadata editor is loaded a javascript error is reported:
```
angular.js?v=09c9c07bf3c4d008d7fc2f9bb1db8d0b06d0346d:15763 TypeError: Cannot read properties of null (reading 'wmsResources')
at OnlineSrcDirective.js:1482:34
at $watchCollectionAction (angular.js?v=09c9c07bf3c4d008d7fc2f9bb1db8d0b06d0346d:19196:13)
at Scope.$digest (angular.js?v=09c9c07bf3c4d008d7fc2f9bb1db8d0b06d0346d:19336:23)
at Scope.$apply (angular.js?v=09c9c07bf3c4d008d7fc2f9bb1db8d0b06d0346d:19696:24)
at done (angular.js?v=09c9c07bf3c4d008d7fc2f9bb1db8d0b06d0346d:13539:47)
at completeRequest (angular.js?v=09c9c07bf3c4d008d7fc2f9bb1db8d0b06d0346d:13796:7)
at XMLHttpRequest.requestLoaded (angular.js?v=09c9c07bf3c4d008d7fc2f9bb1db8d0b06d0346d:13701:9)
```
Related to #6946

Fix related to #6946, scope.config is not ready when the metadata editor is being loaded

---

harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/simpleurl/Harvester.java

Tested using pagination with a CKAN end-point.
Before:
After:

Harvester / Simple URL / Total harvested records when using pagination is incorrect

---

web-ui/src/main/resources/catalog/js/CatController.js
web-ui/src/main/resources/catalog/locales/en-search.json
web-ui/src/main/resources/catalog/views/default/directives/partials/mdactionmenu.html

This PR will disable the publish link in that case so that we see the following
If the workflow is enabled
And we don't  want to allow publishing of non-approved records
Then we are still able to click on the publish link
We just get the following error.

Update publish link so that it is disabled if the metadata has not been approved.

---

csw-server/src/main/java/org/fao/geonet/component/csw/Transaction.java

`Update-fixed-info` was only applied on `Insert` (but not on `Update`).
This was causing an issue on multilingual records as on Insert all namespaces were located on the root element but on Update namespaces were declared when used.
On multilingual records, `lan` namespace was not declared when used on elements declaring `xsi:type` attribute and validation was failing on that. The dispatching of namespaces sounds more related to a JDOM issue not taking into account `xsi:type`.
In any case, it make more sense to be consistent on applying `update-fixed-info` like when using the default open API. The db settings configure if it has to be applied or not.

CSW / Transaction / Consistently apply update-fixed-info

---

pom.xml

Revert b1b3e3d85487d60517c16c233175aff5c5a5c71e
Startup error on Tomcat only - not with Jetty.
```
25-Apr-2023 17:37:00.788 SEVERE [RMI TCP Connection(4)-127.0.0.1] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start: 
org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/geonetwork]]
at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:711)
at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:688)
at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:661)
at …
```

Dependency / Revert camel update triggering issue on Tomcat

---

core/src/main/java/org/fao/geonet/web/GeoNetworkPortalFilter.java
domain/src/main/java/org/fao/geonet/repository/SourceRepository.java

Follow up of https://github.com/geonetwork/core-geonetwork/pull/6970.
Portal redirection was only working fine if name and portal uuid was the same.

Portal redirection / Search portal by uuid not by name.

---

core/src/main/java/org/fao/geonet/web/GeoNetworkPortalFilter.java
web/src/main/webResources/WEB-INF/web.xml

Related to #6970
Update the portal check filter to allow to configure servlet paths to exclude.

Verify the portal requested exists - configure servlet names to exclude

---

web-ui/src/main/resources/catalog/views/default/templates/results.html

When you're scrolled all the way to the bottom of the search page, you need to scroll all the way back to the top to go to the next page. This PR also adds a pagination to the bottom of the page so there's no need to go to the top anymore.

Add pagination to the footer of the search page

---

web-ui/src/main/resources/catalog/views/default/less/gn_topics_default.less

Titles of the Topics on the homepage were breaking in the middle of the word, this PR fixes this by not breaking in the middle of a word anymore
**Before**
**After**

Prevent breaking of topic titles in middle of title

---

services/src/main/java/org/fao/geonet/api/records/formatters/ImageReplacedElementFactory.java
web/src/main/webapp/xslt/skin/default/skin.xsl

Provide some more context to user about the error
```
2023-04-26T12:37:21,072 ERROR [geonetwork] - Error writing metadata to PDF
java.lang.IllegalArgumentException: URI is not absolute
at java.net.URI.toURL(URI.java:1088) ~[?:1.8.0_362]
at org.fao.geonet.api.records.formatters.ImageReplacedElementFactory$UrlImageLoader.loadImage(ImageReplacedElementFactory.java:289) ~[classes/:?]
```
replaced by
```
2023-04-26T12:46:31,470 ERROR [geonetwork] - Error loading image /images/logos/c9c5a394-882a-4520-8011-7f6c11ffaa5a.png for PDF
java.lang.IllegalArgumentException: URI is not absolute
at java.net.URI.toURL(URI.java:1088) ~[?:1.8.0_362]
```
Logging as warning as it is not blocking PDF creation.

PDF / Report image URL in case of error

---

services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
web-ui/src/main/resources/catalog/js/edit/ImportController.js
web-ui/src/main/resources/catalog/templates/editor/import.html

When workflow is enabled, usually extra rules apply to publish records. So don't let the user set those option while importing a new record. Let the record enter the workflow and follow the proper steps.

Import metadata / If workflow is enable hide publish option

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/update-fixed-info.xsl

Same as https://github.com/geonetwork/core-geonetwork/blob/main/schemas/iso19139/src/main/plugin/iso19139/update-fixed-info.xsl#L147-L158
Even if most of the users don't use the parentMetadata for collection/series/partOfSeamlessDatabase relation type and if create child record was removed in https://github.com/geonetwork/core-geonetwork/pull/6708, some users (eg. ifremer) still use this encoding.

Standard / ISO19115-3 / Add same mechanism as ISO19139 for parentIdenfier

---

core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java

On metadata update, `BaseMetadataManager` is calling `update-fixed-info` which set `dateStamp` from metadata table `changeDate` but the table is only updated after in `XmlSerializerDb`. The dateStamp is using the previous changeDate (usually a short time before last edit on an editing session with multiple actions). If user just open the editor and save and close directly, the dateStamp is set to the last editing date (which could be long time ago).
In the index, we expect to have `dateStamp` = `changeDate` but it was not the case.
For testing, edit a record and save and close then check the index fields.

Editing / dateStamp = changeDate on update

---

core/src/main/java/org/fao/geonet/util/XslUtil.java

If URL is not available, this can slow down indexing. Adding a timeout to avoid to wait too long for downloading overview. If not available, the overview URL is used client side instead of the small overview added to the index document.

Indexing / Add timeout when retrieving overview.

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl

Vertical range are gco:Real so index them as numbers and also properly compare negative values.
A record with the following
```xml
<gex:verticalElement>
<gex:EX_VerticalExtent>
<gex:minimumValue>
<gco:Real>-2140.02</gco:Real>
</gex:minimumValue>
<gex:maximumValue>
<gco:Real>-2.5</gco:Real>
</gex:maximumValue>
<gex:verticalCRS/>
</gex:EX_VerticalExtent>
</gex:verticalElement>
```
only the minimum value was indexed due to text comparison.
After the change

Indexing / More robust on negative vertical range.

---

web/src/main/webapp/xslt/common/index-utils.xsl

Fixes for https://github.com/geonetwork/core-geonetwork/issues/7051.
ISO19139 and ISO19115-3 codelist for keyword type is only contains of letters eg. theme, place, discipline. Some users are reporting invalid metadata with keyword title in the keyword type (!) which cause an indexing error. 
Making the indexing more robust on this case only allowing letters and `-_` in codelist type.

Indexing / More robust on invalid thesaurus type

---

web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/linkServiceToDataset.html
web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/linkToMd.html

This issue can be tested from GN 4.0 (https://apps.titellus.net/geonetwork/srv/eng/catalog.search#/home).
Go to link to parent side panel when editing a metadata.
The button was initially disabled.
If we click on it, it shows clickable and enabled.
I placed ng-disabled which is same as adding resource panel to make the button disabled until records are selected.

disable link to parent button to use ng-disabled

---

web-ui/src/main/resources/catalog/components/common/savedselections/SavedSelectionsDirective.js

For logged users, the user selections panel is not displayed:
---
Test case:
1) Login as administrator and enable the `Saved selections` in the `Admin console` > `Settings` > `User interface`
2) Go to the search page, the Basket panel is not displayed
3) Logout and go to the search page, the Basket panel is displayed
With this fix, case 2) is fixed.

Fix display of user selections panel for logged users

---

web-ui/src/main/resources/catalog/views/default/less/gn_result_default.less

Some users are referencing CF standard names (https://cfconventions.org/Data/cf-standard-names/current/build/cf-standard-name-table.html) in keywords which can contains long values and display is not that nice. Improving it.
Create a record with 
```xml
<gmd:descriptiveKeywords>
<gmd:MD_Keywords>
<gmd:keyword>
<gco:CharacterString>altitude_at_top_of_atmosphere_mixed_layer_defined_by_ambient_aerosol_particles_backwards_scattering_by_ranging_instrument</gco:CharacterString>
</gmd:keyword>
<gmd:type>
<gmd:MD_KeywordTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_KeywordTypeCode"
codeListValue="cfstandardname"
codeSpace="ISOTC211/19115"/>
</gmd:type>
</gmd:MD_Keywords>
</gmd:descriptiveKeywords>
```
for testing.
Before
After

Record view / Break keywords with long values

---

web-ui/src/main/resources/catalog/components/viewer/geometry/GeometryDirective.js
web-ui/src/main/resources/catalog/components/viewer/geometry/GeometryService.js
web-ui/src/main/resources/catalog/components/viewer/wps/WpsDirective.js
web-ui/src/main/resources/catalog/components/viewer/wps/WpsService.js
web-ui/src/main/resources/catalog/components/viewer/wps/partials/processform.html

Improve geometry input types:
* Activate only one geometry type at the same time if process has multiple geometry inputs
* Fix controller initialization (related to https://github.com/geonetwork/core-geonetwork/pull/6693)
* Properly set mime type based on format of the features
* Multi geometry support (work done by @jahow for Ifremer)
Before
After
Unfortunately the QGIS WPS server used for testing all types of input is not public but should improve support for all WPS having geometry as inputs.

Map / WPS / Fixes and improvements

---

web/src/main/webResources/WEB-INF/config-db/database_migration.xml
web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v424/migrate-db-default.sql
web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v424/migrate-db-mysql.sql
web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v424/migrate-db-oracle.sql
web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v424/migrate-db-sqlserver.sql

Related to #6788.
If the database contains pages, the Hibernate update doesn't add the `label` column to the `spg_page` as it is defined as not nullable.
Also the section `DRAFT`  was added in the previous version, but no longer exists.

Add migration for static pages

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/fromJsonDkan.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/fromJsonOpenDataSoft.xsl

PR backports the following georchestra PRs upstream:
- https://github.com/georchestra/geonetwork/pull/229
- https://github.com/georchestra/geonetwork/pull/231
- https://github.com/georchestra/geonetwork/pull/239
Sorry for the dev workflow, will try to directly contribute here next time ;-)

[Harvesting] Various ODS/DKAN fixes and improvements

---

web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html

Before the fix, the ui config was display the url html help as follows
After the fix
Note: this issues does not seem to exists in the main branch.

Fix ui config html display

---

web-ui/src/main/resources/catalog/components/common/needhelp/NeedHelpDirective.js
web-ui/src/main/resources/catalog/js/CatController.js

Documentation for 3.12.x has been changed to https://geonetwork-opensource.org/manuals/3.12.x/en. 
For the time being there is a redirect configured from the old url https://geonetwork-opensource.org/manuals/trunk/en/, so previous installations of GeoNetwork work properly.

Update documentation url

---

web/src/main/webapp/xslt/common/base-variables-metadata.xsl

@fxprunayre  
Declaring multiple default tabs in a single view, with a pre-condition to be displayed will cause issue and lead to multiple tabs being shown at once.
```xml
<tab id="tabDataset" default="true" mode="flat" displayIfRecord="count(//dcat:dataset) > 0" hideIfNotDisplayed="true">...</tab>
<tab id="tabDistribution" mode="flat" displayIfRecord="count(//dcat:dataset) > 0" hideIfNotDisplayed="true">...</tab>
<tab id="tabService" default="true" mode="flat" displayIfRecord="count(//dcat:service) > 0" hideIfNotDisplayed="true">...</tab>

Fix multiple default tab in a single view

---

web-ui/src/main/resources/catalog/components/elasticsearch/directives/FacetDirective.js
web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facet-cards.html
web-ui/src/main/resources/catalog/js/CatController.js

Use the facet model for the facet cards as in the search facet component (which takes care of loading keyword translations from the thesaurus based on the key value).
eg. when adding GEMET on home page
```json
"home": {
"facetConfig": {
"th_gemet_tree.key": {
"terms": {
"field": "th_gemet_tree.key",
"size": 10
}
},
```
Before
After

Home page / Aggregations / Fix label for facet based on multilingual thesaurus

---

core/src/main/resources/config-spring-geonetwork.xml
messaging/src/main/resources/config-spring-geonetwork-parent.xml
pom.xml
services/src/main/resources/config-spring-geonetwork.xml
web/src/main/java/org/fao/geonet/DatabaseMigration.java
web/src/main/webResources/WEB-INF/config-db/database_migration.xml
web/src/main/webResources/WEB-INF/config-db/defaultJdbcDataSource.xml
web/src/main/webResources/WEB-INF/config-db/postgres-postgis.xml
web/src/main/webResources/WEB-INF/config-node/srv.xml
web/src/main/webResources/WEB-INF/config-spring-geonetwork.xml
web/src/main/webResources/WEB-INF/config.properties
web/src/main/webResources/WEB-INF/spring-servlet.xml
web/src/main/webapp/WEB-INF/config-security/config-security-ldap.xml
web/src/main/webapp/WEB-INF/config-security/config-security.xml
workers/wfsfeature-harvester/src/main/resources/config-spring-geonetwork.xml

We often have the need to adapt application properties.
Some of the properties are customized using env variables eg. `GEONETWORK_DB_PORT=5433`
or using Java arguments eg. `-Ddb.name=sextant`
In docker, `sed` is also used to set variables in`docker-entrypoint.sh`.
Add the possibility to apply overlay on top of default properties using property files stored in data directory:
* `config/app.properties`
* `config/db.properties`
* `config/security.properties`
so they can persist on update and only contains properties which needs a specific value.
Add the possibility to turn of DB migration on startup if managed using other means (eg. manual SQL update, liquibase). Use ` -Ddb.migration_onstartup=false` to turn it off. It sets Hibernate's `hbm2ddl` to `validate` so any errors with the database …

Config / Add property file overlay.

---

core/src/main/java/org/fao/geonet/util/XslUtil.java
web/src/main/webapp/xslt/base-layout.xsl

Currently HTML head description is set to an empty value. Google is indexing a cookie warning in GeoNetwork case when no HTML head is found (probably because it is the first HTML text content found).
eg.
Use a service metadata record to configure the catalogue title and description:
* for the main node (see admin > settings > record to use for GetCapabilities) 
* for portal.
If no service metadata record configured, default title and description to the node name (or site name for the main portal).
eg. home page with proper title and description:
which can be customized in the service metadata describing the portal
Follow up of:
* https://github.com/geonetwork/core-geonetwork/commit/611be2a0f5a514be9fa3b80a14b0dd785c94dba9
* https://github.com/geonetwork/core-geonetwork/pull/4758
Future …

SEO / Set HTML head title and description

---

core/src/main/java/org/fao/geonet/kernel/setting/Settings.java
services/src/main/java/org/fao/geonet/api/site/SiteApi.java
services/src/main/java/org/fao/geonet/guiservices/util/Env.java
web-ui/src/main/resources/catalog/js/CatController.js
web-ui/src/main/resources/catalog/locales/en-v4.json
web-ui/src/main/resources/catalog/views/default/templates/footer.html
web/src/main/webapp/xslt/base-layout.xsl

When OGC API Records is enabled, display in the footer rss endpoint link(s):

Display footer rss endpoint(s) when OGC API Records service is enabled

---

web/src/main/webResources/WEB-INF/config-spring-geonetwork.xml

Follow up of https://github.com/geonetwork/core-geonetwork/pull/6954
Not sure what is the default value when not set, but changing to update (as create-drop cleanup the schema on startup).
- *validate*: validate that the schema matches, make no changes to the schema of the database, you probably want this for production.
- *update*: update the schema to reflect the entities being persisted
- *create*: creates the schema necessary for your entities, destroying any previous data.
- *create-drop*: create the schema as in create above, but also drop the schema at the end of the session.

DB / Only update schema on startup

---

core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java
services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java

When the metadata workflow is enabled, currently when a metadata status changes to `DRAFT` is send a mail to the metadata author:
https://github.com/geonetwork/core-geonetwork/blob/0f2f2db5e4472735e5b0fc61fb7ef6ca78c78ab4/web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql#L527
There are 2 cases that changes the metadata status to `DRAFT`:
1. When a metadata was submitted and the approval is rejected.
2. When a metadata is approved and it's created a working copy that gets that status.
This change updates the code to only send mail notifications in the 1st case, as the 2on case doesn't make sense to notify when the metadata is edited.

Metadata workflow / send mail notifications for metadata status change to DRAFT when doing a rejection, not when creating a working copy

---

services/src/main/java/org/fao/geonet/api/site/SiteApi.java
services/src/main/java/org/fao/geonet/guiservices/util/Env.java
web-ui/src/main/resources/catalog/views/default/directives/partials/mdactionmenu.html
web/src/main/java/org/fao/geonet/proxy/URITemplateProxyServlet.java
web/src/main/webResources/WEB-INF/web.xml

Follow-up of https://github.com/geonetwork/core-geonetwork/pull/7094.
The targetUri property can be configured using multiple methods, not only as init parameter in `web.xml` servlet's config but also as environment variable, system property or `config.properties` entry. This change saves the targetUri value in a `ServletContext` attribute so it can be retrieved from other servlets to check its value. Added `<load-on-startup>` servlet property to init the attribute on server start.

Fix microservices proxy detection

---

web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js

Fixes the following javascript error when creating / editing online resources in the metadata editor:
```
b.js?v=c45c5f19b136d829dbe12df67e688ce7fd491343:143 TypeError: Cannot read properties of undefined (reading 'forEach')
at H (gn_editor.js?v=c45c5f19b136d829dbe12df67e688ce7fd491343&:2161:266)
at gn_editor.js?v=c45c5f19b136d829dbe12df67e688ce7fd491343&:2162:399
at lib.js?v=c45c5f19b136d829dbe12df67e688ce7fd491343:155:454
at m.$digest (lib.js?v=c45c5f19b136d829dbe12df67e688ce7fd491343:167:67)
at m.$apply (lib.js?v=c45c5f19b136d829dbe12df67e688ce7fd491343:170:484)
at k (lib.js?v=c45c5f19b136d829dbe12df67e688ce7fd491343:121:445)
at v (lib.js?v=c45c5f19b136d829dbe12df67e688ce7fd491343:127:40)
at y.onload (lib.js?v=c45c5f19b136d829dbe12df67e688ce7fd491343:127:464) 'Possibly unhandled …
```

Fix javascript error when creating / editing online resources

---

core/src/main/java/org/fao/geonet/kernel/datamanager/draft/DraftMetadataUtils.java

Follow up of https://github.com/geonetwork/core-geonetwork/pull/5006
Test.
* enable workflow
* create a record
* publish (and approve)
* edit will create a draft
* cancel
* open record view http://localhost:8080/srv/eng/catalog.search#/metadata/5692d7a3-949e-4f27-8fe0-0fa9efd3584e
* open draft view (even if not displayed in record view) http://localhost:8080/srv/eng/catalog.search#/metadraf/5692d7a3-949e-4f27-8fe0-0fa9efd3584e show a records which does not exist in db anymore (due to cancel) but was not properly removed from index.
Also note that if you make some edits in the new draft, the cancel will not remove it (looks to be expected in 5006).

Workflow / On Cancel / Properly remove draft from index

---

core/src/main/java/org/fao/geonet/kernel/GeonetworkDataDirectory.java

When running in a clean data directory we noticed that `manual.json` wasn't copied, due to the `resources/config` not created when starting. This fixed the issue, now making `manual.json` available and enabling the help buttons once again.
@fxprunayre I think this is applicable to the core as well?

Copying the resources/config folder to the data dir

---

web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js

Fixes #7103
I notice when it is used the `DEFAULT_CONFIG` doesn't select the radio button in the dialog:
It's related to this code, that uses the full configuration object for the value:
https://github.com/geonetwork/core-geonetwork/blob/1bd3d8b8cf1cf5cea2d67581fa14ac2cae140967/web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html#L17-L26 
That will not match with any value from the schemas configurations when used `DEFAULT_CONFIG`.
1) Should not be enough to check `process` property only?
2) Maybe when editing an online resource, we don't need to show that section as it's read only? If we create an online resource of type `Add a thumbnail` it's never listed in the resources list, only in the `Overview` panel. So maybe this change makes sense.

Metadata editor / include the metadata file store in the default configuration of the online resources.

---

web/src/main/webResources/WEB-INF/data/config/index/records.json

For some metadata having a conformance title including the word `Date` another dynamic template for dates was matched, causing the following indexing error:
```
ElasticsearchException[Elasticsearch exception [type=mapper_parsing_exception, reason=failed to parse field
[conformTo_INSPIREDatenspezifikationenfrBodennutzung] of type [date] in document with id 
'920eb3af-7e14-48d7-860b-44f6f3a7c1a5'. Preview of field's value: 'false']]; nested: 
ElasticsearchException[Elasticsearch exception [type=illegal_argument_exception, reason=failed to parse date 
field [false] with format [strict_date_optional_time||epoch_millis]]]; nested: ElasticsearchException[
Elasticsearch exception [type=date_time_parse_exception, reason=Failed to parse with all enclosed parsers]];
```
Test case:
1) Create an …

Index configuration / define dynamic template for conformTo_* fields pattern

---

web-ui/src/main/resources/catalog/js/CatController.js
web-ui/src/main/resources/catalog/views/api/index_debug.html

Change for `3.12.x` branch. In `main` branch was fixed.
Currently in `3.12.x` the metadata with any online resource related to `OGC`, for example `OGC:CSW` display in the search results the globe icon to add the "layer" to the map viewer. 
This code change, limits the values to `OGC:WMS` and `OGC:WMTS`.
To fix existing installations, go to Admin console > Settings > User interface. In Search application > List of link types update the map links to:
- `OGC:WMS`
- `OGC:WMTS`
- `ESRI:REST`
Removing the value `OGC`.

Update link type protocol values for map layers

---

web-ui/src/main/resources/catalog/components/elasticsearch/EsFacet.js

Test case: 
1) Load iso19139 samples
2) In the search page change to the List mode
Before:
After:

Return contact information in the search results, used in the results templates

---

web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js

A fix for `3.12.x`. In `main` there are issues with this setting also, but the code is different. A new pull request for `main` will be provided.
Test case:
1) Login as admin 
2) In the user interface settings. Enable the setting `Editor application` > `Only my records`
2) Create an editor user
3) Load the iso19139 samples
4) In the editor board transfer 1 of the records to the editor user
Without the changes:
1) Go to the Editor board (`Only my records` checkbox is enabled) do a search and reset the search --> `Only my records` checkbox is enabled, but the results are not applying the filter.
2) Go to the Import metadata page and select the Editor board page --> `Only my records checkbox` is enabled, but the results are not applying the filter.
The code change fixes these 2 issues.

Fix only my records filter when reset the search in the editor board or access to the editor board from other pages

---

schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl

Test case:
1) Create an iso19139 multilingual metadata
2) Add the following snippet:
```
<gmd:referenceSystemInfo>
<gmd:MD_ReferenceSystem>
<gmd:referenceSystemIdentifier>
<gmd:RS_Identifier>
<gmd:code gco:nilReason="missing" xsi:type="gmd:PT_FreeText_PropertyType">
<gco:CharacterString>http://www.opengis.net/def/crs/EPSG/0/3794</gco:CharacterString>
<gmd:LocalisedCharacterString locale="#SL">http://www.opengis.net/def/crs/EPSG/0/3794</gmd:LocalisedCharacterString>
</gmd:PT_FreeText>
</gmd:code>
</gmd:RS_Identifier>
</gmd:referenceSystemIdentifier>
</gmd:MD_ReferenceSystem>
</gmd:referenceSystemInfo>
```
Without the change, the following error is displayed in the console and the metadata has an indexing error:
```
Error on line 860 of …
```

ISO19139 / Fix indexing of CRS codespace when contains a multilingual value

---

common/src/main/java/org/fao/geonet/utils/Log.java
core/src/main/java/org/fao/geonet/kernel/GeonetworkDataDirectory.java
domain/src/main/java/org/fao/geonet/domain/HarvestHistory.java

The harvester history checks the log file path, but it was using the file name instead of the full path. 
This causes that the harvester history user interface doesn't show the button to download the log file.
With the fix the button is displayed again, allowing to download the log file.
Thanks @fxprunayre for the hints to fix the issue.

Fix check of harvester log file path

---

services/src/main/java/org/fao/geonet/api/processing/report/MetadataProcessingReport.java

Include the parent exception in the MetadataProcessingReport error so that we can see the real error in the logs.

Include the parent exception in the MetadataProcessingReport error

---

.gitignore
core/src/main/java/org/fao/geonet/kernel/security/keycloak/KeycloakPreAuthActionsLoginFilter.java
core/src/main/java/org/fao/geonet/security/web/csrf/GeonetworkCsrfSecurityRequestMatcher.java
core/src/test/java/org/fao/geonet/security/web/csrf/GeonetworkCsrfSecurityRequestMatcherTest.java
web/src/main/webapp/WEB-INF/config-security/config-security-keycloak.xml

* Fix a problem with the Keycloak configuration that was making the server to request CSRF Token for GN URLs that shouldn't be protected by CSRF.
* To do this, now the `GeonetworkCsrfSecurityRequestMatcher` allows to be configured with additional `RequestMatcher` instances, for example the `KeycloakCsrfRequestMatcher`. If Keycloak security is enabled, then the `KeycloakCsrfRequestMatcher` is added to the original GeoNetwork patterns listed in `config-security-core.xml`

Allow multiple request matchers to decide if apply CSRF

---

web/src/main/webapp/WEB-INF/config-security/config-security-mapping.xml

These endpoints were removed from the Spring Security mappings in #6395, that migrated the remote INSPIRE ATOM feed services.
At some moment, we could check to unify the endpoints.

Add Spring Security mappings for local INSPIRE ATOM feed services

---

software_development/BUILDING.md

The link for 'Installing from source code' is broken.  The label of Maintainer Guide is also incorrect and should be Installation Guide.

Fixed broken link for Installing from source code

---

schemas/iso19139/src/main/plugin/iso19139/loc/ger/labels.xml

Test case:
1) Create an iso19139 metadata with the default template
2) Without the change:
3) With the change:

ISO19139 / Metadata editor / Fix display of contact individual name label in German

---

web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html

For source datasets association properties are not returned, the current code displayed an empty block `()`:
@fxprunayre maybe we could display in this case a generic text `Associated resource` or similar instead of just the icon?

Related resources - fix the check to display association information

---

services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
services/src/main/java/org/fao/geonet/api/records/model/MetadataPublicationNotificationInfo.java
services/src/main/java/org/fao/geonet/util/MetadataPublicationMailNotifier.java
services/src/main/resources/config-spring-geonetwork.xml
web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties

When a metadata is published / un-published it can be configured a mail notification.
When the metadata workflow is enabled, published metadata can be edited and re-approved. This change request expands the email notifications in this case, to send an email to let you know that a published metadata has been re-approved, with a new version published.
Related to https://github.com/geonetwork/core-geonetwork/pull/6457
The change request contains also Sonarlint code changes.

Send metadata mail notifications for public metadata when is re-approved

---

software_development/README.md

Another link for 'Installing from source code' is broken.  The label of Maintainer Guide is again incorrect and should be Installation Guide.

Fixed another broken link for Installing from source code

---

web-ui/src/main/resources/catalog/components/viewer/gfi/FeaturesLoader.js

Related to #6801, happens when the column names from the WMS GetFeatureInfo are not in lower case.
Test case:
1) Add this layer to the map: https://data.bev.gv.at/geoserver/INSdataAD/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities
2) Without the change:
3) With the change:

FeatureInfo - lower case columns names to display the table information

---

es/README.md

. eg. > , e.g.,
docer > docker
leacing > leaving
Kabana > Kibana

Fixed typos in es README

---

web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js

Side note : The default list contains all languages, here is a sample SQL to limit languages to the list of languages defined in the app (if modified) 
```sql
DELETE FROM isolanguagesdes
WHERE langid NOT IN (
SELECT id FROM languages
);
DELETE FROM isolanguagesdes
WHERE iddes NOT IN (
SELECT id FROM isolanguages WHERE code IN (
SELECT id FROM languages));
DELETE FROM isolanguages
WHERE code NOT IN (SELECT id FROM languages);
```

UI / Language picker / Display all entries on focus. Search by code and labels

---

web-ui/src/main/resources/catalog/components/common/map/mapService.js
web-ui/src/main/resources/catalog/components/index/IndexDataViewDirective.js
web-ui/src/main/resources/catalog/components/viewer/layermanager/partials/layermanageritem.html
web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextService.js
web-ui/src/main/resources/catalog/components/viewer/searchlayerformap/partials/searchlayerformap.html

Metadata may be multilingual and provide multilingual layer name in the online source description field. GetCapabilities document do not provide multilingual support, so this adds the possibility to translate layer name in maps.
A multilingual description in a link:
```xml
<gmd:onLine>
<gmd:CI_OnlineResource>
<gmd:linkage>
<gmd:URL>https://data.apps.fao.org/map/gsrv/gsrv1/geonetwork/ows?SERVICE=WMS&amp;</gmd:URL>
</gmd:linkage>
<gmd:protocol>
<gmx:MimeFileType type="">OGC:WMS</gmx:MimeFileType>
</gmd:protocol>
<gmd:name xsi:type="gmd:PT_FreeText_PropertyType">
<gco:CharacterString>geonetwork:basins_296</gco:CharacterString>
<gmd:LocalisedCharacterString locale="#EN">geonetwork:basins_296</gmd:LocalisedCharacterString> …
```

Map / Layer manager / Add support for multilingual layer title.

---

software_development/TESTING.md

As the only hint to the integration test maven profile i could find is in the root pom.xml, this could make it easier for people to run the integration tests.

Update TESTING.md to include a hint to the it maven profile

---

web/src/main/webapp/WEB-INF/classes/setup/sql/data/loc-dan-default.sql
web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v425/migrate-default.sql

Regression from PR #6933
This was causing request to urls like /geonetwork/srv/api/records/5bc5b51a-f07f-4cb8-b08f-35fa4b3489b9?language=all to fail because a query would return multiple languages when it only expected one default.

Do not make Danish language a default language.

---

web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html

This is to fix the issue of https://github.com/geonetwork/core-geonetwork/issues/7040
There are some duplicated of tool tip due to the tooltip was added to the recursive input fields instead of a single label. Therefore the tooltip will also be added multiple times.
Here is the after fix look:

Move tooltip from reccusive input field to a single label

---

web/src/main/webapp/xslt/ui-metadata/form-configurator.xsl

When using template field, the label may not be retrieved from translation files.
eg. configuration
```xml
<section>
<field name="sextant-temporalRangeSection"
templateModeOnly="true"
notDisplayedIfMissing="true"
xpath="/mdb:MD_Metadata/mdb:identificationInfo/*/mri:extent/*/gex:temporalElement">
<template>
<values>
<key label="beginPosition"
xpath="gex:EX_TemporalExtent/mri:extent/gml:TimePeriod/*/gml:beginPosition"
use="gn-date-picker"
tooltip="mri:extent|gex:EX_TemporalExtent">
<directiveAttributes data-tag-name="gml:beginPosition"/>
</key>
<key label="endPosition"
xpath="gex:EX_TemporalExtent/mri:extent/gml:TimePeriod/*/gml:endPosition"
use="gn-date-picker"
tooltip="mri:extent|gex:EX_TemporalExtent"
>
data-tag-name="gml:endPosition" …
```

Editor / Template field label fix

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/ISO19139/mapping/defaults.xsl

Backport of https://github.com/ISO-TC211/XML/pull/228
Test:
* Import https://sextant.ifremer.fr/Donnees/Catalogue#/metadata/fed29b44-a074-4025-a23c-dfa59942f458 with 115-3 conversion

Standard / ISO19115-3 / From 19139 conversion / Fix MD_VectorSpatialRepresentation namespace

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/eng/labels.xml
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/fre/labels.xml

It clarifies the context of language fields.

Standard / ISO19115-3 / Better label for metadata language.

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/update-fixed-info.xsl

Only define the language id once language code is defined. 
If not, we can have wrong multilingual widget.
Test:
* create new 115-3 record
* set default language to spanish
* add other language to english
* set title in both languages
* add other language without lang code (it will get the EN id) - and editor do not display title properly.

Standard / ISO19115-3 / Editor / Do not add default lang id

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/utility-fn.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/update-fixed-info.xsl

When updating a metadata record using CSW, revision date could have invalid date type. GeoNetwork always write revision date as dateTime type (to properly order records by change date) but if using the API, user insert records using date type for dates, the wrong type may be introduced.
Test:
* Insert
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<csw:Transaction service="CSW" version="2.0.2" xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:mmi="http://standards.iso.org/iso/19115/-3/mmi/1.0" xmlns:mcc="http://standards.iso.org/iso/19115/-3/mcc/1.0" xmlns:msr="http://standards.iso.org/iso/19115/-3/msr/2.0" xmlns:mac="http://standards.iso.org/iso/19115/-3/mac/2.0" xmlns:cit="http://standards.iso.org/iso/19115/-3/cit/2.0" …
```

Standard / ISO19115-3 / Preserve revision date type.

---

domain/src/main/java/org/fao/geonet/repository/MetadataCategoryRepositoryCustomImpl.java
domain/src/main/java/org/fao/geonet/repository/MetadataRatingByIpRepositoryCustomImpl.java
domain/src/main/java/org/fao/geonet/repository/UserGroupRepositoryCustomImpl.java
domain/src/main/java/org/fao/geonet/repository/UserSavedSelectionRepositoryCustomImpl.java
web-ui/src/main/resources/catalog/components/viewer/gfi/FeaturesLoader.js
web/src/main/java/org/fao/geonet/DatabaseMigration.java
web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v280/MoveHarvesterSettingsToHigherNumber.java
web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v300/SetSequenceValueToMaxOfMetadataAndStats.java
web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v400/UpdateAllSequenceValueToMax.java

SONAR was complaining about possible SQL Injections.
The code affected seems to be in a legacy part of the application.
I used 2 strategies here: 
- Using perpared statements instead of string concatenation. 
- Using //NOSONAR where concat seems to be safely

Fixing SONAR warnings about SQL Injections.

---

core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataUtils.java
core/src/main/java/org/fao/geonet/kernel/setting/SettingManager.java
domain/src/main/java/org/fao/geonet/domain/Language.java
domain/src/main/java/org/fao/geonet/repository/LanguageRepositoryCustom.java
domain/src/main/java/org/fao/geonet/repository/LanguageRepositoryCustomImpl.java
domain/src/test/java/org/fao/geonet/repository/LanguageRepositoryTest.java
services/src/main/java/org/fao/geonet/api/languages/LanguagesApi.java
web/src/main/webapp/WEB-INF/classes/setup/sql/data/loc-ara-default.sql
web/src/main/webapp/WEB-INF/classes/setup/sql/data/loc-cat-default.sql
web/src/main/webapp/WEB-INF/classes/setup/sql/data/loc-chi-default.sql
web/src/main/webapp/WEB-INF/classes/setup/sql/data/loc-dan-default.sql
web/src/main/webapp/WEB-INF/classes/setup/sql/data/loc-dut-default.sql
web/src/main/webapp/WEB-INF/classes/setup/sql/data/loc-eng-default.sql
web/src/main/webapp/WEB-INF/classes/setup/sql/data/loc-fin-default.sql
web/src/main/webapp/WEB-INF/classes/setup/sql/data/loc-fre-default.sql
web/src/main/webapp/WEB-INF/classes/setup/sql/data/loc-ger-default.sql
web/src/main/webapp/WEB-INF/classes/setup/sql/data/loc-ita-default.sql
web/src/main/webapp/WEB-INF/classes/setup/sql/data/loc-nor-default.sql
web/src/main/webapp/WEB-INF/classes/setup/sql/data/loc-pol-default.sql
web/src/main/webapp/WEB-INF/classes/setup/sql/data/loc-por-default.sql
web/src/main/webapp/WEB-INF/classes/setup/sql/data/loc-rus-default.sql
web/src/main/webapp/WEB-INF/classes/setup/sql/data/loc-slo-default.sql
web/src/main/webapp/WEB-INF/classes/setup/sql/data/loc-spa-default.sql
web/src/main/webapp/WEB-INF/classes/setup/sql/data/loc-swe-default.sql
web/src/main/webapp/WEB-INF/classes/setup/sql/data/loc-tur-default.sql
web/src/main/webapp/WEB-INF/classes/setup/sql/data/loc-vie-default.sql
web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v425/migrate-default.sql

The default language value was stored in the `Language` table and also in the `DefaultLanguage` bean.
This code change, removes the related column in the `Language` table, to use the `DefaultLanguage` bean as does other code in the application.
It includes also some Sonarlint improvements.

Remove Language table isdefault column and use DefaultLanguage bean instead

---

schemas/iso19139/src/main/plugin/iso19139/layout/tpl-rdf.xsl

RDF about creation on Distribution class can fail on some multilingual records.
eg https://sextant.ifremer.fr/geonetwork/srv/api/records/8c8c52b3-4b00-4d11-9dad-37edf6395d82/formatters/xml
Test:
```xml
<csw:GetRecordById xmlns:csw="http://www.opengis.net/cat/csw/2.0.2"
service="CSW" version="2.0.2"
outputSchema="http://www.w3.org/ns/dcat#">
<csw:Id>8c8c52b3-4b00-4d11-9dad-37edf6395d82</csw:Id>
</csw:GetRecordById>
```

CSW / DCAT output / Fix for multilingual records

---

software_development/BUILDING.md

The link for 'Maven: The Complete Reference' is broken.

Fixed broken link for Maven Reference

---

web-ui/src/main/resources/catalog/components/search/mdview/partials/keywordBadges.html
web-ui/src/main/resources/catalog/locales/en-v4.json

Clarify link pointing to keyword URL with an info icon and a better label.
Before
After

Record view / Keyword popup / Improve label.

---

web/src/main/webResources/WEB-INF/web.xml

Add the possibility to configure Kibana URL using env variables
eg.
```
-Dgeonetwork.HttpDashboardProxy.targetUri=http://kibana:5601
```
Follow up of https://github.com/geonetwork/core-geonetwork/pull/6356

Configuration / Externalize Kibana configuration

---

index/src/main/java/org/fao/geonet/index/es/EsRestClient.java
services/src/main/java/org/fao/geonet/api/site/SiteInformation.java
web-ui/src/main/resources/catalog/locales/en-admin.json

Currently the information page displays an empty section for the `Index`. 
This change adds some basic information:
- ElasticSearch server version
- ElasticSearch server URL
- Index name

Site information - return ElasticSearch index information

---

web-ui/src/main/resources/catalog/style/gn.less

Letters like j, y, p are getting truncated when displaying the username.
Based on the following it seems like line-height should be normal
https://stackoverflow.com/questions/25470084/minimum-line-height-to-ensure-text-is-not-cut-off
After this change is looks like this

Change line-height for username so that it is not truncated.

---

web-ui/src/main/resources/catalog/components/metadataactions/RelatedResourcesService.js

Fix https://github.com/geonetwork/core-geonetwork/issues/7048

External map viewer / Fix add WFS to map empty variable

---

web-ui/src/main/resources/WEB-INF/classes/web-ui-wro-sources.xml
web-ui/src/main/resources/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.nl.js
web/src/main/webapp/xslt/base-layout-cssjs-loader.xsl

This PR adds a Dutch translation for the datepicker used in GeoNetwork.

Add a Dutch translation for the datepicker

---

web/src/main/webResources/WEB-INF/web.xml

Related to #6970
Using the INSPIRE Atom feeds endpoint: 
http://localhost:8080/geonetwork/opensearch/dut/2b087d2c-6a1c-4746-95c6-3d40bc4294f9/OpenSearchDescription.xml
was returning a 403 error.
The portal filter checker should exclude the value `opensearch`, related to the following forward rule: https://github.com/geonetwork/core-geonetwork/blob/29e131bad89441cd377cf5d4d42098b1d9ba606b/web/src/main/webResources/WEB-INF/urlrewrite.xml#L144-L150, from the portal check.

Exclude ATOM opensearch URLs from the portal filter checker. 

---

domain/src/main/java/org/fao/geonet/domain/InspireAtomFeed.java
domain/src/main/java/org/fao/geonet/repository/InspireAtomFeedRepository.java
inspire-atom/src/main/java/org/fao/geonet/services/inspireatom/AtomServiceDescription.java
web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html

Code optimisations to retrieve the atom feeds. Tested in `3.12.x` and somehow `retrieveDatasetUuidFromIdentifier` causes that the call to `findByMetadataId` takes long time. In `main` doesn't seem so, maybe due to the JPA/Hibernate version.
The change does some cleanup of the code and avoids to retrieve the same information several times.

Remote INSPIRE ATOM Feed / code cleanup and optimisations for ATOM describe service

---

web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html
web-ui/src/main/resources/catalog/components/pages/GnStaticPagesDirective.js

Test case:
1) Create a static page with HTML content.
2) Refresh the page and click the link --> A message `Page not available` instead of the page content is displayed.
Note that in localhost doesn't happen, probably due to ignoring the CORS interceptor.
Thanks @fxprunayre about the code suggestion.

Fix load of static pages html content

---

listeners/src/main/java/org/fao/geonet/listener/metadata/draft/ApprovePublishedRecord.java
services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java

Fixes #5556
Forward port of a commit not added to the `main` branch.
Fix also for bulk privileges, analog to https://github.com/geonetwork/core-geonetwork/pull/7184/commits/7e5446d0d13823d1fac29ab514fb2cc7e96f6f8c
See test cases at https://github.com/geonetwork/core-geonetwork/pull/7184

[FP] Metadata workflow - publish an approved record with a draft copy publishes the draft copy.

---

core/src/main/java/jeeves/config/springutil/JeevesNodeAwareLogoutSuccessHandler.java
core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java
core/src/main/java/org/fao/geonet/kernel/setting/SettingInfo.java

This PR handles the error on signout where there is no port set in the settings manager. Previously if no port was set (because it's not needed) logging out would produce a null pointer error (see below):
This PR adds some logic to check for the value of the port in the settings and to set it to 80 if it is not included.
With this pull request, if no port is set the logout error no longer occurs.

Added some logic into JeevesNodeAwareLogoutSuccessHandler to deal with the case where no port is set in the settings manager

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/thesaurus-transformation.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout-custom-fields-keywords.xsl
schemas/iso19139/src/main/plugin/iso19139/convert/thesaurus-transformation.xsl
schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields-keywords.xsl
schemas/iso19139/src/main/plugin/iso19139/update-fixed-info-keywords.xsl

Follow up of https://github.com/geonetwork/core-geonetwork/pull/6770
When requesting keywords in ISO formats, populate the thesaurus title using the proper multilingual title based on record language.
Test:
* create a local thesaurus with a title in UI language
* add keywords
* create a metadata record and add those keywords = title is wrong.
Sample API call: http://localhost:8080/srv/api/registries/vocabularies/keyword?thesaurus=local.theme.demo&id=https:%2F%2Fregistry.geonetwork-opensource.org%2Ftheme%2Fdemo%2387aa1156-b91e-405c-92c3-5c7063a5ce68&transformation=to-iso19115-3.2018-keyword&langMap=%7B%22fre%22:%22%23FR%22%7D&lang=fre&textgroupOnly=false

Thesaurus / Multilingual titles / Set title according to record language.

---

core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java
core/src/main/java/org/fao/geonet/kernel/setting/SettingInfo.java
core/src/main/java/org/fao/geonet/kernel/setting/SettingManager.java

@archaeogeek apologies for the late review of #7124.
This pull requests contains a fix of `BaseMetadataManager`, that was not caused by your previous pull request, but when the port was empty returned the value ending with a colon `http://SERVERNAME:`, reported by @fxprunayre 
Also contains refactor of similar methods in `SettingInformation` and `SettingManager`. At some moment maybe we can remove `SettingInformation`.

Additional code refactor related to pull request 7124 to avoid code duplication

---

core/src/main/java/org/fao/geonet/kernel/mef/Importer.java
core/src/main/java/org/fao/geonet/kernel/mef/MEFLib.java

Currently `OVERWRITE` mode is not really overwriting the record but remove it (including status, privileges, ...) and then replace it with the new XML and import parameters.
Users expect that overwrite is only updating the XML of the metadata record.
Change `OVERWRITE` mode to only update the XML and add a `REMOVE_AND_REPLACE` (not visible in the UI ?) mode to keep existing mechanism.
When workflow is enabled, `OVERWRITE` is not allowed

API / Import record / Overwrite mode improvement.

---

services/src/main/java/org/fao/geonet/api/tools/i18n/TranslationApi.java

Currently the keys seem retrieved order by id or last update. This causes in the UI to display key values not grouped:
This change sorts the custom translations by key.

Sort custom translations by translation key to display them in the UI grouped by translation

---

web-ui/src/main/resources/catalog/components/pages/partials/menu-page.html
web-ui/src/main/resources/catalog/locales/en-admin.json

Initialise `gnActiveTbItem` directive with `pageId`, `page.pageId` is not yet available when the directive is initialised.
Related to #7138

Static pages / Fix links to load html pages content

---

schemas/iso19110/src/main/plugin/iso19110/index-fields/index.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
web-ui/src/main/resources/catalog/locales/en-core.json
web-ui/src/main/resources/catalog/locales/nl-core.json
web-ui/src/main/resources/catalog/style/gn_metadata.less
web-ui/src/main/resources/catalog/views/default/directives/directive.js
web-ui/src/main/resources/catalog/views/default/directives/partials/attributetable.html
web-ui/src/main/resources/catalog/views/default/templates/recordView/featurecatalogue.html
web/src/main/webResources/WEB-INF/data/config/index/records.json

In ISO19139, `gfc:cardinality` is a multiplicity element with lower/upper properties. In ISO19115-3, cardinality is a `CharacterString`.
Store it as text in the index with `lower..upper` value for ISO19139.
Display cardinality next to the type.
Do not display twice the type name (already the table header).

Standard / ISO19110 / Add cardinality in default view

---

services/src/main/java/org/fao/geonet/api/records/MetadataApi.java
web-ui/src/main/resources/catalog/components/search/mdview/mdviewService.js

When a metadata has a working copy, accessing the metadata detail page was throwing an exception due to use the working copy identifier to update the approved metadata version popularity.
```
2023-07-07T11:33:05,709 ERROR [geonetwork] - No entity found with id: 117; nested exception is javax.persistence.EntityNotFoundException: No entity found with id: 117
org.springframework.orm.jpa.JpaObjectRetrievalFailureException: No entity found with id: 117; nested exception is javax.persistence.EntityNotFoundException: No entity found with id: 117
at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:379) ~[spring-orm-5.3.27.jar:5.3.27]
at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(Hiberna …
```

Metadata workflow / Don't increase popularity when viewing a metadata working copy

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl
schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
web-ui/src/main/resources/catalog/views/default/less/gn_result_default.less

In all `gco:CharacterString` add line breaks and hyperlinks eg. in lineage.
```xml
<mdb:resourceLineage>
<mrl:LI_Lineage>
<mrl:statement>
<gco:CharacterString>http://www.argodatamgt.org/Documentation</gco:CharacterString>
</mrl:statement>
```
Backport https://github.com/geonetwork/core-geonetwork/pull/5446 to ISO19115-3
This is more consistent with ISO19139 and the default view.

Standard / ISO19115-3 / Formatter / Layout improvements

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/utility-fn.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/update-fixed-info.xsl

In ISO19139, the main language was also declared as a `locale` object in order to set the ID for the main language used for translations. See https://github.com/geonetwork/core-geonetwork/blob/main/schemas/iso19139/src/main/plugin/iso19139/update-fixed-info.xsl#L169-L186
In ISO19115-3, `defaultLocale` and `otherLocale` are both locale object so there is no need to declare main language in 2 places like in ISO19139. The ID is already set in the `defaultLocale` element.
Avoid XSL error if a language is declared more than once.
This could happen when users migrate from ISO19139.

Standard / ISO19115-3 / Do not declare main language in other languages

---

services/src/main/java/org/fao/geonet/api/es/EsHTTPProxy.java

The directive `gnRelatedDropdown` lists the associated resources, but if a metadata has more than the original value 100, the first 100 are rendered fine when have external links, but the metadata exists locally, while the rest are displayed with an empty title:
This code change updates the limit as service metadata can easily link to more than 100 datasets.

Increase the limit to retrieve the related metadata in the search results

---

harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/arcsde/ArcSDEHarvester.java

The original code was doing some checks only valid for `fgdc-std` metadata schema that was removed from GeoNetwork 3+

ArcSDE harvester / If the metadata stored in ArcSDE is matched against a known metadata schema, harvest the record as it is.

---

schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl

Some ISO19139 users are still using GML version 320 depending on the base XSD schema used. 
Properly index temporal range in both cases.
Sample record https://metadata.vlaanderen.be/srv/dut/catalog.search#/metadata/7867D384-17E1-434E-A46A-2ACD3750671C

Standard / ISO19139 / Indexing / Temporal range in GML 3.2.0

---

core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
web-ui/src/main/resources/catalog/locales/en-v4.json
web-ui/src/main/resources/catalog/views/default/templates/recordView/type-dataset.html

Geographic extent is sometime described using geographic identifier or description. If any, display them next to the map.
Make indexing more consistent in all ISO schemas.

Record view / Display geographic identifier and description if any.

---

schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl

ISO19139 - Improve metadata full view for contacts when fields information is missing

---

web-ui/src/main/resources/catalog/components/search/mdview/partials/contact.html

Having the organisation name with an hyperlink can be misleading for user as when we click on the contact, the popup with contact details is also displayed. So moving the website info in the popup to not have 2 click actions on same element.
Also use same icons as in full view for address.

Record view / Contact / Move website to popup

---

core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java
core/src/test/resources/org/fao/geonet/api/Messages.properties
core/src/test/resources/org/fao/geonet/api/Messages_fre.properties
web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties

Update status emails to contain link to metadata which does not contain in anchor
This will make the link consistent with other emails such as publish/unpublish notifications.
Before this change the url in the link would be 
http://localhost:8080/geonetwork/srv/eng/catalog.search#/metadata/00000000-0000-0000-0000-000000000000
After this change, the url will be 
http://localhost:8080/geonetwork/srv/api/records/00000000-0000-0000-0000-000000000000
Related to issue #6934

Update status emails to contain link to metadata which does not contain in anchor

---

core/src/main/java/org/fao/geonet/kernel/security/keycloak/KeycloakUserUtils.java
core/src/main/java/org/fao/geonet/kernel/security/openidconnect/OidcUser2GeonetworkUser.java
core/src/main/java/org/fao/geonet/kernel/security/shibboleth/ShibbolethUserUtils.java
domain/src/main/java/org/fao/geonet/domain/UserGroup.java
domain/src/main/java/org/fao/geonet/repository/UserGroupRepositoryCustom.java
domain/src/main/java/org/fao/geonet/repository/UserGroupRepositoryCustomImpl.java
domain/src/test/java/org/fao/geonet/repository/UserGroupRepositoryTest.java

When authenticating user, only update the usergroups in the database if they have changed. 
This will prevent database locks when multiple authentications from the same user are being done.
Fixes issue #7088

When authenticating user, only update the usergroups in the database if they have changed

---

web-ui/src/main/resources/catalog/components/common/map/wmsQueue.js

Related to #7228.
The changes in that pull request worked with the default background layers as `queue[type]` is `undefined`, but with custom background layers `queue[type]` is not `undefined`, failing.

Fix wmsQueue clear method logic

---

core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java

Regression from #7130
Fixes the following error.
Error is: can't parse argument number: {index:_uuid}

Escape {{ to avoid error parsing argument.

---

web-ui/src/main/resources/catalog/components/history/GnHistoryService.js

In #7074 was changed a parameter name of the the metadata workflow API, due to a Sonarlint suggestion. But the client code was not updated.

Fix record history parameter name. Related to #7074

---

web-ui/src/main/resources/catalog/components/metadatamanager/EditorService.js

When deleting an element in the editor, the current sequence is as follows:
- Click the red cross
- Start slideUp animation
- Save
- End slideUp animation
- Update the DOM
In some configuration cases, such as when deleting a section block containing `thesaurus-list-picker` directive, the DOM is read during the save, causing the element to be only partially deleted:
dcat2 config-editor.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<editor ...>
<fields>
<for name="dct:type" xpath="dct:LicenseDocument" use="thesaurus-list-picker">
thesaurus="external.theme.licence-type"
xpath="/dct:license/dct:LicenseDocument/dct:type"
max="1"
labelKey="dcat.addType"/>
</for>
</fields>
<views>
<view ...>
<tab id="tabDistribution" mode="flat" displayIfRecord="count(//dcat:dataset) > …
```

Fix deletion sequence in editor: wait for DOM update before saving

---

schemas/config-editor.xsd
web/src/main/webapp/xslt/ui-metadata/menu-builder.xsl

This change enables the possibility to have multiple default tabs with `displayIfRecord` conditions in a single editor view.  
This is for example useful when having different default tabs for dataset and services metadata. 
```xml
<editor ...>
<views>
<view ...>
<tab id="tabDataset" default="true" mode="flat" displayIfRecord="count(//dcat:dataset) > 0" hideIfNotDisplayed="true">...</tab>
<tab id="tabService" default="true" mode="flat" displayIfRecord="count(//dcat:service) > 0" hideIfNotDisplayed="true">...</tab>
</view>
</views>
</editor>
```
CC @fxprunayre

Allow mulitple conditional default tabs in a single editor view

---

web-ui/src/main/resources/catalog/views/default/module.js

The home page displays the most popular metadata, but it displays them starting from the less popular.
Test case:
1) Load iso19139 samples
2) Access the metadata detail page for one of the metadata samples
3) In the search results, sort by popularity --> The previous metadata appears first
4) Go to the Home page -> Most popular 
- Without the fix --> NO OK, the previous metadata appears the last one
- With the fix --> the previous metadata appears the first one

Fix directive to display the most popular records, to display the most popular first

---

schemas/config-editor.xsd
web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
web/src/main/webapp/xslt/ui-metadata/form-configurator.xsl

When configuring a list of snippets for a field in the editor, if we want to define the same list in another view, it is currently required to repeat the same snippet list.  
This becomes an issue when the list of snippets gets long as it makes the config file harder to read and maintain. 
This change implements a way to configure lists of reusable snippets in the config-editor.xml:
```xml
<editor ...>
<snippets>
<list name="licenses">
<snippet label="license-modellicentie-gratis">
<dct:license>
<dct:LicenseDocument rdf:about="https://data.vlaanderen.be/id/licentie/modellicentie-gratis-hergebruik/v1.0">
<dct:type>
<skos:Concept rdf:about="http://purl.org/adms/licencetype/Attribution">
<skos:prefLabel xml:lang="nl">Verplichte bronvermelding</skos:prefLabel>
<skos:prefLabel …
```

Make editor snippets referenceable and reusable

---

domain/src/main/java/org/fao/geonet/domain/ISODate.java

OGC API Records fails with the following exception with latest GeoNetwork 4.2.5, when accessing:
http://SERVER/geonetwork/api
```
2023-07-20 13:33:10.422  INFO 1 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2023-07-20 13:33:10.423  INFO 1 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2023-07-20 13:33:10.439  INFO 1 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 15 ms
com.sun.xml.bind.v2.runtime.IllegalAnnotationsException: 1 counts of IllegalAnnotationExceptions
If a class has @XmlElement property, it cannot have @XmlValue property.
this problem is related to the following location:
at public …
```

Add XmlTransient annotation to ISODate.getDateAndTimeUtc

---

web-ui/src/main/resources/catalog/views/default/templates/recordView/metadata.html

Fix issue that would occur on metadata that had duplication languages.
Also the following would end up empty.

Fix error that would occur when there were duplicate languages.

---

web-ui/src/main/resources/catalog/components/metadataactions/partials/relatedEditorList.html

When a metadata references a remote resource, if the remote metadata title can not be processed, the entry was displaying an empty text in the metadata editor:
With this change, it displays in these cases the metadata uuid:

Metadata editor / display metadata uuid for remote resources if the metadata title is not available

---

core/src/main/java/org/fao/geonet/kernel/search/index/OverviewIndexFieldUpdater.java
services/src/main/java/org/fao/geonet/api/records/MetadataIndexApi.java
services/src/main/java/org/fao/geonet/api/records/MetadataTagApi.java

When the metadata workflow is enabled and a metadata has an approved and working copy, process both. 
The index code selects the metadata by uuid. In the original code, if the user was allowed to edit it, the working copy was indexed, otherwise the approved version. 
With this change both records are processed.

Metadata index set of records - index the approved and working copies when the workflow is enabled

---

web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html

This PR is to fix issue https://github.com/geonetwork/core-geonetwork/issues/7255
After the fix the screen look like 
And fields layout are stable when shifting to different screen resolutions

fix multi entry combiner ui formatting issue when adding online resource

---

common/src/main/java/org/fao/geonet/utils/AbstractHttpRequest.java
common/src/main/java/org/fao/geonet/utils/GeonetHttpRequestFactory.java

Defining the proxy in the system properties was not used in certain requests, for example the ones done by CSW harvester.
Test case:
1) Execute GeoNetwork configuring in the system properties the proxy configuration, for example if running in localhost port 9090:
```
mvn jetty:run -Dhttp.proxyHost=localhost -Dhttp.proxyPort=9090 -Dhttps.proxyHost=localhost -Dhttps.proxyPort=9090
```
2) Stop the proxy server
3) Create a CSW harvester and run it --> 
- Without the fix --> NO OK:  the harvester is executed fine, not using the proxy configuration.
- With the fix --> OK: the harvester fails, as the proxy server is stopped, the proxy configuration is used.
---
The pull request includes also Sonarlint updates.

Update GeonetHttpRequestFactory to use system proxy defined in JAVA_OPTS

---

core/src/main/java/org/fao/geonet/util/MailUtil.java

Set html emails as utf-8

---

services/src/main/java/org/fao/geonet/api/records/CatalogApi.java
web/src/main/webapp/xslt/services/csv/csv-search.xsl

Current CSV export is based on XSL transformations and can be hard to use when user is interested in element with multiple values (eg. online source, contacts).
Default CSV export remains the same but add the possibility to customize the export with 2 additional parameters to create custom export:
* `loopElementXpath`: element to loop on eg. 
* use `.` for the metadata
* `.//gmd:CI_ResponsibleParty` for all contacts in ISO19139, 
* `.//gmd:transferOptions/*/gmd:onLine/*` for all online resources in ISO19139.
* `propertiesXpath`: columns to extract eg.
*  `gmd:identificationInfo/*/gmd:citation/*/gmd:title//text()` for the title.
Also add parameters for defining separators:
* `sep` for column separator
* `internalSep` when multiple values are stored in a field
User can then build custom …

API / CSV export / Add support for custom export.

---

web-ui/src/main/resources/catalog/style/gn.less

Do not break link in the middle of a word.
The breaking of links in a word is turned around, it's not for all links anymore but the break now has to be added to the exception in order to avoid side effects on the majority of links.

Do not break link in the middle of a word.

---

web/src/main/webResources/WEB-INF/data/config/index/records.json

Declare dutch language field for organisation to be able to create facet on this field.  
It may help fixing https://github.com/geonetwork/core-geonetwork/issues/7252

Search / Aggregation on organisation in Dutch

---

web-ui/src/main/resources/catalog/components/common/map/mapService.js

It's unclear why was used `HEAD` instead of `GET` to retrieve the WMS tile images when loading WMS background layers in the map in the Add Thumbnail option in the metadata editor. 
Some services at least doesn't like that, returning an error 400.

WMS tile images - if HEAD request fails, default to OL image src set

---

core/src/main/java/org/fao/geonet/kernel/SchemaManager.java
core/src/main/java/org/fao/geonet/kernel/XmlSerializer.java
core/src/main/java/org/fao/geonet/kernel/mef/ExportFormat.java
core/src/main/java/org/fao/geonet/kernel/schema/MetadataSchema.java
core/src/main/java/org/fao/geonet/kernel/schema/MetadataSchemaOperationFilter.java
core/src/test/java/org/fao/geonet/kernel/XmlSerializerIntegrationTest.java
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/link-utility.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/schema-ident.xml
schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
schemas/iso19139/src/main/plugin/iso19139/schema-ident.xml
services/pom.xml
services/src/main/java/org/fao/geonet/api/es/EsHTTPProxy.java
web/src/main/webapp/xml/validation/schemaPlugins/schema-ident.xsd

Currently the metadata schemas allow to define filters defined in `schema-ident.xml` file, to remove certain information from the metadata documents if certain conditions apply. 
For example in `iso19139`, if the user has no editing permission the elements with the attribute `@gco:nilReason='withheld'` are removed from the XML output and the full view formatter:
https://github.com/geonetwork/core-geonetwork/blob/fdd7536ac11b3ec8d648fc3e1923797bfe045b62/schemas/iso19139/src/main/plugin/iso19139/schema-ident.xml#L86-L90
The attribute `@gco:nilReason='withheld'` should be added in `update-fixed-info.xsl`  process of each metadata schema to mark which elements should be removed. A typical usage is to remove certain type of contacts for users that can't not edit the metadata record.
This pull …

Extend ElasticSearch proxy to filter out elements defined in the schema filters configurations

---

web-ui/src/main/resources/catalog/components/edit/FieldsDirective.js

Related to this change https://github.com/geonetwork/core-geonetwork/pull/6987 which caused the close button in the tooltip when using `icon` mode to not work.

Fix metadata editor tooltips close button when using the icon mode

---

web-ui/src/main/resources/catalog/templates/editor/top-toolbar.html
web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less

Move the save status below title to avoid overlapping buttons and editor tabs. This depend on the size of translations and the zoom level.
Before
After

Editor / Top bar / Avoid hiding editor tabs with tool bar actions.

---

web-ui/src/main/resources/catalog/components/catalog/CatalogService.js

The option to transfer the metadata ownership in Manage record menu of the metadata detail page was not displayed due to wrong check. 
In 3.12.x the value returned was a string and the check worked, but in 4.x the value is a boolean.

Fix the check to display the Transfer ownership option in the metadata detail page

---

csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/SearchController.java

Embedded documentation in the code now refers to sub-portals rather than virtual csw endpoints

Updated embedded documentation on naming convention for postprocessing files for sub-portals

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/fromJsonOpenDataSoft.xsl

This PR 
- adds a small fix for ods v1 concerning OnlineResource linkages
- inserts ODS explore API urls (which respond with `Access-Control-Allow-Origin:*` CORS headers) for OnlineResource linkages. This should facilitate the usage of the data links in other web apps.
Note: `v2.1` is hard coded in the API URL as ODS v1 does not seem to provide this API. However, ODS v1 endpoints generally also seem to propose a v2 endpoint.
Simple URL config PR was tested with:
- URL: https://opendata.lillemetropole.fr/api/datasets/1.0/search?refine.publisher=M%C3%A9tropole+Europ%C3%A9enne+de+Lille&refine.datasetid=accroche_velos
- Element to loop on: `/datasets`
- Element for the UUID of each record: `/datasetid` (remove `/` here when testing on 4.2.2 or smaller)
- XSL transformation to apply: …

ODS: Use explore API for OnlineResource linkages

---

schemas/dublin-core/src/main/plugin/dublin-core/formatter/xsl-view/view.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl
schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
web-ui/src/main/resources/catalog/views/default/templates/recordView/thumbnails.html

Test case:
1) Create an iso19139 metadata and upload a thumbnail file.
2) Set the visibility to private.
3) Assign the privileges of the metadata to the group `ALL` without the `Download` privilege.
4) Access the metadata detail page with an anonymous user
Previously:
5) Check also the full view formatter

Hide thumbnail image in metadata page when the image can't be loaded due to an error.

---

inspire-atom/src/main/java/org/fao/geonet/inspireatom/harvester/InspireAtomHarvester.java
inspire-atom/src/main/java/org/fao/geonet/inspireatom/util/InspireAtomUtil.java
inspire-atom/src/main/java/org/fao/geonet/services/inspireatom/AtomPredefinedFeed.java

Support series metadata linked in INSPIRE ATOM services in the ATOM dataset describe service, otherwise a 404 error is returned in requests like this for series metadata.
https://localhostgeonetwork/srv/atom/describe/dataset?spatial_dataset_identifier_code=https://doi.org/10.11/3028ccf4-ff64-42ed-98f5-fea1b32da62a&language=de

INSPIRE ATOM - retrieve the metadata ATOM feed using only the resource identifier

---

core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataUtils.java

Follow up of https://github.com/geonetwork/core-geonetwork/pull/6792. 
When sitemap is using a custom URL template, only collect resource identifier if the template contain the resource identifier key.  This avoid doing XPath query on all records in the page (2500) which is quite time consuming. A default sitemap is generated in ~200ms, when adding DOI or Resource identifier, it takes usually more than 30s.
API call http://localhost:8080/geonetwork/srv/api/sitemap?format=html&doc=1

API / Sitemap / Improve speed when using URL template

---

services/src/main/java/org/fao/geonet/api/site/SitemapApi.java
web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html

* Return 200 OK for `/robots.txt` and `/srv/api/sitemap` instead of `500` "service not found". Previously if the request didn't contain `Accept: text/plain` or `Accept: application/xml` the server returned a `500` error. Now the server accepts any `Accept` header without complaining, returning a `200` response with `Content-Type: text/plain` or `Content-Type: application/xml` and the right content.
* Some search engines are indexing the Angular JS HTML template files. Exclude the `${context_path}/catalog` and `${context_path}/static` from being crawled by robots. Fix https://github.com/geonetwork/core-geonetwork/issues/3585.

Fix robots.txt and sitemap 500 errors if no right content type is provided

---

services/src/main/java/org/fao/geonet/api/userfeedback/UserFeedbackAPI.java
web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties

- Update mail message, related to #6792, causing the following error when creating a metadata user feedback:
```
{
"message": "MissingFormatArgumentException",
"code": "unsatisfied_request_parameter",
"description": "Format specifier '%s'"
}
```
- Don't fail the metadata user feedback creation if the mail server is not configured

User feedback API fixes

---

web/src/main/webapp/xslt/common/index-utils.xsl

When a CharacterString or an Anchor is empty, an empty object is created in the index. This is not necessary.
eg.
```xml
<gmd:identificationInfo>
<gmd:MD_DataIdentification>
<gmd:citation>
<gmd:CI_Citation>
<gmd:title>
<gco:CharacterString>Biologische Waarderingskaart en Natura 2000 Habitat</gco:CharacterString>
</gmd:title>
<gmd:alternateTitle gco:nilReason="missing">
<gco:CharacterString/>
</gmd:alternateTitle>
```
Index change:
This would avoid field label to be displayed with no value eg.

Indexing / Do not create empty object if no text

---

web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html
web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/linkToMd.html
web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/remote-record-selector.html
web-ui/src/main/resources/catalog/locales/en-editor.json

- Improve the title extraction For HTML links, to support title elements with attributes.
- Allow to define a custom title for the remote dataset link.
Currently if linking to a web page without title information, the title for the link was assigned to the full html.
With this change, the user can define a custom title for the remote dataset in this case:
or override the title extracted with a custom one:

Metadata editor / link to remote dataset improvements

---

web-ui/src/main/resources/catalog/components/search/mdview/mdviewDirective.js
web-ui/src/main/resources/catalog/components/search/mdview/partials/social.html
web-ui/src/main/resources/catalog/views/default/templates/recordView/share.html

Follow up of https://github.com/geonetwork/core-geonetwork/pull/6792
if not using the permalink linked in and others will not be able to extract the page name from the JS app and not really point to the record. Update to last version of Linked in API https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/plugins/share-plugin

Record view / Social network link points to permalink.

---

web-ui/src/main/resources/catalog/components/viewer/gazetter/GazetteerDefaultFactory.js

Type a search, delete characters, previous search results are still displayed.
This avoids

Map / Localisation / Empty results if no query

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/datacite/view.xsl

DOI can be stored in different places depending on user convention:
* metadata linkage (only in ISO19115-3)
* resource identifier
* online link
Make DOI discovery more similar to ISO19139 (in case record are migrated from ISO19139) https://github.com/geonetwork/core-geonetwork/blob/main/schemas/iso19139/src/main/plugin/iso19139/formatter/datacite/view.xsl#L142
Datacite output is available at http://localhost:8080/geonetwork/srv/api/records/8a14572c-10c4-484e-9963-4dac4bec459b/formatters/datacite?output=xml

DOI / ISO19115-3 / Support DOI set in resource identifier or distribution

---

services/src/main/java/org/fao/geonet/api/site/SiteInformation.java
web-ui/src/main/resources/catalog/locales/en-admin.json

@fxprunayre not sure the strings should be added to all `-admin.json` files, or just the `en-admin.json` with automatic fallbacks to the English variant? What happens when transifex create the corresponding `nl-admin.json` file, for example? Does it populate the missing labels?

HA exercise update - Adding schemapublication_dir to admin info panel.

---

web-ui/src/main/resources/catalog/components/catalog/CatalogService.js
web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionsDirective.js
web-ui/src/main/resources/catalog/components/metadataactions/partials/transferownership.html
web-ui/src/main/resources/catalog/locales/en-core.json

Also fixes a wrong property name in `CatalogService.js`, `getGroupOwner` method.

Display metadata user and group owner in the transfer ownership dialog

---

web-ui/src/main/resources/catalog/js/CatController.js

OGC API Record parameter for paging is `limit`. 
Follow up of https://github.com/geonetwork/core-geonetwork/pull/7094

RSS / Fix number of records parameter

---

web/src/main/java/org/fao/geonet/proxy/URITemplateProxyServlet.java

When the Links table is empty an 500 error happens when using the proxy: 
```
java.lang.IllegalStateException: Cannot call `sendError()` after the response has been committed
```
This is caused because the `response.sendError(...)` method is being called twice when the `Links` table has no entries. This commits fix this error calling the method only once.
In addition, it removes unnecessary info returned to the client.

Fix write after response commit on proxy response

---

common/pom.xml
core/pom.xml
pom.xml
web/pom.xml

* Update Xalan from 2.7.1 to 2.7.3 to address CVE-2022-34169.
* Use a workaround to address a shortcoming in xalan 2.7.3:The xalan serializer is declared as explicit dependency and the place marked for later reversal of this workaround.
This improves on #7057 and #7117 and supercedes those pull requests.
The security implication of  CVE-2022-34169 for core-geonetwork cannot be fully assessed, a malicious XSLT style sheet can be used for an _Arbitrary Code Execution_  and it cannot be ruled out that someone has build a solution where XSLT style sheet elements are supplied by external users and are not fully sanitized. So it makes sense to fix this at least as a precaution now and not wait for xalan 2.7.4. 
Reference: proof of concept description: …

Update xalan dependency (remove potential vuln)

---

pom.xml
web-ui/src/main/resources/catalog/components/search/mdview/mdviewService.js
web/src/main/webResources/WEB-INF/data/config/index/records.json

If a record has more than 100 related records, statistics are only provided on the first 100.
eg. https://sdi.eea.europa.eu/catalogue/srv/eng/catalog.search?#/metadata/3c362237-daa4-45e2-8c16-aaadfb1a003b
If extending the stats to more than 100 records, Elasticsearch returns:
```
Top hits result window is too large, the top hits aggregator [docs]'s
from + size must be less than or equal to: [100] but was [105].
This limit can be set by changing the [index.max_inner_result_window] index level setting."
```
Adding the possibility to configure the index to compute stats on a larger window of results. By default 200.

Record view / Add configuration to support statistics on more than 100 related records

---

web-ui/src/main/resources/catalog/views/default/templates/footer.html

RSS feeds now focus on the current portal in use (as OGC API Records provides endpoints per portal).
If more than one feed declared, add the label to clearly identify the purpose of the link.

Portal / RSS feeds point to current portal

---

web-ui/src/main/resources/catalog/style/gn_editor.less

On Firefox, when adding/removing elements which trigger form reload eg. adding thesaurus block, removing a fieldset, the browser usually scroll down the position before saving.
It seems related to https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-anchor/Guide_to_scroll_anchoring

Editor / Preserve scroll position on Firefox

---

services/src/main/java/org/fao/geonet/api/categories/TagsApi.java

Currently is possible to create several metadata categories with the same name, that is used as a key value.
This change checks that the name is not used in another categories.
@fxprunayre some questions:
- Currently (also for Groups) is checked the same exact name, I think should be better to check with case insensitiveness?
- Not sure why not defined in as unique column in the model class? Although if we want to use case insensitiveness, probably not supported in all databases.

Create metadata category - check doesn't exist a category with the same name

---

core/src/main/java/org/fao/geonet/kernel/url/UrlChecker.java
core/src/main/java/org/fao/geonet/lib/NetLib.java
core/src/main/java/org/fao/geonet/lib/ProxyConfiguration.java
services/src/main/java/org/fao/geonet/api/site/SiteApi.java
web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js
web-ui/src/main/resources/catalog/locales/en-admin.json
web-ui/src/main/resources/catalog/templates/admin/settings/system.html
web/src/main/java/org/fao/geonet/Geonetwork.java

This change avoids overriding the http proxy configuration when saving the application settings, when the http proxy configuration is setup in system properties. For example, when starting up the application like:
```
mvn jetty:run -Dhttp.proxyHost=192.168.1.21 -Dhttp.proxyPort=9090 \ 
-Dhttps.proxyHost=192.168.1.21 -Dhttps.proxyPort=9090
```
In this case, the settings page doesn't allow to configure the proxy settings:
The change includes a code refactor of the proxy configuration. It can facilitate in the future to rely only on the http proxy configuration from system properties and remove the GeoNetwork related settings.

Don't override proxy configuration when saving the settings, if the http proxy is configured in Java system properties

---

web-ui/src/main/resources/catalog/components/viewer/wps/WpsService.js

A WPS may require a `BoundingBoxData` in a particular CRS. Add reprojection step if needed:
```
<Input minOccurs="0" maxOccurs="1">
<ows:Identifier>EXTENT</ows:Identifier>
<ows:Title>A spatial extent</ows:Title>
<ows:Metadata xlink:title="processing:type" xlink:href="extent" xlink:type="simple"/>
<BoundingBoxData>
<Default>
<CRS>EPSG:2154</CRS>
</Default>
<Supported>
<CRS>EPSG:2154</CRS>
</Supported>
</BoundingBoxData>
</Input>
```

Map / WPS / Add support for custom parameter CRS

---

web-ui/src/main/resources/catalog/components/common/ows/OWSService.js
web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js

QGIS Server may not advertised namespace for feature type eg. https://geodata.valenceromansagglo.fr/api/ogc?SERVICE=WFS&REQUEST=GetCapabilities or https://sextant.ifremer.fr/services/wfs/ilico?service=WFS&request=GetCapabilities
Add the missing version parameter to the layer to properly add the layer.
We also have a `useProxy` property which does not look to be set for WFS layer - not sure if it is needed?

WFS layer improvements

---

web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/linktosibling.html
web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
web-ui/src/main/resources/catalog/components/metadataactions/partials/relatedEditorList.html
web-ui/src/main/resources/catalog/locales/en-v4.json
web-ui/src/main/resources/catalog/style/gn_icons.less
web-ui/src/main/resources/catalog/views/default/less/gn_result_default.less

Add icons for related types (association and initiative) in the editor and the footer of a card view. Where ever possible this PR adds icons in front of a link or label.
**The icons used**
In stead of a tooltip, the footer is expanded when you hover over it and the related types are displayed.
**Screenshot with the expanded footer**

Add icons for related types (association and initiative)

---

web-ui/src/main/resources/catalog/components/viewer/layermanager/LayerManagerDirective.js
web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextService.js

* Save current map dimension value in the map context to be able to open a map on specific date. Follow up of https://github.com/geonetwork/core-geonetwork/pull/6820 
* Save if layer is enabled in layer manager
To test:
* add a layer from WMS-Time, enable layer and select a date 
* save the map
* open the map
Information saved in layer extension:
```xml
<ows-context:Layer name="22KGA_CHL" hidden="false" opacity="1">
<ows-context:Server service="urn:ogc:serviceType:WMS" version="1.3.0">
<ows-context:OnlineResource xlink:href="https://www.aquacoope.org/geoserver/c_br/ows?SERVICE=WMS&amp;"/>
<ows-context:Extension>{"timeDimensionValue":"2021-10-06T00:00:00.000Z", "enabled": true}</ows-context:Extension>
```

Map / WMS dimension saved in map

---

web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
web-ui/src/main/resources/catalog/components/toolbar/partials/menu-signin.html

When the setting `gnCfg.mods.authentication.enabled` is disabled, the login menu is not displayed in the top bar, users have to go directly to the login page to be able to login.
This can be useful to hide the login option.
The problem is that once the user is logged in, the menu is not displayed, so the logged user has no easy way to go to the user profile page or logout.
With this change, the login menu is displayed when the option `gnCfg.mods.authentication.enabled` is disabled, but the user is logged in.

Display the login menu for authenticated users when the setting 'gnCfg.mods.authentication.enabled' is disabled

---

web-ui/src/main/resources/catalog/components/utility/CORSInterceptor.js
web-ui/src/main/resources/catalog/components/viewer/wps/WpsService.js

Related to #5941
The variable `url` is used before is declared. It seems that the correct variable to use is `config.url`.
----
Included in the PR prettier formatting for https://github.com/geonetwork/core-geonetwork/compare/main...GeoCat:core-geonetwork:fix-corsinterceptor?expand=1#diff-17af7f0ce89836e5f0d51b830431ce4ee01d98843e81399cd432359e80ae6591

Fix CORSInterceptor, usage of a variable before is defined. 

---

web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/onlinesrcList.html

Test:
* add thumbnail
* in full view
Before
After

Editor / Online source / Fix button icon

---

core/src/main/java/org/fao/geonet/util/XslUtil.java

Fix for https://github.com/geonetwork/core-geonetwork/issues/6955

Indexing / Bounding Polygon / Reproject if needed

---

web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/editor.html
web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid.html
web-ui/src/main/resources/catalog/locales/ca-core.json
web-ui/src/main/resources/catalog/locales/cs-core.json
web-ui/src/main/resources/catalog/locales/da-core.json
web-ui/src/main/resources/catalog/locales/de-core.json
web-ui/src/main/resources/catalog/locales/en-core.json
web-ui/src/main/resources/catalog/locales/es-core.json
web-ui/src/main/resources/catalog/locales/fi-core.json
web-ui/src/main/resources/catalog/locales/fr-core.json
web-ui/src/main/resources/catalog/locales/is-core.json
web-ui/src/main/resources/catalog/locales/it-core.json
web-ui/src/main/resources/catalog/locales/ko-core.json
web-ui/src/main/resources/catalog/locales/nl-core.json
web-ui/src/main/resources/catalog/locales/pt-core.json
web-ui/src/main/resources/catalog/locales/ru-core.json
web-ui/src/main/resources/catalog/locales/sk-core.json
web-ui/src/main/resources/catalog/locales/sv-core.json
web-ui/src/main/resources/catalog/locales/zh-core.json
web-ui/src/main/resources/catalog/views/default/directives/partials/infolist.html

Handle empty titles when they obstruct the use of the UI (such as when they make a record unclickable).

Improved handling of empty titles

---

web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html

This PR fixes the untranslated userRecord and userRecords labels in the record count section of admin console -> users and groups -> users -> user page

fix for untranslated userRecord and userRecords labels in user admin page

---

web-ui/src/main/resources/catalog/js/admin/UserGroupController.js
web-ui/src/main/resources/catalog/templates/admin/usergroup/groups.html

Fix the filter to display of the metadata owned by a group in the groups maintenance and untranslated texts (analog to #7354)

Groups maintenance / fix the display of the metadata owned by a group

---

web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
web-ui/src/main/resources/catalog/components/utility/partials/statusbadge.html
web-ui/src/main/resources/catalog/style/gn.less
web-ui/src/main/resources/catalog/views/default/templates/recordView/status.html
web-ui/src/main/resources/catalog/views/default/templates/recordView/type-dataset.html
web-ui/src/main/resources/catalog/views/default/templates/recordView/type-series.html

In ISO, a record may have more than one status even if not common. 
Fix the overlapping status badge by a dedicated container displaying all status. 
In the search results, only the first status is displayed (and others are listed in the tooltip for information).

Record view / Support multiple status.

---

release/bin/startup.bat
release/bin/startup.sh

To test:
1) Generate the zip bundle in the `release` module
2) Unzip / start Jetty
3) Login to GeoNetwork and access http://localhost:8080/geonetwork/monitor/metrics, a JSON document should be returned, no error

Jetty bundle / Add JAVA_OPTS configuration for the /monitor/metrics endpoint to work correctly

---

services/src/test/resources/services-web-test-context.xml

Thanks @wangf1122 for reporting the issue.
In `main` branch was added as part of https://github.com/geonetwork/core-geonetwork/pull/6989.

Add missing roleHierarchy bean to service test context file

---

services/src/main/java/org/fao/geonet/api/records/MetadataSampleApi.java

~~Make samples generate new uuid so that they don't overwrite any existing data.~~
Make samples loading fail if uuid already exists so that they don't overwrite any existing data.
Fix for #7274

Make samples loading fail if uuid already exists

---

services/src/main/java/org/fao/geonet/api/ApiUtils.java

Fix unit tests and logic related to ApiUtils.canViewRecord to retrieve the metadata internal identifier. 

---

docs/manual/docs/overview/change-log/version-4.2.6.md

Should fix the layout of 
(in github preview it was fine)

Doc / Fix list layout on the website

---

web-ui/src/main/resources/catalog/components/metadataactions/RelatedDirective.js

Related to #7248
The code to load the relations of a metadata is executed in a `watchCollection` and can enter several times. The way to add the parameter was not handling this case producing wrong urls like:
http://localhost:8080/geonetwork/srv/api/records/5b74c2db-9c0c-4fbe-b0d4-3070fc71466b/attachments/report.pdf?approved=false?approved=false

Record view / fix double approved parameter in the metadata working copy page, for the buttons in the online resources panel.

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/eng/labels.xml
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/fre/labels.xml
schemas/iso19139/src/main/plugin/iso19139/loc/ara/labels.xml
schemas/iso19139/src/main/plugin/iso19139/loc/cat/labels.xml
schemas/iso19139/src/main/plugin/iso19139/loc/chi/labels.xml
schemas/iso19139/src/main/plugin/iso19139/loc/dut/labels.xml
schemas/iso19139/src/main/plugin/iso19139/loc/eng/labels.xml
schemas/iso19139/src/main/plugin/iso19139/loc/fin/labels.xml
schemas/iso19139/src/main/plugin/iso19139/loc/fre/labels.xml
schemas/iso19139/src/main/plugin/iso19139/loc/ger/labels.xml
schemas/iso19139/src/main/plugin/iso19139/loc/ita/labels.xml
schemas/iso19139/src/main/plugin/iso19139/loc/nor/labels.xml
schemas/iso19139/src/main/plugin/iso19139/loc/pol/labels.xml
schemas/iso19139/src/main/plugin/iso19139/loc/por/labels.xml
schemas/iso19139/src/main/plugin/iso19139/loc/rus/labels.xml
schemas/iso19139/src/main/plugin/iso19139/loc/slo/labels.xml
schemas/iso19139/src/main/plugin/iso19139/loc/spa/labels.xml
schemas/iso19139/src/main/plugin/iso19139/loc/tur/labels.xml
web-ui/src/main/resources/catalog/components/metadataactions/RelatedResourcesService.js
web-ui/src/main/resources/catalog/js/CatController.js
web-ui/src/main/resources/catalog/style/gn_icons.less
web-ui/src/main/resources/catalog/views/default/module.js

Cf georchestra/geonetwork#226 & georchestra/geonetwork#227
- only tested with an external viewer, mapstore2 (with support for direct 3dtiles loading since geosolutions-it/MapStore2#9021), and in the context of georchestra (eg not 'vanilla geonetwork')
- i have no idea if the default gn 3d viewer has support for 3dtiles datasets, and wont really be able to work on that -> help/finishing touches welcome !
- OGC:3DTILES as a protocol type should be a valid type since its an official OGC standard
- the dataset entry point is a regular http/https url, pointing at a json file
- with what i've done, im not 100% sure by default `OGC:3DTILES` is added to `search->linkTypes->layers` in the ui config..

Add support for OGC:3DTILES protocol

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/eng/labels.xml
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/fre/labels.xml
schemas/iso19139/src/main/plugin/iso19139/loc/ara/labels.xml
schemas/iso19139/src/main/plugin/iso19139/loc/cat/labels.xml
schemas/iso19139/src/main/plugin/iso19139/loc/chi/labels.xml
schemas/iso19139/src/main/plugin/iso19139/loc/dut/labels.xml
schemas/iso19139/src/main/plugin/iso19139/loc/eng/labels.xml
schemas/iso19139/src/main/plugin/iso19139/loc/fin/labels.xml
schemas/iso19139/src/main/plugin/iso19139/loc/fre/labels.xml
schemas/iso19139/src/main/plugin/iso19139/loc/ger/labels.xml
schemas/iso19139/src/main/plugin/iso19139/loc/ita/labels.xml
schemas/iso19139/src/main/plugin/iso19139/loc/nor/labels.xml
schemas/iso19139/src/main/plugin/iso19139/loc/pol/labels.xml
schemas/iso19139/src/main/plugin/iso19139/loc/por/labels.xml
schemas/iso19139/src/main/plugin/iso19139/loc/rus/labels.xml
schemas/iso19139/src/main/plugin/iso19139/loc/slo/labels.xml
schemas/iso19139/src/main/plugin/iso19139/loc/spa/labels.xml
schemas/iso19139/src/main/plugin/iso19139/loc/tur/labels.xml
web-ui/src/main/resources/catalog/components/metadataactions/RelatedResourcesService.js
web-ui/src/main/resources/catalog/js/CatController.js
web-ui/src/main/resources/catalog/locales/en-core.json
web-ui/src/main/resources/catalog/style/gn_icons.less
web-ui/src/main/resources/catalog/views/default/module.js

on top of #6950 to avoid conflicts - so only the last two commits matter for the feature - adds support for OGC:COG links, that's a cherrypick/backport of georchestra/geonetwork#252.
i've chosen OGC:COG as it's a candidate to OGC standards cf https://portal.ogc.org/files/102116
with this in the XML:
```
<gmd:onLine>
<gmd:CI_OnlineResource>
<gmd:linkage>
<gmd:URL>
https://cogeo.craig.fr/opendata/ortho/orthocraig3_vichy_2021.cog.tif
</gmd:URL>
</gmd:linkage>
<gmd:protocol>
<gco:CharacterString>OGC:COG</gco:CharacterString>
</gmd:protocol>
<gmd:name>
<gco:CharacterString>Vichy 3cm</gco:CharacterString>
</gmd:name>
<gmd:description>
<gco:CharacterString>COG de 2021</gco:CharacterString>
</gmd:description>
</gmd:CI_OnlineResource>
</gmd:onLine>
```
i can open COG links in a mapstore2 instance …

[feat] allow to open COG links in external viewer

---

docs/manual/mkdocs.yml

This PR changes the link the logo is pointing, it used to be the root of the documentation, now it is the GeoNetwork site

Change the url the icon in the homepage is linking to

---

pom.xml

Update minor versions for these dependencies:
- Spring Framework -> `5.3.30`
- Spring Security -> `5.8.7`
- Spring JPA ->  `2.7.16`

GeoNetwork 4.4.x minor versions library updates

---

.github/workflows/docs.yml
.github/workflows/linux.yml
.gitignore
docs/manual/docs/index.fr.md
docs/manual/docs/index.md
docs/manual/mkdocs.yml

GitHub workflow actions for docs, with this changes docs are checked as part of the build, and when the `docs/manual` folder is modified new documentation is published. 
* main: this pull-request
* 4.2.x: https://github.com/geonetwork/core-geonetwork/pull/7415
* 3.12.x: https://github.com/geonetwork/core-geonetwork/pull/7414
The result looks something like this in the version selector (addressing feedback it was hard to tell what is "latest").
Reference: https://squidfunk.github.io/mkdocs-material/publishing-your-site/
* mike deploy on change to branch (we will need to backport this workflow to active branches)
* there is no need to deploy on release tag, as docs are now "live" from main
Change to `main` branch are deployed immediately to `latest`, latest title is "4.4 Latest" in version …

Add documentation to GitHub workflows

---

.github/workflows/docs.yml
.github/workflows/linux.yml
.gitignore
docs/manual/docs/index.fr.md
docs/manual/docs/index.md
docs/manual/mkdocs.yml
docs/manual/pom.xml

See https://github.com/geonetwork/core-geonetwork/pull/7411

[backport 3.12.x] Add documentation to GitHub workflows

---

web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html

Enabling the option for administrator user to be able to reset other users passwords
https://github.com/geonetwork/core-geonetwork/blob/609389b5b4b86a05f9283343055f3e0b8602f4d5/web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql#L736-L740
, should not request to the Administrator user to fill the users old password to reset. 
Using an administrator user, the field can be left empty, but it's confusing to display it, as it's not required.
**Without the change**
**With the change**

Reset user password dialog - don't display the field to request the old password for administrators

---

index/src/main/java/org/fao/geonet/index/es/EsRestClient.java
services/src/main/java/org/fao/geonet/api/site/SiteInformation.java

Follow up #7179
Test case:
1) Configure a non existing host name for Elasticsearch in https://github.com/geonetwork/core-geonetwork/blob/6deb3043724996966cd207cc0ad1c5643009ff66/pom.xml#L1529
2) Start up GeoNetwork
3) Access the Site information page: http://localhost:8080/geonetwork/srv/eng/admin.console#/dashboard/information
- Without the fix: all the sections are displayed empty
- With the fix: the page is displayed fine. Elasticsearch information only displays the URL as the other fields can't be retrieved.

Site information / manage Elasticsearch exceptions when trying to retrieve the index information

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/config/associated-panel/default.json

The online resources dialog for ISO19115-3.2008 allows to select metadata records to add the resources referenced by the selected metadata.
Currently the list displays also the metadata templates. 
This change filters out the templates:

Metadata editor / ISO19115-3.2008 / Filter out metadata templates inthe online resources dialog

---

web-ui/src/main/resources/catalog/components/usersearches/UserSearchesDirective.js
web-ui/src/main/resources/catalog/components/usersearches/partials/portalswitcher.html
web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html

Sort the portals by label, not by name. So the portals are sorted on their translated names, not their identifier.

Sort the portals by label, not by name (identifier)

---

core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
core/src/test/java/org/fao/geonet/kernel/ElasticsearchIndexingTest.java
csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/es/CswFilter2Es.java
csw-server/src/test/java/org/fao/geonet/kernel/csw/services/getrecords/es/CswFilter2EsTest.java
csw-server/src/test/java/org/fao/geonet/kernel/csw/services/getrecords/es/CswSortBy2EsTest.java
csw-server/src/test/java/org/fao/geonet/kernel/csw/services/getrecords/es/EsJsonHelper.java
docs/manual/docs/install-guide/installing-from-war-file.md
docs/manual/docs/maintainer-guide/statistics/index.md
docs/manual/docs/maintainer-guide/statistics/setup-elasticsearch.md
docs/manual/docs/maintainer-guide/statistics/setup-geonetwork.md
services/src/main/java/org/fao/geonet/api/es/EsHTTPProxy.java
web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
web-ui/src/main/resources/catalog/components/viewer/heatmap/HeatmapDirective.js
web-ui/src/main/resources/catalog/components/viewer/wfsfilter/WfsFilterService.js
web-ui/src/main/resources/catalog/components/viewer/wps/WpsDirective.js
web-ui/src/main/resources/catalog/locales/en-admin.json
web/src/main/webapp/xml/validation/schemaPlugins/schema-ident.xsd

Renamed ElasticSearch to Elasticsearch as it seems to be the official name of the product.
Based on the following site
https://www.elastic.co/elasticsearch/
Nowhere can I find Elastic**S**earch.  It always seems to be spelled with lowercase **s**

Rename ElasticSearch to Elasticsearch

---

services/src/main/java/org/fao/geonet/api/ApiUtils.java
services/src/main/java/org/fao/geonet/api/records/MetadataApi.java
services/src/main/java/org/fao/geonet/api/records/MetadataAssociatedApi.java
services/src/main/java/org/fao/geonet/api/related/Related.java

If attempting to call the related function for non approved record it would failing
This is a sample call that would fail
http://localhost:8080/geonetwork/srv/api/records/116/related?type=onlines&approved=false&rows=100
Switch `getAndCheckMetadataId` to `getInternalId` because `getAndCheckMetadataId` did not support id as parameter.
Also fixed bug in `getInternalId`. `metadataUtils.findOneByUuid(uuidOrInternalId).getId()` would throw an npe when findOneByUuid did not find the record.

Fix issue with canViewRecord when calling related api

---

web-ui/src/main/resources/catalog/views/default/templates/recordView/metadata.html

Remove the `Download metadata` button in the metadata block on the Metadata page.
This button is a duplicate function for one of the download options in the dropdown in the top of the page
- [x *Clean commit message*s, longer verbose messages are encouraged

Remove the `Download metadata` button on the Metadata page

---

schemas/iso19110/src/main/plugin/iso19110/index-fields/index.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl

Ignore empty codelist value (but it is better to not leave empty codelist value in encoded records).
To avoid:
Sample record for testing https://metadata.vlaanderen.be/srv/dut/catalog.search#/metadata/f1e77b4f-a174-4e2d-9af7-fe7f548b5a5c

Standard / Feature catalogues / Do not index empty codelist value

---

web-ui/src/main/resources/catalog/components/common/savedselections/partials/action.html

When saved selection is enabled the button is not of the same size as other.

Search results / Fix button size

---

core/src/main/java/org/geonetwork/http/SessionTimeoutCookieFilter.java

`request.getContextPath()` for servlets in the root context, returns an empty string instead of /. The browser doesn't receive the path, uses the request path for the cookie.
Thanks @juanluisrp for reporting the issue.

Fix path for serverTime / sessionExpiry when GeoNetwork runs in / It creates these cookies per each path.

---

web/src/main/webResources/WEB-INF/data/config/index/records.json

Some catalogues link records to others which can be in the same catalogue or in remote sites.
Links are encoded using 
```xml
<gmd:source uuidref="https://ec.europa.eu/eurostat/cache/metadata/en/env_nwat_esms.htm"
xlink:title="Water statistics on national level (env_nwat)" 
xlink:href="https://ec.europa.eu/eurostat/cache/metadata/en/env_nwat_esms.htm"/>
```
and the `xlink:title` may contain the remote record title (or the customized title cf. https://github.com/geonetwork/core-geonetwork/pull/7324)
This adds the related records title to the full text search.
Sample record
https://sdi.eea.europa.eu/catalogue/srv/eng/catalog.search#/metadata/04b55edf-9a98-4123-87ab-7845af61d07d With that change searching for `env_nwat` will return the record due to the source dataset.

Indexing / Add related record title to the full text search

---

web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
web-ui/src/main/resources/catalog/views/default/less/gn_result_default.less

Add a list styling to related records when the `data-layout="title"`
**Before**:
**After**:
Related to: https://github.com/osgeonl/geonetwork-dutch-skin/pull/76

List styling for related records

---

web-ui/src/main/resources/catalog/views/default/templates/recordView/type-series.html

Most of the time series are used as container and only provide general information. It may not be always the case, so the following changes are done in the record view for series : 
* display technical information after list of related records. 
* display the series thumbnails when there is no child.
eg. series with no child https://geocatalogue.apur.org/catalogue/srv/eng/catalog.search#/metadata/537e711a-eb13-41c9-9fc5-f351226f6e3a
series with children https://sdi.eea.europa.eu/catalogue/srv/eng/catalog.search#/metadata/34bd02bf-be87-4122-b9a2-1e846c27a786

Record view / Series / Technical information

---

docs/manual/docs/contributing/doing-a-release.md
update-version.sh

If the target version SQL migration do not exist, create it.
This will avoid the manual step https://github.com/geonetwork/core-geonetwork/blob/main/docs/manual/docs/contributing/doing-a-release.md?plain=1#L93-L98

Release / Create SQL migration script for new version

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/eng/strings.xml
schemas/iso19139/src/main/plugin/iso19139/loc/chi/strings.xml
schemas/iso19139/src/main/plugin/iso19139/loc/eng/strings.xml
schemas/iso19139/src/main/plugin/iso19139/loc/fre/strings.xml
schemas/iso19139/src/main/plugin/iso19139/loc/swe/strings.xml

We had discussion with Geonetwork regular meeting. The label "portal" is not so précised to describe. We will just use "catalogue"

change label to "Access to the catalogue"

---

services/src/main/java/org/fao/geonet/guiapi/search/XsltResponseWriter.java

Follow up of #7015, identified in GeoNetwork 3.12.x
In certain setups, accessing the no JS search page: http://localhost:8080/geonetwork/srv/search returns an error 400:
```
Error on line 71 of skin.xsl:
XTTE0790: An empty sequence is not allowed as the second argument of geonet:updateUrlPlaceholder()
2023-10-24 09:48:06,491 ERROR [geonetwork] - An empty sequence is not allowed as the second argument of geonet:updateUrlPlaceholder()
; SystemID: file:///opt/geonetwork/xslt/ui-search/../common/../skin/default/skin.xsl; Line#: 71; Column#: -1
net.sf.saxon.trans.XPathException: An empty sequence is not allowed as the second argument of geonet:updateUrlPlaceholder()
```
The class that applies the xslt transformation doesn't add the `nodeId` field. It's unclear as local testing doesn't produce …

Add node identifier parameter for xlst processing. Required in skin.xsl

---

web-ui/src/main/resources/catalog/lib/angular.ext/date.js

Since the update of WRO4J to version 1.10.1, the project could not be started on Windows machines.  
The reason was that WRO4J was trying to access a nonexistent sourcemap file.
By removing the link to the missing sourcemap, the issue is resolved.
CC: @fxprunayre

WRO4J / Fix unresolvable source map file on Windows

---

web/src/main/webapp/xslt/ui-metadata/form-builder.xsl

If button label is not empty, do not add unneeded space. This was more visible on mandatory elements.

Editor / Remove extra space on mandatory add action

---

.gitignore

This changes adds the folder `web/src/main/webapp/WEB-INF/data/data/resources/schemapublication` to `.gitignore`, as should not be committed in the code repository.
Related to https://github.com/geonetwork/core-geonetwork/pull/7337

Add web/src/main/webapp/WEB-INF/data/data/resources/schemapublication folder to .gitignore

---

.github/workflows/docs.yml
docs/manual/requirements.txt

Docs / Fix the mike version to 2.0.0 and change the parameter --no-redirect to --alias-type=copy (changed in mike 2.0.0)

---

web-ui/src/main/resources/catalog/components/admin/harvester/HarvesterDirective.js

Currently the CSW harvester, when adding a search filter, sets the field value to the first queryable field. This causes confusion to some users, as to get the list of fields, should be removed the value first.
This change displays the field with an empty value and when the user enters in it, the list of available fields:

CSW Harvester / Don't set a default search filter field

---

workers/wfsfeature-harvester/src/main/java/org/fao/geonet/harvester/wfsfeatures/worker/EsWFSFeatureIndexer.java

Was related to an issue on QGIS server side.

Harvesting / WFS / Cleaning comment

---

web-ui/src/main/resources/catalog/components/catalog/CatalogService.js
web-ui/src/main/resources/catalog/views/default/less/gn_result_default.less
web-ui/src/main/resources/catalog/views/default/templates/recordView/metadata.html
web-ui/src/main/resources/catalog/views/default/templates/recordView/technical.html

* Improve space between values (before and after in resource language, after in metadata language)
Before
After
* Unique languages in list (as multilingual record may advertise the main language in other languages) (similar to https://github.com/geonetwork/core-geonetwork/pull/6884/files) - record for testing https://www.geocat.ch/geonetwork/srv/api/records/8698bf0b-fceb-4f0f-989b-111e7c4af0a4/formatters/iso19139
* Hide language if no language defined (eg. ISO19110) - record for testing https://metadata.vlaanderen.be/srv/api/records/35CFB30F-23C1-4EFA-B846-093E2645CF8D/formatters/xml

Record view / Improve language list.

---

web-ui/src/main/resources/catalog/style/gn_metadata.less
web-ui/src/main/resources/catalog/views/default/templates/recordView/processsteps.html
web-ui/src/main/resources/catalog/views/default/templates/recordView/type-dataset.html
web-ui/src/main/resources/catalog/views/default/templates/recordView/type-series.html

Distributor can be referenced as resource contact in identification with a distributor role or in distribution info. Contact encoded in distribution info were not displayed, they are now displayed next to API, download and links.

Record view / Add distributor contact.

---

web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js

In the `gnLinkServiceToDataset` directive, a filter is applied to only display non-service resource type in the modal. 
However, this filter is applied on the incorrect index field `type` instead of `resourceType`.  
By modifying this filter, only the dataset/fc records are shown.
Before:  
After:  
CC: @fxprunayre

Ensure only non-service records are display when linking a dataset from a service

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
web-ui/src/main/resources/catalog/components/search/mdview/mdviewDirective.js
web-ui/src/main/resources/catalog/components/search/mdview/partials/qualitymeasures.html
web-ui/src/main/resources/catalog/locales/en-v4.json
web-ui/src/main/resources/catalog/views/default/templates/recordView/type-dataset.html
web/src/main/webResources/WEB-INF/data/config/index/records.json

The same measure may be followed over time - Add the date information if available.
Add measure schema in index definition.

Record view / DQ / Add measure date information

---

web-ui/src/main/resources/catalog/components/search/mdview/mdviewModule.js
web-ui/src/main/resources/catalog/components/search/resultsview/SelectionDirective.js
web-ui/src/main/resources/catalog/components/validationtools/GnmdInspireValidationDirective.js

It was noticed that if we attempted to handle a delete event on a records and we throw an error like this
`throw new WebApplicationException().withMessageKey("message.key"));`
The API Error would contain a message and null description because the description key was not supplied.
As the record delete error handling only seems to expect to use the description, the user would end up seeing a message like the following
 It can be fixed if we change the error to the following however I believe all errors should handle both message and description.
`throw new WebApplicationException().withDescriptionKey("message.key"));`
This PR is to update some cases where the error message was only using description instead of using one of the other.

Fix some cases that were not considering both message and description when displaying errors.

---

core/src/main/java/org/fao/geonet/languages/LocaleMessages.java

When getting locale message, default locale to LocaleContextHolder when locale is null
It was noticed that if we did something like the following when calling an api.
`throw new WebApplicationException().withMessageKey("message.key"));`
The API Error would contain the message based on the key as follow
"message.key"
The reason for this is because no locale was identified in the exception.  If we do the following 
 
`throw new WebApplicationException().withMessageKey("message.key").withLocale(LocaleContextHolder.getLocale());`
Then the API Error would contain the message on the key as follow
"Some Text for locale"
Since it is better to show text to the end users instead of showing the message key, this PR will default the message key to LocaleContextHolder.getLocale() automatically so that …

When getting locale message, default locale to LocaleContextHolder when locale is null

---

web-ui/src/main/resources/catalog/components/common/map/partials/drawbbox.html
web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
web-ui/src/main/resources/catalog/components/utility/partials/regionpicker.html
web-ui/src/main/resources/catalog/templates/admin/harvest/type/csw.html

Region picker used in the CSW harvester doesn't work correctly with a regions thesaurus that has items in non English language.
The list of regions was displayed with empty labels:
With the fix the list is displayed correctly:
Test case:
1) Replace the regions thesaurus with this [one](https://www.nationaalgeoregister.nl/geonetwork/srv/eng/thesaurus.download?ref=external.place.regions)
2) Switch to Dutch UI and create a CSW harvester filling the URL of the harvester
3) in the `BBOX filter`, select the value `Nederland`
4) Without the fix, a list with empty labels is displayed. With the fix the labels are displayed correctly.

Fix language for region picker directives

---

inspire-atom/src/main/java/org/fao/geonet/inspireatom/harvester/InspireAtomHarvester.java

In the remote INSPIRE Atom Feeds harvester, could happen that several service feeds reference the same dataset. This produces duplicated entries in the InspireAtomFeed, causing errors other parts of the application, for example when trying to use the INSPIRE ATOM search endpoint:
http://localhost:8080/geonetwork/opensearch/eng/f95c6429-2cdf-47b8-bc2a-e614440050b8/search
```
2023-11-15T19:31:27,693 ERROR [geonetwork] - query did not return a unique result: 2; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 2
org.springframework.dao.IncorrectResultSizeDataAccessException: query did not return a unique result: 2; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 2
at …
```

Remote INSPIRE Atom Feeds harvester - Remove duplicates by dataset identifier

---

inspire-atom/src/main/java/org/fao/geonet/services/inspireatom/AtomSearch.java

Follow up of #6395
The INSPIRE Atom Search service, when providing the service metadata uuid was not filtering the related dataset feeds, returning all the dataset feeds available.

INSPIRE Atom Search - add missing filter by feed dataset identifiers

---

web-ui/src/main/resources/catalog/components/utility/partials/recordOriginLogo.html
web-ui/src/main/resources/catalog/views/default/templates/recordView/metadata.html

mini styling fix, I saw this and figured it would be a mistake
before
after

Consistent styling of recordgroup label

---

web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js
web-ui/src/main/resources/catalog/components/search/mdview/mdviewModule.js
web-ui/src/main/resources/catalog/locales/ca-core.json
web-ui/src/main/resources/catalog/locales/cs-core.json
web-ui/src/main/resources/catalog/locales/da-core.json
web-ui/src/main/resources/catalog/locales/de-core.json
web-ui/src/main/resources/catalog/locales/en-core.json
web-ui/src/main/resources/catalog/locales/es-core.json
web-ui/src/main/resources/catalog/locales/fi-core.json
web-ui/src/main/resources/catalog/locales/fr-core.json
web-ui/src/main/resources/catalog/locales/is-core.json
web-ui/src/main/resources/catalog/locales/it-core.json
web-ui/src/main/resources/catalog/locales/ko-core.json
web-ui/src/main/resources/catalog/locales/nl-core.json
web-ui/src/main/resources/catalog/locales/pt-core.json
web-ui/src/main/resources/catalog/locales/ru-core.json
web-ui/src/main/resources/catalog/locales/sk-core.json
web-ui/src/main/resources/catalog/locales/sv-core.json
web-ui/src/main/resources/catalog/locales/zh-core.json
web-ui/src/main/resources/catalog/views/default/templates/recordView/recordView.html

Currently when cancelling a working copy , the user is redirected to the search results. With this change, the record view page is reloaded with the approved version.

Metadata workflow / Record view / reload the page with the approved version when cancelling a working copy

---

web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html

Follow up of #7417
Test cases:
**CASE 1: With the admin user try to reset the admin user password.**
(Case fixed in the code change)
1) With the fix, the old password is requested and the password change works. (Without the fix, the old password is not requested and the password change fails).
**CASE 2: With a non-admin user, try to reset his password.**
(Additional case to test to verify is not broken by the code change)
1) Create a new user 
2) Login with the new user
3) The reset password for the user request the old and new password. The password change works as expected.
**CASE 3: Reset passwords with the setting to allow reset user passwords by admin users.**
(Additional case to test to verify is not broken by the code change)
1) Add the following setting to the database and restart …

Reset user password dialog - don't display the field to request the old password for administrators - unify UI check with backend check

---

web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
web-ui/src/main/resources/catalog/js/admin/UserGroupController.js
web-ui/src/main/resources/catalog/locales/en-admin.json
web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html

Replace https://github.com/geonetwork/core-geonetwork/pull/3543 for main (fix conflicts, add missing translation)
Follow up of https://github.com/geonetwork/core-geonetwork/pull/7449
- Usage of `ng-messages` for validation errors, adding missing validations like maxlength.
- Added directive to check password/confirm passwords are equal in users form.
- Added directive to confirm exiting a form with changes.
Initial changes done for the users form to review. If looks fine the plan is to update other administration forms to unify the validation across all forms.

Administration form validation improvements

---

core/src/main/java/org/fao/geonet/util/WorkflowUtil.java
core/src/test/java/org/fao/geonet/util/WorkflowUtilTest.java

Test case:
With the workflow disabled.
1. Enable the metadata history in the System Settings
2. Create a new metadata
3. Go to the history page, no workflow events listed --> OK
4. Publish the metadata
5. Go to the history page, **without the change** workflow events listed --> NO OK

Fix check to verify if a group has enabled the workflow, checking if the workflow is also enabled

---

core/src/main/java/org/fao/geonet/kernel/security/openidconnect/GeonetworkOidcUserService.java
core/src/main/java/org/fao/geonet/kernel/security/openidconnect/OidcUser2GeonetworkUser.java

OpenId / Use the user profile configured locally if the configuration option OPENIDCONNECT_USERPROFILEUPDATEENABLED is disabled

---

core/src/main/java/org/fao/geonet/util/XslUtil.java
schemas/dublin-core/src/main/plugin/dublin-core/index-fields/index.xsl
schemas/iso19110/src/main/plugin/iso19110/index-fields/index.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/jsonld/iso19115-3.2018-to-jsonld.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index-subtemplate.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/utility-tpl.xsl
schemas/iso19139/src/main/plugin/iso19139/formatter/jsonld/iso19139-to-jsonld.xsl
schemas/iso19139/src/main/plugin/iso19139/index-fields/index-subtemplate.xsl
schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
schemas/iso19139/src/main/plugin/iso19139/layout/utility-tpl.xsl
services/src/main/java/org/fao/geonet/api/es/EsHTTPProxy.java
web/src/main/webapp/xslt/common/index-utils.xsl

Replace xslt JSON texts escaping to use Apache Commons Text:
https://commons.apache.org/proper/commons-text/javadocs/api-release/org/apache/commons/text/StringEscapeUtils.html#escapeJson(java.lang.String)
This provides the benefit of not needing to maintain ad hoc code, whereas there are well-known libraries that implement these types of features, covered by unit tests, which are difficult to manage with XSLT.

Use Apache Commons Text library to escape JSON content in xslt processing

---

core/src/main/java/org/fao/geonet/constants/Edit.java
core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java

Add ownerId to geonet:info
It is a more reliable way to identify the exact user since the owername is not a reliable way to connect the metadata record to the user.

Add ownerId to geonet:info

---

core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java

Currently when a parsing error of the Elasticsearch index configuration happens, the following entry is added in the log file:
```
2023-12-06T10:59:01,750 ERROR [geonetwork.index] - Could not connect to index 'gn-records'. Error is Failed to parse content to map. Is the index server  up and running?
```
Informs about a parsing error, but no further details.
This change logs the exception, that contains details about the location of the error in the configuration file, useful to fix the issue:
```
2023-12-06T10:59:01,750 ERROR [geonetwork.index] - Could not connect to index 'gn-records'. Error is Failed to parse content to map. Is the index server  up and running?
org.elasticsearch.ElasticsearchParseException: Failed to parse content to map
...
Caused by: …
```

Elasticsearch index creation - log the exception when a parsing error of the index configuration file occurs

---

web/src/main/webResources/WEB-INF/data/config/index/records.json

In GeoNetwork 3.12 a Lucene field `orgName` was indexed that tracked the organisations from types of contacts: metadata contact / resource contact / distribution contact, that could be used for searches and facet filters.
In GeoNetwork 4.x with Elasticsearch specific fields are created for each contact type, this change creates a new field `organisationName` that tracks the organisations of the different types of contacts.

Metadata indexing - create an organisation name field that tracks the organisations of the different types of contacts

---

web-ui/src/main/resources/catalog/components/metadataactions/RelatedDirective.js
web-ui/src/main/resources/catalog/components/metadataactions/partials/recordsFilters.html
web-ui/src/main/resources/catalog/locales/en-v4.json
web-ui/src/main/resources/catalog/views/default/less/gn_card_default.less
web-ui/src/main/resources/catalog/views/default/templates/recordView/type-series.html

This PR restyles and restructures the `composed of` block on the Metadata page. Columns and whitespace are added and the buttonbar is now split into separate buttons with a clear `active` state.
**Screenshot** of the new layout

Restructure the 'composed of' block on the detail page

---

web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js

Small visual fix for the 'letter-in-a-circle' icon for firefox. The text is not vertically centered. Tested result as well in chromium and edge. Adding the additional attribute seems to help (though not completely accurate still).
Before: 
After:

Visual fix for icon text circles (firefox)

---

harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java
harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geoPREST/Aligner.java
harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java
harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet20/Aligner.java
harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/oaipmh/Harvester.java
harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/webdav/Harvester.java

I was setting up harvesters and noticed that, when not setting the groupOwner and owner, I received a cryptic error after the harvester finished.
Turns out, a nullpointer was created due to the groupOwner being passed as 'undefined', eventually resulting in a null list of UUID's.
Apart from a durable fix I modified the parameter parsing of the groupOwner (making use of a pre-existing method, present in the aligner), making it at least not fail anymore.

Harvesters without owner > cryptic parse exception

---

domain/src/main/java/org/fao/geonet/domain/page/Page.java
services/src/main/java/org/fao/geonet/api/pages/PageProperties.java
services/src/main/java/org/fao/geonet/api/pages/PagesAPI.java
services/src/test/java/org/fao/geonet/api/pages/PagesApiTest.java
web-ui/src/main/resources/catalog/components/pages/partials/menu-page.html
web-ui/src/main/resources/catalog/locales/en-v4.json
web-ui/src/main/resources/catalog/templates/admin/settings/static-pages.html
web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v442/migrate-default.sql

Added a configurable icon to the static pages. The icon is not shown when not supplied. Added help text indicating it needs to be a font-awesome icon.
@fxprunayre not sure what happens for submenus - the context leads me to believe only top / footer items are allowed for now, and that seems to work fine on my end.

Add icon to static pages, configurable

---

schemas/iso19139/src/main/plugin/iso19139/present/csw/csw-full.xsl

This fix resolves ticket #6742 , allowing full compatibility of iso19139-rndt metadata to be displayed via QGIS

Update iso19139 csw-full.xsl

---

web-ui/src/main/resources/catalog/components/utility/partials/indexerrorpanel.html

Remove ?debug from link to admin dashboard.

Remove ?debug from link to admin dashboard.

---

schemas/iso19139/src/main/plugin/iso19139/loc/ger/codelists.xml

The codelist value `map` in German had an untranslated value:
https://github.com/geonetwork/core-geonetwork/blob/0c8c74edce3df0e789f022f6ebd0d07bd4c08fdd/schemas/iso19139/src/main/plugin/iso19139/loc/ger/codelists.xml#L1583-L1587
Interfering with the German `map` translation in:
https://github.com/geonetwork/core-geonetwork/blob/0c8c74edce3df0e789f022f6ebd0d07bd4c08fdd/web-ui/src/main/resources/catalog/locales/de-core.json#L161
And causing the search map displaying the English value in the German user interface:
----
Test case:
1) Go to the search page in German: http://localhost:8080/geonetwork/srv/ger/catalog.search
- Without the fix: the map search label displays the value `Map` (NO OK)
- With the fix: the map search labels displays the value `Karte` (OK)
----
Maybe we should use some …

Add German codelist translations for scope code

---

web-ui/src/main/resources/catalog/components/catalog/CatalogService.js

A _very_ minor bug: we had the following case in our UI (a spurious comma after the language "Nederlands"):
When `otherLanguage` is null this case is created. Adding a filter for that value fixes the frontend bug.

Fix for absent language leading to spurious comma

---

services/src/main/java/org/fao/geonet/api/records/formatters/ImageReplacedElementFactory.java

Fixes #7540
The pull request contains also several Sonarlint fixes.
Test case:
1) Create an iso19139 metadata and upload an overview image.
2) In the Record view, export the metadata to PDF.
- Without the fix: the overview image is not displayed in the PDF.
- With the fix: the overview image is displayed in the PDF.
---
Aside of the changes this class requires review and cleanup that will be reported in a separate issue for clarity.

Overview not shown in PDF export when the overview image is stored in GeoNetwork and requires authentication to access it.

---

services/src/main/java/org/fao/geonet/api/ApiParams.java
services/src/main/java/org/fao/geonet/api/records/DoiApi.java
services/src/main/java/org/fao/geonet/api/records/InspireValidationApi.java
services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsActionsApi.java
services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java
services/src/main/java/org/fao/geonet/api/records/formatters/CacheApi.java
services/src/main/java/org/fao/geonet/api/records/formatters/FormatterAdminApi.java
services/src/main/java/org/fao/geonet/api/sld/SldApi.java
services/src/main/java/org/fao/geonet/api/tools/i18n/TranslationApi.java
services/src/main/java/org/fao/geonet/api/tools/mail/MailApi.java
services/src/main/java/org/fao/geonet/api/tools/migration/MigrationApi.java

Ensure that all tags have the same description.
If we post the open api spec to https://editor.swagger.io/ there are a bunch of errors.  
This PR is to fix the following errors. 
The issue is caused by duplicate tags due to the descriptions being different.
This PR is to ensure that the tags causing errors are using the same tag name and description.

Fix duplicate SpringDoc tags.

---

services/src/main/java/org/fao/geonet/api/OpenApiConfig.java
services/src/main/java/org/fao/geonet/api/site/SiteApi.java

Fix initialization of SpringDoc so that it does not use null servername and null version
Before this fix. The initial deployment of geonetwork in a new database would cause Spring Doc api to look like the following
Also if checking the yaml api on https://editor.swagger.io/, we would see the following error because the version was not set.
The issue was mostly caused by 2 contexts being used. 
JeevesApplicationContext was being loaded first and at that time, the database was not initialized with the data and ended up returning a null servername and null version from the settings manager.
Then it would later initialize WebApplicationContext and this would initialized the correct version.  But when going to /doc/api/ it was using the JeevesApplicationContext version which was incorrect. …

Fix initialization of SpringDoc so that it does not use null servername and null version

---

services/src/main/java/org/fao/geonet/api/records/MetadataIndexApi.java

API should return a structured object instead of JSONObject
Updated indexer to return an object IndexResponse instead of JSONObject
This was causing a couple issues.
1 - JSONObject is a weird object to be returned from an API when the results are really a String.
2 - There were a couple API's that were returning JSONObject but not the same one. One was net.sf.json.JSONObject and the other was org.json.JSONObject. This was causing a conflict in the SpringDoc API which was causing bugs in the open api specification.  The JSONObject schema could change on each application restart.
3 - It was causing issues when trying to use CodeGen as it has issue using JSONObject objects as it conflict with the normal JSONObject.
This fix updates the indexer so that it returns a new IndexResponse object.

Spring doc API for index should return a structured object instead of JSONObject

---

core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataIndexer.java
pom.xml

Update minor versions for these dependencies:
- Jetty -> `9.4.52.v20230823`
- Spring Framework -> `5.3.30`
- Spring Security -> `5.7.11`
- Jackson -> `2.10.5`

GeoNetwork 4.2.x minor versions library updates

---

services/src/main/java/org/fao/geonet/api/groups/GroupsApi.java
services/src/main/java/org/fao/geonet/api/mapservers/MapServersApi.java

Add missing apiResponse for group and map api
Without these missing  apiResponses, it was creating incorrect open api spec for the api.
It was also causing issues when using codegen as it would think the api did not return any data.

Add missing apiResponse for group and map api

---

services/src/main/java/org/fao/geonet/api/OpenApiController.java

Update SpringDoc json/yaml generator to make the results more deterministic.
This will make it easier to compare different versions between gn releases.
These are the properties that were enabled.
springdoc.writer-with-order-by-keys=true
springdoc.writer-with-default-pretty-printer=true

Update SpringDoc json/yaml generator to make the results more deterministic.

---

services/src/main/java/org/fao/geonet/api/links/LinksApi.java

API should accept a structured object instead of JSONObject
Updated link search to accept an object LinkFilter instead of JSONObject
This was causing a couple issues.
1 - JSONObject is a weird object to be accepted from an API when the results are really a String.
2 - There were a couple API's that were returning JSONObject but not the same one. One was net.sf.json.JSONObject and the other was org.json.JSONObject. This was causing a conflict in the SpringDoc API which was causing bugs in the open api specification. The JSONObject schema could change on each application restart. (i.e. see  #7584)
3 - It was causing issues when trying to use CodeGen as it has issue using JSONObject objects as it conflict with the normal JSONObject.
Note: Usage description had "`groupId: 12`" as a sample …

Spring doc API for link api should accept a structured object instead of JSONObject

---

core/src/main/java/org/fao/geonet/kernel/setting/Settings.java
services/src/main/java/org/fao/geonet/api/records/extent/MapRenderer.java
services/src/test/java/org/fao/geonet/api/records/extent/MapRendererTest.java
web-ui/src/main/resources/catalog/locales/en-admin.json
web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v442/migrate-default.sql

Similar to #6982, but for the metadata map extent API.
Adds a new setting to configure to use the geodesic extents when using a local projection (for global projections: EPSG:4326 and EPSG:3857, the setting is ignored).
By default, the setting is disabled, displaying the extents planars (being similar to #6982).
With the setting **disabled**, using a local projection:
With the setting **enabled**, using a local projection:
--- 
Includes Sonarlint improvements.

Metadata extents API / Make configurable to display the metadata bboxes using geodesic extents for local projections.

---

web-ui/src/main/resources/catalog/components/elasticsearch/directives/FacetDirective.js
web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facet-cards.html
web-ui/src/main/resources/catalog/js/CatController.js

Currently the topic categories and INSPIRE themes filters in the home page seem sorted by the amount of metadata in each category. This change adds support to sort the values alphabetically.
Before:
After:

Home page / sort topic categories and INSPIRE themes facets alphabetically

---

schemas/iso19139/src/main/plugin/iso19139/schematron/schematron-rules-iso.sch
web/src/test/java/org/fao/geonet/kernel/schema/SchematronRulesIsoTest.java

I believe to have identified a bug in a previous PR (https://github.com/geonetwork/core-geonetwork/pull/6930) @fxprunayre .
When adding multiple related datasets the duplicate check fails when they have the same association and initiative. More specifically: in my test I'm adding multiple dataset with **no** initiative and identical association values.
The schematron check compares the `$mdRefRef` variable but that contains multiple elements instead of the desired UUID (as I understood). In my tests, `$mdRefRef` contains two elements: `gco:CharacterString` and `geonet:element`. The comparison in `$hasNoDuplicate` then proceeds to fail.

fix duplicate check on uuid+initiative+association

---

web/src/main/webapp/xslt/ui-metadata/edit/edit-embedded.xsl

Adding some element attributes causes the element section is removed from the user interface until the metadata is saved. See below the explanation.
Test case:
1) Create an iso19139 metadata
2) In the XML view add the following resource constraint:
```
<gmd:resourceConstraints>
<gmd:MD_LegalConstraints>
<gmd:accessConstraints>
<gmd:MD_RestrictionCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_RestrictionCode"
codeListValue="otherRestrictions"/>
</gmd:accessConstraints>
<gmd:otherConstraints>
<gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/noLimitations">No limitations on public access</gmx:Anchor>
</gmd:otherConstraints>
</gmd:MD_LegalConstraints>
</gmd:resourceConstraints>
```
3) In the default view, try to …

Fix add element attribute in the metadata editor

---

web/src/main/webResources/WEB-INF/urlrewrite.xml
web/src/main/webapp/xslt/services/inspire-atom/opensearch.xsl
web/src/main/webapp/xslt/services/inspire-atom/opensearchdescription.xsl

Follow up of https://github.com/geonetwork/core-geonetwork/pull/6395
The URL in the ATOM Feeds `OpenSearchDescription.xml` document pointed to `/htmlsearch`. This service is not defined in GeoNetwork 4.x and also in GeoNetwork 3.12.x was redirecting to the application search results page. What looks not correct as the endpoint is to return ATOM Feeds.
Updated to use the correct endpoint.
Test case (with local feeds): 
1) Enable the INSPIRE setting
2) Create an iso19139 service metadata
3) Request the OpenSearchDescription.xml document: 
http://localhost:8080/geonetwork/srv/opensearch/OpenSearchDescription.xml?uuid=SERVICEUUID
Without the change:
```
http://localhost:8080/geonetwork/srv/en/opensearch/htmlsearch?q={searchTerms?}
```
Endpoint fails as doesn't exist
``` …
```

INSPIRE Atom feeds / Fix link to atom search endpoint

---

workers/wfsfeature-harvester/src/main/java/org/fao/geonet/harvester/wfsfeatures/model/WFSHarvesterParameter.java
workers/wfsfeature-harvester/src/main/java/org/fao/geonet/harvester/wfsfeatures/worker/WFSClientWithStrategyInvestigator.java
workers/wfsfeature-harvester/src/main/java/org/fao/geonet/harvester/wfsfeatures/worker/WFSDataStoreWithStrategyInvestigator.java
workers/wfsfeature-harvester/src/main/java/org/fao/geonet/harvester/wfsfeatures/worker/WFSHarvesterExchangeState.java

Mapserver may return by default GetCapabilities in version 2.0.0. Depending on the URL set in metadata records, WFS harvesting may fails with:
```
2023-10-27T10:54:42,350 ERROR [geonetwork.harvest.wfs.features] -
Failed to connect to server 'http://geoservices.brgm.fr/geologie?language=fre&'.
Error is class net.opengis.wfs20.impl.WFSCapabilitiesTypeImpl
cannot be cast to class net.opengis.wfs.WFSCapabilitiesType
(net.opengis.wfs20.impl.WFSCapabilitiesTypeImpl and net.opengis.wfs.WFSCapabilitiesType
are in unnamed module of loader org.eclipse.jetty.webapp.WebAppClassLoader @cda6100)
```
because of the `MapServerWFSStrategy` extending WFS1 strategy.
Use `StrictWFS_2_0_Strategy` if harvesting is done using 2.0.0 on MapServer.
Can be tested with
```
curl …
```

Harvesting / WFS feature / Add WFS2 support for MapServer

---

services/src/main/java/org/fao/geonet/api/registries/vocabularies/KeywordsApi.java

An api should not do GET/POST in the same operation as it seems to cause issues in open api specification document.
It caused duplicates duplicate OperationID that would occur (getKeywordById and getKeywordById_1)
This PR will split 2 OperationID (getKeywordById and getKeywordByIds)

Fix duplicate operation id caused by use of 2 methods  GET/POST method from getKeywordById api

---

pom.xml
web/src/main/java/org/fao/geonet/proxy/URITemplateProxyServlet.java
web/src/main/webResources/WEB-INF/web.xml

This change request adds configuration to restrict the hosts and ports accessible by the http proxy servlet, independently of the security mode configured.
- `proxy.excludeHosts`: Regular expression to match a set of host names  / IP's that should not be allowed to access by the http proxy, for example, the ones related to localhost.
- By default, has been changed to only allow the proxy to access ports 80 and 443, additional ports can be configured in `proxy.allowPorts`
These  properties can be configured using multiple methods, not only as init parameter
in `web.xml` servlet's config, but also as environment variable, system property or `config.properties`
entry.

Configuration to restrict the hosts and ports accessible by the http proxy servlet

---

web-ui/src/main/resources/catalog/components/common/openlayers/olMapDirective.js

Used to optimize resize when entering is done.
Solves wrong centering of bbox.

Avoid race condition, resize map once target size ok

---

web-ui/src/main/resources/catalog/components/search/mdview/partials/contact.html

We modified the visualisation of the _call_ element to be in line with the other elements: icon + text. This could be relevant for core too?
Before:
Afer:

Using icon for call/phone

---

services/src/main/java/org/fao/geonet/api/records/model/related/RelatedItemType.java
services/src/main/java/org/fao/geonet/config/PublicationOption.java

Set API enum as ref
- This will allow common reference to enum in the open api spec.
Note this also fixes and issue when attempting to build codegen.
`error: incompatible types: List<InnerEnum> cannot be converted to List<String>`
Here is an example reference for ReservedOperation after this fix.
```
PublicationOption:
type: object
example: null
properties:
additionalPublications:
type: object
additionalProperties:
type: array
example: null
items:
$ref: '#/components/schemas/ReservedOperation'
example: null
name:
type: string
example: null
publicationGroup:
type: string
enum:
- all
- intranet
- guest
example: null
publicationOperations:
type: array
example: null
items:
$ref: '#/components/schemas/ReservedOperation'
```
```
ReservedOperation:
type: string
enum:
- view
- download
- editing …
```

Spring doc - Set API enum as ref

---

services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
services/src/main/java/org/fao/geonet/api/records/MetadataProcessApi.java
services/src/main/java/org/fao/geonet/api/records/MetadataTagApi.java
services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java
services/src/main/java/org/fao/geonet/api/sources/SourcesApi.java

Fix issue with @ResponseStatus and @ApiResponse being out of sync.
Update @ApiResponse so that they are in sync with @ResponseStatus
It would not create the proper Open API documentation when these return codes were not correct.
Note: It was noticed that some API's have NO_CONTENT (204) but it is not a void function?  But when I tested some they did not seem to return any content.

Fix issue with @ResponseStatus and @ApiResponse being out of sync.

---

services/src/main/java/org/fao/geonet/api/site/SiteApi.java

The list of available transformations to apply during harvesting or importing is incomplete on Windows.  
This is caused by using a hardcoded "/" for file path comparison. The PR changes this to make it OS-agnostic.   
Before: 
After: 
CC @fxprunayre

Fix linux specific file separator used for harvester transform option

---

schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl

At some point I ended up with a record that triggered an index error, due to the selection of `measureDate` retrieving multiple results. This fixes that erroneous state, in line with the other variables.

Preventing indexing error by limiting selection amount

---

core/src/main/java/org/fao/geonet/api/records/attachments/AbstractStore.java
datastorages/cmis/src/main/java/org/fao/geonet/api/records/attachments/CMISStore.java
datastorages/jcloud/src/main/java/org/fao/geonet/api/records/attachments/JCloudStore.java

Based on this PR https://github.com/geonetwork/core-geonetwork/pull/7556 there seems to be some bug in cmisStore where the ServiceContext was passed as null object. 
The issue is not reproduceable in the 4.0 main branch due to the mechanism difference. But it's reproduceable in the 3.12 backport commit https://github.com/ianwallen/core-geonetwork/commit/91795de5fdc059c04334b10d45f7a00ef1daf38f
The null pointer avoidance is needed in order to make it work
- [] *Clean commit history* broken into understandable chucks, avoiding big commits with hundreds of files, cautious of reformatting and whitespace changes
- [] *API Changes* are identified in commit messages
- [] *Testing* provided for features or enhancements using [automatic tests](https://github.com/geonetwork/core-geonetwork/blob/main …

Service context null pointer

---

inspire-atom/src/main/java/org/fao/geonet/services/inspireatom/AtomSearch.java

Fix duplicate API endpoint /feeds
There were GET 2 apis with the end point /feeds.
~~One was renamed to /feedsAsHtml~~
Merged into one api and check accept header to determine the results to be returned.
I'm not sure where /feeds was used so I don't know which one was supposed to be called?  So I just renamed it based on the function name.

Fix duplicate API endpoint /feeds

---

services/src/main/java/org/fao/geonet/api/OpenApiConfig.java
services/src/main/java/org/fao/geonet/api/records/CatalogApi.java
services/src/main/java/org/fao/geonet/api/records/MetadataApi.java
services/src/main/java/org/fao/geonet/api/records/MetadataAssociatedApi.java
services/src/main/java/org/fao/geonet/api/records/MetadataProcessApi.java
services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
services/src/main/java/org/fao/geonet/api/records/MetadataTagApi.java
services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsActionsApi.java
services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java
services/src/main/java/org/fao/geonet/api/related/Related.java
web-ui/src/main/resources/catalog/components/common/openlayers/olMapDirective.js
web-ui/src/main/resources/catalog/views/default/templates/recordView/type-series.html

Changed http to https for urls that appear in open api specification.
Also fixed some minor formatting.

Changed http to https for urls that appear in open api specification.

---

csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/es/CswFilter2Es.java
csw-server/src/test/java/org/fao/geonet/kernel/csw/services/getrecords/es/CswFilter2EsTest.java
web-ui/src/main/resources/catalog/views/default/templates/recordView/technical.html
web-ui/src/main/resources/catalog/views/default/templates/recordView/type-series.html

See #7527
Includes also Sonarlint improvements.

CSW GetRecords doesn't escape query values when creating the Elasticsearch query

---

services/src/main/java/org/fao/geonet/api/mapservers/MapServersApi.java
services/src/main/java/org/fao/geonet/api/records/MetadataApi.java
services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
services/src/main/java/org/fao/geonet/api/records/editing/MetadataEditingApi.java
services/src/main/java/org/fao/geonet/api/site/SiteApi.java
services/src/main/java/org/fao/geonet/api/tools/i18n/TranslationApi.java

OperationId are generally created based on the function name.  In some cases multiple function names were the same and this was causing OperationId conflicts which was causing one to be called functionName and the other to be called functionName_1.  
The main issue is that each time the application is restarted and the open api spec document is initially created i the cache it can flip which function is called functionName and functionName_1.  So if this is not fixed then the open api spec can change each time the application is restarted.
By simply renaming the function names, it resolves the duplicate OperationId.
Note: there are still other cases of functionName_1 but they are due to other issues that is that will be resolved in another PR.

Fix SpringDoc duplicate OperationId

---

services/src/main/java/org/fao/geonet/api/es/EsHTTPProxy.java

Add missing @ApiResponse status for successful api search response.
Otherwise OpenAPI spec was missing response which caused issues when using codegen.
Fixed body parameters and removed httpEntity.getBody() 
Also added example value for body.
Before this PR search responce for /_msearch and /_search open api spec looks like this
```
responses:
"200":
description: OK
```
After this PR the response will look like this
```
responses:
"200":
content:
application/json:
schema:
type: string
example: null
description: Search results.
```

Add missing @ApiResponse status for successful api search response.

---

services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java

Cleanup consumes section from metadata insert api.
The insert api only accepts XML so remove others.
Attempted to insert JSON data and it fails when attempting to parse it into XML.
If there is any reason to keep the other consumes then please provide use case.

Cleanup consumes section from metadata insert api.

---

services/src/main/java/org/fao/geonet/api/OpenApiController.java

Remove default response from open api specification.
This will remove the following default response that is added to all api's.
And this is the related Yaml for all responses.
```
default:
content:
application/json: {}
description: default response
```
This default causes issue when using codegen because it will apply the default to all api's making it difficult to change the accept headers in the api calls as they will all default to application/json.
Tested with OpenApi codegenerator and the only option to set the accept headers is by using something like 
`.getApiClient().addDefaultHeader(HttpHeaders.ACCEPT, MediaType.APPLICATION_XML_VALUE);`
However, this fails to work when we want to use a mimetype other than `application/json` because the default headers will not overwrite this …

Remove default response from open api specification.

---

.github/workflows/codeql-analysis.yml
.github/workflows/linux.yml
docs/manual/pom.xml
pom.xml
release/README.md
release/build.xml
release/pom.xml
web/pom.xml

- `Funded by GeoCat BV by way of GeoNetwork Enterprise product (thank you customers!)`

release module build workflow improvements / fixes

---

.github/workflows/sonarcloud.yml

Sonarcloud analyzer now requires at least Java 17.
- `Funded by GeoCat BV by way of GeoNetwork Enterprise product (thank you customers!)`

Use Java 21 for Sonarcloud plugin

---

web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html

Online resources with `OGC:WFS` display a WFS selector to dowload the data in the metadata record view.
In `main` and `4.2.x` requires that the online resource has a name defined. Otherwise, it's not displayed:
This behaviour was available in `3.12` version, but seems was removed in `main`:
https://github.com/geonetwork/core-geonetwork/blob/5decddaa13e4bfac2b3696a656d584cfaa963f52/web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html#L90-L94
This change restores the behaviour from `3.12` version:
---
Test case:
1) Create an iso19139 metadata
2) And an online resource with protocol OGC:WFS, providing the URL of a WFS service. Leave empty the name and description fields.
3) Go to the metadata page:
- Without the fix: The WFS download selector is not displayed.
- …

Record view / Display WFS downloads for WFS online resources without a name defined

---

web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/remote-record-selector.html

Fix error on edit page:  elements with non-unique id gnRemoteRecordUrl

Fix error on edit page: elements with non-unique id #gnRemoteRecordUrl

---

docs/manual/docs/index.fr.md
docs/manual/docs/index.md
docs/manual/overrides/assets/stylesheets/extra.css
docs/manual/requirements.txt

Fix the grid on the homepage of the documentation.
Rename `.grid` to `.gn-grid` to avoid conflicting classnames, and some additional styling so content doesn't break between columns.
When the documentation is released and deployed online styles were conflicting. The styles are renamed but the conflict didn't occur locally, so hopefully it's solved.
**Before**
**After**
- [x *Good housekeeping* of code, cleaning up comments, tests, and documentation

Fix the grid on the homepage of the documentation

---

docs/manual/docs/contributing/doing-a-release.md

Follow up of #7412 with updates to unify the release versions used in the different sections of `Doing a release` page, identified while backporting #7412 to `4.2.x`branch.
This PR is only for `main` branch, should not be backported.

Documentation / Unify version numbers in doing a release page

---

core/src/main/java/org/fao/geonet/kernel/XmlSerializer.java
core/src/test/java/org/fao/geonet/kernel/XmlSerializerIntegrationTest.java
services/src/main/java/org/fao/geonet/api/records/formatters/FormatterApi.java
services/src/main/java/org/fao/geonet/guiservices/util/Env.java
services/src/test/java/org/fao/geonet/api/records/formatters/AbstractFormatterTest.java
services/src/test/java/org/fao/geonet/api/records/formatters/FormatterApiIntegrationTest.java
web/src/main/java/org/fao/geonet/Geonetwork.java

Affected API calls:
* http://localhost:8080/geonetwork/srv/api/records/720ceda7-a9ea-4bbe-896a-04925c44a7f0/formatters/xyz
* http://localhost:8080/geonetwork/srv/api/records/720ceda7-a9ea-4bbe-896a-04925c44a7f0/related?type=thumbnails&type=onlines
For testing, add a record with 2 online resources. Add withheld attribute to one of them, call the related API. Sometimes 1 or 2 links are returned (it does not happen always, but usually if accessing the same API call with a browser and Curl using the same session the problem can be observed). A variable was set using ThreadLocal which looks to be the cause of this. It was noticed while opening the editor not always listing all distribution links. Withheld elements are always hidden properly for anonymous user.
```
for i in {1..20}
do
curl -s …
```

Formatter / Withheld element not always hidden.

---

.github/workflows/mvn-dep-tree.yml

[Backport 4.2.x] Bump advanced-security/maven-dependency-submission-action from 3 to 4

---

services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java

Fix mimetypes on attachments as some were incorrect.
i.e. it could produce the following invalid mime types - text/txt, image/jpg, image/tif 
Also added htm to the list so that it would not produce application/htm

Fix MIME-types on attachments as some were incorrect

---

web/src/main/webapp/xslt/skin/default/skin.xsl

This is to address the issue https://github.com/geonetwork/core-geonetwork/issues/7610
Applied the suggest code. Here is the result
By click on the link in the pdf, it gets to the home page

Fix pdf link issue

---

web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js

The directive `gnLinkToMetadata` doesn't have explicitly defined a property in the scope, causing the following JS error when creating / editing a metadata.
```
angular.js?v=07349d682cb6090984b3b9e4bd1d4b194316deb9:15697 TypeError: Cannot read properties of undefined (reading 'length')
at scope.canEnableLinkButton (OnlineSrcDirective.js:1947:37)
```
Tested with iso1939 metadata. The error doesn't cause a malfunction of the dialog to link metadata resources, but should not happen.

Metadata editor / Fix javascript error when editing a metadata

---

web-ui/src/main/resources/catalog/components/search/mdview/mdviewDirective.js

Test case:
1) Load ISO19139 samples
2) Go to the search page and open the metadata page for one of the samples
- Without the fix: a javascript error  is logged in the JS console:
```
lib.js?v=23140d5c3a70e08e503810cb286894258e60b3c6:143 TypeError: Cannot read properties of null (reading 'getUuid')
at Object.link (gn_search_default.js?v=23140d5c3a70e08e503810cb286894258e60b3c6&:730:32)
at lib.js?v=23140d5c3a70e08e503810cb286894258e60b3c6:31:134
at lib.js?v=23140d5c3a70e08e503810cb286894258e60b3c6:104:304
at Ca (lib.js?v=23140d5c3a70e08e503810cb286894258e60b3c6:104:361)
at p (lib.js?v=23140d5c3a70e08e503810cb286894258e60b3c6:88:340)
at lib.js?v=23140d5c3a70e08e503810cb286894258e60b3c6:99:71
at lib.js?v=23140d5c3a70e08e503810cb286894258e60b3c6:155:454
at m.$digest …
```

Fix javascript error accessing the metadata detail page in gnMetadataSocialLink directive

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/schema-ident.xml
schemas/iso19139/src/main/plugin/iso19139/schema-ident.xml
services/src/main/java/org/fao/geonet/api/es/EsHTTPProxy.java

Follow up of #6869
Test case: 
1) Create an ISO19139 metadata and add 3 types of online resources:
- Link
- File to download
- WMS
2) Set the `View` privilege only to the group `ALL`
3) The user should see in the metadata page all 3 links.
4) Logout
- Without the change: the anonymous user see the File to download and WMS resources (not ok). These resources are not present in the XML, what is ok.
- Without the change: the anonymous user doesn't see the File to download and WMS resources (ok). These resources are not present in the XML, what is ok.

Add configuration to filter out Elasticsearch fields when download or dynamic privileges are not set

---

web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html
web-ui/src/main/resources/catalog/components/metadatamanager/EditorService.js
web-ui/src/main/resources/catalog/locales/en-editor.json

Test case:
1) Create an iso19139 dataset metadata
2) Add an online resource with a WMS layer
3) Add an online resource and select the option `Add a thumbnail` in the dialog. Check the Javascript console:
- Without the fix:
```
Error: [orderBy:notarray] http://errors.angularjs.org/1.8.2/orderBy/notarray\?p0\=%7B%22resource%22%3A%7B%22ref%22%3A%22172%22%2C%22refParent%22%3A%22171%22%2C%22name%22%3A%222%22%2C%22url%22%3A%22https%3A%2F%2Fmaps-cartes.ec.gc.ca%2Farcgis%2Fservices%2FDMS%2FStressCumulatifLittorales%2FMapServer%2FWMSServer%3Frequest%3DGetCapabilities%26service%3DWMS%22%2C%22title%22%3A%22Metadata%20WMS%20layer%22%2C%22abstract%22%3A%22The%20ISO19115%20metadata%20standard%20is%20the%20preferred%20metadata%20standard%20to%20use.%20If%20unsure%20what%20templates%20to%20start%20with%2C …
```

Metadata editor / Fix javascript error in the add thumbnail option when the metadata has 1 WMS layer

---

services/src/main/java/org/fao/geonet/api/OpenApiConfig.java

Update Springdoc so that it supports Map objects in the request parameters.
By default injectable parameters are excluded from request parameters. Map is one of those object however it does occur where map objects are supplied as parameters and they should be added to open api spec.  There are currently no cases where a map is injected on purpose into the request parameters. This will fix issues with missing request parameters documentation which are based on Map objects.
Example: Before this PR if you try to test the following api
It is not possible to supply the request body information which is defined as a HashMap here.
https://github.com/geonetwork/core-geonetwork/blob/23140d5c3a70e08e503810cb286894258e60b3c6/services/src/main/java/org/fao/geonet/api/records/MetadataSavedQueryApi.java …

Update Springdoc so that it supports Map objects in the request parameters.

---

services/src/main/java/org/fao/geonet/api/OpenApiController.java

This fixes bug where some apis will not execute correctly from the swagger pager due to the wrong enum value being supplied. i.e.
visibility should be using enum values PUBLIC/PRIVATE instead of public/private
Before this fix.
After this fix 
in formatters/zip api, the format should be SIMPLE/PARTIAL/FULL instead of simple/partial/full
Before
After
i.e. 
Before this fix.

Fix springdoc so that enums names are used instead of toString

---

services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java
services/src/main/java/org/fao/geonet/api/registries/vocabularies/KeywordsApi.java

Fix spring doc for attachment and keyword to better identify files resources being returned.
Update attachment api
"Get a metadata resource" should indicate that gets a file resource
Also "Create a new resource" should identify that it consumes any resources
Update keywords api
"Download a thesaurus by name" should indicate that gets a file resource

Fix spring doc for attachment and keyword to better identify files resources being returned.

---

services/src/main/java/org/fao/geonet/api/OpenApiController.java

[Backport 4.2.x] Fix springdoc so that enums names are used instead of toString

---

docs/manual/docs/customizing-application/adding-static-pages.md
docs/manual/docs/customizing-application/configuring-search-fields.md
docs/manual/docs/customizing-application/editor-ui/creating-custom-editor.md

Addressing two-character literal doc translation glitch (PR #7687)

Addressing docs translation glitch #7687- fixes adding-static-pages and configuring-search-fields

---

docs/manual/docs/administrator-guide/managing-users-and-groups/index.md

This PR adds tables to the documentation to show what each role can do within different parts of GeoNetwork.

Add a role and feature matrix to the GeoNetwork documentation

---

web-ui/src/main/resources/catalog/js/edit/NewMetadataController.js

Made use of the global .less definitions for the various record type icons, instead of the hardcoded `fa-` icons. We make use of `series` in our fork as well, I guess it won't hurt to include it here as well for futureproofing?

Using gn- icon definitions for all types in metadata creation

---

pom.xml
web-ui/pom.xml

Removed unused dependency on jslint-maven-plugin from web-ui.
This dependency is in `web-ui` project since long time ago (2013) and doesn't seem to be used.
It is introducing some components with known vulnerabilities as transitive dependencies in the final GeoNetwork WAR. 
This PR removes the dependency from `web-ui` project.

Remove unused jslint-maven-plugin

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
web-ui/src/main/resources/catalog/views/default/templates/recordView/summary.html

We have modified the vertical extent label to:
- be visually in line with the temporal extent label
- contain the unit
- allow multiple values
This might also be applicable to the core, hence this PR!
Before:
After:

Vertical extent label modification

---

services/src/main/java/org/fao/geonet/api/es/EsHTTPProxy.java

Updated summary and description to differentiate these two end points.
Funded by GeoCat on behalf of GeoCat Live product.

Separate docs for _search and _msearch

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout-custom-fields-date.xsl

* Add support to label override for `cit:date` element:
eg.
```xml
<field xpath="/mdb:MD_Metadata/mdb:identificationInfo/*/mri:citation/*/cit:date"
or="date"
in="/mdb:MD_Metadata/mdb:identificationInfo/*/mri:citation/*"
name="Date de la donnée"/>
```
* Handle setting to hide time in calendar `hideTimeInCalendar`
```xml
<views>
<view name="sextant"
class="gn-label-above-input gn-indent-colored"
upAndDownControlHidden="true"
hideTimeInCalendar="true"
displayIfRecord="contains(
mdb:MD_Metadata/mdb:metadataStandard/
*/cit:title/gco:CharacterString,
'ISO 19115-3 - SEXTANT')">
```

Standard / ISO19115-3 / Editor configuration / Improve date field configuration

---

services/src/main/java/org/fao/geonet/api/registries/vocabularies/KeywordsApi.java
services/src/test/java/org/fao/geonet/api/registries/vocabularies/KeywordsApiTest.java
services/src/test/resources/mobility-theme.owl
web/src/main/webapp/xslt/services/thesaurus/owl-to-skos.xsl

A number of DCAT related vocabularies are published using OWL format describing a concept schema and concepts. eg. https://mobilitydcat-ap.github.io/controlled-vocabularies/network-coverage/latest/index.html
Concepts are described using:
```xml
<owl:NamedIndividual rdf:about="https://w3id.org/mobilitydcat-ap/mobility-theme/accesibility-information-for-vehicles">
<rdf:type rdf:resource="http://www.w3.org/2004/02/skos/core#Concept"/>
<skos:broader rdf:resource="https://w3id.org/mobilitydcat-ap/mobility-theme/data-content-sub-category"/>
<skos:broader rdf:resource="https://w3id.org/mobilitydcat-ap/mobility-theme/public-transport-non-scheduled-transport"/>
<skos:inScheme rdf:resource="https://w3id.org/mobilitydcat-ap/mobility-theme"/>
<skos:prefLabel xml:lang="en">Accesibility information for …
```

Thesaurus / Add support for thesaurus described using OWL format

---

core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataOperations.java

Currently when creating a metadata the user that creates it, by default, gets privileges to edit it  in the group owner, so other editors in the metadata can't edit it(what can be fine). This was changed in https://github.com/geonetwork/core-geonetwork/commit/003fda740bef3839a12403624a9b4781aa1812dd
Other members of the group can view the metadata, but not it's resources. It's unclear the reason, and doesn't make much sense.
This change request, only restricts the edit privilege for other editors in the metadata group, but allow any user in that group to visualise the metadata (no change here) and it's resources.

Create a metadata / Add dynamic and download privileges to the users in the same group

---

web-ui/src/main/resources/catalog/js/admin/ReportController.js

Test case:
1) Create a new user with the roles: `UserAdmin` and `Reviewer` in the `Sample group`
2) Login as the new user
3) In the `Admin console` > `Reports` select a report
- Without the fix: the group is listed 3 times (NO OK).
- With the fix: the group is listed 1 time (OK).

Reports / Fix extract user groups for non-admin users

---

docs/manual/docs/administrator-guide/configuring-the-catalog/csw-configuration.md
docs/manual/docs/administrator-guide/configuring-the-catalog/inspire-configuration.md
docs/manual/docs/administrator-guide/managing-users-and-groups/authentication-mode.md
docs/manual/docs/user-guide/workflow/life-cycle.md

A glitch https://github.com/geonetwork/core-geonetwork/issues/7666 due to documentation conversion was identified by @davidblasby and @archaeogeek.
The following files need to be addressed:

Address two-character literal doc translation glitch

---

docs/manual/docs/administrator-guide/configuring-the-catalog/csw-configuration.md
docs/manual/docs/administrator-guide/configuring-the-catalog/inspire-configuration.md
docs/manual/docs/administrator-guide/managing-users-and-groups/authentication-mode.md
docs/manual/docs/user-guide/workflow/life-cycle.md

[Backport 4.2.x] Address two-character literal doc translation glitch

---

docs/manual/docs/administrator-guide/managing-users-and-groups/authentication-mode.md
docs/manual/docs/administrator-guide/managing-users-and-groups/creating-group.md
docs/manual/docs/customizing-application/search-ui/enrichview.md
docs/manual/docs/customizing-application/search-ui/loadview.md
docs/manual/docs/install-guide/configuring-database.md
docs/manual/docs/install-guide/installing-from-war-file.md
docs/manual/docs/install-guide/map-print-setup.md
docs/manual/docs/overview/change-log/version-4.0.2.md
docs/manual/docs/tutorials/introduction/deployment/index.md
docs/manual/docs/user-guide/publishing/managing-privileges.md

This gathers up pull-requests that got stuck from @archaeogeek, and a few files that were missed, into a PR so it can be cleanly backported.

Address remaining two-character literal doc translation glitch

---

schemas/iso19139/src/main/plugin/iso19139/loc/ger/labels.xml

Update German ISO19139 labels:
- Fix wrong context element for some labels.
- Update translations.

Fix ISO19139 German labels

---

web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html

Fix HTML syntax removing extra quote. Then remove non-needed `form-control` class and add class `checkbox` to the div as indicated by Bootstrap 3.4. Wrap the input with `label` to center it vertically.
Before:
After:

Fix HTML syntax in users.html

---

services/src/main/java/org/fao/geonet/api/records/CatalogApi.java
services/src/main/java/org/fao/geonet/api/records/MetadataApi.java
services/src/main/java/org/fao/geonet/api/records/formatters/FormatterApi.java
services/src/main/java/org/fao/geonet/api/registries/vocabularies/KeywordsApi.java

Backport #7572
* Removed @RequestHeader for "Accept" headers as it is not supported by openAPI specification.
From the following
https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.2.md#fixed-fields-10
If in is "header" and the name field is "Accept", "Content-Type" or "Authorization", the parameter definition SHALL be ignored.
* Update services/src/main/java/org/fao/geonet/api/registries/vocabularies/KeywordsApi.java

[Backport 4.2.x] Removed @RequestHeader for "Accept" headers as it is not supported by openAPI specification

---

services/src/main/java/org/fao/geonet/api/registries/vocabularies/KeywordsApi.java
web/src/main/webapp/xslt/services/thesaurus/sdmx-to-skos.xsl

SDMX is a common format used to statistical data and can be used to describe codelist. eg https://ec.europa.eu/eurostat/databrowser/bulk?lang=en&selectedTab=codeList
Add possibility to import those codelist as SKOS format.
Filename must use extension `.sdmx`.
Similar to https://github.com/geonetwork/core-geonetwork/pull/7674
Funded by EEA

Thesaurus / Add support for codelist described using SDMX

---

web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl

Test:
1) Create an ISO19139 metadata and add a parent relationship to another metadata
2) Go to the static page: http://localhost:8080/geonetwork/srv/api/records/UUID
Without this change a panel is displayed, as relationships are loaded with JS code, and that page doesn't load the JS libraries.
```
Associated resources 
Not available
```
With the change this panel is not displayed.
3) Check in the metadata full view that the relationship it is displayed: http://localhost:8080/geonetwork/srv/ger/catalog.search#/metadata/UUID/formatters/xsl-view?root=div&view=advanced

Record view / Don't add the associated resources in the metadata static page, this page doesn't include JS libs

---

.github/workflows/linux.yml

Backport of #7808.
Bumps [actions/setup-java](https://github.com/actions/setup-java) from 4.0.0 to 4.1.0.
- [Release notes](https://github.com/actions/setup-java/releases)
- [Commits](https://github.com/actions/setup-java/compare/v4.0.0...v4.1.0)
---
updated-dependencies:
- dependency-name: actions/setup-java
dependency-type: direct:production
update-type: version-update:semver-minor
...
Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

[Backport 3.12.x] Bump actions/setup-java from 4.0.0 to 4.1.0

---

core/src/main/java/org/fao/geonet/kernel/AllThesaurus.java
core/src/main/java/org/fao/geonet/kernel/Thesaurus.java
services/src/main/java/org/fao/geonet/api/records/formatters/FormatterApi.java

When loading thesaurus downloadable from the EU publication office, title and namespace of the thesaurus are not extracted properly.
The SKOS format provided contains specificity
eg. https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/data-theme
Thesaurus title is stored in various properties ie. `at:prefLabel`, `rdfs:label`, `skos:prefLabel` but none of them were used so far for title extraction.
```xml
<skos:ConceptScheme rdf:about="http://publications.europa.eu/resource/authority/data-theme"
at:table.id="data-theme"
at:table.version.number="20220715-0">
<at:prefLabel xml:lang="en">Data theme</at:prefLabel>
<rdfs:label xml:lang="en">Data theme</rdfs:label>
<owl:versionInfo>20220715-0</owl:versionInfo>
<skos:prefLabel …
```

Thesaurus / Improve support of EU publication office SKOS format

---

web-ui/src/main/resources/catalog/js/admin/HarvestSettingsController.js

Test case:
1) Select a harvester and move to the 2on page of the executions history.
2) Select another harvester:
- Without the fix: the harvester executions history shows the 2on page (that could not exist), instead of the 1st page.
- With the fix: the harvester executions history shows the 1st page.

Harvesters / Reset harvester history pagination when selecting a harvester

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl

Test case:
1) Create an ISO19139 metadata and with the following content:
```
<gmd:spatialResolution>
<gmd:MD_Resolution>
<gmd:distance>
<gco:Distance uom="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/uom/ML_gmxUom.xml#m">150</gco:Distance>
</gmd:distance>
</gmd:MD_Resolution>
</gmd:spatialResolution>
```
2) From the record view access the full view or to http://localhost:8080/geonetwork/srv/metadata/UUID
Without the change:

Record view / ISO19139 / ISO19115-3.2008 display the unit part in @uom attribute, not the full url

---

common/src/main/java/org/fao/geonet/Logger.java
common/src/main/java/org/fao/geonet/utils/Log.java
core/src/main/java/jeeves/server/context/BasicContext.java
harvesters/src/main/java/org/fao/geonet/kernel/harvest/BaseAligner.java
harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java
harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFilesystemHarvester.java
harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFsHarvesterFileVisitor.java
web-ui/src/main/resources/catalog/components/admin/harvester/partials/privileges.html
web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v3110/UpdateMetadataStatus.java

Follow up of https://github.com/geonetwork/core-geonetwork/pull/2765 and fix harvester logger which was not reporting any error anymore into the harvester logfile that user can download after harvest.
It only reports:
```
2024-01-25T11:06:22,547 WARN  [geonetwork.harvester] - Start of alignment for : SEANOE
2024-01-25T11:08:25,135 INFO  [geonetwork.harvester] - Ended harvesting from node : SEANOE (LocalFilesystemHarvester)
```
If using the harvester logger as before, then the log file properly contains errors
```
2024-01-25T11:06:22,547 WARN  [geonetwork.harvester] - Start of alignment for : SEANOE
2024-01-25T11:06:55,675 ERROR [geonetwork.harvester] - Error transforming JSON into XML from file /data/75639.json, ignoring
2024-01-25T11:07:33,893 ERROR [geonetwork.harvester] - Error …
```

Harvester / Localfilesystem / Log properly to harvester log file.

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/citation/base.xsl
schemas/iso19139/src/main/plugin/iso19139/formatter/citation/base.xsl

Citation last date year was usually correct but if customizing the formatter and a user wants to display the full last date, xpath was not selecting only the last date but all.

Standards / Formatter / Citation / Pick latest date

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/config/associated-panel/default.json
schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml

Follow up of #7468
With the previous pull request, the distributions can be classified in the metadata editor. That works fine in ISO19115-3 where protocols are categorized and the dialog to add a resource for each group only displays the related protocols (user can't specify the protocol, but select a category). 
But ISO19139 is not ready with that changes. When adding an online resource from each section, the resource can end in a different one depending on the protocol selected:
To avoid confusion and simplify, only 1 button to add online resources is provided with this  pull request, instead of 1 per section. Depending on the protocol selected the resource is displayed in the related section:
--- 
We should evaluate to change the protocol management in ISO19139 as done in ISO19115-3 …

Editor / Distribution improvements - Update configuration for ISO19139 distributions as protocols are not categorized as ISO19115-3 protocols.

---

web-ui/src/main/resources/catalog/components/metadataactions/RelatedDirective.js

Follow up of https://github.com/geonetwork/core-geonetwork/pull/7468
Refresh list when user remove the last link of a record. In that case md.link is undefined and we need to reload distributions.

Editor / Distribution / Properly refresh list link on last one

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
web-ui/src/main/resources/catalog/components/search/mdview/mdviewDirective.js

Fixes https://github.com/geonetwork/core-geonetwork/issues/7841
Use the current-group which contains all grouped blocks. Also fix record view which in this case was repeating keywords because the `otherKeywords-` prefix was matching other thesaurus key eg `otherKeywords-place`.

Indexing / ISO / Properly index all keywords even if in different thesaurus block

---

docs/manual/docs/contributing/doing-a-release.md

Documentation / GeoNetwork 4.4 doing a release fixes

---

web/src/main/java/org/fao/geonet/proxy/URITemplateProxyServlet.java

Currently the http proxy doesn't support to send a parameter repeated in the url with different values. This causes Kibana when proxied to fail some requests like the following :
http://localhost:8080/geonetwork/dashboards/api/index_patterns/_fields_for_wildcard?pattern=gn-records&meta_fields=_source&meta_fields=_id&meta_fields=_type&meta_fields=_index&meta_fields=_score
The original code relies in `org.mitre.dsmiley.httpproxy.URITemplateProxyServlet.service` method, that used a list of parameters. This change uses a map with a list of values instead.
It should be check to send a pull to https://github.com/mitre/HTTP-Proxy-Servlet to apply the changes in `org.mitre.dsmiley.httpproxy.URITemplateProxyServlet.service`. But this can take a while until merged and released in HTTP-Proxy-Servlet …

Extend http proxy to support urls with a duplicated parameter with different values

---

web/src/main/java/org/fao/geonet/proxy/URITemplateProxyServlet.java

[Backport 4.2.x] Extend proxy to manage duplicated parameters

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl

In ISO19139 schema Index `gmd:applicationProfile` when the value is encoded as `gmx:Anchor`.

ISO19139 / Index online resources application profile element encoded as anchor

---

web/src/main/java/org/fao/geonet/proxy/URITemplateProxyServlet.java

Follow up of #7456. Fix startup error:
```
javax.servlet.ServletException: targetUri  is required in web.xml or set externally
at org.fao.geonet.proxy.URITemplateProxyServlet.initTarget (URITemplateProxyServlet.java:179)
at org.mitre.dsmiley.httpproxy.ProxyServlet.init (ProxyServlet.java:220)
```

Fix startup error. Follow up #7456

---

web/src/main/java/org/fao/geonet/proxy/URITemplateProxyServlet.java

[Backport 4.2.x] Fix startup error. Follow up #7456

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/update-fixed-info.xsl

This should not happen when records are created using the editor but importing a record with no creation date and then directly applying a batch editing (which does not update dates) will trigger the following error: 
```
"; SystemID: file://web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19115-3.2018/update-fixed-info.xsl; Line#: 134; 
An empty sequence is not allowed as the first argument of gn-fn-iso19115-3.2018:write-date-or-dateTime()
```
Avoiding that case.

Standard / ISO19115-3 / Batch edit may trigger error on creation date

---

.github/workflows/linux.yml
pom.xml

This is required for https://issues.apache.org/jira/browse/MNG-7214 which avoids problems with competing javax annotations (example jsr250-api and javax.annotation-api).
```
Caused by: java.lang.NoSuchMethodError: 'java.lang.String javax.annotation.Resource.lookup()'
```
This is because jsr250-api annotation does not have ``String lookup()`` defined.
I do not expect this will be a problem for most developers - IntelliJ is using maven [3.9.5](https://maven.apache.org/docs/history.html) by default. This pull request is helpful if you find yourself in an environment with an older version of maven - provides fast failure with a useful message on what to do:
```
[ERROR] Rule 0: org.apache.maven.enforcer.rules.version.RequireMavenVersion failed with message:
[ERROR] Detected Maven Version: …
```

require maven 3.8.3 minimum for MNG-7214 fix

---

core/src/main/java/org/fao/geonet/kernel/security/openidconnect/bearer/UserInfoCache.java
core/src/test/java/org/fao/geonet/kernel/security/openidconnect/bearer/UserInfoCacheTest.java

Cached tokens were only cleaned up when they were requested once more. Expired tokens that were not requested again remained in the cache indefinitely. @fxprunayre

OpenID / Cleaning up cached tokens

---

domain/src/main/java/org/fao/geonet/repository/specification/LinkSpecs.java

The query to retrieve the metadata links status information when using filters, specially with users that are User Administrators and have the Editor profile, can take very long time (more than 45 minutes).
Updated the code to simplify the query with a new one, that semantically should be equivalent. The new one is not superfast, but it finishes in seconds.
**Original query**
```
select
distinct count(distinct link0_.id) as col_0_0_
from
Links link0_
inner join MetadataLink records1_ on link0_.id = records1_.linkId
inner join MetadataLink records2_ on link0_.id = records2_.linkId
inner join MetadataLink records3_ on link0_.id = records3_.linkId
where
(
records1_.metadataId in (
select
operationa4_.metadataId
from
OperationAllowed operationa4_
cross join Metadata metadata5_
where …
```

Optimise query used to retrieve metadata links results

---

services/src/main/java/org/fao/geonet/api/records/extent/WMTSBaseMapRenderer.java

Follow up of https://github.com/geonetwork/core-geonetwork/pull/6650
Matrixset id is not always a SRS code eg. https://services.arcgisonline.com/arcgis/rest/services/Ocean/World_Ocean_Base/MapServer/WMTS/1.0.0/WMTSCapabilities.xml
Create image should use the SRS code. 
Test configuration
```xml
<util:map id="regionGetMapBackgroundLayers">
<entry key="osm"
value="\${map.bbox.background.service}"/>
<entry key='arcgis'
value='{
"wmtsGetCapabilitiesURL":"https://services.arcgisonline.com/arcgis/rest/services/Ocean/World_Ocean_Base/MapServer/WMTS/1.0.0/WMTSCapabilities.xml",
"layerName":"Ocean_World_Ocean_Base",
"SRID2MatrixSet": {
"EPSG:3857":"GoogleMapsCompatible"
}
}'
/>
</util:map>
```
Test URL http://localhost:8080/geonetwork/srv/api/regions/geom.png?geomsrs=EPSG:4326&geom=POLYGON((175.015 …

Map / Extent API / Background image failure if matrixset is not SRS code

---

docs/manual/docs/overview/change-log/maintenance/index.md

The maintenance page is presently empty, and 4.2.x release notes are not linked to from anywhere...

Fill in 4.2.x releases for maintenance page

---

services/src/main/java/org/fao/geonet/api/records/extent/WMTSBaseMapRenderer.java

[Backport 4.2.x] Map / Extent API / Background image failure if matrixset is not SRS code

---

services/src/main/java/org/fao/geonet/api/userfeedback/UserFeedbackAPI.java

Just check if the XML metadata contains the email address. It was checking for
indexOf > 0 but this function can return 0 for the first position, although
in a XML test this shouldn't ever happen.

Feedback / Fix email to multiple recipients

---

domain/src/main/java/org/fao/geonet/repository/GeonetRepositoryImpl.java

https://github.com/geonetwork/core-geonetwork/blob/main/harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFsHarvesterFileVisitor.java#L443 has to conclude with a commit, so the proposed fix is to add a transaction around it.
The solution was to make GeonetRepositoryImpl::update transactionnal just like superclass (SimpleJpaRepository) write operations.
To reproduce the bug:
1. add an md
2. export this md as mef/zip
3. declare a local file system harvester asking for metadataoverriding overriding when uuid clash: set harvester settings -> identification -> user to someone else
4. update mef/zip embedded md (just to be sure harvesting took place)
5. make harvester import the mef/zip
6. check that, despite of the initial md has been updated:
- admin …

fix bug where LocalFileSystemHarvester does not update metadata

---

web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties

Backport #7892
**Authored by:** @zhngamy

[Backport 4.2.x] Fix typo in Messages.properties for metadata_approved_published_record_text

---

web/src/main/webapp/WEB-INF/classes/log4j2-dev.xml
web/src/main/webapp/WEB-INF/classes/log4j2-index.xml
web/src/main/webapp/WEB-INF/classes/log4j2.xml

Configure harvesters log to avoid application log duplicated in harvester_default.log file. 

---

core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java

There is little issue in the current workflow status change. The email notification was sent in the middle of transaction before the  event publishing 
https://github.com/geonetwork/core-geonetwork/blob/d7d36bfb4163b5432dfdf6bfb1fa77b86bb18da0/core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java#L185-L191
We have some customized code using the event publishing feature to throw some customized exception.
https://github.com/geonetwork/core-geonetwork/blob/d7d36bfb4163b5432dfdf6bfb1fa77b86bb18da0/core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java#L203
The result is if there is exception been thrown. The user will get error dialog box. But the notification email stating status change will still been sent which confused the user.
Here is how you …

Send email notification after workflow events have been processed

---

core/src/main/java/org/fao/geonet/kernel/datamanager/IMetadataStatus.java
core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataStatus.java
core/src/main/java/org/fao/geonet/kernel/datamanager/draft/DraftMetadataUtils.java
core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java
core/src/main/java/org/fao/geonet/kernel/metadata/StatusActions.java
listeners/src/main/java/org/fao/geonet/listener/metadata/draft/ApprovePublishedRecord.java
listeners/src/main/java/org/fao/geonet/listener/metadata/draft/ApproveRecord.java
services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
services/src/main/java/org/fao/geonet/api/records/editing/MetadataEditingApi.java

The issue happens in this API where the index was update prematurely.
It's supposed to be done here
https://github.com/geonetwork/core-geonetwork/blob/e75ee33f308cb08ad291263c9cff3f71ed4c9457/services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java#L508
But was updated within this code above the thread
https://github.com/geonetwork/core-geonetwork/blob/e75ee33f308cb08ad291263c9cff3f71ed4c9457/services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java#L502
We should add such option to prevent the index updated. 
The issue is if something happens in the publish event into the customized event listener. There are exceptions can be thrown due to the business logic check
https://github.com/geonetwork/core-geonetwork/blob/e75ee33f308cb08ad291263c9cff3f71ed4c9457 …

Fix issue with saving metadata status causes indexing of metadata which causes issues for db rollbacks

---

domain/src/main/java/org/fao/geonet/repository/MetadataValidationRepositoryCustom.java

Test:
* create record, validate
* export as MEF
* modify MEF
* import with overwrite mode fails to update.
If validation status table is empty, overwrite is working
```sql
TRUNCATE TABLE validation;
```
Not sure this is the proper fix for that issue.

API / Import does not overwrite metadata if any validation status

---

web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js

Error "Fielddata access on the _id field is disallowed, you can re-enable it by updating the dynamic cluster setting: indices.id_field_data.enabled" can happen using Elasticsearch 7 and 8
See https://stackoverflow.com/questions/62051460/random-documents-from-elastic-search-7-6-2-deprecation-warning-message
We are using it for the mosaic query.

Search / May fail with random_score depending on ES config

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout.xsl

In feature catalogue, UOM was not displayed as input text
Before
After

Standard / ISO19115-3 / Editor / Uom encoding support

---

core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java

Manfully resolved backporting issue of https://github.com/geonetwork/core-geonetwork/pull/7864
The purpose of the pull request is to make sure indexing updates and email notification get sent at the very end of the transaction where there is no error and exception happening including anything happened in the events listeners.

[Backport 3.12.x] Send email notification after workflow events have been processed #7864

---

web-ui/src/main/resources/catalog/js/search/SearchController.js
web-ui/src/main/resources/catalog/templates/editor/batchedit.html
web-ui/src/main/resources/catalog/templates/editor/editorboard.html
web-ui/src/main/resources/catalog/views/default/templates/searchForm.html

Test case:
1) Load the ISO19139 samples
2) In the search field type `Africa` --> search suggestions are displayed
- Without the change: hit `ENTER` key --> The search is triggered, but the search suggestions are not hidden.
- With the change: hit `ENTER` key --> The search is triggered, the search suggestions are hidden.
Before:
[searchsuggestions-before.webm](https://github.com/geonetwork/core-geonetwork/assets/1695003/3399eac8-3a04-481f-887c-4c7a6006c898)
After:
[searchsuggestions-after.webm](https://github.com/geonetwork/core-geonetwork/assets/1695003/658e92d4-6aa5-4204-8e2e-b4de0ff7202b)

Hide the typeahead search suggestions when hitting the ENTER key in the search field without selecting a suggested value

---

web-ui/src/main/resources/catalog/js/search/SearchController.js
web-ui/src/main/resources/catalog/templates/editor/batchedit.html
web-ui/src/main/resources/catalog/templates/editor/editorboard.html
web-ui/src/main/resources/catalog/views/default/templates/searchForm.html

[Backport 4.2.x] Hide the typeahead search suggestions when hitting the ENTER key in the search field without selecting a suggested value

---

csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/SearchController.java

Follow up of https://github.com/geonetwork/core-geonetwork/pull/7599
`result.hits().hits().size()` returns number of records in response, not total hits matching search. `numberOfRecordsMatched` is wrong.
```
<csw:SearchResults numberOfRecordsMatched="10" numbe
```

CSW / GetRecords / Number of matches is not total match

---

csw-server/src/main/java/org/fao/geonet/component/csw/GetRecordById.java
csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/SearchController.java

CSW server / Use portal filter in GetRecordById requests

---

harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/UriMapper.java

WebDav harvester failed with the following exception if trying to harvest metadata that was already assigned to the local catalogue, due to the `harvestUri` property been `null`:
```
2024-04-11T16:47:11,948 WARN  [geonetwork.harvester] - Raised exception while harvesting from : Test harvester (WebDavHarvester)
2024-04-11T16:47:11,949 WARN  [geonetwork.harvester] -  (C) Class   : NullPointerException
2024-04-11T16:47:11,949 WARN  [geonetwork.harvester] -  (C) Message : null
2024-04-11T16:47:11,949 ERROR [geonetwork.harvester] - null
java.lang.NullPointerException: null
at org.fao.geonet.kernel.harvest.harvester.webdav.Harvester.exists(Harvester.java:205) ~[gn-harvesters-4.2.10-SNAPSHOT.jar:?]
at org.fao.geonet.kernel.harvest.harvester.webdav.Harvester.align(Harvester.java:164) …
```

Fix harvester URIMapper to handle local metadata

---

web/src/main/webapp/xslt/services/csv/csv-search.xsl

Alter search results csv export to escape double-quotes with double-quotes instead of backslashes.
When double quotes are used to enclose fields, applications parsing the csv results expect nested double-quotes to be escaped by another double-quote .
Ex: Importing the CSV into Excel results in data from a single column being spread over multiple columns.
[RFC 4180](https://www.ietf.org/rfc/rfc4180.txt#:~:text=If%20double-quotes%20are%20used%20to%20enclose%20fields%2c%20then%20a%20double-quote%0a%20%20%20%20%20%20%20appearing%20inside%20a%20field%20must%20be%20escaped%20by%20preceding%20it%20with%0a%20%20%20%20%20%20%20another%20double%20quote.): If double-quotes are used to enclose fields, then a double-quote appearing inside a field must be escaped by preceding it with another double …

Search Export CSV - Escape double-quotes with double-quotes instead of backslash

---

web/src/main/webapp/xslt/services/csv/csv-search.xsl

[Backport 4.2.x] Search Export CSV - Escape double-quotes with double-quotes instead of backslash

---

web/src/main/webapp/xslt/services/csv/csv-search.xsl

[Backport 3.12.x] Search Export CSV - Escape double-quotes with double-quotes instead of backslash

---

docker/README.md
docker/docker-geonetwork.txt
docker/gn-cas-ldap/README.md
docker/gn-postgres/README.md
docker/gn-postgres/docker-compose.yml
docker/gn-postgres/kibana/kibana.txt
es/README.md
es/es-dashboards/README.md
es/es-dashboards/pom.xml
es/pom.xml

Thanks for the pointers in the PSC meeting about running Elasticsearch 8.11.3 (as defined in ``pom.xml`` "es.version" file).
This PR gathers several outstanding PRs:
- https://github.com/geonetwork/core-geonetwork/pull/6284
This is for the `docker` folder which contains development environments for testing.
- https://github.com/geonetwork/core-geonetwork/pull/5800
This contained information on license change and troubleshooting information.

Enforce development environment instructions to Elasticsearch  8.11.3

---

web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v444/migrate-default.sql

One of the sql scripts was missing a `;`

Fix sql syntax for migrate to 4.4.4 script

---

pom.xml
services/src/main/java/org/fao/geonet/api/tools/i18n/TranslationApi.java

This replaces PR #7576 
Update springdoc to 1.8.0 which required upgrade of jackson.version to version 2.16.2
Fix springdocs HashMap mapping in /db/translations using new additionalPropertiesSchema from springdoc 1.8.0
If spring doc mapping was viewed in https://editor.swagger.io/.  Then the following error existed.
This fix is to update the mapping so that it fixed this bug.

Update springdoc to 1.8.0 and fix springdocs HashMap mapping in /db/translations

---

web-ui/src/main/resources/catalog/components/elasticsearch/EsFacet.js
web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/editor.html
web-ui/src/main/resources/catalog/js/CatController.js
web-ui/src/main/resources/catalog/locales/ca-core.json
web-ui/src/main/resources/catalog/locales/cs-core.json
web-ui/src/main/resources/catalog/locales/cy-core.json
web-ui/src/main/resources/catalog/locales/da-core.json
web-ui/src/main/resources/catalog/locales/de-core.json
web-ui/src/main/resources/catalog/locales/en-core.json
web-ui/src/main/resources/catalog/locales/es-core.json
web-ui/src/main/resources/catalog/locales/fi-core.json
web-ui/src/main/resources/catalog/locales/fr-core.json
web-ui/src/main/resources/catalog/locales/is-core.json
web-ui/src/main/resources/catalog/locales/it-core.json
web-ui/src/main/resources/catalog/locales/ko-core.json
web-ui/src/main/resources/catalog/locales/nl-core.json
web-ui/src/main/resources/catalog/locales/pt-core.json
web-ui/src/main/resources/catalog/locales/ru-core.json
web-ui/src/main/resources/catalog/locales/sk-core.json
web-ui/src/main/resources/catalog/locales/sv-core.json
web-ui/src/main/resources/catalog/locales/zh-core.json

Some metadata schemas like the https://github.com/metadata101/iso19139.nl.geografie.2.0.0 store in the XML dateStamp element only the date without the time information.
When displaying the metadata in the editor board the information about the update date shows wrong information. creating a metadata at 16:00 PM, shows this wrong information due to the lack of time part:
This change updates the editor board to display the metadata update date from the database. Usually is the same as the XML dateStamp, but as indicated some schemas doesn't store the time part in the XML dateStamp, so makes more sense to use the database field.

Editor board / Use metadata database change date instead of the metadata dateStamp (xml)

---

web-ui/src/main/resources/catalog/components/viewer/wps/WpsDirective.js
web-ui/src/main/resources/catalog/components/viewer/wps/partials/processform.html

Datetime and time parameters were not supported in WPS, all were displayed with a calendar widget that only allowed to select dates without the time part).
This change processes the date fields to display the HTML control depending on the format:

WPS process parameters - support datetime / time formats

---

pom.xml

Backport https://github.com/geonetwork/core-geonetwork/pull/7917

[Backport 4.2.x] Update Jetty to version 9.4.54.v20240208

---

common/src/main/java/org/fao/geonet/utils/Xml.java
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/citation/common.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/citation/view.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl
schemas/iso19139/src/main/plugin/iso19139/formatter/citation/view.xsl
schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
services/src/main/java/org/fao/geonet/api/records/editing/MetadataEditingApi.java
services/src/main/java/org/fao/geonet/api/records/formatters/XsltFormatter.java
services/src/test/resources/org/fao/geonet/api/records/formatters/iso19115-3.2018-citation-html.html
services/src/test/resources/org/fao/geonet/api/records/formatters/iso19139-citation-html.html
web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
web/src/main/webapp/xslt/base-layout.xsl
web/src/main/webapp/xslt/common/render-html.xsl
web/src/main/webapp/xslt/ui-metadata/edit/edit-embedded.xsl
web/src/main/webapp/xslt/ui-metadata/form-builder-xml.xsl
web/src/main/webapp/xslt/ui-metadata/menu-builder.xsl

Formatter API was using an XMLOutputter overriding all configuration made in `xsl:output`. This was producing "invalid" HTML and some workaround were used so far.
Now, return the output produced by saxon XMLIndenter or HTMLIndenter directly.
A good config for HTML output:
```xml
<xsl:output omit-xml-declaration="yes" method="html" doctype-system="html" indent="yes"
encoding="UTF-8"/>
```
It was only affecting the formatter API using the `XML.getString` which was doing the prettyPrint. 
For schema plugin maintainer, this change requires to check plugin formatter which may export HTML, XML or Text output. Adjust the `xsl:output` configuration if needed.
Also do not force editor API to output XML. It outputs HTML and XML view may contains a properly formatted XML snippet.

API / XSL / Use XSL output configuration (formatter, editor).

---

web-ui/src/main/resources/catalog/js/edit/BatchEditController.js
web-ui/src/main/resources/catalog/js/edit/EditorBoardController.js

Follow up of #7910
Without the pull request the sorting option in the editor board and batch editor was using the field from the XML and displaying the translation key instead of the label:

Update the default sort field name in editor board and batch editor.

---

csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/SearchController.java

I encountered an issue whit the CSW's getRecords endpoint when using pagination:
under the following conditions:
- using CSW endpoint `getRecords`
- using pagination by providing `maxRecords` in the request
- results are returned over multiple pages (requested `maxRecords` < total matched records)
when requesting the last page the returned `nextRecord` is always `numberOfRecordsMatched` + 1 instead of being 0. And thus the `nextRecord` value exceeds the value of the `numberOfRecordsMatched`, which may not happen.
depending of the clients implementation when using the `nextRecord`, this can result in a follow up request of getting more records, which then results in the error:
```java.lang.RuntimeException: org.fao.geonet.csw.common.exceptions.InvalidParameterValueEx: …
```

fix for nextrecord in csw getrecords response when using pagination

---

services/src/main/java/org/fao/geonet/api/reports/ReportUsers.java

The users report displays a column with the group/profile assigned, but users with `Administrator` / `Guest` profiles, that are not related to groups, the information was missing. 
With this change this information is added to the report:
Test case:
1) Login as administrator user.
2) Generate the user access report:
- Without the fix: the report shows a row for the administrator user, but no profile is listed.
- Without the fix: the report shows a row for the administrator user, including the profile.

Report users - Display profile for Administrator / Guest profiles that are not related to groups

---

web/src/main/webResources/WEB-INF/web.xml

Related to multinode feature, removed from GeoNework 4.x

Remove unused JeevesDelegatingFilterProxy servlet parameter 'loginService' configuration

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/evaluate.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/fre/labels.xml

When creating custom editor related to feature catalogue, the `cat` namespace may be used. Error is returned when evaluating XPath:
```
Error on line 41 of evaluate.xsl:
XPST0003: Static error in XPath expression supplied to saxon:evaluate: XPath syntax error
at char 37 in {...rc:featureCatalogue/*/cat:n...}:
Prefix cat has not been declared
```
eg.
```xml
<section forEach="/mdb:MD_Metadata/mdb:contentInfo"
name="sextant-datamodel"
del=".">
<field xpath="*/mrc:featureCatalogue/*/cat:name"/>
<section forEach="*/mrc:featureCatalogue/*/gfc:featureType"
name="sextant-table"
del=".">
<field xpath="*/gfc:typeName"/>
<field xpath="*/gfc:carrierOfCharacteristics" name="sextant-columns"/>
<action type="add"
btnLabel="sextant-add-column"
or="carrierOfCharacteristics"
in="*">
<template>
<snippet> …
```

Standard / ISO19115-3 / Feature catalogue improvements

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/ISO19139/utility/create19115-3Namespaces.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/config-editor.xml
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/evaluate.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout-custom-fields.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout.xsl

[Backport 4.2.x] Standard / ISO19115-3 / Ensure dqm namespace is on top of the document

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
web-ui/src/main/resources/catalog/locales/en-core.json
web-ui/src/main/resources/catalog/views/default/templates/recordView/metadata.html
web-ui/src/main/resources/catalog/views/default/templates/recordView/technical.html

For services, service type (version if available) and coupling type are added:
And metadata standard name (and version if available):
Also fix indexing of `srv:serviceTypeVersion`

Record view / Add service type info and metadata standard name

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl
schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
services/src/main/java/org/fao/geonet/api/records/extent/MapRenderer.java
services/src/main/java/org/fao/geonet/api/records/extent/MetadataExtentApi.java
services/src/main/java/org/fao/geonet/api/regions/RegionsApi.java
services/src/test/java/org/fao/geonet/api/records/extent/MetadataExtentApiTest.java
services/src/test/java/org/fao/geonet/api/regions/RegionsApiTest.java
web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-functions.xsl

To make full view more consistent with the default view, add support for geometry collection to the extent API. This allows to have all bounding boxes in the same map in the side panel.
The main page still display each bounding boxes with coordinates details.
eg.
http://localhost:8080/geonetwork/srv/api/regions/geom.png?geomsrs=EPSG:4326&geom=GEOMETRYCOLLECTION(POINT(-32.277667%2037.291833),%20POINT(-44.949833%2023.367667),%20POINT(-31.556167%2037.841167))&width=600&strokeColor=255,255,0,255 http://localhost:8080/geonetwork/srv/api/regions/geom.png?geomsrs=EPSG:4326&geom=GEOMETRYCOLLECTION(POLYGON((10.5253%206.7632,10.5253%2023.2401,-18.3746%2023.2401,-18.3746%206.7632,10.5253%206.7632)),POLYGON((-28.8471%20-34.1253,-28.8471%205.2718,-73.9828%205.2718,-73.9828%20-34.1253,-28.8471%20-34.125 …

API / Extent / Add geometry collection support.

---

web-ui/src/main/resources/catalog/components/viewer/ViewerDirective.js
web-ui/src/main/resources/catalog/components/viewer/wps/WpsDirective.js
web-ui/src/main/resources/catalog/js/CatController.js
web-ui/src/main/resources/catalog/locales/en-v4.json
web-ui/src/main/resources/catalog/views/default/less/gn_map_default.less

Map / Add scale.

---

schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl

In ISO19139 metadata, the full view was not displaying any title element:
After the fix:
---
Additionally, has been improved the specification title label.

ISO19139 metadata full view / display citation titles

---

web/src/main/webResources/WEB-INF/config-db/database_migration.xml

Fix wrong script path for 4.2.10 migration.

Fix migration script configuration for 4.2.10 version

---

schemas/config-editor.xsd
web-ui/src/main/resources/catalog/components/metadataactions/RelatedDirective.js
web-ui/src/main/resources/catalog/components/metadataactions/RelatedResourcesService.js
web-ui/src/main/resources/catalog/components/metadataactions/partials/associatedResourcesPanel.html
web-ui/src/main/resources/catalog/components/metadataactions/partials/distributionResourcesPanel.html
web/src/main/webapp/xslt/ui-metadata/edit/edit.xsl
web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
web/src/main/webapp/xslt/ui-metadata/form-configurator.xsl

Add the possibility to add custom elements in the panel of
`data-gn-distribution-resources-panel` or
`data-gn-associated-resources-panel`.
Common use case is to add explanatory text or add action for shortcuts
eg.
```xml
<directive data-gn-distribution-resources-panel="gnCurrentEdit.metadata"
data-mode="viewConfig.distributionConfig.layout || ''"
data-editor-config="default" ...
>
<section>
<text>
<div class="alert alert-info">
This represents a general availability of a dataset. It implies no information about the actual access method of the data, i.e., whether by direct download, API, or through a Web page.
</div>
</text>
<action type="add"
name=" "
btnLabel="mw-addAtomFeed"
or="onLine"
in="/mdb:MD_Metadata/mdb:distributionInfo/*/mrd:transferOptions/*" …
```

Editor / Add custom element in distribution and associated record directive

---

core/src/test/resources/org/fao/geonet/api/Messages.properties
core/src/test/resources/org/fao/geonet/api/Messages_fre.properties
web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties

Synchronize the Messages.properties files in the web and test directory.
Messages.properties was updated in core/src/test but some changes are missing in web.
Without this fix the arguments in messages do not match the arguments provided.
Ex. user_feedback_text requires 11 arguments in Messages.properties in web but only 10 are provided. Only 10 arguments are required in Messages.properties in core/test.

Synchronize Messages.properties from web and test

---

web-ui/src/main/resources/catalog/components/elasticsearch/EsFacet.js
web-ui/src/main/resources/catalog/views/default/directives/directive.js
web-ui/src/main/resources/catalog/views/default/directives/partials/linksbtn.html

Follow up of https://github.com/geonetwork/core-geonetwork/pull/6321
This was noticed because then when an approved record is found, the edit action in the search result page was opening the editor with a link http://localhost:8080/geonetwork/srv/eng/catalog.edit#/metadata/ApprovedID
Then the editor was opening the editor form with the UUID.
And in such case the editor does not do the redirection (in MetadataEditingApi.java#L153).

Workflow / Edit action / Fix link in search results

---

web-ui/src/main/resources/catalog/components/elasticsearch/EsFacet.js
web-ui/src/main/resources/catalog/views/default/directives/directive.js
web-ui/src/main/resources/catalog/views/default/directives/partials/linksbtn.html

[Backport 4.2.x] Workflow / Edit action / Fix link in search results

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl
schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-functions.xsl

Avoid XSL error when all coordinates are not double. eg. 
```xml
<mri:extent>
<gex:EX_Extent>
<gex:geographicElement>
<gex:EX_GeographicBoundingBox>
<gex:westBoundLongitude>
<gco:Decimal>2</gco:Decimal>
</gex:westBoundLongitude>
<gex:eastBoundLongitude>
<gco:Decimal/>
</gex:eastBoundLongitude>
<gex:southBoundLatitude>
<gco:Decimal/>
</gex:southBoundLatitude>
<gex:northBoundLatitude>
<gco:Decimal/>
</gex:northBoundLatitude>
</gex:EX_GeographicBoundingBox>
</gex:geographicElement>
</gex:EX_Extent>
</mri:extent>
```
Follow up of https://github.com/geonetwork/core-geonetwork/pull/7911
Error:
```
Error on line 54 of render-functions.xsl:
FORG0001: Cannot convert string "" to a double
```

Formatter / ISO / Avoid error on invalid extent

---

web-ui/src/main/resources/catalog/components/search/mdview/partials/contact.html

Since organisation name is an object field use the default property to filter on (the search was made on `OrgForResource`).
The fix may not work when organisation name are multilingual. To be improved.

Record view / Focus on organisation fix

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout-custom-fields.xsl

Same as ISO19139 https://github.com/geonetwork/core-geonetwork/blob/main/schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields.xsl#L233.
Currently, remove the bounding box produce:
```xml
<mri:extent>
<gex:EX_Extent>
<gex:geographicElement/>
</gex:EX_Extent>
</mri:extent>
```
`gex:geographicElement` needs to be removed too.

Standard / ISO19115-3 / Remove geographicElement when removing bounding box

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl

To test, create a record with feature catalogue and add more than one language.
On the long run, we need to add multilingual support here.

Standard / ISO19115-3 / Avoid indexing error on multilingual feature catalogue

---

web/src/main/webResources/WEB-INF/data/config/index/records.json
web/src/main/webapp/xslt/common/index-utils.xsl

More and more links between records (optionnaly remote) are created to identify source datasets, sensors, platforms, study, applications, ... With this information, user may want to configure search aggregations to provide filters by related records.
eg. at Ifremer, dataset may be linked to cruises using their DOI (https://doi.org/10.17600/4040050) and we need a way to easily filter all datasets produced in the context of a cruise. Same for datasets used in publications.
The `recordLink` index field contains the information needed. Nested aggregations (https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-nested-aggregation.html) is working fine, but are not supported client side and can't be use in `query_string` search.
So dedicated `keyword` fields …

Search / Aggregations on related records.

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout-custom-fields.xsl

[Backport 4.2.x] Standard / ISO19115-3 / Remove geographicElement when removing bounding box

---

schemas/iso19115-3.2018/src/main/java/org/fao/geonet/schema/iso19115_3_2018/ISO19115_3_2018SchemaPlugin.java
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/config/associated-panel/default.json
web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcService.js
web-ui/src/main/resources/catalog/components/metadataactions/partials/associatedResourcesContainer.html

In ISO19115-3, linking to parent are most of the time done using associated resources with specific association type (partOfSeamlessDatabase by default, but also series or largerWorkCitation). This can be configured in the plugin but some users have a mix of "old" encoding using parentMetadata element.
```xml
<mdb:parentMetadata uuidref="fa6e13d4-5700-4391-a472-dd29b82ba3db"
xlink:title="REMI Network Observation and Monitoring Locations"/>
```
Now the default encoding is:
```xml
<mri:associatedResource>
<mri:MD_AssociatedResource>
<mri:associationType>
<mri:DS_AssociationTypeCode codeList="http://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#DS_AssociationTypeCode"
codeListValue="partOfSeamlessDatabase"/>
</mri:associationType>
<mri:metadataReference …
```

Standard / ISO19115-3 / Improve linking to parent

---

schemas/config-editor.xsd
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/config-editor.xml
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout-custom-fields.xsl
schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-tpl.xsl
web-ui/src/main/resources/catalog/components/edit/FieldsDirective.js
web-ui/src/main/resources/catalog/components/metadatamanager/EditorService.js
web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
web/src/main/webapp/xslt/ui-metadata/form-builder.xsl

Add possibility to enable ordering control in table mode.
Refactor templates to use the same for all plugins.
Also stop event propagation to avoid to collapse a fieldset when moving such elements.
Fix visibility of icons depending on position.
Funded by Ifremer.

Editor / Table mode / Add ordering control.

---

web-ui/src/main/resources/catalog/js/CatController.js

The map configuration was not using a context and the map extent was centered on coordinate 0 0.
Use the default map context which will center on the context map extent which depends on each catalogue configuration.
Before
After
Configure the default map to properly focus on your area of interest.

Editor / Map / Use main context to have a better default on new extent

---

core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
core/src/main/java/org/fao/geonet/util/XslUtil.java
index/src/main/java/org/fao/geonet/index/es/EsRestClient.java
services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-functions.xsl
web/src/main/webapp/xslt/base-layout.xsl

The function is not much used but can be tested by configuring a multilingual metadata as CSW service.
Then the document title is the title of the metadata record and should match UI language or use default if not found.
It is also use in workflow message.

XSL / Utility / Add multilingual support to getIndexField

---

web-ui/src/main/resources/catalog/views/default/directives/directive.js

In the JS console switching between views in the metadata page:
```
lib.js?v=03a72d6723af7bf6b99d6a6669f76036c997f661:1345 TypeError: Cannot read properties of null (reading 'canReview')
at c.displayPublicationOption (gn_search_default.js?v=03a72d6723af7bf6b99d6a6669f76036c997f661&:1897:435)
at fn (eval at compile (lib.js?v=03a72d6723af7bf6b99d6a6669f76036c997f661:1469:164), <anonymous>:4:402)
```
Updated the related code to check if the metadata information is available when the code is executed.

Record view / Fix JS error related to publication options display.

---

web-ui/src/main/resources/catalog/views/default/less/gn_search_default.less

This menu overlapped the search result which makes them not very readable.
The solution to auto sizing the menu as:

search menu size

---

web-ui/src/main/resources/catalog/js/edit/EditorBoardController.js

Test case:
1) Go to the editor board
2) Edit a metadata and use the back button in the browser.
3) In the editor board, click on a metadata to access the metadata page. 
- Without the change, the following dialog is displayed (no ok):
- With the change, no dialog is displayed (ok)
The editor controller defines this:
https://github.com/geonetwork/core-geonetwork/blob/ca92682a9b758e76346289a100bf35de57d024ca/web-ui/src/main/resources/catalog/js/edit/EditorController.js#L366-L372
When using the back button, the event handler was not cleanup.

Cleanup onbeforeunload event when loading the editorboard controller

---

web-ui/src/main/resources/catalog/js/admin/UserGroupController.js

Test case:
1) Create a new user and save it.
2) In the application menu, select an option.
- Without the fix, the following dialog is displayed (no ok)
- With the fix, no dialog is displayed (ok)

Users / reset form status when creating a user

---

web-ui/src/main/resources/catalog/components/common/map/mapService.js
web-ui/src/main/resources/catalog/components/utility/CORSInterceptor.js
web-ui/src/main/resources/catalog/components/viewer/wmsimport/WmsImportDirective.js

If CORS is not allowed for WMS GetMap HEAD request, the error response doesn't contain the status property. Protect the related check.
Follow up of #7000

WMS GetMap HEAD request error response - check response status defined

---

web-ui/src/main/resources/catalog/components/common/map/mapService.js

Complementary to https://github.com/geonetwork/core-geonetwork/pull/8023
Some servers may not provide CORS header if an HTTP error occurs. eg. https://stackoverflow.com/questions/28584891/cors-header-not-being-served-by-apache-if-theres-a-404 On Apache, it depends on the usage of `always` in
```
Header always set Access-Control-Allow-Origin "*"
```
but it also depends on the list of virtual host in the configuration. A virtual host matching `*` or an IP corresponding to the domain may resolve first and the `Header` directive may not be the same in all virtual host.
Can be tested, with https://sextant.ifremer.fr/services/wms/environnement_marin. When indexing features, large GET request may be generated when adding many filters eg.
``` …
```

Map / Switch from GET to POST request improved in case of missing CORS header on HTTP errors

---

web-ui/src/main/resources/catalog/js/edit/EditorBoardController.js

[Backport 4.2.x] Cleanup onbeforeunload event when loading the editorboard controller

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl
schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl

Follow up of https://github.com/geonetwork/core-geonetwork/pull/7791
Without the change, the value is displayed twice:

Record view / ISO19139 / ISO19115-3.2008 display the unit part in @uom attribute - avoid duplicated value

---

docs/manual/README.md
docs/manual/overrides/partials/main.html

This is a backport some of:
* https://github.com/geonetwork/core-geonetwork/pull/7887
* https://github.com/geonetwork/core-geonetwork/pull/8089
Thanks to GeoCat Live and my employer GeoCat for the chance to bring you this documentation update

[Backport 2.10.x] flatten changelog into current release and release history for ease of maintenance

---

docs/manual/docs/user-guide/associating-resources/doi.md

Small improvement of the DOI documentation page.

Documentation / Add information about the type of users that can request a DOI

---

services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java

```
Java 8 optional type `java.util.Optional` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jdk8" to enable handling
```
Related to https://github.com/geonetwork/core-geonetwork/pull/6956

Editor / Groupowner change error

---

web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionsDirective.js

Editor / Group owner change / Fix label on error

---

core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
core/src/main/java/org/fao/geonet/util/XslUtil.java
index/src/main/java/org/fao/geonet/index/es/EsRestClient.java
services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-functions.xsl
web/src/main/webapp/xslt/base-layout.xsl

[Backport 4.2.x]XSL / Utility / Add multilingual support to getIndexField

---

docs/manual/docs/administrator-guide/managing-metadata-standards/configure-validation.md

These are two different audiences. When deploying admin guide in isolation this produces a broken link.
If configuration of validation levels requires customization then the activity should move to the customization section.
Thanks to GeoCat Live for the opportunity to assist with documentation.

Remove link from admin-guide to schematron details as inappropriate

---

schemas/config-editor.xsd
web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
web/src/main/webapp/xslt/ui-metadata/form-configurator.xsl

The list can be used to display a list of contact with only organisation name for example. This can facilitate building simple form hiding the details of ISO elements. In this case, use a contact directory to add new contact makes sense.
This mode can be also more efficient when record contains lots of contacts which in some case can create large HTML form which can take time to build, download and render in the browser (eg. when having more than 100 contacts in a record). If only `label` are used the form will be faster to render.
For large XML record, form may trigger error like `Form with too many keys [1001 > 1000]` when submitted. The list mode allows to deal with such situation.
eg.
```xml
<action type="add"
forceLabel="true"
addDirective="data-gn-directory-entry-selector" …
```

Editor / Add list mode

---

core/src/test/resources/org/fao/geonet/api/Messages.properties
core/src/test/resources/org/fao/geonet/api/Messages_fre.properties
doi/src/main/java/org/fao/geonet/doi/client/BaseDoiClient.java
doi/src/main/java/org/fao/geonet/doi/client/DoiDataciteClient.java
doi/src/main/java/org/fao/geonet/doi/client/DoiManager.java
doi/src/main/java/org/fao/geonet/doi/client/DoiMedraClient.java
web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties

Follow up of #6472
When trying to publish a DOI the exception reported to the user was `Unsatisfied request parameter` instead of the real cause of the exception. This was caused as not all the places throwing a `DOIClientException` were setting the required multilingual properties, causing the exception manager to use a generic message.
@fxprunayre would you mind to add the French translations?

Update DOI exceptions to be multilingual exceptions

---

core/src/main/java/org/fao/geonet/kernel/security/openidconnect/bearer/GeonetworkJwtAuthenticationProvider.java

The class org.springframework.security.oauth2.server.resource.BearerTokenAuthenticationToken [is deprecated](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/oauth2/server/resource/BearerTokenAuthenticationToken.html) in the current spring security version (5.8.11), this means that [this is always false](https://github.com/geonetwork/core-geonetwork/blob/c50cff70b036390d5c049df6e736c7e3a0b10559/core/src/main/java/org/fao/geonet/kernel/security/openidconnect/bearer/GeonetworkJwtAuthenticationProvider.java#L255), making the bearer token authentication fail.
This PR imports the correct version of BearerTokenAuthenticationToken ([org.springframework.security.oauth2.server.resource.authentication.BearerTokenAuthenticationToken](https://docs.spring.io/spr …

Deprecated BearerTokenAuthenticationToken from spring security

---

web-ui/src/main/resources/catalog/style/gn.less
web-ui/src/main/resources/catalog/views/default/less/gn_login_default.less
web-ui/src/main/resources/catalog/views/default/less/gn_navbar_default.less

Logo in the left corner usually changes its vertical positioning dependent on which page youre on. This fixes it and as well increase logo size without making the headerbar bigger
- [] *Testing* provided for features or enhancements using [automatic tests](https://github.com/geonetwork/core-geonetwork/blob/main/software_development/TESTING.md)

Make logo size bigger and set it to fixed position regardless of web pages

---

web-ui/src/main/resources/catalog/templates/admin/harvest/type/arcsde.js
web-ui/src/main/resources/catalog/templates/admin/harvest/type/geoPREST.js
web-ui/src/main/resources/catalog/templates/admin/harvest/type/geonetwork20.js
web-ui/src/main/resources/catalog/templates/admin/harvest/type/oaipmh.js

This property was used in GeoNetwork 2.x for the GeoNetwork harvester to define how to handle the permissions in the remote groups, see documentation in https://docs.geonetwork-opensource.org/2.10/users/managing_metadata/harvesting/gn/#adding-a-geonetwork-harvester
In GeoNetwork 3.x was replaced by a local groups privileges, but the code was not removed from the GeoNetwork harvester and also the property was added in the UI Javascript code of some other harvesters, but it is not used anywhere.
This change request removes the property from these other harvesters.
The code for the GeoNetwork harvester is still available, but not used as the user interface doesn't allow to configure these groups, @fxprunayre should we remove also the code related to this property from the GeoNetwork …

Harvesters / remove unused groupsCopyPolicy property

---

web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/linktosibling.html

If one config was using the `metadataStore` source, then this source was never hidden when other types are opening the panel.
Follow up of https://github.com/geonetwork/core-geonetwork/pull/7669
eg. in the following config, `linkToParent` allows `metadataStore` source, but opening `linkToPlatform` will also show it even if it is only configured with DOI or remote URL sources.
```xml
<section>
<action type="associatedResource"
name="linkToParent"
btnClass="fa gn-icon-series"
process="siblings">
<directiveAttributes>{"fields": {"associationType": "largerWorkCitation", "initiativeType": "" },
"sources": {"metadataStore": {"params": {"isTemplate": "n"}},
"remoteurl": {"multiple": true}
}}</directiveAttributes>
</action>
<action type="associatedResource"
name="sextant-linkToPlatform" …
```

Editor / Associated resource / Update panel based on type config

---

services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java

The issue is that when restoring metadata 
The transaction does not change the last updated date.
Here the data is restored to the previous status which considered as data change. So the transaction in this restore API need small adjustment.

update last changed date when restore metadata

---

core/src/main/java/org/fao/geonet/kernel/SchemaManager.java

Test case:
1) Access to http://localhost:8080/geonetwork/xml/schemas/dublin-core/schema.xsd
- Without the fix: a 404 error is returned
- With the fix: the xsd file is returned

Fix copy xsd files from metadata schemas to the web application

---

web-ui/src/main/resources/catalog/components/metadataactions/partials/transferownership.html

Without the fix, the `Save` button displayed the text `Save` in all languages, instead of the translation.

Transfer ownership / fix translation key for Save button

---

core/src/test/resources/org/fao/geonet/api/Messages.properties
core/src/test/resources/org/fao/geonet/api/Messages_fre.properties
services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties

Use translations from `Messages.properties` for security exceptions thrown in the metadata workflow API.

Metadata workflow API / Update security exceptions to use translations

---

schemas/config-editor.xsd
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/config-editor.xml
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout-custom-fields-keywords.xsl
schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields-keywords.xsl
web/src/main/webapp/xslt/common/base-variables-metadata-editor.xsl

More and more the default encoding for keywords is using `Anchor` instead of `CharacterString`. It is even mandatory in a number of case like INSPIRE/IACS validation.
Quite often, all editor views are configured using:
```xml
<thesaurusList>
<thesaurus key="external.theme.httpinspireeceuropaeutheme-theme"
transformations="to-iso19115-3.2018-keyword-with-anchor"/>
<thesaurus key="external.theme.httpinspireeceuropaeumetadatacodelistSpatialScope-SpatialScope"
transformations="to-iso19115-3.2018-keyword-with-anchor"/>
...
```
to enable usage of `Anchor` for a number of thesaurus.
This change propose to be able to configure the default keyword encoding for all thesaurus using:
```xml
<thesaurusList defaultTransformation="to-iso19115-3.2018-keyword-with-anchor"/>
</view>
```
If defined, it …

Editor / Keywords / Add option to configure keyword encoding for a view.

---

services/src/main/java/org/fao/geonet/api/records/editing/AjaxEditUtils.java

This type of errors were reported but are wrong on multilingual records:
```
2024-05-16T10:45:08,952 ERROR [geonetwork.editor] - Element not found at ref = 554
2024-05-16T10:45:08,953 ERROR [geonetwork.editor] - Element not found at ref = 556
```
Multilingual elements have reference like `_lang_EN_123` and are managed by `updatedLocalizedTextElement` method and the schema plugin. There is no need to search for them in the preprocess phase.

Editor / Remove wrong ERROR log message on multilingual records

---

services/src/main/java/org/fao/geonet/api/registries/vocabularies/KeywordsApi.java
web-ui/src/main/resources/catalog/components/elasticsearch/directives/FacetDirective.js
web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facet-cards.html
web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facet.html
web-ui/src/main/resources/catalog/components/utility/UtilityService.js
web-ui/src/main/resources/catalog/js/CatController.js

Improve the facet items tooltips.
- For keyword items, display the definition if available.
Before:
After:
- For other items, display the translation instead of the key.
Before:
After:
---
Includes Sonarlint improvements.
Funded by: 
- IFremer

Improve tooltips for facet filter items

---

web-ui/src/main/resources/catalog/components/edit/crsselector/partials/crsselector.html
web-ui/src/main/resources/catalog/components/metadatamanager/EditorService.js
web-ui/src/main/resources/catalog/components/thesaurus/ThesaurusDirective.js
web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
web-ui/src/main/resources/catalog/js/admin/DashboardWfsIndexingController.js
web-ui/src/main/resources/catalog/views/default/module.js

Follow up of #8015
Includes also prettier formatting fixes for other files
---
No need to backport this pull request as the changes are applied to the jQuery 3.7.1 backport PR (https://github.com/geonetwork/core-geonetwork/pull/8105)

Fix html <i> elements defined in javascript with wrong self-closing

---

web-ui/src/main/resources/catalog/views/default/less/gn_result_default.less

Before the fix, when using custom map (something other than open streetmap), going in the Discover Data section
The attribution show/hide button is not working.
And if the button was clicked
After the fix
And if clicked

Fix issue with Map Attribution not being toggled correctly in data preview.

---

web-ui/src/main/resources/catalog/components/metadataactions/partials/recordLinkButton.html

Test case:
1) Import the iso19139 metadata samples
2) In the UI settings, disable the map application
3) Go to the `Hydrological Basins in Africa` record view
Without the fix:
With the fix:

Record view / display WMS resources button label to open the link when the map viewer is not enabled

---

web-ui/src/main/resources/catalog/components/metadataactions/RelatedResourcesService.js
web-ui/src/main/resources/catalog/views/default/module.js

It works fine in debug mode, but not in production mode.
Test case:
1) Create an iso19139 or iso19115-3.2008 metadata and add a WFS layer.
2) With the map application enabled (default) go to the record view page --> The `Add to map` button is displayed and adding the layer to the map viewer, should open it and load the layer.
3) Disable in the UI settings the map application.
4) In the record view:
- Without the fix, the `Add to map` button is displayed, but it should show an `Open link` button instead
- With the fix, the `Open link` button is displayed, clicking on it, opens the WFS capabilities document
---
It seems related to wroj4j renaming due to the function defined inline, to fix it has been refactor in a similar way of the other functions used to add WMS / WMTS / ... map …

Record view / don't display the add to map button for WFS resources when the map viewer is disabled.

---

web-ui/src/main/resources/catalog/components/viewer/layermanager/partials/layermanageritem.html

The display of the style selector was linked to a layer property that is used for:
- the filter panel to work with WFS features
- and the data download
It's unclear why the layer styling was linked to that property as doesn't seem to be related.
---
Test case:
1) Create a metadata with WMS layer that has multiple styles
2) From the metadata page add the layer to the map viewer.
- Without the fix: No style selector is displayed
- With the fix: The style selector is displayed

Map viewer / Add layer with styles from a metadata doesn't show the styles selector

---

services/src/main/java/org/fao/geonet/api/records/extent/MetadataExtentApi.java
services/src/main/java/org/fao/geonet/api/regions/metadata/MetadataRegionSearchRequest.java

Extents API for metadata with a working copy fails with a `NullPoiinterException` at: https://github.com/geonetwork/core-geonetwork/blob/3605e9f6dd28af798979b286101802586a6371a9/services/src/main/java/org/fao/geonet/api/regions/metadata/MetadataRegionSearchRequest.java#L286, as was trying to find the working copy metadata in the `Metadata` table. 
Changes:
- Updated the code to retrieve the date from the search index (as in version 3.12.x). 
- The API accepts now an optional parameter to retrieve the approved or the working copy versions.
Test case:
1) Enable the metadata workflow
2) Create an iso19139 metadata, approve it and edit it to create a working copy
3) Access the extents.png API: http://localhost:8080/geonetwork/srv/api/UUID/extents.png
- Without the fix: an error is returned.
- …

Metadata extents API - fix service for metadata with working copy

---

docs/manual/docs/overview/change-log/version-3.8.0.md
docs/manual/docs/overview/change-log/version-4.0.0-alpha.1.md

* remove use of HTML blocks instead of Markdown's image syntax to be
more consistent and help mike and mkdocs to get relative links right.
resolve #7847

docs: fix image links in change-log(version-3.8.0.md and 4.0.0-alpha.1

---

core/src/main/java/org/fao/geonet/kernel/EditLib.java
services/src/main/java/org/fao/geonet/api/records/editing/AjaxEditUtils.java

Certain fields in the editor do not trigger a full save and refresh upon adding it. Instead, they partially update the metadata and then synchronize the changes with the backend while updating the DOM accordingly. While this partial save feature is intentional, it has led to some bugs.
Over time, when using these specific fields for extended periods, the synchronization starts to fail. As a result, errors appear in the logs indicating "Element not found at ref = {id}". This issue has not caused any problems in ISO19139. However, during the development of the DCAT2 plugin, it resulted in visual errors and the breaking of the editor form.
Upon investigation, I noticed that the geonet element is sometimes not created for newly added/edited elements, while at other times, some other geonet …

Fix presence of duplicated or missing geonet elements after partial metadata updates

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
web-ui/src/main/resources/catalog/components/catalog/CatalogService.js
web-ui/src/main/resources/catalog/components/search/mdview/partials/keywordBadges.html
web-ui/src/main/resources/catalog/views/default/templates/recordView/technical.html
web/src/main/webapp/xslt/common/index-utils.xsl

Fix for issue [#384](https://github.com/metadata101/iso19139.ca.HNAP/issues/384)
In the geonetwork 4 record "default view", the keywords thesaurus titles only show in the main language of the record regardless of the UI language.
Example scenario:
- Add a new iso19139.ca.HNAP record with a main language of English and alternate language of French
- Add some keywords from a thesaurus to the record (Ex. Government of Canada Core Subject Thesaurus)
- Open the record in the default view with the UI language set to French
- Under Technical Information / Informations techniques the thesaurus title appears in English
This PR aims to solve this issue by introducing support for multilingual values for thesaurus titles in the index. These changes maintain functionality for unilingual titles by …

Add support for multilingual thesaurus titles in the index

---

web-ui/src/main/resources/catalog/components/common/popup/partials/popup.html
web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcService.js
web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/linktosibling.html
web-ui/src/main/resources/catalog/components/metadataactions/RelatedDirective.js
web-ui/src/main/resources/catalog/components/metadataactions/partials/associatedResourcesContainer.html
web-ui/src/main/resources/catalog/components/metadataactions/partials/metadataCard.html
web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
web-ui/src/main/resources/catalog/components/utility/partials/associated-record-label.html
web-ui/src/main/resources/catalog/templates/editor/editor.html
web-ui/src/main/resources/catalog/views/default/less/gn_card_default.less
web-ui/src/main/resources/catalog/views/default/templates/recordView/related.html
web-ui/src/main/resources/catalog/views/default/templates/recordView/sources.html
web-ui/src/main/resources/catalog/views/default/templates/recordView/type-dataset.html
web-ui/src/main/resources/catalog/views/default/templates/recordView/type-series.html

Create one directive to display associated resources labels with icon to have same layout/labels in search and editor apps.
The directive is used in all places:
* Record view (list and card layout)
* Editor side panel
* Editor popup
Add the possibility to customize an association label by adding custom translation key in `${lang}-custom.json`
eg.
```json
{
"crossReference-study": "Publication",
"crossReference-campaign": "Campaign",
"crossReference-reuse": "Reuse"
}
```
* Editor / Associated resource popup / Fix element using same DOM id.
* Record view / Improve alignement of source datasets

Association type / Consistent labels

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
web-ui/src/main/resources/catalog/components/catalog/CatalogService.js
web-ui/src/main/resources/catalog/components/search/mdview/partials/keywordBadges.html
web-ui/src/main/resources/catalog/views/default/templates/recordView/technical.html
web/src/main/webapp/xslt/common/index-utils.xsl

Backport #8154
* Add logic to allow multilingual thesaurus titles in the index and translate them when being displayed
* Implement multilingual thesaurus titles in iso19139 and iso19115-3.2018

[Backport 4.2.x] Add support for multilingual thesaurus titles in the index (#8154)

---

services/src/main/java/org/fao/geonet/api/ApiUtils.java

Prior to this fix, it would always return working copy record if it exists.
Regression caused by https://github.com/geonetwork/core-geonetwork/pull/7248
I had assumed that getRecord() was going to get the approved copy but it does not.  It can return working copy if they exists.
This is causing apis like 
and 
to return the status history on the working copy records instead of the approved records.

Fix canViewRecord function so that it returned the workflow record.

---

web-ui/src/main/resources/catalog/components/admin/harvester/partials/extras.html
web-ui/src/main/resources/catalog/components/metadataactions/partials/associatedResourcesContainer.html
web-ui/src/main/resources/catalog/components/metadataactions/partials/distributionResourcesContainer.html
web-ui/src/main/resources/catalog/views/default/directives/partials/mdactionmenu.html
web-ui/src/main/resources/catalog/views/default/templates/recordView/technical.html

I have seen the combination of `data-translate` and the `translate` pipe lead to an infinite stack in angularjs when there's a missing translation. Previously I fixed this in our own fork, but we identified a number of other occurrences that might be fixed as well. 
I tried replicating the issue but I'm having trouble identifying the exact situation. It doesn't happen for all types of translations, it seems, though I do recall that it went wrong with external thesauri labels. To avoid too much time on trying to figure out the specific failing situation: does it make sense to remove these duplicate translations? @fxprunayre

Double translation can lead to infinite stack

---

web-ui/src/main/resources/catalog/components/edit/bounding/partials/boundingpolygon.html

Editor / Bounding  polygon not saved

---

schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl

Can be tested with https://sextant.ifremer.fr/record/1a301465-aee7-42c2-a950-7708f422a6aa/
Is handled properly in ISO19115-3

Standard / ISO19139 / Formatter / Do not display extent if none available

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/tpl-csv.xsl

[Backport 4.2.x] ISO19115-3.2018  / Remove duplicated fields for metadata identifier and uuid in CSV export

---

web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js
web-ui/src/main/resources/catalog/js/edit/EditorBoardController.js

The error when delete metadata is not broadcasted correctly on the editor board page. There are two issues:
1) When select some metadata to delete, if there is some error from the API (i.e. Some customized event listener to process extra business logic or some unhandled exception). The error is not broadcasted at all.
2) This delete button is not adapting error correctly. It should be same as what the editorController https://github.com/geonetwork/core-geonetwork/blob/e3f92aac98e74614b5b487be1881ed019af95cb2/web-ui/src/main/resources/catalog/js/edit/EditorController.js#L674-L677
In order to test the error, you can go to this API https://github.com/geonetwork/core-geonetwork/blob/e3f92aac98e74614b5b487be1881ed019af95cb2/services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteA …

broadcasting error when delete record

---

web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js

If an error happens while using the delete, validate or other option of the editor dashboard metadata actions menu then remove the text "Please wait" and the spinner from the button to allow to perform a new action.
In order to test the error, you can go to this API https://github.com/geonetwork/core-geonetwork/blob/e3f92aac98e74614b5b487be1881ed019af95cb2/services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java#L266
Place some mocked error like:
```java
boolean throwError = true;
if (throwError) {
throw new NotAllowedException()
.withMessageKey("api.metadata.import.errorEventStore", new String[]{""});
}
```

Fix infinite "Please wait" message on error

---

schemas/config-editor.xsd
web/src/main/webapp/xslt/ui-metadata/form-configurator.xsl

Improve documentation and properly target node to delete in case the forEach loop element is not the one to remove.
eg.
```xml
<section name="Axe - Time"
forEach="/mdb:MD_Metadata/mdb:spatialRepresentationInfo/*/msr:axisDimensionProperties/*[msr:dimensionName/*/@codeListValue = 'time']"
del="ancestor::msr:axisDimensionProperties">
<field xpath="msr:dimensionSize"/>
<field xpath="msr:resolution"/>
</section>
```
Before the change, the remove button was not displayed. Most of the time the loop element is the one to delete and this case was fine.
Follow up of https://github.com/geonetwork/core-geonetwork/pull/6907

Editor / Configuration / Improve deletion in forEach section

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/ISO19139/toISO19139.xsl

Fixes "md:scope will be gmd:MD_Scope when it should be gmd:DQ_Scope" 
See https://github.com/geonetwork/core-geonetwork/issues/8220

Standard / ISO19115-3 / Formatters / ISO19139 / Fix scope code

---

services/src/main/java/org/fao/geonet/api/records/MetadataApi.java

This fixes and issue where the export XML fails to get working copy.
This also fixed the same issue with getting the json object as well.

Fix issue with working copy not being returned from getRecordAS api

---

services/src/main/java/org/fao/geonet/api/records/CatalogApi.java
services/src/main/java/org/fao/geonet/guiapi/search/XsltResponseWriter.java
web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js

Fixes #7969
Use the UI language for the metadata information, when exporting a metadata selection to CSV / PDF.
The API for these services accept a new optional parameter `language` that defaults to English as previously.

Use UI language for metadata selection export to CSV / PDF. 

---

web-ui/src/main/resources/catalog/components/common/alert/AlertDirective.js
web-ui/src/main/resources/catalog/components/common/map/mapService.js
web-ui/src/main/resources/catalog/components/search/resultsview/SelectionDirective.js
web-ui/src/main/resources/catalog/components/search/searchmanager/LocationService.js
web-ui/src/main/resources/catalog/components/viewer/ViewerDirective.js
web-ui/src/main/resources/catalog/components/viewer/wmsimport/WmsImportDirective.js
web-ui/src/main/resources/catalog/js/edit/DirectoryController.js
web-ui/src/main/resources/catalog/views/default/module.js

Fixes #8260
Fixes also wrong values for add alert delay, provided in some pages in milliseconds, but the method expects seconds.

Zoom to map popup remains active on non-map pages. 

---

web-ui/src/main/resources/catalog/components/userfeedback/GnUserfeedbackDirective.js
web-ui/src/main/resources/catalog/components/userfeedback/GnmdFeedbackDirective.js
web-ui/src/main/resources/catalog/js/LoginController.js

In the register user, metadata feedback and user feedback forms, sometimes the settings with the recaptcha keys takes a bit longer to load making the recaptcha widget not to load. This commit fixes that updating the values of the recaptcha settings when the settings have finished loading.
It also resets the recaptcha widget if there is any problem returned by the server
after sending the form.

Fix a problem with recaptcha not shown sometimes

---

web-ui/src/main/resources/catalog/components/userfeedback/GnUserfeedbackDirective.js
web-ui/src/main/resources/catalog/components/userfeedback/GnmdFeedbackDirective.js
web-ui/src/main/resources/catalog/js/LoginController.js

Sometimes the settings with the recaptcha keys takes a bit longer to load making the recaptcha widget not to load. This commit fixes that updating the values of the recaptcha settings when the settings have finished loading.
It also resets the recaptcha widget if there is any problem returned by the server after sending the form.
Backport https://github.com/geonetwork/core-geonetwork/pull/8285
Authored by: @juanluisrp

[Backport 3.12.x] Fix a problem with recaptcha not shown sometimes 

---

schemas/iso19139/src/main/plugin/iso19139/extract-relations.xsl
schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
schemas/iso19139/src/main/plugin/iso19139/process/onlinesrc-add.xsl
schemas/iso19139/src/main/plugin/iso19139/process/onlinesrc-remove.xsl

Follow up of https://github.com/geonetwork/core-geonetwork/pull/7431
Address the case when multiple transfer option groups are used. Following discussion in https://github.com/geonetwork/core-geonetwork/pull/7431#discussion_r1694869644
Can be tested with https://gist.github.com/fxprunayre/5641c474514a9d5159ef1479a030a117
Also add support for online sources in distributor blocks.
For ISO19115-3, it is a bit more complicated as online resources can be used in portrayal, feature catalogue, dq report, ... https://github.com/geonetwork/core-geonetwork/blob/main/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/link-utility.xsl#L78-L90
Funded by EEA

Standard / ISO19139 / Fix removal of online source when multiple transfer options block are used.

---

services/src/main/java/org/fao/geonet/api/records/CatalogApi.java

Records with working copies are causing the batch PDF export xslt to fail. The UUIDs are used as an ID resulting in duplicate ID values where there must only be unique values.
CSV export seems to handle this by processing the results after they are received and removing any working copies but there is not similar logic for PDF.
Ex.
- Select at least one record with a working copy from the search page
- Export as PDF
This results in a 400 and the below error:
```
Error at xsl:value-of on line 235 of metadata-fop.xsl:
SXCH0003: org.apache.fop.fo.ValidationException: Property ID
"section-37aecae5-7783-4274-b595-df02aa003ac3" (found on "fo:block") previously used; ID
values must be unique within a document! (See position 234:-1)
```
This PR aims to fix this issue by omitting the working …

Update batch PDF export to skip working copies

---

schemas/iso19139/src/main/plugin/iso19139/loc/fre/labels.xml

On application startup, the translation pack may report an error like the following
```
org.fao.geonet.api.exception.ResourceNotFoundException
at org.fao.geonet.api.standards.StandardsUtils.getCodelistOrLabel(StandardsUtils.java:72)
at org.fao.geonet.api.standards.StandardsUtils.getLabel(StandardsUtils.java:55)
at org.fao.geonet.api.tools.i18n.TranslationPackBuilder.getStandardLabel(TranslationPackBuilder.java:217)
```
due to a missing french translation for element `DQ_EvaluationMethodTypeCode`
Follow up of https://github.com/geonetwork/core-geonetwork/pull/7180

Standard / ISO19139 / i18n / Missing french translation

---

harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java

Non-valid metadata can occur during CSW harvesting. So far, only the number of these has been counted. No information was provided in the log file (only in the debug log level, which is very detailed). In order to be able to draw conclusions about non-valid metadata without having to set the log level to debug, analogous to other harvesters, this was set to INFO.
---
Funded by [LGL BW](https://www.lgl-bw.de/index.html)

harvesting CSW: changed loglevel for invalid metadata to info

---

web-ui/src/main/resources/catalog/components/search/mdview/mdviewModule.js

When the record not found alert message is shown the UUID is always empty. The UUID should be shown in the strong tag following "identifier".
This PR aims to fix this issue by setting `recordIdentifierRequested` to the requested UUID using the `gnSearchLocation.getUuid()` function.
**Error message with this fix:**

Set UUID correctly in "recordNotFound" message

---

web-ui/src/main/resources/catalog/components/search/mdview/mdviewDirective.js

Fixes #8322
Test case:
1. Load ISO19139 metadata samples
2. Go to the metadata page of the `Hydrological Basins in Africa (Sample record, please remove!) sample`
3. Scroll down to the social links and click the mail icon
- Without the fix: it contains `body=undefined` instead of the metadata page permalink
- With the fix: it contains `body=http://....` with the metadata page permalink

Social links in metadata page doesn't have the metadata page permalink.

---

web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js

Clipboard permissions are only implemented in Chromium-based browsers. See https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard for more details.
Chrome also changed their behaviour in recent versions, so that these permissions are no longer needed (see https://chromestatus.com/feature/5167870134976512 ). The W3 Spec also specifies that the permission is in the process of being removed: https://w3c.github.io/clipboard-apis/#dom-clipboard-write
Clipboard read is already supported for a longer time to work without requesting the permission if the clipboard copy originates from a user handler (like a button on click), which is the case for all copy calls.
Instead, check if the browser supports the writeText/readText clipboard functions (some …

Fix Clipboard copy/paste on Firefox

---

core/src/main/java/org/fao/geonet/web/GeoNetworkStrictHttpFirewall.java
web/src/main/webapp/WEB-INF/config-security/config-security-core.xml

Special characters in the cookie causing 400 bad requests from Spring Security

---

core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java

A workflow metadata submission is cancelled with these 2 actions:
- cancel working copy (from editor) --> should be notified the reviewer.
- rejection (from reviewer) --> should be notified the editor.
Currently, by default the editor is notified: https://github.com/geonetwork/core-geonetwork/blob/111a1d7f79fe23b5663e727aeaf126277576fe89/web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql#L527
It can be changed the notification in the database to notify the reviewer, but in both types of cancellation is notified the same type of user, what doesn't seem correct.
This change adapts the notification depending on the user profile that cancels a submission:
- cancel working copy (from editor) --> reviewer is notified
- rejection (from reviewer) --> editor is notified.
Test …

Workflow / update notification level based on user profile when cancelling a submission

---

web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js

[Backport 4.2.x] Fix Clipboard copy/paste on Firefox - use ES5

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/ISO19139/toISO19139.xsl

`MD_BrowseGraphic_Type` contains 2 properties that can be used to store overview file path
* mandatory `fileName` which we are using to store the URL of the overview ("name of the file that contains a graphic that provides an illustration of the dataset")
* and option unbounded `linkage` "link to browse graphic"
Proposal to only convert `mcc:fileName` when producing ISO19139 (which only define `gmd:fileName`)

Standard / ISO19115-3 / Formatters / ISO19139 / Ignore mcc linkage for overview

---

web-ui/src/main/resources/catalog/locales/en-v4.json

Before 
After
More meaningful label indicating that user has to search for something (and not only choose)
Funded by ifremer

Editor / DOI search / Improve label

---

web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/linkToMd.html

When adding a source for example, the button label may be empty. Add a default one.
Before
After

Editor / Associated resource / Avoid empty label

---

listeners/src/main/java/org/fao/geonet/listener/metadata/draft/ApprovePublishedRecord.java
web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js

To fix https://github.com/geonetwork/core-geonetwork/issues/8341
The direct publish should have approved status at the end. The issue is update status was part of another thread not totally sync with the main API. So we need to update the index as well. The UI part is also lack of refreshing mechanism to refresh the current status.

publish status not refreshing fix

---

schemas/iso19139/src/main/plugin/iso19139/process/thumbnail-add.xsl
schemas/iso19139/src/main/plugin/iso19139/process/thumbnail-remove.xsl

In the case where we have the following list of images that were imported.
```
<gmd:graphicOverview>
<gmd:MD_BrowseGraphic>
<gmd:fileName>
<gco:CharacterString>http://localhost:8080/geonetwork/srv/api/records/d14ed343-96a9-4e36-a639-b71def9f6cc0/attachments/test1.png</gco:CharacterString>
</gmd:fileName>
<gmd:fileDescription>
<gco:CharacterString>Image 1</gco:CharacterString>
</gmd:fileDescription>
</gmd:MD_BrowseGraphic>
</gmd:graphicOverview>
<gmd:graphicOverview>
<gmd:MD_BrowseGraphic>
<gmd:fileName>
<gco:CharacterString>http://localhost:8080/geonetwork/srv/api/records/d14ed343-96a9-4e36-a639-b71def9f6cc0/attachments/test2.png</gco:CharacterString>
</gmd:fileName>
<gmd:fileDescription>
<gco:CharacterString>Image 2</gco:CharacterString>
</gmd:fileDescription>
</gmd:MD_BrowseGraphic> …
```

iso19139 - Update thumbnail add/update and remove to support index update/removal

---

harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java

Retrieve metadata method increments metrics under certain conditions and returns null. Methods calling the retrieve metadata method increments additionally the unretrievable metric if null is returned. Sonarlint fixeas are already applied. 
Fixes #8039

CSW Harvester / Avoid increment 2 metrics for a single metadata in certain conditions

---

web-ui/src/main/resources/catalog/views/default/less/gn_result_default.less
web-ui/src/main/resources/catalog/views/default/templates/recordView/thumbnails.html

This commit adds the `<img>` in the `alt` attribute when there is a name, otherwise a default string is used.
The image name used to be the caption underneath the thumbnail, but is now removed
Extra: the `max-height` is increased in order to have the full width of the image.

[a11y] Put the image name in the `alt` attribute of the thumbnail on the metadata page

---

common/src/main/java/org/fao/geonet/utils/XmlRequest.java

When an http request is made that expects an XML document, if this is not the case, the content of the file is added to the exception. If the file is very large or is a binary file, the log is overloaded.
Adding the file content to the exception / log seems useless. The pull request adds a generic message, reporting the problematic URL.
For remote ATOM Feeds, the exception is added to the result report of the collector, producing an invalid response.

Don't add file content to the exception when requesting XML documents, if the content is not XML

---

common/src/main/java/org/fao/geonet/utils/XmlRequest.java

[Backport 4.2.x] Don't add file content to the exception when requesting XML documents, if the content is not XML

---

web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcService.js
web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/doisearchpanel.html

* Add tooltip with API query to inform user which fields are used for the search.
* Ignore https://doi.org prefix as most of the time user search using the DOI URL but the API https://support.datacite.org/docs/api-queries search is only based on prefix/id

Editor / Associated resource / DOI search.

---

core/src/main/java/org/fao/geonet/util/XslUtil.java

Some schema (eg. DCAT) does not contain thesaurus name in the metadata record. While indexing we add the thesaurus title in the index. This utility function allows to retrieve it with the thesaurus key (eg. external.theme.publisher-type).

Xsl utility / Add a function to retrieve thesaurus title with its key

---

web/src/main/webapp/xslt/common/index-utils.xsl

* Use 3 letter code for field ID like in ISO
* Fix position to properly index a set of multilingual elements 
```xml
<dct:title xml:lang="nl">NL</dct:title>
<dct:title xml:lang="en">EN</dct:title>
```
Related to https://github.com/metadata101/dcat-ap.vl/pull/5

Indexing / DCAT multilingual support

---

inspire-atom/src/main/java/org/fao/geonet/services/inspireatom/AtomDescribe.java
inspire-atom/src/main/java/org/fao/geonet/services/inspireatom/AtomGetData.java
inspire-atom/src/main/java/org/fao/geonet/services/inspireatom/AtomHarvester.java
inspire-atom/src/main/java/org/fao/geonet/services/inspireatom/AtomSearch.java
inspire-atom/src/main/java/org/fao/geonet/services/inspireatom/AtomServiceDescription.java
services/src/main/java/org/fao/geonet/api/categories/TagsApi.java
services/src/main/java/org/fao/geonet/api/groups/GroupsApi.java
services/src/main/java/org/fao/geonet/api/harvesting/HarvestersApi.java
services/src/main/java/org/fao/geonet/api/identifiers/IdentifiersApi.java
services/src/main/java/org/fao/geonet/api/languages/LanguagesApi.java
services/src/main/java/org/fao/geonet/api/mapservers/MapServersApi.java
services/src/main/java/org/fao/geonet/api/processing/ProcessApi.java
services/src/main/java/org/fao/geonet/api/records/DoiApi.java
services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
services/src/main/java/org/fao/geonet/api/records/MetadataTagApi.java
services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java
services/src/main/java/org/fao/geonet/api/records/editing/MetadataEditingApi.java
services/src/main/java/org/fao/geonet/api/records/formatters/CacheApi.java
services/src/main/java/org/fao/geonet/api/selections/UserSelectionsApi.java
services/src/main/java/org/fao/geonet/api/site/LogosApi.java
services/src/main/java/org/fao/geonet/api/site/SiteApi.java
services/src/main/java/org/fao/geonet/api/sources/SourcesApi.java
services/src/main/java/org/fao/geonet/api/status/StatusApi.java
services/src/main/java/org/fao/geonet/api/uisetting/UiSettingApi.java
services/src/main/java/org/fao/geonet/api/userfeedback/UserFeedbackAPI.java
services/src/main/java/org/fao/geonet/api/users/MeApi.java
services/src/main/java/org/fao/geonet/api/usersearches/UserSearchesApi.java

After/Before
Clients generated from OpenAPI spec were not handling HTTP status 204 properly (eg. when using openapi-generator). 
See https://springdoc.org/#how-can-i-return-an-empty-content-as-response
Funded by SPW

OpenAPI / Operation returning no content should not advertised a schema.

---

docs/manual/docs/customizing-application/configuring-faceted-search.md
web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facet-temporalrange.html

When using temporal range for aggregations
```
resourceTemporalDateRange: {
gnBuildFilterForRange: {
field: "resourceTemporalDateRange",
buckets: 2024 - 1970,
dateFormat: "YYYY",
dateSelectMode: "years",
vegaDateFormat: "%Y",
from: 1970,
to: 2024,
mark: "area"
},
meta: {
vega: "timeline",
collapsed: true
}
},
```
browser autocomplete may overlap with calendar

Aggregations / Temporal range / Avoid browser autocomplete on calendar

---

add-schema.sh

Maven artifact identifiers were changed to include the `gn-` prefix, the script for adding metadata schemas to the development project was not updated.
This change requires revising the custom schemas at https://github.com/metadata101 to use the old convention if they are not already using it.

Fix the schema artifact name in add schema script

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl

Previously the values were converted to UTC. If the timezone defined in the server is Europe/Madrid and the metadata has a creation date '2023-01-01T00:00:00', the index field creationYearForResource had the value 2022
Test case: 
1) Create an ISO19139 and add a creation date `2023-01-01T00:00:00`.
2) In the UI settings replace the Search application facet `creationYearForResource` with 
```
"creationYearForResource": {
"terms": {
"field": "creationYearForResource",
"order": {
"_key": "desc"
}
},
"meta": {
"collapsed": true
}
},
```
3) Go to the search page:
- Without the fix:
- With the fix:
---
@fxprunayre, instead of extracting the year from the XML content, should we convert the date for these fields, not to UTC, but to the server timezone configured? 
With the current change we are …

ISO19139 / ISO19115.3 / Index resource date fields as defined in the metadata.

---

web-ui/src/main/resources/catalog/components/history/GnHistoryDirective.js
web-ui/src/main/resources/catalog/components/history/partials/recordHistory.html

Previously the metadata page displayed the Tasks and Events selector, even if DOI (Task) was disabled in the settings.
With the change, if DOI is enabled, it works as previously displaying the selector.
Test case:
1) Login as administrator and enable the metadata history and disable the DOI publication in the system settings. 
2) Load ISO19139 templates and create a metadata.
3) Go to the metadata page:
- Without the change: A selector for Tasks and Events is displayed
- With the change: No selector is displayed.
3) Enable the DOI publication in the system settings and go to the metadata page:
- With the change: Check that the selector for Tasks and Events is displayed.

Metadata detail page - hide history types selector when tasks (DOI) and workflow are disabled

---

web-ui/src/main/resources/catalog/components/search/mdview/partials/datapreview.html
web-ui/src/main/resources/catalog/components/viewer/gfi/partials/featurestables.html
web-ui/src/main/resources/catalog/components/viewer/wfsfilter/partials/wfsfilterfacet.html
web-ui/src/main/resources/catalog/style/gn.less
web-ui/src/main/resources/catalog/style/gn_viewer.less

This PR adds visual and UX improvements to the WFS preview:
- added whitespace
- remove border for the selection lists
- re-order buttons
- toolbar positioned on the right of the table
- larger buttons in the metadata page and map
**The new look in the map:**
**The new look in the metadata page:**

Visual and UX changes for WFS previews

---

core/src/main/java/org/fao/geonet/util/LogUtil.java

Test case:
1. Create a harvester.
2. Execute it and check the harvester history tab. The execution has a button to download the log file.
3. Execute it 2 or more times and check the harvester history tab. Most probably is that the latest executions don't have the button to download the log file. Checking the previous log files, you can find out that are stored there.
The problem seems related to https://github.com/geonetwork/core-geonetwork/blob/1a780ac0d09f1a1df0cdbe23e513e8440c994227/core/src/main/java/org/fao/geonet/util/LogUtil.java#L74, as Quartz probably reuses threads and `putIfNull` does not update the value if a thread that had a set value has been reused. The other properties added to the `ThreadContext` are added using `put` instead. It is not clear why the log file name is …

Fix harvester execution logs added to previous logs

---

core/src/main/java/org/fao/geonet/util/LogUtil.java

[Backport 4.2.x] Fix harvester execution logs added to previous logs

---

harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java

The counter for updated metadata is updated in `updateMetadata` method:
https://github.com/geonetwork/core-geonetwork/blob/c932372349a6d918a5da2671630252f3dc66962a/harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java#L802
But with existing metadata managed by another harvester if the uuid collision policy is set to override, it was updated again in https://github.com/geonetwork/core-geonetwork/blob/c932372349a6d918a5da2671630252f3dc66962a/harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java#L219

GeoNetwork harvester - avoid double counting of updated metadata.

---

web-ui/src/main/resources/catalog/components/history/GnHistoryDirective.js
web-ui/src/main/resources/catalog/components/history/partials/recordHistory.html

[Backport 4.2.x] Metadata detail page - hide history types selector when tasks (DOI) and workflow are disabled

---

core/src/main/java/org/fao/geonet/kernel/Thesaurus.java
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/thesaurus-transformation.xsl
schemas/iso19139/src/main/plugin/iso19139/convert/thesaurus-transformation.xsl
web/src/main/webapp/xslt/services/thesaurus/ldregistry-to-skos.xsl
web/src/main/webapp/xslt/services/thesaurus/registry-to-skos.xsl

https://github.com/geonetwork/core-geonetwork/pull/6972/files#diff-c7548d94bdb4268915f50f66df5a90f1f7868e4fb1de2f3d2938397e202aaf2fR1057 added month and year format support. This was resolving thesaurus date to the last matching format ie. 1st January for the default date.
This can be tested using regions thesaurus which will contains 2 dates for the thesaurus block.
https://github.com/geonetwork/core-geonetwork/pull/6972 adds retrieval of `dct:issued|modified|created` dates but multiple dates could be added more than one time with same date type code. Improve the mapping (and add more flexibility to customize date type code).
@wangf1122, @ianwallen  if you could review to check if the grouping of various dates match your requirements?
Misc:
* Cleanup namespace so that they are added to …

Thesaurus / Date improvements.

---

web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facet.html
web-ui/src/main/resources/catalog/components/search/mdview/partials/keywordBadges.html

Test case:
1. Create a metadata with a keyword `World`
2. Create another metadata with a keyword `world`
Before:
It's confusing that 2 filters `World` are displayed, the first one corresponds to the keyword `World` and the second one to the keyword `world`.
After:

Don't capitalize the labels for the facet filter values

---

web-ui/src/main/resources/catalog/components/edit/validationreport/partials/validationreport.html
web-ui/src/main/resources/catalog/locales/en-editor.json
web-ui/src/main/resources/catalog/style/gn_editor.less

- Update buttons to display success and errors to use text instead of an icon.
- Show separate messages for success and errors.
- Add style to display the display buttons greyed when the related rules are not displayed.
- If not success or errors reported don't show the expander to display the results in the validation rules.
- Group the success and error messages.

Metadata editor / validation report improvements

---

web-ui/src/main/resources/catalog/components/edit/fieldduration/partials/fieldduration.html
web-ui/src/main/resources/catalog/components/thesaurus/ThesaurusDirective.js
web-ui/src/main/resources/catalog/components/thesaurus/partials/keywordselector.html

Keyword selector support for required indicator:
For the field duration directive, the required indicator was not displayed properly. After the fix:

Metadata editor / Add required indicator to keyword selector and fix the required indicator for the field duration directive

---

web-ui/src/main/resources/catalog/views/default/less/gn_result_default.less
web-ui/src/main/resources/catalog/views/default/templates/recordView/metadata.html
web-ui/src/main/resources/catalog/views/default/templates/recordView/spatial.html
web-ui/src/main/resources/catalog/views/default/templates/recordView/technical.html

The listing of CRS values was showing a spurious space, originating in the use of inline list items. The solution we implemented makes use of CSS where the whitespace elements are given zero space, while not touching the other element within the list items. This also updates any occurrence of the css class where there's bare text nodes included in the list items.
**before**
**after**

Fixed spurious whitespace for gn-comma-list

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl

Test case:
1) Create an ISO19139 metadata and add the following
```
<gmd:graphicOverview>
<gmd:MD_BrowseGraphic>
<gmd:fileName>
<gco:CharacterString>D:\02Document\image.bmp</gco:CharacterString>
</gmd:fileName>
</gmd:MD_BrowseGraphic>
</gmd:graphicOverview>
```
- Without the fix: An error like this is reported in the log
```
2024-10-09T10:17:32,081 ERROR [geonetwork.index] - Parsing invalid JSON node { "url": "D:\02Document\image.bmp" } for property overview. Error is: Unrecognized character escape '0' (code 48)
at [Source: (String)"{
```
- With the fix: No error reported.

Metadata indexing / ISO19139 / ISO19115-3.2018 / Escape graphic overview file name for JSON

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/extract-date-modified.xsl

While harvesting, `extract-date-modified.xsl` is used to retrieve last update of the record. If empty, harvester will fail with:
```
[geonetwork.harvester] - Invalid ISO date: 
java.lang.IllegalArgumentException: Invalid ISO date: 
at org.fao.geonet.domain.ISODate.parseDate(ISODate.java:426) ~[gn-domain-4.4.5-SNAPSHOT.jar:?]
at org.fao.geonet.domain.ISODate.setDateAndTime(ISODate.java:239) ~[gn-domain-4.4.5-SNAPSHOT.jar:?]
at org.fao.geonet.domain.ISODate.<init>(ISODate.java:117) ~[gn-domain-4.4.5-SNAPSHOT.jar:?]
at org.fao.geonet.kernel.harvest.harvester.simpleurl.Aligner.addMetadata(Aligner.java:237) ~[gn-harvesters-4.4.5-SNAPSHOT.jar:?]
at org.fao.geonet.kernel.harvest.harvester.simpleurl.Aligner.lambda$insertOrUpdate$0(Aligner.java:126) ~[gn-harvesters-4.4.5-SNAPSHOT.jar:?]
``` …

Harvester / ISO19115-3 / Better support missing metadata date info

---

core/src/main/java/org/fao/geonet/api/records/attachments/AbstractStore.java
datastorages/cmis/src/main/java/org/fao/geonet/api/records/attachments/CMISStore.java
datastorages/cmis/src/main/java/org/fao/geonet/resources/CMISConfiguration.java
datastorages/cmis/src/main/resources/config-store/config-cmis-overrides.properties
datastorages/cmis/src/main/resources/config-store/config-cmis.xml
datastorages/jcloud/src/main/java/org/fao/geonet/api/records/attachments/JCloudStore.java
datastorages/jcloud/src/main/java/org/fao/geonet/resources/JCloudConfiguration.java
datastorages/jcloud/src/main/java/org/fao/geonet/resources/JCloudMetadataNameValidator.java
datastorages/jcloud/src/main/resources/config-store/config-jcloud-overrides.properties
datastorages/jcloud/src/main/resources/config-store/config-jcloud.xml
pom.xml

- Add {objectId} property in external management url (base64 unique identifier for the record)
- Change external management type url property {type} so that it is fixed values so that same value can be used in {objectId}
-  Fixed property names used for validation fields to be consistent with other names.
-  Updgade from jcloud 2.3.0 to jcloud 2.5.0
-  Add support for external management named properties similar to cmis
-  Fix bug with deleting all resources as it was failing to identify folders correctly for azure blob.
---
After this update, it will be possible to set parameters similar to the following 
```
JCLOUD_EXTERNAL_RESOURCE_MANAGEMENT_CHANGE_DATE_PROPERTY_NAME=changedate
JCLOUD_EXTERNAL_RESOURCE_MANAGEMENT_VALIDATION_STATUS_PROPERTY_NAME=validationstatus …
```

Add support for external management named properties in JCloud

---

schemas/iso19115-3.2018/src/main/java/org/fao/geonet/schema/iso19115_3_2018/ISO19115_3_2018SchemaPlugin.java

Sources or feature catalogue reference may be described using description or uuidref.
Do not consider text description while searching for associated records. eg.
```xml
<mdb:resourceLineage >
<mrl:LI_Lineage>
<mrl:source>
<mrl:LI_Source>
<mrl:description xsi:type="lan:PT_FreeText_PropertyType">
<gco:CharacterString>Le référentiel utilisé comme trait de côte est celui de Ifremer-Shom au 1/25 000 (date de révision 1995).</gco:CharacterString>
```
This is not really visible but avoid to do search with an empty id in `MetadataUtils#getAssociated`

Standard / ISO19115-3 / Only search for associated record with UUID

---

core/src/main/java/org/fao/geonet/kernel/Thesaurus.java

GeoNetwork local thesaurus may be exposed in third party apps (eg. vocprez, ontoportal). In GeoNetwork, a thesaurus file contains one `conceptScheme` with a set of `concept`. When combining multiple files into an RDF graph the link between concept and scheme may be required.
This changes add the `skos:inScheme` property to each concepts (https://www.w3.org/TR/skos-reference/skos.html#inScheme).
```xml
<rdf:Description rdf:about="https://vocab.ifremer.fr/scheme/SXT/type_jeux_donnee/b64f008f-5e3f-43b6-a3bd-8ae291056305">
<rdf:type rdf:resource="http://www.w3.org/2004/02/skos/core#Concept"/>
<ns2:prefLabel xml:lang="en">/Administrative data</ns2:prefLabel>
<ns2:prefLabel xml:lang="fr">/Données administratives</ns2:prefLabel>
<ns2:inScheme …
```

Thesaurus / Add inScheme property in concept of local thesaurus

---

web-ui/src/main/resources/catalog/views/default/less/gn_result_default.less
web-ui/src/main/resources/catalog/views/default/templates/recordView/technical.html

Avoid empty blocks like
Funded by EEA

Record view / Does not display thesaurus block if no keywords.

---

services/src/test/java/org/fao/geonet/api/registries/vocabularies/KeywordsApiTest.java
web/src/main/webapp/xslt/services/thesaurus/owl-to-skos.xsl

Follow up of https://github.com/geonetwork/core-geonetwork/pull/7674
Mobility DCAT theme vocabulary top concepts is available at https://mobilitydcat-ap.github.io/controlled-vocabularies/mobility-theme/latest/index.html#/
The vocabulary contains 2 top concepts:
```xml
<skos:hasTopConcept rdf:resource="https://w3id.org/mobilitydcat-ap/mobility-theme/data-content-category"/>
<skos:hasTopConcept rdf:resource="https://w3id.org/mobilitydcat-ap/mobility-theme/data-content-sub-category"/>
```
which are not needed for browsing the main categories and sub categories.
Use the narrower terms of the "content category" top concept as the top concepts of the scheme to
* generate proper facet hierarchy in search (after/before).
* and facilitate keyword selection in editor 
Funded by Service Public de …

Thesaurus / OWL format / Mobility theme hierarchy

---

core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java
web-ui/src/main/resources/catalog/locales/en-admin.json

Remove spaces from the list of schema list of metadata import restrictions so that "iso19115-3.2018, dublin-core" will also work.
Also updated the admin documentation so that it is clear that it expects to get a comma separated list.

Update list of metadata import restrictions so that it will work even it there are spaces in the list.

---

core/pom.xml
core/src/main/java/org/fao/geonet/api/records/attachments/AbstractStore.java
core/src/main/java/org/fao/geonet/api/records/attachments/CMISStore.java
core/src/main/java/org/fao/geonet/api/records/attachments/JCloudStore.java
core/src/main/java/org/fao/geonet/resources/CMISConfiguration.java
core/src/main/java/org/fao/geonet/resources/JCloudConfiguration.java
core/src/main/java/org/fao/geonet/resources/JCloudMetadataNameValidator.java
core/src/main/resources/config-store/config-cmis-overrides.properties
core/src/main/resources/config-store/config-cmis.xml
core/src/main/resources/config-store/config-jcloud-overrides.properties
core/src/main/resources/config-store/config-jcloud.xml

Backport #8357
Add {objectId} property in external management url (base64 unique identifier for the record)
Change external management type url property {type} so that it is fixed values so that same value can be used in {objectId}
CMIS
Fixed property names used for validation fields to be consistent with other names.
Jcloud
Updgade from jcloud 2.3.0 to jcloud 2.5.0
Add support for external management named properties similar to cmis
Fix bug with deleting all resources as it was failing to identify folders correctly for azure blob.

[Backport 4.2.x] Add support for external management named properties in JCloud

---

web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js

While adding a remote document URL, the app tries to extract title from the remote document (which can be XML or HTML page).
eg. https://metawal.wallonie.be/geonetwork/srv/api/records/19381245-dc52-438c-b1cd-cdf5d646b69e?language=all 
or https://doi.org/10.1016/j.onehlt.2024.100873
The 2nd link has redirect and return an error if content type does not contains text/html and the link considered invalid can't be attached to the current metadata. This PR add supported content types.

Editor / Associated resource / Remote document / Add content type

---

services/src/main/java/org/fao/geonet/api/mapservers/GeoServerRest.java
services/src/main/java/org/fao/geonet/api/mapservers/MapServersUtils.java
web-ui/src/main/resources/catalog/components/edit/geopublisher/GeoPublisherDirective.js
web-ui/src/main/resources/catalog/templates/admin/settings/mapservers.html

* Admin configuration / Show reset password only once the mapserver is created. Removed unused code
* API / Fix ZIP file publication and coverage removal (probably related to GeoServer API changes - tested with version 2.25.1)
* Editor / Fix zoom to layer due to mapservice change, do not show styler if not configured
[geopublication.webm](https://github.com/geonetwork/core-geonetwork/assets/1701393/ac77bcfd-420e-46df-9a36-180a2377535e)

Editor / Geopublication / Misc fix.

---

services/src/main/java/org/fao/geonet/api/es/EsHTTPProxy.java

Some libraries/apps are using `_msearch` endpoint which can allow both `application/json` or `application/x-ndjson` content type.
When ndjson is used, the API call is not forwarded to Elasticsearch
```
ERROR [geonetwork] - Content type 'application/x-ndjson' not supported
```
Cf. https://www.elastic.co/guide/en/elasticsearch/reference/current/search-multi-search.html
eg.
```
curl -L 'https://apps.titellus.net/geonetwork/mapstore/api/search/records/_msearch?' \
-H 'accept: application/json' \
-H 'content-type: application/x-ndjson' \
--data-raw $'{"preference":"cardQuickFilter_2"}\n{"query":{"bool":{"must":[{"bool":{"must":[{"query_string":{"query":"+(resourceType:application) -(th_infraSIG.default:Reporting_INSPIRE) -(cl_status.key:obsolete)"}}]}}]}},"size":0,"_source":{"includes":["*"],"e …
```

Elasticsearch / API / Allow ndjson for _msearch endpoint

---

schemas/iso19139/src/main/plugin/iso19139/process/thumbnail-remove.xsl

Currently an empty graphic overview cannot be removed as the match condition checks for an empty file name. This PR aims to fix this issue by removing the check for an empty file name allowing empty graphic overviews to be removed.
An example of an empty graphic overview looks like:
```
<gmd:graphicOverview>
<gmd:MD_BrowseGraphic>
<gmd:fileName gco:nilReason="missing">
<gco:CharacterString/>
</gmd:fileName>
</gmd:MD_BrowseGraphic>
</gmd:graphicOverview>
```

Allow removal of empty graphic overviews

---

docs/manual/docs/install-guide/installing-index.md
es/README.md
es/docker-compose.yml
es/es-dashboards/README.md
pom.xml
web/src/main/webResources/WEB-INF/data/config/index/records.json

Fix for https://github.com/geonetwork/core-geonetwork/issues/8305

Elasticsearch / Update to 8.14.3.

---

harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/simpleurl/Harvester.java

Cleanup records to remove, only once all URL are processed. No need for the Element to be preserved, alignement only require the list of UUIDs.
eg. test can be done with the following
```json
{"@id":"335518229","@type":"simpleurl","owner":["1"],"ownerGroup":["4"],"ownerUser":["undefined"],"site":{"name":"pangea","uuid":"44563ecf-4747-4f9b-826c-aafb26e7a5d2","account":{"use":false,"username":[],"password":[]},"url":"https://ws.pangaea.de/oai/provider?verb=GetRecord&identifier=oai:pangaea.de:doi:10.1594/PANGAEA.820342&metadataPrefix=iso19139\nhttps://ws.pangaea.de/oai/provider?verb=GetRecord&identifier=oai:pangaea.de:doi:10.1594/PANGAEA.820377&metadataPrefix=iso19139\nhttps://ws.pangaea.de/oai/provider?verb=GetRecord&identifier=oai:pangaea.de:doi:10.1594/PANGAEA.820377&metadataPrefix=iso1913 …
```

Harvester / Simple URL / Fix multiple URL alignement

---

web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js

The UI settings form has always the `Save` button enabled and clicking it without changes, returns the following error:
```
JSON parse error: Cannot deserialize value of type `java.lang.String` from Object value (token 
`JsonToken.START_OBJECT`); nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: 
Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`) at [Source: 
REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 29] (through reference 
chain: org.fao.geonet.domain.UiSetting["configuration"])
```
This pull request fix the issue.
A better solution would be to disable the button if there are no changes, but the current form is not ready for this and it will require to model the …

Fix saving UI settings without changes

---

core/src/main/java/org/fao/geonet/api/records/attachments/FilesystemStore.java
datastorages/cmis/src/main/java/org/fao/geonet/api/records/attachments/CMISStore.java
datastorages/jcloud/src/main/java/org/fao/geonet/api/records/attachments/JCloudStore.java
datastorages/s3/src/main/java/org/fao/geonet/api/records/attachments/S3Store.java

Add better logging when resources are deleted to make it clear what metadata record the resource was deleted from
Also renamed "MetadataResource" in the message to be "Metadata resource"

Add better logging when resources are deleted to make it clear what metadata record the resource was deleted from

---

core/src/test/resources/org/fao/geonet/api/Messages.properties
core/src/test/resources/org/fao/geonet/api/Messages_fre.properties
services/src/main/java/org/fao/geonet/api/users/validation/UserRegisterDtoValidator.java
web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties

In the register user form, register a new user with the email of an existing user.
Before:
After:

Avoid duplicate validation message when trying to register a user with existing email

---

web-ui/src/main/resources/catalog/views/default/templates/home.html

When there are only two facets displayed on the home page the first facet appears as a button. This can be confusing to the users as it appears like there is some action to be taken on this button but clicking it results in no action.
This PR aims to fix this issue by displaying the facet in place of the "Browse by" label when there is only a single facet to be displayed. The logic checks for two facets however as the last facet is displayed separately.

Update home page "browse by" to display facet as label if there is only one

---

core/src/main/java/org/fao/geonet/kernel/datamanager/draft/DraftMetadataUtils.java

Delete date not being copied causing duplicate
Fixes issue #8452

Delete date not being copied causing duplicate

---

core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java

1. Don't add saludation if the user to notify is the catalogue administrator (defined in settings), as only has the email address.
Test case:
- Update the notification level in the database for DOI request to `catalogueAdministrator`
```
UPDATE StatusValues SET notificationLevel = 'catalogueAdministrator' WHERE name = 'doiCreationTask';
```
- Configure the DOI server in the settings and the mail configuration.
- Create a new metadata and publish it.
- Request the DOI.
- Without the fix: the mail start with a placeholder for the username:
```
{{userName}},
... requested creation of the DOI for the record...
``` 
- With  the fix: 
```
... requested creation of the DOI for the record...
``` 
2. Filter out the users without mail when retrieving the users to notify.

Metadata status changes notification mails improvements

---

pom.xml
services/src/main/java/org/fao/geonet/api/tools/i18n/TranslationApi.java
web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/linkToMd.html

Update springdoc to 1.8.0 which required upgrade of jackson.version to version 2.16.2
Fix springdocs HashMap mapping in /db/translations using new additionalPropertiesSchema
Backport of https://github.com/geonetwork/core-geonetwork/pull/7905

[Backport 4.2.x] Upgrade springdocs to 1.8.0 and jackson to 2.16.2

---

web/src/main/webapp/xslt/ui-metadata/form-builder.xsl

This feature and extra param in the render-element function gives option for the sub schema to either force xsd check for required field or not.

option to force xsd schema check for required field

---

schemas/iso19139/src/main/plugin/iso19139/layout/layout.xsl
web-ui/src/main/resources/catalog/components/edit/multientrycombiner/partials/multientrycombiner.html
web-ui/src/main/resources/catalog/components/edit/multientrycombiner/partials/multientrycombiner_onlineresourcesdescription.html
web-ui/src/main/resources/catalog/components/thesaurus/ThesaurusDirective.js
web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less

Currently keywordPicker fields do not give any indication that the field has suggested values. This is an issue for new users as the field appears as a plain text field. When a keywordPicker field is validated against its suggested values it is unclear to the user how to see all the options.
This PR aims to fix this issue by introducing an optional attribute on the keywordPicker which will add styles to make the field appear like a dropdown list / HTML5 datalist by adding the caret icon.
Seeing the caret icon will prompt the user to click on the field to see the available options.
When combined with the `data-show-hints-on-focus="true"` attribute introduced in #7227 when the field is clicked the whole list of hints is shown regardless of the current input which makes it much more clear to …

Add option to mock a dropdown for keywordPickers

---

core/src/main/java/org/fao/geonet/api/records/attachments/ResourceLoggerStore.java
core/src/main/java/org/fao/geonet/util/XslUtil.java
datastorages/cmis/src/main/java/org/fao/geonet/api/records/attachments/CMISStore.java
datastorages/jcloud/src/main/java/org/fao/geonet/api/records/attachments/JCloudStore.java

This change implement  `getResourceInternal` (created in #5467) for CmisStore and JcloudStore.
It is used by `buildDataUrl`
https://github.com/geonetwork/core-geonetwork/blob/573d4be9c98e98f28246db6aaa9cdd33c3ad16bc/core/src/main/java/org/fao/geonet/util/XslUtil.java#L1236-L1250
and the function is used within individual shema's search engine indexing. for example:
https://github.com/geonetwork/core-geonetwork/blob/573d4be9c98e98f28246db6aaa9cdd33c3ad16bc/schemas/dublin-core/src/main/plugin/dublin-core/index-fields/index.xsl#L248-L251

getResourceInternal implementation for cmis and jcloud

---

web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v446/migrate-default.sql
web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v447/migrate-default.sql

Move the new setting from 4.4.6 to 4.4.7 migration.
Follow up: https://github.com/geonetwork/core-geonetwork/pull/8416

Configuration to display an application banner - fix database migration script

---

pom.xml

This PR resolves https://github.com/geonetwork/core-geonetwork/issues/8183 (in response to [CVE-2024-36404](https://github.com/geotools/geotools/security/advisories/GHSA-w3pj-wh35-fq8w) ). 
This change is to support GeoCat Find catalogue.

GeoTools 32.0 update and JTS 1.20.0 update

---

domain/src/main/java/org/fao/geonet/domain/page/Page.java
domain/src/main/java/org/fao/geonet/repository/page/PageRepository.java
services/src/main/java/org/fao/geonet/api/groups/GroupsApi.java
services/src/main/java/org/fao/geonet/api/pages/PageProperties.java
services/src/main/java/org/fao/geonet/api/pages/PagesAPI.java
web-ui/src/main/resources/catalog/js/admin/StaticPagesController.js
web-ui/src/main/resources/catalog/locales/en-v4.json
web-ui/src/main/resources/catalog/templates/admin/settings/static-pages.html

Backport conflict resolving for https://github.com/geonetwork/core-geonetwork/pull/7707
* Add group/accessExpression field to static page feature
* Filter none group member access to page belong to certain group
* code improvement
* multi selections for groups
* multi selections for groups.
* Refactoring group checking logic
* Update services/src/main/java/org/fao/geonet/api/pages/model/GroupAccessExpression.java
* ui change menu behavior
* Fixing ui issue
* pageGroup joint relation in page entity
* pageGroup joint relation in page entity (add SQL)
* remove page creation script
* Update domain/src/main/java/org/fao/geonet/domain/page/Page.java
* rename group
* prevent group remove if it has association with static pages
* JPA ManyToMany bug fix
---------

[Backport 4.2.x] Enhance static page with group user accessibility

---

web-ui/src/main/resources/catalog/components/viewer/layermanager/partials/layermanageritem.html
web-ui/src/main/resources/catalog/style/gn_viewer.less

The tools in the layer manager in the map are opened on hover. But the icon was misleading, it invited you to click on it. When you hovered the layer the icon disappeared leading to the thought that you couldn't click the icon and therefore couldn't open a menu and missing some extra options (that weren't there).
The tools are still opened on hover, making it clickable asks for some rebuilding, but the icon has changed and the color is dimmed.
Related to issue: https://github.com/geonetwork/core-geonetwork/issues/8116
**The new look:**

Change icon for the layer tools in the layer manager panel on the map page

---

web/src/main/webapp/xslt/ui-metadata/form-builder.xsl

Elements that define a `btnLabel` value and define multiple choices, like:
```xml
<element name="gmd:DQ_Result" id="128">
<label>Ergebnis</label>
<btnLabel>Ergebnis</btnLabel>
...
</element>
```
Are displayed with a wrong font due to FontAwesome styling applied wrongly to `button` elements:
After the fix:

Metadata editor / Fix display of multiple choice elements with custom label

---

web/src/main/webapp/xslt/ui-metadata/form-builder.xsl

[Backport 4.2.x] Metadata editor / Fix display of multiple choice elements with custom label

---

web-ui/src/main/resources/catalog/components/utility/UtilityService.js
web-ui/src/main/resources/catalog/js/LoginController.js
web-ui/src/main/resources/catalog/js/admin/ReportController.js

Display the group names alphabetically in new account and report pages.
Before:
After:

Sort groups alphabetically on the new account and report pages

---

web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js

Regions picker display empty entry form the metadata regions dao:
Metadata regions dao is used to generate the extent images for the metadata, but it's not intended to use it in the regions picker to search for regions. Updated the regions picker directive to don't display the related entry.

Metadata editor / Regions picker display empty entry form the metadata regions dao

---

harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/simpleurl/RDFUtils.java

Harvester config for test:
```json
{"@id":"100","@type":"simpleurl","owner":["1"],"ownerGroup":["2"],"ownerUser":["undefined"],"site":{"name":"dcat","uuid":"38630a58-14fc-4d39-a483-d6ba4562afab","account":{"use":false,"username":[],"password":[]},"url":"https://ontwikkel.dov.vlaanderen.be/geonetwork/srv/api/records/85a4d2f3-fc4c-4798-bf53-1db9e8b81d2c/formatters/xml","icon":"blank.png","loopElement":".","numberOfRecordPath":[],"recordIdPath":".//dcat:record/*/dct:identifier","pageSizeParam":[],"pageFromParam":[],"toISOConversion":[]},"content":{"validate":"NOVALIDATION","importxslt":"none","batchEdits":"[]","translateContent":false,"translateContentLangs":"","translateContentFields":[]},"options":{"every":"0 0 0 ? * *","oneRunOnly":false,"overrideUuid":"SKIP","status":"active"},"privileges …
```

Harvester / Simple URL / Removing jena non-compliant attribute during harvesting

---

web-ui/src/main/resources/catalog/components/edit/directoryentryselector/DirectoryEntrySelector.js
web-ui/src/main/resources/catalog/js/edit/DirectoryController.js

Configuring a the Manage directory sorting options with this format `changeDate#desc`, including the sort order: http://localhost:8080/geonetwork/srv/eng/admin.console#/settings/ui
Causes the manage directory page to fail: http://localhost:8080/geonetwork/srv/eng/catalog.edit#/directory
This pull request fixes the parsing of the sort configuration for the Manage directory page and the entry selector component in the metadata editor.

Directory entries / Fix parsing of sorting configuration

---

core/src/main/java/org/fao/geonet/api/records/attachments/AbstractStore.java
datastorages/cmis/src/main/java/org/fao/geonet/api/records/attachments/CMISStore.java
datastorages/jcloud/src/main/java/org/fao/geonet/api/records/attachments/JCloudStore.java
datastorages/jcloud/src/main/java/org/fao/geonet/resources/JCloudConfiguration.java
datastorages/jcloud/src/main/resources/config-store/config-jcloud-overrides.properties
datastorages/jcloud/src/main/resources/config-store/config-jcloud.xml
datastorages/s3/src/main/java/org/fao/geonet/api/records/attachments/S3Store.java

Jcloud does not really support version numbers and will instead create an ETAG which is not comprehensible by the end users.  We need to use jcloud storage metadata properties to manage the versions being created.
Before
After
Added the following new properties for identifying the version property name to be used as well as the strategy.
- jcloud.external.resource.management.version.property.name
- jcloud.versioning.strategy 
The strategy is to indicate how versioning will be performed based on how the system is configured.
- ALL - each file uploaded will create a new version (Default)
- DRAFT - each file updloaded will create a new version - but once approved, it can only create one version for each approval
- APPROVED - Can only create one version per approval process.
Jcloud does not …

Add better Jcloud versioning supports

---

web/src/main/webapp/WEB-INF/classes/ESAPI.properties

ESAPI logger was using log4j logger (we use log4j2 in GeoNetwork) and locally when trying to reset the user password an exception is launched:
```
ESAPI: DefaultSecurityConfiguration: The code to print all the properties is currently commented out
2024-11-28T13:43:19,906 ERROR [geonetwork] - java.lang.ClassNotFoundException: org.owasp.esapi.logging.log4j.Log4JLogFactory LogFactory class (org.owasp.esapi.logging.log4j.Log4JLogFactory) must be in class path.
org.owasp.esapi.errors.ConfigurationException: java.lang.ClassNotFoundException: org.owasp.esapi.logging.log4j.Log4JLogFactory LogFactory class (org.owasp.esapi.logging.log4j.Log4JLogFactory) must be in class path.
at org.owasp.esapi.util.ObjFactory.make(ObjFactory.java:108) ~[esapi-2.5.4.0.jar:2.5.4.0]
at …
```

Change ESAPI logger to SLF4J using log4j2

---

web/src/main/webapp/WEB-INF/classes/ESAPI.properties

[Backport 4.2.x] Change ESAPI logger to SLF4J using log4j2

---

core/src/main/java/org/fao/geonet/kernel/SelectionManager.java
services/src/main/java/org/fao/geonet/api/es/EsHTTPProxy.java

Fixes #8295
@fxprunayre the fix solves the issue, but there is another selection bucket (`SELECTION_METADATA`) that is used in 22 places:
https://github.com/geonetwork/core-geonetwork/blob/bedfe3da2b9461e5549f6c9935a5f9c73a9a4f97/core/src/main/java/org/fao/geonet/kernel/SelectionManager.java#L55
I have change `EsHTTPProxy` search methods to use `SELECTION_BUCKET` and update the value from `bucket` to `s101`. I haven't change `EsHTTPProxy.msearch` that still uses `SELECTION_METADATA` as I'm not sure if should be changed or not.
I would like to add some comment to `SELECTION_METADATA` describing it's usage.
---
Includes Sonarlint code improvements.

Batch selection is not in sync between search results and record view.

---

datastorages/jcloud/src/main/java/org/fao/geonet/api/records/attachments/JCloudStore.java

Use the copyBlob to copy the resource with updated metadata
Prior it was trying to copy the payload which was buggy on large files and could produce the following error
"`Failed copy of resources: Incomplete output stream connecting to PUT`"
Also increase performance as the copyBlob is more efficient.

Use the copyBlob to copy the resource with updated metadata

---

core/src/main/java/org/fao/geonet/api/records/attachments/JCloudStore.java

[Backport 4.2.x] Use the copyBlob to copy the resource with updated metadata

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/eng/codelists.xml
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/fre/codelists.xml

The codelist value had a typo `facsimilie` instead of the correct value `facsimile`.

ISO19115.3-2008 / Fix typo in facsimile codelist value

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/dcat/dcat-core-access-and-use.xsl
services/src/test/resources/org/fao/geonet/api/records/formatters/iso19115-3.2018-dcat-dataset-core.rdf
services/src/test/resources/org/fao/geonet/api/records/formatters/iso19115-3.2018-dcat-dataset.xml
services/src/test/resources/org/fao/geonet/api/records/formatters/iso19115-3.2018-eu-dcat-ap-dataset-core-multipleAccrualPeriodicityAllowed.rdf
services/src/test/resources/org/fao/geonet/api/records/formatters/iso19115-3.2018-eu-dcat-ap-dataset-core.rdf
services/src/test/resources/org/fao/geonet/api/records/formatters/iso19115-3.2018-eu-dcat-ap-hvd-dataset-core.rdf
services/src/test/resources/org/fao/geonet/api/records/formatters/iso19115-3.2018-eu-dcat-ap-mobility-dataset-core.rdf
services/src/test/resources/org/fao/geonet/api/records/formatters/iso19115-3.2018-eu-geodcat-ap-dataset-core.rdf

In DCAT-AP, the Publication Office vocabulary is used for license and the mapping was expecting ISO to encode original URI (eg. http://creativecommons.org/licenses/by/4.0/) and not PO ones (eg. http://publications.europa.eu/resource/authority/licence/CC_BY_4_0). So ISO record using PO URI was not returning the licence in DCAT-AP (and was in DCAT - because all licence URI are allowed).
The vocabulary is encoded with the following and `skos:exactMatch` was used for the mapping:
```xml
<skos:Concept rdf:about="http://publications.europa.eu/resource/authority/licence/CC_BY_4_0"
at:deprecated="false">
...
<skos:exactMatch rdf:resource="http://creativecommons.org/licenses/by/4.0/"/>
```
Adding also `rdf:about` to allow PO URI to be used in ISO record.
Eg. if
```xml
<mri:resourceConstraints> …
```

Formatters / DCAT-AP / Allow PO URI to be used for constraints.

---

core/src/main/java/org/fao/geonet/kernel/datamanager/IMetadataUtils.java
core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataUtils.java
core/src/main/java/org/fao/geonet/kernel/datamanager/draft/DraftMetadataUtils.java
domain/src/main/java/org/fao/geonet/repository/MetadataDraftRepository.java
domain/src/main/java/org/fao/geonet/repository/MetadataRepository.java
services/src/main/java/org/fao/geonet/api/processing/DatabaseProcessApi.java
services/src/main/java/org/fao/geonet/api/processing/DatabaseProcessUtils.java

Currently the db search and replace API does not support working copies. This means that when we try to create a working copy and apply the search and replace on it, the working copy is ignored and the change is applied directly to the approved version.
This PR aims to fix this by implementing the following logic:
- If the record is a draft
- Update the draft record
- If the record is approved (with no working copy)
- Update the approved record
- If the record is approved (with a working copy)
- Update the working copy

Update db search and replace to support working copies

---

core/src/main/java/org/fao/geonet/api/records/attachments/AbstractStore.java
services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java

Currently the attachments `putResourceFromURL` API uses the last node from the URL (excluding query parameters) to get the filename. This becomes an issue when providing URL's that do not contain the filename in the last node. Instead the content disposition header should have higher priority over the url for retrieving the filename.
For example when providing a URL for a file that is uploaded to a cloud provider like OneDrive the download URL looks like `.../.../download.aspx?...`. This means when putResourceFromUrl is called the extracted filename is always `download.aspx` rather than the actual file download's name. If content disposition is used instead the actual filename can be extracted from the header.
Additionally there are some issues with the "consumes" and "produces" spring …

Attachments API use filename from Content-Disposition before url

---

core/src/main/java/org/fao/geonet/kernel/datamanager/IMetadataUtils.java
core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataUtils.java
core/src/main/java/org/fao/geonet/kernel/datamanager/draft/DraftMetadataUtils.java
domain/src/main/java/org/fao/geonet/repository/MetadataDraftRepository.java
domain/src/main/java/org/fao/geonet/repository/MetadataRepository.java
services/src/main/java/org/fao/geonet/api/processing/DatabaseProcessApi.java
services/src/main/java/org/fao/geonet/api/processing/DatabaseProcessUtils.java

Backport https://github.com/geonetwork/core-geonetwork/pull/8514
Authored by: @tylerjmchugh 
* Update db search and replace API to allow replacements on working copies
* Remove param
* retrigger checks
* retrigger checks
* Update db search and replace preview API to allow replacements on working copies
* Update search and replace logic to use the correct repository
* Remove unused import
* Update selectOneWithSearchAndReplace to fallback to non-draft repository
* Fix calling wrong method

[Backport 4.2.x] Update db search and replace to support working copies (#8514)

---

core/src/main/java/org/fao/geonet/api/records/attachments/AbstractStore.java
services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java

Backport https://github.com/geonetwork/core-geonetwork/pull/8470
Authored by: @tylerjmchugh 
[Backport 4.2.x] Attachments API use filename from Content-Disposition before urll (#8470)
* Update spring doc consumes and produces
* Update putResource logic to get filename from contentDisposition header before using url
* retrigger checks
* retrigger checks
* Remove incorrect consumes
* Update getFilenameFromHeader to return null on exception
* Update getFilenameFromHeader to return null on exception (including fileUrl.openConnection)

[Backport 4.2.x] Attachments API use filename from Content-Disposition before url

---

web/src/main/webapp/xslt/common/base-variables-metadata.xsl

When creating an editor configuration with more than one default view an exception is returned.
```
Error on line 82 of edit.xsl:
XPTY0004: A sequence of more than one item is not allowed as the second argument of concat()
```
Instead, select the first default view defined.
Also add support for conditionally defined default views:
```xml
<view name="default-for-dataset"
default="true"
displayIfRecord="count(//dcat:Catalog/dcat:dataset) > 0">
<tab id="Dataset" default="true">
<section name="Dataset info"/>
</tab>
</view>
<view name="default-for-service"
default="true"
displayIfRecord="count(//dcat:Catalog/dcat:service) > 0">
<tab id="Service" default="true">
<section name="Service info"/>
</tab>
</view>
```

Editor / Add support for conditional default view

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/encode-keyword-as-anchor.xsl

Co-authored with @fxprunayre 
Utility process `encode-keyword-as-anchor` to replace keywords encoded as CharacterString with Anchor (when a thesaurus is available).
Funded by SPW

Standard / ISO19115-3 / Process / encode all keywords using anchor

---

core/src/main/java/org/fao/geonet/kernel/EditLib.java
schemas/iso19115-3.2018/src/main/java/org/fao/geonet/schema/iso19115_3_2018/ISO19115_3_2018SchemaPlugin.java
schemas/iso19139/src/main/java/org/fao/geonet/schema/iso19139/ISO19139SchemaPlugin.java
schemas/schema-core/src/main/java/org/fao/geonet/kernel/schema/MultilingualSchemaPlugin.java
services/src/main/java/org/fao/geonet/api/records/editing/AjaxEditUtils.java
services/src/main/java/org/fao/geonet/api/records/editing/MetadataEditingApi.java

Dublin core or DCAT use `xml:lang` attribute added to sibling elements for translations (compared to ISO which always have a container element with translations in it).
This change add support for:
* adding such element in embedded mode (ie. not while saving the full document but only requesting expansion of a particular element) 
* and ordering  multilingual elements.
Funded by https://metadata.vlaanderen.be/

Editor / Improve support of schema having sibling elements for translation

---

core/src/main/java/org/fao/geonet/kernel/search/KeywordsSearcher.java
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout-custom-fields-keywords.xsl
services/src/main/java/org/fao/geonet/api/registries/vocabularies/KeywordsApi.java
services/src/main/java/org/fao/geonet/services/thesaurus/GetKeywordByIdAsConcept.java
services/src/main/java/org/fao/geonet/services/thesaurus/GetTopConcept.java
web-ui/src/main/resources/catalog/components/ng-skos/templates/skos-concept.html
web-ui/src/main/resources/catalog/components/thesaurus/ThesaurusService.js
web/src/main/webapp/xslt/services/thesaurus/to-jskos.xsl

Add english as default language for thesaurus searches in order to populate metadata with english label if the thesaurus is not available in the current record language. For example, this can happen when using DCAT-AP related vocabularies only avilable in english that have to be used in Member States records not in english.
Display english label if UI and record language is not available in thesaurus
After/Before
Use the english label when encoding the keyword in the metadata (API changes):
http://localhost:8080/geonetwork/srv/api/registries/vocabularies/keyword?thesaurus=external.theme.gemet&id=http:%2F%2Fwww.eionet.europa.eu%2Fgemet%2Fconcept%2F3599,http:%2F%2Fwww.eionet.europa.eu%2Fgemet%2Fconcept%2F15034,http:%2F%2Fwww.eionet.europa.eu%2Fgemet%2Fconcept%2F105,http:%2F%2Fwww.eionet.euro …

Editor / Add keywords even if thesaurus not available in record languages

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/dcat/dcat-core-access-and-use.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/dcat/dcat-core-catalog.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/dcat/dcat-core-dataservice.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/dcat/dcat-core.xsl
services/src/test/resources/org/fao/geonet/api/records/formatters/iso19115-3.2018-dcat-service-core.rdf
services/src/test/resources/org/fao/geonet/api/records/formatters/iso19115-3.2018-dcat-service.xml

* Fix service mapping for DCAT due to the change in namespace for SRV (https://github.com/geonetwork/core-geonetwork/pull/7806) which happened in between PRs.
* Add more flexible parameters to make distinction between endpoint URLs and endpoint description
* Fix `uuidref` attribute typo.
Funded by Service Public de Wallonie

Formatter / DCAT / Service

---

services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java

This change sets the content-length of the file to download and closes the related input stream.

Attachments API / Set content-length and close input stream when retrieving a metadata resource

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/schematron/schematron-rules-dcat-ap-hvd.sch
schemas/iso19139/src/main/plugin/iso19139/schematron/schematron-rules-dcat-ap-hvd.sch

ISO metadata can be retrieved in DCAT and specific rules apply to High Value Dataset context. See https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/
This schematron test ISO19139 or ISO19115-3 records and check mandatory elements for datasets and services to facilitate encoding of HVD requirements in ISO records.
The mapping rule defined in the ISO to DCAT mapping are used. Some rules may require adjustments eg.
* no common practice to encode service documentation which is a mandatory element for HVD
* `conformsTo` reference INSPIRE data specification but how none INSPIRE dataset reference specification?
Relates to https://github.com/geonetwork/core-geonetwork/pull/8547
DCAT-AP-HVD output is available at http://localhost:8080/geonetwork/srv/api/records/2414e736-72e2-4b5a-967d-da410ef452 …

Standard / ISO / Schematron for DCAT HVD requirements

---

services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java

[Backport 4.2.x] Attachments API / Set content-length and close input stream when retrieving a metadata resource

---

docs/manual/docs/api/rdf-dcat.md

Preview on intellij or github is not the same as mkdoc pages.
List requires blank line above.

Doc / DCAT page / Fix formatting

---

web/src/main/webapp/xslt/common/utility-tpl.xsl

Fixes https://github.com/geonetwork/core-geonetwork/issues/8226

Formatters / Properly detect URL ending in 1,2,3 or 5

---

services/src/main/java/org/fao/geonet/api/records/extent/ExpandFactor.java
services/src/main/java/org/fao/geonet/api/records/extent/MapRenderer.java
services/src/main/java/org/fao/geonet/api/regions/RegionsApi.java

When scale factor is big, image generated always follows geom proportions. It may not be relevant as the geom is small on the image and a square image may be preferred.
Add an option to render square image depending on the scale factor.
Sample configuration (with large scale factor for small geometry - this catalogue contains quite some point extent in the middle of the sea):
```xml
<util:set id="regionGetMapExpandFactors" set-class="java.util.TreeSet">
<bean class="org.fao.geonet.api.records.extent.ExpandFactor"
p:proportion=".00005" p:factor="256" p:squareImage="true"/>
```
Added more detailed API doc:

API / Extents / Scale factor / Add option to generate square image

---

docs/manual/docs/customizing-application/configuring-faceted-search.md
web-ui/src/main/resources/catalog/components/elasticsearch/directives/FacetDirective.js
web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facets.html
web-ui/src/main/resources/catalog/components/metadataactions/RelatedDirective.js
web-ui/src/main/resources/catalog/components/metadataactions/partials/recordsFilters.html
web-ui/src/main/resources/catalog/components/search/searchfiltertag/SearchFilterTagsDirective.js
web-ui/src/main/resources/catalog/components/search/searchfiltertag/partials/searchFilterTagsTemplate.html
web-ui/src/main/resources/catalog/js/CatController.js
web-ui/src/main/resources/catalog/views/default/templates/home.html

To facilitate facet configuration when using the application using webcomponent mode. All users may not have access to the admin UI to add or customize labels using database translations.
Add also documentation on how to configure labels when the key used for the facet is not known.
eg. 
```js
facetConfig: {
resourceType: {
terms: {
field: "resourceType"
},
meta: {
labels: {
eng: "Hierarchy level"
},
```

Facet / Add meta property to customize label.

---

web/src/main/java/org/fao/geonet/proxy/URITemplateProxyServlet.java
web/src/main/webResources/WEB-INF/web.xml

When doing the GN5 -> GN4 proxy, I added authentication headers.  See https://github.com/geonetwork/geonetwork/pull/77
However, under some configurations, this could leak authentication tokens via the GN4 proxy. 
I've added the ability to disallow some headers to be attached to the GN4 proxy requests.  I've set it up so it, by default, will block the "standard" GN5->GN4 authentication header ("`gn5.to.gn4.trusted.json.auth`").
However, there are (potentially) other headers that should be removed.  For example, OAUTH Bearer tokens (and other security system's tokens or identification information).

remove outgoing headers for the proxy

---

services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java

After batch editing several records, the history is the status in the database is stored as JSON and XML embedded.
When trying to view the previous and current version from UI:
The API specify the format as  XML
https://github.com/geonetwork/core-geonetwork/blob/da294f7466fb9832edf9f1493d58de8bbd8f9e72/services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java#L814
https://github.com/geonetwork/core-geonetwork/blob/da294f7466fb9832edf9f1493d58de8bbd8f9e72/services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java#L844
So the browser cannot render the text:
The JSON format is not very compactible to the API. I am adding a JSON conversion to XML to render the API properly.

Return xml inside JSON status

---

web/src/main/webapp/WEB-INF/config-security/config-security-gn5-overrides.properties
web/src/main/webapp/WEB-INF/config-security/config-security-gn5.xml
web/src/main/webapp/WEB-INF/config-security/config-security-jwt-headers-base.xml
web/src/main/webapp/WEB-INF/config-security/config-security.xml

Security configuration for GeoNetwork 4 deployed behing GeoNetwork 5 prototype using simple mode (ie. GN4 MUST not be exposed to intranet and internet).
Authentication is managed by version 5 which check user credentials and create user in the database if needed. Then a JWT token is added to a header that version 4 checks.
Related to:
* JWT headers support https://github.com/geonetwork/core-geonetwork/pull/7899
* GeoNetwork 5 auth https://github.com/geonetwork/geonetwork/pull/77
To enable the configuration, use:
```sh
mvn jetty:run -Dgeonetwork.security.type=gn5
```

GN5 / Security configuration

---

core/src/main/java/org/fao/geonet/util/XslUtil.java

Url decode the resourceId supplied to store.getResourceInternal to fix filenames containing spaces.
Without this fix, filename containing spaces may not be indexed in the data url as the file will not be found due to %20 in the filename.

Url decode the resourceId supplied to store.getResourceInternal to fix filenames containing spaces.

---

services/src/main/java/org/fao/geonet/api/site/SiteApi.java
services/src/test/java/org/fao/geonet/api/site/SiteApiTest.java

Prior to this fix, the swagger ui for applying site settings was not working.
Before the swagger ui would look like the following 
And generate the following error 
After, it will look like the following (with some examples.)
And when valid values are supplied, it will generate the following results

Fix set site settings in swagger_ui so it function correctly.

---

domain/src/main/java/org/fao/geonet/domain/StatusValue.java
listeners/src/main/java/org/fao/geonet/listener/history/AttachmentAddedListener.java
listeners/src/main/java/org/fao/geonet/listener/history/AttachmentDeletedListener.java
listeners/src/main/java/org/fao/geonet/listener/history/RecordCategoryChangeListener.java
listeners/src/main/java/org/fao/geonet/listener/history/RecordCreatedListener.java
listeners/src/main/java/org/fao/geonet/listener/history/RecordDeletedListener.java
listeners/src/main/java/org/fao/geonet/listener/history/RecordGroupOwnerChangeListener.java
listeners/src/main/java/org/fao/geonet/listener/history/RecordImportedListener.java
listeners/src/main/java/org/fao/geonet/listener/history/RecordOwnerChangeListener.java
listeners/src/main/java/org/fao/geonet/listener/history/RecordPrivilegesChangeListener.java
listeners/src/main/java/org/fao/geonet/listener/history/RecordProcessingChangeListener.java
listeners/src/main/java/org/fao/geonet/listener/history/RecordRestoredListener.java
listeners/src/main/java/org/fao/geonet/listener/history/RecordUpdatedListener.java
listeners/src/main/java/org/fao/geonet/listener/history/RecordValidationTriggeredListener.java
services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java

Move StatusValue.Events to an enum class
Identified the media type that is being stored in the database. 
Instead of detecting if data is json or xml, instead base it on the media type for the event.
This is mostly a refactoring the code.
This is an enhancement on the changes from #8579

Move StatusValue.Events to an enum class

---

core/src/main/java/org/fao/geonet/util/XslUtil.java

[Backport 4.2.x] Url decode the resourceId supplied to store.getResourceInternal to fix filenames containing spaces.

---

core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
web-ui/src/main/resources/catalog/js/CatController.js
web-ui/src/main/resources/catalog/views/default/templates/recordView/lineage.html

When a metadata has multiple resource lineage source descriptions the following javascript error occurs:
```
angular.js?v=2e31720b368df88f570059d390b081d82fe9cf75:15697 Error: [linky:notstring] Expected string but received: 
[...
```
A metadata can have multiple lineage sources, updated the code to process the array of lineage sources. After the change:

Record view / fix javascript error when a metadata has multiple lineage source descriptions

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl

If the dates are not valid there was an error in the metadata document index, failing the search when the metadata is returned:
```
at org.fao.geonet.api.es.EsHTTPProxy.lambda$processResponse$0(EsHTTPProxy.java:700)
at org.fao.geonet.api.es.JsonStreamUtils.filterTree(JsonStreamUtils.java:147)
at org.fao.geonet.api.es.JsonStreamUtils.lambda$null$1(JsonStreamUtils.java:109)
at org.fao.geonet.api.es.JsonStreamUtils.filterArrayElements(JsonStreamUtils.java:50)
at org.fao.geonet.api.es.JsonStreamUtils.lambda$addInfoToDocs$2(JsonStreamUtils.java:108)
at org.fao.geonet.api.es.JsonStreamUtils.filterObjectInPath(JsonStreamUtils.java:74)
at org.fao.geonet.api.es.JsonStreamUtils.filterObjectInPath(JsonStreamUtils.java:77)
at …
```

Metadata indexing / parse process steps and measure dates to check that are valid.

---

core/src/main/java/org/fao/geonet/api/exception/InputStreamLimitExceededException.java
core/src/main/java/org/fao/geonet/api/exception/RemoteFileTooLargeException.java
core/src/main/java/org/fao/geonet/api/records/attachments/AbstractStore.java
core/src/main/java/org/fao/geonet/api/records/attachments/FilesystemStore.java
core/src/main/java/org/fao/geonet/util/LimitedInputStream.java
core/src/test/resources/WEB-INF/config.properties
core/src/test/resources/org/fao/geonet/api/Messages.properties
core/src/test/resources/org/fao/geonet/api/Messages_fre.properties
datastorages/jcloud/src/main/java/org/fao/geonet/api/records/attachments/JCloudStore.java
services/src/main/java/org/fao/geonet/api/GlobalExceptionController.java
services/src/test/java/org/fao/geonet/api/records/attachments/AbstractStoreTest.java
web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties

Currently the `putResourceFromURL` api does not enforce the maximum upload size limit. This means that you can upload files larger than the limit if you provide a URL to that resource rather than uploading the file directly.
This PR aims to fix this issue by checking the InputStream's available bytes against the configured `maxUploadSize`.

Enforce upload size limit on putResourceFromUrl api

---

core/src/main/java/org/fao/geonet/api/exception/InputStreamLimitExceededException.java
core/src/main/java/org/fao/geonet/api/exception/RemoteFileTooLargeException.java
core/src/main/java/org/fao/geonet/api/records/attachments/AbstractStore.java
core/src/main/java/org/fao/geonet/api/records/attachments/FilesystemStore.java
core/src/main/java/org/fao/geonet/util/LimitedInputStream.java
core/src/test/resources/WEB-INF/config.properties
core/src/test/resources/org/fao/geonet/api/Messages.properties
core/src/test/resources/org/fao/geonet/api/Messages_fre.properties
datastorages/jcloud/src/main/java/org/fao/geonet/api/records/attachments/JCloudStore.java
services/src/main/java/org/fao/geonet/api/GlobalExceptionController.java
services/src/test/java/org/fao/geonet/api/records/attachments/AbstractStoreTest.java
web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties

[Backport 4.2.x] Enforce upload size limit on putResourceFromUrl api

---

core/src/test/resources/org/fao/geonet/api/Messages_fre.properties
web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties

Test case:
Steps to recreate:
- use the french interface
- click sign in / s'identifier
- click create an account / créer un compte
- fill in the registration form and click register / créer un compte
- a blue message box pops up in the top, left corner with the message in English: "User '[email address]' registered."
With the pull request in the French user interface, it is displayed the message: "Utilisateur '[email address]' enregistré."

French translation for user registered message

---

core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataOperations.java

Currently privileges cannot be unset from the `Manage Record > Privileges` UI.
The issue occurs when list of operations to exclude from deletion is empty. Passing an empty list seems to cause no operations to be deleted instead of all operations for certain database types. H2 does not have this issue however PostgreSQL does.
This PR aims to fix this issue by deleting all operations when the excludes list is empty instead of passing the empty list.

Fix privileges cannot be unset

---

core/src/main/java/org/fao/geonet/api/records/attachments/AbstractStore.java
core/src/main/java/org/fao/geonet/util/LimitedInputStream.java
datastorages/jcloud/src/main/java/org/fao/geonet/api/records/attachments/JCloudStore.java

Currently the content length for uploading resources to jcloud is set using the InputStream.available function which is unreliable. This results in uploads ending pre-maturely.
This PR aims to fix this issue by passing the content length to the input stream so the jcloud store can use that value if it is known.

Fix jcloud content length is inaccurate

---

domain/src/main/java/org/fao/geonet/repository/SourceRepository.java
services/src/main/java/org/fao/geonet/api/sources/SourcesApi.java
services/src/test/java/org/fao/geonet/api/sources/SourcesApiTest.java
web-ui/src/main/resources/catalog/components/usersearches/UserSearchesDirective.js
web-ui/src/main/resources/catalog/components/usersearches/UserSearchesService.js
web-ui/src/main/resources/catalog/js/admin/CSWTestController.js

Add get /api/sources/{sourceIdentifier} to be able to get a source by id.
Moved /api/sources/{type} to Moved /api/sources?type=type as it conflicted with /api/sources/{sourceIdentifier}

Add get /api/sources/{sourceIdentifier} to be able to get a source by id.

---

web-ui/src/main/resources/catalog/locales/ca-editor.json
web-ui/src/main/resources/catalog/locales/cs-editor.json
web-ui/src/main/resources/catalog/locales/da-editor.json
web-ui/src/main/resources/catalog/locales/de-editor.json
web-ui/src/main/resources/catalog/locales/es-editor.json
web-ui/src/main/resources/catalog/locales/fi-editor.json
web-ui/src/main/resources/catalog/locales/fr-editor.json
web-ui/src/main/resources/catalog/locales/is-editor.json
web-ui/src/main/resources/catalog/locales/it-editor.json
web-ui/src/main/resources/catalog/locales/ko-editor.json
web-ui/src/main/resources/catalog/locales/nl-editor.json
web-ui/src/main/resources/catalog/locales/pt-editor.json
web-ui/src/main/resources/catalog/locales/ru-editor.json
web-ui/src/main/resources/catalog/locales/sk-editor.json
web-ui/src/main/resources/catalog/locales/sv-editor.json
web-ui/src/main/resources/catalog/locales/zh-editor.json

This pull request is for `4.2.x` where backporting the Transifex translations to this branch in #8166 the translations for link to sibling were changed accidentally to English.
Thanks @ianwallen for reporting the issue.

Restore link to sibling translations.

---

core/src/main/java/org/fao/geonet/api/records/attachments/AbstractStore.java
core/src/test/java/org/fao/geonet/api/records/attachments/FilesystemStoreTest.java

Currently the putResourceFromUrl API gets the file name from the URL itself but does not consider URL encoded characters. This means if a URL like `http://domain.com/dictionnaire%20de%20donn%C3%A9es.pdf` is provided the uploaded file's name will be `dictionnaire%20de%20donn%C3%A9es.pdf`.
This PR aims to fix this issue by URL decoding the filename. With this fix the filename would be `dictionnaire de données.pdf` as intended.

URL Decode filename for resources uploaded by url

---

pom.xml

I have released an unsupported version of [GeoTools 28.6](https://github.com/geotools/geotools/releases/tag/28.6) that contains the patch for CVE-2024-36404.
This is not intended to be a functional change, only to prevent security scans for being upset. 
For *main* branch see https://github.com/geonetwork/core-geonetwork/pull/8613

Update GeoTools 28.6

---

docs/manual/docs/api/the-geonetwork-api.md

* Use `srv/api/me` endpoint (instead of old API)
* Use session once connected.

Doc / Update Python example

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/citation/base.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/citation/common.xsl
schemas/iso19139/src/main/plugin/iso19139/formatter/citation/base.xsl
services/src/test/resources/org/fao/geonet/api/records/formatters/iso19115-3.2018-citation-bibtex.txt
services/src/test/resources/org/fao/geonet/api/records/formatters/iso19115-3.2018-citation-ris.txt
services/src/test/resources/org/fao/geonet/api/records/formatters/iso19139-citation-bibtex.txt
services/src/test/resources/org/fao/geonet/api/records/formatters/iso19139-citation-ris.txt
web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionsDirective.js
web-ui/src/main/resources/catalog/components/metadataactions/partials/citation.html
web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
web-ui/src/main/resources/catalog/locales/en-core.json

- BibTex: change data entry type to `misc` (`data` seems not valid: https://en.wikipedia.org/wiki/BibTeX\#Entry_types).
- RIS: add support for `PY` (publication year), `DA` (publication date) and `LA` (language) fields.
Adds also an option to download the citation file:
Funded by EEA

Metadata citation improvements

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl

Analog to #8598 to parse resource maintenance date of next update to check that is valid, otherwise if the search results return the metadata with the issue, the search response is returned.
Search response error:
```
at org.fao.geonet.api.es.EsHTTPProxy.lambda$processResponse$0(EsHTTPProxy.java:696)
at org.fao.geonet.api.es.JsonStreamUtils.filterTree(JsonStreamUtils.java:147)
at org.fao.geonet.api.es.JsonStreamUtils.lambda$addInfoToDocs$1(JsonStreamUtils.java:109)
at org.fao.geonet.api.es.JsonStreamUtils.filterArrayElements(JsonStreamUtils.java:50)
at org.fao.geonet.api.es.JsonStreamUtils.lambda$addInfoToDocs$2(JsonStreamUtils.java:108)
at org.fao.geonet.api.es.JsonStreamUtils.filterObjectInPath(JsonStreamUtils.java:74)
```
Index error of a metadata with …

Metadata indexing / parse resource maintenance date of next update to check that is valid.

---

web-ui/src/main/resources/catalog/components/filestore/FileStoreDirective.js

Currently if you paste a file anywhere in the editor it will be uploaded to the catalogue store. This is problematic as applications like Microsoft OneNote copy multiple versions of the text to the clipboard. For example OneNote has text, html, and an image version of the text.
This means that when text is copied from OneNote and pasted into a field, the image version of the text is uploaded to the store.
This behavior seems to come from `blueimp.fileupload` having its `pasteZone` set to `document`.
This PR aims to fix this issue by setting the `pasteZone` to the same element as the `dropZone`. It could also be set to `null` if the pasting functionality is not required. I suspect it may not be required as there is no field to actually paste in only a button.

Pasting text in the metadata editor uploads an image to the catalogue store

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/dut/codelists.xml
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/dut/labels.xml
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/dut/schematron-rules-datacite.xml
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/dut/schematron-rules-url-check.xml
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/dut/strings.xml

Added translations of analog elements from the iso19139 metadata schema.

Add Dutch translations of the iso19115-3.2018 metadata schema

---

.github/workflows/backport.yml
.github/workflows/linux.yml

Ubuntu 20.04 will become unsupported on 2025-04. Update the images used in the Github Actions runners to one supported.

Update Github Actions runner images

---

.github/workflows/linux.yml

Ubuntu 20.04 will become unsupported on 2025-04. Update the images used in the Github Actions runners to one supported.
https://github.com/actions/runner-images/issues/11101

[BP] Update Github Actions runner images

---

web-ui/src/main/resources/catalog/views/default/templates/recordView/type-dataset.html

Set a limit to rendering the number of children thumbnail. Similar to the card view 
https://github.com/geonetwork/core-geonetwork/blob/ed27371b6fae65cb451ab5b8b28c19cd972cab8d/web-ui/src/main/resources/catalog/views/default/templates/recordView/type-dataset.html#L121
In some extreme case, the user can set hundreds of children to a parent record and causing some mess to the parent record view page. This issue is discussed in pull request of https://github.com/geonetwork/core-geonetwork/pull/8608

Set related children's thumbnail to default 4

---

web-ui/src/main/resources/catalog/components/common/map/mapDirective.js

Map viewer / Use 8 decimals for the bounding box of map in a metadata.

---

web-ui/src/main/resources/catalog/components/common/map/mapDirective.js

[Backport 4.2.x] Map viewer / Use 8 decimals for the bounding box of map in a metadata.

---

web-ui/src/main/resources/catalog/components/search/resultsview/ResultsviewDirective.js
web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid.html
web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/list.html

The Search Page break down the abstract brief by line break as paragraphs. However, there is some special case some user write the format as 
Description:
This is some abstract etc.
By the existing logic, search result will show very little abstract which is not clear to the user
The improved logic will make sure the abstract brief is at least 50 characters or it will keep appending the next paragraph together.
As result, the user will have more content to read.

Search result record abstract parsing improvement

---

web-ui/src/main/resources/catalog/components/utility/DraftValidationWidget.js

This was causing the issue in the widget, related to this backport: https://github.com/geonetwork/core-geonetwork/pull/8483 where `documentStandard` field is required in the backend code. Due to the wrong property name, was not added.
In `main` it contains the correct value.

Fix DraftValidationWidget Elasticsearch query.

---

web-ui/src/main/resources/catalog/components/search/mdview/mdviewDirective.js
web-ui/src/main/resources/catalog/components/search/mdview/partials/contact.html
web-ui/src/main/resources/catalog/js/CatController.js
web-ui/src/main/resources/catalog/views/default/templates/recordView/contact.html
web-ui/src/main/resources/catalog/views/default/templates/recordView/metadatacontact.html
web-ui/src/main/resources/catalog/views/default/templates/recordView/processsteps.html
web-ui/src/main/resources/catalog/views/default/templates/recordView/type-dataset.html
web-ui/src/main/resources/catalog/views/default/templates/recordView/type-series.html

In the metadata page, clicking on a contact shows an option to filter by the organisation name: 
The filter was hardcoded to use the field `OrgForResourceObject.default`, to filter by the resource contact. Updated the code to configure the field name depending on the type of contact displayed. 
In the previous example, for a metadata contact, the query was not showing any result: 
http://localhost:8080/geonetwork/srv/eng/catalog.search?debug#/search?query_string=%7B%22OrgForResourceObject.default%22:%7B%22FAO%20-%20NRCW%22:true%7D%7D
With the change, the query shows the results properly:
http://localhost:8080/geonetwork/srv/eng/catalog.search?debug#/search?query_string=%7B%22OrgObject.default%22:%7B%22FAO%20-%20NRCW%22:true%7D%7D

Record view / contact focus on feature: allow to customise the contact field name to filter

---

web/src/main/webapp/WEB-INF/classes/schematron/iso_svrl_for_xslt2.xsl
web/src/main/webapp/xsl/utils-fn.xsl

In the dcat-ap schema plugin there is a need to translate schematron strings. One of the ways is to use the `loc/eng/schematron-rules-x.xml` files that are loaded by `iso_svrl_for_xslt2.xsl`. A helper function `replacePlaceholders` was added that makes sure the schematron rules remain language agnostic and the translations are easily adaptable to the needs of each language.
- English is proposed as the fallback language whenever a file cannot be found. 
- A shared schematron localisation file is introduced to prevent having to duplicate common schematron translation strings. Not having this file in place works fine.
- Fix in `iso_svrl_for_xslt2.xsl` to make sure $loc is also used when wrapped in a function.
In the schema plugin a PR was created that makes use of this change: …

Improved schematron localisation

---

web-ui/src/main/resources/catalog/components/thesaurus/ThesaurusService.js

Thesaurus dropdowns in the editor were only sorted by label when presenting in English, not when switching to another language. This fix should alleviate that issue, while taking into account the existing configuration toggle that sorts by id/URI instead.
Before:
After:
@fxprunayre @CMath04

Editor / Keyword dropdown / Sort keywords by label

---

schemas/config-editor.xsd
web/src/main/webapp/xslt/ui-metadata/form-builder.xsl

Added the following:
- sort snippets in the UI based on their label
- add an override for snippets when the sort should not occur based on their label (for example, when one value should be shown at the end of the list at all times)
Example implementation in the dcat-ap editor for a snippet that allows defining an empty `conformsTo`:
```xml
<snippet label="protocol-51" sortLabel="ZZZZ">
<dct:conformsTo>
<dct:Standard xmlns:dct="http://purl.org/dc/terms/">
<dct:identifier/>
<dct:title xml:lang=""/>
<dct:description xml:lang=""/>
</dct:Standard>
</dct:conformsTo>
</snippet>
```

Add sortLabel as override when applicable

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/ISO19139/mapping/CI_ResponsibleParty.xsl

Without the fix, contacts with organisation name using Anchor in ISO19139 are converted, but with empty content:
```
<gmd:pointOfContact>
<gmd:CI_ResponsibleParty>
<gmd:organisationName>
<gmx:Anchor xmlns:gmx="http://www.isotc211.org/2005/gmx" xmlns:xlink="http://www.w3.org/1999/xlink" 
xlink:href="http://test.organisation">Test organisation</gmx:Anchor>
</gmd:organisationName>
...
```
is converted to: 
```
<mri:pointOfContact />
```
With the fix:
```
<mri:pointOfContact>
<cit:CI_Responsibility>
<cit:role>
<cit:CI_RoleCode codeList="https://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#CI_RoleCode" codeListValue="custodian">custodian</cit:CI_RoleCode>
</cit:role>
<cit:party>
<cit:CI_Organisation>
<cit:name>
<gcx:Anchor xlink:href="http://test.organisation">Test …
```

Conversion from ISO19139 to ISO19115-3.2018: Manage organisation name with Anchor

---

web-ui/src/main/resources/catalog/js/admin/StaticPagesController.js

Sort the list of groups in the static pages form alphabetically.

Static pages / sort groups alphabetically

---

harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java
harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/IHarvester.java
harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/CswHarvester.java
harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Harvester.java
harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geoPREST/GeoPRESTHarvester.java
harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geoPREST/Harvester.java
harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/GeonetHarvester.java
harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Harvester.java
harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/oaipmh/Harvester.java
harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/oaipmh/OaiPmhHarvester.java
harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/ogcwxs/Harvester.java
harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/simpleurl/Harvester.java
harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/simpleurl/SimpleUrlHarvester.java
harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/thredds/Harvester.java
harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/thredds/ThreddsHarvester.java
harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/webdav/Harvester.java
harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/webdav/WebDavHarvester.java
harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/wfsfeatures/Harvester.java
harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/wfsfeatures/WfsFeaturesHarvester.java
harvesters/src/test/java/org/fao/geonet/kernel/harvest/harvester/geoPREST/HarvesterTest.java
harvesters/src/test/java/org/fao/geonet/kernel/harvest/harvester/simpleurl/HarvesterTest.java

This Pull Request fixes an issue with the way how harvesters report their errors.
Currently, there are two lists that may contain error, one in [AbstractHarvester](https://github.com/geonetwork/core-geonetwork/blob/03c2aae7a0b59d8d70f50673d0121bfd99f2cfd7/harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java#L151) and one in many harvester classes. The intent is to merge these two lists in AbstractHarvester via the `getErrors()` method.
This, however, does not work, as getErrors always returns the List that is present in AbstractHarvester. There seems to be an inheritance issue here: The subclasses of AbstractHarvester do not implement getErrors themself, but the classes that are called by the subclasses.
Let's take the CSW Harvester as an example: The …

Fix harvesting errors not always being reported

---

schemas/iso19139/src/main/plugin/iso19139/loc/por/codelists.xml

In the Portuguese codelist for the schema 19139, few words had typos and others were in Spanish.

Update translations for Portuguese in codelists for schema 19139

---

core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
web-ui/src/main/resources/catalog/components/metadataactions/RelatedDirective.js

The parent metadata can contain large amounts of children record and on its summary page, it displays their thumbnails.
The issue was it was url for each of the thumbnail which invokes its resource API and with large volumes of HTTP traffic it will crash the application if the backend database pool is relative small.
This pull request will alter the search service to have the data as part of the children in related records.
and these byte data from the search engine can be used to the HTML/Javascript

Add byte data to metadata summary page for its children thumbnails

---

web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl

When implementing the dcat-ap view, we noticed the generated title did not include the typical status label that we were used to seeing in ISO. This PR adds the same label, making use of the same markup as the ISO records. It also take into account displaying the records in an HTML view (see test on `$root = 'div'`).
added statuslabel to the dcatview
same presentation as an ISO record
@fxprunayre

dcatview statuslabel

---

SECURITY.md

Update security policy for Coordinated vulnerability disclosure.
I thought we had covered this in response to Cyber Security Act, but apparently not yet.
Please see proposed text to note handling of CVE numbers and coordinated vulnerability disclosure policy. Idea is to give everyone a chance to update before public disclosure.

Coordinated vulnerability disclosure

---

harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java
harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/simpleurl/Aligner.java

CSW and Simple URL harvesters were not translating the metadata on metadata updates if translations are configured.
This caused that metadata updated lost the translations.

CSW and Simple URL harvesters: translate the metadata on metadata updates if translations are configured

---

doi/src/main/java/org/fao/geonet/doi/client/DoiBuilder.java
doi/src/main/java/org/fao/geonet/doi/client/DoiDataciteClient.java
doi/src/main/java/org/fao/geonet/doi/client/DoiManager.java
doi/src/main/java/org/fao/geonet/doi/client/DoiMedraClient.java
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/eu-po-doi/base.xsl

Multiple DOI server (https://github.com/geonetwork/core-geonetwork/pull/8098) did not migrate the Medra client.
The Medra API send the DOI URL in the message envelope and depends on the selected DOI server.
Funded by EEA

DOI / Update medra client to use selected DOI server.

---

web-ui/src/main/resources/catalog/components/viewer/wmsimport/partials/styles.html

This change request displays the style selection menu on the right to avoid cropping it.
Before:
After:

Map viewer / show style selection menu on the right to avoid cropping it

---

web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v445/DoiServerDatabaseMigration.java

Remove invalid field name in DOI servers database migration, causing the migration to fail. 
```
2025-04-10 12:33:08.353 UTC [5710] ERROR:  column "isdefault" of relation "doiservers" does not exist at character 29
2025-04-10 12:33:08.353 UTC [5710] STATEMENT:  INSERT INTO doiservers (id, isdefault, landingpagetemplate, name, url, username, password, pattern, prefix, publicurl) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
```
Related to #8098

Remove wrong field name in  DOI server database migration

---

core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java

This is some bug leftover from the previous pull request https://github.com/geonetwork/core-geonetwork/pull/8608
The issue is some parent or siblings record come with invalid resource url which means the resource is totally missing from the backend file store system
So due to the file missing, the byte data cannot be stored in the index. Therefore, if we attempt to fetch it thru the painless script, it will causing some null pointer from the query.
This code change will filter out the null object in this case.

Avoid null pointer when indexing overview data

---

web-ui/src/main/resources/catalog/components/userfeedback/partials/mdFeedback.html

Currently the roles in the feedback form are not translated:
This PR aims to fix this issue by updating the template to translate the role codes.
After the fix the form should look like:

Translate roles in the feedback form

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/schematron/schematron-rules-datacite.sch
schemas/iso19139/src/main/plugin/iso19139/schematron/schematron-rules-datacite.sch

Some users are using ROR to add organisation identifier using `Anchor`.
```xml
<cit:CI_Organisation>
<cit:name>
<gcx:Anchor xlink:href="https://ror.org/05hnb7x64">Bureau de Recherches Géologiques et Minières (Orléans - France)</gcx:Anchor>
</cit:name>
```
When creating DOI, schematron validation was not identifying publisher properly in that case (Datacite conversion is supporting it).
Nore: It may be more relevant to use party identifier
```xml
<cit:partyIdentifier>
<mcc:MD_Identifier>
<mcc:code>
<gco:CharacterString>https://ror.org/05hnb7x64</gco:CharacterString>
</mcc:code>
</mcc:MD_Identifier>
</cit:partyIdentifier>
```

DOI / Validation /  Improve schematron validation on organisation encoded using Anchor.

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/duplicate-metadata.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/templates/geodata.xml
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/templates/map.xml
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/templates/service.xml
schemas/iso19115-3.2018/src/test/java/org/fao/geonet/schema/DuplicateRecordXslProcessTest.java
schemas/iso19115-3.2018/src/test/java/org/fao/geonet/schema/LanguageXslProcessTest.java
schemas/iso19115-3.2018/src/test/resources/metadata.xml

Compared to ISO19139 which only contains a `dateStamp` for the metadata record which GeoNetwork use to store the last update date, ISO19115-3 allows various date information about the record (eg. creation, revision, publication).
When duplicating a record, remove metadata dates of the source record. They will be initialized by db creation and update dates and this will avoid to have multiple creation dates.
For testing, duplicate an ISO19115-3 record having a creation date.
We could also at some point consider keeping only one date of each types?
Funded by Service Public de Wallonie

Standard / ISO19115-3 / Duplicate record / Remove record date.

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl

Noticed that XPath has to begin with "//" in this case.

fix iso19115-3 phone indexation

---

services/src/main/java/org/fao/geonet/api/pages/PagesAPI.java

There is a bug with the #8491 backport. The groups update logic was put below the page save logic resulting in the groups never being saved.
This means that when a static page is created with access granted to a specific group, the group which is granted access can never be changed.
Given two groups (`A` & `B`):
1. Create a static page (Settings > Static pages > New static page)
Status: Visible to users belonging to the groups
Groups: A
2. Save the static page
3. Edit the static page
Groups: B
4. Save the static page
5. Edit the static page to view the current groups
6. The groups are still set to "A"
This PR aims to fix this issue by updating the 4.2.x branch to have these calls in the correct order like the main branch.

[4.2.x] Fix cannot update groups for static page

---

core/src/test/resources/WEB-INF/config.properties
docs/manual/docs/install-guide/installing-index.md
docs/manual/docs/tutorials/introduction/deployment/deploy.md
harvesters/src/test/resources/WEB-INF/config.properties
index/src/main/java/org/fao/geonet/index/es/EsRestClient.java
pom.xml
schemas-test/src/main/webapp/WEB-INF/config.properties
services/src/main/webapp/WEB-INF/config.properties
services/src/test/resources/WEB-INF/config.properties
web/src/main/webResources/WEB-INF/config.properties
web/src/main/webResources/WEB-INF/web.xml

This pull request allows to configure the Elasticsearch connection using environment variables.

Allow to configure the Elasticsearch connection in environment variables

---

docs/manual/docs/customizing-application/implementing-a-schema-plugin.md

Add a note about how to reload schematron.
This is useful when developing new rules.

Doc / Schematron can be reloaded using API

---

web-ui/src/main/resources/catalog/components/pages/partials/menu-page.html
web-ui/src/main/resources/catalog/components/search/mdview/mdviewModule.js
web-ui/src/main/resources/catalog/views/default/templates/recordView/downloads.html
web-ui/src/main/resources/catalog/views/default/templates/recordView/recordView.html
web-ui/src/main/resources/catalog/views/default/templates/recordView/title.html

Following #7802 the `md` object is not set in the `recordView` template. The reason is that `gnMdActionsMenu` set the `md` object and now it is in a different scope.
This causes several issues:
The working copy link is broken (UUID is missing):
The record links are not shown:
The status label is not shown:
This PR aims to fix this issue by changing the template and sub templates to use `mdView.current.record` instead of `md`. With the changes from this PR all three of these issues are fixed.

Fix md is null in record view

---

core/src/main/java/org/fao/geonet/kernel/WatchListNotifier.java
core/src/main/java/org/fao/geonet/util/LocalizedEmailComponent.java
core/src/test/resources/org/fao/geonet/api/Messages.properties
core/src/test/resources/org/fao/geonet/api/Messages_fre.properties
web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_dut.properties
web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_fre.properties

Localized emails (#7966) were not fully tested with the emails sent by the watchlist feature. There are a few issues preventing these emails from being sent:
- If an email component has no parameters (`user_watchlist_message_record` for example) a null pointer exception is thrown
- The subject message uses the `%d` placeholder but a string is provided so an exception is thrown
- The url parameter is added twice to the email message so the parameters and placeholders do not match and an exception is thrown
This PR aims to fix all these issues so that the watchlist emails can be sent again.

Fix localized watchlist emails

---

web-ui/src/main/resources/catalog/components/common/savedselections/SavedSelectionsDirective.js

Currently the map list does not do much.
Clicking add to map list adds the record to the map list saved selection:
But when the "Add to map" button is clicked within the map list nothing happens:
The reason seems to be that the metadata record information is coming from an Elasticsearch query which is not including the links.
This PR aims to fix this issue by including the record's links in the Elasticsearch query. With this fix, when we click on "Add to map" the layers are added to the map.
Additionally this PR adds ESRI REST support for this feature as it currently only supports WMS.

Fix map list "add to map" function

---

web-ui/src/main/resources/catalog/components/search/mdview/mdviewDirective.js

Fixes #8776.
A manual backport to `4.2.x` is required.

Record view / fix permalink option.

---

core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java
domain/src/main/java/org/fao/geonet/domain/StatusValueNotificationLevel.java
services/src/main/java/org/fao/geonet/util/MetadataPublicationMailNotifier.java
web-ui/src/main/resources/catalog/locales/en-admin.json

Currently there is no notification level for user administrators part of the record group owner. This means if we want to use user administrators as the notified party, all user administrators are notified not only user administrators for the group which owns the record.
This PR aims to fix this issue by implementing a "Notify the user administrators part of the record group owner" option.

Add new recordProfileUserAdmin notification level

---

harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/webdav/Harvester.java

The WebDav harvester was not updating the database change date when updating a metadata as other harvesters do.
For ISO metadata, when doing a reharvest if the metadata was updated the XML contained a different value (`gmd:dateStamp`) than the value in the database, that was preserving the value from the 1st harvesting. 
Included Sonarlint improvements in the change request.

WebDav harvester / update database change date when updating a metadata.

---

web-ui/src/main/resources/catalog/style/gn.less

Update z-index for citation buttons

---

web/src/main/webResources/WEB-INF/web.xml

Fix typo in ESFeaturesProxy configuration

---

web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js

API response of `api/site/settings/details` is ordered by setting name and the configuration panel extracting sections was not ordering settings before hand. Depending on setting names, sections may be wrongly ordered (issue present in 4.4.7 with default db).
Ensure order of section whatever the setting names.
* Maybe position range should be different for each sections (see also https://github.com/geonetwork/core-geonetwork/pull/6981)

Admin console / Settings / Ensure section order

---

core/src/main/java/org/fao/geonet/kernel/security/openidconnect/SimpleOidcUser.java

Backport https://github.com/geonetwork/core-geonetwork/pull/8817

[Backport 4.2.x]OpenID Connect - Fix Login failure with empty address info (#8817)

---

web/src/main/webResources/WEB-INF/data/config/index/records.json

This is a minor fix, to support Portuguese language in `records.json`. This json is used to initialize ES.
Without this changes, we are not able to search in Portuguese.
Example error, when the user navigates to 'Map', for example:
```
Fielddata is disabled on [tag.langpor] in [gn-records]. Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default.  Please use a keyword field instead. Alternatively, set fielddata=true on [tag.langpor] in order to load field data by uninverting the inverted index. Note that this can use significant memory.
```
This was tested with 4.4.7 and elesticsearch 8.18.1.

Fix ES search for Portuguese

---

core/src/main/java/org/fao/geonet/kernel/schema/MetadataSchema.java

The log file doesn't contain meaningful error when an error occurs building the metadata schema validation rules. For example, 
```
May 19 11:31:20 2025-05-19T09:31:20,513 ERROR [geonetwork.schemamanager] -      Schematron rule compilation failed
for /PATH/geonetwork/WEB-INF/data/config/schema_plugins/iso19139/schematron/schematron-rules-geonetwork.xsl. 
Error is /PATH/geonetwork/WEB-INF/data/config/schema_plugins/iso19139/schematron/schematron-rules-geonetwork.xsl
```
WIth this change request, the exception details are added to the log file:
```
2025-05-26T12:51:40,972 ERROR [geonetwork.schemamanager] -      Schematron rule compilation failed for /PATH/geonetwork/WEB-INF/data/config/schema_plugins/iso19139/schematron/schematron-rules-geonetwork.xsl. Error is …
```

Improve error logging of exceptions when building the metadata schema validation rules

---

web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages.properties
web/src/main/webapp/WEB-INF/classes/org/fao/geonet/api/Messages_dut.properties

Currently there are issues with the English and Dutch metadata feedback email. There seems to be two different versions of the messages with different numbers of parameters. This causes field values to be out of place:
This PR aims to fix this issue by ensuring all messages are consistent in wording and number of parameters.

Fix metadata feedback email text

---

web-ui/src/main/resources/catalog/components/search/resultsview/partials/selection-widget.html

Without the change, the dialog to confirm a batch action always displays 1 metadata selected:
With the change, it displays the correct value:

Fix in the metadata selection widget the number of metadata selected

---

web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v447/migrate-default.sql

This PR removes the SQL migration steps that were redundant with Hibernate and would make the DB migration fail because the columns are already there.
Fixes https://github.com/geonetwork/core-geonetwork/pull/8644#discussion_r2142345265

Fix DB migration failure related to Datahub plugin

---

core/src/main/java/org/fao/geonet/util/MailUtil.java

A small bugfix: our mails contained special characters (éë...) that were misinterpreted by the receiving end. By setting the charSet explicitly before sending it gets fixed. As the charSet is not set anywhere explicitly (except for test mails, which do it correctly) I'd figure we'd best have an explicit default here?

Set UTF-8 on sent mails

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/create-featurecatalogue-from-wfs.xsl

When using the suggestion `create-featurecatalogue-from-wfs` metadata contact was removed.

Standard / ISO19115-3 / Suggestion / Add feature catalogue from WFS lose metadata contact

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
web-ui/src/main/resources/catalog/views/default/templates/recordView/processsteps.html

This PR modifies the ISO 19139 and ISO19115-3 plugins to correctly index process steps having multiple sources.
This was already handled by the UI but unfortunately for both schemas the indexation was failing because of this line:
```xsl
<xsl:if test="normalize-space(gmd:source)">
```
with the following error:
```
Error on line 1054 of index.xsl:
XPTY0004: A sequence of more than one item is not allowed as the first argument of
normalize-space() ("...", "...") 
```
This error has been removed by not using `normalize-space()` any more and instead checking whether the `source` array in the index document is empty or not.
Funded by [UFZ](https://www.ufz.de/)

Lineage / handle process steps with multiple sources

---

web/src/main/webapp/WEB-INF/classes/schematron/iso_svrl_for_xslt2.xsl

Follow up of #8665 where the change expects to contain `$loc/strings`
This breaks the messages displayed that used variables starting with `$loc`. For example, with the change in #8665, the following code instead of displaying in the validation the translation text value as previously:
https://github.com/metadata101/iso19139.ca.HNAP/blob/76791b4be27f1b9e111ebeffd83c7c4edc3b6ea4/src/main/plugin/iso19139.ca.HNAP/schematron/schematron-rules-multilingual.sch#L287-L288
It displays the text `$locMsgMainLang`

Schematron validation message: restore the logic to resolve validation  messages starting with '$loc'

---

core/src/main/java/org/fao/geonet/kernel/security/openidconnect/GeonetworkOidcPreAuthActionsLoginFilter.java
core/src/main/java/org/fao/geonet/kernel/security/openidconnect/SessionExpirationFilter.java
web/src/main/webapp/WEB-INF/config-security/config-security-openidconnectbearer.xml

- Add session filter for OIDC to detect invalidated session from OIDC provider such as Keycloak, and end the http session in spring
- Modify the condition in [GeonetworkOidcPreAuthActionsLoginFilter.java](https://github.com/geonetwork/core-geonetwork/compare/main...xiechangning20:core-geonetwork:main?expand=1#diff-ba9a74ea7e017e4859bcc65fefc8fbc72270685ecf78092fde3f8ff17202f9ad) to redirect the user to re-authentication if there session does not exists

Fix issue with oidc invalid session by adding session filter

---

web/src/main/webapp/xslt/ui-metadata/form-builder.xsl

When configuring the tooltip mode to icon in `config-editor.xml`:
```
<view name="default" default="true"
displayTooltips="true" displayTooltipsMode="icon"
class="gn-label-above-input gn-indent-bluescale">
```
Help icons are displayed next to the input fields, but also are displayed in the buttons to add new elements. In this mode the rendering is not very good. It seems better to define a descriptive label:
With this change:

Metadata editor / Avoid displaying the tooltip icon next to buttons to add new elements, when the toolstip mode is icon

---

web-ui/src/main/resources/catalog/components/edit/validationreport/ValidationReportDirective.js

Follow up: #6456
If a schema has optional validation rules, the schema validation was not displayed at the bottom.
Before:
After:

Validation report / Show schema validation after optional rules

---

services/src/main/java/org/fao/geonet/api/records/formatters/FormatterApi.java
web-ui/src/main/resources/catalog/components/search/mdview/mdviewModule.js
web-ui/src/main/resources/catalog/components/search/mdview/mdviewService.js
web-ui/src/main/resources/catalog/views/default/directives/directive.js

View and download formatter are configured globally. But not all metadata schemas support the same formatters. This is specially true for DCAT-AP formatters and metadata from schemas like Dublin Core or ISO19110.
This change request adds a new API endpoint to retrieve a list of formatter names available for a metadata:
`GET` `​/records​/{metadataUuid}​/formatters`
Example:
http://localhost:8080/geonetwork/srv/api/records/b41b7ce1-9695-435c-858d-d017b05d5934/formatters
```
[
"zip",
"iso19115-3.2018",
"citation",
"datacite",
"jsonld",
"eu-dcat-ap",
"eu-geodcat-ap-semiceu",
"xml",
"xsl-view",
"eu-dcat-ap-hvd",
"eu-geodcat-ap",
"dcat",
"eu-po-doi"
]
```
The metadata record page is updated to filter out the view and download formatters not supported by the metadata schema.
Download formatters: …

Record page / restrict formatters to view / export metadata to those supported by the metadata schema

---

web-ui/src/main/resources/catalog/components/userfeedback/GnUserfeedbackDirective.js

Currently if a user refreshes the record view then tries to add a rating they will appear as logged out in the ratings panel:
This causes confusion for the users as the message says they are not logged in even though they are logged in. In this circumstance he user must re-enter their information if they want to submit a rating.
This PR aims to fix this issue by rechecking the logged in status when the rating panel is opened.
After these changes the user can refresh the page and submit a rating without needing to re-enter their details.

Fix user appears logged out in ratings panel

---

web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js
web-ui/src/main/resources/catalog/templates/admin/settings/system.html

The INSPIRE Atom type setting was retrieved fine from the database, but the user interface didn't select the correct value, displaying the entry as empty. When saving the settings, the value was reset to an invalid value.
With this fix, the user interface is fixed, selecting properly the value:

Settings / Fix INSPIRE Atom type setting value selected

---

harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/simpleurl/Aligner.java

Simple URL harvester was not reindexing the updated metadata. Accessing the metadata page displayed the old information. Issuing a manual indexing, the metadata page displays the updated information.
This change request reindexes the metadata when it is updated.

Simple URL harvester / Index the metadata when updated

---

domain/src/main/java/org/fao/geonet/domain/Setting.java
events/src/main/java/org/fao/geonet/events/setting/SettingsChanged.java
inspire-atom/src/main/java/org/fao/geonet/inspireatom/listener/setting/InspireAtomSettingsChangedListener.java
services/src/main/java/org/fao/geonet/api/site/SiteApi.java

The scheduler for the remote INSPIRE ATOM harvester is processed during application start-up, 
https://github.com/geonetwork/core-geonetwork/blob/f8042c0c229a6a9568d48c5ff9860e2c4cd8e002/web/src/main/java/org/fao/geonet/Geonetwork.java#L322-L336
but when the related system settings are updated, the scheduler is not updated.
This change request adds a new application event that is triggered when the system settings are updated. This event receives the old and new values of the settings. This event can be used to create listeners to execute for example this code defined currently in `SiteApi`: https://github.com/geonetwork/core-geonetwork/blob/f8042c0c229a6a9568d48c5ff9860e2c4cd8e002/services/src/main/java/org/fao/geonet/api/site/SiteApi.java#L146-L176
The `inspire-atom` module includes a …

Remote INSPIRE ATOM harvester / fix scheduling

---

core/src/main/java/org/fao/geonet/kernel/datamanager/IMetadataManager.java
core/src/main/java/org/fao/geonet/kernel/datamanager/IMetadataValidator.java
core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java
core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataValidator.java

Currently the batch validation from the search page and editor board does not output the same results as the validation from within the metadata editor.
For example the iso19139.ca.HNAP rule for topicCategory is defined as:
```XML
<sch:rule context="//gmd:identificationInfo/*/gmd:topicCategory  
|//*[@gco:isoType='gmd:MD_DataIdentification']/gmd:topicCategory
|//*[@gco:isoType='srv:SV_ServiceIdentification']/gmd:topicCategory">  
<sch:let name="missing" value="not(string(gmd:MD_TopicCategoryCode))  
" />  
<sch:assert  
test="not($missing)"  
>$loc/strings/TopicCategory</sch:assert>  
</sch:rule>
```
The validation from the editor shows:
But the batch validation outputs:
This issue occurs on the above mentioned rule because the rule is checking for a `gmd:MD_TopicCategoryCode` on the …

Fix batch validation and editor validation do not output the same result

---

services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java

Currently there are issues downloading attachments and displaying thumbnails. These issues seem to be caused by the newly introduced `etag`/`lastModifiedDate`/`304` logic. The server attempts to send `304` to the client but the `@ResponseStatus(value = HttpStatus.OK)` annotation was forcing a `200`.
Identified by @josegar74 in #8940
Reproduction steps:
1. Load ISO19139 samples
2. Go to the metadata page of Hydrological Basins in Africa (Sample record, please remove!)--> thumbnails are displayed.
3. Copy the URL of one of the thumbnails
4. Refresh the browser page --> Thumbnails are not displayed.
5. Paste the URL from item 3 in a new browser tab. A dialog to save the file is displayed, saving the file, the size is 0.
This PR aims to fix this issue by removing the above mentioned …

Fix attachment caching issue

---

services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsApi.java

Introduced while implementing resumable downloads #8940 #8959
Currently attachment downloads are not working for the jcloud store. This is caused by the temporary file being deleted before the file is served.
This PR aims to solve this issue by removing the auto closing logic for the resource holder. This will prevent the temporary file from being deleted prematurely. The PathResource is also customized to close the ResourceHolder when it's InputStream is closed to ensure the temporary file is deleted.

Fix attachment download for jcloud

---

core/src/main/java/org/fao/geonet/kernel/security/openidconnect/GeonetworkClientRegistrationProvider.java
core/src/main/java/org/fao/geonet/kernel/security/openidconnect/HardcodedRegistrationIdOAuth2AuthorizationRequestResolver.java
core/src/main/java/org/fao/geonet/kernel/security/openidconnect/oidclogout/InMemoryOidcSessionRegistry.java
core/src/main/java/org/fao/geonet/kernel/security/openidconnect/oidclogout/OidcBackchannelLogoutFilter.java
core/src/main/java/org/fao/geonet/kernel/security/openidconnect/oidclogout/OidcSessionInformation.java
core/src/main/java/org/fao/geonet/kernel/security/openidconnect/oidclogout/OidcSessionRegistry.java
core/src/main/java/org/fao/geonet/kernel/security/openidconnect/oidclogout/OidcSessionRegistryAuthenticationStrategy.java
core/src/test/java/org/fao/geonet/security/web/csrf/GeonetworkCsrfSecurityRequestMatcherTest.java
docs/manual/docs/administrator-guide/managing-users-and-groups/authentication-mode.md
web/src/main/webapp/WEB-INF/config-security/config-security-core.xml
web/src/main/webapp/WEB-INF/config-security/config-security-openidconnect-overrides.properties
web/src/main/webapp/WEB-INF/config-security/config-security-openidconnect.xml
web/src/main/webapp/WEB-INF/config-security/config-security-openidconnectbearer-overrides.properties
web/src/main/webapp/WEB-INF/config-security/config-security-openidconnectbearer.xml

Implement OIDC Logout based on Spring security 6.5.x 
Add OidcBackchannelLogoutFilter that handles backchannel logout request and invalidate OIDC and http sessions
Add InMemoryOidcSessionRegistry that handles stores and removes OIDC sessions
Add OidcSessionRegistryAuthenticationStrategy that save the OIDC session during authentication
Modify xml configuration to config the filters and classes
Fix the typo of registrationId
- [✔️ ] I have read the [contribution guidelines](https://github.com/geonetwork/core-geonetwork/blob/main/CONTRIBUTING.md)
- [✔️ ] *Pull request* provided for `main` branch, backports managed with label
- [ ✔️] *Good housekeeping* of code, cleaning up comments, tests, and documentation
- [✔️ ] *Clean commit history* broken into understandable chucks, avoiding big …

Fix the back channel logout config that is missing in the current version of spring security

---

web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcService.js

The online resource added to the dataset contained the text 'undefined' instead of the service online resource name
Test case:
1) Create a service metadata with an online resource.
2) Create a dataset metadata and add a link to the previous service, selecting the option `Add the following link to the dataset (as an online source in the distribution section): ...`
3) Without the fix: the service link is added and an online resource with the name `undefined` --> **NO OK**
3) With the fix: the service link is added and an online resource with the name of the online resource in the service metadata is added --> **OK**

Add service associated resource. Fix add link from service distribution section.

---

services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java

The publication type parameter in the metadata sharing API should be optional, but was defined as required.

Sharing API / fix publication type parameter to be optional

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/common.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl
schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
services/src/main/java/org/fao/geonet/api/records/formatters/SchemaLocalizations.java
services/src/test/java/org/fao/geonet/api/records/formatters/SchemaLocalizationsIntegrationTest.java
services/src/test/java/org/fao/geonet/api/records/formatters/SchemaLocalizationsTest.java
web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl

The full view formatter was not calculating the label to display for an element when the element context property contained the full xpath instead of the parent element name.
For example, previously if the `gmd:element` was defined with different values depending on the xpath, like:
https://github.com/metadata101/iso19139.nl.geografie.2.0.0/blob/6b24bb8735e4ad6a7163de0ada3fbe9cf0a436dd/src/main/plugin/iso19139.nl.geografie.2.0.0/loc/dut/labels.xml#L540-L555
```xml
<element name="gmd:description" context="/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:extent/gmd:EX_Extent/gmd:description">
<label>Beschrijving temporele dekking</label>
<description>temporele dekking van de data, gespecificeerd als een periode.</description>
</element>
<element name="gmd:description" …
```

Record page / Update metadata full view formatter to Use context information with xpath from labels.xml

---

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout-custom-fields.xsl
schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/eng/labels.xml

This pull request affects `4.2.x`  branch. In `main` branch units of measure are managed a bit differently:  https://github.com/geonetwork/core-geonetwork/pull/8245, which is not backported to `4.2.x`
Without the changes, the units can only be selected from the suggestions list
With the changes, the user can write the units:

[4.2.x] ISO1915-3.2018 / Metadata editor / Allow to write the value of the unit of measure for spatial representation of grid spatial representation

---

core/src/main/java/org/fao/geonet/kernel/SchematronValidatorExternalMd.java
core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataValidator.java

Correcting some log messages that were not clear.
i.e. 
**Before** **for more details** is confusing.
`2025-09-18T13:00:57,181 ERROR [geonetwork.harvester] - Cannot validate XML from file /home/site/geonetwork/data/harvester/xml-files/test.xml, ignoring. Error was: Schematron errors detected for file   - schematronVerificationError: Failed to validate resources associated with the catalogue entry. for more details`
**After** 
`2025-09-18T13:00:57,181 ERROR [geonetwork.harvester] - Cannot validate XML from file /home/site/geonetwork/data/harvester/xml-files/test.xml, ignoring. Error was: Schematron errors detected for file ' ' - schematronVerificationError: Failed to validate resources associated with the catalogue entry.`
**Before** Missing ", " when there are multiple errors and it shows …

Corrected the formatting on validation log messages.

---

web-ui/src/main/resources/catalog/locales/ca-search.json
web-ui/src/main/resources/catalog/locales/ca-v4.json
web-ui/src/main/resources/catalog/locales/cy-search.json
web-ui/src/main/resources/catalog/locales/cy-v4.json
web-ui/src/main/resources/catalog/locales/en-search.json
web-ui/src/main/resources/catalog/locales/en-v4.json
web-ui/src/main/resources/catalog/locales/es-search.json
web-ui/src/main/resources/catalog/locales/fi-search.json
web-ui/src/main/resources/catalog/locales/fi-v4.json
web-ui/src/main/resources/catalog/locales/is-search.json
web-ui/src/main/resources/catalog/locales/is-v4.json
web-ui/src/main/resources/catalog/locales/it-search.json
web-ui/src/main/resources/catalog/locales/it-v4.json
web-ui/src/main/resources/catalog/locales/ko-search.json
web-ui/src/main/resources/catalog/locales/ko-v4.json
web-ui/src/main/resources/catalog/locales/pl-search.json
web-ui/src/main/resources/catalog/locales/pl-v4.json
web-ui/src/main/resources/catalog/locales/pt-search.json
web-ui/src/main/resources/catalog/locales/pt-v4.json
web-ui/src/main/resources/catalog/locales/ru-search.json
web-ui/src/main/resources/catalog/locales/ru-v4.json
web-ui/src/main/resources/catalog/locales/sk-search.json
web-ui/src/main/resources/catalog/locales/sk-v4.json
web-ui/src/main/resources/catalog/locales/zh-search.json
web-ui/src/main/resources/catalog/locales/zh-v4.json

Before:
- The text `Clicking on Replace by selected...` was not aligned with the button `Update`.
-  The text `remove record categories` was wrong, should be `remove record privileges`.
- `Update` button tooltip typo in `priviliges`.
After:

Update batch privileges dialog texts

---

services/src/main/java/org/fao/geonet/api/records/formatters/SchemaLocalizations.java

Fixes issue where harvester validation did not have an http request attributes which was causing null pointer error.
This is a sample error that was previously generated.
`2025-09-12T10:43:45,637 ERROR [geonetwork.harvester] - Cannot validate XML from file /home/site/geonetwork/data/harvester/xml-files/test.xml, ignoring. Error was: Schematron errors detected for file   - schematronVerificationError: Exception in extension function java.lang.NullPointerException, schematronVerificationError: Failed to validate resources associated with the catalogue entry. for more details`

Use default locale for harvester validation.

---

docs/manual/docs/overview/change-log/index.md

Update change log page, that was referencing to the release notes of 4.2.13 instead of 4.2.14

Release notes for 4.2.14 - update change log page

---

docs/manual/docs/overview/change-log/index.md

Update change log page, that was referencing to the release notes of 4.2.13 instead of 4.2.14

[4.2.x] Release notes for 4.2.14 - update change log page
