- core/src/main/java/org/fao/geonet/kernel/search/keyword/KeywordSearchParamsBuilder.java
- core/src/main/java/org/fao/geonet/kernel/search/keyword/URISearchClause.java
Actually when running a keyword search, both the labels and the code are used for the search.
The label search is based on the search type parameter but the code search is equal only.
Use the search type parameter to search in keyword codes like on labels.
This will allows user to search keyword by code without knowning the full URI
eg. http://www.eionet.europa.eu/gemet/concept/12349 should be used for now to search
for "beach cleansing" concept in GEMET. With this change 12349 could also be used.
This is useful when codes may have meanings or when users know concept codes.
> Search on keyword code depending on type of search parameter (eg. equals, contains, startswith)

- core/src/main/java/org/fao/geonet/kernel/security/ldap/AbstractLDAPUserDetailsContextMapper.java
- core/src/main/java/org/fao/geonet/kernel/security/ldap/LDAPUtils.java
- domain/src/main/java/org/fao/geonet/domain/Address.java
- domain/src/main/java/org/fao/geonet/domain/LDAPUser.java
- domain/src/main/java/org/fao/geonet/domain/User.java
- web/src/main/webapp/WEB-INF/config-security/config-security-ldap.xml
- web/src/main/webapp/WEB-INF/config-security/config-security.properties
NPE may occurs in 2 places depending on the configuration: 
* when hashcode on DN which may be null
* when ldapBaseDn is not set
Do not reset profile using LDAP info, if configuration says to use the local db value.
Do not reset user information if LDAP info are empty (and not only if null). With this, LDAP user info could still be set in the database even if not available in the LDAP.
Try to add doc to ldap.privilege.create.nonexisting.users property.
> Fix NPE when LDAP user login (#708).

- core/src/main/java/org/fao/geonet/kernel/DataManager.java
- core/src/main/java/org/fao/geonet/kernel/setting/SettingManager.java
- services/src/main/java/org/fao/geonet/services/metadata/Insert.java
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/geocat.html
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid.html
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/list.html
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v300/migrate-default.sql
- web/src/main/webapp/WEB-INF/config-lucene.xml
_logo is chosen as follows:
If metadata.groupOwner != null && metadata.group.logo != null && settings.prefergrouplogo {
_logo = /resources/logo/{{metadata.group.logo}}.<ext>
} else {
_logo = /resources/logo/{{metadata.source.uuid}}.<ext>
}
<ext> is chosen by searching the resources/logo directory for an image with the prefix source.uuid or group.logo (according to above algorithm).  This ensures that the image is valid irregardless of whether the user uploaded a gif or png or tif or... and is not hardcoded as a .gif like many old solutions of logo were.
This will not change any behaviour of existing systems because most current sytems will not have group.logo since that is a new geocat 3.0 feature.  additionally there is a setting that will force the logo to always be based on the …
> Change templates to use the _logo index field for logo path.

- web-ui/src/main/resources/catalog/templates/admin/harvest/type/arcsde.js
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/csw.js
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/filesystem.js
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/geoPREST.js
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/geonetwork.js
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/geonetwork20.js
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/oaipmh.js
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/ogcwxs.js
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/thredds.js
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/webdav.js
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/wfsfeatures.js
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/z3950.js
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/z3950Config.js
When adding a harvesting node, the boolean default values are discarded because of string vs boolean mismatch in js.
tests: runtime tested.
> Harvesting - Fixing default options

- domain/src/main/java/org/fao/geonet/domain/Setting.java
That commit fixes two of the three hibernate hdb2ddl issues:
```
ERROR [org.hibernate.tool.hbm2ddl.SchemaUpdate] - HHH000388: Unsuccessful: alter table Settings add column internal char(1) not null
ERROR [org.hibernate.tool.hbm2ddl.SchemaUpdate] - ERROR: column "internal" contains null values
ERROR [org.hibernate.tool.hbm2ddl.SchemaUpdate] - HHH000388: Unsuccessful: alter table Settings add column position int4 not null
ERROR [org.hibernate.tool.hbm2ddl.SchemaUpdate] - ERROR: column "position" contains null values
```
Whatever i try for the UserGroups profile field addition (which should be added between 2.8 and 2.10), it will still complain:
```
ERROR [org.hibernate.tool.hbm2ddl.SchemaUpdate] - HHH000388: Unsuccessful: alter table UserGroups add column profile int4 not null
2015-01-29 …
```
> Provide default values for position and internal fields (issue #739)

- core/src/main/java/org/fao/geonet/kernel/EditLib.java
- core/src/main/java/org/fao/geonet/kernel/SchemaManager.java
- core/src/main/java/org/fao/geonet/kernel/schema/MetadataSchema.java
- schemas/iso19139/src/main/java/org/fao/geonet/schema/iso19139/ISO19139SchemaPlugin.java
- schemas/iso19139/src/main/plugin/iso19139/index-fields/default.xsl
- schemas/schema-core/src/main/java/org/fao/geonet/kernel/schema/ISOPlugin.java
- services/src/main/java/org/fao/geonet/guiservices/metadata/GetRelated.java
- services/src/main/java/org/fao/geonet/services/metadata/EditUtils.java
- services/src/main/java/org/fao/geonet/services/metadata/format/groovy/Functions.java
- web-ui/src/main/resources/catalog/components/common/schemamanager/SchemaManagerService.js
When adding a simple element only gco:CharacterString were added. Some schema may have a different basic type.
For the time being only gco:CharacterString is customizable.
It's required for ISO19139 and ISO19115-3, the later using a new namespace for all basic types.
> SchemaPlugin / Add ISOPlugin interface to be able to customize basic type

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFilesystemHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFsHarvesterFileVisitor.java
On local filesystem, reconsidering the indexation at each inserted MD can be really time-consuming and inneficient. This PR proposes to postpone the indexation, forcing the indexation once every MDs have been parsed and inserted.
> Local FS harvesting - postpone indexation

- web/pom.xml
At runtime, jetty complains about a missing dependency when GN is
configured to use a postgis alternate datasource
(see config-db/postgis-alternate-datasource.xml). This commit adds the
missing GeoTools module.
Tests: runtime tested, launching jetty via maven (mvn jetty:run)
> web - missing dependency in pom.xml

- core/src/main/java/org/fao/geonet/kernel/DataManager.java
- core/src/main/java/org/fao/geonet/kernel/IndexMetadataTask.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/arcsde/ArcSDEHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFilesystemHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFsHarvesterFileVisitor.java
When the harvester is configured to delete old previously harvested elements, a query is made to fetch *every* (java object) Metadata for this specific harvester, from the database.
On regular directories, containing less than a hundred or thousands of MD, that is not a problem, but our customer is willing to harvest a directory containing +230k metadata, which obviously won't fit, even on a server with a huge amount of RAM.
Most problematic line of code is here:
https://github.com/geonetwork/core-geonetwork/blob/develop/harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFilesystemHarvester.java#L133
This commit proposes to address the problem by:
- Constructing a list of Integers instead of strings (this can reduce the amount of mermory used by java …
> Local FS harvesting - fixing memory consumption

- web-ui/src/main/resources/catalog/locales/fr-core.json
Having that trailing comma leads to JSON parsing errors in firebug, and the inability to switch languages.
> remove trailing comma

- domain/src/main/java/org/fao/geonet/domain/statistic/LuceneQueryParamType.java
In a case, it is possible to have no upper boundary,e.g. the following
filter:
```xml
<ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml">
<ogc:PropertyIsGreaterThanOrEqualTo matchCase="false">
<ogc:PropertyName>csw:Modified</ogc:PropertyName>
<ogc:Literal>2014-09-04</ogc:Literal>
</ogc:PropertyIsGreaterThanOrEqualTo>
</ogc:Filter>
```
can lead to a NPE when creating the Lucene filter:
```
at org.fao.geonet.domain.statistic.LuceneQueryParamType$7.createTypeFrom(LuceneQueryParamType.java:126)
at org.fao.geonet.domain.statistic.LuceneQueryParamType.createRequestParam(LuceneQueryParamType.java:162)
at org.fao.geonet.kernel.search.log.SearcherLogger.extractQueryTerms(SearcherLogger.java:144)
at …
```
> fixing NPE when CSW searching

- docs/eng/developer/source/xml_services/group_xml_services.rst
URL for xml.info was incorrect
> Fixed typo in group services documentation for 2.10.x

- domain/src/test/java/org/fao/geonet/repository/InspireAtomFeedRepositoryTest.java
- web/src/main/filters/dev.properties
- web/src/main/filters/inspire.properties
- web/src/main/filters/prod.properties
- web/src/main/webResources/WEB-INF/wro.properties
- wro4j/pom.xml
- wro4j/src/main/java/org/fao/geonet/wro4j/DiskbackedCache.java
- wro4j/src/main/java/org/fao/geonet/wro4j/GeonetworkWrojManagerFactory.java
- wro4j/src/test/java/org/fao/geonet/wro4j/DiskbackedCacheTest.java
implemented a cache that writes to disk and uses in-memory caching.  If a resource not in memory then disk is checked.  This allowed caching to cross server restarts.
The caching is configured in wro.properties and dev/prod/inspire.properties.  When in dev mode then the in-memory caching is used otherwise the disk+memory strategy is used.
The cached data is stored in a H2 database, the path of which can be configured in the wro.properties file.  The default is in WEB-INF/wro4j.db
the databases can't currently be shared between webapps but they can be moved out of the webapplication so that when updating the server the same cache files can be used.
If you update the webapp and use the same cache you don't have to worry about the cache having out-of-date files.  The cache stores a hash and …
> WRO 4J Diskbased caching

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/RecordInfo.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/GeonetHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/GeonetParams.java
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/geonetwork.html
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/geonetwork.js
- web/src/main/webapp/xsl/xml/harvesting/geonetwork.xsl
- web/src/main/webapp/xsl/xml/harvesting/geonetwork30.xsl
New option on geoNetwork harvester settings to use the changedate as reference to know if we should update the metadata. 
Less mef.export calls to remote geoNetwork server. The harvester reduces A LOT time spent. In just a couple of seconds, if there are no changes, the harvester ends.
Also, comparison between dates on harvester now is strictly great than. If the dates are exactly the same, right now it returns true, which doesn't make much sense...
> Option to speed up geoNetwork harvester using changeDate

- core/src/main/java/org/geonetwork/http/proxy/HttpProxyServlet.java
Sometimes, browsers (e.g. firefox) automatically add a charset
after the content-type header:
'Content-Type: application/json;charset=UTF-8'
But the ContentType.create(String, String) method expects as first
argument a string without some characters, including ";". We need to
split the string on ";" to get the most significant part of the
content-type before calling ContentType.create().
> HTTP Post - Content type

- web-ui/src/main/resources/catalog/components/edit/FieldsDirective.js
Change the selector for the delete button since it has changed its
structure using an 'a' element. Now it show/hides the 'a' instead the
icon. See issue #953.
> Fix delete icon always shown.

- services/src/main/java/org/fao/geonet/services/metadata/format/XsltFormatter.java
XSLT formatter used to have the following structure:
* root
* schemas_id
* strings
* labels
* codelist
Now it is:
* root
* schemas_id
* schemas_id containing strings
* schemas_id containing labels
* schemas_id containing codelist
It's not meaningfull and breaks compatibility with old formatter.
This restore previous XML structure for XSLT formatters.
2.10.x branch ref: https://github.com/geonetwork/core-geonetwork/blob/2.10.x/web/src/main/java/org/fao/geonet/services/metadata/format/Format.java#L219
> Formatter / Restore XML structure for XSLT formatter.

- core/src/test/resources/org/fao/geonet/kernel/valid-getrecordbyidresponse.iso19139.xml
- services/src/main/java/org/fao/geonet/services/metadata/format/Format.java
- services/src/test/java/org/fao/geonet/services/metadata/format/FormatIntegrationTest.java
- web/src/main/webapp/WEB-INF/config-security/config-security-mapping.xml
This PR proposes to add a new parameter to the `xml.format.{type}` service.
The parameter is `mdpath`, it specifies a xpath to the metadata root element.
If the url is a getRecordById request for example, the XML root element is `csw:GetRecordByIdResponse` so we need to send the `gmd:MD_Metadata` to the formatter. We will use `mdpath=gmd:MD_Metadata` in that case.
> formatter: add optional mdpath parameter in xml.format.{type} service

- common/src/main/java/org/fao/geonet/utils/nio/NioPathHolder.java
- schemas/iso19139/src/main/plugin/iso19139/update-fixed-info.xsl
- web-ui/src/main/resources/catalog/components/edit/geopublisher/GeoPublisherDirective.js
- web-ui/src/main/resources/catalog/components/edit/geopublisher/GeoPublisherService.js
Fixes for GeoPublish workflow
Workflow is:
* upload shapefile zip file
* Publish to Geoserver
* Add WMS/WFS links to Geoserver layer
* Get Suggestions
* Update extent/Thumbnail/spatial info using WMS suggestion
Fixes that needed to be done to make this work:
* Make access == public in update-fixed-info.xsl and GeoPublisherService
* Update GeoPublisherDirective so it checks if there is an extent before trying to show the extent on map
* Update NioPathHolder to not throw an exception when trying to resolve http://...  paths
> Fixes for GeoPublish workflow

- web/pom.xml
Tested at runtime, it does not seem to break navigation (interface still usable, no 404 detected)
> Excluding useless files in bootstrap and font-awesome (#879)

- services/src/test/java/org/fao/geonet/services/metadata/format/XmlViewFormatterTest.java
This was commented out in al other unit tests.
> Commented out write to e:/tmp/view.html

- common/src/test/java/org/fao/geonet/utils/GeonetHttpRequestFactoryTest.java
The values for port are -1 in the GeonetHttpRequestFactory if they are the default port. The CSW test cannot handle :80 or :443 at the end of a URI.
> Ammended defaultPort, cross merge from develop to 3.0.x branch.

- .travis.yml
To speed up development add sudo:false to trigger container based CI. This will cache all maven dependencies.
> Explicit sudo false to trigger container based Travis CI

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFilesystemHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFilesystemParams.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFsHarvesterFileVisitor.java
- web-ui/src/main/resources/catalog/components/search/formfields/FormFieldsDirective.js
- web-ui/src/main/resources/catalog/components/search/formfields/partials/recordTypesCombo.html
- web-ui/src/main/resources/catalog/js/edit/ImportController.js
- web-ui/src/main/resources/catalog/locales/du-editor.json
- web-ui/src/main/resources/catalog/locales/en-core.json
- web-ui/src/main/resources/catalog/locales/en-editor.json
- web-ui/src/main/resources/catalog/locales/es-editor.json
- web-ui/src/main/resources/catalog/locales/fr-editor.json
- web-ui/src/main/resources/catalog/locales/ge-editor.json
- web-ui/src/main/resources/catalog/locales/it-editor.json
- web-ui/src/main/resources/catalog/locales/ko-editor.json
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/filesystem.html
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/filesystem.js
- web-ui/src/main/resources/catalog/templates/editor/import.html
This PR aims to allow catalog admins to harvest subtemplates in local file system harvester.
It adds an option to tell what kind of metadata to create (metadata, template, subtemplate), and extend its capabilities to retrieve the uuid from XML content.
> Filesystem harvest can harvest subtemplates

- web-ui/src/main/resources/catalog/components/search/formfields/FormFieldsDirective.js
- web-ui/src/main/resources/catalog/components/search/formfields/partials/bboxInput.html
- web-ui/src/main/resources/catalog/components/viewer/wps/WpsDirective.js
- web-ui/src/main/resources/catalog/components/viewer/wps/WpsService.js
- web-ui/src/main/resources/catalog/components/viewer/wps/partials/processform.html
Handle bounding box inputs.
Client side validation for mandatory fields.
Exemple use:
```
<gn-wps-process-form
data-uri="wpsUri"
data-process-id="wpsProcessId"
data-defaults="wpsDefaults"
data-map="map"
></gn-wps-process-form>
```
> Improve WPS client with bounding box parameters

- core/src/main/java/jeeves/server/overrides/ConfigurationOverrides.java
- core/src/test/java/jeeves/server/overrides/ConfigurationOverridesTest.java
In geOrchestra, we are willing to stay the closest possible to the GN codebase, as a result, we use the overrides mechanism to resolve configuration customization files. But one limitation of this feature is that using java properties is not possible in the XML file. We are then forced to hardcode the paths in the provided XML overrides, see:
https://github.com/pmauduit/core-geonetwork/blob/georchestra-gn3-3.0.x/web/src/deb/resources/etc/georchestra/geonetwork/config/config-overrides-georchestra.xml
In our case, we generate a debian package for GeoNetwork, so we can guess that the files (for what we called the "georchestra datadir", hosting our configuration files), would end up in the right place (e.g.
/etc/georchestra/geonetwork), but an administrator could define his own datadir …
> Resolving environment variables in overrides

- web/src/main/webapp/xsl/searchform_advanced.xsl
The elements have been translated in the selected language and the dropdown list is now ordered using the translated labels.
> Fixed #1196 groups list missing i18n in advanced search

- core/src/main/java/org/fao/geonet/kernel/AccessManager.java
When there are several (reverse-)proxies between the client and the
server, the header might contain several IP addresses, separated
by a comma. This was leading to NumberFormatException at each client
request, trying to parse for example "109, 10"...
This can also be merged to 3.0.x, i've experienced the issue on 3.0.2.
> Only take the first IP address when parsing client IP.

- web-ui-docs/pom.xml
Fix error during compilation : 
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.11:install-node-and-npm (install node and npm) on project web-ui-docs: Execution install node and npm of goal com.github.eirslett:frontend-maven-plugin:0.0.11:install-node-and-npm failed: A required class was missing while executing com.github.eirslett:frontend-maven-plugin:0.0.11:install-node-and-npm: org/slf4j/helpers/MarkerIgnoringBase
> Update fronted-maven-plugin version to 0.0.23

- web-ui/src/main/resources/catalog/lib/bootstrap.ext/tagsinput/bootstrap-tagsinput-angular.js
The placeholder was showing empty so adding this JQuery function we can add or recuperate the value of an attribute of an element
http://api.jquery.com/attr/ so we ask the values of tagsinput
> Placeholder fix proposed by Juan

- pom.xml
Commons-mail v1.1 has a bug when sending a HtmlEmail and attaching files. In this case the HTML content is attached too and the email appears in blank. Upgrading to commons-email v1.4 fix this.
> Update commons-email to v1.4

- core/src/main/java/org/fao/geonet/kernel/security/ldap/LDAPSynchronizerJob.java
Otherwise they can't be set at all from the web admin interface.
Code copypasted from https://github.com/geonetwork/core-geonetwork/blob/develop/services/src/main/java/org/fao/geonet/services/group/Update.java#L123
> Initialize group labels when importing a group from LDAP (#1294)

- core/src/main/java/jeeves/server/JeevesEngine.java
- core/src/main/java/org/fao/geonet/kernel/search/SearchManager.java
- core/src/main/java/org/fao/geonet/kernel/search/index/LuceneIndexLanguageTracker.java
- wro4j/src/main/java/org/fao/geonet/wro4j/DiskbackedCache.java
- wro4j/src/main/java/org/fao/geonet/wro4j/GeonetworkWrojManagerFactory.java
This improves 2 issues when redeploying GN in the same application server context (e.g. when a new war is deployed onto an older one). The destroy methods are called too lately in the undeploy process, raising some unexpected NPE.
- Better check on the objects to avoid NPEs
- Introducing some methods to destroy extra previously uncleaned objects (related to lucene index locks & h2 usage in wro4j)
This has been successfully tested at runtime on the geOrchestra fork.
> Redeploy improvements

- services/src/main/java/org/fao/geonet/services/user/Update.java
- web-ui/src/main/resources/catalog/js/admin/UserGroupController.js
- web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html
- stop removing all groups if the user is an admin
- don't hide the group selection form and stop unselecting all group profiles
if the current profile is Administrator
Tested locally with a global admin, i'm now able to put him as reviewer in one or several groups, and the groups are persisted/kept if the global admin flag is toggled.
> Allow a global administrator to have other roles in groups (#1297)

- web-ui/src/main/resources/catalog/components/edit/geopublisher/GeoPublisherDirective.js
When the bbox is default (ie [-180, -90, 180, 90]) reprojecting it
to EPSG:4326 triggers an ol3 bug since one of the bounds is -Infinity
See https://github.com/openlayers/ol3/issues/3925
> Check that the md extent is valid before calling fit() (#1308)

- core/pom.xml
Dunno if it'd be better to bump the dep on avalon-framework-impl, if it's the cause of having httpclient 4.3.1 - and i dont know maven enough.
> Enforce dependency on httpclient 4.3.2 to fix SNI support (#1368)

- web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/index-fields.xsl
The // here was picking up all constraints including metadata constraints for each gmd:resourceConstraints in the metadata.
Not an issue in develop/3.0 as this code has been rewritten.
> Only index resource constraints and only index each one once.

- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v2110/2-migrate-default.sql
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v300/SetSequenceValueToMaxOfMetadataAndStats.java
Should fix the remaining migration issues - works for me, tested locally with postgres and 480k+ entries in requests.
> take into account amount of requests when bumping the initial hibernate_sequence value (#1373)

- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/views/default/less/gn_search_default.less
- web-ui/src/main/resources/catalog/views/default/templates/index.html
- web-ui/src/main/resources/catalog/views/default/templates/recordView.html
The social media links located in the footer are hidden when an user looks at a specific metadata. 
Share on social sites such as linkedin and to mailto have been added.
> Add social media links (footer)

- services/src/main/java/org/fao/geonet/services/resources/handlers/DefaultResourceDownloadHandler.java
Otherwise you get two warning lines in logs each time someone visits
a metadata containing thumbnails uploaded before MetadataFileDowloads was added.
I know this code will be changed/revamped in #1385 but in the meantime that really uselessly fills logs at WARNING level, which is the default for geonetwork logger. Another option would be to demote that to DEBUG/INFO level..
> Don't log a warning when an upload request wasnt found

- core/src/main/java/org/fao/geonet/kernel/XmlSerializer.java
That log message is uselessly spamming the logs when geonetwork.datamanager is at info level.
> Demote "XLink Resolver enabled|disabled" log message to debug

- web/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java
- web/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet20/Aligner.java
When harvesting and updating records from GeoNetwork nodes it would be helpful to know which record ID is invalid. This PR adds the ID to the log message.
> Add ID field to invalid metadata records

- web/src/main/webapp/WEB-INF/urlrewrite.xml
Redirects /apps/search/?uuid=xx to /#/metadata/xx
Tested working fine here w/ 3.0.x.
> Add a redirect rule for ExtJS-style permalinks (#808)

- pom.xml
Checked with `mvn dependency:tree`, thx to @pmauduit 
```
-[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.3.1:compile (version managed from 4.3.2)
-[INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.3:compile
+[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.3.2:compile
+[INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.3.1:compile
```
`grep :httpclient` in the output of the dep-tree doesnt yield 4.3.1 anymore.
> Enforce dependency on httpclient 4.3.2 in toplevel pom.xml (#1368)

- schemas/iso19139/src/main/plugin/iso19139/present/csw/own-brief.xsl
- schemas/iso19139/src/main/plugin/iso19139/present/csw/own-full.xsl
- schemas/iso19139/src/main/plugin/iso19139/present/csw/own-summary.xsl
When the CWS files were renamed, the own-brief.xsl, own-full.xsl and
own-summary.xsl kept the old include of iso-XXXXX.xsl files. This update
that reference to gmd-XXXXXX.xsl files.
> Fix the reference to the non-existent iso-....xsl

- core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java
- core/src/main/java/org/fao/geonet/util/MailSender.java
- core/src/main/java/org/fao/geonet/util/MailUtil.java
- harvesters/src/main/java/org/fao/geonet/component/harvester/csw/Harvest.java
- services/src/main/java/org/fao/geonet/services/api/tools/mail/MailApi.java
- services/src/main/java/org/fao/geonet/services/feedback/Insert.java
- services/src/main/java/org/fao/geonet/services/resources/Download.java
- services/src/main/java/org/fao/geonet/services/resources/DownloadArchive.java
- web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v310/migrate-default.sql
Add TLS support, code cleanup in MailUtil, removing the thread in send mail as return of function was not reliable and fixes for mail tester feature, to display the error message returned by the server, not a generic "Precondition Failed" message.
> Support TLS mode for mail server configuration

- pom.xml
1.2.14 ships with rollingPolicy in log4j.dtd
1.2.16 allows to configure rollingPolicy via properties files
Refs: http://stackoverflow.com/questions/5117758/configuring-rollingfileappender-in-log4j & http://stackoverflow.com/a/13037467. Tested 3.0.4-SNAPSHOT working fine with log4j 1.2.17.
> Bump log4j requirement to 1.2.17.

- web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html
- web-ui/src/main/resources/catalog/templates/top-toolbar.html
- web/src/main/webapp/WEB-INF/config-security/config-security-mapping.xml
This PR revert this https://github.com/geonetwork/core-geonetwork/commit/712559e51bfd9b730c82f18303678c95e6be219b commit ( see top-toolbar.html in this PR) in order to make accessible the admin section to any RegisteredUser. 
In this way ant user will be able to change their own details and password. If the user has no higher profile than RegisteredUser will see only itself in the user list but he won't be able to delete himself nor change its own groups assignment.
@fxprunayre is this ok? I couldn't understand if you disabled the link in the topbar due to the fact that a RegisteredUser before wasn't actually able to change its own details or if because he **must not do it**. In the latter case I think it should be at least allowed to change its own password.
> allow user to change its user details and password. close #1258

- web/src/main/webapp/xslt/base-layout-nojs.xsl
- web/src/main/webapp/xslt/common/base-variables.xsl
- web/src/main/webapp/xslt/skin/default/skin.xsl
- web/src/main/webapp/xslt/ui-search/search-nojs.xsl
introduce header/footer for no-js ui
and link each search result to /metadata/{uuid} (urlrewrite can forward this to some formatter for the metadata)
The development indicates a way the layout of angular app can be reused partially (it includes the css from angular app) on the no-js interface. Idea behind improving the no-js interface is triggered from search engine crawlability, but off course no-js users/browsers will also profit
> introduce header/footer for no-js ui

- schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
- schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields-sds.xsl
- schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields.xsl
- schemas/iso19139/src/main/plugin/iso19139/loc/eng/codelists.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/eng/schematron-rules-inspire-sds.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/eng/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/process/sds-add-dataquality.xsl
- schemas/iso19139/src/main/plugin/iso19139/process/sds-add-qualityofservice.xsl
- schemas/iso19139/src/main/plugin/iso19139/process/sds-fix-category.xsl
- schemas/iso19139/src/main/plugin/iso19139/schematron/schematron-rules-inspire-sds.disabled.sch
- schemas/iso19139/src/main/plugin/iso19139/templates/inspire_sds.xml
- schemas/iso19139/src/main/plugin/iso19139/update-fixed-info.xsl
- web-ui/src/main/resources/catalog/components/edit/crsselector/CRSSelector.js
- web-ui/src/main/resources/catalog/components/metadatamanager/EditorXMLService.js
- web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
- web/src/main/webapp/xslt/ui-metadata/form-configurator.xsl
As described in #1445, this PR adds a new tab for editing metadata fields related to the INSPIRE Spatial Data Services (SDS).
Furthermore some improvements to the form-configurator and form-builder have been added (check 
#1467).
_This PR comes from a squashed set of commits and replaces #1468_
> #1445: Implement INSPIRE Spatial Data Services (SDS)

- services/src/main/java/org/fao/geonet/api/tools/i18n/TranslationApi.java
- services/src/main/java/org/fao/geonet/api/tools/mail/MailApi.java
- services/src/main/java/org/fao/geonet/api/tools/migration/MigrationApi.java
In some setup, migration is applied manually. SQL migration can easily be applied to a DB but Java migration steps can't. This PR adds the capability to run a Java migration manually using the API.
> Add API endpoint to call db migration step manually.

- domain/src/main/java/org/fao/geonet/repository/MetadataRepositoryImpl.java
Using parametrized queries instead of building the SQL by hand, this to avoid a potential SQLi. See
https://docs.jboss.org/hibernate/orm/3.2/api/org/hibernate/Query.html
I don't have the time to create an exploit so it might be FUD, but I guess it is a better practice to build the SQL this way in any case.
@Delawen care to review ? (since it was from your code IIRC)
Tests: compilation OK, testsuite on domain OK, not tested at runtime
> domain - fixing SQLi

- domain/src/main/java/org/fao/geonet/domain/HarvesterDataId.java
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v304/migrate-mysql.sql
This avoid that the table is not created by Hibernate in some databases like MySql.
> Rename field 'key' for HarvesterData table as 'key' is a reserved word

- core/src/main/java/org/fao/geonet/kernel/security/shibboleth/ShibbolethUserConfiguration.java
- core/src/main/java/org/fao/geonet/kernel/security/shibboleth/ShibbolethUserUtils.java
- web/src/main/webapp/WEB-INF/config-security/config-security-shibboleth.xml
New filterchain for authentication and some non-autowired objects.
Allow empty header names for very basic SAML authentication (only username).
> Fixing shibboleth configuration for latest changes

- web/src/main/webapp/WEB-INF/config-db/jdbc.properties
- web/src/main/webapp/WEB-INF/config-db/postgres.xml
see similar PR for develop-branch:
https://github.com/geonetwork/core-geonetwork/pull/1510#partial-pull-merging
> replaced static port 5432 in postgres.xml to make port configurable

- .editorconfig
Most of IDE are supporting this .editorconfig file (http://editorconfig.org/). It does not modify existing files (unless we use reformat code action or some autoformat options are enabled) and only applies to new files.
> Add .editorconfig for formatting

- web-ui/src/main/resources/catalog/components/utility/CORSInterceptor.js
Internet Explorer's strings doesn't implement the `startsWith` method. In this PR calls to startsWith have been replaced by `.indexOf('textToSearch', 0) === 0`.
> Fix use of string.startsWith for IE

- web-ui/src/main/resources/catalog/components/ng-skos/templates/skos-concept.html
To add the concept to the keywords, the user hits on the "plus" icon.
To make the concept the current concept, the user hits on the concept's name
> Improve UX of topconcept for hierarchical thesaursus (#278)

- core/src/main/java/jeeves/config/springutil/JeevesContextLoaderListener.java
- core/src/main/java/jeeves/monitor/MonitorManager.java
- core/src/main/java/jeeves/server/JeevesEngine.java
- core/src/main/java/org/fao/geonet/kernel/oaipmh/OaiPmhDispatcher.java
- core/src/main/java/org/fao/geonet/kernel/oaipmh/ResumptionTokenCache.java
- core/src/main/java/org/fao/geonet/kernel/search/LuceneOptimizerManager.java
- core/src/main/java/org/fao/geonet/kernel/search/SearchManager.java
- core/src/main/java/org/fao/geonet/kernel/search/spatial/SpatialIndexWriter.java
- core/src/main/java/org/fao/geonet/util/ThreadPool.java
- core/src/main/resources/config-spring-geonetwork.xml
- domain/src/main/java/org/fao/geonet/domain/SpringScheduledThreadPoolExecutor.java
- domain/src/main/resources/config-spring-geonetwork-parent.xml
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java
- healthmonitor/src/main/java/org/fao/geonet/monitor/webapp/MetricsRegistryInitializerFilter.java
- healthmonitor/src/main/java/org/fao/geonet/monitor/webapp/WebappMetricsFilter.java
- inspire-atom/src/main/java/org/fao/geonet/inspireatom/harvester/InspireAtomHarvesterScheduler.java
- messaging/src/main/java/org/geonetwork/messaging/JMSMessager.java
- messaging/src/main/resources/config-spring-geonetwork-parent.xml
- services/src/main/java/org/fao/geonet/api/records/formatters/cache/FilesystemStore.java
- web/src/main/java/org/fao/geonet/Geonetwork.java
- web/src/main/webapp/WEB-INF/classes/log4j.xml
- web/src/main/webapp/WEB-INF/config-spring-geonetwork-parent.xml
- web/src/main/webapp/WEB-INF/config-spring-geonetwork.xml
- workers/wfsfeature-harvester/src/main/resources/config-spring-geonetwork-jms.xml
- workers/wfsfeature-harvester/src/main/resources/config-spring-geonetwork.xml
- wro4j/src/main/java/org/fao/geonet/wro4j/DiskbackedCache.java
A lot of threads are not stopped when the webapp is stopped. This can
cause trouble if you use the tomcat manager to install and uninstall the
application. Leaving threads behind and running.
To test, I've used:
```
mvn package -Dmaven.test.skip=true && \
docker run -ti --rm -p 8080:8080 \
-v $PWD/web/target/geonetwork.war:/usr/local/tomcat/webapps/geonetwork.war \
tomcat:8.5-jre8
```
You let it start and you hit CTRL+C
> Stop some threads when the webapp is stopped

- web-ui/src/main/resources/catalog/components/metadataactions/RelatedDirective.js
Sometimes scope.md is null and the code in RelatedDirective.js throws an exception
> fixed annoying null pointer issue

- schemas/dublin-core/src/main/plugin/dublin-core/formatter/xsl-view/view.xsl
- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
- services/src/main/java/org/fao/geonet/api/records/formatters/XsltFormatter.java
- web-ui/src/main/resources/catalog/views/default/config.js
- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-functions.xsl
- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-variables.xsl
- web/src/main/webapp/WEB-INF/oasis-catalog.xml
- web/src/main/webapp/xslt/base-layout-nojs.xsl
- web/src/main/webapp/xslt/common/render-html.xsl
- web/src/main/webapp/xslt/skin/default/skin.xsl
- web/src/main/webapp/xslt/ui-search/search-nojs.xsl
This is a replacer for https://github.com/geonetwork/core-geonetwork/pull/1511
It does not create a new formatter but instead improve the existing XSL formatter based on editor-config.xsl for rendering a record. The formatter now provide schema.org tags.
eg.
* get record as full HTML page
http://localhost:8080/geonetwork/srv/api/records/da165110-88fd-11da-a88f-000d939bc5d8/formatters/xsl-view
* get record as a DIV snippet to be emebedded in a page (eg. Angular app)
http://localhost:8080/geonetwork/srv/api/records/da165110-88fd-11da-a88f-000d939bc5d8/formatters/xsl-view?root=div&view=advanced
The formatter is also bind to the nojs XSL template for header and footer to make layout more similar in all HTML pages.
@pvgenuchten , if you could have a look before merging that would be good, I …
> Add schema.org tags in xsl formatter.

- web-ui/src/main/resources/catalog/components/viewer/ViewerDirective.js
- web-ui/src/main/resources/catalog/components/viewer/partials/mainviewer.html
- web-ui/src/main/resources/catalog/locales/en-search.json
- Implemented sycn mode between map viewer and mini map: sync all layers, or sync only background layers (default).
- Added button on the map viewer, to switch between sync modes
.
> Option to sync All layers in the Map Viewer and the Mini Map

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvestError.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/HarvestError.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Harvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geoPREST/Aligner.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geoPREST/Harvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Harvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/oaipmh/Harvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/webdav/Harvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/wfsfeatures/Harvester.java
In the `config/config-service-monitoring.xml` file, a `AbstractHarvesterErrorCounter` is defined, but is never used / incremented. This PR aims to increment the counter whenever it is appropriate.
Note: this metric can give some basic hints on when an issue is encountered at runtime, but it might be interesting to dig in further, maybe defining a counter like this for each defined harvesters ? Also, it is never reset.
Compilation: I was not able to compile it from the `harvesters/` subdirectory, and I needed to compile the whole project.
Tests: runtime tested on geOrchestra (based on 3.0.x branch, but the touched code did not evolve that much between develop and the one)
> harvesters - plugging the harvester error counter

- schemas/config-editor.xsd
- schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-tpl.xsl
- schemas/iso19139/src/main/plugin/iso19139/layout/layout.xsl
- schemas/iso19139/src/main/plugin/iso19139/schema-suggestions.xml
- web-ui/src/main/resources/catalog/style/gn_editor.less
- web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
This mode is applied in flat mode (ie. simple view) or when using an editor configuration with:
```
<xsl xpath="/gmd:MD_Metadata/gmd:identificationInfo/*/gmd:pointOfContact"
mode="iso19139-table-contact"/>
```
Advantages with template mode used in INSPIRE view is that it also support multilingual elements.
@josegar74 Could you review that and see if that also cover your needs on the swedish project ? thanks.
One future improvement would be to be able to configure a table from the config-editor section directly.
> ISO19139 / Add table view mode for contact 

- web-ui/src/main/resources/catalog/js/GnLocale.js
Enhancement of ```GnLocale``` to allow load translations defined in custom views while also loading the default GeoNetwork translations. 
Previously, the only way to add custom translations in a view was to modify the locale files from GeoNetwork, not optimal.
With this change, you can define in your view a snippet like this with the path and name of the locale name to load:
```
module.config(['$LOCALES', function($LOCALES) {
$LOCALES.push('../../catalog/views/sdi/locales/|search');
}]);
```
Maybe there's a better way to do this, but this works and it's quite simple to setup.
@fxprunayre , @fgravin If you can review and merge it if looks fine would be great. Thanks.
> Allow configure locale files in views

- schemas/iso19139/src/main/plugin/iso19139/extract-relations.xsl
In the API /records/{uuid}/related, when requested in JSON, and no thumbnails or onlines are found set these properties to null instead of an empty array to remain consistents with the other fields in the related response.
> Set thumbnails and onlines to null in JSON get related API response 

- schemas/iso19139/src/main/plugin/iso19139/formatter/groovy/iso19139/Functions.groovy
- schemas/iso19139/src/main/plugin/iso19139/formatter/groovy/iso19139/Handlers.groovy
- schemas/iso19139/src/main/plugin/iso19139/formatter/groovy/iso19139/Matchers.groovy
- schemas/iso19139/src/main/plugin/iso19139/index-fields/default.xsl
- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
- web-ui/src/main/resources/catalog/views/default/templates/recordView.html
This feature adds a new directive ```gnLynky``` that can be used to display metadata indexed fields (or any other text) with the following format: ```link|URL|Text``` as an HTML hyperlink:
It contains changes in the indexing of ```gmd:useLimitation``` with ```gmx:Anchor``` that contains ```xlink:href``` attributes with previous format to be displayed with the ```gnLynky``` directive. An example xml snippet with this use case:
```
<gmd:useLimitation>
<gmx:Anchor 
xlink:href="http://www.nationalarchives.gov.uk/doc/open-government-licence/">
Open Government Licence</gmx:Anchor>
</gmd:useLimitation>
```
Similar indexing can be applied to other elements with similar stuff.
Also the groovy formatter has been updated to manage these cases:
> Display links in gmx:Anchor (used for gmd:useLimitation) with hyperlinks in metadata views

- code_quality/findbugs-excludes.xml
Common function handles an illegalArgumentException, nullpointerexception etc by checking the base recursively this is not a bug, and only affected users are Jetty based web containers.
> Added exception for path resolver.

- web/src/main/java/org/fao/geonet/kernel/harvest/harvester/ogcwxs/Harvester.java
- web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/convert/OGCWxSGetCapabilitiesto19119/OGCSOSGetCapabilitiesLayer-to-19139.xsl
Hi!
Simple fix to make GetCapabilities-URLs valid according to [Common XML specification](http://www.opengeospatial.org/standards/common).
As discussed in this email thread [here](http://sourceforge.net/p/geonetwork/mailman/message/34461085/), the harvesting of strict OGC web services is broken in 2.10.x. 
The GetCapabilities URL creation uses ``version``, which is not a valid parameter in GetCapabilities. Service implementations (more concretely: the 52°North SOS) that throw an exception on invalid parameters cannot be harvested (try for example http://sosmet.nerc-bas.ac.uk:8080/sosmet/sos, example request: http://sosmet.nerc-bas.ac.uk:8080/sosmet/sos?service=SOS&request=GetCapabilities&version=1.0.0).
I am open to fix this issue in other development branches (e.g. …
> Fix capabilities URL for OGC WxS harvesters

- schemas/iso19110/src/main/plugin/iso19110/layout/layout-custom-fields.xsl
- schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields-date.xsl
- schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields.xsl
- schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-tpl.xsl
Now use the `isoType` and `xpath` to retireve the right label for fields defined in custom fields xsl. This should use the context defined in the `<element>`  in labels.xml to determine the right label to choose.
> Add context to the label search for custom fields and templates

- core/src/main/java/org/fao/geonet/listeners/security/CheckUsername.java
- domain/src/main/java/org/fao/geonet/domain/SchematronCriteria.java
- web-ui/src/main/resources/catalog/components/admin/schematron/SchematronEditCriteriaDirective.js
- web-ui/src/main/resources/catalog/components/admin/schematron/partials/criteria-viewer.html
- web-ui/src/main/resources/catalog/js/admin/SchematronAdminController.js
- web-ui/src/main/resources/catalog/style/gn_admin.less
- web-ui/src/main/resources/catalog/templates/admin/metadata/schematron.html
When a schematron criteria (in the admin console - Metadata and Templates - Schematron) was of type `XPATH `or `ALWAYS_ACCEPT` it didn't send the right criteria value to the server to be save. Now, if the criteria type is not using a typeahead control, it uses the criteria type value to generate the actual value for the criteria replacing `@@value@@` by the valueui in the criteriaType value field.
Also some style fixes have been made:
Before
After
> Fix empty SchematronCriteria empty value

- web-ui/src/main/resources/catalog/js/admin/UserGroupController.js
When creating a new user on Internet Explorer 11, the user list won't be updated, as if the user didn't exist at all. Working fine on any other browser.
Tried to: Log out/in again, close browser, clear browser caché, clear wro4j cache, reboot client & server... and problem persisted. It turns out to be an IE11 "issue" with JSON AJAX queries: http://stackoverflow.com/questions/16098430/angular-ie-caching-issue-for-http
Forcing cache headers solved it.
> Update user list on IE11 (admin interface)

- schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
Fixes Vertical Extent form elements, which were lacking a section title and were showing integer values as multilingual fields:
> Fix vertical extent on editor's default view

- schemas/iso19139/src/main/plugin/iso19139/index-fields/default.xsl
- schemas/iso19139/src/main/plugin/iso19139/index-fields/language-default.xsl
Don't concatenate "::" when no codeSpace is present:
> Fix CRS labels starts with :: on metadata view

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFilesystemHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFilesystemParams.java
- schemas/iso19139/src/main/plugin/iso19139/loc/nor/labels.xml
- web-ui/src/main/resources/catalog/locales/ca-admin.json
- web-ui/src/main/resources/catalog/locales/cz-admin.json
- web-ui/src/main/resources/catalog/locales/du-admin.json
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/locales/es-admin.json
- web-ui/src/main/resources/catalog/locales/fi-admin.json
- web-ui/src/main/resources/catalog/locales/fr-admin.json
- web-ui/src/main/resources/catalog/locales/ge-admin.json
- web-ui/src/main/resources/catalog/locales/it-admin.json
- web-ui/src/main/resources/catalog/locales/ko-admin.json
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/filesystem.html
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/filesystem.js
- web/src/main/webapp/xsl/xml/harvesting/filesystem.xsl
Now, the user can configure a local harvester to run a script before the
files are harvested. For example, this can be used to do a rsync of a remote
directory.
Fix bad merge resolution in ISO19139 Norvegian labels
> Add beforeScript in the local harvester

- core/src/main/java/jeeves/config/springutil/MultiNodeAuthenticationFilter.java
- core/src/main/java/org/fao/geonet/web/DefaultLanguage.java
- core/src/main/java/org/fao/geonet/web/LocaleRedirects.java
- pom.xml
- web/src/main/webResources/WEB-INF/config.properties
- web/src/main/webResources/WEB-INF/spring-servlet.xml
- web/src/main/webapp/WEB-INF/config-spring-geonetwork.xml
* Add compile time option to set default language (default is eng).
* Add an option to force redirection to the default language.
Define if redirection should ignore HTTP headers,
Cookie or URL parameters. Set it to true to always redirect
to the default language. This is useful when you only have one language supported.
Related to #1579 (@josegar74 could you have a look ? Thanks)
> Default language improvement.

- core/src/main/java/org/fao/geonet/constants/Geonet.java
- core/src/main/java/org/fao/geonet/kernel/DataManager.java
This pull request allows to define a xslt process in the metadata schemas in a file `inflate-metadata.xsl` to add elements to the metadata before it's edited.
Note that in most cases, a similar stuff can be accomplished with the proper configuration of the editor fields, the inflate option is only required in some advanced cases where the editor configuration is not suitable. 
Usually the inflate process, will require a deflate process to remove the added elements for example if are left empty by the user and can cause validation issues in that case. This deflate can be done in the  `update-fixed-info.xsl`.
**An example use case**
The metadata requires these elements:
* 2 gmd:spatialResolution with an inner element gmd:equivalentScale
* 2 gmd:spatialResolution with an inner element …
> Add optional inflate mechanism to apply when the metadata is edited

- common/src/main/java/org/fao/geonet/utils/FilePathChecker.java
- services/src/main/java/org/fao/geonet/services/feedback/AddLimitations.java
- services/src/main/java/org/fao/geonet/services/logo/Add.java
- services/src/main/java/org/fao/geonet/services/logo/Delete.java
- services/src/main/java/org/fao/geonet/services/logo/Set.java
- services/src/main/java/org/fao/geonet/services/mef/ImportWebMap.java
- services/src/main/java/org/fao/geonet/services/resources/Download.java
- services/src/main/java/org/fao/geonet/services/resources/DownloadArchive.java
- services/src/main/java/org/fao/geonet/services/resources/Get.java
- services/src/main/java/org/fao/geonet/services/resources/handlers/DefaultResourceRemoveHandler.java
- services/src/main/java/org/fao/geonet/services/thesaurus/Upload.java
Unify file path checks done in several services to avoid absolute or relative paths using `..` characters.
There's room for further improvements like review of the exceptions throws, additional checks if required. But I guess is a starting point.
The PR is for 3.0.x, will be added to 3.2.x when merging 3.0.x into 3.2.x
> File path checks improvements

- web-ui/src/main/resources/catalog/components/metadataactions/RelatedResourcesService.js
- web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
- File downloads are assigned different icons according to the content.
- OWS services are assigned a stack icon, with overlaid text describing the service.
- Everything that is not matched is assigned a generic link icon
> - Extended support for mime type icons:

- web-ui/src/main/resources/catalog/components/catalog/CatalogService.js
- web-ui/src/main/resources/catalog/components/edit/crsselector/CRSSelector.js
- web-ui/src/main/resources/catalog/components/edit/directoryentryselector/DirectoryEntrySelector.js
- web-ui/src/main/resources/catalog/components/edit/geopublisher/GeoPublisherDirective.js
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcService.js
- web-ui/src/main/resources/catalog/components/edit/organisationentryselector/OrganisationEntrySelector.js
- web-ui/src/main/resources/catalog/components/edit/templatefield/TemplateFieldDirective.js
- web-ui/src/main/resources/catalog/components/thesaurus/ThesaurusDirective.js
- web-ui/src/main/resources/catalog/js/edit/DirectoryController.js
- web-ui/src/main/resources/catalog/js/edit/EditorController.js
- web-ui/src/main/resources/catalog/locales/du-editor.json
- web-ui/src/main/resources/catalog/locales/en-editor.json
- web-ui/src/main/resources/catalog/templates/info.html
Display a link to the XML editor if a error occurs while saving the editor form contents. See attached screenshot.
Duplicates #1804 for branch 3.2.x.
> Display a link to the XML editor if an error occurs

- web-ui/src/main/resources/catalog/components/thesaurus/ThesaurusDirective.js
Fix a JS error when clearing the typeahead content and other when synchronizing the typeadhead contents with the Angular JS model.
```
Uncaught Error: [ng:cpi] Can't copy! Source and destination are identical.
http://errors.angularjs.org/1.5.2/ng/cpi
at angular.js:68
at Object.copy (angular.js:868)
at HTMLInputElement.<anonymous> (ThesaurusDirective.js:391)
at HTMLInputElement.dispatch (jquery-2.0.3.js:4676)
at HTMLInputElement.elemData.handle (jquery-2.0.3.js:4360)
at Object.trigger (jquery-2.0.3.js:4594)
at HTMLInputElement.<anonymous> (jquery-2.0.3.js:5119)
at Function.each (jquery-2.0.3.js:590)
at init.each (jquery-2.0.3.js:237)
at init.trigger (jquery-2.0.3.js:5118)
```
```
TypeError: Cannot create property 'highlight' on string ''
at typeahead.bundle.js:1729
at String.reverseArgs …
```
> Fixes some JS errors in the thesaurus directive

- services/src/main/java/org/fao/geonet/api/ApiParams.java
- services/src/main/java/org/fao/geonet/api/processing/XslProcessApi.java
- services/src/main/java/org/fao/geonet/api/processing/XslProcessUtils.java
API change:
* GET GET /srv/api/0.1/processes/{process}
Return results of the selected records after processing.
Usually process return XML. All processed records are combined under
a ```<preview/>``` root tag.
Process could also return text output if process name ends-with ```.csv```.
In such case, output is return with appropriate headers.
The CSV mode is usefull when having to create some kind of reports based
on the content of the metadata which requires advanced XPath filters
(eg. table of quality measures).
> Processing / Add the capability to preview process results.

- schemas/config-editor.xsd
- schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
- schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-tpl.xsl
In config-editor.xml, define which elements should be displayed using table
in flat mode views (ie. this does not apply to advanced view).
Related work: https://github.com/geonetwork/core-geonetwork/pull/1635
In ISO19139, table is used for contact, online source, coupled resource, format, other locale.
> Editor / Make table layout configurable

- core/src/main/java/org/fao/geonet/util/PasswordUtil.java
- domain/src/main/java/org/fao/geonet/domain/UserSecurity.java
- services/src/main/java/org/fao/geonet/api/users/UsersApi.java
If a UserAdmin user reset the password of and old user with an old password hash (SHA-1) he is not able to login because update password method sets the hash using SHA-256, but the column `security` still contains `UPDATE_HASH_REQUIRED`.
This PR removes that string from `security` after updating the password.
It also fixes some errors reported by Findbugs.
> User unable to login after password reset made by other user using the admin console

- web-ui/src/main/resources/catalog/components/search/resultsview/SelectionDirective.js
The selected count badge in editor dashboard show random values after a reload if there are selected records.  
Fix:
The value returned by `gnSearchManagerService.selected()` is an array. Changed `parseInt(res, 10)` by `res.length`
> Wrong selected count in badge in the editor dashboard

- web/src/main/webapp/xslt/common/functions-metadata.xsl
Instead return the first match and print a warning in the log.
> Don't fail if multiple labels match name and context

- core/src/main/java/org/fao/geonet/util/XslUtil.java
Some servers return a 500 error (incorrectly) when they don't support the HEAD method used to test if a metadata linked resource exists so this commit add this error code to the ones that launch a new GET
request if HEAD is not supported.
This change can be applied to 3.0.x branch too.
> Retry the request as POST when HEAD fails in getUrlStatus

- schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
Instead of creating a new variable on the /root/gui/setting/system subtree as suggested in #1849, let's just use the existing serviceInfo.
> #1849: Enable INSPIRE view in config-editor.xml according to settings

- services/src/main/java/org/fao/geonet/api/records/attachments/AttachmentsActionsApi.java
- services/src/main/java/org/fao/geonet/api/records/editing/BatchEditsApi.java
- services/src/main/java/org/fao/geonet/api/registries/DirectoryApi.java
- services/src/main/java/org/fao/geonet/api/registries/DirectoryUtils.java
- services/src/main/java/org/fao/geonet/api/site/SiteApi.java
- services/src/main/java/org/fao/geonet/api/status/StatusApi.java
- services/src/main/java/org/fao/geonet/api/users/PasswordApi.java
- services/src/main/java/org/fao/geonet/api/users/RegisterApi.java
- services/src/test/java/org/fao/geonet/api/directory/DirectoryApiTest.java
- services/src/test/java/org/fao/geonet/api/site/SiteApiTest.java
- services/src/test/java/org/fao/geonet/api/status/StatusApiTest.java
- services/src/test/java/org/fao/geonet/services/metadata/BatchEditsServiceTest.java
This pull request removes the usage of problematic `ServiceContext.get()` in controllers from the `org.fao.geonet.api` package. 
Still some usages in `FilesystemStore` and `ResourceLoggerStore` that require some review/refactoring.
> Remove usage of ServiceContext.get() in api methods

- csw-server/src/main/java/org/fao/geonet/component/csw/GetRecords.java
- csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/SearchController.java
- csw-server/src/test/java/org/fao/geonet/component/csw/CswGetRecords_Test.java
```
<?xml version="1.0"?>
<csw:GetRecords xmlns:csw="http://www.opengis.net/cat/csw/2.0.2"
xmlns:gmd="http://www.isotc211.org/2005/gmd"
service="CSW" version="2.0.2" startPosition="199"
resultType="results">
<csw:Query typeNames="gmd:MD_Metadata">
<csw:Constraint version="1.1.0">
<Filter xmlns="http://www.opengis.net/ogc"/>
</csw:Constraint>
</csw:Query>
</csw:GetRecords>
```
Return an exception saying that startPosition <= matching records:
```
<?xml version="1.0" encoding="UTF-8"?>
<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2.0" xsi:schemaLocation="http://www.opengis.net/ows http://schemas.opengis.net/ows/1.0.0/owsExceptionReport.xsd">
<ows:Exception exceptionCode="InvalidParameterValue" …
```
> CSW / Adding some checks on startPosition and nextRecord

- web-ui/src/main/resources/catalog/components/edit/validationreport/ValidationReportDirective.js
Remove the loading spinner from the _Validate_ button if there is any error while saving or validating.
> Hide the loading spinner of validate button on error

- web-ui/src/main/resources/catalog/style/gn_editor.less
> Fix#1907 - Update style of the container editor (margin-top)

- web-ui/src/main/resources/catalog/js/admin/HarvestSettingsController.js
* Don't make a request when there is no URL in the input box.
* Wait 750 ms after the last url value change to make the capabilities request.
Fix conflicts found in PR #1886.
> Improve CSW getCapabilities request in harvesters

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Harvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Harvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/oaipmh/Harvester.java
Issue #1889. 
If a remote node (eg. CSW, OAI - also issue if remote server return 0 record alignment is not made) returns an error, the harvester is aligning the content. In this case, it drops all because the remote node returned an error.
eg. https://github.com/geonetwork/core-geonetwork/blob/develop/harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Harvester.java#L160
Do not align in case of error, and let's see on next run if there is still an error or the remote is back online.
> Harvester / Do not align a node returning an error

- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
Align hidden textarea to top of page
Without "top" attribute textarea started after the 100% height div
Specifying position makes sense of absoulte positioning
Closes #1923
> Fix scrollbar issue

- web-ui/src/main/resources/catalog/components/search/resultsview/ResultsviewDirective.js
- web-ui/src/main/resources/catalog/components/viewer/ViewerDirective.js
- web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextService.js
- web-ui/src/main/resources/catalog/style/gn.less
- web-ui/src/main/resources/catalog/style/gn_search.less
- web-ui/src/main/resources/catalog/views/default/directives/partials/linksbtn.html
- web-ui/src/main/resources/catalog/views/default/module.js
- web-ui/src/main/resources/catalog/views/default/templates/footer.html
- web-ui/src/main/resources/catalog/views/default/templates/index.html
This PR fixes a bug that occurs when a map is asked to fit an extent while not being displayed (ie. the map is in another tab).
This happens on two occasions: 
* Viewer map: when the OWS context is loaded (first arrival on the website)
* Search map: when search results are fetched
In order to fix this, the computed extent is now systematically saved in a `lastExtent` property on the respective map object. This is then used to display maps properly when switching tabs.
Other UI fixes are:
* the footer for the default view is now factorized in a separate template (same as top toolbar)
* the layers synchronization feature between the two maps was causing a bug and has been fixed
* links list in the search results view now use the name of the link when a description is not available
* …
> Map extent fix when loaded from another view + minor UI fixes

- core/src/main/java/org/fao/geonet/util/XslUtil.java
- inspire-atom/src/main/java/org/fao/geonet/inspireatom/util/InspireAtomUtil.java
- inspire-atom/src/main/java/org/fao/geonet/services/inspireatom/AtomPredefinedFeed.java
- inspire-atom/src/main/java/org/fao/geonet/services/inspireatom/AtomServiceDescription.java
- schemas/iso19139/src/main/plugin/iso19139/convert/ATOM/inspire-atom-feed.xsl
- schemas/iso19139/src/main/plugin/iso19139/convert/ATOM/iso19119ToAtomFeed.xsl
- web/src/main/webapp/WEB-INF/config-security/config-security-mapping.xml
Based on the work of @fgravin (https://github.com/fgravin/core-geonetwork/tree/atomFeed)
> #1899: INSPIRE Pre-defined ATOM feeds

- services/src/main/java/org/fao/geonet/api/related/Related.java
- web-ui/src/main/resources/catalog/components/metadataactions/RelatedDirective.js
- web-ui/src/main/resources/catalog/components/search/resultsview/gridRelated.js
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid.html
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/style/gn_search.less
- web-ui/src/main/resources/catalog/views/default/module.js
- web-ui/src/main/resources/catalog/views/default/templates/gridRelated.html
- web-ui/src/main/resources/catalog/views/default/templates/results.html
- A new service is created to get all related from a set of metadatas instead of getting them one metadata by one: `api/related`
Reduce the number of requests and processes to get all relations in metadatas search result grid.
Exemple: 
http://localhost:8080/geonetwork/srv/api/related?type=parent&type=children&type=services&type=datasets&uuid=e21e09f13a47ae498cf9c891cf4ac6b58f8cf873&uuid=f232e24f9c219d67c6fda40976062cb14b659e7d&uuid=0cab0c4c632c8e220f1a66c9150c6a55c4990fcc
- Add a directive`gnGridRelated`  in the grid result to display relations of all metadatas. The metadatas relations are fetched from an angular value that contains all relations of the metadata list, returned by the new service (done in `gnGridRelatedQuery`).
New settings in angular api for the ui :
```js
mods: { …
```
> Add a new service to get all related from a set of metadatas

- web-ui/src/main/resources/catalog/components/UrlUtilsService.js
- web-ui/src/main/resources/catalog/components/utility/CORSInterceptor.js
CORS errors and network/server errors can't be distinguished by the browser JS engine.
CORS errors usually happen when the requested URL is in other domain/protocol that
the current page current one.
With this commit requests made to the same origin that GN that result in an error will
not be retried using the proxy and the request will be rejected with the actual response
value from the server.
If the request is for another origin it will be retried using the proxy.
> Don't use proxy for URL with the same origin (#1943)

- core/src/main/java/org/fao/geonet/kernel/DataManager.java
This allows to edit the uuid to users in the metadata editor and get the value assigned in the xml, otherwise the ufo process, keeps the original uuid.
Most of the schemas have readwriteUuid disable as expected, so should not cause any side effect.
> Send to ufo xslt the uuid from the metadata for schemas that have enabled the flag readwriteUuid.

- web-ui/src/main/resources/catalog/components/common/ows/OWSService.js
- web-ui/src/main/resources/catalog/components/viewer/baselayerswitcher/partials/baselayerswitcher.html
- web-ui/src/main/resources/catalog/components/viewer/gfi/GetFeatureInfoDirective.js
- web-ui/src/main/resources/catalog/components/viewer/layermanager/LayerManagerDirective.js
- web-ui/src/main/resources/catalog/components/viewer/layermanager/partials/layermanageritem.html
- web-ui/src/main/resources/catalog/components/viewer/ncwms/NcwmsDirective.js
- web-ui/src/main/resources/catalog/components/viewer/ncwms/NcwmsService.js
- web-ui/src/main/resources/catalog/components/viewer/ncwms/partials/ncwmstools.html
- web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextService.js
- web-ui/src/main/resources/catalog/components/viewer/wfs/WfsDirective.js
- web-ui/src/main/resources/catalog/components/viewer/wfsfilter/WfsFilterDirective.js
- web-ui/src/main/resources/catalog/style/gn_viewer.less
- web/src/main/webapp/WEB-INF/data/data/resources/map/config-viewer.xml
Change the way the layers are managed from `OWSContext`.
Initially, we called all getCapabilities and wait for all responses in the `$q.all()` but if a response is very long, then the layers are not displayed for a while.
We now process all layers as they come from the context.
During loading, an empty loading layer is added to the map, to keep layer position in the map and for the layermanager to display it while loading.
On response, this fake layer is either set to null or replaced in the map by the real one.
This is done for both background and top layers. A spinner is diplayed while loading.
Error are managed.
> Continous Layertree loading

- schemas/iso19139/src/main/plugin/iso19139/index-fields/default.xsl
- schemas/iso19139/src/main/plugin/iso19139/index-fields/language-default.xsl
- web-ui/src/main/resources/catalog/components/catalog/CatalogService.js
- web-ui/src/main/resources/catalog/views/default/templates/recordView.html
- web/src/main/webapp/WEB-INF/config-lucene.xml
This PR has two objectives regarding a metadata CRS:
* Handle CRS codes encoded with a `<gmx:Anchor>` element instead of `<gco:CharacterString>`
* Provide additional info on the CRS to the frontend:
* Name
* Url
The template `recordView.html` has been adjusted to reflect this change.
This has been tested with the following XML structure:
```xml
<gmd:referenceSystemInfo>
<gmd:MD_ReferenceSystem>
<gmd:referenceSystemIdentifier>
<gmd:RS_Identifier>
<gmd:code>
<gmx:Anchor xlink:href="http://www.opengis.net/def/crs/EPSG/0/2154" xlink:title="RGF93 - Lambert 93">2154</gmx:Anchor>
</gmd:code>
<gmd:codeSpace>
<gco:CharacterString>EPSG</gco:CharacterString>
</gmd:codeSpace>
</gmd:RS_Identifier>
</gmd:referenceSystemIdentifier>
</gmd:MD_ReferenceSystem>
</gmd:referenceSystemInfo>
```
> Rework how metadata CRS are indexed & displayed in MD view

- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
- web-ui/src/main/resources/catalog/components/viewer/wfsfilter/WfsFilterDirective.js
- web-ui/src/main/resources/catalog/components/viewer/wfsfilter/partials/wfsfilterfacet.html
- web-ui/src/main/resources/catalog/locales/en-core.json
- web-ui/src/main/resources/catalog/locales/fr-core.json
This PR improves the usability of the 'filter' button in the map viewer:
The button will be greyed out if the currently selected filters have already been applied (this state is stored in `scope.previousFilterState`.
The saved state include bounding box selection & full text search.
> Disable or enable 'filter' button based on previous filter state

- web-ui/src/main/resources/catalog/components/search/facets/partials/dimension-facet-category.html
- web-ui/src/main/resources/catalog/style/gn_search.less
Facet label CSS was switched to using flexbox in order to better behave when the screen is narrowed. Text ellipsis is not done with angular filter anymore, but with the CSS `text-overflow: ellipsis` property.
Before:
After:
> Correct facet label rendering in search view

- core/pom.xml
- core/src/main/resources/config-spring-geonetwork.xml
- messaging/pom.xml
- messaging/src/main/resources/config-spring-geonetwork-parent.xml
- pom.xml
- schemas-test/src/main/webapp/WEB-INF/config.properties
- services/src/main/webapp/WEB-INF/config.properties
- web/pom.xml
- web/src/main/webResources/WEB-INF/config-db/defaultJdbcDataSource.xml
- web/src/main/webResources/WEB-INF/config-spring-geonetwork.xml
- workers/wfsfeature-harvester/pom.xml
- workers/wfsfeature-harvester/src/main/resources/config-spring-geonetwork.xml
Proposal: Add a pom property to configure property file location for the app and the db config. 
```
-  <context:property-placeholder location="WEB-INF/config.properties"
+  <context:property-placeholder location="${app.properties}"
```
This is useful when you have the need to move configuration outside the webapp.
Then you can set the location with full file path or using env variables like
```
location="file:/${geonetwork.dir}/jdbc.properties"
or
location="file:/c:/datadir/jdbc.properties"
```
Remove usage of "classpath*:" prefix which was not complaining if no file found but was unclear about which config files are required for each module.
See https://github.com/geonetwork/core-geonetwork/issues/1995
Runtime is ok, test are ok.
> App & db config properties file location set by maven build

- schemas/config-editor.xsd
- schemas/iso19139/src/main/plugin/iso19139/layout/layout.xsl
- schemas/iso19139/src/main/plugin/iso19139/layout/utility-fn.xsl
- schemas/iso19139/src/main/plugin/iso19139/update-fixed-info.xsl
Currently multilingual metadata records in ISO19139, encode translation using the following form (a):
```
<gmd:title xsi:type="gmd:PT_FreeText_PropertyType">
<gco:CharacterString>Carte indicative des dangers eaux</gco:CharacterString>
<gmd:LocalisedCharacterString locale="#EN">Water risk information map</gmd:LocalisedCharacterString>
```
Another XSD valid encoding (b) would be to use only PT_FreeText:
```
<gmd:title xsi:type="gmd:PT_FreeText_PropertyType">
<gmd:LocalisedCharacterString locale="#FR">Carte indicative des dangers eaux</gmd:LocalisedCharacterString>
<gmd:LocalisedCharacterString locale="#EN">Water risk information map</gmd:LocalisedCharacterString> …
```
> ISO19139 / Use PT_FreeText element for default language.

- messaging/src/main/resources/config-spring-geonetwork-parent.xml
- pom.xml
- web/pom.xml
- web/src/main/webResources/WEB-INF/web.xml
- workers/wfsfeature-harvester/src/main/resources/config-spring-geonetwork-jms.xml
- workers/wfsfeature-harvester/src/main/resources/config-spring-geonetwork.xml
miss integration tests.
default is no messaging, no camel, no activemq, no es.
mvn -Pes
or
setting "es.spring.profile" maven property to "es" to activate.
> [#2018] use spring profile to allow discard of camel/es.

- common/src/main/java/org/fao/geonet/exceptions/BadParameterEx.java
- core/src/test/resources/WEB-INF/config-lucene.xml
- core/src/test/resources/org/fao/geonet/kernel/sub-OnlineResource.xml
- services/src/main/java/org/fao/geonet/api/records/MetadataValidateApi.java
- services/src/test/java/org/fao/geonet/api/records/MetadataValidateApiTest.java
This PR allow manual validation of a subtemplate.
Validation of a subtemplate does not follow validation rules as for metadata and templates. It is done manually by the administrator who set it to `true` or `false`.
The metadatavalidate service has been updated to receive a `isvalid` param to validate only a subtemplate.
The validation will be set in the directory manager and will provide information about the state of a subtemplate to the users.
Thanks @cmangeat for contribution.
> Subtemplate validation service

- core/src/main/java/org/fao/geonet/MetadataResourceDatabaseMigration.java
- core/src/main/java/org/fao/geonet/kernel/mef/Importer.java
- services/src/test/java/org/fao/geonet/api/records/attachments/MetadataResourceDatabaseMigrationTest.java
- services/src/test/resources/org/fao/geonet/api/records/attachments/record-with-old-links.xml
* Fix Importing MEF file with thumbnails doesn't set the proper url in the xml used since 3.2.x #1730
* Fix links which may have been containing "//"
> ISO19139 / On import update old style links to graphic overview and online resources.

- web-ui/src/main/resources/catalog/js/edit/DirectoryController.js
- web-ui/src/main/resources/catalog/style/gn_editor.less
- web-ui/src/main/resources/catalog/templates/editor/directory.html
See discussions on https://github.com/geonetwork/core-geonetwork/pull/2045
* Pagination is hidden and a message is given when no entry found
* Fix on entry types not showing if only templates are available
* Separated delete icon & used `fa-times` instead of `fa-trash`
* Do not show "Associated Metadata" menu if XLink resolution is not enabled in app settings
* Improve template dropdown list readability
* Fixed icon colors:
> Minor Directory UI improvements following suggestions

- web-ui/src/main/resources/catalog/js/edit/EditorController.js
When editing a document, click "close" might provoke an unintended and inconsistent behaviour across browsers.
Now the code will only attempt to close the tab if it has no history. Here is a comparison of behaviors across browsers:
Current:
| browser |  close editor (main tab)  |  close editor (new tab) |
| -----------| -----------------------------------------| -------------------------------------------------------------|
| edge / ie 11 |  ask user to confirm tab close | ask user to confirm tab close |
| firefox | go back to editor home | go back to editor home |
| chrome/chromium | go back to editor home | close tab without prompt |
With this PR:
| browser |  close editor (main tab)  |  close editor (new tab) |
| -----------| -----------------------------------------| …
> MD editor fix when closing editor

- web-ui/src/main/resources/catalog/components/common/map/mapService.js
- web-ui/src/main/resources/catalog/components/common/map/print/PrintMapDirective.js
- web-ui/src/main/resources/catalog/components/common/map/print/PrintMapService.js
- web-ui/src/main/resources/catalog/components/viewer/localisation/LocalisationDirective.js
- web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextService.js
- web-ui/src/main/resources/catalog/components/viewer/wmsimport/WmsImportDirective.js
This PR enables support of other projection than `EPSG:3857`.
The active projection will be the one detected in the owscontext.
A context like:
```xml
<ows-context:General>
<ows:BoundingBox crs="EPSG:4326">
<ows:LowerCorner>-180.0 -90.0</ows:LowerCorner>
<ows:UpperCorner>180.0 90.0</ows:UpperCorner>
</ows:BoundingBox>
</ows-context:General>
```
will load the map viewer in `EPSG:4326`.
> Enable custom projection in map viewer

- core/src/main/java/org/fao/geonet/kernel/DataManager.java
- web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/js/edit/BatchEditController.js
- web-ui/src/main/resources/catalog/js/edit/EditorBoardController.js
- web-ui/src/main/resources/catalog/js/search/SearchController.js
- web-ui/src/main/resources/catalog/locales/en-search.json
- web-ui/src/main/resources/catalog/templates/editor/batchedit.html
- web-ui/src/main/resources/catalog/templates/editor/editorboard.html
- web-ui/src/main/resources/catalog/views/default/module.js
- web-ui/src/main/resources/catalog/views/default/templates/home.html
- web-ui/src/main/resources/catalog/views/default/templates/searchForm.html
Restrict the search results to the metadata with status `UNKNOWN`, `DRAFT`, `APPROVED`, `SUBMITTED` or `REJECTED`. To allow the search of the `RETIRED` metadata a checkbox is added to the advanced search form.
The `_status=0 or 1 or 2 or 4 or 5` filter is added to the search query unless the checkbox _Show retired metadata_ is checked. This filter is always added to the initial search to to get the records count in the main page and the newest and most popular records search.
If the workflow has not been ever enabled for a record there is no `_status` field in the index for it.  This change add `_status=0` _UNKNOWN_ to each record to allow the search filter. So a **full reindex is required after this change to show the metadata without workflow**.
> Don't show RETIRED metadata in the search results by default

- web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
- web-ui/src/main/resources/catalog/components/viewer/ViewerDirective.js
- web-ui/src/main/resources/catalog/components/viewer/graticule/GraticuleDirective.js
- web-ui/src/main/resources/catalog/components/viewer/partials/mainviewer.html
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
This PR extends the `GraticuleDirective` by adding a mode where a WMS service is used instead of software rendering with OpenLayers.
A setting has been added in the admin console too.
> Adds support for WMS layer in graticule directive

- web-ui/src/main/resources/catalog/components/common/map/print/PrintMapDirective.js
- web-ui/src/main/resources/catalog/components/viewer/ViewerModule.js
- web-ui/src/main/resources/catalog/components/viewer/ViewerService.js
- web-ui/src/main/resources/catalog/components/viewer/geometry/GeometryDirective.js
- web-ui/src/main/resources/catalog/components/viewer/geometry/GeometryModule.js
- web-ui/src/main/resources/catalog/components/viewer/geometry/GeometryService.js
- web-ui/src/main/resources/catalog/components/viewer/geometry/partials/geometrytool.html
- web-ui/src/main/resources/catalog/components/viewer/partials/mainviewer.html
- web-ui/src/main/resources/catalog/components/viewer/wps/WpsDirective.js
- web-ui/src/main/resources/catalog/components/viewer/wps/WpsService.js
- web-ui/src/main/resources/catalog/components/viewer/wps/partials/processform.html
- web-ui/src/main/resources/catalog/js/jsonix/OWC_0_3_1.js
- web-ui/src/main/resources/catalog/js/jsonix/OWS_1_1_0.js
- web-ui/src/main/resources/catalog/js/jsonix/WPS_1_0_0.js
- web-ui/src/main/resources/catalog/lib/jsonix/jsonix/Jsonix-all.js
- web-ui/src/main/resources/catalog/lib/jsonix/jsonix/Jsonix-min.js
- web-ui/src/main/resources/catalog/style/gn_viewer.less
- web/src/main/webapp/xslt/base-layout-cssjs-loader.xsl
This PR adds support for `ComplexData` inputs with a new directive that allows the user to draw shapes according to the format specified. Experimental support has also been added for profile graph display in the viewer.
This feature has been developed for a specific WPS service and may not work with others, although it can probably be expanded easily.
Also contains a fix with `PrintMapDirective` giving an error on page load.
> Improve WPS tool & handle complex input

- schemas/config-editor.xsd
- schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
- schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields-keywords.xsl
- web-ui/src/main/resources/catalog/components/thesaurus/ThesaurusDirective.js
- web-ui/src/main/resources/catalog/components/thesaurus/partials/keywordselector.html
Add configuration in the editor to make thesaurus fields a simple field instead of fieldset.
> Editor / Keyword input as simple field (ie. without fieldset).

- domain/src/test/java/org/fao/geonet/repository/UserRepositoryTest.java
there are tests which expects users list to be ordered given their names
and names to be ordered given their creation order: the later a test user
is created, the later it has to appear in ordered users list, the problem
is that "9" is greater than "10", whereas "09" is smaller than "10".
> avoid randomly failing test

- schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
- web-ui/src/main/resources/catalog/components/edit/directoryentryselector/DirectoryEntrySelector.js
- web-ui/src/main/resources/catalog/components/edit/directoryentryselector/partials/directoryentrylistselector.html
- web-ui/src/main/resources/catalog/components/edit/directoryentryselector/partials/directoryentryselector.html
- web-ui/src/main/resources/catalog/components/search/searchmanager/partials/searchresults.html
- web-ui/src/main/resources/catalog/js/edit/DirectoryController.js
- web-ui/src/main/resources/catalog/locales/en-core.json
- web-ui/src/main/resources/catalog/locales/en-editor.json
- web-ui/src/main/resources/catalog/style/gn.less
- web-ui/src/main/resources/catalog/style/gn_editor.less
- web-ui/src/main/resources/catalog/templates/editor/directory.html
- web/src/main/webapp/WEB-INF/config-summary.xml
Again, some improvements to the UI:
* Directory entries can be filtered and/or sorted by validity status
* The entry creation button has been clarified (now only available as a dropdown with the list of templates):
Also, it is now possible to filter directory entries by validity status in the metadata editor using `show-valid-only="true"` on the `gn-directory-entry-selector` directive.
Without filter:
With filter:
Please note: I've added the following css classes to `gn.less` in order to facilitate creating elaborate layouts. These are mostly self explaining and combining them in HTML templates should allow us to write less stylesheet code.
```css
.pos-relative { position: relative; }
.pos-absolute { position: absolute; }
.spacer, .flex-spacer { flex-grow: 0; flex-shrink: 0; min-width: …
```
> Directory UI improvements

- schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields.xsl
- web-ui/src/main/resources/catalog/components/edit/FieldsModule.js
- web-ui/src/main/resources/catalog/components/edit/bounding/BoundingDirective.js
- web-ui/src/main/resources/catalog/components/edit/bounding/BoundingModule.js
- web-ui/src/main/resources/catalog/components/edit/bounding/BoundingService.js
- web-ui/src/main/resources/catalog/components/edit/bounding/partials/boundingpolygon.html
- web-ui/src/main/resources/catalog/components/viewer/geometry/GeometryDirective.js
- web-ui/src/main/resources/catalog/components/viewer/geometry/GeometryService.js
- web-ui/src/main/resources/catalog/components/viewer/geometry/partials/geometrytool.html
- web-ui/src/main/resources/catalog/components/viewer/wps/partials/processform.html
- web-ui/src/main/resources/catalog/locales/en-editor.json
- web-ui/src/main/resources/catalog/style/gn.less
- web-ui/src/main/resources/catalog/style/gn_editor.less
- web-ui/src/main/resources/catalog/style/gn_viewer.less
A new `gn-bounding-polygon`  directive was created, similar to the one that handles bounding-box drawing:
The bounding polygon can be drawn/modified on the map, and a new one can be set by pasting text in the input and selection format and projection.
Remaining:
> Added support for bounding polygons in MD editor

- core/src/main/java/org/fao/geonet/kernel/search/keyword/KeywordSort.java
- services/src/main/java/org/fao/geonet/api/registries/vocabularies/KeywordsApi.java
Improve multilang keyword search api.
- Restore pLang attribute
Overrides the lang attribute, can be an array. If specified, all keywords will return translation for all requested languages.
- Fix response order TreeSet behavior cause if comparator returns 0 (when 2 keywords have no translation in a language) then the keyword is not added. Only one keyword were returned in the case of a thesaurus requested in a lang where it had no translation for.
- Fix API parameter `rows` that were set to `Number of rows`, issue with api config.
> Registries api

- schemas/iso19139/src/main/java/org/fao/geonet/schema/iso19139/ISO19139SchemaPlugin.java
- schemas/iso19139/src/test/java/org/fao/geonet/schema/iso19139/ISO19139SchemaPluginTest.java
- schemas/iso19139/src/test/resources/org/fao/geonet/schema/iso19139/multilingual-contact.xml
- schemas/schema-core/src/main/java/org/fao/geonet/kernel/schema/MultilingualSchemaPlugin.java
- services/src/main/java/org/fao/geonet/api/registries/DirectoryEntriesApi.java
- services/src/main/java/org/fao/geonet/api/registries/DirectoryUtils.java
- web-ui/src/main/resources/catalog/components/edit/directoryentryselector/DirectoryEntrySelector.js
This PR updates languages in the subtemplate while inserted in the template as xlink.
As keyword, subtemplate api now takes array of langs as parameter and filter the XML on these langs.
If no lang is requested, then the multilingual part is deleted (`gmd:PT_FreeText`)
The xlink fragment in the metadata is inserted with languages:
```xml
<gmd:pointOfContact xmlns:xlink="http://www.w3.org/1999/xlink"
xlink:href="local://srv/api/registries/entries/26b6901f-6914-40c4-bc1c-af237e296924?process=gmd:role/gmd:CI_RoleCode/@codeListValue~distributor&amp;lang=eng&lang=fre">
```
This way, the xlink subtemplate XML fragment contains the same languages as in the metadata.
Not covered: if user add new languages in the metadata (or remove them), the `xlink:href` is not update at the moment.
> Update langs in subtemplate depending on metadata langs

- core/src/main/java/jeeves/xlink/Processor.java
- schemas/iso19139/src/main/plugin/iso19139/convert/thesaurus-transformation.xsl
- services/src/main/java/org/fao/geonet/api/registries/DirectoryEntriesApi.java
- services/src/main/java/org/fao/geonet/api/thesaurus/KeywordsApi.java
Keyword xlink were still working with jeeves services `xml.keyword.get`, so the local resolution was broken.
This PR migrate the service and update UI and backend to manage the new url:
- new spring service for getKeywordById
- insert xlink with the new service in the metadata
The new xlink local url is like:
```
local://srv/api/keyword?thesaurus=external.place.regions&amp;id=http://www.naturalearthdata.com/ne_admin#Country/AFG,http://www.naturalearthdata.com/ne_admin#Country/DZA&amp;multiple=true&amp;lang=eng,fre,ger,chi,ara,spa,rus
```
> Migrate keyword xlink to GN spring API

- schemas/iso19139/src/main/plugin/iso19139/update-fixed-info.xsl
- web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
If you delete langs in the metadata, all localizedString stay but change locale to #EN
Change this behavior, the problem right now is that the localizedString is still in the metadata, but empty (no translation and no locale code).
> [WIP] - Remove localizedString for lang that is not in the metadata

- web/src/main/webapp/xsl/conversion/OGCWxSGetCapabilitiesto19119/OGCWxSGetCapabilities-to-19119.xsl
The generation of the `ows` xsl variable should be an instance of `xsl:text` to avoid whitespaces and newlines. 
This caused all subsequent 
```
<xsl:when test="$ows='true'">
```
checks to fail
> Capabilities to 19119 - Fixed title generation

- web-ui/src/main/resources/WEB-INF/classes/web-ui-wro-sources.xml
- web-ui/src/main/resources/catalog/components/index/IndexRequest.js
- web-ui/src/main/resources/catalog/components/search/formfields/FormFieldsDirective.js
- web-ui/src/main/resources/catalog/components/search/map/MapFieldDirective.js
- web-ui/src/main/resources/catalog/components/search/mdview/mdviewDirective.js
- web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js
- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
- web-ui/src/main/resources/catalog/components/viewer/geometry/GeometryService.js
- web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextService.js
- web-ui/src/main/resources/catalog/components/viewer/profile/partials/profile.html
- web-ui/src/main/resources/catalog/components/viewer/wfsfilter/partials/wfsfilterfacet.html
- web-ui/src/main/resources/catalog/components/viewer/wps/WpsDirective.js
- web-ui/src/main/resources/catalog/components/viewer/wps/WpsService.js
- web-ui/src/main/resources/catalog/components/viewer/wps/partials/processform.html
- web-ui/src/main/resources/catalog/js/jsonix/OWC_0_3_1.js
- web-ui/src/main/resources/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.fr.js
- web-ui/src/main/resources/catalog/locales/en-core.json
- web-ui/src/main/resources/catalog/templates/top-toolbar.html
- web/src/main/webapp/xslt/base-layout-cssjs-loader.xsl
These fixes and improvements are backports from a customer fork:
* `GeometryService` had a typo that meant sending GML polygons to WPS services was broken
* JS errors were popping up when a context save was attempted while a layer was still loading
* i18n was added to the date-picker component; only `fr` for now though (each language is a separate include)
* Do not add duplicate filters in URL when searching for MD
* Fixed JSONIX schema for persistent WFS filters
* WPS response which are WMS layers is now added to the map
* The WPS directive was cleaned up & improved
* User account link is fixed in top toolbar
Note: there are features in there that may not yet be accessible with the current UI, mainly customizing WPS services with an `applicationProfile` field (adding default values & …
> Minor UI fixes and improvements

- web-ui/src/main/resources/catalog/components/edit/directoryassociatedmd/DirectoryAssociatedMdDirective.js
- web-ui/src/main/resources/catalog/components/search/resultsview/SelectionDirective.js
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/selection-widget.html
- web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js
- web-ui/src/main/resources/catalog/js/edit/DirectoryController.js
- web-ui/src/main/resources/catalog/templates/editor/directory.html
This adds the selection options with appropriate menus to the directory manager.
* Changes: mdSelection directive can now disable menus by configuration using the excludeActionsPattern attribute
* Minor fix: resetSearch must preserved selection bucket.
> Directory manager / Add selection mechanism.

- web-ui/src/main/resources/catalog/components/viewer/gfi/GetFeatureInfoDirective.js
This aims to avoid confusing the user regarding layer order vs. table order when doing a GetFeatureInfo call (click on the map).
Layer order: top to bottom
Table order: left to right
> Reverses layer order when displaying GetFeatureInfo results as tables

- web-ui/src/main/resources/catalog/js/admin/ThesaurusController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/style/gn.less
- web-ui/src/main/resources/catalog/style/gn_admin.less
- web-ui/src/main/resources/catalog/style/gn_editor.less
- web-ui/src/main/resources/catalog/templates/admin/classification/thesaurus.html
Keyword editor now uses `gn-multilingual-field` directive: better code reuse & ability to edit many different languages at the same time:
> Improve multilingual authoring in thesaurus keyword editor

- web-ui/src/main/resources/catalog/components/admin/uiconfig/UiConfigDirective.js
- web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
- web-ui/src/main/resources/catalog/components/common/map/mapDirective.js
- web-ui/src/main/resources/catalog/components/common/map/mapService.js
- web-ui/src/main/resources/catalog/components/common/map/wmsQueue.js
- web-ui/src/main/resources/catalog/components/edit/bounding/BoundingDirective.js
- web-ui/src/main/resources/catalog/components/viewer/geometry/GeometryService.js
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
This is intended to be used mainly by maps other than search & viewer, as the search map is centered according to search results and the viewer map according to the OWS context.
* A new UI setting `mapExtent` has been added: the extent will be applied to editor maps (bounding polygon editor & bounding box editor) if defined
* A new UI setting `mapBackgroundLayer` has been added: if defined, the WMS/WMTS layer will be used in the editor maps instead of OSM
* Minor fixes to `gnMap` service to make that work
* Tweak to the UI settings controller to show settings which have not been defined yet by the user
Only `gn-draw-bbox` and `gn-bounding-polygon` directives are affected by this PR.
Side note: I added new UI settings to handle these features, but this is clearly not the ideal way as there …
> Add a new setting to specify extent & background for editor maps

- web-ui/src/main/resources/catalog/components/common/map/mapService.js
This pull requests adds support for WMTS services that only supports `RESTful` and not `KVP` like https://maps.wien.gv.at/basemap/1.0.0/WMTSCapabilities.xml
If the WMTS supports `KVP` is used to don't change the original functionality.
Also the spec seem doesn't require to have the full url to the capabilities document, but just the service endpoint. For example:
```
<ows:Operation name="GetCapabilities">
<ows:DCP>
<ows:HTTP>
<ows:Get xlink:href="https://maps.wien.gv.at/basemap">
<ows:Constraint name="GetEncoding">
<ows:AllowedValues>
<ows:Value>RESTful</ows:Value>
</ows:AllowedValues>
</ows:Constraint>
</ows:Get>
```
The problem is that the feature used in GeoNetwork to save the context in the session needs the full url (in this example: …
> Improved WMTS support for restful

- services/src/main/java/org/fao/geonet/api/records/model/related/RelatedMetadataItem.java
- web/src/main/webapp/xslt/services/metadata/relation.xsl
This pull requests adds the metadata type information to the metadata relations response.
We need to improve the way to add additional metadata information to the metadata relations response as actually requires Java changes, but in any case the metadata type field seem quite relevant and it's used by some customers using the API from third party applications.
> Add metadata type information in metadata relations service

- core/src/main/java/org/fao/geonet/kernel/DataManager.java
- core/src/main/java/org/fao/geonet/kernel/IndexMetadataTask.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/IMetadataCategory.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/IMetadataIndexer.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/IMetadataManager.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/IMetadataOperations.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/IMetadataSchemaUtils.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/IMetadataStatus.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/IMetadataUtils.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/IMetadataValidator.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataCategory.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataIndexer.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataOperations.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataSchemaUtils.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataStatus.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataUtils.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataValidator.java
- core/src/main/resources/config-spring-geonetwork.xml
Why?
* This classes are more Spring friendly
* It will create less chaos when merging and modifying the same file
* Decoupling
* Allow to override parts of DataManager with overriding beans (documentation in future PR)
This PR only split the DataManager (now deprecated) into smaller files. It does not change any code or behaviour.
You can still use DataManager, it will just redirect to the proper helper class. But for future coding, try to use the helper class directly (through the interface).
> Refactoring DataManager.java into smaller helper classes 

- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/js/LoginController.js
- web-ui/src/main/resources/catalog/templates/signin.html
- web-ui/src/main/resources/catalog/templates/top-toolbar.html
- web/src/main/webapp/WEB-INF/config-security/config-security-shibboleth.xml
- web/src/main/webapp/xslt/base-layout-cssjs-loader.xsl
- web/src/main/webapp/xslt/common/base-variables.xsl
I am removing deprecated configuration on SAML/Shibboleth. Right now it only works on an external login interface like on Apache Shibboleth that will take care of the login and logout and will send the proper headers to GN for login.
If shibboleth is enabled, no login form is shown.
Fixes #2107
> Removing deprecated SAML/Shibboleth configuration

- web-ui/src/main/resources/catalog/components/edit/directoryentryselector/partials/directoryentryselector.html
- web-ui/src/main/resources/catalog/components/thesaurus/partials/thesaurusselector.html
Fixes:
* `gn-keyword-picker` now correctly handles the `allowFreeTextKeywords` attribute; if set to false, the user will not be able to add a new free-text keyword and the thesaurus button will be rendered without text:
Note: this attribute's value is currently set in the schema config, ie: https://github.com/geonetwork/core-geonetwork/blob/develop/schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml#L180
* `gn-directory-entry-selector` now disables browser autocomplete on its input field, as it may collide with the autocompletion already existing
> Minor fixes to editor directives (thesaurus and directory entry selector)

- schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields.xsl
- web-ui/src/main/resources/catalog/components/common/map/mapDirective.js
- web-ui/src/main/resources/catalog/components/common/map/partials/drawbbox.html
- web-ui/src/main/resources/catalog/components/edit/bounding/BoundingDirective.js
- web-ui/src/main/resources/catalog/components/edit/bounding/partials/boundingpolygon.html
Improvements:
* better handle background layer setting (use OSM if none defined) - note: this is a temporary fix, a better handling of maps still need to be done
* implement a read-only mode for the bounding box editor, which is active when the extent is resolved through a xlink (and as such, not editable)
> Improvements to editor map tools (bounding box & polygon)

- web-ui/src/main/resources/catalog/js/admin/ThesaurusController.js
- web-ui/src/main/resources/catalog/templates/admin/classification/thesaurus.html
Previously keywords with an extent could not be loaded or saved. This is fixed with this PR.
Also the template for the geo coords has been improved:
> Fix keywords management when of 'place' type

- web-ui/src/main/resources/catalog/components/admin/uiconfig/UiConfigDirective.js
- web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/mapconfig.html
- web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
- web-ui/src/main/resources/catalog/components/common/map/mapDirective.js
- web-ui/src/main/resources/catalog/components/common/map/mapModule.js
- web-ui/src/main/resources/catalog/components/common/map/mapService.js
- web-ui/src/main/resources/catalog/components/common/map/mapsManager.js
- web-ui/src/main/resources/catalog/components/common/map/partials/drawbbox.html
- web-ui/src/main/resources/catalog/components/edit/bounding/BoundingDirective.js
- web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextService.js
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
The goal of this PR is to begin standardizing the way OpenLayers maps are created & configured in the admin console.
Currently the way the search map, viewer map and editor maps are handled is completely different.
With this PR, every map creation should be done through the new `gnMapsManager` service, which takes one argument: the map type (`VIEWER_MAP`, `SEARCH_MAP` or `EDITOR_MAP`).
The map will be available right away but some layers may be added asynchronously, especially WMTS as they go through a `GetCapabilities` call.
This PR also introduces a standard *layer notation* which is already used in the saved contexts, but should now be used everywhere to describe a map layer. The notation is a string structured like so:
`{type=<TYPE>,arg1=<VALUE>,...}`
Valid examples are:
* OSM layer: …
> Begin refactoring OpenLayers map handling

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/CswHarvester.java
When the harvester settings are retrieved from the database using the
HarvesterSettingManager it includes a <value> element inside the search
filters. With this commit this case is covered too when the settings are 
cloned to be preserved.
This change should be merged in 3.4.x and develop branches too.
Fixes #1780.
> Avoids losing the filter after removing all CSW harvester's records

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/arcsde/ArcSDEHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet20/Aligner.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/oaipmh/Harvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/ogcwxs/Harvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/thredds/Harvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/webdav/Harvester.java
- web-ui/src/main/resources/catalog/locales/en-admin.json
Set groupOwner to all harvested metadata as required from harvester admin UI.
> Set groupOwner in CSW harvester - fix #2188

- web-ui/src/main/resources/catalog/components/search/facets/FacetDimensionDirective.js
- web-ui/src/main/resources/catalog/components/search/facets/FacetsDirective.js
- web-ui/src/main/resources/catalog/components/search/facets/partials/dimension-facet-list.html
- web-ui/src/main/resources/catalog/locales/en-core.json
- web-ui/src/main/resources/catalog/views/default/less/gn_facets_default.less
Just a quick rework of the expand/collapse buttons:
Also all the facet directives now support custom templates.
> Minor facets UI improvement

- web-ui/src/main/resources/catalog/components/search/formfields/partials/sortByCombo.html
- web-ui/src/main/resources/catalog/components/search/pagination/partials/pagination.html
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/locales/en-core.json
- web-ui/src/main/resources/catalog/style/gn.less
- web-ui/src/main/resources/catalog/style/gn_search.less
- web-ui/src/main/resources/catalog/templates/top-toolbar.html
- web-ui/src/main/resources/catalog/views/default/less/gn_navbar_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_pagination_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_search_default.less
- web-ui/src/main/resources/catalog/views/default/templates/results.html
More UI improvements with this PR:
* The user info block in the toolbar is now more compact (this way, there should not be any overlapping in the toolbar anymore), with the signout link being in a dropdown
* When logged out, an inline form is available in the toolbar to quickly login:
* The toolbar displays all its items properly when on mobile format:
* The pagination & sort-by widgets have been slightly improved:
* The general layout of the search results page have been slightly improved to better handle mobile formats & have better widgets placement:
> Toolbar improvements pt. 2 & search widgets improvements

- web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
In the `render-element` when using `directive` parameter, the value for multilingual fields is not handle properly, sending all translation values in the same field as a string:
https://github.com/geonetwork/core-geonetwork/blob/3.2.x/web/src/main/webapp/xslt/ui-metadata/form-builder.xsl#L128
This Pull Request sends a JSON doc with the language/id/value for each multilingual element to the directive.
In any case, the `render-element` template accepts also a `type` parameter that can be used also for directives and is handle in https://github.com/geonetwork/core-geonetwork/blob/3.2.x/web/src/main/webapp/xslt/ui-metadata/form-builder.xsl#L142, not very clear the reason to handle directives in 2 ways. The pull request only affects the `directive` parameter.
> Add multilingual values in multilingual fields for directives managed in render-element template

- .travis.yml
seems that _JAVA_OPTIONS overwrite surefire settings
wonder if this is the cause of randomly failing builds
(java.lang.RuntimeException: The forked VM terminated
without properly saying goodbye. VM crash or System.exit called?)
> try to avoid vm being rude at test times with travis

- web-ui/src/main/resources/catalog/js/edit/EditorController.js
When closing the editor (save or cancel) try to go back from where we come.
If coming from search page, then go back to metadata view, else go back to editor board.
> Go back to metadata view when closing to editor if coming from search

- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
- web-ui/src/main/resources/catalog/templates/top-toolbar.html
- web-ui/src/main/resources/catalog/views/default/less/gn_navbar_default.less
* the inline login form does not appear on the new account page anymore (fixes #2207)
* dropdowns can now be opened with keyboard navigation (tab focus)
* fixed root menu items 'active' state
> Navbar fixes

- web-ui/src/main/resources/catalog/components/common/map/mapService.js
- web-ui/src/main/resources/catalog/components/common/map/mapsManager.js
- web-ui/src/main/resources/catalog/components/index/IndexRequest.js
- web-ui/src/main/resources/catalog/components/viewer/geometry/GeometryService.js
- web-ui/src/main/resources/catalog/components/viewer/gfi/FeaturesLoader.js
- web-ui/src/main/resources/catalog/components/viewer/wfsfilter/WfsFilterService.js
- web-ui/src/main/resources/catalog/components/viewer/wps/WpsDirective.js
These fixes are backports from a customer fork.
Includes:
* Fix to `GeometryService` for IE11 compatiblity
* Fixed extents in search map not appearing under certain projections (e.g. EPSG:21781)
* WFS Filter:
* Fixed features table sometimes not working & not exporting correctly in CSV
* Fixed `WfsFilterService` CQL output sometimes incorrect (quotes not escaped & param names)
* WPS Client:
* Minor fix to application profile loading (more explicit error)
* WMS output now better filters `output_`-like layers
> Misc. UI fixes to WFS filter & WPS client

- web-ui/src/main/resources/catalog/components/metadataactions/RelatedResourcesService.js
Previously, clicking on the "Download" button would cause a JS error:
> Fixes download action on related resources

- web-ui/src/main/resources/catalog/js/edit/DirectoryController.js
- web-ui/src/main/resources/catalog/templates/editor/directory.html
Previously, editing the permissions would close the current entry. Also the editor form was improved to not show the previous entry while a new one is loading.
> Fix permissions editor in directory management

- services/src/main/java/org/fao/geonet/api/records/formatters/FormatterApi.java
In Geonetwork, xlink subtemplate resolutions are not saved in database (don't know if it is an issue or not).
So when the formatter get the metadata to process it, it does not render the subtemplates.
This PR add the xlink resolution before the formatter is applied.
> formatter: resolve xlink before applying formatter

- schemas/iso19139/src/main/plugin/iso19139/update-fixed-info-subtemplate.xsl
- web-ui/src/main/resources/catalog/components/edit/bounding/BoundingDirective.js
- web-ui/src/main/resources/catalog/components/viewer/geometry/GeometryService.js
* Preserve polygon input projection
* Fix empty namespace on non WGS84 geometries
```
org.jdom.IllegalAddException: The namespace xmlns="" could not be added as a namespace to "Polygon": The namespace prefix "" collides with the element namespace prefix
```
* Remove unecessary metadocument cleanup
* Editor / Bounding polygon / Read the data projection #2261
* Editor / Bounding polygon / Polygon is converted to WGS84 whatever is the initial projection #2262
> Editor / Bounding polygon improvements.

- web-ui/src/main/resources/catalog/components/utility/CORSInterceptor.js
Without this, some requests (i.e. i18n API calls) would sometimes be redirected with an unwanted `Accept-Language` header.
> Fix unwanted lang header overwrite in CORS interceptor

- web-ui/src/main/resources/catalog/components/common/popup/PopupDirective.js
- web-ui/src/main/resources/catalog/js/edit/DirectoryController.js
- web-ui/src/main/resources/catalog/style/gn_editor.less
- web-ui/src/main/resources/catalog/templates/editor/directory.html
Now the privileges widget is cleared when not displayed, which prevents some bugs & inconsistencies.
Also a slight improvement to the directory UI search results.
To do this I had to handle a `closeCallback` parameter on `gnModal`, which is pretty handy for this sort of case (ie doing something when the modal is closed by any means).
Note that this only applies to the privileges edition of a single record from the search results list.
> Improve privileges widget in directory UI

- web-ui/src/main/resources/catalog/templates/top-toolbar.html
This is a simple cosmetic fix as the editors already had access to the batch editing menu before, but not from the toolbar.
> Give access to batch editing submenu to editors

- web-ui/src/main/resources/catalog/components/metadataactions/RelatedDirective.js
- web-ui/src/main/resources/catalog/components/metadataactions/RelatedObserverDirective.js
- web-ui/src/main/resources/catalog/components/metadataactions/partials/relatedObserverTemplate.html
- web-ui/src/main/resources/catalog/components/search/mdview/mdviewModule.js
- web-ui/src/main/resources/catalog/views/default/templates/recordView.html
In the main metadata view, show a loading spinner while the requests to the related API are active. Hide it at the end and show the actual related elements if there are any.
Related load in progress:
Related load finished:
> Add a loading spinner while requesting related resources in the metadata view

- web-ui/src/main/resources/catalog/components/viewer/partials/mainviewer.html
Extended the list of tools that can be disabled by adding the tool to the `disabledTools` list (json at the bottom of the User Interface settings).
The list of tools now include:
- addLayers
- layers
- filter
- processes
- contexts
- print
- mInteraction
- drawVector
- syncAllLayers
- graticule
> Disabled tools extended

- web-ui/src/main/resources/catalog/components/mdFeedback/GnmdFeedbackDirective.js
- web-ui/src/main/resources/catalog/components/mdFeedback/partials/mdFeedback.html
this feature adds the capability to add a label to the feedback button
also some btn pull-right styling removed imho this type of config should go on a template
> extend feedback button to remove styling and add option for a label

- schemas/iso19139/src/main/plugin/iso19139/index-fields/default.xsl
- schemas/iso19139/src/main/plugin/iso19139/index-fields/language-default.xsl
- web-ui/src/main/resources/catalog/components/search/facets/partials/dimension-facet-category.html
- web-ui/src/main/resources/catalog/locales/en-search.json
- web/src/main/webapp/WEB-INF/config-summary.xml
This PR adds a new facet, displayed by default after the "Resource Type" in the search results:
The facet is based on the presence of online resources of type `WMS`, `FILE` and `WPS`.
For now only "downloadable", "viewable" and "processable" values are handled, but I think it could be interesting to add a "filterable" value as well (i.e. possible to index & filter features from a WFS).
Only works for iso19139.
Please note: as there is no backend translator for these values, I had to modify the facets template to translate labels on the front end side.
> Add "available actions" facet to filter downloadable/viewable MD

- web-ui/src/main/resources/catalog/components/common/ows/OWSService.js
The performance issue was caused by the recursive array manipulation when the CRS array had several thousand values.
I've chosen a simpler approach & tested with WMS services from mapserver and geoserver.
> Improve performance when parsing a WMS GetCapabilities response

- pom.xml
- web/pom.xml
Sometimes a file is deleted from a schema or even a full schema is removed from the project. In these cases the file/folder needs to be manually removed from `web/src/main/webapp/WEB-INF/data/config/schema_plugins`. 
To avoid errors caused by unexpected files in `schema_plugins` folder this commit configures the `maven-clean-plugin` in web project to empty this folder during the maven clean phase.
> Clean web's schema_plugins in the maven clean phase

- web-ui/src/main/resources/catalog/components/edit/directoryentryselector/partials/directoryentryselector.html
Previously the string used to search directory entries did not contain wildcards, and as such was not really usable.
> Editor / Improve search in directory entry selector

- schemas/iso19139/src/main/plugin/iso19139/index-fields/index-subtemplate.xsl
- web-ui/src/main/resources/catalog/templates/editor/directory.html
Previously, if a subtemplate did not have a value for the current lang, the title would appear empty:
This commit adds a fallback value (any non-empty value available for this field in another language).
> [WIP] Add fallback values for multilingual subtemplate indexing

- web-ui/src/main/resources/catalog/components/catalog/CatalogService.js
eg. OGC:WMS or application/ogc-wms.
> getLinksByType / Lower case comparaison to properly return links 

- web-ui/src/main/resources/catalog/js/edit/DirectoryController.js
- web-ui/src/main/resources/catalog/templates/editor/directory.html
- web/src/main/webapp/xslt/ui-metadata/edit/edit.xsl
This adapts the subtemplate editor following https://github.com/geonetwork/core-geonetwork/pull/2298
Subtemplate saving and XML editing is functional again with this PR.
> Restore subtemplate editing

- web-ui/src/main/resources/catalog/components/edit/validationreport/ValidationReportService.js
- web-ui/src/main/resources/catalog/js/edit/EditorController.js
- web-ui/src/main/resources/catalog/locales/en-editor.json
- web-ui/src/main/resources/catalog/style/gn.less
- web-ui/src/main/resources/catalog/templates/editor/editor.html
This dialog will only appear if the option to automatically unpublish invalid MD is set.
This will trigger only when the user clicks "save & close". When the validation process is triggered, the validity status of the MD is updated client-side, which means that this dialog:
* will appear if the user starts editing a valid MD and make it invalid, but triggers the validation process manually,
* will NOT appear if the user breaks validity on a MD and do not trigger the validation process manually.
I could not find a better way to implement this, but am of course open to suggestions.
> Add a confirmation dialog when saving&closing editor on an invalid MD

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
Previously multilingual fields were cleared on first opening of the Add Online Resource dialog, even when there were existing values.
> Fix multilingual fields cleared incorrectly in Add Online Resource dialog

- web-ui/src/main/resources/catalog/components/edit/bounding/BoundingDirective.js
The attribute `output-crs` can be used to force a CRS for the output geometry of `gn-bounding-polygon`.
If undefined, the behavior stays unchanged: output CRS is the one currently selected by the user. See https://github.com/geonetwork/core-geonetwork/pull/2265
> Add an attribute on gn-bounding-polygon to force output CRS

- web-ui/src/main/resources/catalog/components/viewer/geometry/GeometryService.js
In the case of EPSG:4326, writing the CRS in the GML will cause the longitudes and latitudes to be inversed, which breaks things down the line.
Note: this is apparently normal behavior.
> Editor / When outputting 4326 geometry in GML, do not specify the CRS

- web-ui/src/main/resources/catalog/components/edit/directoryentryselector/partials/directoryentryselector.html
- web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js
- web-ui/src/main/resources/catalog/components/search/searchmanager/SearchManagerService.js
- web-ui/src/main/resources/catalog/js/edit/DirectoryController.js
- web-ui/src/main/resources/catalog/templates/editor/directory.html
* The method `SearchManagerService.gnSearch` now cancels any previous request before making a new one; this means that there cannot be race conditions with search results anymore. This removes the need for the "search counter" login in `SearchFormDirective`, which is now also adjusted (should still be backwards compatible with everything).
* Add a spinner when searching directory entries in `gn-directory-entry-selector`:
* Title search in directory management UI is now more flexible (wildcards added) and the reset button keeps the current type:
> Various UI search improvements

- web-ui/src/main/resources/catalog/components/common/needhelp/partials/needhelp.html
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/onlinesrcList.html
- web-ui/src/main/resources/catalog/components/metadataactions/partials/metadatacategoryupdater.html
- web-ui/src/main/resources/catalog/components/metadataactions/partials/metadatagroupupdater.html
- web-ui/src/main/resources/catalog/views/default/directives/partials/mdactionmenu.html
- web-ui/src/main/resources/catalog/views/default/templates/recordView.html
Add labels to buttons and make these labels responsive:
- on the editor buttonbar
- on the buttons in the metadata view
- on the `associated resources` button
- move the `associated resources` button to the panel body
- restyle the help button
**Screenshot of the labels in the metadata page**
**Screenshot of the label and help button in the editor page**
> Add labels to buttons

- web-ui/src/main/resources/catalog/style/gn.less
- web-ui/src/main/resources/catalog/templates/editor/directory.html
- web-ui/src/main/resources/catalog/templates/editor/import.html
- web-ui/src/main/resources/catalog/templates/editor/new-metadata-horizontal.html
- web-ui/src/main/resources/catalog/templates/editor/new-metadata-vertical.html
Add `cancel` buttons to Import and New Metadata page. Make the look and label for the `cancel` the same for all pages (new, import, manage directory, batch edit).
**Look and label for `cancel` button**
> Add cancel buttons

- web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js
- web-ui/src/main/resources/catalog/components/search/searchmanager/SearchManagerService.js
This restores the front page searches (latest/popular) as I've reverted a breaking (and unnecessary) change in #2340: search requests are not cancelled anymore.
Fixes #2347
> Revert breaking change on UI search service

- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
- web-ui/src/main/resources/catalog/views/default/less/gn_result_default.less
- web-ui/src/main/resources/catalog/views/default/templates/recordView.html
- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
Classes are added to the different blocks in the sidebar of the metadata page (recordView), both in default and advanced view. Classes are named after the purpose (and title) of the blocks.
These classes make it easier for identifying and manipulating a single block. The advanced sidebar has an extra class: `gn-md-side-advanced` to distinguish it from the default sidebar.
Some code cleanup has been done, <br>'s are replaced with a `margin-bottom` and non-breaking spaces have been replaced with the class `fa-fw` where possible.
> Sidebar classes

- web-ui/src/main/resources/catalog/js/CatController.js
Previously, the user would always see the logged in status in the toolbar even after a log out.
This happens because IE11 does not take into account the "Expired" header in the response.
> Avoid "user status" request caching in IE11

- web-ui/src/main/resources/catalog/components/viewer/gfi/FeaturesLoader.js
Since FeaturesLoader is using Angular's $http service to retrieve the info and
it uses the CORSInterceptor it doesn't need to add anymore the proxy's URL
manually to the URL because the interceptor will do if it is needed.
Fixes #2375.
> Use CORS interceptor for getFeatureInfo requests

- core/src/main/java/org/fao/geonet/kernel/search/UserQueryInput.java
- web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js
- web-ui/src/main/resources/catalog/components/search/searchmanager/SearchManagerService.js
If `URLDecoder.decode` fails, for example an unknown escape sequence like `"%8"`, the original value is used as parameter.
Also add some error control to the JS function `gnSearch`.
> Urldecode fails sometimes in lucene search

- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/editor.html
- web-ui/src/main/resources/catalog/style/gn.less
- web-ui/src/main/resources/catalog/style/gn_editor.less
On the contribute page the edit buttons on each row had their own table cell, they are now placed in a buttonbar. This is taking less space and allows longer titles.
The checkbox and the type widget now each have their own table cell, this makes it easier to align all the elements on that row.
**Screenshot of the buttonbar**
> Edit buttons in a buttonbar

- web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextDirective.js
- web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextService.js
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/views/default/config.js
* Search map is using deprecated settings. Use mapsManager instead
* viewerSettings.storage was duplicates of viewerSettings.mapConfig.storage with a hard coded value
* Default layers are always merged in custom config so it was not possible to turn off OSM when using context config. Use context configuration by default.
* Add possibility to set an empty map viewer state storage. This allows to forget what use to be in localStorage eg. in case some VIP complains about some OSM labels in wrong languages.
> Map on search is not using config from the admin

- web-ui/src/main/resources/catalog/components/common/map/mapsManager.js
Following #2369 I've done a bit of research and it turns out that removing the `ol-rotate` control altogether seems to fix the problem. This can be done in the maps manager instead of simply hiding them with CSS (remember: *maps are managed by the maps manager now* :smile:).
@MichelGabriel  @josegar74 can you please confirm this fixes it?
This fix won't be applicable to 3.2.x. For this branch, the modification will have to be done here:
https://github.com/geonetwork/core-geonetwork/blob/2d1c12e45ef9ac772976cbce8aea15539b036309/web-ui/src/main/resources/catalog/components/common/map/mapDirective.js#L209-L220
Adding `controls: [ new ol.control.Zoom() ]` should do the trick.
> Fixes editor form fields disappearing below OL maps

- web-ui/src/main/resources/catalog/templates/admin/usergroup/groups.html
Place the checkbox for the label, this fixes an error when displaying the checkbox.
**Old situation**
**New situation**
> Fix for category checkbox on Group page

- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/editor.html
- web-ui/src/main/resources/catalog/style/gn_editor.less
Small fix for displaying the edit buttons correctly. The buttonbar with edit buttons on the contribute page is now made responsive for smaller screens.
**Screenshot of a small screen**
> Fix for edit buttons in the buttonbar on smaller screens

- schemas/iso19139/src/main/plugin/iso19139/index-fields/default.xsl
- schemas/iso19139/src/main/plugin/iso19139/layout/layout.xsl
The metadata editor for iso19139 doesn't provides in default/full views support to edit elements with `gmx:Anchor`, been displayed as an empty block:
This pull request adds support for `gmx:Anchor`:
Additionally manages the indexing of  `gmd:code` using anchor for gmd:identifier`
> Metadata editor support for gmx:Anchor in iso19139 schema and indexing of gmd:identifier using anchor in gmd:code

- web-ui/src/main/resources/catalog/style/gn.less
Add an extra margin for the help button. The button was sometimes positioned directly below another element.
**Old situation**
**New situation**
> Margin for help button

- web-ui/src/main/resources/catalog/components/search/mdview/mdviewModule.js
- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
- web/src/main/webapp/xslt/common/render-html.xsl
The content in the advanced view was listed in a long list with different sections. These sections are now displayed as tabs.
When a tab is empty it is not displayed. A function is added to the controller (GnMdViewController) to activate the tabs and hide the tab header.
This PR is the same as https://github.com/geonetwork/core-geonetwork/pull/2367 but based on a more recent version of 3.4x. core. 
**Screenshot of the tabs in the advanced view**
> Tabs in advanced view (renewed)

- web/src/main/java/org/fao/geonet/proxy/URITemplateProxyServlet.java
After the introduction of the new `ProxyServlet` it doesn't use the proxy gateway configured in the admin settings making impossible the connection to external websites in environments where a proxy is needed to access the external network.
This commit allows `ProxyServlet` to use the proxy configured by Java standard properties `http.proxyHost`, `http.ProxyPort`, etc.
Other GN's components like the harvesters comply with the settings from the admin console.
> Use standard properties for proxy

- web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
Better display for related items (`Download and links`) on small screens. There was not enough space for a good display of the text and `add to map` button on small screens.
**Screenshot old situation**
**Screenshot new situation**
> Better display for related items on small screens

- web-ui/src/main/resources/catalog/components/search/mdview/mdviewModule.js
- web-ui/src/main/resources/catalog/locales/en-search.json
- web-ui/src/main/resources/catalog/views/default/templates/recordView.html
Before
After 
The sign in link redirect to the current page.
> When user click a link to a private record and is not yet authenticated, suggest the user to sign in and redirect to requested record.

- web-ui/src/main/resources/catalog/components/common/map/mapService.js
- web-ui/src/main/resources/catalog/components/common/map/print/PrintMapService.js
Since GN uses Mapfish-print v2.1.2 and it contains some bugs when printing a WMTS layer when REST is used this commit is a workaround that processes some parameters in the client side to allow Mapfish print the layer.
For example it needs a `dimensions` parameter, even when it should be optional. Another change is that Mapfish v2.1.2 doesn't replace the `{style}` and `{layer}` parameters in the URL, so we need to do that in the Javascript code.
Same fix than #2441 but ported to 3.4.x branch.
> Fix error when printing WMTS layers using REST

- web-ui/src/main/resources/catalog/components/common/map/mapService.js
- web-ui/src/main/resources/catalog/components/common/map/print/PrintMapService.js
Since GN uses Mapfish-print v2.1.2 and it contains some bugs when printing a WMTS layer when REST is used this commit is a workaround that processes some parameters in the client side to allow Mapfish print the layer.
For example it needs a `dimensions` parameter, even when it should be optional. Another change is that Mapfish v2.1.2 doesn't replace the `{style}` and `{layer}` parameters in the URL, so we need to do that in the Javascript code.
>  Fix error when printing WMTS layers using REST

- web-ui/src/main/resources/catalog/components/common/map/print/PrintDirective.js
- web-ui/src/main/resources/catalog/components/common/map/print/PrintMapDirective.js
- web-ui/src/main/resources/catalog/components/common/map/print/PrintMapService.js
Previously printing maps in 4326 would sometime fail because of an computation error in the `matrixSize` parameter sent to mapfish print.
> Fix for printing maps in EPSG:4326

- schemas/iso19139/src/main/plugin/iso19139/process/onlinesrc-add.xsl
Currently when adding some OGC services as online resources on a multilingual MD, this may happen:
When editing the resource:
Example here is using the OGC-WPS protocol.
I added support for multilingual values in the associated XSL process. Not sure if it is the right way to go though, as it feels weird to be able to specify multilingual names for an OGC service. I tried doing the change in the UI code but could not find a simple way to do this.
@fxprunayre do you think this is an acceptable fix?
> Fix for multilingual value handling in "Add Online Resource" dialog

- web-ui/src/main/resources/catalog/js/admin/AdminController.js
if warninghealthcheck is slow (or timeout) a file undefinedundefined.html is tried to be loaded, this fix prevents loading of the file, in the end the effect is the same: blank page while loading, would be better to add some spinner while loading
> on admin-dashboard prevent to load undefined.html

- web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextService.js
if ows context has a projection not known to ol, then throw a warning and set projection to epsg:3857, alternative would be to load projection on the fly from epsg.io
> set proj to 3857 if proj of context is unknown

- web-ui/src/main/resources/catalog/components/common/popup/PopupDirective.js
- web-ui/src/main/resources/catalog/style/gn_search.less
Fix for https://github.com/geonetwork/core-geonetwork/issues/2473
Heights are adjusted so the content of the panel is contained within the panel. The maximum height of the table body inside the privileges popup now depends on the height of the screen itself.
Another issue that came up was the position of the privileges popup, it was positioned absolute just beneath the top of the screen, therefore when you open the popup when scrolled down the popup opens out of sight. The popup now has a fixed position, so it opens always where you can see it.
> Fix for #2473: content of privilege window runs out of panel

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/onlinesrcList.html
Fix for https://github.com/geonetwork/core-geonetwork/issues/2484
The dropdown menu was opening to the left, however when the block containing the dropdown is on the left side of the page, the dropdown 'falls' off the page.
When the class `pull-right` is removed the dropdown opens to the right, and is now accessible when the block containing the dropdown is on the left or right side of the page (even on smaller screens).
> Fix for #2484: Content of add online resource dropdown runs outside of the screen

- web-ui/src/main/resources/catalog/style/gn_editor.less
- web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
Fix for: https://github.com/geonetwork/core-geonetwork/issues/2468
The `nil-reason` button has the class `btn-link`, this is causing it to not align with the other elements in the editor. This class is now replaced with `btn-default`.
The class `fa-fw` is added to the icon on the button to add some extra spacing between icon and label.
**Screenshot of the button after adding the `btn-default` class**
> Improve layout of attribute display in editor. Fix for: #2468

- schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/cat/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/dut/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/eng/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/fin/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/fre/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/ger/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/ita/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/nor/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/pol/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/por/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/rus/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/spa/strings.xml
This PR updates the INSPIRE view structure to resemble the TG document sections and solves the following issues:
- Metadata editor - INSPIRE view - Provide CRS selector with INSPIRE allowed values #2235
- Metadata editor - INSPIRE view - Missing mandatory elements #2236
- Metadata editor - INSPIRE view issues #2249
- INSPIRE service metadata - validation issues with 'Description of technical specification' #2251
---
A screenshot of the updated UI:
> INSPIRE view improvements. Fixes #2235, #2236, #2249, #2251

- web/src/main/webapp/WEB-INF/config-security/config-security-core.xml
forward param in session incidentally gets overwritten by failed image/thumbnail/ajax requests, solves #2379
> do not use session to store the forward url after login

- web-ui/src/main/resources/catalog/components/utility/UtilityModule.js
* `asGetCapabilities`: filter to check if a link is a getcapabilities request
* `asArray `: filter to check if a value is an array, and if so, return param or empty string quite some of the gn json returns empty array if undefined or empty string was intended
> Migrate Utility filters from NGR3 to GN 3.4.x

- web-ui/src/main/resources/catalog/components/metadataactions/RelatedDirective.js
This prevents a JS error when `gn-related` is not encapsulated in a `gn-related-observer` controller.
> Fix error in gnRelated directive when the observer is missing

- schemas/iso19139/src/main/plugin/iso19139/present/csw/gmd-brief.xsl
- schemas/iso19139/src/main/plugin/iso19139/present/csw/gmd-summary.xsl
Conversion of an element to its base type indicated in the `gco:isoType` attribute was done in the `full` output, but not in `brief` or `summary`.
This should not change anything for the iso19139 schema, but will give a more consistent behaviour for other schemas derived from it. Also facilitates extending the stylesheet for other schemas.
> Improve iso19139 CSW brief & summary output

- core/src/main/java/org/fao/geonet/kernel/DataManager.java
* wait call must be inside a synchronized block. In other cases it
throws IllegalMonitorStateException.
* Use a specific lock to synchronize the modification of indexing set.
This must be ported to 3.4.x and develop too.
> Fix deadlock threads while indexing

- web/src/main/webapp/WEB-INF/config-security/config-security-core.xml
Revert PR #2476 since use referer keeps the user in the login page and doesn't redirect to the protected resource as stated in issue #2379.
> Revert PR #2476

- core/src/main/java/org/fao/geonet/kernel/AccessManager.java
- core/src/test/java/org/fao/geonet/kernel/AccessManagerTest.java
In the settings a user can enter an IP and a network mask to detect request coming from the intranet.
Currently `system/intranet/network` needs to end in a series of zeroes to detect the intranet fine. 
If a user enters a network like `192.168.1.1` instead of `192.168.1.0` in the intranet's network setting `isIntranet` returns `false` for the IP `192.168.1.2` and netmask `255.255.255.0` when it should return `true`.
With this change `system/intranet/network` can be defined like `192.168.1.1` and netmask `255.255.255.0` and `192.168.1.2` will be accepted as part of the intranet.
> Apply netmask to network in isIntranet(ip) check

- integration-test/src/main/java/env/BaseTest.java
- integration-test/src/main/java/env/Env.java
- integration-test/src/test/java/stepDefintions/PredefinedStepDefinitions.java
- integration-test/src/test/resources/features/002.create_new_user.feature
- integration-test/src/test/resources/features/003.delete_new_user.feature
- integration-test/src/test/resources/features/004.create_advanced_users.feature
- integration-test/src/test/resources/features/010.create_and_publish_metadata.feature
- integration-test/src/test/resources/features/011.edit_created_metadata.feature
- integration-test/src/test/resources/features/012.edit_with_another_editor.feature
- integration-test/src/test/resources/features/013.edit_and_publish_with_reviewer.feature
- integration-test/src/test/resources/features/998.cleanup.feature
- integration-test/src/test/resources/features/999.exit.feature
- integration-test/src/test/resources/system.properties
On this commit I add some basic testing. The idea is to run this basic tests always before we do any release, to make sure there are no critical obvious bugs on the new release.
To run this, you have to run two separated maven commands:
On one hand you need to run a local GeoNetwork: **mvn jetty:run** on **web** folder.
On the other hand you need to run the tests: like **mvn test -Dwebdriver.chrome.driver=$path/chromedriver -Dbrowser=chrome** on **integration-tests** folder
See on the README.md of integration-tests folder to know more about running this tests.
It takes several minutes, be patient. 
The tests included here are:
* Creation of users (with roles on groups)
* Creation of metadata 
* Import of templates
* Check an editor of the same group can edit a metadata with privileges on …
> Tests for user creation, group management, creation of metadata, editing

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java
- web-ui/src/main/resources/catalog/components/common/savedselections/SavedSelectionsDirective.js
to make sure transformations, categories and attributes are correctly
applied. solves https://github.com/geonetwork/core-geonetwork/issues/2552
> Forcing an update when the metadata gets overrided by another harvester,

- core/src/main/java/org/fao/geonet/constants/Geonet.java
- core/src/main/java/org/fao/geonet/kernel/search/LuceneSearcher.java
- core/src/main/java/org/fao/geonet/kernel/search/SearchManager.java
- core/src/main/java/org/fao/geonet/kernel/search/spatial/OverlapsBBoxFilter.java
- core/src/main/java/org/fao/geonet/kernel/search/spatial/SpatialFilter.java
- core/src/main/java/org/fao/geonet/kernel/search/spatial/SpatialIndexWriter.java
- core/src/main/java/org/fao/geonet/kernel/search/spatial/WithinBBoxFilter.java
- core/src/main/java/org/fao/geonet/services/util/SearchDefaults.java
- web-ui/src/main/resources/catalog/locales/en-search.json
- web-ui/src/main/resources/catalog/views/default/module.js
The PR comes with refactorings which helped to better take measure of geonetwork spatial indexing mechanisms.
The purpose of this PR is to propose two spatial filters operating on bbox rather than on geometries, in order to earn ram and cpu at runtime:
- as spatial requests emanating form minimap are related to rectangular bounds, theses two filters are substitued to usual minimap geometrical ones.
- at search time, as features bbox are already stored in SRTTree (spatial index), these two filters don't rely on jcscahe.
In my opinion, replacing Data Pair by POJO helps a lot:
https://github.com/geonetwork/core-geonetwork/pull/2555/files#diff-431f31b5144d54b586f8eabcdda4567aL415.
vs 
https://github.com/geonetwork/core-geonetwork/pull/2555/files#diff-431f31b5144d54b586f8eabcdda4567aR559
In …
> Spatial search: Bbox filters

- web-ui/src/main/resources/WEB-INF/classes/web-ui-wro-sources.xml
- web-ui/src/main/resources/catalog/components/viewer/ViewerModule.js
- web-ui/src/main/resources/catalog/components/viewer/heatmap/HeatmapDirective.js
- web-ui/src/main/resources/catalog/components/viewer/heatmap/HeatmapModule.js
- web-ui/src/main/resources/catalog/components/viewer/heatmap/HeatmapService.js
- web-ui/src/main/resources/catalog/components/viewer/wfsfilter/WfsFilterDirective.js
- web-ui/src/main/resources/catalog/components/viewer/wfsfilter/partials/wfsfilterfacet.html
- web-ui/src/main/resources/catalog/js/admin/DashboardController.js
- web-ui/src/main/resources/catalog/js/admin/DashboardWfsIndexingController.js
- web-ui/src/main/resources/catalog/lib/geohash.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/style/gn_viewer.less
- web-ui/src/main/resources/catalog/templates/admin/dashboard/wfs-indexing.html
- web-ui/src/main/resources/catalog/views/default/less/gn_admin_default.less
- web/src/main/webapp/xslt/base-layout-cssjs-loader.xsl
This PR adds a little polish to the WFS indexing system:
* a list of ongoing indexing jobs is now available in admin/dashboard
This is still very raw data, taken directly from the ElasticSearch index. We will have to make a more robust system in the future with start/stop controls and finer status (hint @fxprunayre).
* fix for #2498
* bonus: a functional heatmap (backported from a customer fork):
Still a lot more to do on this topic, both on the frontend and backend, but hopefully this PR will make the system a bit more suitable for basic use.
> Improvements to WFS indexing: dashboard and map widget

- schemas/iso19139/src/main/plugin/iso19139/loc/ger/labels.xml
The codelist was not defined like the others, see:
https://github.com/geonetwork/core-geonetwork/blob/ee31c1aa388adcebfaf0c4fcb970351b4813eb8b/schemas/iso19139/src/main/plugin/iso19139/loc/eng/labels.xml#L2172-L2174
> Minor fix to german iso19139 labels (protocols)

- web-ui/src/main/resources/catalog/components/common/map/mapService.js
- web-ui/src/main/resources/catalog/components/common/map/mapsManager.js
- web-ui/src/main/resources/catalog/components/viewer/ViewerModule.js
- web-ui/src/main/resources/catalog/components/viewer/baselayerswitcher/BaseLayerSwitcherDirective.js
- web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextDirective.js
- web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextService.js
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/views/default/config.js
- web-ui/src/main/resources/catalog/views/default/module.js
- web/src/main/webapp/xslt/base-layout-cssjs-loader.xsl
- web/src/main/webapp/xslt/common/base-variables.xsl
Load `viewerMap` in `mapsManager` as it was done for `searchMap`.
Fix `mapsManager` issues and move the localStorage context loading in this service, from `OwsContextService`.
Add a map size load directive to tell when the map has an ok size to be fit.
This make `lastExtent` useless.
Make `baselayerDirective` more robust if the context has been loaded before directive.
Move url params `owscontext, layergroup, layername, wmsurl` to angular params
> Focus map loading in mapsManager

- web-ui/src/main/resources/catalog/components/common/map/mapsManager.js
Minor fix following #2580 
In some cases, a map view would be initialized even though the map container has no height (since the wheck is only done on the width)
> Check for height and width when initializing a map view

- web-ui/src/main/resources/catalog/components/common/map/mapsManager.js
- web-ui/src/main/resources/catalog/views/default/less/gn_map_default.less
Add expandable attribution control, in the bottom left corner of the map viewer and of the mini map.
Discussion [here](https://github.com/geonetwork/core-geonetwork/pull/2581).
> Add support to map attribution

- web-ui/src/main/resources/catalog/components/common/map/mapService.js
The field STYLES in requests to ESRI WMS services is mandatory. With this fix, every time the style is not indicated, the first one defined in the capabilities object is used.
#2409
> Fix for missing Styles on ESRI WMS requests

- web-ui/src/main/resources/catalog/components/common/map/mapService.js
- web-ui/src/main/resources/catalog/components/viewer/gfi/FeaturesLoader.js
This to remove a duplication of code introduced with these changes https://github.com/geonetwork/core-geonetwork/pull/2333
The metadataUUID is already available in the layer, so there is no need to extract it again from metadata record.
> Simplify metadataUuid management in mapService

- web-ui/src/main/resources/catalog/components/common/map/mapService.js
This check can avoid an unexpected behaviour that can compromise the stability of a GeoNetwork instance. The issue is described here https://github.com/geonetwork/core-geonetwork/issues/2569
This fix checks if a projection is supported before it breaks the system. If a projection is not supported a default one is used, and a warning is shown on the console together with a message that notifies the use of the default projection.
> Check for not supported map projections

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/webdav/Harvester.java
If there is a record with the same UUID harvested by another harvester, a NullPointerException is
thrown when it is harvested again from a WebDAV harvester with the Override option set:
```
2018-03-07 13:24:02,220 INFO  [localwebdav] - Start of alignment for : localwebdav
2018-03-07 13:24:02,253 WARN  [geonetwork.resources] - Resource not found images/harvesting/blank.png, default resource returned: /images/harvesting/blank.png
2018-03-07 13:24:02,280 ERROR [localwebdav] - Raised exception while harvesting from : localwebdav (WebDavHarvester)
2018-03-07 13:24:02,280 ERROR [localwebdav] -  (C) Class   : NullPointerException
at org.fao.geonet.kernel.harvest.harvester.webdav.Harvester.addMetadata(Harvester.java:276)
2018-03-07 13:24:02,280 ERROR [localwebdav] - …
```
> Fixes a NPE when override is set in WebDAV harvesters

- web-ui/src/main/resources/catalog/components/edit/directoryassociatedmd/DirectoryAssociatedMdDirective.js
- web-ui/src/main/resources/catalog/components/edit/directoryentryselector/DirectoryEntrySelector.js
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
- web-ui/src/main/resources/catalog/components/edit/recordfragmentselector/RecordFragmentSelector.js
- web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js
- web-ui/src/main/resources/catalog/components/search/searchmanager/SearchManagerService.js
- web-ui/src/main/resources/catalog/js/admin/HarvestSettingsController.js
- web-ui/src/main/resources/catalog/views/default/module.js
This is mainly to improve search statistics reports and have a more representative search service information.
Currently "qi" which could be defined as internal search service is never used by the Angular app - as it was in the ExtJS app.
> Make distinction between user search and internal queries made by the app

- services/src/main/java/org/fao/geonet/api/records/attachments/FilesystemStore.java
- web-ui/src/main/resources/catalog/components/filestore/partials/filestore.html
If attachement's file name contains characters that need to be encoded in URL, they are not for now
In the XML
Should be
Thinking of how to migrate existing records ... any suggestions welcomed.
> Metadata file store / Encode file name for URL.

- core/src/main/java/org/fao/geonet/kernel/GeonetworkDataDirectory.java
- core/src/test/java/org/fao/geonet/kernel/AbstractGeonetworkDataDirectoryTest.java
- services/src/main/java/org/fao/geonet/api/site/SiteInformation.java
- services/src/main/java/org/fao/geonet/services/config/GetInfo.java
- web/src/main/java/org/fao/geonet/Geonetwork.java
At some point, spatial searches are not working when using Shapefile for spatial index. It looks like search by FID is not working here https://github.com/geonetwork/core-geonetwork/blob/develop/core/src/main/java/org/fao/geonet/kernel/search/spatial/SpatialFilter.java#L199-L200. Reading https://osgeo-org.atlassian.net/browse/GEOT-5830, it could be related to feature deletion. 
Disabling fix index file looks to solve the issue.
Anyone having this error could try this fix ?
This PR also remove the unused spatialindex folder created in the datadir. Shapefile is created in index folder with Lucene one.
> Fix spatial search not working with shapefile sometimes

- web-ui/src/main/resources/catalog/components/utility/UtilityService.js
- web-ui/src/main/resources/catalog/js/admin/AdminController.js
- web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js
- web-ui/src/main/resources/catalog/js/edit/EditorController.js
The editor permalink allows users to point to a specific section of the editor
and use it in emails or links in the application.
The permalink is structured as followed:
```
http://localhost:8080/geonetwork/srv/eng/catalog.edit
#/metadata/{metadataId}?
tab={tabIdentifier}&
scrollTo={elementSelector}&
displayAttributes=true&
displayTooltips=true&
displayTooltipsMode={icon|onhover}
```
The path part of the URL (after the # and before the ?) define
the identifier of the metadata record to edit with the **metadataId** parameter.
Then the search part of the URL define a set of parameters
to customize the editor:
* **tab**: One tab identifier defined in config-editor.xml (eg. identificationInfo, metadata, xml). Remember a view is composed of one or more tab. Point to a tab to define which view …
> Editor / Add permalink

- core/src/main/java/org/fao/geonet/web/GeoNetworkHttpSessionRequestCache.java
- web/src/main/webapp/WEB-INF/config-security/config-security-core.xml
The issue is described here https://github.com/geonetwork/core-geonetwork/issues/2379
It happens randomly after valid sign in process.
This happens because multiple requests are done by ajax calls to server and HttpSessionRequestCache (from spring security web) stores only the last request and then redirect to this url after successful login. 
This solution proposed here is to contain the problem by filtering the urls where the browser should not be redirect.
In this PR are considered valid the any .../catalog.*/... and .../admin.console/... but probably there are more.
This bug is really annoying, please let me know your thoughts.
> ISSUE 2379 - Applying a match filter to RequestCache

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcService.js
Some schemas, like iso19139.nl.services.1.2.1, require an additional parameter for creating the `srv:operatesOn` element.
See issues #757, #2463 and commit metadata101/iso19139.nl.services.1.2.1@2ede1ef3c5.
> source parameter for dataset-add process

- services/src/main/java/org/fao/geonet/guiservices/metadata/Sitemap.java
a 20000 records request (doesn't hang the system anymore) but still takes 20 seconds, we have tha pagination in place, so why not decrease it a bit...
> decrease page size in sitemap pagination

- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
- web/src/main/webapp/xslt/common/render-html.xsl
adds some social media annotations + canonical link to metadata details page to optimise browsing and search experience, resolves #2653
todo: add to iso19115-1 the getMetadataThumbnail override, that returns a single thumbnail url
> adds some social media annotations to metadata detail page

- schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields-date.xsl
- schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields.xsl
- web-ui/src/main/resources/catalog/components/edit/datepicker/partials/datepicker.html
- web-ui/src/main/resources/catalog/style/gn_editor.less
- web-ui/src/main/resources/catalog/views/default/less/gn_view.less
- web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
This is replacing PR: https://github.com/geonetwork/core-geonetwork/pull/2475
The padding for the column in tables in the editor (with class `gn-table`) is removed. The column labels and input elements are now aligned properly. This removal is done by adding classes that remove the padding (e.g. `.nopadding-in-table`)
**Screenshot of old situation**
**Screenshot of new situation**
Also padding is removed around datepickers.
**Screenshot of the old situation**
**New Situation**
> Remove whitespace in editor table and datepicker (replaces PR: #2475)

- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/csw.html
The schema fields are now displayed beside each other to highlight that they are connected.
Fixes: https://github.com/geonetwork/core-geonetwork/issues/2608
> Align schema fields in CSW harvester: Fixes #2608

- services/src/main/java/org/fao/geonet/api/records/MetadataApi.java
- services/src/main/java/org/fao/geonet/api/records/formatters/FormatterApi.java
When received 'Accept: \*/\*' header at `/api/records/{uuid}` or
`/api/records/{uuid}/formatters/xsl-view` return HTML instead of a 400 error.
Fixes #2567.
> Allow 'Accept: */*' header in '/api/records/{uuid}' request

- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
This fix a bug on full view of metadata ISO19110 (and in general on every metadata record containing no tabs) that shows nothing but the title.
With this fix the content is shown also if not in tabs.
https://github.com/geonetwork/core-geonetwork/issues/2562
> Missing content in metadata full view (ISO19110)

- core/src/main/java/org/fao/geonet/kernel/mef/Importer.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFsHarvesterFileVisitor.java
Currently local filesystem harvester harvests only .xml files.
This PR add a light support for MEF files as well.
All harvesting options are supported the same way.
MEF are processed with `MEFLib.doImport` method.
Also Fix the groupOwner attribution in MEF importer.
> Support MEF in LocalFilesystemHarvester

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html
- web-ui/src/main/resources/catalog/style/gn.less
Set a max height for the content of a dialog body so it fits on small screens.
Add a new class to calculate the height of a div with the class `gn-modal-content`, the height is based on the max height of it's container: `modal-body`. Also `overflow: auto` is added to the class to get a scrollbar when needed.
Fix for: https://github.com/geonetwork/core-geonetwork/issues/2685
> Fix for add-resource panel content: #2685

- core/src/main/java/org/fao/geonet/kernel/mef/Importer.java
`finalGroupId` was always `null`, non-sense, but now default value is empty string.
Add double check.
> Fix MEF harvesting if no groupId specified

- core/src/main/java/org/fao/geonet/kernel/EditLib.java
- core/src/main/java/org/fao/geonet/kernel/schema/MetadataType.java
- core/src/test/java/org/fao/geonet/kernel/EditLibIntegrationTest.java
- services/src/main/java/org/fao/geonet/api/records/editing/EditUtils.java
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html
- web-ui/src/main/resources/catalog/style/gn.less
last commit (rebased on top, "do not want last text to override content") avoid csw
```xml
<gn_replace>
<gco:Date xmlns:gco="http://www.isotc211.org/2005/gco">2018-11-01T00:00:00</gco:Date>
</gn_replace>
```
to fail when 
```xml
<gn_replace><gco:Date xmlns:gco="http://www.isotc211.org/2005/gco">2018-11-T00:00:00</gco:Date></gn_replace>
```
works.
previous commits are opportunist refactorings.
> Csw gn replace ignoring carriage return

- web-ui/src/main/resources/catalog/templates/admin/harvest/type/arcsde.html
In a ArcSDE harvester when `postgres` connection type is selected the harvester
fails with an `ArcSDEConnectionType JDBC for database type postgres not supported`.
This commit fixes this exception (#2636).
> Fixes postgres database type not supported in ArcSDE harvester.

- web-ui/src/main/resources/catalog/templates/top-toolbar.html
- web-ui/src/main/resources/catalog/views/default/less/gn_navbar_default.less
When you give your GeoNetwork a long name/title, and you are logged in, there is the possibility that the name and menu buttons do not fit and the admin menu is displayed on a new line (see screenshot)
**A long title forces the admin menu on a new line**
This PR adds a (general) class to the name (`gn-name`) to make it more unique, and adds a class to the name (`gn-truncate`) when you are logged in. The less file will then truncate the text and add an overflow.
**The truncated title**
This solution is not fool proof, you can use even longer titles or a very wide logo and then the problem will be back again, but it will cover most cases.
> Truncate a long GeoNetwork name

- core/src/main/java/org/fao/geonet/constants/Geonet.java
- core/src/main/java/org/fao/geonet/kernel/DataManager.java
- core/src/main/java/org/fao/geonet/kernel/search/SearchParameter.java
- core/src/main/java/org/fao/geonet/kernel/search/UserQueryInput.java
- services/src/main/java/org/fao/geonet/api/userfeedback/UserFeedbackAPI.java
- services/src/main/java/org/fao/geonet/api/userfeedback/service/UserFeedbackDatabaseService.java
- web-ui/src/main/resources/catalog/components/userfeedback/GnUserfeedbackDirective.js
- web/src/main/webapp/WEB-INF/config-lucene.xml
Concept of advanced user feedback was introduced in https://github.com/geonetwork/core-geonetwork/pull/2419.
This pull request improves:
* the average rating was not index in Lucene in the rating field. So sorting by rating and stars displayed in search results are wrong. (Fix https://github.com/geonetwork/core-geonetwork/pull/2419#issuecomment-383503510)
* add the possibility to search by feedback count eg. get records with 20 to 30 feedbacks and having rating between 3 and 5  http://localhost:8080/geonetwork/srv/fre/q?_ratingFrom=3&_ratingTo=5&feedbackCountFrom=20&feedbackCountTo=30
@PascalLike Would be good that you have a look too ? Thanks
> User feedback / In advanced mode, improve indexing and add search

- services/src/main/java/org/fao/geonet/api/records/MetadataUtils.java
Angular code expects a null value instead of empty array when there are no feature catalogs associated with the record.
> Fix for feature catalog return null when empty

- core/src/main/java/org/fao/geonet/kernel/setting/Settings.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/HarvestManagerImpl.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/HarvesterJob.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/arcsde/ArcSDEHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/CswHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geoPREST/GeoPRESTHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/GeonetHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet20/Geonet20Harvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFilesystemHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/oaipmh/OaiPmhHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/ogcwxs/OgcWxSHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/thredds/ThreddsHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/webdav/WebDavHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/wfsfeatures/WfsFeaturesHarvester.java
- harvesters/src/main/java/org/fao/geonet/services/harvesting/Get.java
- harvesters/src/main/java/org/fao/geonet/services/harvesting/Info.java
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v342/migrate-default.sql
This pull request adds a system settings to specify a list of disabled harvester protocols. 
* These harvester's protocols will not be returned by the get available protocols operation, so no new harvesters of these disabled types can be created.
* For the existing harvesters, if they are of one of the disabled types, they will not be shown in the harvester list in the admin console. 
* Also, if an existing harvester belong to a disabled type and it is scheduled it will return immediately  if it is launched by the scheduler.
This fixes issue #2607.
> Make configurable in the admin settings a list with disabled harvester protocols

- web-ui/src/main/resources/catalog/components/viewer/baselayerswitcher/partials/baselayerswitcher.html
- web-ui/src/main/resources/catalog/components/viewer/owscontext/partials/owscontext.html
Move the onClick handler for resetting the map from the div to the contained button to avoid that clicking outside the button result in a map reset.
> Move the click event handler to the button for Reset map

- schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields-date.xsl
- schemas/iso19139/src/main/plugin/iso19139/layout/layout.xsl
This pull request allows to define a custom label element in `config-editor.xml` for a date field to override the one in `labels.xml`, like:
```
<field
name="referenceDate"
xpath="/gmd:MD_Metadata/gmd:identificationInfo/*/gmd:citation/gmd:CI_Citation/gmd:date"/>
```
If `strings.xml` contains an element `<referenceDate>Reference Date</referenceDate>` will be shown that label.
This mechanism was already support for other elements.
> Support override label for iso19139 date fields

- schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields.xsl
Similar to https://github.com/geonetwork/core-geonetwork/pull/2767, but for bbox. Apologies as noticed about this element after https://github.com/geonetwork/core-geonetwork/pull/2767 was merged.
> Support override label for iso19139 geographic bounding box

- services/src/main/java/org/fao/geonet/api/users/transfer/TransferApi.java
Please check details in #2738, used to work differently in old versions. 
The change seem fine, but not sure if the current behaviour was added for any reason that I can be missing?
> User Admins can transfer ownership of records outside of their groups). Fixes #2738

- web-ui/src/main/resources/catalog/components/common/map/mapService.js
Better handling of WFS: now we use on the query the version of WFS returned on the GetCapabilities and try to accomodate to each version details (GML version).
Also applying a fix  which is not asking for bounding box on WFS 1.1.0. That will return all features. Because ArcGIS is a mess. See below to get the detailed explanation:
Example of failing ArcGIS service:
If I don't use any bbox, it returns all features on WFS 1.1.0. So the layer has content:
http://sedsh127.sedsh.gov.uk/arcgis/services/ScotGov/ProtectedSites/MapServer/WFSServer?service=WFS&request=GetFeature&version=1.1.0&srsName=EPSG:27700&typename=PS:Cairngorms_National_Park
If I use the same bbox as in WFS 1.0.0:
In 1.0.0 works:
http://sedsh127.sedsh.gov.uk/arcgis/services/ScotGov/ProtectedSites/MapServer/WFSServer?service=WFS …
> Bug fix: better WFS handling (failed on some corner cases)

- schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
- schemas/iso19139/src/main/plugin/iso19139/update-fixed-info.xsl
Changes:
- Action to add the temporal extent in the INSPIRE view, if the element is missing.
- When deleting the element, remove the container element to avoid this empty element:
```
<gmd:extent>
<gmd:EX_Extent/>
</gmd:extent>
```
That causes in the schematron iso the following validation issue:
```
[ISOFTDS19139:2005-TableA1-Row23] - Extent element required
In extent section, one of the following elements need to be defined : description, geographicElement, temporalElement, verticalElement. 
count(description + geographicElement + temporalElement + verticalElement) > 0.
```
> INSPIRE view - allow to add temporal extent element if missing, cleanup up it's parent when removing it, if doesn't contain any other child

- web-ui/src/main/resources/catalog/components/utility/UtilityService.js
there are place where gnLocalized filter is called with no dom available, so with no scope available, so with no lang available, and in this case have to look for lang using what is set thru gn_locale services.
> allow use of gnLocalized filter from gnRelatedService

- web-ui/src/main/resources/catalog/js/CatController.js
If the Gazetteer URL is not defined in the Config UI JSON string use the one in `defaultConfig` var as URL.
Related to #2690.
> Set the Gazetteer default URL if it is not defined in Config UI

- web-ui/src/main/resources/catalog/components/viewer/baselayerswitcher/BaseLayerSwitcherDirective.js
- web-ui/src/main/resources/catalog/components/viewer/baselayerswitcher/partials/baselayerswitcher.html
- web-ui/src/main/resources/catalog/style/gn_search.less
This PR replaces #2488 but using ngeo-popover instead of customising the JS for the list's positioning.
If there are many base layers available the dropdown menu hide some of them. This commit changes the dropdown menu by a ngeo-popover component.
Original problem: 
Using `ngeo-popover`:
> Fix base layer dropdown cut with many layers present (using ngeo-popover)

- core/src/main/java/org/fao/geonet/web/XFrameOptionsFilter.java
Previously `SAMEORIGIN` mode wasn't working without a `url` parameter, but now it should be.
@josegar74 could you please take a look? Thanks
> Fix for allowing SAMEORIGIN mode in XFrameOptions filter

- services/src/main/java/org/fao/geonet/api/records/editing/MetadataEditingApi.java
- web-ui/src/main/resources/catalog/components/metadatamanager/EditorService.js
The option to display attributes ("More details") was lost when doing ajax editing.
> Fix #2511 Nil Reason is hidden when added

- core/src/main/java/org/fao/geonet/migration/JsonDatabaseMigration.java
- web/src/main/java/org/fao/geonet/DatabaseMigration.java
- web/src/main/webResources/WEB-INF/config-db/database_migration.xml
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v343/AdvancedSearchFormMigration.java
- web/src/test/java/v343/AdvancedSearchFormMigrationTest.java
With this refactor the only things needed to implement a `JsonDatabaseMigration` is to define the setting name to update and the list of JSON paths to update/modify in the method `setUpNewSettingValues`.
This PR also moves `AdvancedSearchFormMigration` to version v3.4.3 since the PR #2547 was not included in v3.4.2 release.
Another fix in this PR is to use the right types for map values in `database-migration.xml`.
> Refactor JsonDatabaseMigration to make easier to implement future JSON setting migrations

- web-ui/src/main/resources/catalog/components/admin/harvester/HarvesterDirective.js
- web-ui/src/main/resources/catalog/components/admin/harvester/partials/privileges.html
- web-ui/src/main/resources/catalog/style/gn_admin.less
This PR brings two changes:
- Prior to modifications, we were enable to check a single group. This is now fixed 
- Instead of having private/public buttons, we use the same mechanism as the one in metadata privileges attributions.
> Fix and adapt privileges for harvest

- web-ui/src/main/resources/catalog/components/viewer/wps/WpsDirective.js
- web-ui/src/main/resources/catalog/components/viewer/wps/WpsService.js
- web-ui/src/main/resources/catalog/components/viewer/wps/partials/processform.html
- web-ui/src/main/resources/catalog/style/gn_viewer.less
Some new options & improvements on the WPS form directive:
* `hide-title` and `cancel-previous` allows for finer tuning of the form behaviour (previously all previous requests to WPS endpoints would be cancelled when a new one was made)
* Some minor UI improvements
* Provided a callback for when the WPS process is described, i.e. the response to `DescribeProcess` has been received and correctly parsed
> Small improvements to WPS directive API

- core/src/main/java/org/fao/geonet/kernel/search/CaseInsensitiveFieldComparatorSource.java
- core/src/main/java/org/fao/geonet/kernel/search/LuceneSearcher.java
- csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/CatalogSearcher.java
- schemas/iso19139/src/main/plugin/iso19139/index-fields/index-subtemplate.xsl
CaseInsensitiveFieldComparatorSource.java is used for example for sorting subtemplate before to display them in a paginated list. Bottom refer to the last element of the requested page.
In the case of subtemplate, element are first sorted on docLocale, then on _tilte (attempt on "_title|{searchLang}", then on "_title" if  "_title|{searchLang}" not defined).
If monolingual subtemplate, docLocale should also be defined, as for multilingual.
> Ordering subtemplate fixes

- web-ui/src/main/resources/catalog/components/viewer/wmsimport/WmsImportDirective.js
Fixing $translate dependency injection in gnKmlImport directive. This fix makes possible to load correctly a layer over the map through a kmz file.
> Fix $translate dependency injection in gnKmlImport directive

- web-ui/src/main/resources/catalog/components/edit/validationreport/ValidationReportDirective.js
- web-ui/src/main/resources/catalog/components/edit/validationreport/partials/validationreport.html
- web-ui/src/main/resources/catalog/locales/en-editor.json
- web-ui/src/main/resources/catalog/style/gn_editor.less
In the metadata editor, can be useful to have fixed on top of the page the validation results box, to have the informations on screen while checking the metadata issues. https://github.com/geonetwork/core-geonetwork/issues/2560
This mode is activated/deactivated with a button on the top of the validation results panel
> Button to keep the validation panel on top in md editor

- core/src/main/java/org/fao/geonet/kernel/search/LuceneOptimizerManager.java
regardless of whether the process is enabled or not (see #2771), instantiate the member variables
Tests: only on the core module, utests:
```
Tests run: 400, Failures: 0, Errors: 0, Skipped: 4
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:22 min
[INFO] Finished at: 2018-05-16T14:16:03+02:00
[INFO] Final Memory: 36M/401M
[INFO] ------------------------------------------------------------------------
```
> Lucene optimizer - instantiate variables in ctor

- web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionsDirective.js
- web-ui/src/main/resources/catalog/components/metadataactions/partials/transferownership.html
- web-ui/src/main/resources/catalog/locales/en-search.json
Currently, when there are no users to transfer ownership an empty drop-down is shown. This change introduces a "No users" message in place of the empty drop-down.
> Fix transfer ownership message when no users available

- common/src/main/java/org/fao/geonet/utils/Version.java
- core/pom.xml
- core/src/main/java/org/fao/geonet/kernel/SchemaManager.java
- core/src/main/java/org/fao/geonet/kernel/schema/MetadataSchema.java
- pom.xml
- schemas-test/pom.xml
- schemas/csw-record/pom.xml
- schemas/csw-record/src/main/plugin/csw-record/schema-ident.xml
- schemas/dublin-core/pom.xml
- schemas/dublin-core/src/main/plugin/dublin-core/schema-ident.xml
- schemas/iso19110/pom.xml
- schemas/iso19110/src/main/plugin/iso19110/schema-ident.xml
- schemas/iso19139/pom.xml
- schemas/iso19139/src/main/plugin/iso19139/schema-ident.xml
- schemas/pom.xml
- schemas/schema-core/pom.xml
- web/pom.xml
- web/src/main/java/org/fao/geonet/DatabaseMigration.java
- web/src/main/webapp/xml/validation/schemaPlugins/schema-ident.xsd
Currently the metadata schemas use the same versioning for the maven `artifactId` as the other modules.
While this is ok for schemas bundled in GeoNetwork, it's hard to maintain for third party schemas for example from https://github.com/metadata101/ when adding them as submodules (you can add them as a copy in your project, but then you loose the advantages of submodules):
* You need to keep them aligned with the related latest branch in GeoNetwork: 3.4.1-SNAPSHOT, 3.4.2-SNAPSHOT, etc.
* Also means that when updated to the latest branch in GeoNetwork, the schemas can't be used easily in a previous releases for the same branch.
This pull request changes the `artifactId` number for schemas module, so for GeoNetwork 3.4.x branch we use for shemas the `artifactId` 3.4. In the future, when …
> Remove minor version number from schema artifacts

- web-ui/src/main/resources/catalog/components/utility/CORSInterceptor.js
so http-error-cases are not entered, for example on #2837
> interceptor resolves errors unexpectedly

- web-ui/src/main/resources/catalog/components/search/searchfiltertag/SearchFilterTagsDirective.js
See issue details in #2869
Tested the fix with other facets and look fine also, displaying the labels.
> Search page - filter tag for inspire themes thesaurus is not translated. Fixes #2869

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Harvester.java
Additional fix related to #2810.
Some catalogues return the translation element in the source information, but it's empty. In this case should be used the default translations created from the source name.
> GeoNetwork harvester issues with sources - store remote source translations if available - Check if translation element has values #2810 

- web-ui/src/main/resources/catalog/components/common/languageswitcher/LanguageSwitcherDirective.js
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid.html
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid4maps.html
- web-ui/src/main/resources/catalog/components/viewer/owscontext/partials/owscontext.html
- web-ui/src/main/resources/catalog/components/viewer/partials/mainviewer.html
- web-ui/src/main/resources/catalog/components/viewer/searchlayerformap/partials/searchlayerformap.html
- web-ui/src/main/resources/catalog/lib/angular.ext/template/tabset.html
- web-ui/src/main/resources/catalog/locales/en-core.json
- web-ui/src/main/resources/catalog/style/gn_badge_categories.less
- web-ui/src/main/resources/catalog/templates/top-toolbar.html
- web-ui/src/main/resources/catalog/views/default/directives/partials/infolist.html
- web-ui/src/main/resources/catalog/views/default/less/gn_topics_default.less
- web-ui/src/main/resources/catalog/views/default/templates/home.html
- web-ui/src/main/resources/catalog/views/default/templates/index.html
- web-ui/src/main/resources/catalog/views/default/templates/searchForm.html
- web/src/main/webapp/xslt/skin/default/skin.xsl
This PR focusses on the homepage for a user who is not logged in. The colour scheme is not changed, so some colours still need more contrast.
Everything is tested with the Axe plugin: https://www.deque.com/axe/
Changes are made for images (alt attribute), labels and ARIA attributes for the search results:
* Screenreader only labels for search buttons
* Add aria label to the search buttons
* Add aria label to the language switcher
* Add Landmark role to the main content
* Remove duplicate ID's
* Alt text for the logo
Correct ARIA roles for the homepage:
* for tabs, tabpanels
* grid
* language switcher
> Web Accessibility for the homepage

- schemas/iso19139/src/main/plugin/iso19139/index-fields/default.xsl
- schemas/iso19139/src/main/plugin/iso19139/index-fields/language-default.xsl
- web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js
- web-ui/src/main/resources/catalog/views/default/templates/recordView.html
CRS is now indexed as a JSON object with `code` and `codeSpace` as separate keys, to allow better rendering when the code space is missing.
Fixes #2357
> Improve CRS details indexing & rendering

- web-ui/src/main/resources/catalog/js/GnFormatterLib.js
- web/src/main/webapp/WEB-INF/data/data/formatter/groovy/common/Handlers.groovy
- web/src/main/webapp/WEB-INF/data/data/formatter/html/view-header.html
Previously the Groovy formatter would always show the Overview tab by default.
With this PR, by passing a `tab=...` argument to the formatter API, other tabs can be shown as well (useful for permalinks). For example:
```
http://localhost:8080/geonetwork/srv/api/records/c8f3043a-b7b0-468d-9470-274be47371e5/formatters/full_view?output=xml&tab=complete
```
Accepted values for all records are:
* `overview`: default behaviour
* `associated`: associated resources (will be empty if none found)
* `complete`: complete view
Other tabs depend on the record XML and may also be shown using their `rel` attribute, e. g.:
* `.gmd_identificationInfo`
* `.gmd_distributionInfo`
* `.gmd_identificationInfo`
* etc.
> Groovy Formatter / allow showing a tab other than the Overview

- web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
- web-ui/src/main/resources/catalog/components/viewer/wfs/partials/download.html
- web-ui/src/main/resources/catalog/templates/editor/editorboard.html
- web-ui/src/main/resources/catalog/templates/top-toolbar.html
- web-ui/src/main/resources/catalog/views/default/directives/partials/mdactionmenu.html
- web-ui/src/main/resources/catalog/views/default/less/gn_result_default.less
- web-ui/src/main/resources/catalog/views/default/templates/recordView.html
This PR focusses on the detail/result page for a user who is not logged in. The colour scheme is not changed, so some colours still need more contrast.
Issues addressed in this PR for roles, labels and ARIA attributes:
- added role `menuitem` to dropdown menu items
- added `aria-label` to buttons
- headings in the right order (`<h3>` follows `<h2>` follows `<h1>`)
> Accessibility for the Details/Result page

- web-ui/src/main/resources/catalog/templates/new-account.html
- web-ui/src/main/resources/catalog/templates/new-password.html
- web-ui/src/main/resources/catalog/templates/signin.html
- web-ui/src/main/resources/catalog/templates/top-toolbar.html
- web-ui/src/main/resources/catalog/views/default/less/gn_login_default.less
- web/src/main/webapp/xslt/base-layout.xsl
This PR focusses on the **login** page, **new account** page, **reset password** page. The colour scheme is not changed, so some colours still need more contrast.
Issues addressed in this PR:
- added `aria-labels` for buttons and inputs
- main landmark added to each page
- add a main heading (`<h1>`)
> Accessibility features and attributes for Login pages

- web-ui/src/main/resources/catalog/components/common/savedselections/partials/action.html
- web-ui/src/main/resources/catalog/components/search/pagination/partials/pagination.html
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/selection-widget.html
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/editor.html
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/geocat.html
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid.html
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/list.html
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/titlewithselection.html
- web-ui/src/main/resources/catalog/locales/en-core.json
- web-ui/src/main/resources/catalog/locales/en-search.json
- web-ui/src/main/resources/catalog/templates/editor/directory.html
- web/src/main/webapp/xslt/base-layout.xsl
This PR focusses on the search page for a user who is not logged in. The colour scheme is not changed, so some colours still need more contrast.
This PR is builds on an earlier (and merged) PR (https://github.com/geonetwork/core-geonetwork/pull/2893).
Issues addressed in this PR for images (alt attribute), labels and ARIA attributes:
* Remove `user-scalable` form the meta tags
* Screenreader only labels for pagination
* New language items for screenreader only labels
* Add alt attribute for thumbnails
* Add roles to items in dropdown menus
* Add `aria-label` to checkboxes
Everything is tested with the Axe plugin: https://www.deque.com/axe/
> Accessibility for the Search page

- web-ui/src/main/resources/catalog/views/default/less/gn_search_default.less
Fix for issue: https://github.com/geonetwork/core-geonetwork/issues/2918
Keywords were breaking out of the searchbox. Now long keywords are displayed on more than one line.
> Fix for too long keywords in the advanced search form (#2918)

- services/src/main/java/org/fao/geonet/services/region/GetMap.java
- web-ui/src/main/resources/catalog/views/default/templates/recordView.html
Fixes #2281 
Previously the GetMap API would not accept a named layer in the database setting (although it accepted one when given in the URL param `background`).
> Use database setting for the map in simple record view

- schemas/iso19139/src/main/plugin/iso19139/layout/layout.xsl
Fix for https://github.com/geonetwork/core-geonetwork/issues/2940
> Editor / Topic category / + should not be displayed #2940.

- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
When merged will cherry-pick to 3.4.x branch. Fixes #2803
> Geonames search when editing a record doesn't seem to be working. Fixes #2803

- core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java
- services/src/main/resources/org/fao/geonet/api/Messages.properties
- services/src/main/resources/org/fao/geonet/api/Messages_fre.properties
A number of links are invalid in emails sent when changing the status of a record
Contains "//" and invalid content at the end.
> Workflow / Fix invalid links in email.

- web-ui/src/main/resources/catalog/components/common/needhelp/NeedHelpDirective.js
This fix the links to the doc available with the need help directive which currently return 404
> The doc in the website looks to have moved to some new folder.

- web-ui/src/main/resources/catalog/style/gn_viewer.less
Fix for issue: https://github.com/geonetwork/core-geonetwork/issues/2917
Changes in this PR:
- small position changes for the feature info popup
- no more opacity (accessibility)
- added box-shadow
- control tools are positioned absolute for the tooltips to display over the featureinfo
**Screenshot after the fix:**
> Fix for gfi result to pop over panels (#2917)

- web-ui/src/main/resources/catalog/views/default/less/gn_footer_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_search_default.less
Small fix for content that mixed/overlapped with the footer. The footer now has a z-index and the `.gn-search-page` now has a padding at the bottom so the content can be accessed and doesn't display behind the footer.
**Screenshot of the overlap:**
> Fix for content that is overlapping the footer

- services/src/main/java/org/fao/geonet/api/records/formatters/SchemaLocalizations.java
Due to URL change with the API. Use request accept language header instead.
Step to reproduce: Try to open a formatter in a language which is not english = field label not translated
> Formatter / Schema resources are not properly loaded 

- schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
Having a record with a parent identifier is encoded as multilingual string
```
<gmd:fileIdentifier>
<gco:CharacterString>290bb420-7ded-4195-9a54-8a9fc6e64670</gco:CharacterString>
</gmd:fileIdentifier>
codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml#MD_CharacterSetCode"/>
</gmd:characterSet>
<gmd:parentIdentifier xsi:type="gmd:PT_FreeText_PropertyType">
<gco:CharacterString>04f28da2-ea7d-4ffc-b74a-ebb550748bf7</gco:CharacterString>
<gmd:LocalisedCharacterString locale="#FR">04f28da2-ea7d-4ffc-b74a-ebb550748bf7</gmd:LocalisedCharacterString>
</gmd:PT_FreeText>
</gmd:parentIdentifier>
```
Configure parent identifier to be excluded from multilingual fields.
> ISO19139 / Parent identifier is not multilingual

- web/pom.xml
These jars should be provided by the servlet container.
Note: If Hadoop transitively requires jetty + jetty:jsp-api + servlet-api (in wfsfeature-harvester subproject), there is probably a good reason for this. I preferred to exclude the dependencies from the web/pom.xml instead of acting on each maven subprojects.
Note 2: some classes actually require the servlet-api jar, so I added it as a dependency, but keeping it away from the resulting artifact using the 'provided' scope.
Tests: compilation + runtime on web, no issue so far.
> Excluding servlet-related dependencies (#1912)

- services/src/main/java/org/fao/geonet/api/site/SiteApi.java
Fix for issue: https://github.com/geonetwork/core-geonetwork/issues/2992
Change the upload directory of the `favicon.png`. The favicon is now uploaded to the `images/logos` directory where the xslt expects it to be.
> Fix for Favicon doesn't work (#2992)

- web-ui/src/main/resources/catalog/style/gn.less
- web-ui/src/main/resources/catalog/templates/top-toolbar.html
- web-ui/src/main/resources/catalog/views/default/less/gn_navbar_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_variables_default.less
- web-ui/src/main/resources/catalog/views/default/templates/footer.html
Fix for https://github.com/geonetwork/core-geonetwork/issues/2934
Display the menubar with labels on small screens.
**Screenshot with labels and user/profile menu:**
Changes made:
- hide icons
- added a user/profile submenu
- fix for height when logged in (caused by truncating long GN title)
- layer indicator doesn't need whitespace anymore
- added margin in footer on small screens
- added class `fa-fw` to icon on the navbar
> Fix for small display does not have menu labels #2934

- web-ui/src/main/resources/catalog/components/common/map/mapService.js
When the online resource defines a URL with extra parameters like getCapabilities, addToMap fails.
this is on the main map, if you click add-2-map from metadata and the wms url has http://.../wms?Request=getcapabilities
> Bug fix: Prefer to use capabilities url instead of hand-hard-coded URL.

- core/src/main/java/org/fao/geonet/util/XslUtil.java
- web-ui/src/main/resources/catalog/components/common/map/mapDirective.js
- web-ui/src/main/resources/catalog/components/common/map/mapsManager.js
- web-ui/src/main/resources/catalog/components/edit/bounding/BoundingDirective.js
* Previously, automatic generation of bounding box from a bounding polygon might fail on certain system (depending on locale). This is now fixed. Typical error was coordinates with `,` instead of `.` as decimal separator, which resulted in this:
* Bounding polygon map now initializes properly using the `sizePromise` available on maps created by the Maps Manager. I have taken the liberty to adapt the bounding box map too (though it had already been fixed in https://github.com/geonetwork/core-geonetwork/pull/2811/commits/459ea1aea0bdd0a6a0d7a41b171468df3f1de542 ). Should be cleaner & more consistent.
This promise resolves when the map is created *and* is guaranteed to have a size.
> Editor / fix bugs on bounding box & bounding polygon editor

- web-ui/src/main/resources/catalog/templates/formatter-viewer.html
Previously the edit button present at the top of a formatted record was sometimes not pointing to the right URL (ie when `mdId` was not defined in the scope).
> Formatter / fix edit link in formatter header

- web-ui/src/main/resources/catalog/components/search/formfields/partials/sortByCombo.html
- web-ui/src/main/resources/catalog/components/search/pagination/partials/pagination.html
- web-ui/src/main/resources/catalog/views/default/less/gn_pagination_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_search_default.less
This PR focusses on accessibility changes for dropdowns for users that are not logged in. In addition to that some changes are made to get the same style and colors (also for accessibility) for the dropdowns on the results page.
**Screenshot of the same styles for the dropdowns:**
**Screenshot of the old situation:**
Changes:
- added roles to dropdowns
- small color changes for pagination
> Accessibility changes for dropdowns on results page

- web-ui/src/main/resources/catalog/components/common/map/mapService.js
Currently the new code for definition a WMTS layer projection does not always work as expected. See for example the endpoint `https://sextant.ifremer.fr/geowebcache/service/wmts`, layer `Sextant`.
This PR fixes this issue (along with some remaining tab/trailing space issues).
> Map / fix projection used when creating a WMTS layer

- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/list.html
- web-ui/src/main/resources/catalog/views/default/less/gn_results_default.less
Some (small) changes where made to the search result list view (not the default grid view). Color (contrast) changes for accessibility, and some whitespace is added to improve readability.
Screenshot of new list:
Small changes to the list view of the search results:
- added whitespace between buttons and icons
- aligned elements to the top
- changed status style to meet accessibility standards
- uniform style for buttons
> Small accessibility and UI changes to the list view of the search results

- web-ui/src/main/resources/catalog/js/admin/AdminController.js
- web-ui/src/main/resources/catalog/locales/en-core.json
- web-ui/src/main/resources/catalog/templates/editor/editorboard.html
- web-ui/src/main/resources/catalog/templates/top-toolbar.html
The *Contribute* and *Admin console* dropdowns now have an explicit 'home' item:
Some users were having trouble finding the editor board UI for example, as they were expecting it to appear in the dropdown.
I've also changed the *Directory management* icon to make it more distinct.
> Toolbar / add explicit 'home' submenus

- schemas/iso19139/src/main/plugin/iso19139/index-fields/language-default.xsl
Currently, an online resource (aka *link*) will not be indexed if the name and desc are not translated in the current lang, although fallback values might be available in the default language.
I could not find any reason for this, and it caused some links to appear in certain languages but not others depending on which fields are translated or not.
> Indexing / improve fallback logic with online resources in multilingual records

- schemas/iso19139/src/main/plugin/iso19139/index-fields/default.xsl
Fixes #2719. Only create fields `inspiretheme`, `inspirethemewithac`, `inspiretheme_en`, `inspireannex` and `inspirecat` if the element `gmd:MD_keywords` contains the `GEMET - Inspire themes, version 1.0` thesaurus.
(PR #2733 in 3.4.x branch)
> Only index INSPIRE related fields if thesaurus is present

- web/src/main/java/org/fao/geonet/proxy/URITemplateProxyServlet.java
Some sites use the [Strict-Transport-Security policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security) to add another layer of safety by preventing access to their data in unsecured HTTP altogether.
When transmitted by the proxy, this policy may wrongly apply to a Geonetwork catalog, which may in turn cause some general trouble (inaccessible resources, errors...).
This PR prevents the proxy from forwarding the STS header.
> Proxy / do not forwards STS header

- web-ui/src/main/resources/catalog/js/edit/EditorController.js
Do not alter history when switching tabs. This means to close tab if empty history or use the redirectUrl parameter in other cases.
> Editor / Properly close editor tab when a new window is opened. 

- core/src/main/java/org/fao/geonet/kernel/search/LuceneSearcher.java
When a spatial search uses the `region:` prefix and no region is found for it in the thesaurus throw an `IllegalArgumentException` with message `"Geometry %s not found in the available source RegionDAO objects"` instead of letting JTS try to parse a null geometry and throw the cryptic `"Argument "env" should not be null."` error.
Also re-indent the class, organize the imports and upgrade the use of `StringUtils` class from Apache Commons to v3.
> Throws a more legible exception when region is not found

- domain/src/main/java/org/fao/geonet/domain/MetadataCategory.java
- services/src/main/java/org/fao/geonet/api/categories/TagsApi.java
Fixes a problem of `OutOfMemoryError` when the catalog has a lot of records with categories and the list of Groups is requested using the service `admin.group.list` since all the records assigned to each category was being returned to as part of the `records` collection.
This commit excludes the `records` property from the XML or JSON generated.
In `TagsAPI` now retrieves the number of records assigned to a category using a `count` query instead of loading all the records and counting the size of the collection returned.
Fixes #3002 too.
> OutOfMemoryError when listing groups using service admin.group.list

- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
- schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
Currently a CHOICE_ELEMENT element is added when building the metadocument for the editor. The XPath for matching a gml:beginPos or gml:endPos required an extra * parent to match due to this extra element added in between. BUT the XSLT formatter using the metadata document was failing to find a match due to that. Use // instead to match in both cases.
Same as https://github.com/geonetwork/core-geonetwork/pull/2868 for master
> Formatter / XSLT / Display temporal extent properly based on config editor

- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid4maps.html
- web-ui/src/main/resources/catalog/components/viewer/legendpanel/partials/legendpanel.html
- web-ui/src/main/resources/catalog/components/viewer/owscontext/partials/owscontext.html
- web-ui/src/main/resources/catalog/components/viewer/partials/mainviewer.html
- web-ui/src/main/resources/catalog/locales/en-search.json
- web-ui/src/main/resources/catalog/style/gn_viewer.less
- web-ui/src/main/resources/catalog/views/default/less/gn_map_default.less
In this PR the map tools and panels on the map did get some small style changes. The tools and the panel now look more like tabbed panels.
The content of the panels now has a more uniform look, all panels have a title and close button, have whitespace around titles and buttons. The tooltips of controls on the left side of the map are now opening to the right
Extra text and explanation has been added to several panels.
**Screenshot of the restyled buttons and panels**
Some changes have been made to the positioning of the tools on smaller screens, the control tools are displayed on the left side of the map on smaller screens and the searchbox is not overlapping other tools anymore.
**Screenshot of the map on smaller screens**
> Small styling and usability changes for the maptools

- core/src/main/java/org/fao/geonet/kernel/EditLib.java
- core/src/main/java/org/fao/geonet/kernel/schema/MetadataType.java
- core/src/test/java/org/fao/geonet/kernel/EditLibIntegrationTest.java
- services/src/main/java/org/fao/geonet/api/records/editing/EditUtils.java
come with a lot of refactoring.
for csw, trouble was that
```xml
<gn_replace>
<gco:Date>ValueTimestamp</gco:Date>
</gn_replace>
```
fails whereas 
```xml
<gn_replace><gco:Date>ValueTimestamp</gco:Date></gn_replace>
```
works.
so "do not want last text to override content".
relates to 
https://github.com/geonetwork/core-geonetwork/commit/d134d5a0d8dcbd0fa48584700c9772a084f649b2#diff-38f2b06a4b51beceb472a010acd91187
Files with more than 800 lines are in my opinion very hard to maintain, because hard to understand and hence forbidding evolution as we shouldn't modify something we don't understand.
> fix a bug in csw replace handling (do not want last text to override content)

- web-ui/src/main/resources/catalog/components/common/map/mapService.js
> Add WMS layer doesn't work fine when url ends with ? the proxy adds an extra ? character and the GetMap requests fail. Fixes #3088

- web-ui/src/main/resources/catalog/components/common/share/partials/panel.html
- web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js
- web-ui/src/main/resources/catalog/style/gn.less
- web-ui/src/main/resources/catalog/style/gn_search.less
- web-ui/src/main/resources/catalog/views/default/less/gn_variables_default.less
Change the opening of metadata action from popup to modal
Fix for https://github.com/geonetwork/core-geonetwork/issues/3063
**Screenshot of the modal dialog:**
The privileges table is made more responsive, columns are now the same width, labels are hidden on small screens.
**Screenshot of a small table on a small screen:**
> Change the metadata action popup to modal (#3063)

- services/src/main/java/org/fao/geonet/api/users/transfer/TransferApi.java
- web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionsDirective.js
- web-ui/src/main/resources/catalog/components/metadataactions/partials/transferownership.html
- web-ui/src/main/resources/catalog/js/admin/AdminToolsController.js
- web-ui/src/main/resources/catalog/locales/en-core.json
- web-ui/src/main/resources/catalog/templates/admin/tools/transferownership.html
When using the Transfer Owner tool, groups are now rendered a bit better:
* Admins are put in a separate group at the beginning of the list
* Group names are translated
Note that being able to transfer records to admins appears to be misleading to some users. Maybe this could be allowed or not in the settings?
> Transfer Owner / make dropdown content clearer

- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid4maps.html
- web-ui/src/main/resources/catalog/style/gn_search.less
- web-ui/src/main/resources/catalog/views/default/less/gn_search_default.less
Map thumbnails now render a bit more nicely, including a multiline overflow effect.
Home page:
Map tools:
When hovering a map preview, the tooltip will show the full title.
@MichelGabriel I've noticed you had reversed map title and thumbnail in #2997, didn't know if it was intentional considering the layout was a bit broken in the map tool and the change was not mentioned in your PR. Please let me know if this should be kept this way.
> Search / Better map thumbnails

- services/src/main/java/org/fao/geonet/api/registries/vocabularies/KeywordsApi.java
Some thesaurus downloaded from INSPIRE registry are not stored in UTF-8 when GeoNetwork
runs on Windows causing a `Error on line 1: Invalid byte 1 of 1-byte UTF-8 sequence.` exception.
This commit stores this file using UTF-8 charset.
Should be backported to 3.4.x branch.
> Fixes an error related to thesaurus encoding when uploading from a registry

- web-ui/src/main/resources/catalog/js/admin/DashboardWfsIndexingController.js
Minor fix to handle the case where the ES index holding WFS features is *not* named `features`.
> WFS Indexing dashboard / do not depend on index name

- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/js/GnEditorModule.js
- web-ui/src/main/resources/catalog/js/admin/DashboardController.js
- web-ui/src/main/resources/catalog/js/edit/AccessManagerController.js
- web-ui/src/main/resources/catalog/js/edit/EditorBoardController.js
- web-ui/src/main/resources/catalog/js/edit/EditorController.js
- web-ui/src/main/resources/catalog/locales/en-editor.json
- web-ui/src/main/resources/catalog/templates/editor/accessManager.html
- web-ui/src/main/resources/catalog/templates/editor/editorboard.html
- web-ui/src/main/resources/catalog/templates/top-toolbar.html
This new panel only accessible by administrator user when ElasticSearch index is populated
provides an overview of privileges for a set of records.
This panel can be accessed from the editor board.
Records can be filtered by title and publication group.
User can choose which types of operation and groups to preview.
This is using scripted fields in ES to create a field easily from a
simple expression; here, Is operation view available for group A?
This work is supported by Ifremer
> Access rights overview panel.

- services/src/main/java/org/fao/geonet/api/users/transfer/TransferApi.java
Followup of #3102
Without this fix, a useradmin (or any role other than admin) would only see him/herself in the Transfer owner dropdown.
> Transfer Owner / fix available user lists when I am not an admin

- web-ui/src/main/resources/catalog/components/common/map/mapService.js
wmts loading in ngeo expects tilematrixset SupportedCRS in capabilities to have urn format, ngeo-debug.js line 91346
```
projection = ol.proj.get(matrixSetObj['SupportedCRS'].replace(
/urn:ogc:def:crs:(\w+):(.*:)?(\w+)$/, '$1:$3'));
```
however many services use a plain epsg:xxx format
https://geodata.nationaalgeoregister.nl/tiles/service/wmts
by explicitly providing the projection in the config object, an error is prevented
> fix map loading in non-google projection

- web-ui/src/main/resources/catalog/components/metadataactions/partials/metadatacategoryupdater.html
- web-ui/src/main/resources/catalog/components/metadataactions/partials/metadatagroupupdater.html
- web-ui/src/main/resources/catalog/locales/en-core.json
- web-ui/src/main/resources/catalog/style/gn_editor.less
- web-ui/src/main/resources/catalog/templates/editor/editor.html
- web-ui/src/main/resources/catalog/templates/editor/top-toolbar.html
- web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_variables_default.less
- web/src/main/webapp/xslt/ui-metadata/menu-builder.xsl
Replaces PR: https://github.com/geonetwork/core-geonetwork/pull/3048
This PR focusses on the editor toolbar for logged in users.
**Screenshot with the simplified display menu on the right:**
Improved displaying of the editor toolbar:
- added `navbar-btn` to the buttons
- simplified the display menu (now with a `<button>` and not a `<a>`)
- changed the responsive breakpoint for the editor container
**Better displaying of the buttons on small screens:**
Added a11y options:
- added titles and roles to the menu and menu items
- aria labels
- added `<h1>` to the page
- added main landmark
- added more color contrast to the toolbar
> Accessibility option and better responsiveness for the editor toolbar

- web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
- web-ui/src/main/resources/catalog/components/viewer/atom/partials/atomDownload.html
- web-ui/src/main/resources/catalog/style/gn.less
- web-ui/src/main/resources/catalog/style/gn_metadata.less
- web-ui/src/main/resources/catalog/style/gn_search.less
- web-ui/src/main/resources/catalog/views/default/directives/partials/attributetable.html
- web-ui/src/main/resources/catalog/views/default/directives/partials/mdactionmenu.html
- web-ui/src/main/resources/catalog/views/default/less/gn_result_default.less
- web-ui/src/main/resources/catalog/views/default/templates/recordView.html
Replaces PR: https://github.com/geonetwork/core-geonetwork/pull/3007
Some small changes for the detail page in order to get a more uniform look: same buttons, same tables, same size of icons.
**Screenshot of new page:**
Changes:
- same icons (colors, size, labels)
- smaller width for buttons
- uniform buttons in the button bar
- different style for the status
- other headings for feature catalog (`<h3>` and `<h4>` in stead of `<h2>`)
**Screenshot of new feature catalog block:**
> More uniform styling for Detail Page

- web-ui/src/main/resources/catalog/locales/en-core.json
- web-ui/src/main/resources/catalog/templates/new-account.html
- web-ui/src/main/resources/catalog/templates/new-password.html
- web-ui/src/main/resources/catalog/templates/signin.html
- web-ui/src/main/resources/catalog/views/default/less/gn_login_default.less
The Login, Register and Password page now have more of the same styling and colours, elements and buttons are positioned the same. More color contrast is added for accessibility.
**The overall look has a more cleaner style:**
**New account:**
**Reset pasword:**
> Uniform look for Login, Register and Password pages

- web-ui/src/main/resources/catalog/components/common/scrollspy/ScrollSpyDirective.js
- web-ui/src/main/resources/catalog/components/common/scrollspy/partials/scrollspy.html
- web-ui/src/main/resources/catalog/style/gn.less
- web-ui/src/main/resources/catalog/views/default/less/gn_view.less
This PR focusses on the scroll spy for the editor and settings for logged in users.
Changes made:
- full height
- more color contrast
- added aria-labels
- larger font
- scrollspy is closed by default
- changed the icons in more commenly used icons
- open and scroll buttons are larger and rounded
**Screenshot of new scrollspy - larger buttons, larger headers and full height:**
> Accessibility and styling changes to the scroll spy

- services/src/main/java/org/fao/geonet/api/ApiUtils.java
Most of the API action can be done using an internal ID or a UUID. Usually both are unique BUT some schemas allow read/write UUIDs which may be based on some rules which sometimes lead to build duplicate UUID. In that case, add a warning in order to have the catalogue admin be able to track such case.
To handle also in:
> [WIP] Log a warning on duplicate UUID

- web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/projectionSwitcher.html
- web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
- web-ui/src/main/resources/catalog/components/common/map/mapService.js
- web-ui/src/main/resources/catalog/components/common/ows/OWSService.js
- web-ui/src/main/resources/catalog/components/viewer/ViewerDirective.js
- web-ui/src/main/resources/catalog/components/viewer/ViewerModule.js
- web-ui/src/main/resources/catalog/components/viewer/baselayerswitcher/BaseLayerSwitcherDirective.js
- web-ui/src/main/resources/catalog/components/viewer/partials/mainviewer.html
- web-ui/src/main/resources/catalog/components/viewer/projectionSwitcher/ProjectionSwitcher.js
- web-ui/src/main/resources/catalog/components/viewer/projectionSwitcher/partials/projectionSwitcher.html
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/locales/en-core.json
- web-ui/src/main/resources/catalog/locales/en-search.json
- web-ui/src/main/resources/catalog/style/gn.less
- web-ui/src/main/resources/catalog/views/default/config.js
Projection Switcher: change the projection of the map on the fly with just a button.
Comes with:
* New configuration on the UI Settings to add a list of projections to populate the projection switcher.
* Fixed bug on loading TMS layer from settings: encoding.
* Enhancement: Now layers from settings can have attribution.
This also adds a couple of indirect features:
* Now you can define projections on the settings to be used on the map.
* Now you can change the default projection on the map on the settings.
If you want, we can even deprecate the initial context file from the map and use this. 
Documentation ready here to be merged once this gets into master: https://github.com/Delawen/doc/commit/36a26ce9f5c380300b8ebe5e804d1c009b91894d
> New map tool: Projection switcher

- web/src/main/webapp/xslt/services/thesaurus/registry-to-skos.xsl
Registry does not look to provide the expected publication date of a list. 
Hard coding the value for the INSPIRE theme one which is required for validation tools.
Related to https://github.com/geonetwork/core-geonetwork/issues/2500#issuecomment-427818239
> Thesaurus / import form Registry / Set INSPIRE theme thesaurus date

- web-ui/src/main/resources/catalog/components/common/multiselect/MultiselectDirective.js
> backport - Multiselect directive bug

- web-ui/src/main/resources/catalog/locales/en-core.json
- web-ui/src/main/resources/catalog/style/gn_infolist.less
- web-ui/src/main/resources/catalog/views/default/directives/partials/infolist.html
- web-ui/src/main/resources/catalog/views/default/less/gn_infolist_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_search_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_variables_default.less
- web-ui/src/main/resources/catalog/views/default/module.js
- web-ui/src/main/resources/catalog/views/default/templates/home.html
This replaces PR https://github.com/geonetwork/core-geonetwork/pull/3134
The homepage had an animated section for recent and popular datasets. This PR replaces this with blocks showing only the thumbnails in black/white (default). There is also the opportunity to change the list type with the 3 toggle buttons on the top right of the list.
**Screenshot of the new design:**
Changes and improvements:
- accessibility color scheme
- no thumbnail then display text
- added aria roles
- color thumbnails on hover
- 12 cards instead of 9 (better for displaying a 4x3 of 3x4 grid)
- smooth zoom in/out effect on hover
- background color on hover over list items
- display an icon when there is no thumbnail
- responsive view for all the lists
Reordering and cleaning css and less:
- remove old and unused …
> New design for the info list (Recent/Popular) on the homepage (replaces #3134)

- web-ui/src/main/resources/catalog/components/search/formfields/partials/usersCombo.html
Fix for issue https://github.com/geonetwork/core-geonetwork/issues/3083
Added the surname to the users combobox, so now the name and surname are shown
> Fix: Show name + surname in harvester users dropdown (#3083)

- .travis.yml
Usually building and testing GeoNetwork in Travis are taking more than the maximum time allowed to run the jobs (50 minutes). Most of the time is spent in downloading maven dependencies.
This commit caches the `$HOME/.m2` folder between builds to speed up the job avoiding to download dependencies.
> Caches .m2 folder in Travis builds to speed up them

- core/src/main/java/org/fao/geonet/kernel/search/spatial/OgcGenericFilters.java
Enhancement/bug fix: when CSW has a wrong filter, instead of returning error it applied a null filter. Now it returns an error.
Fixes #2897.
> Return an error when CSW filter is invalid

- pom.xml
Updated jackson core dependencies from 2.5.5 to 2.9.7 version. Artifacts affected: jackson-core, jackson-databind and jackson-annotations.
Updated jackson datatype dependencies from 2.7.4 to 2.9.7 version. Artifacts affected: jackson-datatype-hibernate4.
> Updated jackson dependencies

- web-ui/src/main/resources/catalog/components/admin/harvester/partials/logopicker.html
In stead of fixing the typo (there were no translations) I suggest to just display the logo (file)name as label
Same in pulldown-list, add a hover-title with the logo name, may help to identify the relevant logo
> typo and missing translation

- release/bin/shutdown.sh
- release/bin/startup.sh
In Mac OS X, after installing GN using the installer, and running `startup.sh` this failed because no log files were present yet in the `logs` folder. This fixes the errors using `rm -f` for removing and `find -exec mv` for moving old files if present.
This should be backported to v3.4.5.
>  Avoid fails when in first run when no log files exist yet

- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
- web-ui/src/main/resources/catalog/style/gn_metadata.less
- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-variables.xsl
A `<gmx:FileName>` element can be present in a contact info (or elsewhere), but these elements currently are rendered as plain text without taking into account the `@src` attribute. This PR adds support in the XSL formatter to render such element properly.
Example xml:
```xml
...
<gmd:contactInstructions>
<gmx:FileName src="https://www.geograndest.fr/metadata/live/logo/logo_ZAEU.png">Logo</gmx:FileName>
</gmd:contactInstructions>
</gmd:CI_Contact>
...
```
Before:
After:
Please let me know if this is redundant with another xsl process and/or may break other things in the formatter, thanks.
> XSL Formatter / handle logos in contact info

- core/src/main/java/org/fao/geonet/util/XslUtil.java
- services/src/main/java/org/fao/geonet/api/processing/XslProcessUtils.java
Utility method to update the metadata schema identifier in the database. Usage in xslt processes, like:
- Suggestion process to be displayed in the metadata editor, so the user can select it to upgrade a metadata to a newer schema version.
- Batch process to upgrade the metadata to a newer schema version.
> Utility method to change metadata schema identifier

- schemas/iso19139/src/main/plugin/iso19139/formatter/datacite/view.xsl
- services/src/test/java/org/fao/geonet/api/records/formatters/ListFormattersIntegrationTest.java
DataCite format is a common output format required to user who would like to assign DOIs to datasets. This formatter converts ISO19139 to the DataCite format based on http://schema.datacite.org/meta/kernel-4.1/doc/DataCite-MetadataKernel_v4.1.pdf. 
This conversion will be used in future work about DOIs in order to ask DOI creation once a record is published.
It would be good to also merge this PR https://github.com/geonetwork/core-geonetwork/pull/3191 in order to easily get output with the proper content type in the browser.
> ISO19139 / Formatter / Add DataCite

- services/src/main/java/org/fao/geonet/api/records/formatters/FormatType.java
- services/src/main/java/org/fao/geonet/api/records/formatters/FormatterApi.java
- services/src/main/java/org/fao/geonet/api/records/formatters/XsltFormatter.java
Some formatter may provide text response and not only XML or PDF as
currently supported. Rename file with a proper extension based on file
type. Add support to formatter providing a text response. In such case
the XSLT formatter has to return one element like the following with the
text to be returned:
```
<xsl:template match="/">
<textResponse>
{
"@context": "http://schema.org",
"@type": "Dataset",
"@id": "https://doi.org/10.5438/4K3M-NYVG"
...
}
</textResponse>
```
The text response can be CSV or JSON, ...
The content type can still be controlled using accept header or the
output URL parameter.
eg.
http://localhost:8080/geonetwork/srv/api/records/ff8d8cd6-c753-4581-99a3-af23fe4c996b/formatters/jsonld?output=json
> API / Formatter / Add JSON and text responses support.

- schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields.xsl
eg. in config-editor.xml
```
<field xpath="/gmd:MD_Metadata/gmd:fileIdentifier"
name="copernicusmarine-fileIdentifier"/>
```
and in strings.xml
```
<copernicusmarine-fileIdentifier>Internal permanent shortname</copernicusmarine-fileIdentifier>
```
> ISO19139 / Editor / Add possibility to customize field label for fileIdentifier and date stamp

- services/src/main/java/org/fao/geonet/api/standards/StandardsApi.java
- services/src/main/java/org/fao/geonet/api/standards/StandardsUtils.java
- services/src/main/java/org/fao/geonet/services/schema/Info.java
- services/src/main/java/org/fao/geonet/services/subtemplate/GetTypes.java
- web-ui/src/main/resources/catalog/components/common/schemamanager/SchemaManagerService.js
- web-ui/src/main/resources/catalog/components/edit/directoryentryselector/DirectoryEntrySelector.js
Only happen when using advanced codelist configuration such as the following:
eg.
```
<codelist name="gmd:CI_RoleCode" alias="roleCode"
displayIf="ancestor::node()[name()='gmd:MD_Metadata' and contains(gmd:metadataStandardName/gco:CharacterString, 'ISO 19139, MyOcean profile')]">
<entry>
<code>custodian</code>
<label>Production center</label>
<description>Party that accepts accountability and responsability for the data and ensures
appropriate care and maintenance of the resource</description>
</entry>
...
<codelist name="gmd:CI_RoleCode" alias="roleCode">
<entry>
<code>resourceProvider</code>
<label>Resource provider</label>
<description>Party that supplies the resource</description>
</entry>
```
In such case, the http://localhost:8080/geonetwork/srv/api/standards/iso19139/codelists/roleC …
> API / Standard / Codelist not properly retrieved when multiple defined.

- web-ui/src/main/resources/catalog/templates/editor/batchedit.html
This allows to access the records affected quickly after processing.
> Batch edit / Add link to record

- services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
> API / Delete metadata record API endpoint doesn't work when a UUID is provided

- web-ui/src/main/resources/catalog/components/admin/harvester/partials/schedule.html
In the harvesters admin page, in the dropdown shown next to the cron expression for executing the harvester there is a link for more cron syntax examples. This PR opens this link in a new window instead of the current one.
> Open cron help in a new window

- web-ui/src/main/resources/catalog/components/admin/harvester/partials/schedule.html
> Opens cron help in a new window

- schemas/config-editor.xsd
- schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-tpl.xsl
The `table` configuration in `config-editor.xml` use the `for` attribute to match the element to process and also the table title to display (matching the value in `labels.xml` file).
This pull request adds a new optional attribute `label` to the `table`:
- If defined, searches the value in `strings.xml` file. 
- If not defined or the value doesn't exist in `strings.xml` file, uses `for` to match the value in `labels.xml` file as the current behaviour.
**Example:**
_config-editor.xml_
```
<table for="gmd:DQ_ConceptualConsistency" title="qos">
...
```
_strings.xml_
```
<qos>Quality of service reports</qos>
```
> Support custom titles for metadata editor tables

- schemas/config-editor.xsd
- schemas/dublin-core/src/main/plugin/dublin-core/layout/layout.xsl
- schemas/iso19110/src/main/plugin/iso19110/layout/layout-custom-fields.xsl
- schemas/iso19110/src/main/plugin/iso19110/layout/layout.xsl
- schemas/iso19110/src/main/plugin/iso19110/layout/utility-fn.xsl
- schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields.xsl
- schemas/iso19139/src/main/plugin/iso19139/layout/layout.xsl
- web/src/main/webapp/xslt/common/functions-metadata.xsl
Some xml elements are available in different sections with different usage, but the configuration to use a directive or html control applies to all (this can be redefined in the views in some cases, but doesn't work for table mode for example).
This change allows to configure a field using the xpath. For example, for `gmd:name` in distribution format to use `gn-keyword-picker`, while `gmd:name` in other elements, like `gmd:onLine` will use the default control (input text):
```
<for name="gmd:name" xpath="/gmd:MD_Metadata/gmd:distributionInfo/gmd:MD_Distribution/gmd:distributionFormat/gmd:MD_Format/gmd:name"
use="data-gn-keyword-picker">
<directiveAttributes data-thesaurus-key="external.theme.httpinspireeceuropaeumediatypes-media-types" …
```
> Add support for xpath in the metadata editor fields configuration

- schemas/pom.xml
It should be `3.4.5-SNAPSHOT` since the release of v3.4.4.
> Fix `gn.project.version` property in schemas module

- update-version.sh
* Fixes update of maven `gn.project.version` property. It will avoid to forget updating the property manually when doing a release like in #3268
> Update versions release script

- web-ui/src/main/resources/catalog/components/search/map/MapFieldDirective.js
The pr will check if there is an actual valid geometry before triggering the search, 
when the user clicks on either the draw or the type of intersection buttons
> Search not trigged if geom is empty or undefined

- web-ui/src/main/resources/catalog/components/common/map/mapService.js
Layers with errors are shown on the map anyway, but as they don't appear on Layer Manager there is no way to handle them (or remove them). Better to show them with errors, so the user can:
1.- Check the list of errors associated to that layer. Not only as an alert that disappears.
2.- If there is something added to the map and shown, even if it is ugly and weird, have a button to remove it.
3.- If the layer was properly shown (as with OL reprojecting the layer), then why not show it, even if the projection missing error is there?
Not sure why the "layers from WPS" aren't shown either.
> Let layers with errors be shown on LayerManager.

- core/src/main/java/org/fao/geonet/kernel/KeywordBean.java
- core/src/main/java/org/fao/geonet/kernel/search/keyword/KeywordSearchParams.java
- core/src/main/java/org/fao/geonet/kernel/search/keyword/KeywordSearchParamsBuilder.java
- core/src/test/java/org/fao/geonet/kernel/AbstractThesaurusBasedTest.java
- core/src/test/java/org/fao/geonet/kernel/AllThesaurusTest.java
- core/src/test/java/org/fao/geonet/kernel/ThesaurusTest.java
- core/src/test/java/org/fao/geonet/kernel/search/KeywordsSearcherTest.java
First: Remove duplicates on results from the thesauri search. This was making the tests fail on $random_unknown_environment_and_circunstamces.
Second: Use real temporary files for thesauri tests. This prevents errors due to unclean environments or, even, simultaneous tests running at the same time.
Third: Refactor a bit thesauri management, there was code rewritten over and over again.
> Thesaurus tests fix

- web-ui/src/main/resources/catalog/components/common/scrollspy/partials/scrollspy.html
- web-ui/src/main/resources/catalog/style/gn.less
Small improvements:
- increased the `z-index` for the `toggle` and `go to top` buttons
- added a `close` button in the upper right corner
> Small improvements to the scrollspy

- add-schema.sh
Script Shell script  to add a metadata schema in GeoNetwork for development. Adds the submodule and updates the related configuration files:
Parameters:
- metadata schema name
- git repository of the metadata schema
- git branch of the metadata schema
Example:
`./add-schema.sh iso19115-3 https://github.com/metadata101/iso19115-3 3.4.x`
> Shell script  to add a metadata schema in GeoNetwork for development

- core/src/main/java/org/fao/geonet/util/XslUtil.java
Backport to 3.4.x branch of https://github.com/geonetwork/core-geonetwork/pull/3287
> XslUtil.getSiteUrl returns the url with an additional slash #3286

- web-ui/src/main/resources/catalog/js/admin/HarvestSettingsController.js
On master, I'm getting this error when I try to define a new Harvester:
```
TypeError: Cannot read property 'match' of undefined
at m.a.getTplForHarvester (gn_admin.js?v=29577de66801486a7ffd26921633d82764a02b08&:1350)
at fn (eval at compile (lib.js?v=29577de66801486a7ffd26921633d82764a02b08:740), <anonymous>:4:245)
at m.$digest (lib.js?v=29577de66801486a7ffd26921633d82764a02b08:653)
at m.$apply (lib.js?v=29577de66801486a7ffd26921633d82764a02b08:657)
at HTMLAnchorElement.<anonymous> (lib.js?v=29577de66801486a7ffd26921633d82764a02b08:781)
at HTMLAnchorElement.dispatch (lib.js?v=29577de66801486a7ffd26921633d82764a02b08:7)
at HTMLAnchorElement.r.handle (lib.js?v=29577de66801486a7ffd26921633d82764a02b08:7)
```
The fix is to avoid this, but to check if it would be better another kind of error …
> Small bug in harvester creation

- web-ui/src/main/resources/catalog/components/edit/FieldsDirective.js
Example of configuration:
```
<field xpath="/gmd:MD_Metadata/gmd:identificationInfo/*/gmd:supplementalInformation"
name="cm-display-priority"
use="data-gn-field-with-prefix-or-suffix">
<directiveAttributes data-prefix="display priority: " 
data-suffix=" meters" 
data-field-type="number"/>
</field>
```
Form field:
XML encoding:
> Editor / Add directive to hide a prefix or a suffix

- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
* List was limited to 5 entries which is usually not enough when using
region thesaurus
* List was not displayed until something is typed in the input. Open
list on focus.
> Editor / Region selection.

- core/src/main/java/org/fao/geonet/kernel/search/LuceneQueryBuilder.java
- core/src/main/java/org/fao/geonet/kernel/search/LuceneQueryInput.java
- core/src/main/java/org/fao/geonet/kernel/search/LuceneSearcher.java
- core/src/main/java/org/fao/geonet/kernel/search/SearchParameter.java
- core/src/main/java/org/fao/geonet/kernel/search/UserQueryInput.java
Registered users were able to see metadata without viewing privileges but with editing privileges.
So a metadata with 
previously was seen by registered users of Sample Group.
Now it is only seen by editors or more of Sample Group.
> Bug fix: Editing privileges acting as view privileges

- web-ui/src/main/resources/catalog/templates/admin/settings/system.html
Was working fine for boolean setting but not for others:
Once fix, looks like
> Settings / Link in setting documentation not rendered

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/HarvestManagerImpl.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java
If an existing harvester is of a type that there is not defined in `config-spring-geonetwork.xml` anymore don't make GN fail on startup, just write this fact in the log.
Also, allow removing a harvester that has not type bean anymore.
Fixes #2607.
> If a harvester type bean is not available don't fail on GN initialisation

- web-ui/src/main/resources/catalog/components/edit/validationreport/partials/validationreport.html
Following the discussion here https://github.com/geonetwork/core-geonetwork/issues/3056
This removes the refresh validation button from the right column panel in the metadata editor.
> Removing "Refresh validation" button from side panel

- web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js
Fix for https://github.com/geonetwork/core-geonetwork/issues/3310
Changed function to close a modal. The close function was trying to close a popup and not a modal. Now the bootstrap method to close a modal is used.
> Fix: Close a modal (#3310)

- web-ui/src/main/resources/catalog/components/admin/harvester/partials/account.html
- web-ui/src/main/resources/catalog/components/admin/harvester/partials/identification.html
- web-ui/src/main/resources/catalog/components/admin/harvester/partials/privileges.html
- web-ui/src/main/resources/catalog/components/admin/harvester/partials/schedule.html
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html
- web-ui/src/main/resources/catalog/templates/admin/harvest/harvest-settings.html
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/arcsde.html
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/csw.html
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/filesystem.html
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/geoPREST.html
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/geonetwork.html
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/geonetwork20.html
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/oaipmh.html
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/ogcwxs.html
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/thredds.html
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/webdav.html
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/wfsfeatures.html
- web-ui/src/main/resources/catalog/templates/editor/import.html
ID's are added to be able to do automated testing and for hiding fields via `css`.
This is related to https://github.com/geonetwork/core-geonetwork/issues/3152, https://github.com/geonetwork/core-geonetwork/issues/3155 and https://github.com/geonetwork/core-geonetwork/issues/3168
The ID's are added to the following pages: 
- Import pages
- Harvester pages
- Online Resource pages
> ID's added Import, Harvester and Online Resource pages

- core/src/main/java/org/fao/geonet/arcgis/ArcSDEJdbcConnection.java
It seems that on some versions of ArcSDE, the metadatas are stored in database using the SQL XML type available on the DBMS.
Tests: Runtime tested only: The following patch has been successfully tested against a PostGreSQL ArcSDE database, which have the following structure (truncated output):
```
\d gdb_items
Table "sde.gdb_items"
Column      |          Type          |                                  Modifiers
-----------------+------------------------+------------------------------------------------------------------------------
uuid            | character varying(38)  | not null default [...]
[...]
definition      | xml                    |
documentation   | xml                    |
iteminfo        | xml                    |
[...]
```
> ArcSDE harvester - Allow SQLXML type

- web-ui/src/main/resources/catalog/components/edit/validationreport/partials/validationreport.html
- web-ui/src/main/resources/catalog/style/gn_editor.less
The text color in the validation panel used colours, that made the text sometimes hard to read.
This PR changes the text colour to the default colour and adds a coloured left border (the same colour as the text used to be).
An extra addition is the toggle option for the different (sub)panels, so you can collapse a list you're not interested in.
**Screenshot of the changes:**
> Small improvements to the validation panel

- wro4j/src/main/java/org/fao/geonet/wro4j/TemplatesUriLocator.java
Fix for #3328
Thanks @yuanb
Anyone on Windows for a review ?
> TemplatesUriLocator.locate assumes file system path separator is uri path separator 

- web-ui/src/main/resources/catalog/lib/bootstrap.ext/typeahead.js/typeahead.bundle.js
When the server returns less suggestions than what is configured as limit for the autocompleter, it only shows the first one, not adding the others to the suggestions list. 
This is a bug detected in Typeahead library, see https://github.com/twitter/typeahead.js/issues/1232.
This library seems not to be actively maintained by Twitter anymore (latest commits were in 2015). I've taken the patch from a fork https://github.com/corejavascript/typeahead.js
Patch: https://github.com/corejavascript/typeahead.js/blob/107a9b0d002e549be746d93a1fbcde05853d745a/src/typeahead/dataset.js#L269-L281
After applying the patch this is the result:
> Patches typeahead.bundle.js to fix an error in results shown

- web-ui/src/main/resources/catalog/lib/bootstrap.ext/typeahead.js/typeahead.bundle.js
Backport of #3332.
When the server returns less suggestions than what is configured as
limit for the autocompleter, it only shows the first one, not adding the
others to the suggestions list. This is a bug detected in Typeahead
library, see https://github.com/twitter/typeahead.js/issues/1232.
This library seems not to be actively maintained by Twitter anymore
(latest commits were in 2015). I've taken the patch from a fork, Corejs
Typeahead.js https://github.com/corejavascript/typeahead.js
https://github.com/corejavascript/typeahead.js/blob/107a9b0d002e549be746d93a1fbcde05853d745a/src/typeahead/dataset.js#L269-L281
> [BP] Patches typeahead.bundle.js to fix an error in results shown

- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
- web-ui/src/main/resources/catalog/js/admin/UserGroupController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/templates/admin/usergroup/groups.html
Displays at the end of the group form the users associated to the group:
It's updated the `gnPaginationList` directive also, so can be added several times the directive in the same page to use different lists, previously that was not working.
Requires  https://github.com/geonetwork/core-geonetwork/pull/3343 to get working the links of the users page.
Thank @juanluisrp for the support in the AngularJs development.
> Display users of a group in the group maintenance #3341

- web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionsDirective.js
Refresh board after bulk ownership change, so the new owner is shown on metadata records affected. Right now, after save, it shows the old values (you need to reload the page).
Contribute -> Editor Board
then select some records
selected -> Transfer Ownership
> Refresh board after bulk ownership change

- web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js
When `data-wait-for-user` is set there was a bug that didn't register the watch that
waits for the user info to be available before triggering the search.
This was making the search sometimes be triggered before the user were available returning all the records available even when _Only my records_ check was marked.
This should be backported to 3.4.x too.
> Fixes a bug when checking the waitForUse attribute in SearchFormDirective

- web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js
Backport of  #3349.
When `data-wait-for-user` is set there was a bug that didn't register the watch that waits for the user info to be available before triggering the search.
> [BP] Fixes a bug when checking the waitForUse attribute in SearchFormDiretive

- web-ui/src/main/resources/catalog/components/search/formfields/partials/usersCombo.html
Backport of #3364 and #3361.
Shows the user's surname and username in the harvester select options.
> [BP] Add surname and username to user list

- domain/src/main/java/org/fao/geonet/domain/InspireAtomFeed.java
- domain/src/main/java/org/fao/geonet/domain/MetadataFileDownload.java
- domain/src/main/java/org/fao/geonet/domain/MetadataFileUpload.java
- domain/src/main/java/org/fao/geonet/domain/MetadataStatus.java
- domain/src/main/java/org/fao/geonet/domain/MetadataValidation.java
- domain/src/main/java/org/fao/geonet/domain/OperationAllowed.java
Added database index configuration at least for the fields used in queries to extract the data add to the Lucene indexing process. Probably more require to be reviewed. 
Also in most cases are required these explicit indexes as most tables are not using relations between entities (mostly to the `metadata` table), so no `FK` are defined. I guess this was done to maintain compatibility with the old database model and also to avoid issues with the loading of related entities in JPA, but we should review this, with a proper configuration of the data objects, this should not be a problem.
> DB / Missing indexes. Fixes #3358

- web-ui/src/main/resources/catalog/components/common/map/mapsManager.js
When a projection defined in the projection list of Settings/Config UI is not defined correctly it causes GN not to load at all and makes also the Settings page not to load for fixing the error. 
This PR improves the error handling in the custom projections definition showing a console warning instead of crashing GN.
> Avoid GN crashes when a projection is not correctly defined

- services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java
Use appropriate method to retrieve the correct language 3 letters code. Currently fra was returned for French for example.
> Workflow / Email not in correct language

- web-ui/src/main/resources/catalog/components/viewer/ViewerDirective.js
Not sure since when this happens (3.4.x is fine. Maybe related to the projection switcher change or other changes made on the map in the last month?) but when opening the map, in non debug mode (why this does not happen in debug mode?) the map is blank. Resizing the window or refreshing the tab make the map to be rendered properly.
Force OL to render the map if not yet initialized on location change.
> Map is blank in non debug mode when opening the map tab

- web-ui/src/main/resources/catalog/components/viewer/terrainswitcher/TerrainSwitcherDirective.js
Turn off terrain provider which is not freely accessible anymore. Only ellipsoid is now in use.
Fix for #3317
> Map / 3D mode does not work. 

- web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionsDirective.js
This happens most of the time (it happens in master and 3.4x).
Bug description:
- Go to the metadata board (Contribute)
- Click on the edit button of one metadata record
- Check which categories are enabled then click Cancel and go back to metadata board
- Check that record and click "Update the categories" and do some change
- Click on the edit button of that metadata record again
The bug is that the changes done with the bulk update are not shown (but are correctly saved on the database)
The bug does not belong to the bulk update in the board, but the editor. There is some delay, that causes the editor to be loaded without latest change.
> Bug fix - Bulk update not propagated to editor

- web-ui/src/main/resources/catalog/components/admin/uiconfig/UiConfigDirective.js
- web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/projectionSwitcher.html
* Sync angular model with input values. When changing values in individual coordinates the general field is updated. Also update the model on general field change using `$scope.$apply` to integrate it in angular `$digest` cycle and make changes more immediate.
* Make the `extent` and `worldExtent` fields readonly to avoid the user to enter wrong values, like objects instead of arrays.
* Allow floating point numbers in coordinate fields.
> Improvements in projectionSwitcher configuration

- web-ui/src/main/resources/catalog/js/admin/DashboardWfsIndexingController.js
Related to https://github.com/geonetwork/core-geonetwork/pull/3205 which now encode URL and feature type name to support ES 6.4+ and to point to the correct index containing features (and not to the ES cluster root only).
> WFS Indexing / Admin panel does not display correct information

- web-ui/src/main/resources/catalog/js/edit/ImportController.js
- web-ui/src/main/resources/catalog/style/gn.less
- web-ui/src/main/resources/catalog/templates/editor/import.html
When you import a lot of files at once you have to scroll down to click the import button. In the old situation the focus stays at the bottom but the progress and messages are displayed at the top of the page, outside the view port.
This PR adds some small changes. Fist of all the progress bar is replaced with a fixed progress bar on top of the page, this progress bar is always within the view port. And second a scroll to top action is added after the import button is clicked.
**Screenshot with the fixed progress bar**
> Improved messaging/user feedback in Import Page

- schemas/config-editor.xsd
- schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcService.js
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/overview-manager.html
- web-ui/src/main/resources/catalog/components/filestore/partials/filestore.html
- web-ui/src/main/resources/catalog/locales/en-core.json
Simply drop a file here to set thumbnail.
Short video https://www.youtube.com/watch?v=5gHyE13gGws&feature=youtu.be
The panel allows:
* to add an overview
* to remove existing ones
It does not allow to set name and description.
The panel is enabled by default in simple view mode.
it is also an option to put the overview manager in the main form with:
```
<tab id="default" default="true" mode="flat">
<section xpath="/gmd:MD_Metadata/gmd:identificationInfo"/>
<directive data-gn-overview-manager=""/>
<section xpath="/gmd:MD_Metadata/gmd:referenceSystemInfo"/>
```
which is rendered as:
> Editor / Simple overview manager

- web-ui/src/main/resources/catalog/locales/en-admin.json
Added extra help text as suggested in PR: https://github.com/geonetwork/core-geonetwork/pull/3306
> Extra help text in the admin for the `logo in header` part

- web-ui/src/main/resources/catalog/components/viewer/wfs/partials/download.html
- web-ui/src/main/resources/catalog/style/gn_metadata.less
Improve display of `tables` and `listviews` on small screens:
- display `<th>` and `<td>` beneath each other
- remove borders
- reduce padding left and right
- added `text-warning` to the warnings
**Detail view on wider screens:**
**Detail view on smaller screens:**
> Improve display of `tables` and `listviews` of Detail page on small screens

- web-ui/src/main/resources/catalog/js/admin/HarvestSettingsController.js
Due to timing issues while loading the Harvester admin page and the language files
sometimes the translation for the harvester type is not available yet when the page
is rendered. This is cause by the use of `$translate.instant` function. To fix this
and allow the translation to be set once the language is available we use now a promise
for setting the `text` translated value.
> Fixes harvester type names not translated

- schemas/iso19139/src/main/plugin/iso19139/schematron/schematron-rules-inspire.disabled.sch
Currently an error is reported if a lineage is set in one section and if another section does not have it.
INSPIRE validator (old and new one) do not report this error. 
The check is: at least one lineage is defined in the record (not for each dataQuality section)
> ISO19139 / Schematron INSPIRE / Check at least one lineage is defined

- es/es-core/src/main/java/org/fao/geonet/es/EsClient.java
- healthmonitor/src/main/java/org/fao/geonet/monitor/health/DashboardAppHealthCheck.java
- healthmonitor/src/main/java/org/fao/geonet/monitor/health/IndexHealthCheck.java
- pom.xml
- web/pom.xml
- web/src/main/webResources/WEB-INF/config.properties
* HealthCheck on Kibana only if URL is not empty to avoid exception in the log.
```
15-Nov-2018 17:49:22.364 SEVERE [ajp-nio-8112-exec-3] org.apache.catalina.core.StandardWrapperValve.invoke "Servlet.service()" pour la servlet HttpDashboardProxy a généré une exception
org.apache.http.conn.HttpHostConnectException: Connect to localhost:5601 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connexion refusée
```
* HealthCheck on index with the type to avoid forbidden when ES cluster is secured.
> ES / Configure ES only when the profil is set. 

- web-ui/src/main/resources/catalog/style/gn_search.less
hides some artifacts that prevent clicking on last month on the datepicker in advanced search
> hide datepicker artifact

- core/src/main/java/org/fao/geonet/notifier/MetadataNotifierManager.java
Metadata notifiers system doesn't work well since it can't store the result of the notifications in the table `MetadataNotifications`. This PR  fixes #1184. Create a new `MetadataNotification` if it doesn't exist in the database. Also don't delete the notification when deleteNotification is true.
> NullPointerException in metadata notifications management

- schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields-date.xsl
- schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields.xsl
- web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_variables_default.less
- web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
Fix for https://github.com/geonetwork/core-geonetwork/issues/3386
Changes:
- date picker stays on one line
- better responsiveness for delete buttons
- rounded corners are back (new variable added)
**Screenshot of the datepicker:**
**Delete buttons on a small screen:**
> Fixes for the editor fields (#3386)

- web-ui/src/main/resources/catalog/components/catalog/CatalogService.js
The behaviour is not consistent with other parts of the code, where the port is not added to the URL when equals to 80 or null.
> Don't concat port number if it's null or 80 in settings

- web-ui/src/main/resources/catalog/components/common/map/partials/drawbbox.html
- web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
The map in the editor is displayed in a table with the map in the center table cell. This means that when you use the editor on a small screen the map is usually only one third of the width of a screen.
This PR takes the styling from the detail view where the coordinate boxes are displayed over the map. This results in a better responsiveness and a larger map on small screens. 
The N, E, S and W labels are hidden on small screens.
**Old situation:**
**New situation:**
**New situation on larger screens (with N, E, S and W labels):**
> Larger map for editor on small screens

- web-ui/src/main/resources/catalog/components/admin/uiconfig/UiConfigDirective.js
- web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js
This fixes a bug that occurs when started with an empty database. Then UI settings page shows duplicated values for all the fields.
* Setting name is in `name` property, not `id`
* `Object.keys` returns 4 for `"null"` value. Add this check also to the condition for
using `gnGlobalSettings.getDefaultConfig`.
Related to #3378.
> Fix a bug handling initial value of `ui/config` setting

- web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
- web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/templates/admin/admin.html
- web-ui/src/main/resources/catalog/templates/admin/harvest/harvest-report.html
- web-ui/src/main/resources/catalog/templates/admin/page-layout.html
- web-ui/src/main/resources/catalog/templates/admin/settings/cssstyle.html
- web-ui/src/main/resources/catalog/templates/admin/settings/logo.html
- web-ui/src/main/resources/catalog/templates/admin/settings/mapservers.html
- web-ui/src/main/resources/catalog/templates/admin/settings/system.html
- web-ui/src/main/resources/catalog/templates/admin/settings/ui.html
- web-ui/src/main/resources/catalog/templates/admin/tools/transferownership.html
- web-ui/src/main/resources/catalog/templates/top-toolbar.html
- web-ui/src/main/resources/catalog/views/default/less/gn_admin_default.less
- web/src/main/webapp/xslt/ui-admin/admin.xsl
This is a PR for small UI changes to the admin pages. A sidebar is added to the left, the tabs that used to be on top are added as a submenu to the left.
Two settings pages now have a filter option on top. This will filter on the labels used before each setting (_note_: sometimes labels are not properly used and therefore sometimes bigger blocks of settings are included in the filter results).
The `CSS & Style` is a bit reorganised, whitespace is removed, columns are added and a toolbar has been added at the top of the page. 
There is no toggle button yet, this could be in another PR. And more could have been added, but I wanted to keep this PR manageable and not too big.
Changes:
- menu in sidebar on the left
- uniform use of panels and rows
- filter option for `settings` and `user …
> UI Improvements to the admin interface

- web-ui/src/main/resources/catalog/components/common/map/mapService.js
- web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextService.js
When user define a non default style for a layer. On page reload (or export/restore map from a context), the style is lost.
Can be tested with service http://www.aquacoope.org/geoserver/c_ge/ows and layer t_mostation
The style is now stored in the extension section (like filters and process info)
```xml
<ows-context:Layer name="t_mostation" hidden="false" opacity="1">
<ows-context:Server service="urn:ogc:serviceType:WMS">
<ows-context:OnlineResource xlink:href="http://www.aquacoope.org/geoserver/c_ge/ows?SERVICE=WMS&amp;"/>
<ows-context:Extension>{"style":"c_ge:t_mostation_ge_MON_GE002"}</ows-context:Extension>
</ows-context:ResourceList>
</ows-context:OWSContext>
```
> Map / Restore layer style.

- web-ui/src/main/resources/catalog/components/search/mdview/partials/contact.html
This PR adds a phone number to the contact details displayed in the detail view (record view). The phone number is only added when mode is `org-role`.
The `org-role` is now also using the `<address>` element in stead of a normal `<div>`.
> Added phone number to metadata contact in detail view

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/onlinesrcList.html
This is to avoid 
for file not starting with http://
The icon is already added line 137.
> Editor / Link list / Remove duplicated protocol icon

- web-ui/src/main/resources/catalog/components/common/map/partials/drawbbox.html
- web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
This PR fixes too small maps in the editor. After resizing or displaying the map on a small screen the map could have a width of almost 0.
Related to https://github.com/geonetwork/core-geonetwork/pull/3390#issuecomment-452674591
> Fix for too small maps in the editor

- schemas/iso19139/src/main/plugin/iso19139/schema-ident.xml
Some validators (eg. the INSPIRE ETF) does not follow redirects and will return errors due to those http links to the XSD.
> ISO19139 / ISO website is now available with HTTPs

- workers/wfsfeature-harvester/pom.xml
To avoid 
```
[WARNING] Some problems were encountered while building the effective model for org.geonetwork-opensource:wfsfeature-harvester:jar:3.5.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing.
@ org.geonetwork-opensource:wfsfeature-harvester:[unknown-version],/geonetwork/workers/wfsfeature-harvester/pom.xml, line 75, column 15
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
```
> Build / Fix maven warning

- web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextService.js
When a record describes a map and a context is associated to the record, when loading the map from the record view the map may not zoom to the map extent defined in the context. 
When loading from the map panel, it works. So it looks like it is related to the fact that the map may not be initialized early enough in this case. Adding a timeout (as done in other places) fix the issue.
This can be tested on http://www.aquacoope.org/cat_eecca/srv/eng/catalog.search#/metadata/75419ae3-bb54-4648-8330-20d15a82247c which is currently running master (but will soon have this fix in)
> Map viewer not zooming to context extent

- web-ui/src/main/resources/catalog/style/gn.less
- web-ui/src/main/resources/catalog/style/gn_editor.less
- web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
Increase the `z-index` of the topbar and decrease the `z-index` of the draw map elements (autocomplete, coordinate inputs) in the editor.
Fix for: https://github.com/geonetwork/core-geonetwork/issues/3121
> Fix: Decrease the `z-index` of the draw map elements in the editor

- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
Currently the first one is selected and is GeoNames.
Some users have more important custom regions eg. Marine areas
> Editor / Region selector / Add an optional attribute to set the default

- web-ui/src/main/resources/catalog/js/CatController.js
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v350/LogoPositionInHeaderMigration.java
Fix for the logo in the header: the default option is now set to `false` (do not show the logo in the header).
Related to: https://github.com/geonetwork/core-geonetwork/pull/3306#discussion_r247828108
> Fix for the logo in the header: default is false (#3306)

- web-ui/src/main/resources/catalog/templates/admin/admin.html
Related to https://github.com/geonetwork/core-geonetwork/commit/f4d8324966304d426e9a930bfcff980a7c07a881
> Admin console / Restore message suggesting to load samples & template when empty the catalogue is.

- web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
In the editor there are cases (INSPIRE view) where the date picker is displayed on 2 lines. This PR fixes this and display the date picker on 1 line.
**Screenshot of the old situation**
**Screenshot after the fix**
> Fix for the width of a datepicker in the editor

- web-ui/src/main/resources/catalog/js/edit/BatchEditController.js
- web-ui/src/main/resources/catalog/locales/en-editor.json
- web-ui/src/main/resources/catalog/templates/editor/batchedit.html
When too many records are selected due to HTTP 414 URI too long error. Search is made on all UUIDs selected.
The displayed list is a search with no filter.
Display a message instead.
> Batch editing / List of selected record is invalid 

- web-ui/src/main/resources/catalog/components/common/map/partials/drawbbox.html
If only one projection is configured to be used in the editor form, a list with one item mis proposed. To keep things simple, do not show the switcher in such case. Most of the time only the local projection is used to input coordinates.
After the change
> Editor / Bbox / Do not show projection selector if there is only one.

- web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
After the change:
Related to https://github.com/geonetwork/core-geonetwork/pull/3323/files
Example when adding an action like:
```
<action type="process"
btnClass="fa fa-square-o"
process="add-vector-info"
if="count(gmd:MD_Metadata/gmd:identificationInfo/*/gmd:spatialRepresentationType) = 0 and count(gmd:MD_Metadata/gmd:identificationInfo/*/gmd:spatialRepresentationType[*/@codeListValue = 'vector']) = 0"/>
```
> Editor / When label are placed above field, the offset of action button should be removed to keep all aligned left

- release/bin/startup.sh
On first run, the logs dir does not exist. Create parent if needed.
> Installer / Avoid error when parent dir does not exist.

- web-ui/src/main/resources/catalog/views/default/less/gn_admin_default.less
The colours in the admin sidebar were different than the colours used in the dropdown menu of the menubar. This PR changes the colours of the dropdown to those used in the sidebar.
**Screenshot of the matching colours**
> Match the dropdown menu colours in the admin with the sidebar colours

- web-ui/src/main/resources/catalog/components/search/facets/partials/dimension-facet-list.html
The facet toggle buttons are now aligned in the center. This looks good on wider screens where the facets and search results are beside each other. On smaller screens the search result are display below the facets, and then the toggle buttons are somewhere floating in the middle of the screen.
**Screenshot of centered buttons**
This PR aligns the toggle buttons to the left, so on smaller screens the toggle buttons are displayed right above the facets and now also have a visual connection
**Screenshot of buttons aligned to the left**
> Align facet toggle buttons to the left

- web-ui/src/main/resources/catalog/views/default/less/gn_search_default.less
- web-ui/src/main/resources/catalog/views/default/templates/advancedSearchForm/defaultAdvancedSearchForm.html
The elements in the advanced search form are not aligned with each other (different horizontal positions) and are not centered on the page (whereas the search box is).
This PR aligns and centers the elements which results in a cleaner view.
**Screenshot of the old situation:**
**Screenshot of the aligned elements:**
Changes:
- added hover styles in the typeahead
- cleanup unused styles
- wider search on small screens
- elements aligned with each other
- centered on the page
- better positioning of `trigger` and `clear` buttons
> Re-arrange the elements in the advanced search form

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/CswParams.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geoPREST/GeoPRESTParams.java
Fix for #3422 +  Harvester URL not properly saved when containing characters to be escaped.
eg. for testing use https://sextant.ifremer.fr/geonetwork/srv/eng/csw?any=%25Like%25 and set AnyText=dorade should harvest 9 records
* save harvester, the URL is properly restored
* if  https://sextant.ifremer.fr/geonetwork/srv/eng/csw?any=%Like% then URL is saved, app can restart properly and proxy does not reach the server as the URL is not correct (maybe something to address in another ticket)
This code was introduced by https://trac.osgeo.org/geonetwork/ticket/728 but I think it was only required for the XSLT based UI (@josegar74 maybe you could review this one in case you remind some historical reasons ?)
> Harvester / Runtime exception on startup with non escaped character 

- web-ui/src/main/resources/catalog/views/default/less/gn_map_default.less
- web-ui/src/main/resources/catalog/views/default/templates/results.html
Small improvements to the mini map:
- background-color added (looks better when refreshing the page and there are no maptiles yet)
- toggle button has an `:focus` background
- mini map is hidden on small screens
- larger font for attribution text
> Small improvements to the mini map on the search results page

- domain/src/main/java/org/fao/geonet/domain/page/Page.java
- domain/src/main/java/org/fao/geonet/domain/page/PageIdentity.java
- domain/src/main/java/org/fao/geonet/repository/page/PageRepository.java
- services/src/main/java/org/fao/geonet/api/pages/PageJSONWrapper.java
- services/src/main/java/org/fao/geonet/api/pages/PagesAPI.java
- web-ui/src/main/resources/catalog/components/pages/GnStaticPagesDirective.js
- web-ui/src/main/resources/catalog/components/pages/GnStaticPagesModule.js
- web-ui/src/main/resources/catalog/components/pages/partials/content.html
- web-ui/src/main/resources/catalog/components/pages/partials/footer.html
- web-ui/src/main/resources/catalog/components/pages/partials/menu.html
- web-ui/src/main/resources/catalog/components/pages/partials/top.html
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/js/search/SearchController.js
- web-ui/src/main/resources/catalog/templates/top-toolbar.html
- web-ui/src/main/resources/catalog/views/default/templates/footer.html
- web-ui/src/main/resources/catalog/views/default/templates/index.html
- web-ui/src/main/resources/catalog/views/default/templates/page.html
- web/src/main/webResources/WEB-INF/urlrewrite.xml
Following https://github.com/geonetwork/core-geonetwork/issues/3173
The idea is to support the creation of static pages of HTML inside GeoNetwork. This PR implements two aspects:
- Store the HTML content
- Show the links to these pages in specific points of the user interface
Enough for a low level (serviceable via API) working implementation.
In this solution:
- The HTML content is stored in a new table of the GN's database.
- The link to pages can be showed in different points of the GN's GUI according to a list of "sections" associated to each page. In this PR is introduced the support to show the links for the top toolbar and the footer.
- Each page can be in 3 states:
_HIDDEN_: visible to administrator
_PRIVATE_: visible to logged users
_PUBLIC_: visible to everyone
- Only the …
> Load static pages into GeoNetwork

- web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_result_default.less
- web-ui/src/main/resources/catalog/views/default/templates/recordView.html
- web/src/main/webapp/xslt/ui-metadata/menu-builder.xsl
This PR adds a little bit of styling to the dropdown menu in the editor, highlighting the current view a bit more clear.
**Screenshot of the active view**
> Highlight the active view in the dropdown menu of the editor

- core/src/main/java/jeeves/server/dispatchers/ServiceManager.java
- web/src/main/webResources/WEB-INF/urlrewrite.xml
- web/src/main/webapp/WEB-INF/config-security/config-security-mapping.xml
- web/src/main/webapp/WEB-INF/config/config-service-inspireatom.xml
- web/src/main/webapp/xslt/services/inspire-atom/describe.xsl
- web/src/main/webapp/xslt/services/inspire-atom/opensearch.xsl
- web/src/main/webapp/xslt/services/inspire-atom/search-results.xsl
Fixes for INSPIRE ATOM remote feeds, related to validation issues (http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp).
- Update OpenSearchDescription to add Query element for each dataset and remove default ports from urls.
- Add searchhtml endpoint to return feeds as html as required by the validator.
```
<Url type="text/html" rel="results" 
template="http://localhost:8080/geonetwork/opensearch/eng/
5cfe8a91-3dc9-4cf6-a40a-6a6d6f3124ab/searchhtml?any={filter}"/>
```
- Use `application/atom+xml` content type for ATOM Describe service as required by the validator.
- Add support for `redirect` option in Jeeves, used in ATOM Download service.
> Fixes for INSPIRE Atom remote feeds validation issues

- web-ui/src/main/resources/catalog/components/search/mdview/mdviewModule.js
Use `gnConfigService.load()` to retrieve the settings values with a promise instead of using `gnConfig` that seem not initialised when the code is executed.
> Metadata rating options (advanced mode) doesn't display always when the option is enabled. Fixes #3469

- web-ui/src/main/resources/catalog/style/gn.less
- web-ui/src/main/resources/catalog/templates/top-toolbar.html
Before the `Username` in the menubar a non-breaking space is added, but this means that `Username` and `Role` are not displayed right beneath each other. While this may look good for the admin, it doesn't for an editor:
This PR removes the `nbsp;` so the items are aligned to the left, and adds some padding to increase whitespace:
> Small fix for outlining username/user role in the menu

- services/src/main/java/org/fao/geonet/api/groups/GroupsApi.java
- web-ui/src/main/resources/catalog/js/admin/UserGroupController.js
- web-ui/src/main/resources/catalog/templates/admin/usergroup/groups.html
Fix for #2391
* User admin can't remove or update a group
* Group API / Add force parameter to remove a group associated with
records (as it is now, UI is using the force parameter)
> User administrator can delete his own group 

- pom.xml
Updated avalon-framework dependencies from 4.2.0 to 4.3 version. Artifacts affected: avalon-framework-api.
> Updated avalon-framework dependencies

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/onlinesrcList.html
As a result the url is displayed instead of title.
> Editor / Associated resource / Protocol might be null and trigger JS error

- schemas/iso19139/src/main/plugin/iso19139/templates/vector-multilingual.xml
- schemas/iso19139/src/main/plugin/iso19139/update-fixed-info.xsl
- web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
Fields in the editor form should be displayed in the same order as
defined in the locales section of the record.
It applies to both input mode:
> ISO19139 / Multilingual record / Preserve order of languages

- web-ui/src/main/resources/catalog/components/edit/FieldsDirective.js
In the old situation the tooltip (with help text) in the editor, when you use the icon with a question mark, is closed by hovering away from the icon.
However if you add a hyperlink in the tooltip for example, you can not click it because the tooltip closes before you reach it.
This PR removes the close trigger on the `mouseout` event.
**Screenshot of tooltip with link:**
> Remove trigger for closing tooltip on mouseout in the editor

- web-ui/src/main/resources/catalog/style/gn.less
- web-ui/src/main/resources/catalog/templates/editor/editorboard.html
- web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
The editorboard (contribute page) has some issues on smaller screens: buttons are covered by the button bar, facets not clickable because of layer on top of it, controls for the result list not directly above the list. This PR fixes these issues.
**Screenshot of an old situation:**
**Screenshot after the changes:**
Changes:
- hide labels on small screens
- selection, sort and pager above the search results on small screens
- added extra `col-*` classes (facets not covered with invisible layer anymore)
- added whitespace
> Improved responsiveness for the editor board

- web-ui/src/main/resources/catalog/templates/top-toolbar.html
- web-ui/src/main/resources/catalog/views/default/less/gn_navbar_default.less
The menu in the current version of GN doesn't always fit on small screens (smartphone) and can be broken when the menubar has `position: fixed` like on the editor board.
This PR restyles the menu, makes it more compact, better clickable and fixes the missing background.
**Old styling:**
**Old broken layout:**
**New styling when not logged in:**
**New style when logged in:**
Changes for restyling menu on small screens:
- added background (no background when menubar is fixed to the top)
- items as buttons (bit larger, better for touch)
- use less whitespace (more items on 1 row)
- styled the login for smaller screens
- add name and logo in upper bar
> Restyling and Fix for menu on small screens

- web-ui/src/main/resources/catalog/components/search/facets/FacetsConfigService.js
- web-ui/src/main/resources/catalog/components/search/facets/FacetsDirective.js
- web-ui/src/main/resources/catalog/components/search/map/MapFieldDirective.js
- web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js
Fixes #3566. Preserve the geometry parameter when the user updates the search facets.
> Adds a parameter to resetSearch to preserve the geometry on facet filter changes

- web-ui/src/main/resources/catalog/components/search/facets/FacetsConfigService.js
- web-ui/src/main/resources/catalog/components/search/facets/FacetsDirective.js
- web-ui/src/main/resources/catalog/components/search/map/MapFieldDirective.js
- web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js
Fixes #3566. Preserve the geometry parameter when the user updates the search facets.
Backport of #3567.
> [BP] Adds a parameter to resetSearch to preserve the geometry

- schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-tpl.xsl
- web-ui/src/main/resources/catalog/style/gn_editor.less
eg. to add an asterisk on organisation name:
```xml
<tableFields>
<table for="gmd:CI_ResponsibleParty">
<header>
<col label="gmd:organisationName" class="gn-required"/>
```
> Editor / Table / Add support to set header class to customize styling.

- web-ui/src/main/resources/catalog/components/common/ows/partials/layersGrid.html
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html
* This is useful when service is in error, requires auth, .... 
* Also add the possibility to choose a group of layers. 
Add description in some ISO19115-3 resource types.
> Editor / Associated resource / Display name and description for OGC resources

- web-ui/src/main/resources/catalog/components/search/searchfiltertag/SearchFilterTagsDirective.js
* Allows to configure the thesaurus used by searchFilterTags directive configurable.
* Sets `external.place.regions` as default value instead of `external.place.administrativeAreas` that doesn't exist in most GN instances.
> Makes thesaurus of searchFilterTags configurable

- web-ui/src/main/resources/catalog/components/search/searchfiltertag/SearchFilterTagsDirective.js
* Allows to configure the thesaurus used by searchFilterTags directive configurable.
* Uses `external.place.regions` as default value.
Backport of #3571.
> [BP] Makes thesaurus of searchFilterTags configurable

- services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
The error reported here https://github.com/geonetwork/core-geonetwork/issues/3596 happens only when you try to update from a record that is not registered in any group (could happen during import, where the destination group is not mandatory). This is a fix.
> Fix update from empty groups

- services/src/main/java/org/fao/geonet/api/users/MeApi.java
- services/src/main/java/org/fao/geonet/api/users/model/MeResponse.java
- web-ui/src/main/resources/catalog/js/CatController.js
This PR introduces improvements that are required here https://github.com/geonetwork/core-geonetwork/pull/3600
The angular methods to check profile scope.user.isEditor() or user.isEditorOrMore() or user.isReviewerOrMore() etc... don't take into account the group, so they are not useful in contexts where to determine the profile is necessary to know the relative group (for example for an operation related to metadata).
This PR adds new methods like scope.user.isEditorInGroup(groupId), scope.user.isReviewerInGroup(groupId) etc...
To do so, it was necessary to improve the api/me message to return also information about the user profile and groups. So now it returns 4 lists, each one associated with a specific profile, that includes the groups where the user is allowed that profile.
> Add info about profiles and groups in api/me services

- web-ui/src/main/resources/catalog/views/default/module.js
Use `title#reverse` in the UI config to define the direction. Default is DESC, `reverse` means ASC.
eg.
> Search / Sort can't define direction for default value

- web/src/main/webapp/xslt/common/functions-core.xsl
The meaning of iso19115 scope values are quite poorly documented, most relevant guess seems on comment at http://home.badc.rl.ac.uk/lawrence/blog/2008/03/19/the_scope_of_iso19115
I'm suggesting to use the type [WebAPI](http://schema.org/WebAPI) for "service", in stead of the dataCatalog type, this is the most relevant change, because service is used quite frequently in the scope of inspire. Following discussion schemaorg we may actually be able to at some point link WebAPI's to datasets. But we could also wait with merging this PR until schema-org has developed this as part of core
> improve scope to schema-org types

- web-ui/src/main/resources/catalog/views/default/directives/partials/linksbtn.html
This PR makes the buttons look the same in the results view
Before:
After:
> Add bootstrap classes to link button

- web/src/main/webapp/WEB-INF/data/config/codelist/external/thesauri/place/regions.rdf
See https://en.wikipedia.org/wiki/Macedonia_naming_dispute
> Region thesaurus / Macedonia is now North Macedonia since February 2019

- schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields-keywords.xsl
- schemas/iso19139/src/main/plugin/iso19139/layout/utility-tpl-multilingual.xsl
This allows to at least open the editor in XML mode to apply a fix.
> ISO19139 / Avoid XSL error in case of a language is declared more than once in other locale section.

- schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields-date.xsl
- web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
> Editor / Missing asterisk on + action when cardinality is 1..n. 

- schemas/iso19139/src/main/java/org/fao/geonet/schema/iso19139/ISO19139SchemaPlugin.java
- schemas/iso19139/src/main/plugin/iso19139/process/empty.xsl
- schemas/iso19139/src/main/plugin/iso19139/update-fixed-info.xsl
A directory entry does not have a main language. It can be multilingual but there is no main one. When retrieving a directory entry, the main language of the record embedding the entry must be the first one in order to set the CharacterString properly. Also, when changing the language of a record (switch main language, add/remove a language), xlink pointing to directory entries must be updated. Add in update-fixed-info a template to reorder the lang parameter according to the lang of the record.
Add an empty process in order to be able to apply update-fixed-info to a set of records using the process API.
> ISO19139 / Directory entry API xlink MUST contains languages in the order defined in the record.

- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
- schemas/iso19139/src/main/plugin/iso19139/loc/ara/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/cat/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/chi/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/dut/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/eng/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/fin/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/fre/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/ger/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/ita/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/nor/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/pol/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/por/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/rus/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/slo/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/spa/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/tur/strings.xml
Translates the true/false values in the detail page full view:
Also adds in `view.xsl` a commented template to handle boolean elements that should handle undefined values, that can be uncommented for the required elements.
> Translate true/false values on xslt formatter. Fixes #3045

- web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/projectionSwitcher.html
- web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
- web-ui/src/main/resources/catalog/templates/admin/settings/ui.html
- web-ui/src/main/resources/catalog/views/default/less/gn_admin_default.less
Small UI improvements for the admin `Settings` and `User Interface` :
- better hierarchy of labels and headings
- added visual 'blocks' to distinguish between settings/inputs
- more padding at the bottom so the `scrollspy` buttons do not overlap
**Screenshot of the 'blocks'**
> Small UI improvements for the admin `Settings` and `User Interface`

- web-ui/src/main/resources/catalog/components/viewer/gfi/FeaturesLoader.js
The if clauses where negated, which returned the opposite value we wanted.
Now using plain javascript compatible with all browsers (EMACS 5, even IE10).
> Bug fix: Info Formats for WMS were not correctly selected. 

- pom.xml
Excludes `geronimo-spec-javamail` and also `geronimo-spec-jms`(`jms` is referenced already by `activemq`)
> Mail send fails with java.lang.UnsupportedOperationException: Method not yet implemented. Fixes #3669

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/AbstractAligner.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Harvester.java
Instead of having everything on memory until the alignment in the end, start alignment as soon as we have a set of records available.
Improved also the database transaction management: no more forced flushes, rely on normal transactions which is better for general GN behaviour.
Removal of records is done at the end. To do this, we only store a Set<String> with all UUID instead of the full record. Still memory heavy but better than before. Coincidentally, as we are using a HashSet, removal of records is faster (no need to loop over the whole set of records to look for coincidences).
Also, leverages the final load on the database and index writing as it has a request petition between each batch of records.
Also, move some log info messages to debug to improve cleanliness and speed.
Also, …
> Improve memory handling on CSW harvesters

- web-ui/src/main/resources/catalog/components/viewer/projectionSwitcher/partials/projectionSwitcher.html
- web-ui/src/main/resources/catalog/views/default/less/gn_map_default.less
This PR changes the styling of the Projection Switcher on the map. The styling is now more like the search box on the map.
Changes:
- projection label shown once
- toggle button stays on first row
- toggle now has button styling
- current projection is highlighted
- background color on hover
- pointer cursor
**Old styling:**
**New styling:**
> Small UI changes to Projection Switcher

- web-ui/src/main/resources/catalog/components/common/map/print/PrintMapService.js
Without this fix, `tileGrid.getSize` and `tileGrid.getOrigin` would sometimes both return null, which caused the corresponding WMTS layer to not be rendered.
This does not happen for OSM though.
Example WMTS service: https://gis.ngdc.noaa.gov/arcgis/rest/services/web_mercator/etopo1_hillshade/MapServer/WMTS
> Fix computations for WMTS layers in print map service

- integration-test/pom.xml
- pom.xml
- schemas/csw-record/pom.xml
- schemas/dublin-core/pom.xml
- schemas/iso19110/pom.xml
- schemas/iso19139/pom.xml
- schemas/pom.xml
- schemas/schema-core/pom.xml
Currently, the version in pom.xml for schemas is 3.5. This PR changes to 3.6.
> Align schema version in pom.xml for 3.6.x

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcService.js
The bug is described here https://github.com/geonetwork/core-geonetwork/issues/3437
It's already fixed on master and 3.6.x here https://github.com/geonetwork/core-geonetwork/pull/3440 this PR is the porting to 3.4.x
> Fix thumbnail remove button

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java
Fixes compile error introduced by commit d9913ba682d7fe2556b3ef554bf59dfce549ded1
removing now unused parameters of `addMetadata` method calls.
See PR #3643.
> Fixes compile error

- core/src/main/java/org/fao/geonet/kernel/search/LuceneSearcher.java
- core/src/main/java/org/fao/geonet/kernel/search/MetaSearcher.java
- core/src/main/java/org/fao/geonet/kernel/search/UnusedSearcher.java
- services/src/main/java/org/fao/geonet/api/records/CatalogApi.java
- services/src/main/java/org/fao/geonet/api/records/rdf/RdfOutputManager.java
- services/src/main/java/org/fao/geonet/api/records/rdf/RdfSearcher.java
As commented in #3001, the  /geonetwork/srv/api/0.1/record endpoint (the DCAT/RDF output to GeoNetwork) does not support paging. For catalogs with a large number of records (for example: 
https://vanilla.geocat.net/geonetwork/srv/api/0.1/records) the request will timeout without pagination.
This pull request enables the paging and other filter parameters that are alraedy available in the LuceneSearcher. This is also documented in Swagger API description (see for example: http://beta.metadata.vlaanderen.be/geonetwork/doc/api/#/records/getAsRdf).
Additionally, this pull request includes structured information about paging according to the [W3C Linked Data Platform Paging](https://www.w3.org/TR/ldp-paging/#) spec and the [W3C Hydra](http://www.hydra-cg.com/spec/latest/core/) spec. The CKAN …
> Enable paging and other filters on the DCAT RDF endpoint

- schemas/iso19139/src/main/plugin/iso19139/formatter/groovy/iso19139/Handlers.groovy
- web/src/main/webapp/WEB-INF/data/data/formatter/html/bbox.html
- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-functions.xsl
This PR adds the "_settings_" parameter also to other parts of the code where the **getmap** method is invoked, to follow the new approach defined here https://github.com/geonetwork/core-geonetwork/pull/2938
@jahow what do you think?
Another parameter that could be good to take from settings is the SRS, should we add the keyword "_settings_" also for this?
> [BUG] - Map background, use default parameter defined in settings

- web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
In the metadata editor on some dutch schema, it happens that the remove button is shown even close to specific mandatory fields when the parent is not mandatory. For example, check https://github.com/metadata101/iso19139.nl.geografie.2.0.0
This is an extra check on the current field, to check explicitly if it's mandatory, before showing the remove button.
> [BUG] - Hide remove button from mandatory fields in editor

- web-ui/src/main/resources/catalog/views/default/less/gn_navbar_default.less
This PR adds a little bit more padding/whitespace in the dropdown menus for better readability
**Screenshot of the new padding**
> Extra padding in the menu items

- web-ui/src/main/resources/catalog/components/common/map/mapService.js
When parsing WMS GetCapabilites, the default selected legend URL should be from the first `Style` object and not the last. This is to be consistent with the fact that the default selected style is the first too.
This can be tested with the following path:
http://localhost:8080/geonetwork/srv/fre/catalog.search#/map?wmsurl=http:%2F%2Fsdn.oceanbrowser.net%2Fweb-vis%2FPython%2Fweb%2Fwms&layername=Mediterranean%20Sea%2FTemperature.19002013.4Danl.nc*Temperature_L2
Result:
> Fix WMS default legend URL

- web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
- web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
Sometimes fields in the editor are put together in one, big column. Usually this is not a problem, but when you use tooltip icons in the editor (`displayTooltips="true" displayTooltipsMode="icon"`) the tooltips are displayed on a big pile:
This PR adds rows and columns in this one, big column. This results in neatly ordered tooltip icons.
_Note_: in this screenshot the labels are missing (but still the tooltips are nicely ordered)
> Add rows and columns in a template

- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
- web/src/main/webapp/xslt/ui-search/search-nojs.xsl
this PR adds some improvements to the schema-org annotations in html view (no-js)
- adds a link to source catalog from each record
- adds some datacatalog annotations to search url
- validated results in ggl structured data testing tool
> improve schema-org mapping

- web/pom.xml
Restore https://github.com/geonetwork/core-geonetwork/commit/ff23797410e7e69d68c6ff6afde2441401cd60e9 which has been partially dropped at some point.
> Add maven properties to set Jetty port

- es/es-core/src/main/java/org/fao/geonet/es/EsClient.java
Currently it always return empty text.
> ES / Return the synonym found.

- core/src/main/java/org/fao/geonet/kernel/search/LuceneQueryBuilder.java
Before that change, only `without=something` was building a negative full text query on `any` field.
This adds support to do negative query on all fields eg. `&without-_cat=geodatacore&` = Do not contain category geodatacore
> Search / Add support to negative query on any fields

- core/src/main/java/org/fao/geonet/kernel/SchematronValidator.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataValidator.java
- services/src/main/java/org/fao/geonet/api/records/model/validation/Report.java
- web-ui/src/main/resources/catalog/components/edit/validationreport/partials/validationreport.html
- web-ui/src/main/resources/catalog/components/utility/partials/batchreport.html
- web-ui/src/main/resources/catalog/locales/en-editor.json
- web-ui/src/main/resources/catalog/templates/admin/tools/batch-replacer-report.html
- web/src/main/webapp/xslt/services/metadata/validate.xsl
If a schematron fails when it is running causing an exception now the user can know that an error has happened instead of see a successful 0/0 errors message.
Fixes #3594.
See warning:
> Report about failed schematron executions

- web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js
- web-ui/src/main/resources/catalog/templates/admin/settings/system.html
You can filter on settings in the `Settings` and `User Interface` pages in the admin. Until now only the line with the settings was hidden, which could result in empty blocks (parent) where all lines (children) were hidden.
This PR also checks on the parents. If the parent has no visible children it will be hidden.
An extra change has been made to **not** show a fieldset when it's empty
**Screenshot of only one block (parent) shown:**
> Hide complete panel when filtering settings in the admin

- web-ui/src/main/resources/catalog/components/edit/FieldsDirective.js
Fixes a problem that was adding the tooltip icon to multiple `gn-control` divs
when a template with more than one field is used.
> Missing tooltip icon for date fields in templates

- web/src/main/webapp/xslt/services/sitemap/sitemap.xsl
This is to uniform to other URLs in GeoNetwork (basically is for avoiding to add port '80' to these URLs).
The URL affected is the one shown when the portal contains more than 2500 records and the sitemap is paginated.
http://localhost:8080/geonetwork/srv/eng/portal.sitemap
> Use correct siteURL in sitemap urls

- services/src/main/java/org/fao/geonet/api/tools/migration/MigrationApi.java
> Migration API - NullPointerException when executing a database migration task. Fixes #3729

- services/src/main/java/org/fao/geonet/api/tools/migration/MigrationApi.java
Fixes #3729.
Backport of #3730.
> [BP] Migration API - NullPointerException when executing a database migration task. Fixes #3729

- services/src/main/java/org/fao/geonet/api/tools/migration/MigrationApi.java
Sets auto commit in database connection to `True` as by default was `False` (tested with H2 and Postgres) causing the issue.
Fixes #3732.
Backport of #3733.
> [BP] DatabaseMigration tasks doesn't save changes in the database. Fixes #3732

- common/src/main/java/org/fao/geonet/utils/Xml.java
- core/pom.xml
- pom.xml
- web/pom.xml
Upgrade `Apache FOP` from very old version`0.95` to latest `2.3` and minor upgrade of `Mapfish print-map` from `2.1.1` to `2.1.4`.
Tested the print of metadata selection that uses `Apache FOP` and map viewer printing that uses `Mapfish print-map` and looks working fine.
The upgrade for Apache FOP is done to be able to use https://xmlgraphics.apache.org/fop/fop-pdf-images.html for some improvements in the metadata printing to allow include in the output template PDF. The version of this library that was working with Apache FOP 0.95 seem no longer available in maven repositories.
> Update Apache Fop to 2.3 and MapFish print-map to 2.1.4

- schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
- web-ui/src/main/resources/catalog/components/edit/FieldsDirective.js
- web-ui/src/main/resources/catalog/components/edit/FieldsModule.js
- web-ui/src/main/resources/catalog/components/edit/anchorswitcher/AnchorSwitcher.js
- web-ui/src/main/resources/catalog/components/edit/anchorswitcher/partials/anchorswitcher.html
- web-ui/src/main/resources/catalog/components/metadatamanager/EditorService.js
- web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
Directive `gnAnchorSwitcher` for switching between `gmx:Anchor` and `gco:CharacterString`
CharacterString mode:
This mode produces a snippet like:
```xml
<element>
<gco:CharacterString>Sample text</gco:CharacterString>
</element>
```
When clicking in the button with the link icon it sets the Anchor mode:
In this mode the component produces:
```xml
<element>
<gmx:Anchor xlink:href="Url in URL field">Sample text</gmx:Anchor>
</element>
```
Clicking in the :x: button sets the CharacterString mode again.
The directive can be use defining it in `config-editor.xml` for specific fields, for example:
```xml
<for name="gmd:code" xpath="/gmd:MD_Metadata/gmd:identifier/gmd:MD_Identifier/gmd:code" use="data-gn-anchor-switcher"/>
<for name="gmd:supplementalInformation" use="data-gn-anchor-switcher"/> …
```
> Directive for switching between Anchor and CharacterString

- domain/src/main/java/org/fao/geonet/domain/SchematronCriteriaType.java
- schemas/iso19139/src/main/plugin/iso19139/schematron/criteria-type.xml
This adds the possibility to trigger a validation rule only for user with some profiles. The use case here is that we have some editors populating the main information with some basic level of validation and then catalogue administrator are reviewing records with an extra set of rules.
One issue with that criteria is that a record may be valid for some users and invalid for some others but if used in the context of a workflow with clear profiles and persons in charge of the final validation that is useful.
> Schematron / Add criteria to filter on user main profile.

- web-ui/src/main/resources/catalog/views/default/less/gn_alerts_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_login_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_search_default.less
This PR has some small improvements for the alert messages to make them more visible and stand out and to have a more uniform style. 
**Changes**:
- new, separate stylesheet for the alerts
- `max-width` and `min-width` for the alerts
- added an icon
- slightly changed green for the success messages (better visibility for a smaller message in the upper left corner)
- added a border on the left side (like the messages in the admin)
Two screenshot of the new messages:
> Small styling changes for the alert messages

- web-ui/src/main/resources/catalog/locales/ca-editor.json
- web-ui/src/main/resources/catalog/locales/cs-editor.json
- web-ui/src/main/resources/catalog/locales/de-editor.json
- web-ui/src/main/resources/catalog/locales/en-editor.json
- web-ui/src/main/resources/catalog/locales/es-editor.json
- web-ui/src/main/resources/catalog/locales/fi-editor.json
- web-ui/src/main/resources/catalog/locales/fr-editor.json
- web-ui/src/main/resources/catalog/locales/is-editor.json
- web-ui/src/main/resources/catalog/locales/it-editor.json
- web-ui/src/main/resources/catalog/locales/ko-editor.json
- web-ui/src/main/resources/catalog/locales/nl-editor.json
- web-ui/src/main/resources/catalog/locales/ru-editor.json
- web-ui/src/main/resources/catalog/locales/sk-editor.json
- web-ui/src/main/resources/catalog/locales/zh-editor.json
Since commit 2779b741d6 link to XML view shown in editor error messages (#1806) doesn't
point to the right URL. This commit change it to the new format
`/metadata/:id?tab=xml`
> Fixes link to XML tab in editor error message.

- web-ui/src/main/resources/catalog/js/admin/AdminToolsController.js
- web-ui/src/main/resources/catalog/templates/admin/tools/batch.html
In Batch processes admin tool the _Owner_ list of users is empty. This PR fixes that:
> Fixes empty owner select in admin's batch process

- web-ui/src/main/resources/catalog/style/gn_metadata_pdf.less
…left
If one plan to use alternate pdf formatter, the one usin flying-saucer, "float: left" can't be processed.
(following diff illustrating pdf formatter switch)
```
web-ui/src/main/resources/catalog/views/default/directives/partials/mdactionmenu.html
@@ -103,7 +103,7 @@
<i class="fa fa-file-zip-o"></i>&nbsp;
<span data-translate="">exportMEF</span>
</a></li>
-      <li><a data-ng-href="../api/records/{{md.getUuid()}}/formatters/xsl-view?root=div&output=pdf"
+     <li><a data-ng-href="../api/records/{{md.getUuid()}}/formatters/full_view?output=pdf"
target="_blank">
<i class="fa fa-file-pdf-o"></i>&nbsp;
<span data-translate="">exportPDF</span>
```
> Formatter / fix pdf generation from full view, flying saucer trouble with float left

- schemas/iso19139/src/main/plugin/iso19139/extract-relations.xsl
- services/src/main/java/org/fao/geonet/api/records/model/related/LocalizedString.java
Currently the Associated resources panel doesn't display the values in elements that use Anchors, for example for INSPIRE the description should use an Anchor like:
```
<gmd:description>
<gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/OnLineDescriptionCode/accessPoint">
accessPoint
</gmx:Anchor>
</gmd:description>
```
The Associated resource panel UI requires additional work to support the Anchors properly allowing to edit also the `xlink:href` attribute as with this change only the text value can be edited. 
This is a change in the related service to process Anchors and return the value and also the `xlink:href` attribute. Example response for an online resource with previous `gmd:description`:
```
<related>
<onlines>
<item>
...
<description>
<value lang="dut" …
```
> Support gmx:Anchor in extract relations xslt process

- core/src/main/java/org/fao/geonet/util/MailUtil.java
**Describe the bug**
There is an issue when using a SMTP host that does not require any authentication in geonetwork.
By default, in the database, the the setting with ID _system/feedback/mailServer/username_ contain an empty string. Saving the Admin settings form will not change that.
When the SMTP server is configured with the settings encoded, it will test if the username setting is set to \<null> but not if it is an empty string. It will then try to authenticate to the SMTP with an empty username and will cause an error.
**To Reproduce**
1) In the Feedback section of the admin settings page, set the address of an SMTP host that does not require authentication
2) Let the user name input field empty
3) Click on "test mail configuration"
**Expected behavior**
In the Feedback section of …
> Ignore empty username for SMPT server configuration

- core/src/main/java/org/fao/geonet/util/XslUtil.java
- schemas/dublin-core/src/main/plugin/dublin-core/formatter/xsl-view/view.xsl
- schemas/iso19110/src/main/plugin/iso19110/formatter/xsl-view/view.xsl
- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
- services/src/test/resources/org/fao/geonet/api/records/formatters/xsl-test-formatter/view.xsl
This pull request consists of two parts, which were identified during setup of a local GeoNetwork repository (at 3.4.4) - from looking at the 3.6.x branch these should also be applicable there.
**1. Remove references to node-label and replace with nodeLabel (bugfix)**
During testing we spotted errors related to view.xsl in our logs. From looking at schemaLocalizations (https://github.com/geonetwork/core-geonetwork/blob/3.4.x/services/src/main/java/org/fao/geonet/api/records/formatters/SchemaLocalizations.java) I discovered there was a nodeLabel function, but no such node-label function - nor did there appear to be any correction of node-label to nodeLabel during processing. Changing node-label to nodeLabel resolved our errors in our plugin - this pull request changes it throughout the …
> 3.4.x - add support for ISO 639-2/T + ISO 3166-1 codes in language and correct node-label refs

- core/src/main/java/org/fao/geonet/util/XslUtil.java
- schemas/dublin-core/src/main/plugin/dublin-core/formatter/xsl-view/view.xsl
- schemas/iso19110/src/main/plugin/iso19110/formatter/xsl-view/view.xsl
- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
- services/src/test/resources/org/fao/geonet/api/records/formatters/xsl-test-formatter/view.xsl
ISO 19115 standards often suggest using a combination of an ISO 639-2/T three letter code and a ISO 3166-1 three letter code (separated by a semicolon) to identify language and locale, but strings longer than 3 characters were being rejected. This correction checks for the semicolon and for long languages (which probably means they are using the above format), then passes the first three characters into the already existing iso mapper.
See https://github.com/geonetwork/core-geonetwork/pull/3759
> Language / Add support for ISO 639-2/T + ISO 3166-1 codes in language

- web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/templates/editor/editor.html
- web-ui/src/main/resources/catalog/templates/editor/editorboard.html
- web-ui/src/main/resources/catalog/views/default/module.js
- web-ui/src/main/resources/catalog/views/default/templates/home.html
- web-ui/src/main/resources/catalog/views/default/templates/results.html
- web-ui/src/main/resources/catalog/views/default/templates/searchForm.html
Replaces PR: https://github.com/geonetwork/core-geonetwork/pull/3662
The layout of GeoNetwork can have a fluid (full width) or fixed (centered) container. These classes were hard-coded in the templates. Now 2 variables are introduced that can be changed in the admin module, so hard-coded classes aren't needed anymore.
There is a setting for the home and search page, and a setting for the contribute and edit pages. So it is possible to have a homepage with a fixed and centered width while the editor has a full width layout.
The layout of some templates has been reordered a little in order to have parts/blocks on the page with a full page width (even when the layout has a fixed width, see the `topics` in the screenshot).
**Screenshot of the homepage**
**Screenshot of the editor**
> Settings to switch between fluid and fixed width container/layout

- domain/src/main/java/org/fao/geonet/domain/HarvesterSetting.java
- events/src/main/java/org/fao/geonet/events/server/ServerStartup.java
- pom.xml
- slave/Readme.md
- slave/pom.xml
- slave/src/main/java/org/fao/geonet/readonly/InterceptsStartup.java
- slave/src/main/java/org/fao/geonet/readonly/InterceptsUserAdd.java
- slave/src/main/java/org/fao/geonet/readonly/InterceptsUserUpdate.java
- slave/src/main/resources/config-spring-geonetwork-parent.xml
- slave/src/main/resources/config-spring-geonetwork.xml
- slave/src/main/resources/slave.properties
- web/pom.xml
- web/src/main/java/org/fao/geonet/Geonetwork.java
Usage: "mvn clean package install -P slave" to generate the war file or "mvn jetty:run -P slave" to run jetty (on web folder).
To run this instance you have to configure the master URL first. Configuration options are on file slave/src/main/resources/slave.properties 
masterURL is on https://github.com/geonetwork/core-geonetwork/pull/3712/files#diff-38229dfbdddf6cb469c704fa9b3ee403R2
With this profile active, GeoNetwork:
* Does not allow any login (intercepts all logins)
* Does not allow adding or updating any users (intercepts all database changes)
* [Optional] Remove all users except admin user, which is still used for internal GeoNetwork tasks. Admin user will not be available for login either.
* [Optional] Remove all harvesters from the database
* Create and run a harvester pointing …
> Adding slave mode.

- web-ui/src/main/resources/catalog/components/usersearches/UserSearchesDirective.js
- web-ui/src/main/resources/catalog/components/usersearches/partials/featuredusersearchesbutton.html
- web-ui/src/main/resources/catalog/components/usersearches/partials/featuredusersearchescards.html
- web-ui/src/main/resources/catalog/views/default/less/gn_results_default.less
- web-ui/src/main/resources/catalog/views/default/templates/home.html
- web-ui/src/main/resources/catalog/views/default/templates/searchForm.html
Make featured search more visible to user (currently only displayed in home page). 
Adds a directive which can layout as cards view (form home page) or dropdown list (for search page). Also adding a type attribute for future usage for another type of search group.
> User searches / List of featured search as dropdown.

- schemas/iso19139/src/main/plugin/iso19139/schematron/schematron-rules-url-check.sch
To avoid reporting errors on protocol the validation method in XslUtil does not handle.
> ISO19139 / Schematron / Check only http urls

- core/src/main/java/org/fao/geonet/kernel/AccessManager.java
eg. this is used in schema filtered element.
For test, create a record with "WWW:DOWNLOAD-1.0-http--download" set download privilege on & off to intranet group = Errors. The element is always filtered.
See https://github.com/geonetwork/core-geonetwork/blob/master/schemas/iso19139/src/main/plugin/iso19139/schema-ident.xml#L88-L90
> Access manager / Intranet group not found when using canDownload/Dynamic

- web-ui/src/main/resources/catalog/components/edit/geopublisher/GeoPublisherDirective.js
In Geopublisher control in the editor fixes a typo in the property `stylerUrl`.
The right value is `stylerurl`.
> Fixes typo in stylerurl property.

- web-ui/src/main/resources/catalog/templates/admin/page-layout.html
- web-ui/src/main/resources/catalog/views/default/less/gn_admin_default.less
This PR fixes to the sidebar for `Editor` and `Reviewer`. The sidebar was also showing an 'empty' main sidebar because the `Editor` and `Reviewer` had no access to the items in this sidebar. This PR hides the main sidebar and extends the 'sub sidebar'
**Screenshot of before:**
**Screenshot after the fix:**
This PR also fixes the background colour for active items in the `User` dropdown in the menubar.
> Fix for the sidebar in the Admin (for Editor and Reviewer)

- web-ui/src/main/resources/catalog/components/viewer/wmsimport/WmsImportDirective.js
- web-ui/src/main/resources/catalog/components/viewer/wmsimport/partials/layer.html
- web-ui/src/main/resources/catalog/components/viewer/wmsimport/partials/styles.html
- web-ui/src/main/resources/catalog/components/viewer/wmsimport/style/layertree.less
Before change
After change
* Replace long button title by icon and alt title
* Use "+" icon for add to map action (for both default and a styled layer)
* Add caret down icon for the list style popup
* Reduce spacing
> Map / Compact layer tree for better readability of large capability document

- core/src/main/java/org/fao/geonet/kernel/security/shibboleth/ShibbolethUserConfiguration.java
- core/src/main/java/org/fao/geonet/kernel/security/shibboleth/ShibbolethUserUtils.java
- core/src/test/java/org/fao/geonet/kernel/security/shibboleth/ShibbolethUserUtilsTest.java
- web/src/main/webapp/WEB-INF/config-security/config-security-shibboleth-overrides.properties
- web/src/main/webapp/WEB-INF/config-security/config-security-shibboleth.xml
Now we accept a list of groups and profiles to assign to the user.
Also, keys "updateProfile" and "updateGroups" were ignored. Now we can handle authorization safely.
Also, key "email" was ignored. Now we can setup an email using shibboleth.
Unit Tests added to explore corner cases.
I had added the missing keys on the config files. Also reordered the keys to match the same as in xml file and the same as in java config class, to make sure in the future no keys are lost.
To test this I used a browser extension to add HTTP headers manually.
The groups and profile headers now allow a list (separated by https://github.com/geonetwork/core-geonetwork/pull/3785/files#diff-1dcd473586cb00240bdfbcf814e536f9R40 ) to assign several groups with different profiles to the same user, as in the user …
> Improving Shibboleth authorization

- services/src/main/java/org/fao/geonet/api/records/formatters/FormatterApi.java
- web-ui/src/main/resources/catalog/views/default/directives/partials/mdactionmenu.html
Fix issue when multilingual record is browsed in french and click on PDF
link return the document in browser language which may be different.
Related to https://github.com/geonetwork/core-geonetwork/issues/3782
> Formatter / Add parameter to override language header.

- schemas/dublin-core/src/main/plugin/dublin-core/index-fields/default.xsl
Related to ISO19139 changes for keywords with anchor.
Before
After
> Dublin core / Record view / Keywords not displayed

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcService.js
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/linkServiceToDataset.html
- web-ui/src/main/resources/catalog/components/metadatamanager/EditorService.js
- web-ui/src/main/resources/catalog/locales/en-editor.json
When linking a service to a dataset, the service will be modified with a coupledResource + operatesOn (as before) and the dataset can be optionally modified with the following link added:
* a service with a WMS endpoint - a link to the WMS + layer name can be added to the dataset record
* a service with no URL - a link to the metadata record (main landing page in HTML) can be added to the dataset record
Related to https://github.com/geonetwork/core-geonetwork/commit/00bd2de0cf74fc429ba96d74cda632cc4ca4f670
Also fix the search which was only listing datasets (and for example not series) - replaced by search for all which is not a service.
> Associated resources / Clarify links added when linking service and datasets

- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/editor.html
- web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
- web-ui/src/main/resources/catalog/views/default/templates/recordView.html
This PR show the 'draft' message on the record view now in full width. Furthermore, the status on the editor dashboard has been moved. It's now under the title (see screenshot)
> FIX: Display 'Draft' message on record view in full width

- schemas/dublin-core/src/main/plugin/dublin-core/index-fields/default.xsl
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcService.js
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/linkServiceToDataset.html
- web-ui/src/main/resources/catalog/components/metadatamanager/EditorService.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/locales/en-editor.json
- web-ui/src/main/resources/catalog/templates/admin/settings/cssstyle.html
- web-ui/src/main/resources/catalog/views/default/less/gn_admin_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_navbar_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_variables_default.less
Replaces PR: https://github.com/geonetwork/core-geonetwork/pull/3652
Fixes for menubar colours for when custom colours are set in the admin.
It is possible to adjust the colours of the navigation/menu in the admin. However, not all colours where correctly used which resulted in a default colour for an active menu  (colours in the screenshot are only for testing purposes :-) ).
Furthermore, some colours where also used in the admin menu which could result in menu items with the same background colour and text colour.
This PR fixes the active menu colour, and adds default colours to the admin menu.
An extra setting is added for the background colour on hover and the active color
> FIX for menubar colours for when custom colours are set in the admin.

- core/pom.xml
- core/src/main/java/jeeves/server/dispatchers/ServiceManager.java
- pom.xml
- services/src/main/java/org/fao/geonet/guiservices/util/GetSettingValue.java
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v370/migrate-default.sql
- web/src/main/webapp/WEB-INF/config/config-service-pdf.xml
- web/src/main/webapp/loc/ara/xml/strings.xml
- web/src/main/webapp/loc/cat/xml/strings.xml
- web/src/main/webapp/loc/chi/xml/strings.xml
- web/src/main/webapp/loc/dut/xml/strings.xml
- web/src/main/webapp/loc/eng/xml/strings.xml
- web/src/main/webapp/loc/fin/xml/strings.xml
- web/src/main/webapp/loc/fre/xml/strings.xml
- web/src/main/webapp/loc/ger/xml/strings.xml
- web/src/main/webapp/loc/ita/xml/strings.xml
- web/src/main/webapp/loc/nor/xml/strings.xml
- web/src/main/webapp/loc/pol/xml/strings.xml
- web/src/main/webapp/loc/por/xml/strings.xml
- web/src/main/webapp/loc/rus/xml/strings.xml
- web/src/main/webapp/loc/spa/xml/strings.xml
- web/src/main/webapp/loc/tur/xml/strings.xml
- web/src/main/webapp/xslt/services/pdf/metadata-fop.xsl
- web/src/main/webapp/xslt/services/pdf/portal-present-fop.xsl
This pull request adds the following enhancements for the metadata selection pdf to create a report having a more professional look and feel:
- TOC page
- Configurable texts for header/footer
- Support to include external cover and intro pages
- Customise the pdf name
- Improve margins for printing
The different options can be customised in the Administration settings:
Attached a sample PDF including cover, toc and intro pages:
[metadata_20190507160221.pdf](https://github.com/geonetwork/core-geonetwork/files/3153051/metadata_20190507160221.pdf)
Old report, to compare differences:
[old-report.pdf](https://github.com/geonetwork/core-geonetwork/files/3153070/old-report.pdf)
> Metadata selection pdf improvements

- core/src/main/java/org/fao/geonet/kernel/search/facet/ItemBuilder.java
- web-ui/src/main/resources/catalog/components/search/facets/partials/dimension-facet-category.html
- web-ui/src/main/resources/catalog/components/search/facets/partials/dimension-facet-list.html
config-summary.xml give possibility to configure facets presenting search result...
sort by label may ignore case (as by value does not ignore case) and sorting order configuration can be trusted to work (no need to reorder at html side ?).
> Facets / Order by label ignore case (and server side only)

- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
- schemas/iso19139/src/main/plugin/iso19139/loc/eng/strings.xml
- web-ui/src/main/resources/catalog/views/default/less/gn_facets_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_navbar_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_pagination_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_result_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_results_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_search_default.less
- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-functions.xsl
- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
- web/src/main/webapp/xslt/base-layout-cssjs-loader.xsl
- web/src/main/webapp/xslt/common/render-html.xsl
- web/src/main/webapp/xslt/skin/default/skin.xsl
- web/src/main/webapp/xslt/ui-search/search-nojs.xsl
Replaces PR: https://github.com/geonetwork/core-geonetwork/pull/3645
This PR brings the layout of the NoJS view closer to the default views. A new class is introduced: gn-nojs to target styling for the NoJS views.
Changes to the styling
- use of `<blockquote>` for the filter options
Together with the styling some accessibility issues are addressed:
- added aria-roles
- better headings (`<h2>` follows `<h1>`)
- improved colour contrast
**Screenshots after the restyling**
> Improvements to the NoJS view

- es/config/records.json
- web-ui/src/main/resources/catalog/components/index/IndexRequest.js
- web-ui/src/main/resources/catalog/components/index/IndexRequestConfig.js
- web-ui/src/main/resources/catalog/components/viewer/heatmap/HeatmapService.js
- web-ui/src/main/resources/catalog/components/viewer/wfsfilter/WfsFilterDirective.js
- workers/wfsfeature-harvester/src/main/java/org/fao/geonet/harvester/wfsfeatures/worker/EsWFSFeatureIndexer.java
When indexing features, add 4 fields to store the coordinate of the
bounding box of each features. On client side use min/max aggregations
to retrieve the bounding box of all features matching filter.
When ES support for geo_bounds aggregation will be implemented for geo_shape type
See https://github.com/elastic/elasticsearch/issues/7574
The following would be better probably:
```
"viewport" : {
"geo_bounds" : {
"field" : "location",
"wrap_longitude" : true
}
}
```
See in action https://youtu.be/SKwnwN5RPKA
> WFS Feature / Zoom to filtered results.

- web-ui/src/main/resources/catalog/components/admin/importxsl/ImportXSLDirective.js
Related to https://github.com/geonetwork/core-geonetwork/commit/4193933ea0f19daae75c2050f8bf679d582ab086
In some cases, the element is an object and the empty line was added in such case.
Only setup the element value to the first transformation if it is not set to avoid a reset. In debug mode, it was working but not in prod mode.
Cache the call to get the list of transformation.
> Harvester / Avoid to set empty XSL transformation

- web-ui/src/main/resources/catalog/components/common/schemamanager/SchemaManagerService.js
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
- web-ui/src/main/resources/catalog/components/search/formfields/FormFieldsDirective.js
- web-ui/src/main/resources/catalog/js/edit/EditorController.js
In labels and codelist.xml, we have the possibility to constraint list of values using a display if attribute.
This filter can not be set in the associated resource panel according to the metadata record currently on edition. This PR add support for that.
eg. if you have 2 configs for protocol
```
<element name="gmd:protocol" id="398.0" alias="protocol"
displayIf="ancestor::node()[name()='gmd:MD_Metadata' and contains(gmd:metadataStandardName/*/gco:CharacterString, 'ISO 19139, MyOcean profile')]">
<label>Protocol</label>
<description>Connection protocol to be used</description>
<helper>
<option value="WWW:FTP">FTP</option>
<option value="WWW:MAIL">Mail</option>
<option value="WWW:LINK">Web link</option>
<option value="OGC:WMS">Web Map Service (OGC)</option>
<option value="OGC:WCS">Web …
```
> Editor / Helper & codelist / Add support to displayIf constraint in associated resource panel.

- services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
Error is related to the record history change. In the model, groupowner may be null. Error is:
```
date: "2019-03-06T10:39:31"
message: "The given id must not be null!; nested exception is java.lang.IllegalArgumentException: The given id must not be null!"
stack: "org.springframework.dao.Invali
```
> Transfert ownership / group owner may be null

- web-ui/src/main/resources/catalog/components/viewer/layermanager/partials/layermanageritem.html
- web-ui/src/main/resources/catalog/components/viewer/wfs/WfsDirective.js
- web-ui/src/main/resources/catalog/components/viewer/wfs/partials/download.html
- web-ui/src/main/resources/catalog/locales/en-search.json
* Fix dropdown not display in layer popup options (replaced by a select to be consistent with styling)
* Fix JS errors on layer download menu due to undefined capabilities
* Add a directive attribute to only init the widget on demand (when done on load, if the WMS is public and the WFS restricted, user is asked for credentials because of this directive even if the map layer loads fine. Add a step to init the directive so credentials are requested only when a user want to download the data)
* In layer menu, check only on demand
* In record view, check on load
* Cleaning some useless console.log
> Map / WFS download improvements

- schemas/schema-labels.xsd
- web-ui/src/main/resources/catalog/components/edit/editorhelper/EditorHelperDirective.js
- web-ui/src/main/resources/catalog/components/edit/editorhelper/partials/editorhelper.html
The following configuration adding ` editorMode="suggestion"` to the helper element: 
```xml
<element name="gmd:descriptor" id="258.0">
<label>Descriptor</label>
<description>Description of the range of a cell measurement value</description>
<helper displayIf="gco:CharacterString[contains(., 'temporal resolution: ')]" 
editorMode="suggestion">
<option value="temporal resolution: irregular">Irregular</option>
<option value="temporal resolution: instantaneous">Instantaneous</option>
<option value="temporal resolution: hourly mean">Hourly mean</option>
<option value="temporal resolution: hourly mean, weekly mean, monthly mean">Hourly mean, weekly mean, monthly mean</option>
<option value="temporal resolution: hourly instantaneous">Hourly instantaneous</option>
<option value="temporal …
```
> Editor / Helper / Add tags input mode.

- schemas/iso19139/src/main/plugin/iso19139/convert/OGCWxSGetCapabilitiesto19119/OGCCSWGetCapabilities-to-19119.xsl
- schemas/iso19139/src/main/plugin/iso19139/convert/OGCWxSGetCapabilitiesto19119/OGCSOSGetCapabilities-to-19119.xsl
- schemas/iso19139/src/main/plugin/iso19139/convert/OGCWxSGetCapabilitiesto19119/OGCSOSGetCapabilitiesLayer-to-19139.xsl
- schemas/iso19139/src/main/plugin/iso19139/convert/OGCWxSGetCapabilitiesto19119/OGCWxSGetCapabilitiesLayer-to-19139.xsl
- schemas/iso19139/src/main/plugin/iso19139/convert/OGCWxSGetCapabilitiesto19119/identification.xsl
- schemas/iso19139/src/main/plugin/iso19139/convert/OGCWxSGetCapabilitiesto19119/resp-party.xsl
- schemas/iso19139/src/main/plugin/iso19139/convert/ogcwxs-info-injection.xsl
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/ogcwxs.html
* Language encoding now use LanguageCode instead of CharacterString
* Language can now be defined in the record and preserved (priority is now: INSPIRE GetCapabilities language, record language, harvester config language and 'eng')
* Multilingual / Preserve translation in title and abstract fields in case a record is first harvested and then editor add translations. On next harvest preserve them.
* Validation / Avoid creation of 2 address blocs (one for address, one for the email)
* Validation / Abstract avoid nested CharacterString
* Validation / Online / Name was place before protocol
Those fix mainly applies when using the template mode of the OGC WxS harvester and when editor makes changes to the harvested records:
Work made in collaboration with Cantone di Ticino after advanced …
> Harvester / OGC WxS / More valid records and better multilingual support

- core/src/main/java/org/fao/geonet/util/XslUtil.java
Added utility method to retrieve iso language label from xsl files. Example of usage in `update-fixed-info.xsl` to add the label in `gmd:LanguageCode`:
```
<xsl:stylesheet  xmlns:java="java:org.fao.geonet.util.XslUtil"
...
<xsl:variable name="mainLanguage"
select="/root/*/gmd:language/gco:CharacterString/text()|
/root/*/gmd:language/gmd:LanguageCode/@codeListValue"/>
...
<xsl:template match="gmd:LanguageCode[@codeListValue]" priority="20">
<gmd:LanguageCode codeList="http://www.loc.gov/standards/iso639-2/">
<xsl:apply-templates select="@*[name(.)!='codeList']"/>
<xsl:value-of select="java:getIsoLanguageLabel(@codeListValue, $mainLanguage)" />
</gmd:LanguageCode>
</xsl:template>
```
> Utility method to retrieve the name (label) for an iso language using it's code for a specific language

- wro4j/src/main/java/org/fao/geonet/wro4j/GeonetWroModelFactory.java
The error "Parameter 'directory' is not a directory" thrown by FileUtils is not really helpful. 
Explain a bit more why it is failing.
It has been raised on different places already:
* https://sourceforge.net/p/geonetwork/mailman/message/35527805/
* https://github.com/georchestra/georchestra/issues/1120
Exception is now:
```
[INFO] Started Jetty Server
java.lang.IllegalArgumentException: Directory '/data/dev/gn/sextant/web-client/src/main/resources/catalog/lib/bootstrap-table/dist' is not a directory. It could be a missing library. Check the source if you have all dependency files required.
at org.fao.geonet.wro4j.GeonetWroModelFactory$ResourceDesc$1.iterator(GeonetWroModelFactory.java:719)
at org.fao.geonet.wro4j.GeonetWroModelFactory.addCssGroupsByRequireDependencies(GeonetWroModelFactor …
```
> Wro4j / More detailed error when a lib is not found.

- web-ui/src/main/resources/catalog/components/admin/harvester/partials/schedule.html
Unfortunately Quartz project has change documentation urls to have the exact version number instead of generic ones as previously (http://quartz-scheduler.org/documentation/quartz-2.x/tutorials/crontrigger).
Updated to use `2.1.7` version that is the latest from `2.1.x` version we use in Geonetwork (http://www.quartz-scheduler.org/documentation/). Probably if they make a new minor release, with the change for documentation urls, will require to be updated this link.
> Fix link to quartz crontrigger documentation in harvester schedule

- schemas/iso19139/src/main/plugin/iso19139/config/associated-panel/default.json
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html
- web-ui/src/main/resources/catalog/style/gn.less
Support tooltips in the Associated resources panel fields:
> Metadata editor - associated panel - support tooltips

- web-ui/src/main/resources/catalog/style/gn.less
Increase the z-index of the navbar in the editor to display the menus over the editor content
**Before:**
**After:**
> FIX: Increase the navbar z-index to display the menus over the editor content

- web-ui/src/main/resources/catalog/components/search/formfields/FormFieldsDirective.js
Fixes the check to initialise the group selected checking the value `null` that is used for example in the import controller: https://github.com/geonetwork/core-geonetwork/blob/master/web-ui/src/main/resources/catalog/js/edit/ImportController.js#L66
Also sets the selected value as string,otherwise angularjs adds empty option with the value of the group as a number as can't match it to the groups list, as expects a string.
As a side effect removes the empty group selection in the import metadata, what in my opinion was wrong as every metadata should be assigned to a group.
> Fix groupsCombo directive to select first group

- schemas/iso19139/src/main/plugin/iso19139/convert/thesaurus-transformation.xsl
- services/src/main/java/org/fao/geonet/api/registries/vocabularies/KeywordsApi.java
This is used in `config-editor.xml` when defining the attribute for `data-transformation` for the directive `data-gn-thesaurus-selector`, previously was send, but not used in the backend service:
```
<for name="gmd:descriptiveKeywords" addDirective="data-gn-thesaurus-selector">
<directiveAttributes data-transformation="to-iso19139-keyword-with-anchor" />
</for>
```
> Use tranformation parameter in Keyword API service to retrieve a keyword xml snippet

- web-ui/src/main/resources/catalog/js/admin/AdminController.js
Currently when accessing a page with tabs the default tab is displayed, but not selected in the tabs controls. For example, when accessing `Users and groups` in the Administration panel the url opened  is the following http://localhost:8080/geonetwork/srv/eng/admin.console#/organization, that display the users page (the default one), but doesn't show the option selected in the tab list:
With the changes:
> Select default option in admin UI in pages using tabs

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
In branch `3.4.x` of https://github.com/metadata101/iso19115-3 the parameters
of the process `thumbnail_add.xsl` are `thumbnail_url`, `thumbnail_desc` and
`thumbnail_type` (https://github.com/metadata101/iso19115-3/blob/2f484b053aabe8939c48bbeb0018824c1bbd724b/src/main/plugin/iso19115-3/process/thumbnail-add.xsl#L18-L21)
This commit fixes the names of these parameters in the
_Add online resource_ panel configuration to match the names in the schema
process. This also should fix the part of metadata101/iso19115-3#35 about
the overview not being added to the XML.
Backport of #3852.
> [BP 3.6.x] Fix thubmnail-add parameter names for ISO 19115-3

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
In branch `3.5.x` of https://github.com/metadata101/iso19115-3 the parameters
of the process `thumbnail_add.xsl` are `thumbnail_url`, `thumbnail_desc` and
`thumbnail_type` (https://github.com/metadata101/iso19115-3/blob/51911709ab4f7e7cb7f93bbd90121addcba69061/src/main/plugin/iso19115-3/process/thumbnail-add.xsl#L18-L21)
This commit fixes the names of these parameters in the
_Add online resource_ panel configuration to match the names in the schema
process. This also should fix the part of metadata101/iso19115-3#35 about the overview not being added to the XML
> Fix thumbnail-add.xsl parameter names for ISO 19115-3

- web-ui/src/main/resources/catalog/components/catalog/CatalogService.js
- web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v370/migrate-default.sql
Fixes a bug in `getServiceURL` that was returning the wrong port when HTTPS is used.
For example it returned `https://www.example.com:80/geonetwork/srv/` instead of
`https://www.example.com/geonetwork/srv`.
> Set `system/server/securePort` setting as public instead of internal

- web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
* Adds an id to the add attribute button in using the pattern `gn-attr-add-button-namespaceCOLONelement_insertRef` so it can be used in CSS/JS scripts.
> Adds an id to add attribute button

- web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionsDirective.js
- web-ui/src/main/resources/catalog/components/metadataactions/partials/transferownership.html
Shows a loading spinner while the load groups request is not yet finished.
Actually disables the Save button instead of just add the class `disabled` to it
if not user is selected.
> Improvements in transfer ownership dialog usability

- schemas/iso19139/src/main/plugin/iso19139/process/linked-data-checker.xsl
Since the previous `getUrlStatus` can throw an exception and interrupt the suggestions request
this commit changes the `getUrlStatus` call to `validateURL` that only returns `true` or `false`
but doesn't throw any excaption if for example the URL is malformed.
> Uses function validateUrl in linked-data-checker.xsl process

- web-ui/src/main/resources/catalog/components/viewer/searchlayerformap/partials/searchlayerformap.html
- web-ui/src/main/resources/catalog/locales/en-search.json
When user focus on search field this trigger an empty search. Currently user would have to focus and type "*" to trigger search for example.
if no record are returned a comprehensive message indicates that there is no record with reference to a map 
or to a WMS layer
> Map / Add map or layer from records / Search on focus and info when none found

- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
To avoid identification > identification for example
> Formatter / XSL / Do not repeat tab as header as it is already displayed in the tab itself

- schemas/iso19139/src/main/plugin/iso19139/layout/layout.xsl
Example of usage:
```
<field xpath="/gmd:MD_Metadata/gmd:identificationInfo/*/gmd:resourceMaintenance[1]/*/gmd:maintenanceAndUpdateFrequency"
name="cm-updateFrequency"/>
<field xpath="/gmd:MD_Metadata/gmd:identificationInfo/*/gmd:resourceMaintenance[position() > 1]/*/gmd:maintenanceAndUpdateFrequency"
name="cm-updateFrequency"
del="../.."/>
```
This allows to display a codelist element and to have the remove button acting on an ancestor element.
> Editor / Configuration / Add support for `@del` in codelist element

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcService.js
Currenlty if no layer selected (when the service does not provide valid URL for listing layers), coupledResource is populated with the service name.
> Associated panel / When there is no layer, coupledResource should not be added

- web-ui/src/main/resources/catalog/components/common/ows/OWSService.js
- web-ui/src/main/resources/catalog/components/viewer/wfs/WfsDirective.js
- web-ui/src/main/resources/catalog/components/viewer/wfs/WfsService.js
- web-ui/src/main/resources/catalog/components/viewer/wfs/partials/download.html
- web-ui/src/main/resources/catalog/locales/en-core.json
* Don't display messages & status before all is loaded (error or not)
* Make it work when URL contains GetCapabilities parameter by adding parameters to exclude in input URL
* Fix WFS download from layer tree panel
* Add missing translations
Example before
Example after
* if wrong URL, unable to connect to service
* if wrong feature type, list others
> WFS / Download improvements

- core/src/main/java/org/fao/geonet/kernel/EditLib.java
**Bug Description**
For our Dcat-ap plugin, we encountered a issue where some fields in the editor are not saved at all. Filling-up those inputs with some text then saving the editor does not modify the record. When the editor reload, those inputs fields are emptied.
**Expected behavior**
When saving the editor, the modifications made for those fields should be saved in the database and when the editor reloads, the fields should be pre-filled with the value previously encoded in it.
**Screenshots**
**Log file**
Not applicable.
**Desktop**
- All browsers
- GeoNetwork Version 3.6 and lower
- Tomcat 8 with Java 8
**Additional context**
Not applicable.
**Root cause**
When saving the editor, multiple xml fragments are sent in the back-end to be applied to the edited record.
If an XML fragment …
> Fix metadata text node saving

- web-ui/src/main/resources/catalog/locales/ca-editor.json
- web-ui/src/main/resources/catalog/locales/cs-editor.json
- web-ui/src/main/resources/catalog/locales/de-editor.json
- web-ui/src/main/resources/catalog/locales/en-editor.json
- web-ui/src/main/resources/catalog/locales/es-editor.json
- web-ui/src/main/resources/catalog/locales/fi-editor.json
- web-ui/src/main/resources/catalog/locales/fr-editor.json
- web-ui/src/main/resources/catalog/locales/is-editor.json
- web-ui/src/main/resources/catalog/locales/it-editor.json
- web-ui/src/main/resources/catalog/locales/ko-editor.json
- web-ui/src/main/resources/catalog/locales/nl-editor.json
- web-ui/src/main/resources/catalog/locales/ru-editor.json
- web-ui/src/main/resources/catalog/locales/sk-editor.json
- web-ui/src/main/resources/catalog/locales/zh-editor.json
Since commit 2779b741d6 link to XML view shown in editor error messages doesn't
point to the right URL. This commit change it to the new format
`/metadata/:id?tab=xml`
Backport of #3575.
> [BP] Fixes link to XML in editor

- services/src/main/java/org/fao/geonet/api/site/LoggingApi.java
- web-ui/src/main/resources/catalog/js/admin/DashboardStatusController.js
LoggingApi  / admin UI (related to issue #3549):
* Removing the argument passed to the private method isAppenderLogFileLoaded, which results in calculating the fileAppender once (at first call)
* Replacing the XHR call in the admin UI by a window.location, forcing the browser to actually download the content returned by the webservice
Caveats:
If the logging configuration is reloaded, I am not sure the current code will update the fileAppender file location. this might require both beans to be aware of each other, then null'ing the fileAppender member variable each time the log4j config is changed.
Runtime tested
> Fixes LoggingApi (#3549)

- schemas/iso19139/src/main/plugin/iso19139/convert/thesaurus-transformation.xsl
- schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields-keywords.xsl
- schemas/iso19139/src/main/plugin/iso19139/update-fixed-info-keywords.xsl
Use the namespace defined in the thesaurus file to add the title as an Anchor when the selected keywords mode in the editor is `anchor`:
```
<gmd:thesaurusName>
<gmd:CI_Citation>
<gmd:title>
<gmx:Anchor
xlink:href="http://inspire.ec.europa.eu/theme#">
GEMET - INSPIRE themes, version 1.0
</gmx:Anchor>
</gmd:title>
```
In other modes is added added as a `CharacterString` (as previously):
```
<gmd:thesaurusName>
<gmd:CI_Citation>
<gmd:title>
<gco:CharacterString>
GEMET - INSPIRE themes, version 1.0
</gco:CharacterString>
</gmd:title>
```
Required for INSPIRE related thesaurus.
> Add thesaurus title as an Anchor when adding iso19139 in Anchor mode

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
Fix an issue when linking to a dataset without adding the service link in the target.
When linking to a WFS or ATOM, use the correct service URL to be added to the dataset (instead of the formatter):
> Editor / Link to dataset / Init uuid correctly, Add support for WFS and ATOM services

- services/src/main/java/org/fao/geonet/api/records/InspireValidationApi.java
- services/src/main/java/org/fao/geonet/api/records/formatters/FormatterApi.java
- web-ui/src/main/resources/catalog/components/validationtools/GnmdInspireValidationDirective.js
Schema is supported if an extension of iso19139 or iso19115-3 and provides a formatter nammed iso19139.
Example with an ISO19115-3 record:
Funded by metawal
> INSPIRE / Validation / Convert non ISO19139 records in order to do remote validation

- schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields-date.xsl
- web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
This is the backporting to 3.6.x of https://github.com/geonetwork/core-geonetwork/pull/3620 from @fxprunayre
> [BP 3.6.x] Editor / Missing asterisk on + action when cardinality is 1..n

- web-ui/src/main/resources/catalog/components/common/ows/OWSService.js
When using a background map which is using multiple layers from the same service, the layer name may be like `layer1,layer2`.
Currently, this function does not found the layer. 
Check if all layer in the list are defined in the capabilities.
eg.
```
<ows-context:ResourceList>
<ows-context:Layer name="3,2,1,7,12,13,4,5,6,8,9,10" group="Background layers" hidden="false" opacity="1">
<ows-context:Server service="urn:ogc:serviceType:WMS" version="1.3.0">
<ows-context:OnlineResource
xlink:href="https://land.discomap.eea.europa.eu/arcgis/services/Background/Background_Cashed_WGS84/MapServer/WmsServer"/>
<ows:Title>EEA discomap background</ows:Title>
```
> WMS / Add support for group of layers when searching in capabilities 

- schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields-keywords.xsl
In simple (more precisely "flat" mode) views, keywords are displayed by default with a fieldset. This can be customized per thesaurus using the `fieldset` config:
```
<thesaurus key="external.theme.NVS.L05POS"
fieldset="false"
transformations="to-iso19139-keyword"/>
```
The idea is to keep flat mode view as simple as possible.
But in this case all other thesaurus are displayed using a fieldset - and the editor config can't configure for all thesaurus in a record. Below, INSPIRE, theme sextant and ISO topics are known but others no:
This change use the no fieldset mode when the view is flat:
But config-editor can still force usage of fieldset mode by declaring the thesaurus.
Advanced view is using the fieldset mode:
> Editor / Keywords / Simple layout in flat mode

- web-ui/src/main/resources/catalog/templates/admin/harvest/harvest-settings.html
- web-ui/src/main/resources/catalog/views/default/less/gn_admin_default.less
When harvester names in the list with harvesters are too long the count badge is partly hidden. This PR displays a longer name on more than one line, so the counter is visible.
**Before:**
**After:**
> Fix for long harvester names

- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/templates/admin/settings/cssstyle.html
- web-ui/src/main/resources/catalog/views/default/less/gn_layout_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_search_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_variables_default.less
This PR adds new CSS variables for the search box on the `Home` and `Search` page.
The following variables have been added:
- outline for search box
- background-color for the search button
- color for search button
These 3 variables can be set in the admin pages in the `CSS & Style` section:
> New CSS variables for the Search Box

- web-ui/src/main/resources/catalog/js/CatController.js
This is used line 309 and as not part of the default config was never displayed in admin > Settings UI.
> Map / Missing bing key config

- web-ui/src/main/resources/catalog/style/gn_metadata_pdf.less
- web/src/main/webapp/xslt/base-layout-cssjs-loader.xsl
This PR improves the styling of the PDF export. The stylesheet used is specifically for the PDF. The styling now looks more like the detail view
**Screenshot of the document:**
> Improve the styling of the PDF document

- schemas/iso19139/src/main/plugin/iso19139/schema.xsd
- schemas/iso19139/src/main/plugin/iso19139/schema/gsr/gsr.xsd
- schemas/iso19139/src/main/plugin/iso19139/schema/gsr/spatialReferencing.xsd
Currently adding a vertical element, the `gmd:verticalCRS` is added to the xml, but not displayed in the metadata editor, due to missing namespace `gsr` in the related xsd files. 
If not present, the types in the `gsr` xsd files are loaded without namespace prefix, but the backend code to add the element in the editor uses the namespace prefix to match it. This pull request adds the namespace to the required xsd files, being displayed properly now:
> Fix gmd:verticalCRS to display choices in advanced view

- services/src/test/java/org/fao/geonet/api/records/editing/InspireValidatorUtilsTest.java
It is hanging up the test processes waiting for a response from the upstream remote server.
> Disable InspireValidatorUtilsTest#testLifeCycle test

- schemas/iso19139/src/main/plugin/iso19139/formatter/jsonld/iso19139-to-jsonld.xsl
- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-functions.xsl
- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
in #3714 a json-ld schema.org snippet was introduced in metadata view, this duplicates the schema.org annotations, this pr therefore removes the schema.org microdata
todo: same for iso19115-3
> remove microdata, 

- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid.html
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/list.html
- web-ui/src/main/resources/catalog/components/utility/partials/draftvalidationwidget.html
- web-ui/src/main/resources/catalog/locales/en-core.json
- web-ui/src/main/resources/catalog/style/gn.less
- web-ui/src/main/resources/catalog/style/gn_search.less
- web-ui/src/main/resources/catalog/views/default/less/gn_results_default.less
Fix for: https://github.com/geonetwork/core-geonetwork/issues/3869
Uniform styling for the status on the search results and metadata page. The `no thumbnail` image is now in a separate `<div>`, otherwise the status badges would be displayed on top of the `no thumbnail` image.
The changes are made for both the `grid` and `list` search results.
**Screenshot after the changes:**
Changes:
- new way to display no thumbnail image
- remove duplicate styles
- cleanup unused styles
- fix for background colour on hover for cards on the results list
> Uniform styling for the status on the search results and metadata page

- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataUtils.java
Currently cancelling an editing session where a saved action occurred restore the XML of the record (with the correct datastamp) but the changedate in the db table is not restored to the initial value (and the record is on top when sorting by modification date). Set updateDateStamp to true as the date stamp is retrieved from the `geonet:info` (see previous argument) when cancelling.
Test:
* Go to http://localhost:8080/geonetwork/srv/fre/catalog.edit#/board
* Edit a record not on top of the list is another tab
* Save
* Trigger search on editor board, record is on top
* Cancel
* Trigger search on editor board, record is on its initial position (it used to be on top before this fix)
> Editing / Cancel / Restore the change date as it was before the editing

- services/src/main/java/org/fao/geonet/services/main/SelectionSearch.java
- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-functions.xsl
- web/src/main/webapp/loc/ara/xml/strings.xml
- web/src/main/webapp/loc/cat/xml/strings.xml
- web/src/main/webapp/loc/chi/xml/strings.xml
- web/src/main/webapp/loc/dut/xml/strings.xml
- web/src/main/webapp/loc/eng/xml/strings.xml
- web/src/main/webapp/loc/fin/xml/strings.xml
- web/src/main/webapp/loc/fre/xml/strings.xml
- web/src/main/webapp/loc/ger/xml/strings.xml
- web/src/main/webapp/loc/ita/xml/strings.xml
- web/src/main/webapp/loc/nor/xml/strings.xml
- web/src/main/webapp/loc/pol/xml/strings.xml
- web/src/main/webapp/loc/por/xml/strings.xml
- web/src/main/webapp/loc/rus/xml/strings.xml
- web/src/main/webapp/loc/spa/xml/strings.xml
- web/src/main/webapp/loc/tur/xml/strings.xml
- web/src/main/webapp/xslt/services/pdf/metadata-fop.xsl
- web/src/main/webapp/xslt/services/pdf/portal-present-fop.xsl
* Remove unused code
* Style PDF with same colors as in angular view (no more old 2.10 blue)
* Add extent, resource type, last update, all overviews
* Create section for metadata link in HTML/PDF/XML with proper link to
formatters
* (Experimental) Add option to use a formatter (only works for public record, looks to be quite slow and memory consuming) - it would be better to use iText in Java directly
Examples
* Default
[apur_catalogue_20190709111725.pdf](https://github.com/geonetwork/core-geonetwork/files/3372273/apur_catalogue_20190709111725.pdf)
* With formatter
[apur_catalogue_20190709112639.pdf](https://github.com/geonetwork/core-geonetwork/files/3372277/apur_catalogue_20190709112639.pdf)
> Search results / PDF improvements

- web-ui/src/main/resources/catalog/components/search/resultsview/gridRelated.js
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid.html
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/list.html
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/style/gn_search.less
- web-ui/src/main/resources/catalog/views/default/less/gn_results_default.less
- web-ui/src/main/resources/catalog/views/default/templates/gridRelatedList.html
Currently related records are displayed in a dropdown
In grid mode, it is probably good as we don't want to have variable height depending on number of related. When using row mode, this template is useful:
> Search results / Add template to display related record as list instead of dropdown

- services/src/main/java/org/fao/geonet/api/records/InspireValidationApi.java
- services/src/main/java/org/fao/geonet/api/records/editing/InspireValidatorUtils.java
- services/src/main/resources/config-spring-geonetwork.xml
- services/src/test/java/org/fao/geonet/api/records/editing/InspireValidatorUtilsTest.java
- web-ui/src/main/resources/catalog/components/validationtools/GnmdInspireValidationDirective.js
- web-ui/src/main/resources/catalog/components/validationtools/partials/mdValidationTools.html
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/templates/admin/settings/system.html
* Default validator to use is now http://inspire.ec.europa.eu/validator/
* Add configurable levels of validation (now TG13, TG2 DS, TG2 SDS) - can be customized in bean configuration
* API / Add operation to return available testsuites.
* Admin / Add option to set the INSPIRE validator URL to the default one
@pvgenuchten, I'm not sure which conformance class we have to use for service from class 1 to 7. Do you know how we should configure that ?
> Editor / Validation / INSPIRE / Add support for TG2

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/RecordInfo.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Harvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Search.java
Backport of #3916. Only the client part, not the `search.xml` service. With this PR
the client GN will be able of harvesting new v3.8.0 GNs and to use paginated requests,
avoiding timeouts with big catalogs.
> Paginate GeoNetwork type harvester

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/RecordInfo.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Harvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Search.java
Backport of #3916. Only the client part, not the `search.xml` service. With this PR
the client GN will be able of harvesting new v3.8.0 GNs and to use paginated requests,
avoiding timeouts with big catalogs.
Backport of #3927.
> [BP] Paginate GeoNetwork type harvester

- services/src/test/java/org/fao/geonet/api/records/editing/InspireValidatorUtilsTest.java
Fix a NPE in InspireValidatorUtilsTest  caused by @Autowired without Spring
Context introduced in #3915 (cc9ef24c).
> Fix NullPointerException in InspireValidatorUtilsTest

- schemas/iso19110/src/main/plugin/iso19110/layout/config-editor.xml
Hello geonetwork community,
This is a fix for #3704. See link precise description of the bug.
After this fix, iso19110 editor simple view renders (3 printscreens below):
and
and
iso19110 editor full view renders:
> group attributes with corresponding feature type / ISO19110 editor

- common/src/main/java/org/fao/geonet/utils/Resolver.java
- common/src/main/java/org/fao/geonet/utils/ResolverWrapper.java
- common/src/main/java/org/fao/geonet/utils/Xml.java
- core/src/main/java/jeeves/server/JeevesProxyInfo.java
- core/src/main/java/org/fao/geonet/kernel/SchemaManager.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataValidator.java
Each metadata schema contains a file oasis-catalog.xml with "schemaLocation hints to local schemas to make sure that GeoNetwork edits and validates against a schema it knows about.". When more schemas are used, during the validation all the oasis-catalog.xml are used together, creating undesired overrides when a namespace is present in more than one schema.
This PR creates specific **Resolver** for each schema available, to use during the validation. The centre of this change is ResolverWrapper that changes to be a Singleton, to be a map of resolvers, one per each schema.
The map is initialized at startup in SchemaManager, and used for each validation.
Note: It seems that the validation functions in Xml.java are used to validate also resources not specific for metadata schemas. These …
> [BUG] - Load schema related oasis-catalog in Resolver

- schemas/iso19139/src/main/plugin/iso19139/update-fixed-info.xsl
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v370/migrate-default.sql
This is an INSPIRE requirement and should be ok for other ISO19139 profiles
> ISO19139 / Format / nilReason is set to unknown when missing

- core/src/main/java/org/fao/geonet/kernel/KeywordBean.java
- schemas/iso19139/src/main/plugin/iso19139/convert/OGCWxSGetCapabilitiesto19119/OGCCSWGetCapabilities-to-19119.xsl
- schemas/iso19139/src/main/plugin/iso19139/convert/OGCWxSGetCapabilitiesto19119/OGCWxSGetCapabilities-to-19119.xsl
- schemas/iso19139/src/main/plugin/iso19139/convert/OGCWxSGetCapabilitiesto19119/identification.xsl
- schemas/iso19139/src/main/plugin/iso19139/convert/ogcwxs-info-injection.xsl
- schemas/iso19139/src/main/plugin/iso19139/convert/thesaurus-transformation.xsl
- schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
- schemas/iso19139/src/main/plugin/iso19139/process/add-service-info-from-wxs.xsl
- schemas/iso19139/src/main/plugin/iso19139/process/inspire-themes-and-topiccategory.xsl
- schemas/iso19139/src/main/plugin/iso19139/process/onlinesrc-add.xsl
- schemas/iso19139/src/main/plugin/iso19139/process/sibling-add.xsl
- schemas/iso19139/src/main/plugin/iso19139/update-fixed-info.xsl
- schemas/iso19139/src/test/resources/org/fao/geonet/schemas/xsl/process/input.xml
- schemas/iso19139/src/test/resources/org/fao/geonet/schemas/xsl/process/onlinesrc-add-multilingual.xml
- schemas/iso19139/src/test/resources/org/fao/geonet/schemas/xsl/process/onlinesrc-add-simplelinkwithdesc.xml
- services/src/test/resources/org/fao/geonet/api/records/attachments/record-with-external-url-for-thumbnails.xml
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v370/migrate-default.sql
- web/src/main/webapp/xsl/conversion/OGCWMCtoISO19139/OGCWMC-OR-OWSC-to-ISO19139.xsl
- web/src/main/webapp/xsl/conversion/OGCWMCtoISO19139/identification.xsl
TG2 validation for INSPIRE expect [(most of the time](https://github.com/inspire-eu-validation/ets-repository/blob/master/metadata/2.0/common/ets-md-common-bsxets.xml#L190-L195)) the codelist URL to be `http://standards.iso.org/iso/19139/resources/gmxCodelists.xml` (eg. https://github.com/inspire-eu-validation/ets-repository/blob/master/metadata/2.0/datasets-and-series/ets-md-datasets-and-series-bsxets.xml#L427-L428).
> ISO19139 / INSPIRE / Validation is expecting a specific URL for codelist file.

- services/src/main/java/org/fao/geonet/api/records/MetadataSampleApi.java
Sometimes necessary to be able to load subtemplates/fragments from the schema templates directory with a known uuid so that templates and other records can  refer to them with xlinks.
eg. templates/sub-cc-by-4.0.xml:
`
<mco:MD_LegalConstraints xmlns:mdb="http://standards.iso.org/iso/19115/-3/mdb/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:mco="http://standards.iso.org/iso/19115/-3/mco/1.0" xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0" xmlns:xlink="http://www.w3.org/1999/xlink" title="Creative Commons CC-BY-4.0" uuid="urn:csiro:marlin:license:cc-by-4">
...
</mco:MD_LegalConstraints>
`
The uuid and title attributes are read and then removed when the subtemplate is loaded to ensure validity.
> Allow subtemplates to specify uuid and title as attributes on root element

- web/src/main/webapp/WEB-INF/classes/schematron/iso_svrl_for_xslt2.xsl
Since commit https://github.com/fxprunayre/core-geonetwork/commit/514c9b5ab4319dbb0b9a2278e6888b82e7c8c110 in PR #3298 the schematron throws an error when the `<sch:assert>` `see` attribute contains a URL. For example
``` 
Error at svrl:failed-assert on line 320 column 56 of schematron-rules-nl-19115-basis.xsl:
XPST0003: XPath syntax error at char 10 on line 320 in {...https://docs.geostandaarden...}:
QName cannot end with colon: {https:}
Error at svrl:failed-assert on line 353 column 52 of schematron-rules-nl-19115-basis.xsl:
XPST0003: XPath syntax error at char 10 on line 353 in {...https://docs.geostandaarden...}:
QName cannot end with colon: {https:}
Error at svrl:failed-assert on line 384 column 56 of schematron-rules-nl-19115-basis.xsl:
XPST0003: XPath syntax error at char 10 on …
```
> Fix error when sch:assert/@see attribute contains a URL

- schemas/iso19139/src/main/plugin/iso19139/layout/layout.xsl
- web-ui/src/main/resources/catalog/components/thesaurus/ThesaurusDirective.js
- web-ui/src/main/resources/catalog/locales/en-core.json
- web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
- web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
Applies when using a thesaurus to populate the input text and keyword if to set the xlink:href of the Anchor.
Example configuration:
```xml
<for name="gmd:useLimitation"
use="data-gn-keyword-picker">
data-thesaurus-key="external.theme.httpinspireeceuropaeumetadatacodelistLimitationsOnPublicAccess-LimitationsOnPublicAccess"
data-thesaurus-concept-id-attribute="xlinkCOLONhref"/>
</for>
```
Depending on the presence or not of the Anchor link, the UI was different when initializing the editor (URL above or below input depending if the record is multilingual or not). This was related to the fact that the keyword directive if not present add a new input after the element with JS and if the xlink:href attribute is present, then the XSL build the input.
After:
* Simple view …
> Editor / Anchor support / Improve layout

- web-ui/src/main/resources/catalog/views/default/less/gn_results_default.less
- web-ui/src/main/resources/catalog/views/default/templates/results.html
This PR improves the styling for the toolbar in the search results page.
Changes:
- uniform colours for `hover` and `active` state
- no white background for text in dropdown
**Background for text in dropdown:**
**After:**
> Styling improvements to the search toolbar

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/wfsfeatures/WfsFeaturesParams.java
WFS Feature Harvester is the only(?) harvester that stores an XML query as a harvester parameter (GetFeature query). The harvester passes the query through JDOM, XSLT and converts it to JSON for display in the u/i. The only way this can be done safely is to keep the query in the form of an escaped XML string. But the query has to be in XML when it is sent to the WFS by the harvester. This fix adds logic to handle the case when the query is already an escaped XML string and needs to be converted to XML for the harvester to send to the WFS (the contrary case was already handled). Without this fix, the user would have to save the harvester to make sure the query was in XML format to send to the WFS, otherwise a cryptic error about parsing an empty WFS getfeature query would be returned.
> WFS Feature Harvester BUG fix

- services/src/main/java/org/fao/geonet/api/records/InspireValidationApi.java
- services/src/main/java/org/fao/geonet/api/records/editing/InspireValidatorUtils.java
- services/src/test/java/org/fao/geonet/api/records/editing/InspireValidatorUtilsTest.java
Inspire Validator calls now use directly GeonetHttpRequestFactory instead of the HttpClient in it. This to avoid issues with the pool of connection managed by it.
> Inspire Validator calls now use directly GeonetHttpRequestFactory

- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java
From historical reason ?, update-fixed-info (ufo) was not applied to templates. But now, this is causing issue as ufo is making important changes which also applies to template. eg. all thesaurus handling, nilReason, codelist updates, gml@id, ... When editors try to validate template they are facing issues that they don't have with records. So it does not make much sense to not apply ufo to template.
> Editing / Update-fixed-info applies to template

- core/src/main/java/jeeves/config/springutil/JeevesDispatcherServlet.java
In some configurations Tomcat/Jetty can decide to not redirect from `/geonetwork` to `/geonetwork/`.
In these cases accessing /geonetwork causes a `NullPointerException`. This commit fixes the case
when Request.getPathInfo() returns null.
```
2019-08-01 15:18:39,972 ERROR [jeeves] - Error occurred within a transaction
at jeeves.config.springutil.JeevesDispatcherServlet.setNodeId(JeevesDispatcherServlet.java:80)
at jeeves.config.springutil.JeevesDispatcherServlet.access$000(JeevesDispatcherServlet.java:46)
at jeeves.config.springutil.JeevesDispatcherServlet$1.doInTransaction(JeevesDispatcherServlet.java:57)
at jeeves.config.springutil.JeevesDispatcherServlet$1.doInTransaction(JeevesDispatcherServlet.java:54)
at …
```
> Fix NullPointerException when server doesn't redirect

- schemas/iso19139/src/main/plugin/iso19139/loc/dut/labels.xml
Remove multiple occurrences of entries for the same `name`. This was causing
a fail in the the method `gn-fn-metadata:getLabel` and it stopped the rendering
of the metadata editor for iso19139 when Dutch language was used.
> Remove duplicated element entries in Dutch labels.xml

- schemas/iso19139/src/main/plugin/iso19139/loc/dut/labels.xml
Backport of #3958.
Remove multiple occurrences of entries for the same `name`. This was causing
a fail in the the method `gn-fn-metadata:getLabel` and it stopped the rendering
of the metadata editor for iso19139 when Dutch language was used.
> [BP] Remove duplicated element entries in Dutch labels.xml

- core/src/main/java/org/fao/geonet/kernel/search/LuceneSearcher.java
- csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/CatalogSearcher.java
When creating a portal eg. `copernicus` with filter `+any:copernicus` from admin > source, the filter was not applied to csw queries
Request
http://localhost:8080/geonetwork/copernicus/eng/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetRecords&typeNames=gmd:MD_Metadata
should return the subset of records corresponding to the portal.
> Portal / Add portal filter to CSW queries.

- services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
Records is inserted but in the process, the generated UUID is not used and report an error:
```
Record with UUID 'daa-b311-41db-a638-b309ceeba98e' not found in this catalog
```
> Import record / Generate UUID return ResourceNotFoundException

- web-ui/src/main/resources/catalog/style/gn_metadata.less
- web-ui/src/main/resources/catalog/views/default/directives/partials/attributetable.html
- web-ui/src/main/resources/catalog/views/default/templates/recordView.html
Small styling changes for the attribute table for ISO19110 in the recordView
Related to https://github.com/geonetwork/core-geonetwork/pull/3951
Changes made:
- new class `gn-table-attribute`
- less padding in table cell
- different styling for the table in table
> Styling changes for the attribute table for ISO19110 in the recordView

- web-ui/src/main/resources/catalog/style/gn_search.less
Fix for https://github.com/geonetwork/core-geonetwork/issues/3966
The sort by field is not converted to `lowercase` via CSS anymore
> FIX: Remove lowercase in sortBy dropdown

- web-ui/src/main/resources/catalog/components/category/CategoryDirective.js
- web-ui/src/main/resources/catalog/components/category/partials/category.html
- web-ui/src/main/resources/catalog/js/search/SearchController.js
Fix for https://github.com/geonetwork/core-geonetwork/issues/3967
Order the categories by the translated label for the `advanced search ` and `harvester setting`.
> Fix for #3967: Order the categories by the translated label

- web-ui/src/main/resources/catalog/templates/admin/settings/system.html
The scrollspy in the settings page of the admin did not include all the sections. This was partly because of non-unique IDs. This PR fixes this and adds an extra, second level to the scrollspy
Related to (v 3.4) issue: https://github.com/geonetwork/core-geonetwork/issues/3926
Changes:
- introduced extra level to loop over
- unique IDs
- changed `<h1>` to `<legend>`
**Screenshot of the old situation:**
**Screenshot after the changes:**
> FIX: Include all blocks in the Admin Scrollspy

- schemas/iso19139/src/main/plugin/iso19139/layout/layout.xsl
- web/src/main/webapp/xslt/common/functions-metadata.xsl
Add xpath to make it more strict on the matching element. Currently the first one is used.
eg. configuration to populate format and specification based on
thesaurus
```xml
<for name="cit:title"
xpath="/mdb:MD_Metadata/mdb:distributionInfo/mrd:MD_Distribution/mrd:distributionFormat/mrd:MD_Format/mrd:formatSpecificationCitation/cit:CI_Citation/cit:title"
use="data-gn-keyword-picker">
<directiveAttributes data-thesaurus-key="external.theme.httpregistrymetawalcodelistmediatypes-media-types"
data-thesaurus-concept-id-attribute="xlinkCOLONhref"/>
</for>
<for name="cit:title"
xpath="/mdb:MD_Metadata/mdb:dataQualityInfo/mdq:DQ_DataQuality/mdq:report/mdq:DQ_DomainConsistency/mdq:result/mdq:DQ_ConformanceResult/mdq:specification/cit:CI_Citation/cit:title"
use="data-gn-keyword-picker"> …
```
> Editor / Using thesaurus on element with same name does not work.

- core/src/main/java/org/fao/geonet/kernel/datamanager/draft/DraftMetadataUtils.java
Fixing the issue causing the Null pointer Exception
```
2019-08-22 11:34:06,343 ERROR [geonetwork.api] - UserFeedbackAPI - newUserFeedback: null
at org.fao.geonet.repository.MetadataRatingByIpRepositoryImpl.averageRating(MetadataRatingByIpRepositoryImpl.java:61)
at org.fao.geonet.repository.MetadataRatingByIpRepositoryImpl$$FastClassBySpringCGLIB$$ef81c63a.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:651)
at org.fao.geonet.repository.MetadataRatingByIpRepositoryImpl$$EnhancerBySpringCGLIB$$458d5789.averageRating(<generated>)
at sun.reflect.GeneratedMethodAccessor712.invoke(Unknown Source)
at …
```
> Fix rating issue

- core/src/main/resources/config-spring-geonetwork.xml
- services/src/main/java/org/fao/geonet/api/records/editing/MetadataEditingApi.java
- Comment beans in `core` module that are "overridden" in `web` module using `primary` attribute, but during startup seem assigning the ones in the `core` module causing errors when trying to edit a published copy.
- Fixed also an error with the redirect to edit the draft copy, seem caused by the changes in https://github.com/geonetwork/core-geonetwork/pull/3622
After the redirect was written in the output stream, causing the following error when editing a metadata and being redirected to the draft version:
```
Caused by: java.lang.IllegalStateException: WRITER
at org.eclipse.jetty.server.Response.getOutputStream (Response.java:917)
at javax.servlet.ServletResponseWrapper.getOutputStream (ServletResponseWrapper.java:142)
at javax.servlet.ServletResponseWrapper.getOutputStream …
```
> Draft copy - As a reviewer or an Editor, it is impossible to open the editor on a record with a draft copy attached to it Fixes #3896

- schemas/iso19110/src/main/plugin/iso19110/index-fields/default.xsl
- web-ui/src/main/resources/catalog/locales/en-search.json
- web-ui/src/main/resources/catalog/views/default/templates/recordView.html
- web/src/main/webapp/WEB-INF/config-lucene.xml
Hi geonetwork community,
This pull requests does two things:
1. Fix the indexing and display in recordView of iso19110 gfc:producer/md:CI_ResponsibleParty. It uses to display only the company name in "Metadata information" section. Now it shows all fields of the contact (address, phone number, etc.) in the section "About this resource". 
2. Add to indexes and recordView a new field : versionIdentifier (mapped to versionNumber of iso19110)
Both changes endup with the following rendering of iso19110 recordView (only "About this resource" section shown):
> Pr iso19110 fix responsibleparty indexing + add version identifier

- schemas/config-editor.xsd
- schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-tpl.xsl
Sample configuration:
```xml
<table fieldset="false" for="mac:MI_Instrument">
<header>
<col label="mac:MI_Instrument"/>
<col label="mac:MI_Platform"/>
<col/>
</header>
<row>
<col xpath="mac:identifier/*/mcc:code"/>
<col xpath="mac:mountedOn/*/mac:identifier/*/mcc:code"/>
<col del=".."/>
</row>
</table>
```
Needs an update in ISO19115-3.2018
> Editor / Table mode / Add option to not to have a fieldset around the table

- web-ui/src/main/resources/catalog/components/common/ows/OWSService.js
Speed up all when loading layers from the same server (GetCapabilities document can be quite big).
Stuff lost in Sextant history...
> Map / Cache getcapabilities parsing.

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
- web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
- web/src/main/webapp/xslt/ui-metadata/form-configurator.xsl
Example configuration to make a button to add thumbnail and to add an
aggregation to a source/mission type:
```xml
<action type="associatedResource"
name="add-thumbnail"
process="onlinesrc">
<directiveAttributes>addThumbnail</directiveAttributes>
</action>
<action type="associatedResource"
name="add-ref-to-source-mission"
process="sibling">
<directiveAttributes>{"associationType": "source", "initiativeType": "mission"}</directiveAttributes>
</action>
```
Allows to create custom button pointing directly to a specific type of online resource or aggregation:
> Editor / Associated resources / Set default value to action

- web-ui/src/main/resources/catalog/templates/editor/editorboard.html
- web-ui/src/main/resources/catalog/templates/top-toolbar.html
- web-ui/src/main/resources/catalog/views/default/less/gn_view.less
This PR optimises the toolbars of the contribute dashboard on medium sized screens, paying extra attention to languages with long button labels (e.g. German).
Furthermore, this PR takes care of overlapping `sort` and `pagination` options.
Changes made:
* max width for buttons and truncate labels
* hide some labels on medium sized screens
* add `title` attribute to buttons
**Screenshot of truncated buttons**
> Fix for overlapping buttons on contribute dashboard on medium sized screens

- web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
- web-ui/src/main/resources/catalog/style/gn_metadata.less
- web-ui/src/main/resources/catalog/views/default/less/gn_view.less
This PR adds extra classes to the related items in the metadata page. These classes make it easier to manipulate the look and feel of the related items via a custom view/styling
Classes added to:
- `.gn-related-..type..` to the related item itself
- title (`gn-related-title`)
- description (`gn-related-description`)
> Added extra classes to related resources

- schemas/iso19139/src/main/plugin/iso19139/process/onlinesrc-add.xsl
- schemas/iso19139/src/main/plugin/iso19139/update-fixed-info.xsl
* remove MimeFileType detection which breaks multilingual editing in associated resource panel (values always removed)
* remove geocat.ch hardcoded ref to DE generating invalid updatekey in some cases
* xlink clean link without trailing commas
* populate-free-text already check if textgroup local was present. Cleaning
* quicker selection of the main language free text
@sppigot, @josegar74  , would like your opinion on the MimeFileType removal ? or should we add an option to allow activation of this ?
> ISO19139 / Multilingual record / Fix online source name editing

- core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
- pom.xml
- web/pom.xml
- web/src/main/webResources/WEB-INF/config.properties
- web/src/main/webResources/WEB-INF/web.xml
For security reason, it may be relevant to populate one index with all
records with restricted access (to be configured on elastic side) and
another public index with only public records. This allows to create
Kibana dashboard with no restricted access.
> ES / Add option to populate an index with only public records.

- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
- web-ui/src/main/resources/catalog/style/gn_metadata.less
- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-variables.xsl
* Add `related` and `sideRelated` variables to control which related item to display in top header and in side panel
* Add `template` variable to use a custom XSL template to use
* Add `viewMenu` variable to display or not view menu switcher
* Citation is in footer
* Add CSS for abstract in header
* Make modal popup work in both angular view and formatter view
* Avoid duplicated org name.
Related work : https://github.com/metadata101/iso19115-3.2018/pull/9
> Formatter improvements

- inspire-atom/src/main/java/org/fao/geonet/services/inspireatom/AtomPredefinedFeed.java
- inspire-atom/src/main/resources/config-spring-geonetwork.xml
This pull request fix two issue in one.
**Describe the bug**
Beans from package org.fao.geonet.inspireatom are not scanned by Spring. 
**To Reproduce**
Example with [http://localhost:8080/geonetwork/srv/eng/atom.download?...](http://localhost:8080/geonetwork/srv/eng/atom.download)
**Log file**
```
2019-09-13 09:43:47,087 ERROR [jeeves.service] - Exception when executing service
2019-09-13 09:43:47,087 ERROR [jeeves.service] -  (C) Exc : org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.fao.geonet.inspireatom.InspireAtomService] is defined
2019-09-13 09:43:47,153 ERROR [jeeves] - Error occurred within a transaction
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type …
```
> INSPIRE ATOM - Beans not in context + AtomPredefineFeed endpoints not mounted correctly

- web-ui/src/main/resources/catalog/components/common/ows/OWSService.js
Related to https://github.com/geonetwork/core-geonetwork/commit/22a19736cff1a2438981956e1d66d6741adbebb2 which introduced a 5sec timeout
A too short timeout is also quite useless because then the direct query is cancelled on the browser, got -1 as status, then it goes to the proxy then is cancelled on the client side and the proxy continue ...
> OGC / GetCapabilities / Time out set to 1 min.

- core/src/main/java/org/fao/geonet/web/LocaleRedirects.java
- domain/src/main/java/org/fao/geonet/repository/SourceRepository.java
- services/src/main/java/org/fao/geonet/api/sources/SourcesApi.java
- web-ui/src/main/resources/catalog/style/gn.less
- web/src/main/webapp/xslt/base-layout-nojs.xsl
- web/src/main/webapp/xslt/common/render-html.xsl
- web/src/main/webapp/xslt/ui-search/portal-list.xsl
* Add home page for portal list in API /api/sources (Accept header
starts with text/html)
* "/" redirect to default node if only one.
* "/validPortalId" redirect to the corresponding portal.
* "/invalidPortalId" redirect to portal list if more than one portal
available or to the default if only one (fix #3884).
> Portal list

- web/pom.xml
Only a limited set of users is having ES index with security layer.
> ES / By default do not insert in a public index

- web-ui/src/main/resources/catalog/style/gn.less
- web-ui/src/main/resources/catalog/style/gn_editor.less
- web-ui/src/main/resources/catalog/style/gn_fonts.less
- web-ui/src/main/resources/catalog/style/gn_inspire.less
- web-ui/src/main/resources/catalog/style/gn_pickers.less
- web-ui/src/main/resources/catalog/style/gn_search.less
- web-ui/src/main/resources/catalog/views/default/less/gn_layout_default.less
- web/src/main/webapp/xslt/base-layout-cssjs-loader.xsl
This PR splits the large GeoNetwork stylesheet in smaller stylesheets. 
This is done in order to speed up the loading of the different files. A browser can load these smaller files simultaneously. The first styles needed to draw the opening page are accessible faster. The page doesn't have to wait until the one large stylesheet is loaded.
The new GN stylesheet is now (more or less) half the size of the old one.
> Splitting the large GN stylesheet into smaller ones and speed up loading

- web-ui/src/main/resources/catalog/views/default/less/gn_admin_default.less
The `admin` page had a padding of 15px on both sides, but is designed to be full width. This PR removes the padding.
**Screenshot of old situation**
**The new situation**
> Fix: Remove padding in Admin page

- services/src/main/java/org/fao/geonet/api/sources/SourcesApi.java
On some tomcat installation, it looks like content type is sometimes set to text/html. Not sure if related to Spring.
> Portal list / Force content type to text/html

- web-ui/src/main/resources/catalog/style/gn_admin.less
- web-ui/src/main/resources/catalog/templates/admin/settings/logo.html
Before
After
Was broken by https://github.com/geonetwork/core-geonetwork/commit/e789b00c2ee65b551d723151e1b0002950378811
> Admin / Logo / Improve styling

- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/templates/admin/admin.html
- web-ui/src/main/resources/catalog/templates/admin/settings/sources.html
- web-ui/src/main/resources/catalog/views/default/less/gn_admin_default.less
Currently if a portal has no matching records, a message indicate that the catalogue is empty. This is not always true.
Add a specific message for empty portal:
Also add icon and logo in list of sources
> Portal / Add message when a portal is empty.

- services/src/main/java/org/fao/geonet/api/records/MetadataUtils.java
Error is:
```xml
<apiError>
<code>unsatisfied_request_parameter</code>
<description>Cannot add null object</description>
<message>IllegalAddException</message>
</apiError>
```
This is related to a record having a reference to a non existing feature catalogue eg.
```xml
<gmd:contentInfo >
<gmd:MD_FeatureCatalogueDescription>
<gmd:includedWithDataset>
<gco:Boolean>false</gco:Boolean>
</gmd:includedWithDataset>
<gmd:featureCatalogueCitation uuidref="fr-120066022-ca-jdd-36d391b9-8b55-4eb3-b891-c02b706ad97a" xlink:href="http://localhost:8080/geonetwork/srv/fre/csw?service=CSW&request=GetRecordById&version=2.0.2&outputSchema=http://www.isotc211.org/2005/gmd&elementSetName=full&id=fr-120066022-ca-jdd-36d391b9-8b55-4eb3-b891-c02b706ad97a"/>
</gmd:MD_FeatureCatalogueDescription>
</gmd:contentInfo> …
```
> API / Related / Errors in case a feature catalogue is linked but not found

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/HarvestResult.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/CswHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/CswParams.java
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/csw.html
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/csw.js
- web/src/main/webapp/xsl/xml/harvesting/csw.xsl
In some cases, CSW returns a limited set of Queryables or user wants to filter on more restrictive queries. This adds the possibility to filter input records with an XPath expression.
> Harvester / CSW / Add XPath filter

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java
GeoNetwork supports harvesting unsupported iso19139 profile records from another GeoNetwork harvester by falling back to the core iso19139 metadata record included in the mef by the other GeoNetwork instance.
However, when harvesting these records, it's not possible to apply a transform as GeoNetwork incorrectly tries to source the transform from the process directory for the unsupported profile which of course doesn't exist and aborts harvesting the record.
Fix this by sourcing the transform to be applied from the process directory of the harvested metadata format.
> Use transform for harvested metadata format (GeoNetwork harvester) (3.8.x)

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java
GeoNetwork supports harvesting unsupported iso19139 profile records from another GeoNetwork harvester by falling back to the core iso19139 metadata record included in the mef by the other GeoNetwork instance.
However, when harvesting these records, it's not possible to apply a transform as GeoNetwork incorrectly tries to source the transform from the process directory for the unsupported profile which of course doesn't exist and aborts harvesting the record.
Fix this by sourcing the transform to be applied from the process directory of the harvested metadata format.
> Use transform for harvested metadata format (GeoNetwork harvester) (master)

- web-ui/src/main/resources/catalog/js/search/SearchController.js
Fix for https://github.com/geonetwork/core-geonetwork/issues/4092
The categories in the `Advanced Search` panel were not translated to the chosen language. This PR replaces the hardcoded English to the preferred, chosen language.
**Screenshot after the change**
> Fix for untranslated categories in the Advanced Search panel

- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v382/migrate-default.sql
The type is now mainly used to display a specific icon depending on the source type
If null, no icon displayed
> SQL / Migration / Set source types

- healthmonitor/src/main/java/org/fao/geonet/monitor/health/IndexHealthCheck.java
JEST has no update and ES 7 introduced a breaking change in the search result response. Workaround for now. Next step is moving to ES branch instead which removed JEST in favor of ES High level java client.
> ES / Index health check / Fix due to incompatibility between JEST 6.3.1 and ES 7.x

- web-ui/src/main/resources/catalog/components/viewer/gfi/FeaturesLoader.js
The `hits.total` property on the ES responses used to be an integer but it is now an object, which broke the features table rendering with a layer using ES-indexed data.
> Fixes how the total feature count is computed with ElasticSearch

- web/src/main/webResources/WEB-INF/config-spring-geonetwork.xml
Same as https://github.com/geonetwork/core-geonetwork/blob/master/web/src/main/webResources/WEB-INF/config-db/defaultJdbcDataSource.xml#L34
For example changing es.url may not be taken into account.
> Property file / Ensure the one in WEB-INF is loaded

- web-ui/src/main/resources/catalog/components/admin/harvester/partials/logopicker.html
Quite useful when you have 100 logos or more ...
> Logo picker / Order by file name & allow filtering when more than 10 logos

- web-ui/src/main/resources/catalog/templates/admin/dashboard/record-links.html
Only admin can trigger analyze link task.
See https://github.com/geonetwork/core-geonetwork/blob/master/services/src/main/java/org/fao/geonet/api/links/LinksApi.java#L143-L151
> Record link / Disable analyze button (only allowed for admin user)

- web-ui/src/main/resources/catalog/templates/editor/top-toolbar.html
Fix for https://github.com/geonetwork/core-geonetwork/issues/3517
Hide the button and dropdown when VCS (Version Control System) in not enabled. This PR hides the dropdown toggle button because the versioning item is the only item in the dropdown
> Fix for #3517: Hide the button and dropdown when VCS (Version Control System) in not enabled

- web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
Fix for https://github.com/geonetwork/core-geonetwork/issues/3862
The content of the privileges dialog didn't fit in all languages. This PR makes the modal dialog a bit wider in the editor (but it still fits the screen) so all languages will fit in the window. 
**Screenshot after the change**
> Fix for #3862: Fit content in Privileges dialog

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/BaseAligner.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractParams.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/HarvestResult.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/arcsde/ArcSDEHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/fragment/FragmentHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geoPREST/Aligner.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/GeonetHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/GeonetParams.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Harvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFilesystemHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFsHarvesterFileVisitor.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/oaipmh/Harvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/ogcwxs/Harvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/thredds/Harvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/webdav/Harvester.java
- web-ui/src/main/resources/catalog/components/admin/harvester/partials/privileges.html
- web-ui/src/main/resources/catalog/js/admin/HarvestSettingsController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/csw.js
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/geonetwork.js
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/webdav.js
- web/src/main/webapp/xsl/xml/harvesting/common.xsl
- web/src/main/webapp/xsl/xml/harvesting/geonetwork.xsl
When more than one harvester harvest the same record, then record is usually rejected or overriden.
It can override existing, but the privileges are not preserved. This option preserve privileges set in the different harvesters.
This can happen when you have user admins not aware of other harvesters and duplicates are created and different set of privileges need to be combined. 
It applies to GeoNetwork, CSW and Webdav protocol.
Also do some cleanup of useless comment and unused method.
> Harvester / Add option to append privileges in case of override

- domain/pom.xml
- pom.xml
We recently updated from 3.6 to 3.8.1 however after the upgrade, we started having build issues.  
Prior to the upgrade, the build would take approx 15 - 20 minutes. After the upgrade it was taking 70 minutes or more.
Our build platform is a 2 core 4GB Ram system in the Azure.  We are using Azure devops pipeline for doing the build. The build run all the tests.
After some testing, we could see that the 2.6 build would run without using any swap space (So it did not require more than 4GB of ram).  But the 3.8.1 build was using 3+GB of swap at some points in the testing.  It almost looks like there are some memory leaks in some of the tests - but I did not find the cause so this is only a guess?
If we update the system to use 8GB of ram, then the build would take between 20 and 30 minutes - …
> Set threads in maven-surefire-plugin based on number of cores.

- web-ui/src/main/resources/catalog/templates/editor/new-metadata-horizontal.html
- web-ui/src/main/resources/catalog/templates/editor/new-metadata-vertical.html
Currently gourp owner can be left empty if user is Editor, Reviewer or UserAdmin.
Force to set the value (like when harvesting) to attach record to one of the user group. 
Only admin can leave it blank.
When user is member of one group, then the UI is simple and the group owner is set automatically
> New metadata / Force to set groupOwner when user is not an administrator

- services/src/main/java/org/fao/geonet/api/tools/i18n/TranslationApi.java
When moving from older version, translations may be incomplete (depending on language setup changes). JSON can then contains null which make translate directive to fail with errors and it breaks the UI in some places:
```
TypeError: Cannot read property 'substr' of null
at ha (lib.js?v=ff50cfc1dea2dbd6a7f1c491fbd3e91405026a32:390)
at Function.V.instant (lib.js?v=ff50cfc1dea2dbd6a7f1c491fbd3e91405026a32:390)
at c (lib.js?v=ff50cfc1dea2dbd6a7f1c491fbd3e91405026a32:390)
at fn (eval at compile (lib.js?v=ff50cfc1dea2dbd6a7f1c491fbd3e91405026a32:237), <anonymous>:4:199)
at lib.js?v=ff50cfc1dea2dbd6a7f1c491fbd3e91405026a32:135
at m.$digest (lib.js?v=ff50cfc1dea2dbd6a7f1c491fbd3e91405026a32:150)
at m.$apply (lib.js?v=ff50cfc1dea2dbd6a7f1c491fbd3e91405026a32:154)
at …
```
> API / Translation should never be null

- web-ui/src/main/resources/catalog/style/gn.less
Fix for https://github.com/geonetwork/core-geonetwork/issues/4123
After updating to Chrome 78 the dropdown items with a `&nbsp;` (in combination with the `min-width` of the dropdown) were sometimes displayed on 2 lines.
This PR also brings back icons (in dropdowns) that were lost after PR https://github.com/geonetwork/core-geonetwork/pull/4044
**Before**
**After the change**
> Fix for #4123: "Breaking" dropdowns in Chrome 78 and missing icons

- web-ui/src/main/resources/catalog/views/default/templates/recordView.html
In the current situation the `Source Dataset` block in the detailview is in the table of the `Technical Information`. This means that the content is put in just one column and the text of the button doesn't fit.
This PR takes the `Source Dataset` block out of the table and positions it under this table. This results in a more balanced view and solves the button text problem.
After the change
> Position 'Source Dataset' block in detailview under 'Technical Information' table

- web-ui/src/main/resources/catalog/components/viewer/localisation/partials/localisation.html
The update to Chrome 78 "broke" the styling for the `localisation` search on the map. This PR fixes it.
**Before**
**After**
I guess this is the smallest PR ever 😄
> Fix the localisation style for Chrome 78

- common/src/main/java/org/fao/geonet/NodeInfo.java
- core/src/main/java/jeeves/config/springutil/JeevesDispatcherServlet.java
Depending on the last resource retrieved, the portal id was sometimes set
to a webapp root folder name which was not matching any portals.
Exclude those folders.
Problem was random, but for example, signin with the popup with wrong
password was most of the time redirecting to a non existing node (ie.
catalog).
> Portal id / Exclude webapp root folders

- web-ui/src/main/resources/catalog/style/gn.less
Fix for https://github.com/geonetwork/core-geonetwork/issues/4142
Add a maximum height to the thumbnail image. This prevents form elements to be pushed out of sight. 
Extra: Try to minimize the amount of scrollbars.
**The 'Add Online resource' dialog after the changes**
> Fix for #4142: Maximum height for image thumbnail in 'Add Online resource' dialog

- web-ui/src/main/resources/catalog/views/default/module.js
This fixes a bug where on the record view clicking on "View WMS" would mutate the corresponding `link` and break the WMS service info. Can be reproduced here:
https://www.geograndest.fr/geonetwork/srv/fre/catalog.search?t=1555485535#/metadata/FR-180067019_IGNF_ORTHOHR_RVB_CIGAL_2015
Before clicking:
After clicking:
This is still present on master.
Note: this is only noticeable when using an external viewer.
> Record view / Prevent mutating the index record when clicking on 'view WMS'

- services/src/main/java/org/fao/geonet/api/records/InspireValidationApi.java
- services/src/main/java/org/fao/geonet/api/records/editing/InspireValidatorUtils.java
- services/src/test/java/org/fao/geonet/api/records/editing/InspireValidatorUtilsTest.java
My previous PR https://github.com/geonetwork/core-geonetwork/pull/3952 breaks the Inspire Validation services when a proxy is set. This is a fix for this.
I'm not sure if it's a good idea to apply this kind of fixes directly to GeonetHttpRequestFactory. What do you think?
> Inspire validator proxy geonet

- services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
- web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextDirective.js
- web-ui/src/main/resources/catalog/components/viewer/owscontext/partials/owscontext.html
- web-ui/src/main/resources/catalog/locales/en-search.json
Those options make it more consistent with other UI used to create metadata record (New metadata, Import record).
> Map viewer / Save map as metadata / Options to choose group and publication status

- web/src/main/webapp/xslt/common/functions-metadata.xsl
Make metadata:isFieldFlatModeException more robust in case the view does not have config (eg. directory view)
> Directory / Fix error when opening editor.

- core/src/main/java/org/fao/geonet/MetadataResourceDatabaseMigration.java
This is to fix the URLs of attachments when you import a MEF file from one GeoNetwork to the other. The current mechanism does not work with all kinds of attachments.
> Update attachment records on import

- web-ui/src/main/resources/catalog/components/search/facets/FacetDimensionDirective.js
Currently, configuration only hides facet which are not in the config, but user can not override the order.
@jahow maybe there is a more elegant way to do that?
> UI Config / Facet / Order facet according to configuration

- schemas/iso19139/src/main/plugin/iso19139/update-fixed-info.xsl
Bug fix -  wrong gco:nilReason update-fixed-info.xsl  was only checking the PT_FreeText and not CharacterString which was creating a gco:nilReason attribute when gco:CharacterString was not empty but PT_FreeText was.
This was happening during after importing data which did not contain the main language in the PT_FreeText yet. Running the update-fixed-info.xsl the first time was setting the gco:nilReason and the PT_FreeText. Running the update-fixed-info.xsl the second time would remove the gco:nilReason as the PT_FreeText existed. 
Also renamed isEmpty to isMainLanguageEmpty because it is only checking the main language for empty - not all languages.
> iso19139 / incorrect gco:nilReason assignment

- web-ui/src/main/resources/catalog/components/metadataactions/RelatedDirective.js
Example, when you have a custom layout and you need to hide a parent when no relation found. Below, we want to hide the row element containing the label and the directive:
Use a CSS selector to point to a container element to hide.
> Related resource / Add possibility to hide a parent element in case no relation found.

- core/src/main/java/org/fao/geonet/kernel/BatchEditParameter.java
- core/src/main/java/org/fao/geonet/kernel/EditLib.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractParams.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java
- services/src/main/java/org/fao/geonet/api/records/editing/BatchEditsApi.java
- services/src/test/java/org/fao/geonet/services/metadata/BatchEditsServiceTest.java
- web-ui/src/main/resources/catalog/js/admin/HarvestSettingsController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/locales/en-editor.json
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/csw.html
- web-ui/src/main/resources/catalog/templates/admin/harvest/type/csw.js
- web/src/main/webapp/xsl/xml/harvesting/common.xsl
Add the possibility to define a batch editing configuration for an harvester. Catalogue administrator needs to be able to update some information during harvesting eg.
* Add some classification based on keywords
* Remap organisation name to make it consistent with local record values
Some users have been activating the option to edit harvested record but it is not easy to synchronize records later on (except for the OGC WxS harvester which only focus on a small set of information from the capabilities).
Batch edits allows to add/replace/delete information during the harvesting process.
Example of configuration:
```json
[
{
"condition": "count(.//gmd:keyword[*/text() = 'watersheds']) > 0",
"xpath": "/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:descriptiveKeywords[1]",
"value": …
```
> Harvester / Add batch edit parameter.

- schemas/iso19139/src/main/plugin/iso19139/update-fixed-info.xsl
update-fixed-info.xsl creating empty PT_FreeText when gco:CharacterString is null.
This is not necessary so check for empty gco:CharacterString before adding PT_FreeText
> Don't create PT_FreeText on main language if the CharacterString is null

- web-ui/src/main/resources/catalog/locales/en-admin.json
It got removed, along with it's associated help text at some point
> Add ui-defaultSearchString back in

- inspire-atom/src/main/java/org/fao/geonet/inspireatom/util/InspireAtomUtil.java
- schemas/iso19139/src/main/plugin/iso19139/convert/ATOM/inspire-atom-feed.xsl
- schemas/iso19139/src/main/plugin/iso19139/loc/eng/labels.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/fre/labels.xml
- web-ui/src/main/resources/catalog/components/viewer/atom/AtomDirective.js
- web-ui/src/main/resources/catalog/components/viewer/atom/partials/atomDownload.html
- web-ui/src/main/resources/catalog/locales/en-core.json
- web-ui/src/main/resources/catalog/locales/en-editor.json
- web-ui/src/main/resources/catalog/locales/en-search.json
* Return exception with a bit more context. There is some assumptions
made that normal user can't find without digging into the code.
Before:
After:
* Support entry with multiple links (eg.
https://geoservices.wallonie.be/inspire/atom/BU_Dataset_b795de68-726c-4bdf-a62a-a42686aa5b6f.xml)
> ATOM improvement.

- web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
In Internet Explorer 11 the asterisk indicating a required field has different sizes that are too large. This small PR fixes the issue.
**The error in IE11**
**After the fix**
> Fix: right size for asterisk in IE11

- web-ui/src/main/resources/catalog/components/common/map/mapService.js
- web-ui/src/main/resources/catalog/components/common/map/wmsQueue.js
- web-ui/src/main/resources/catalog/components/viewer/layermanager/partials/layermanageritem.html
- web-ui/src/main/resources/catalog/components/viewer/legendpanel/partials/legendpanel.html
- web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextDirective.js
- web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextService.js
- web-ui/src/main/resources/catalog/components/viewer/wmsimport/partials/styles.html
- web-ui/src/main/resources/catalog/style/gn_viewer.less
* Adding 2 times the same layer was not managed in wmsQueue
* Fix issue when style name contains special character
* Force UTF-8 encoding when writing context
* Add style name on temporary layer while loading
* Make style consistent between layer manager and legend panel
* Break long words
* Order style in list
> Map / Add support for same layer with different styles

- schemas/iso19139/src/main/plugin/iso19139/index-fields/index-subtemplate.xsl
- schemas/iso19139/src/main/plugin/iso19139/process/datasets-remove.xsl
- optimizes remove-dataset by operateson element. operateson contains link to dataset-record in xlink:href (if no @uuidref), as used in [TG Req 3.6; inspire metadata; p65](https://inspire.ec.europa.eu/sites/default/files/documents/metadata/inspire-tg-metadata-iso19139-2.0.1.pdf)
- index subtemplates also for resource constraints
> improve operateson link remove+resource constraint subtemplate option

- web-ui/src/main/resources/catalog/components/common/ows/OWSService.js
The `Style` property of the layer in the getcapabilities document was modified and as such some code that relied on it would break. This was the case for legend rendering.
Note: this is not a final fix as this code was probably necessary for some other features (such as https://github.com/geonetwork/core-geonetwork/pull/3859). This PR is open for discussion, thanks.
> Fix legends for map layers

- services/src/main/java/org/fao/geonet/api/processing/XslProcessApi.java
* updateDatestamp does not apply as it is handled by DataManager (so only when saving. Not on preview)
* indexing is not needed in preview mode too
> API / XSL Process / Preview should not save in db. 

- core/src/main/java/org/fao/geonet/kernel/DataManager.java
- core/src/main/java/org/fao/geonet/kernel/XmlSerializer.java
- core/src/main/java/org/fao/geonet/kernel/XmlSerializerDb.java
- core/src/main/java/org/fao/geonet/kernel/XmlSerializerSvn.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/IMetadataManager.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataUtils.java
- core/src/test/java/org/fao/geonet/kernel/XmlSerializerIntegrationTest.java
- services/src/main/java/org/fao/geonet/api/processing/XslProcessUtils.java
- services/src/main/java/org/fao/geonet/api/records/formatters/FormatterApi.java
This is a really old bug (5 years!) we observed in Sextant which was happenning from time to time and never managed to track down until now.
The record history helped on solving this (Thanks @PascalLike).
The issue happens under the following circunstances:
* Create a record, add attachments with protocol WWW:DOWNLOAD-1.0-http--download
* Update record privileges and allow Edit and disable Download for group A
* Sign in with a user of group A and edit the record
* Save is working fine.
* Add a thumbnail (ie. processing), the element filtered by the download operation are removed.
Schema-ident.xml is taking care of filtering:
```
<filter
xpath="*//gmd:onLine[*/gmd:protocol/gco:CharacterString = 'WWW:DOWNLOAD-1.0-http--download']"
ifNotOperation="download"/>
```
Usually when editing, the …
> Elements targeted by operation filters can be removed on processing.

- web-ui/src/main/resources/catalog/views/default/less/gn_map_default.less
The map panel can fall behind the bottom bar when it contains a lot of content. This PR calculates the height of the map panel and takes into account the height of the bottom bar.
**Before**:
**After**:
> Fix: Map panel height should take into account the height of the bottom bar

- web-ui/src/main/resources/catalog/views/default/less/gn_map_default.less
The Feature info table on the map is displayed behind the fixed bottombar. This PR displays the table above the bottombar by taking into account the height of the bottombar.
**Before the change:**
**After the fix:**
> Fix: Feature info table should display above bottombar

- web-ui/src/main/resources/catalog/components/viewer/draw/partials/draw.html
- web-ui/src/main/resources/catalog/locales/en-search.json
Add a label for the text `<input>` for the annotation text on the map, so the user knows where the input is for
**Before**:
**After**:
> Add label for the annotation text input

- web-ui/src/main/resources/catalog/components/viewer/gfi/FeaturesLoader.js
Feature info on a layer in the map with a layer with a not recognised feature format caused an error. This error also stopped the feature info of other layers in the map.
This PR catches the unknown format and lets the other feature info to pass through.
> Fix for toLowerCase bug for featureinfo on unknown format

- web-ui/src/main/resources/catalog/style/gn_viewer.less
When using the localisation popup in the map, longer search results 'break' out of the dropdown. This PR fixes this by truncating the search result text, and on smaller screens the text will be displayed on 2 lines.
**Before**:
**After**:
> Fix for the width of the localisation dropdown (for all screen sizes)

- web-ui/src/main/resources/catalog/views/default/less/gn_search_default.less
In the map, in the layer settings dropdown, the texts can 'break' out off the popover window when they are too large. This PR increases the `max-width` of the popover a little, so texts fit.
> Increase the max width of the popover

- web-ui/src/main/resources/catalog/components/common/map/print/PrintDirective.js
- web-ui/src/main/resources/catalog/components/common/map/print/PrintMapDirective.js
The print size/rectangle had a bug on retina screens. The rectangle was drawn almost outsize of the view. This PR fixes this and draws the print rectangle in the center of the screen.
See the screenshot in: https://github.com/geonetwork/core-geonetwork/pull/4265
> Fix for the print size on retina screens

- web-ui/src/main/resources/catalog/views/default/less/gn_map_default.less
The feature identify table was not displayed at the bottom of the map. This PR fixes this issue, it fixes the identify table to the bottom of the map.
> Fix for sticking the feature identify table to the bottom

- web-ui/src/main/resources/catalog/components/metadataactions/RelatedDirective.js
When linking records with aggregates (19139) or associated resources (19115-3), if user connect the 2 records in both direction then the link is displayed twice. Combined siblings and associated records in one list to avoid this.
> Record view / Associated resources / Avoid duplicates

- web-ui/src/main/resources/catalog/components/common/map/print/PrintDirective.js
- web-ui/src/main/resources/catalog/components/common/map/print/PrintMapDirective.js
- web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid4maps.html
- web-ui/src/main/resources/catalog/components/viewer/ViewerModule.js
- web-ui/src/main/resources/catalog/components/viewer/gfi/GetFeatureInfoDirective.js
- web-ui/src/main/resources/catalog/components/viewer/partials/mainviewer.html
- web-ui/src/main/resources/catalog/style/gn_infolist.less
- web-ui/src/main/resources/catalog/style/gn_search.less
- web-ui/src/main/resources/catalog/style/gn_viewer.less
- web-ui/src/main/resources/catalog/views/default/less/gn_map_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_search_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_view.less
- web-ui/src/main/resources/catalog/views/default/module.js
- web-ui/src/main/resources/catalog/views/default/templates/home.html
GeoNetwork has the option to save your own maps, these can be displayed on the homepage and in a maps panel in the sidebar on the map.
The maps on the homepage had their own block. This PR adds the latest maps on the same 'level' as the 'latest news' and 'most popular'. The different list types also apply to the latest maps. Furthermore it fixes the go to map link from the homepage (click on the thumbnail).
This PR also gives the latest maps in the map panel the same styling as on the homepage.
> Reorganize latest maps on the homepage and the map

- web-ui/src/main/resources/catalog/components/viewer/wps/partials/processform.html
@jahow 
Use processDescription to check possible outputs. 
This is used later to loop over the processOutputs.
> fix(wps) use processDescription for dropdown output options

- domain/src/main/java/org/fao/geonet/domain/LinkStatus.java
@josegar74 please ?
@fxprunayre por favor ?
so to avoid 
java.sql.BatchUpdateException: Batch entry 0 insert into LinkStatus (batchKey, checkDate, failing, link, statusInfo, statusValue, id) values ('Host name ''www.upc.es'' does not match the certificate subject provided by the peer (CN=www.upc.edu, OU=UPCnet, O=Universitat Politècnica de Catalunya. BarcelonaTech., L=Barcelona, C=ES, SERIALNUMBER=Government Entity, OID.1.3.6.1.4.1.311.60.2.1.3=ES, OID.2.5.4.15=Government Entity)', '2019-12-10T13:49:32', 'y', 334555813, 'Host name ''www.upc.es'' does not match the certificate subject provided by the peer (CN=www.upc.edu, OU=UPCnet, O=Universitat Politècnica de Catalunya. BarcelonaTech., L=Barcelona, C=ES, SERIALNUMBER=Government Entity, OID.1.3.6.1.4.1.311.60.2.1.3=ES, …
> avoid to set too long batchkey

- services/src/main/java/org/fao/geonet/api/ApiUtils.java
- services/src/main/java/org/fao/geonet/api/mapservers/MapServersApi.java
Sometimes LuceneSearcher throws this exception:
`java.lang.IllegalStateException: There needs to be a ServiceContext in the thread local for this thread`
when it's used from the API service. This commits sets the service
context created in `ApiUtils.createServiceContext` as thread local allowing
LuceneSearcher to find it in the thread local store.
> Set context as thread local when it is created in ApiUtils

- services/src/main/java/org/fao/geonet/api/ApiUtils.java
- services/src/main/java/org/fao/geonet/api/mapservers/MapServersApi.java
Sometimes LuceneSearcher throws this exception:
`java.lang.IllegalStateException: There needs to be a ServiceContext in the thread local for this thread`
when it's used from the API service. This commits sets the service
context created in `ApiUtils.createServiceContext` as thread local allowing
LuceneSearcher to find it in the thread local store.
Backport of #4157.
> [BP] Set context as thread local when it is created in ApiUtils

- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
Handle display of all possible combinations of organisation name, individual name and position name in iso19139 full view
Fix for 19139 full view for https://github.com/geonetwork/core-geonetwork/issues/4276 for 3.8.x
After fix:
> Display position name if no individual name specified

- web-ui/src/main/resources/catalog/components/viewer/heatmap/HeatmapService.js
@fxprunayre @jahow 
toLonLat gave bad results when the map viewer is was of bounds.
Useing transformextent fixes this
> fix(heatmap) use transform extent to get topleft & bottomright

- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
- schemas/iso19139/src/main/plugin/iso19139/loc/fre/strings.xml
- web-ui/src/main/resources/catalog/style/gn_metadata.less
- web-ui/src/main/resources/catalog/views/default/less/gn_result_default.less
- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-variables.xsl
Will help solving https://github.com/geonetwork/core-geonetwork/issues/4263
From the admin configure the formatter to not display citation
It can also be customized using an xpath expression in the formatter itself. eg. if a DOI, then display it.
Add some improvement of the advanced mode - right column:
* add extent
* add keyword
to make it more similar to the default view.
> ISO19139 / Citation / Parameter to turn it off

- web-ui/src/main/resources/catalog/components/metadataactions/partials/metadatagroupupdater.html
Replace checkbox by radio as only one groupowner is allowed.
Add a filter if many groups eg. some catalogs can have 200+
> Editor / Group owner / Radio icon and filter if more than 10.

- schemas/iso19139/src/main/plugin/iso19139/update-fixed-info.xsl
If the main language locale contain a gmd:country the update-fixed-info.xsl is not including the gmd:country during the  gmd:locale creation for the main language so the gmd:country value is dropped/lost.
This fix copies the gmd:country code if it exists so that it is not lost.
> iso19139/Don't lose gmd:country for mainlanguage in gmd:locale

- schemas/iso19139/src/main/plugin/iso19139/update-fixed-info.xsl
If the following was used for the gmd:language
```
<gmd:LanguageCode codeList="http://www.loc.gov/standards/iso639-2/" codeListValue="eng">
eng  
</gmd:LanguageCode>
```
The text portion will be removed and it will be saved as 
```
<gmd:LanguageCode codeList="http://www.loc.gov/standards/iso639-2/" codeListValue="eng"/>
```
So the text portion is lost.
This pull request ensure that if a text() existed then it will update the value based on the code list value using getIsoLanguageLabel.
However if we want to create our own custom code list with values like "eng; USA" then a sample is provided
using the getCodelistTranslation function so that we can have something like the following
```
<gmd:LanguageCode codeList="http://www.loc.gov/standards/iso639-2/" codeListValue="eng">
eng; USA …
```
> iso19139/gmd:LanguageCode text() lost

- web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
- web-ui/src/main/resources/catalog/components/viewer/ViewerDirective.js
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/locales/en-admin.json
- web-ui/src/main/resources/catalog/locales/en-search.json
This PR adds a new behaviour, disabled by default, where the map viewer automatically zoom in when adding a layer from a record. The standard behaviour shows this message:
The added behaviour is the same as if the user was immediately clicking on the link in the message, and shows the following message:
This is controlled by the new UI setting `map/autoFitOnLayer`.
Note: I personally think this should be the default behaviour since most users don't even see this message, so if other people agree I can change it in the PR.
> Viewer / add setting to allow autofit on layer added from record

- schemas/config-editor.xsd
- schemas/dublin-core/src/main/plugin/dublin-core/layout/layout.xsl
- schemas/iso19110/src/main/plugin/iso19110/layout/layout.xsl
- schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
- schemas/iso19139/src/main/plugin/iso19139/layout/layout.xsl
- web/src/main/webapp/xslt/common/functions-metadata.xsl
For certain elements can be relevant to exclude them from flat mode exceptions, depending on the parent element. For example: don't apply flat mode to `gmd:contact` except if  it's defined in `gmd:MD_MaintenanceInformation`.
Currently if we define:
```
<flatModeExceptions>
...
<for name="gmd:contact"/>
...
</flatModeExceptions>
```
If `gmd:contact` is rendered in non-flat mode, and if not present in the metadata a button to add it is displayed in any element that can contain `gmd:contact` (`gmd:MD_Metadata` and `gmd:MD_MaintenanceInformation`)
With the change we can only apply this for `gmd:MD_Metadata`, excluding it from `gmd:MD_MaintenanceInformation`:
```
<flatModeExceptions>
...
<for name="gmd:contact" excludeFrom="gmd:MD_MaintenanceInformation"/>
...
</flatModeExceptions>
```
> Allow to exclude elements from flatModeExceptions

- web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html
- web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
- web-ui/src/main/resources/catalog/components/metadataactions/partials/relatedObserverTemplate.html
- web-ui/src/main/resources/catalog/components/viewer/wfs/partials/download.html
- web-ui/src/main/resources/catalog/components/viewer/wmts/partials/wmtsDownload.html
In the metadata view the different types of related records weren't always displayed in the same way.
This PR improves this where possible. Titles are now always shown first (as a `<h3>` for a11y), then the description (as a `<p>`). 
Some small changes are made:
- unknown types now have an icon
- warning message (WFS) displayed on the same line
- added margin for the loader icon
The way link details are shown depend on translation strings and are not covered in this PR.
**Screenshot after the changes:**
(titles in the screenshot are just for testing, the texts 'Unknown' and 'WFS' are just dummy names)
A small change was made to the online resource add/edit dialog: the layer grid is positioned like the rest of the elements
**Before:**
**After:**
> Uniform view for related records in the Metadata view

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/AbstractAligner.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/arcsde/ArcSDEHarvester.java
- harvesters/src/main/resources/config-spring-geonetwork.xml
Same as https://github.com/geonetwork/core-geonetwork/pull/4249 targeting `master`:
2 fixes behind this PR:
* First is adding a missing bean for db harvesting. It is a similar issue as the one described here: #4025 ; using a bean definition in one of the xml file was a quick fix to me because it was not convenient in the customer's environment to rebuild Java code, but there might be a better way:
* no need of a bean for the ArcSDEDatabaseFactory, maybe a class with a static method would be a better approach ?
* Shall we rescan for the other packages for missing Spring @components (see PR above) ?
* second fix is to avoid a NPE when harvesting, especially when trying to set rights on the currently harvested MD (passing params from the harvester to the aligner).
Tests: Applied and …
> Fixes arcsde harvesting master

- web-ui/src/main/resources/catalog/style/gn_admin.less
Before
After
Related to https://github.com/geonetwork/core-geonetwork/pull/4284/files#diff-5fda5d857b8f8c6936f10181fddeffa5L54-L60
> Admin / Record link / Remove unused CSS classes and fix layout when long URL in report

- web/src/main/webResources/WEB-INF/urlrewrite.xml
In debug mode some URL like `/geonetwork/catalog/templates/admin/metadata/metadata-and-template.html` are caught by rewrites.
> URL Rewrite / Be more strict on what webapp and portal name can be.

- web-ui/src/main/resources/catalog/components/common/ows/OWSService.js
Sometimes in a GetCapabilities response several Layer objects can be pointed to the same metadata record, such breaking right after the first metadata UUID and/or identifier match would mean we might be at the wrong Layer object.
This can be tested with the following record:
https://sextant.ifremer.fr/geonetwork/srv/api/records/f8ed7346-94ae-4a86-b38e-3b07f7e5bf6a/formatters/xml
Without this PR, the second WMS layer of this record ("Chenaux de la baie de Saint Brieuc") cannot be added to the map because the layer lookup always finds the first layer ("Habitats benthiques...").
The behaviour should not be changed other than that.
@fxprunayre apparently you're the last one to have modified this logic, please let me know if you think that fix is acceptable! thanks
> OWS Service / give higher priority to layer name than metadata/id when looking up layer

- web/src/main/java/org/fao/geonet/i18n/UrlLocaleChangeInterceptor.java
- web/src/main/webResources/WEB-INF/spring-servlet.xml
Fixes #4309. Fixes an `ArrayIndexOutOfBoundsException` that happened when
GeoNetwork is deployed with ROOT ("/") as context name.
It also fix a bug related to the wrong part of the URL being selected as
the locale used in the request.
> Fix an error when GN is deployed as ROOT context ("/")

- web/src/main/java/org/fao/geonet/i18n/UrlLocaleChangeInterceptor.java
- web/src/main/webResources/WEB-INF/spring-servlet.xml
Fixes #4309. Fixes an `ArrayIndexOutOfBoundsException` that happened when
GeoNetwork is deployed with ROOT ("/") as context name.
It also fix a bug related to the wrong part of the URL being selected as
the locale used in the request.
Backport of #4358.
> [BP] Fix an error when GN is deployed as ROOT context ("/")

- services/src/main/java/org/fao/geonet/api/links/LinksApi.java
- services/src/test/resources/services-web-test-context.xml
`RequestParamMethodArgumentResolver` cannot deserialize page request and should not take the place of the handler required to do it.
@fxprunayre please
> RequestParamMethodArgumentResolver cannot deserialize page request

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/oaipmh/Harvester.java
- schemas/dublin-core/src/main/plugin/dublin-core/process/dc-to-iso19139.xsl
If the OAI-PMH server provides only DC format, configuring the field **XSL transformation to apply** with the process **dc-to-iso19139**  allows to convert it to ISO19139 format.
> Add process in Dublin Core schema that can be used in OAI-PMH harvester to o convert from DC to ISO19139 if the remote server only provides DC format

- schemas/iso19139/src/main/plugin/iso19139/loc/ara/labels.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/chi/labels.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/dut/labels.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/eng/labels.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/por/labels.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/rus/labels.xml
- schemas/iso19139/src/main/plugin/iso19139/update-fixed-info.xsl
- web-ui/src/main/resources/catalog/components/viewer/geometry/GeometryService.js
- web-ui/src/main/resources/catalog/js/CatController.js
Also change default WGS (EPSG:4326) code to be urn:ogc:def:EPSG:6.6:4326 instead of EPSG:4326 as lat/lon ordering of coordinates is normally expected to be followed for this code
Requires https://github.com/geonetwork/core-geonetwork/pull/4318 for the srs not to be reset to EPSG:4326 when editing an existing polygon.
Fixes: https://github.com/geonetwork/core-geonetwork/issues/4255
> Use projection axis order when writing gml for bounding polygon's

- web-ui/src/main/resources/catalog/components/edit/bounding/BoundingDirective.js
This allows projections not of the form EPSG:[0-9]* to be used when creating bounding polygons.
The projection still needs to be supported by openlayers.
Refer https://github.com/geonetwork/core-geonetwork/issues/4255 for more information.
> Allow CRS:84 to be specified as projection on bounding polygon's

- web/src/main/webapp/xslt/ui-metadata/edit/edit.xsl
Also do not create an empty div if it is not required for the current view.
> Editor / Subtemplate / Do not display side panel

- web-ui/src/main/resources/catalog/components/viewer/gfi/FeaturesTable.js
Introduced in  https://github.com/geonetwork/core-geonetwork/commit/d7782b7a077adb75ddfe12874e71b35d1340718a#diff-d0e8238aaa0a7f356e58eaf682d8a082
Request was triggered but results not displayed.
Lang for bootstrap table is set by https://www.google.com/url?q=https://github.com/geonetwork/core-geonetwork/blob/af2a821cbdf31918928aedf0bf423a32cd849183/web-ui/src/main/resources/catalog/components/utility/UtilityService.js%23L491-L504&sa=D&source=hangouts&ust=1579336390603000&usg=AFQjCNF77cVBEDbtu0d_auy4I3AfVmYdXg
> Map / Fix GetFeatureInfo

- web-ui/src/main/resources/catalog/components/edit/datepicker/DatePickerDirective.js
Check details in #4260.
Tested with GMT+1 (Europe) and GMT-5 (Canada) and looks working fine.
> Date picker directive - use utc format to process the date. Fixes #4260

- web-ui/src/main/resources/catalog/js/admin/CSWTestController.js
```
lib.js?v=322d05a25e1afb2d5f2af1a6c9e480a7066e4bf7:126 SyntaxError: Unexpected token < in JSON at position 0
at JSON.parse (<anonymous>)
at tc (lib.js?v=322d05a25e1afb2d5f2af1a6c9e480a7066e4bf7:29)
at $b (lib.js?v=322d05a25e1afb2d5f2af1a6c9e480a7066e4bf7:101)
at lib.js?v=322d05a25e1afb2d5f2af1a6c9e480a7066e4bf7:101
at p (lib.js?v=322d05a25e1afb2d5f2af1a6c9e480a7066e4bf7:19)
at cd (lib.js?v=322d05a25e1afb2d5f2af1a6c9e480a7066e4bf7:101)
at c (lib.js?v=322d05a25e1afb2d5f2af1a6c9e480a7066e4bf7:103)
at lib.js?v=322d05a25e1afb2d5f2af1a6c9e480a7066e4bf7:139
at m.$eval (lib.js?v=322d05a25e1afb2d5f2af1a6c9e480a7066e4bf7:153)
at m.$digest (lib.js?v=322d05a25e1afb2d5f2af1a6c9e480a7066e4
```
Probably related to Spring MVC update ?
> CSW / Test interface does not load samples

- web-ui/src/main/resources/catalog/views/default/less/gn_results_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_search_default.less
When you change the catalog logo and choose a very wide one, the view in the search result list is broken. This PR adds a `max-width` to the logo so it's displayed properly.
**Before**
**After**
> Fix for too wide logo in result list

- web-ui/src/main/resources/catalog/style/gn_metadata_pdf.less
PDF has no header now. It use to have something like
Make it simple
> Formatter / PDF / Restore the header with logo

- core/src/main/java/org/fao/geonet/kernel/mef/MEF2Exporter.java
Introduced in https://github.com/geonetwork/core-geonetwork/pull/4248/files#r370629987
This was making ZIP export and harvesting unusable.
> MEF / Move back attachment folders in the record folder

- web-ui/src/main/resources/catalog/components/search/searchfiltertag/SearchFilterTagsDirective.js
- web-ui/src/main/resources/catalog/components/search/searchfiltertag/partials/searchFilterTagsTemplate.html
- web-ui/src/main/resources/catalog/locales/en-search.json
- web-ui/src/main/resources/catalog/style/gn.less
- web-ui/src/main/resources/catalog/style/gn_search.less
- web-ui/src/main/resources/catalog/templates/editor/batchedit.html
- web-ui/src/main/resources/catalog/templates/editor/editorboard.html
- web-ui/src/main/resources/catalog/views/default/less/gn_results_default.less
- web-ui/src/main/resources/catalog/views/default/templates/results.html
This PR is a follow-up of #4361.
The `SearchFilterTags` directive is reworked:
* simpler logic by removing the special cases for geometry and boolean filters which were not used (if I'm not mistaken)
* no more HTTP request to the thesaurus endpoint; the `dimension` object is used to read the keyword labels
* `privateVar` and `thesaurusKey` attributes are not used anymore
* support for nested keywords (e.g. GEMET)
* button for clearing all filters at once (same as resetting the search)
* filters are shown on the side above the facets panel, instead of above the search results
The active filters are not actually shown as "tags" anymore, but I kept the directive name to avoid breaking too many things in custom projects.
Also it still works in editor board and batch edit.
> Search / Improve the search active filters display

- web/src/main/webResources/WEB-INF/config-db/initial_data.xml
- web/src/main/webapp/WEB-INF/classes/setup/sql/data/custom-data-db-default.sql
Added empty file for custom sql data initialization, applied after the default data initialization files from GeoNetwork. 
This can be useful in custom projects to add custom sql instructions in that file for custom data or update for example the settings to customise values, without having to update the default data files, facilitating the upgrade of custom projects to new versions of GeoNetwork. 
For example, if a project has a custom view named `minimal`, instead of updating the `data-db-default.sql`, it can be configured in the file `custom-data-db-default.sql`
```
-- File to add custom project sql, it's loaded after the default data files
UPDATE Settings SET value = 'minimal' WHERE name = 'system/ui/defaultView';
```
> Add support for custom sql file for data initialization

- common/pom.xml
- common/src/main/java/org/fao/geonet/utils/Xml.java
- core/src/main/java/org/fao/geonet/util/XslUtil.java
- services/src/main/java/org/fao/geonet/api/processing/XslProcessUtils.java
To be used in XSLT. Eg. To build feature catalogue from ESRI Rest service - see https://github.com/metadata101/iso19115-3.2018/pull/24.
> Utility / Add download JSON from URL and return XML

- web-ui/src/main/resources/catalog/style/gn.less
- web-ui/src/main/resources/catalog/style/gn_fonts.less
- web-ui/src/main/resources/catalog/style/gn_search.less
This PR fixes the issue in: https://github.com/geonetwork/core-geonetwork/issues/4389
All version numbers of Font-awesome are `4.4.0` and the location is fixed (no more 302 errors)
> Fix #4389: Font-awesome location and update all version numbers

- web/src/main/webapp/xslt/services/rss/rss-utils.xsl
It should avoid bot requests to load plenty of stack traces in logs.
> avoid rss search to send link with two slashes

- core/src/main/java/org/fao/geonet/web/LocaleRedirects.java
- web/src/main/webapp/WEB-INF/config-security/config-security-mapping.xml
- web/src/main/webapp/xslt/skin/default/skin.xsl
With portals, more and more users are using it and play with it in URL.
This will redirect correctly to the portal requested instead of the
login form.
> Portal / Allow /srv/ to redirect to home.

- services/src/main/java/org/fao/geonet/api/GlobalExceptionController.java
For example, an anonimous user or with `RegisteredUser` profile trying to use metadata import API method, was returning http code 400 instead of 403 as expected.
See https://github.com/geonetwork/core-geonetwork/blob/97766465724233b20249204bdc0c44f0e2b8fee1/services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java#L524
> Handle AccessDeniedException to return http status code 403 instead of 400

- web-ui/src/main/resources/catalog/views/default/less/gn_layout_default.less
- web-ui/src/main/resources/catalog/views/default/less/gn_variables_default.less
In GeoNetwork it is possible to change the `background-image` via the settings. However, if you do not change it, it defaults to an empty string.
This empty string has a nasty side-effect, it is substituted with the name of it's stylesheet and this causes the stylesheet to be loaded twice
Read more: https://stackoverflow.com/questions/20727262/css-file-considered-as-being-an-image-resource
This PR fixes this with setting the default to `none` (variable_default.less) and if there's an empty string it's not put directly in the `background-image` property (http://lesscss.org/features/#css-guards-feature).
> Fix: Do not use an empty string as `background-image`

- pom.xml
Getting this kind of errors with maven today:
```
[WARNING] Error resolving sources artifact. Artifact id: org.geonetwork-opensource:csw-server:java-source:sources:3.8.2 (Message: Could not transfer artifact org.geonetwork-opensource:csw-server:jar:sources:3.8.2 from/to maven2 (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/org/geonetwork-opensource/csw-server/3.8.2/csw-server-3.8.2-sources.jar. Return code is: 501 , ReasonPhrase:HTTPS Required.
```
coherent with the following announcement: https://twitter.com/ASFMavenProject/status/1217495225905577984
Tests: maven OK
> pom - switch to https for repo.maven.apache.org

- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
Fix for https://github.com/geonetwork/core-geonetwork/issues/4005
This PR changes the use of the 'internal id' to into the 'file identifier'
> Fix for #4005: Use `File Identifier` in metadata tab of the full metadata view

- web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
Some records define lots of languages (eg. 60 langs) then each field make a call to the service.
Depending on the setup, this can cause issue with the DB pool 
```
java.sql.SQLException: Cannot get a connection, pool error Timeout waiting for idle object
```
Symptom: part of the editor is not initialized properly eg. no keywords. Firefox seems to be more affected than Chrome.
Only init the autocomplete when the user focus on the field.
Tested with https://sdi.eea.europa.eu/catalogue/srv/eng/xml.metadata.get?id=1069985
> Editor / Init language autocomplete only on focus

- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
- web-ui/src/main/resources/catalog/components/search/mdview/partials/contact.html
- web-ui/src/main/resources/catalog/style/gn_metadata.less
- web-ui/src/main/resources/catalog/views/default/less/gn_result_default.less
- web-ui/src/main/resources/catalog/views/default/templates/recordView.html
This PR adds some styling/UI changes to the full view of the metadata page. The purpose is to achieve a more balanced view: better alignment to the left, even spaces between list items and a more indented tree structure.
Changes:
- adding more (even) whitespace
- no padding for related title
- change related title colour
- clearer tree structure
- 1 address element (not 2 in 2 columns)
- added icons
- telephone number has now `tel:` in front of the number (makes it clickable)
**Before**:
**After**:
> Styling improvements to the full metadata view

- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/views/default/directives/directive.js
- web-ui/src/main/resources/catalog/views/default/directives/partials/mdactionmenu.html
This adds a configuration for 
It allows for example to easily :
* change the menu proposed for export formats
* add new formatters
* turn off export of related records in MEF (which is now the default as it was misleading to user to export one record and ending up with many in the ZIP)
* configure the XML to not be an attachment and to open directly in the browser which the preferred way for some users
RDF menu is not covered by this because it uses an old Jeeves service and some code for this was also duplicated in the schema for csw. A cleanup would be welcome to move DCAT conversion to a formatter.
> Record view / Add download menu configuration.

- domain/src/main/java/org/fao/geonet/domain/MetadataValidationId.java
- web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v3110/migrate-default.sql
Sometimes the name of the schematron files are longer than 40 characters. This commit allow file names up to 128 characters long instead of 40.
> Increase length of Validation.valType column

- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
- schemas/iso19139/src/main/plugin/iso19139/loc/cat/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/dut/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/eng/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/fin/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/fre/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/ger/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/ita/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/nor/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/pol/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/por/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/rus/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/slo/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/spa/strings.xml
- schemas/iso19139/src/main/plugin/iso19139/loc/tur/strings.xml
- services/src/main/java/org/fao/geonet/api/regions/metadata/MetadataRegionSearchRequest.java
- web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-functions.xsl
Fixes https://github.com/geonetwork/core-geonetwork/issues/4258 for 19139.
Use region.getmap service to display the spatial extent of a metadata record containing bounding polygons that can also be rendered to a pdf.
Also modified the region.getmap service to:
- handle non WGS84 bounding polygons
- to use a gml 3.2 parser for gml 3.2 bounding polygons
- return all selected bounding polygons as a multi polygon
> Display bounding polygons in 19139 full view

- services/src/main/java/org/fao/geonet/services/region/GetMap.java
Refer https://github.com/geonetwork/core-geonetwork/pull/4422#issuecomment-583372477
Draw each element of a GeometryCollection separately to fill correctly.
> Fix fill of multi-polygon in region.getmap

- web/src/main/webapp/xml/csw/record-to-csw-capabilities.xsl
If no language parameter provided in URL
Then 
```
Schema not valid: [org.xml.sax.SAXException: Fatal error: org.xml.sax.SAXParseException; lineNumber: 452; columnNumber: 36; cvc-enumeration-valid: Value '' is not facet-valid with respect to enumeration '[bul, cze, dan, dut, eng, est, fin, fre, ger, gre, hun, gle, ita, lav, lit, mlt, pol, por, rum, slo, slv, spa, swe]'. It must be a value from the enumeration. Response did not validate against schema 'http://www.opengis.net/cat/csw/2.0.2 http://schemas.opengis.net/csw/2.0.2/CSW-discovery.xsd http://inspire.ec.europa.eu/schemas/inspire_ds/1.0 http://inspire.ec.europa.eu/schemas/inspire_ds/1.0/inspire_ds.xsd'.]
```
Technical guidance
```
If an unsupported language was requested or if no specific language was
requested …
```
> INSPIRE / CSW / Validator trigger error if ResponseLanguage is empty

- schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
- schemas/iso19139/src/main/plugin/iso19139/layout/utility-tpl-multilingual.xsl
Some records may use multilingual Anchor. Add support for this.
Some multilingual record may have translations and no value defined for the main language. In such case, fallback to a non empty value if any.
> ISO19139 / Multilingual / Add Anchor and fallback to non empty value

- services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
- services/src/main/resources/config-spring-geonetwork.xml
In manage record, publish/unpublish operations currently act on Internet group privileges
In some installation, the list of operations may be different (eg. removing dynamic, add a new one) or it may be needed to add more privileges to Intranet group compared to the Internet one (eg. can download).
This adds a configuration of what publish action really do.
> Sharing / Add definition of publish.

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Harvester.java
Some server aren't compliant with CSW specification. In some cases they can  return a value
different of `0` for `nextRecord` when the harvester has reached the end of the available
results.
This commit stops the harvesting loop if the value of `nextResult` returned by the server
is smaller than the current `start` record.
Could be a complement to #3713.
> Stop infinite CSW harvester loop if start > nextRecord

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Harvester.java
Some server aren't compliant with CSW specification. In some cases they can  return a value
different of 0 for nextRecord when the harvester has reached the end of the available
results.
This commit stops the harvesting loop if the value of `nextResult` returned by the server
is smaller than the current `start` record.
Backport of #4443.
> [BP] Stop infinite harvester loop if start > nextRecord

- schemas/iso19139/src/main/plugin/iso19139/index-fields/default.xsl
INSPIRE Technical Guidelines 2.0.1 require to use `gmx:Anchor` for `gmd:otherContraints`, updated the indexing to index these elements properly so are displayed in the metadata detail page:
> Index gmd:otherConstraints with gmx:Anchor

- schemas/csw-record/src/main/plugin/csw-record/convert/oai_dc.xsl
- schemas/iso19110/src/main/plugin/iso19110/convert/oai_dc.xsl
- schemas/iso19139/src/main/plugin/iso19139/convert/oai_dc.xsl
Remove unused namespaces like `gmc`, `gco`... from output of `oai_dc` transformations.
> Remove unused namespaces from OAI records

- services/src/main/java/org/fao/geonet/api/site/LoggingApi.java
The value was set to the log file size, but the service returns a zip file with different size, causing download issues in some cases.
> Remove invalid content length header in log file download. 

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java
- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/oaipmh/Harvester.java
- web-ui/src/main/resources/catalog/components/admin/harvester/partials/extras.html
Add options to skip, override or generate a random UUID in case of UUID collisions with records
already present in the catalog.
Fix a bug in CSW harvester when random UUID option was selected: the UUID inside the XML document wasn't updated with the new random UUID although in the DB and the index was.
> Add override and random UUID options to OAI-PMH harvester

- core/src/main/java/org/fao/geonet/MetadataResourceDatabaseMigration.java
Some extra characters can be used in thumbnail filename "_=()%:".
Even it the migration task is quite old it may still be used in some places.
Tested on Ifremer 20k records.
> DB migration / resources.get converted to attachments API

- web/src/main/webapp/WEB-INF/classes/log4j-dev.xml
- web/src/main/webapp/WEB-INF/classes/log4j-index.xml
- web/src/main/webapp/WEB-INF/classes/log4j-search.xml
- web/src/main/webapp/WEB-INF/classes/log4j.xml
Added support for a system property `log_dir`to customise the to customise the parent directory of the log folder:
- `-Dlog_dir=/var/tomcat/` (path should end with /) -> the log file is created in `/var/tomcat/logs/geonetwork.log`.
- if not defined, a relative path is used.
>  Use system property to customise the parent directory of the log folder

- services/src/main/java/org/fao/geonet/api/records/editing/MetadataEditingApi.java
Currently every time editors change tab a copy is preserved. Only record history when editing session is closed.
Related to https://github.com/geonetwork/core-geonetwork/pull/3209
> Editing / History / Only save changes at the end of the editing session

- csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/SearchController.java
Update of https://github.com/geonetwork/core-geonetwork/pull/1871 for master.
* Adding post process to `srv/eng/csw` by creating for each output schema a file eg. for gmd, `gmd-csw-postprocessing.xsl`
* Adding post process to a virtual CSW service `srv/eng/csw-inspire` by creating for each output schema a file eg. for gmd, `gmd-csw-inspirepostprocessing.xsl`
* Adding post process to a portal `inspire/eng/csw` by creating for each output schema a file eg. for gmd, `gmd-inspire-postprocessing.xsl`
> Add post processing xslt for CSW results

- web-ui/src/main/resources/catalog/components/viewer/localisation/LocalisationService.js
currently, if you enter e.g. a gb postcode such as SE1 2AA into the map geocoder, it presumes the digits are coordinates, and pans to them (around equatorial guinea in this case); so, only convert and pan to numbers if input starts with numbers ([via gitter](https://gitter.im/geonetwork/core-geonetwork?at=5e3c3687ea9ba00b84b65d31))
_note_ location names can be odd, so it's quite conceivable someone might start entering two numbers for reasons other than entering a coordinate pair, they may get a little surprise when the map pans there (i know i did) although it's obviously really handy being able to quickly get to a lng lat pair.
> in map geocoder, only pan to presumed coordinates if they start the input
