geonetwork/core-geonetwork

core/src/main/java/org/fao/geonet/kernel/security/ldap/AbstractLDAPUserDetailsContextMapper.java, core/src/main/java/org/fao/geonet/kernel/security/ldap/LDAPUserDetailsContextMapperWithProfileSearch.java, core/src/main/java/org/fao/geonet/kernel/security/ldap/LDAPUtils.java, web/src/main/webapp/WEB-INF/config-security/config-security.properties
to support custom indexes on profile pattern
=> Extending LDAPUserDetailsContextMapperWithProfileSearch

web-ui/src/main/resources/catalog/style/gn_search_default.less, web-ui/src/main/resources/catalog/templates/search/default/home.html, web-ui/src/main/resources/catalog/templates/search/default/search.html, web-ui/src/main/resources/catalog/templates/top-toolbar.html, web/src/main/webapp/xslt/ui-search/search.xsl
on Web-UI default search: the bottom-bar should be on the bottom
(but scroll when page content is larger)
the menu should collapse nicely on mobile devices
=> default search: the bottom-bar should be on the bottom

web-ui/src/main/resources/catalog/style/gn_editor.less, web-ui/src/main/resources/catalog/style/gn_search.less, web-ui/src/main/resources/catalog/style/gn_search_default.less, web-ui/src/main/resources/catalog/views/default/templates/recordView.html
Several styling changes mostly for default search
=> Ux improvements

domain/src/main/java/org/fao/geonet/domain/InspireAtomFeed.java
=> Fix initialisation of Oracle DB (InspireAtomFeed)

docs/eng/developer/source/xml_services/group_xml_services.rst, docs/eng/developer/source/xml_services/metadata_xml_insert_update_delete.rst
The xml.metadata.update service requires the id, not the uuid
=> xml.metadata.update only works with id, not uuid

web/src/main/java/org/fao/geonet/Geonetwork.java, web/src/main/java/org/fao/geonet/constants/Geonet.java, web/src/main/java/org/fao/geonet/services/metadata/DefaultStatusActions.java, web/src/main/webapp/WEB-INF/config.xml
Allow to modify the property html5ui in DefaultStatusActions using the configuration file.
=> Handle html5/legacyUI links in StatusActions. Closes #841.

code_quality/findbugs-excludes.xml, common/src/main/java/org/fao/geonet/ZipUtil.java
This PR is not ready but when it is it will make travis build (or get closer :-P)
=> Fixes for travis

schemas/iso19139/src/main/plugin/iso19139/process/onlinesrc-add.xsl, schemas/iso19139/src/main/plugin/iso19139/process/onlinesrc-remove.xsl, web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js, web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html, web-ui/src/main/resources/catalog/style/gn_editor.less
This PR updates the add online resource wizzard modal to propose multilingual fields for
- name
- description
if the metadata is multilingual, in all langages provided by the metadata.
It also fixes the oneline resource removal via batch process
=> Onlinesrc multilingual

core/src/main/java/org/fao/geonet/kernel/search/keyword/KeywordSearchParamsBuilder.java, services/src/main/java/org/fao/geonet/guiservices/metadata/GetRelated.java, services/src/main/java/org/fao/geonet/services/metadata/format/Format.java, services/src/main/java/org/fao/geonet/services/thesaurus/GetKeywords.java, web/src/main/webapp/WEB-INF/config/config-service-thesaurus.xml, web/src/main/webapp/WEB-INF/config/config-service-xml-api.xml
Migrated to Spring MVC and added not modified checking for performance. Lastmodified is calculated based on the thesaurus with the most recent last modified date.
=> GetKeywords service migrated to Spring MVC

schemas-test/src/test/java/cswrecord/FullViewFormatterTest.java, schemas-test/src/test/java/cswrecord/XmlViewFormatterTest.java, schemas-test/src/test/java/dublincore/FullViewFormatterTest.java, schemas-test/src/test/java/dublincore/XmlViewFormatterTest.java, schemas-test/src/test/java/iso19139/AbstractFullViewFormatterTest.java, schemas-test/src/test/java/iso19139/XmlViewFormatterTest.java, services/src/main/java/org/fao/geonet/services/metadata/format/AbstractFormatService.java, services/src/main/java/org/fao/geonet/services/metadata/format/Format.java, services/src/main/java/org/fao/geonet/services/metadata/format/ListFormatters.java, services/src/test/java/org/fao/geonet/services/metadata/format/AbstractFormatterTest.java, services/src/test/java/org/fao/geonet/services/metadata/format/FormatIntegrationTest.java, services/src/test/java/org/fao/geonet/services/metadata/format/XmlViewFormatterTest.java, web/src/main/java/org/fao/geonet/Geonetwork.java
PR for https://github.com/geonetwork/core-geonetwork/issues/997
=> Formatter / Id or uuid parameter ? #997.

common/src/main/java/org/fao/geonet/utils/GeonetHttpRequestFactory.java, common/src/test/java/org/fao/geonet/utils/GeonetHttpRequestFactoryTest.java, core/src/test/java/org/fao/geonet/kernel/ThesaurusTest.java
This is probably a refactor issue. A lot of tests broke because no proper value was added to the ThesaurusTest helper class for the siteUrl.
=> Added siteUrl

core/src/main/java/jeeves/monitor/healthcheck/FreeFileHandlesHealthCheck.java
A function is called without a side effect but it's result is not used in the function. Added a return.
=> Added return value of unhealthy code path.

pom.xml
Updgraded the yuicompressor, this is drop-in compatible.
=> Upgraded yuicompressor

core/src/test/java/org/fao/geonet/kernel/mef/MEFExporterIntegrationTest.java, core/src/test/java/org/fao/geonet/kernel/search/LuceneSearcherPresentTest.java
And added @Ignore instead of putting it in the pom.xml
=> Excluded Core Test Changed on 3.0.x branch instead of develop

core/src/main/java/org/fao/geonet/kernel/SchematronValidator.java
=> Removed dead Store Manager on 3.0.x branch

core/src/main/java/org/fao/geonet/kernel/XmlSerializerSvn.java
=> Removed Redundant Null Check on 3.0.x

core/src/main/java/org/fao/geonet/resources/ResourceFilter.java
This is a bug found by findbugs, inconsistent sync.
=> Extracted faviconMap.put in a synchronized method.

cachingxslt/pom.xml, cachingxslt/src/main/java/de/fzi/dbs/xml/transform/CachingTransformerFactory.java, common/pom.xml, common/src/main/java/org/fao/geonet/utils/CachedTransformer.java, common/src/main/java/org/fao/geonet/utils/Xml.java
Refactored Invoke with try catch to strategy pattern.
=> Removed invoke with try catch, replaced with strategy pattern.

.travis.yml, code_quality/findbugs-excludes.xml, schemas-test/src/test/java/iso19139/FullViewFormatterServiceTest.java, schemas-test/src/test/java/iso19139/FullViewFormatterTest.java, services/src/main/java/org/fao/geonet/services/metadata/format/groovy/util/LinkType.java, wro4j/src/main/java/org/fao/geonet/wro4j/ClosureDependencyUriLocator.java, wro4j/src/main/java/org/fao/geonet/wro4j/GeonetWroModelFactory.java
Excluded some test to get the Travis build running.
=> Excluded tests

core/src/main/java/org/fao/geonet/kernel/search/LuceneConfig.java
Needless boxing and unboxing of parameter.
=> Replaced valueOf with parseXXX to save 8 bytes of memory.

core/src/main/java/org/fao/geonet/kernel/oaipmh/ResumptionTokenCache.java
Use iteration over items to save cpu cycles.
=> Refactored itteration over keys to itteration over items.

pom.xml
Updated surefire-plugin to solve NPE problems.
=> Updated surefire-plugin

core/src/main/java/org/fao/geonet/kernel/security/ldap/LDAPSynchronizerJob.java, core/src/main/java/org/fao/geonet/kernel/security/ldap/LDAPUserDetailsContextMapperWithProfileSearch.java, domain/src/main/java/org/fao/geonet/domain/LDAPUser.java, web-ui/src/main/resources/catalog/js/CatController.js, web-ui/src/main/resources/catalog/templates/admin/settings/logo.html
Here are some several fixes I had to apply onto my georchestra branche (for gn3 integration ; https://github.com/pmauduit/core-geonetwork/tree/georchestra-gn3-3.0.x ) to be able to integrate GN3 basically into geOrchestra.
Tests: obviously tested onto geOrchestra at runtime :-). For the testsuite, tests seem broken on 3.0.x anyway, so I could not go any further.
=> Georchestra gn3 integration fixes

core/src/main/java/org/fao/geonet/kernel/security/ldap/LDAPSynchronizerJob.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/HarvestManager.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/HarvestManagerImpl.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/HarversterJobListener.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/HarvesterJob.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java, services/src/main/java/org/fao/geonet/guiservices/sampledata/Add.java, services/src/main/java/org/fao/geonet/guiservices/templates/AddDefault.java
Due to missing ApplicationContext in harvester thread.
=> Multinode harvester / DataManager get mixed

core/src/main/java/org/fao/geonet/notifier/MetadataNotifierClient.java
Fix #1174. Close the input stream used in the connection to the notifier
URL.
=> Release resources in the web notifications mechanism

web-ui/src/main/resources/catalog/components/search/formfields/FormFieldsDirective.js, web-ui/src/main/resources/catalog/components/viewer/wps/WpsDirective.js, web-ui/src/main/resources/catalog/components/viewer/wps/WpsService.js, web-ui/src/main/resources/catalog/components/viewer/wps/partials/processform.html
Add ResponseDocument, lineage, storeExecuteResponse, status parameters.
Parse defaults as KVP params.
=> Improve WPS client

core/src/test/java/org/fao/geonet/kernel/search/HierarchicalFacetsIntegrationTest.java, pom.xml, services/src/main/java/org/fao/geonet/services/region/ListRegionsResponse.java, services/src/test/java/org/fao/geonet/services/region/ListRegionsTest.java, web-ui/src/main/resources/catalog/style/ellipsis.less, web/pom.xml
=> #1176 Enable tests

web/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java, web/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/GeonetHarvester.java
This pull request fixes the issue #1212
=> #1212 Clean sources when geonetwork harvester is deleted.

core/src/main/java/org/fao/geonet/kernel/DataManager.java, domain/src/main/java/org/fao/geonet/domain/Group.java, services/src/main/java/org/fao/geonet/services/group/Update.java, web-ui/src/main/resources/catalog/js/admin/UserGroupController.js, web-ui/src/main/resources/catalog/locales/en-admin.json, web-ui/src/main/resources/catalog/templates/admin/usergroup/groups.html
If defined, all metadata created on that group will be assigned the default category.
If not defined, works as before.
=> Adding default category to group.

.gitmodules, web-ui/src/main/resources/WEB-INF/classes/web-ui-wro-sources.xml, web/src/main/webapp/xslt/base-layout-cssjs-loader.xsl
https://github.com/wenzhixin/bootstrap-table
I needed it for a custom project and we thought it may be useful for GeoNetwork, even if right now no table is using it.
What do you think?
=> Adding bootstrap-table to basic UI 

web-ui/src/main/resources/catalog/components/viewer/terrainswitcher/partials/terrainswitcher.html
Fix a typo in the data-ng-show directive in terrainswitcher.html template.
=> Fix data-ng-showa typo

csw-server/src/main/java/org/fao/geonet/services/main/CswPublicationDispatcher.java
Used the CatalogDispatcher.extractParams() like in CswDiscoveryDispatcher.
=> Make 'request' KVP param case insensitive - fix #1199

docs/eng/users/source/admin/authentication/index.rst, docs/fra/users/source/admin/authentication/index.rst, web/src/main/webapp/WEB-INF/config-security/config-security-overrides.properties
name should be mapped to givenName, and surname to sn.
=> Fix ldap attributes mapping (1293)

web-ui/src/main/resources/catalog/style/gn_badge_categories.less, web-ui/src/main/resources/catalog/style/gn_infolist.less, web-ui/src/main/resources/catalog/style/gn_search.less, web-ui/src/main/resources/catalog/views/default/directives/partials/infolist.html, web-ui/src/main/resources/catalog/views/default/templates/home.html
=> New proposition of homepage

core/src/main/java/org/fao/geonet/kernel/security/ldap/LDAPSynchronizerJob.java
Fix proposal for:
https://github.com/geonetwork/core-geonetwork/issues/1288
Ensures the search contexts are closed in order to avoid socket handle consumptions.
=> LDAP sync job - closing search contexts

domain/src/main/java/org/fao/geonet/domain/MapServer.java, services/src/main/java/org/fao/geonet/services/publisher/Do.java, services/src/main/java/org/fao/geonet/services/publisher/GeoFile.java, services/src/main/java/org/fao/geonet/services/publisher/GeoServerRest.java, web-ui/src/main/resources/catalog/js/admin/MapServerController.js, web-ui/src/main/resources/catalog/locales/en-admin.json, web-ui/src/main/resources/catalog/locales/fr-admin.json, web-ui/src/main/resources/catalog/templates/admin/settings/mapservers.html, web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v303/migrate-default.sql
Same thing as  #1304 but against 3.0.x.
=> Publish the style in the same workspace used for the datastore & layer

web/src/main/java/org/fao/geonet/util/GmlWktConverter.java, web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/present/metadata-geo.xsl, web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/update-fixed-info.xsl, web/src/test/java/org/fao/geonet/util/GmlWktConverterTest.java
Use CRS:84 for lon/lat ordered coords created by drawing tool.
Convert from srs specified in the metadata to WKT for display of existing polygon.
=> Fixes #1371.

core/src/main/java/org/fao/geonet/kernel/EditLib.java, core/src/test/java/org/fao/geonet/kernel/EditLibIntegrationTest.java
* Add support for create if not exist
* Add support for update/delete all matching nodes (and not only the first one)
=> XPath API update improvements

schemas/iso19139/src/main/plugin/iso19139/index-fields/default.xsl, schemas/iso19139/src/main/plugin/iso19139/index-fields/index-subtemplate-fields.xsl, schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml, web-ui/src/main/resources/catalog/components/common/popup/PopupService.js, web-ui/src/main/resources/catalog/components/edit/directoryentryselector/DirectoryEntrySelector.js, web-ui/src/main/resources/catalog/components/edit/directoryentryselector/partials/directoryentrylistselector.html, web-ui/src/main/resources/catalog/components/edit/directoryentryselector/partials/directoryentryselector.html, web-ui/src/main/resources/catalog/locales/en-core.json, web-ui/src/main/resources/catalog/locales/en-editor.json, web-ui/src/main/resources/catalog/style/gn.less, web-ui/src/main/resources/catalog/style/gn_editor.less, web/src/main/webapp/WEB-INF/config-spring-geonetwork.xml, web/src/main/webapp/WEB-INF/config-summary.xml
See https://github.com/geonetwork/core-geonetwork/issues/1450
=> Editor / Contact list from directory could be long #1450.

schemas/dublin-core/src/main/plugin/dublin-core/schema-ident.xml, schemas/iso19110/src/main/plugin/iso19110/schema-ident.xml, schemas/iso19139/src/main/plugin/iso19139/schema-ident.xml, web/src/main/webapp/xml/validation/schemaPlugins/schema-ident.xsd, web/src/main/webapp/xml/validation/schemaPlugins/xml.xsd
Add the possibility to define title, standardUrl and description in different languages.
Those informations will be used to generate standard plugin documentation which will be part of a future PR (draft demo here http://files.titellus.net/tmp/en/standards/iso19115-3.html).
=> Schema documentation

web-ui/src/main/resources/catalog/components/ng-skos/templates/skos-concept.html, web-ui/src/main/resources/catalog/locales/en-editor.json, web-ui/src/main/resources/catalog/style/gn_editor.less
Modify the template in order to improve the navigation between the concepts of a hierarchical thesaurus.
Old version:
=> Modify template of the hierarchical thesaurus

web-ui/src/main/resources/catalog/components/admin/harvester/partials/privileges.html, web-ui/src/main/resources/catalog/components/search/formfields/partials/groupsCombo.html, web-ui/src/main/resources/catalog/components/utility/UtilityModule.js, web-ui/src/main/resources/catalog/templates/admin/report/report-internal-metadata.html, web-ui/src/main/resources/catalog/templates/admin/report/report-updated-metadata.html, web-ui/src/main/resources/catalog/templates/admin/report/report-users.html, web-ui/src/main/resources/catalog/templates/admin/settings/csw-virtual.html, web-ui/src/main/resources/catalog/templates/admin/tools/batch.html, web-ui/src/main/resources/catalog/templates/admin/tools/transferownership.html, web-ui/src/main/resources/catalog/templates/admin/usergroup/groups.html, web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html
the introduced empty filter verifies if empty array is returned in json and replaces by an alternative (or empty string)
resolves issue #1507
=> #1507 add an "empty" filter 

schemas/iso19139/src/main/plugin/iso19139/loc/cat/codelists.xml, schemas/iso19139/src/main/plugin/iso19139/loc/cat/criteria-type.xml, schemas/iso19139/src/main/plugin/iso19139/loc/cat/labels.xml, schemas/iso19139/src/main/plugin/iso19139/loc/cat/strings.xml, schemas/iso19139/src/main/plugin/iso19139/loc/spa/codelists.xml, schemas/iso19139/src/main/plugin/iso19139/loc/spa/criteria-type.xml, schemas/iso19139/src/main/plugin/iso19139/loc/spa/labels.xml, schemas/iso19139/src/main/plugin/iso19139/loc/spa/strings.xml
Managed to merge the XML transifex translations back to their original files using some custom ugly scripts & some manual editing.
Sadly, the plugin on https://github.com/geonetwork/core-geonetwork/pull/1057 didn't work for me.
=> Further Spanish and Catalan translations, for iso19139 XML files

web-ui/src/main/resources/catalog/components/common/map/mapService.js, web-ui/src/main/resources/catalog/components/common/ows/OWSService.js, web-ui/src/main/resources/catalog/components/search/mdview/mdviewModule.js, web-ui/src/main/resources/catalog/components/utility/CORSInterceptor.js, web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextService.js, web-ui/src/main/resources/catalog/components/viewer/wfs/WfsService.js, web-ui/src/main/resources/catalog/components/viewer/wps/WpsService.js, web-ui/src/main/resources/catalog/js/CatController.js, web-ui/src/main/resources/catalog/views/default/module.js
If an AJAX call to a URL fails and it is not a recognizable fail (status is -1) so it looks like the request has not even been made, just try with the proxy again.
=> CORS support

web-ui/src/main/resources/catalog/views/default/less/gn_search_default.less, web-ui/src/main/resources/catalog/views/default/module.js, web-ui/src/main/resources/catalog/views/default/templates/results.html
Improve the design of the toggle function of the minimap (search results).
Old version
=> Add button to the toggle function of the minimap

web-ui/src/main/resources/catalog/components/search/facets/FacetDimensionDirective.js, web-ui/src/main/resources/catalog/components/search/facets/partials/dimension-facet-list.html, web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js, web-ui/src/main/resources/catalog/style/gn_editor.less, web-ui/src/main/resources/catalog/views/default/less/gn_search_default.less
=> Add button to the toggle function for facets

web-ui/src/main/resources/catalog/js/CatController.js
=> Translation / Add Finnish to language list

web-ui/src/main/resources/catalog/components/search/searchmanager/SearchManagerService.js
=> fixed unselect checkbox issue

schemas/iso19110/src/main/plugin/iso19110/loc/dut/strings.xml, schemas/iso19139/src/main/plugin/iso19139/loc/dut/strings.xml, web-ui/src/main/resources/catalog/style/inspire/iti-i18n.css, web-ui/src/main/resources/catalog/style/inspire/iti.css
I added some Dutch translations. Not really happy with the iti.css file, but I didn't have the time to refactor this.
=> Some Dutch translations

schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields-keywords.xsl, schemas/iso19139/src/main/plugin/iso19139/loc/cat/labels.xml
... when no thesaurus title available
=> Show a default label for descriptiveKeywords

schemas/iso19139/src/main/plugin/iso19139/loc/cat/labels.xml
=> Minor translation fix (v2)

schemas/iso19139/src/main/plugin/iso19139/loc/fin/labels.xml
Old labels.xml doesn't work in 3.2.0. This file has been harmonised with the English labels.xml
=> Update Finnish labels.xml

core/src/main/java/org/fao/geonet/util/XslUtil.java, schemas/iso19139/src/main/plugin/iso19139/process/linked-data-checker.xsl
Use the GeonetHttpRequestFactory to create the request for validating the status of a URL.
The request factory will set the proxy with the parameters from GN settings.
Also try to follow the redirects until 5 redirections before returning an ERR_TOO_MANY_REDIRECTS response.
Based on the code from geoadmin
https://github.com/geoadmin/geocat/blob/6d3697de7b1735239017b95c2c5cc60ae24920cf/core/src/main/java/org/fao/geonet/util/GeocatXslUtil.java#L767-L793
=> Use the GeoNetwork HTTP request factory to check the URL in XSLUtil.getUrlStatus method

schemas/iso19139/src/main/plugin/iso19139/loc/cat/codelists.xml, schemas/iso19139/src/main/plugin/iso19139/loc/cat/criteria-type.xml, schemas/iso19139/src/main/plugin/iso19139/loc/cat/labels.xml, schemas/iso19139/src/main/plugin/iso19139/loc/cat/schematron-rules-geonetwork.xml, schemas/iso19139/src/main/plugin/iso19139/loc/cat/schematron-rules-inspire-strict.xml, schemas/iso19139/src/main/plugin/iso19139/loc/cat/schematron-rules-inspire.xml, schemas/iso19139/src/main/plugin/iso19139/loc/cat/schematron-rules-iso.xml, schemas/iso19139/src/main/plugin/iso19139/loc/cat/strings.xml, schemas/iso19139/src/main/plugin/iso19139/loc/spa/codelists.xml, schemas/iso19139/src/main/plugin/iso19139/loc/spa/criteria-type.xml, schemas/iso19139/src/main/plugin/iso19139/loc/spa/labels.xml, schemas/iso19139/src/main/plugin/iso19139/loc/spa/schematron-rules-geonetwork.xml, schemas/iso19139/src/main/plugin/iso19139/loc/spa/schematron-rules-inspire-strict.xml, schemas/iso19139/src/main/plugin/iso19139/loc/spa/schematron-rules-inspire.xml, schemas/iso19139/src/main/plugin/iso19139/loc/spa/schematron-rules-iso.xml, schemas/iso19139/src/main/plugin/iso19139/loc/spa/strings.xml
Ported `loc/spa` and `loc/cat` resources from 3.0.x to 3.2.x. Closes #1842
=> iso19139 spanish & catalan translations for GN 3.2.x

harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractParams.java, web-ui/src/main/resources/catalog/components/search/formfields/partials/usersCombo.html
* Save the owneruser in harvester settings when the harvester is created
* Select the right owner user in the select box in harvester settings panel.
=> Fix harvester owner user not saved on creation

web-ui/src/main/resources/catalog/components/metadataactions/partials/metadatacategoryupdater.html, web-ui/src/main/resources/catalog/components/metadataactions/partials/metadatagroupupdater.html, web-ui/src/main/resources/catalog/style/gn.less
@josegar74 please review if this PR is compatible with what you commented (can't guess which undesired effects could cause in the use case you mentioned).
=> Enable category edition - closes #1840

web/src/main/webapp/WEB-INF/config-db/postgis-shared-datasource.xml
No functional changes, just adding a proposition of configuration in the XML files.
=> JNDI spatial indexes in postgis - adding some doc in the XML

web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js, web-ui/src/main/resources/catalog/components/utility/UtilityModule.js
It fixes the metadata detail page to display the dublin Core description, when there are two dc:description elements.
=> It fixes the metadata detail page to display multiple description

schemas/dublin-core/src/main/plugin/dublin-core/index-fields/default.xsl
Now index BBOX in Dublin Core accept the formats:
4.817,-179.95 / 88.225,180 (min, max Latitude / min, max Longitude)
and
Latitude 4.817 to 88.225; Longitude -179.950 to 180.000
=> FIX 9766 - Now index BBOX in Dublin Core accept the formats:

schemas/iso19139/src/main/plugin/iso19139/extract-relations.xsl, schemas/iso19139/src/main/plugin/iso19139/process/onlinesrc-add.xsl, schemas/iso19139/src/main/plugin/iso19139/process/thumbnail-add.xsl, services/src/main/java/org/fao/geonet/api/records/model/related/ObjectFactory.java, services/src/main/java/org/fao/geonet/api/records/model/related/RelatedItem.java, services/src/main/java/org/fao/geonet/api/records/model/related/relatedResponse.xsd, web-ui/src/main/resources/catalog/components/catalog/CatalogService.js, web-ui/src/main/resources/catalog/components/edit/multilingualfield/MultilingualFieldDirective.js, web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js, web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcService.js, web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html, web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/onlinesrcList.html, web-ui/src/main/resources/catalog/components/metadataactions/RelatedResourcesService.js, web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
Some schema (like GM03 in Switzerland and ISO19115-3) allows multilingual URLs. Currently we are only supporting simple URL. This PR, made by Florent & me for geocat.ch improve that point.
=> Associated resources / Support multilingual URL

schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml, web-ui/src/main/resources/catalog/components/edit/directoryentryselector/DirectoryEntrySelector.js, web-ui/src/main/resources/catalog/components/edit/directoryentryselector/partials/directoryentrylistselector.html, web-ui/src/main/resources/catalog/components/edit/directoryentryselector/partials/directoryentryselector.html, web-ui/src/main/resources/catalog/components/metadatamanager/EditorService.js, web-ui/src/main/resources/catalog/components/search/searchmanager/partials/searchresults.html, web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js, web-ui/src/main/resources/catalog/components/utility/popover.js, web-ui/src/main/resources/catalog/js/CatController.js, web-ui/src/main/resources/catalog/style/gn.less, web-ui/src/main/resources/catalog/style/gn_bootstrap.less, web-ui/src/main/resources/catalog/style/gn_editor.less, web-ui/src/main/resources/catalog/style/gn_metadata.less, web-ui/src/main/resources/catalog/style/gn_search.less, web-ui/src/main/resources/catalog/style/gn_viewer.less
- Improve integration of directory pickup from editor.
- Add a new directive from ngeo popover (next could remove all gn-popover directives)
- Upgrade bootstrap to 3.3.7 to support the popover
**Directory entry modal**
- Fix facet alignement if small screen
- Add intermediate action to choose role then add the contact
- Search input centering
- Improve result style
**Directory entry list**
- Fix btn overlaying text
- Btn is now popover, no issue cause inside a dropdown
- smaller height thanks to previous fix
- Fix 30px top offset from the dropdown to the input ..
- Improve layout, color size ...
- Fix dropdown display on input focus
=> Improve Directory selector integration in the editor

schemas/iso19139/src/main/plugin/iso19139/index-fields/default.xsl
Index xlinks in the metadatas to be able to retreive all the metadatas that use an xlink.
=> Index xlinks

core/pom.xml, core/src/main/java/jeeves/xlink/Processor.java, core/src/main/java/org/fao/geonet/kernel/SpringLocalServiceInvoker.java, core/src/main/resources/config-spring-geonetwork.xml, services/src/test/java/org/fao/geonet/api/records/MetadataApiTest.java
invoke method service using spring mechanisms
=> Support local protocol on api registries

core/src/main/java/org/fao/geonet/kernel/DataManager.java, web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js, web-ui/src/main/resources/catalog/js/CatController.js, web-ui/src/main/resources/catalog/js/edit/BatchEditController.js, web-ui/src/main/resources/catalog/js/edit/EditorBoardController.js, web-ui/src/main/resources/catalog/js/search/SearchController.js, web-ui/src/main/resources/catalog/locales/en-search.json, web-ui/src/main/resources/catalog/templates/editor/batchedit.html, web-ui/src/main/resources/catalog/templates/editor/editorboard.html, web-ui/src/main/resources/catalog/views/default/module.js, web-ui/src/main/resources/catalog/views/default/templates/home.html, web-ui/src/main/resources/catalog/views/default/templates/searchForm.html
Reverts geonetwork/core-geonetwork#2062
=> Revert "Don't show RETIRED metadata in the search results by default"

web-ui/src/main/resources/catalog/components/common/map/mapService.js, web-ui/src/main/resources/catalog/views/default/module.js, web-ui/src/main/resources/catalog/views/default/templates/searchForm.html
Adding a WMTS layer works almost the same as WMS ones.
In the future, a refactoring/simplification of the code that handles adding layers would be preferable IMHO. This PR is a simple fix that does not go beyond that.
Also contains an unrelated fix on the full text search: previously, the model would wait 300ms before updating which means that sometimes search results were not consistent with the text entered.
=> Simple fix to allow adding WMTS layers to the viewer map

web-ui/src/main/resources/catalog/components/viewer/ViewerModule.js, web-ui/src/main/resources/catalog/components/viewer/ViewerService.js, web-ui/src/main/resources/catalog/components/viewer/geometry/GeometryDirective.js, web-ui/src/main/resources/catalog/components/viewer/geometry/GeometryService.js, web-ui/src/main/resources/catalog/components/viewer/geometry/partials/geometrytool.html, web-ui/src/main/resources/catalog/components/viewer/partials/mainviewer.html, web-ui/src/main/resources/catalog/components/viewer/profile/ProfileDirective.js, web-ui/src/main/resources/catalog/components/viewer/profile/ProfileModule.js, web-ui/src/main/resources/catalog/components/viewer/profile/ProfileService.js, web-ui/src/main/resources/catalog/components/viewer/profile/partials/profile.html, web-ui/src/main/resources/catalog/components/viewer/wps/WpsDirective.js, web-ui/src/main/resources/catalog/components/viewer/wps/WpsService.js, web-ui/src/main/resources/catalog/components/viewer/wps/partials/processform.html, web-ui/src/main/resources/catalog/locales/en-core.json, web-ui/src/main/resources/catalog/style/gn_viewer.less
Improvements:
* Better support for `minOccurs` and `maxOccurs` attributes for WPS services: for the fields that support it, the form now allow the user to enter several values:
* Geometry tool has a better usability + bug fixes
* Profile graph rendering is improved
* Hovering the profile graph or the profile geometry gives the correct feedback:
=> WPS directive improvements

services/src/main/java/org/fao/geonet/api/registries/DirectoryApi.java, services/src/test/java/org/fao/geonet/api/registries/ApiImportSpatialDirectoryEntriesTest.java, services/src/test/resources/org/fao/geonet/api/registries/layers_111_feature.xml, services/src/test/resources/org/fao/geonet/api/registries/layers_111_feature_EPSG_3857.xml
* delete tmp dir on exit, even if it same not to operate
* try to fix build
=> Subtemplate / Extent from shapefile test improvements (#5)

web-ui/src/main/resources/catalog/components/common/map/mapService.js, web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextService.js, web/src/main/webapp/WEB-INF/data/data/resources/map/config-viewer.xml
This pull request it´s for add tms type support for base layer on config-viewer.xml.
An example is provided in the config-viewer.xml file
=> Add support for TMS base layer on config-viewer.xml

services/src/main/java/org/fao/geonet/api/records/MetadataIndexApi.java, web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js, web-ui/src/main/resources/catalog/components/search/resultsview/partials/selection-widget.html, web-ui/src/main/resources/catalog/locales/en-search.json
Add a new button in metadata action menu from search page to index the selected records.
=> Add an indexing of the metadata selection feature in search page

web-ui/src/main/resources/catalog/components/edit/directoryentryselector/DirectoryEntrySelector.js, web-ui/src/main/resources/catalog/components/metadatamanager/EditorService.js, web-ui/src/main/resources/catalog/js/edit/DirectoryController.js, web-ui/src/main/resources/catalog/js/edit/EditorBoardController.js, web-ui/src/main/resources/catalog/templates/editor/directory.html
* Disable valid/reject action if already in one of those states.
* Add option to limit validation to admin only
* Remove duplicated save action in editor mode
* Add option to publish when validated
=> Directory manager options on validation

core/src/main/java/org/fao/geonet/util/XslUtil.java, schemas/iso19139/src/main/plugin/iso19139/loc/ara/schematron-rules-url-check.xml, schemas/iso19139/src/main/plugin/iso19139/loc/cat/schematron-rules-url-check.xml, schemas/iso19139/src/main/plugin/iso19139/loc/chi/schematron-rules-url-check.xml, schemas/iso19139/src/main/plugin/iso19139/loc/dut/schematron-rules-url-check.xml, schemas/iso19139/src/main/plugin/iso19139/loc/eng/schematron-rules-url-check.xml, schemas/iso19139/src/main/plugin/iso19139/loc/fin/schematron-rules-url-check.xml, schemas/iso19139/src/main/plugin/iso19139/loc/fre/schematron-rules-url-check.xml, schemas/iso19139/src/main/plugin/iso19139/loc/ger/schematron-rules-url-check.xml, schemas/iso19139/src/main/plugin/iso19139/loc/ita/schematron-rules-url-check.xml, schemas/iso19139/src/main/plugin/iso19139/loc/nor/schematron-rules-url-check.xml, schemas/iso19139/src/main/plugin/iso19139/loc/pol/schematron-rules-url-check.xml, schemas/iso19139/src/main/plugin/iso19139/loc/por/schematron-rules-url-check.xml, schemas/iso19139/src/main/plugin/iso19139/loc/rus/schematron-rules-url-check.xml, schemas/iso19139/src/main/plugin/iso19139/loc/spa/schematron-rules-url-check.xml, schemas/iso19139/src/main/plugin/iso19139/loc/tur/schematron-rules-url-check.xml, schemas/iso19139/src/main/plugin/iso19139/schematron/schematron-rules-url-check.report_only.sch
Add new schematron rules for url check in metadata.
Not critical
=> Add a url check in editor metadata validation

core/src/main/java/org/fao/geonet/kernel/EditLib.java
=> wip, dirty fix for snippet trouble

common/src/main/java/org/fao/geonet/utils/IO.java, core/src/main/java/jeeves/xlink/Processor.java, core/src/main/java/org/fao/geonet/kernel/DataManager.java, core/src/main/java/org/fao/geonet/kernel/search/LuceneSearcher.java, core/src/main/java/org/fao/geonet/kernel/search/index/IndexingTask.java, core/src/test/java/org/fao/geonet/kernel/AbstractIntegrationTestWithMockedSingletons.java, core/src/test/java/org/fao/geonet/kernel/LocalXLinksInMetadataIntegrationTest.java, core/src/test/java/org/fao/geonet/kernel/LocalXLinksUpdateHaveToTriggerIndexationTest.java, core/src/test/resources/org/fao/geonet/kernel/babarContact.xml, core/src/test/resources/org/fao/geonet/kernel/vicinityMap.xml, web/src/test/java/org/fao/geonet/kernel/schema/TestIso19139SchematronDefinition.java, web/src/test/java/org/fao/geonet/wro4j/Wro4jJsCssCompilationTest.java, web/src/test/resources/http-request-factory-context.xml
work in progress, are travis tests ok ?
=> reindex when shared object edited

pom.xml
=> Duplicated postgres driver in war causes startup issues #2146

web-ui/src/main/resources/catalog/components/edit/bounding/BoundingDirective.js, web-ui/src/main/resources/catalog/components/edit/bounding/partials/boundingpolygon.html, web-ui/src/main/resources/catalog/components/search/facets/FacetDimensionDirective.js, web-ui/src/main/resources/catalog/components/search/facets/partials/dimension-facet-category.html, web-ui/src/main/resources/catalog/components/viewer/geometry/GeometryDirective.js, web-ui/src/main/resources/catalog/components/viewer/geometry/partials/geometrytool.html, web-ui/src/main/resources/catalog/components/viewer/localisation/LocalisationDirective.js, web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextDirective.js, web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextService.js, web-ui/src/main/resources/catalog/components/viewer/wps/WpsDirective.js, web-ui/src/main/resources/catalog/components/viewer/wps/WpsService.js, web-ui/src/main/resources/catalog/components/viewer/wps/partials/processform.html, web-ui/src/main/resources/catalog/style/gn_editor.less, web-ui/src/main/resources/catalog/style/gn_search.less, web-ui/src/main/resources/catalog/style/gn_viewer.less, web-ui/src/main/resources/catalog/views/default/less/gn_search_default.less
Some more UI polish:
* added `&nbsp;` between icons & labels on draw buttons (WPS form & bounding polygon editor)
* added a broadcast event when loading a context (including but not only the default one)
* fixed zooming on the map when finishing a shape (either in WPS form or Bounding Polygon editor)
* fixed scrollbar unexpectedly showing up in the profile panel
* added support for custom template in `gn-ows-context` directive
* minor improvements to `WPSDirective` and `WPSService`
* improve lang fetching in Localisation directive
=> Minor UI fixes

web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js, web-ui/src/main/resources/catalog/components/viewer/localisation/LocalisationDirective.js, web-ui/src/main/resources/catalog/js/CatController.js
(just a different "secure" domain). Url now on the settings to easily change it in the future.
=> Bug fixing: Using geocoder that works fine with https and IE

web-ui/src/main/resources/catalog/components/edit/directoryassociatedmd/partials/associated-results.html, web-ui/src/main/resources/catalog/style/gn_editor.less, web-ui/src/main/resources/catalog/templates/editor/directory.html
Several small things were tweaked on this UI:
* better search widgets positioning (pagnination, selection, sort)
* better responsive behavior
* margin fixes
=> Minor fixes & improvements to directory UI

web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/linktosibling.html, web-ui/src/main/resources/catalog/locales/en-editor.json
=> Fix "link to sibling" button label in MD editor

services/src/main/java/org/fao/geonet/api/records/editing/MetadataEditingApi.java
Related to #1659.
Currently, user does not know that this happen.
=> Warn user that record edited was unpublished due to its validation status

web-ui/src/main/resources/catalog/components/viewer/layermanager/partials/layermanager.html, web-ui/src/main/resources/catalog/components/viewer/layermanager/partials/layermanageritem.html, web-ui/src/main/resources/catalog/components/viewer/partials/mainviewer.html, web-ui/src/main/resources/catalog/locales/en-search.json, web-ui/src/main/resources/catalog/style/gn_viewer.less
This PR is an attempt at improving the layers appearance in the layer manager panel. Functionalities are the same, only the layout have been changed:
Objectives were:
* clearer "show legend" action, hidden if no legend or attribution available
* fixing the settings popover (see #2201)
* bigger up/down buttons
=> Layer manager UI improvement

core/src/main/java/org/fao/geonet/constants/Geonet.java, core/src/main/java/org/fao/geonet/kernel/DataManager.java, core/src/main/java/org/fao/geonet/util/XslUtil.java, schemas/iso19139/src/main/plugin/iso19139/update-fixed-info-subtemplate.xsl, schemas/iso19139/src/main/plugin/iso19139/update-fixed-info.xsl
Applies to EX_Extent and EX_SpatialTemporalExtent
=> ISO19139 / Subtemplate / Extent / Compute bbox when a polygon is described

web-ui/src/main/resources/catalog/components/search/mdview/partials/contact.html, web-ui/src/main/resources/catalog/style/gn_metadata.less
Small UI improvement to contacts (only when grouped by org & role).
Previous:
New:
=> Improve MD contacts rendering

web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html, web-ui/src/main/resources/catalog/components/common/map/mapService.js, web-ui/src/main/resources/catalog/components/common/ows/OWSService.js, web-ui/src/main/resources/catalog/components/index/IndexRequest.js, web-ui/src/main/resources/catalog/components/metadataactions/RelatedDirective.js, web-ui/src/main/resources/catalog/components/search/facets/FacetsDirective.js, web-ui/src/main/resources/catalog/components/search/facets/partials/facet-daterange.html, web-ui/src/main/resources/catalog/components/search/facets/partials/facet-graph.html, web-ui/src/main/resources/catalog/components/search/formfields/FormFieldsDirective.js, web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js, web-ui/src/main/resources/catalog/components/viewer/graticule/GraticuleDirective.js, web-ui/src/main/resources/catalog/components/viewer/wfsfilter/WfsFilterDirective.js, web-ui/src/main/resources/catalog/components/viewer/wfsfilter/WfsFilterService.js, web-ui/src/main/resources/catalog/components/viewer/wfsfilter/partials/wfsfilterfacet.html, web-ui/src/main/resources/catalog/js/CatController.js, web-ui/src/main/resources/catalog/lib/timeline/timeline-zoomable.js, web-ui/src/main/resources/catalog/locales/en-admin.json, web-ui/src/main/resources/catalog/style/gn_search.less
These are mainly UI fixes/small improvements which are beneficial to the core:
* Misc improvements to the features index search (for the WFS filter functionality)
* Added support for the `grid ` setting in UI settings (fixes #2205)
* Added polyfill for WMTS loading in IE
* Improvements to the "Related" button directive
* Fix on the "sortby" combo that would change the parent scope without user action
* Better handle CRS values when adding a child layer from a GetCapabilities response (inheritance)
* Minor fix to WMS graticule
=>  Misc backports from customer forks

harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/webdav/Harvester.java, web-ui/src/main/resources/catalog/components/admin/harvester/partials/extras.html
Adding settings to override, skip or generate a random UUID for CSW, GeoNetwork and webdav harvester. Also it is printed on the log of the harvester to trace when this happens.
=> Harvesters collision

web-ui/src/main/resources/catalog/style/gn.less
Fixes #2285.
See https://github.com/twbs/bootstrap/issues/18543.
=> Fixes scrollbar overlapping content in IE

core/src/main/java/org/fao/geonet/constants/Geonet.java, core/src/main/java/org/fao/geonet/kernel/DataManager.java, web/src/main/webapp/WEB-INF/config-summary.xml
Add a facet `isPublishedToAll` to the manager summary. If it is published to the group all the value of the facet is `y`, in other case it is `n`.
=> Add a facet isPublishedToAll to the manager summary

web/src/main/webapp/xslt/base-layout.xsl
move notification up, else it is below the bottom of the page, add warning style
=> move js alert up on page

web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js, web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html, web-ui/src/main/resources/catalog/components/filestore/FileStoreDirective.js, web-ui/src/main/resources/catalog/locales/en-core.json
Another batch of UI fixes towards the 3.4 release:
* Added missing `resolutions` locale key
* Fixed the behaviour of the "Add Online Resource" dialog regarding uploaded files (previously, clicking several times on the same file would not refresh the URL and name values)
=> Misc UI fixes

domain/src/main/java/org/fao/geonet/repository/MetadataRepository.java, domain/src/main/java/org/fao/geonet/repository/MetadataRepositoryCustom.java, domain/src/main/java/org/fao/geonet/repository/MetadataRepositoryImpl.java, services/src/main/java/org/fao/geonet/guiservices/metadata/Sitemap.java, web/src/main/webapp/xslt/services/sitemap/sitemap.xsl
This pull request is to fix a memory issue (OutOfMemoryError) with sitemap on portals with many metadata records. The full xml parsing is replaced with a simple query on database.
=> Sitemap memory issue

web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
Add the following schema.org tags:
- schema.org/url
- schema.org/name
- schema.org/identifier
=> Improve schema.org tags (#2233)

web-ui/src/main/resources/catalog/components/common/ows/OWSService.js, web-ui/src/main/resources/catalog/components/search/formfields/FormFieldsDirective.js, web-ui/src/main/resources/catalog/components/search/formfields/partials/bboxInput.html, web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js, web-ui/src/main/resources/catalog/components/viewer/measure/MeasureDirective.js, web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextService.js, web-ui/src/main/resources/catalog/components/viewer/wfsfilter/WfsFilterDirective.js, web-ui/src/main/resources/catalog/components/viewer/wfsfilter/WfsFilterService.js, web-ui/src/main/resources/catalog/components/viewer/wfsfilter/partials/wfsfilterfacet.html, web-ui/src/main/resources/catalog/components/viewer/wps/WpsDirective.js, web-ui/src/main/resources/catalog/components/viewer/wps/partials/processform.html, web-ui/src/main/resources/catalog/lib/timeline/timeline-zoomable.js
The measure tool now uses geodesic measurements and takes into account the current map projection. Example of the Earth circumference measurement in EPSG:4326:
Other UI fixes include:
* Map extent is now correctly restored when a map reset occurs (either loading the default map or a map from an xml file)
* Fixes to WPS and WFS form components (dates, bounding box...)
=> Improvement to measure tool & minor UI fixes

web-ui/src/main/resources/catalog/components/catalog/CatalogService.js, web-ui/src/main/resources/catalog/js/edit/EditorController.js
Backport of #1668 fix to 3.2.x branch
=> Editor / No "just created" flag for new records in Geonetwork 3.2.x

.gitignore, services/src/main/java/org/fao/geonet/api/site/SiteInformation.java, web-ui/src/main/resources/catalog/locales/en-admin.json, web-ui/src/main/resources/catalog/templates/admin/dashboard/information.html, web/pom.xml, web/src/main/webResources/WEB-INF/config-spring-env.xml
Also, check you are at least an authenticated user to ask the API about the site info.
So for each GeoNetwork build we can know the exact build it was compiled with, the commit message, how far is the commit from last version (substitutes SNAPSHOT with count of commits since tag), timestamp of creation and even if the source code was dirty on the moment of build (it means: if it had any modifications compared to the git source code).
=> Adding git version information to Site Info.

web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/editor.html, web-ui/src/main/resources/catalog/js/edit/DirectoryController.js, web-ui/src/main/resources/catalog/templates/editor/directory.html
* Directory manager
* Editor board
=> Use same layout for record info (ie. owner name and last update) in directory manager and editor board.

web-ui/src/main/resources/catalog/components/viewer/wps/WpsDirective.js, web-ui/src/main/resources/catalog/components/viewer/wps/partials/processform.html, web-ui/src/main/resources/catalog/style/gn_viewer.less
* Fields can be set as hidden/inputs in the `applicationProfile` field associated to the WPS service in the metadata
* "Download" button is now positioned inline in the WPS form:
=> Support hidden/disabled fields in WPS form

web-ui/src/main/resources/catalog/js/CatController.js, web-ui/src/main/resources/catalog/locales/en-core.json, web-ui/src/main/resources/catalog/style/gn_login.less, web-ui/src/main/resources/catalog/templates/signin.html, web-ui/src/main/resources/catalog/templates/top-toolbar.html, web-ui/src/main/resources/catalog/views/default/less/gn_navbar_default.less
Add a title and text on the login form. Add an icon in front of the username and password input.
**Screenshot of the login page**
=> Title and text on login

services/src/main/java/org/fao/geonet/api/records/formatters/ConfigFile.java
=> Fix override order in the formatters' config

core/src/main/java/org/fao/geonet/kernel/search/facet/FacetNameFormatter.java
=> fixed problem with filtering on type in dutch

web-ui/src/main/resources/catalog/components/common/multiselect/MultiselectDirective.js, web-ui/src/main/resources/catalog/components/common/multiselect/partials/multiselect.html, web-ui/src/main/resources/catalog/components/thesaurus/ThesaurusDirective.js, web-ui/src/main/resources/catalog/components/thesaurus/partials/keywordselector.html, web-ui/src/main/resources/catalog/js/admin/UserGroupController.js, web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html
When having long list of groups, it can be quite complicated to select them in the multiple select.
Use 2 select inputs for each roles: one with list of groups available, one with list of groups selected.
=> User groups / Use twin selector instead of multiselect. Add filter.

services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java, web-ui/src/main/resources/catalog/components/catalog/CatalogService.js, web-ui/src/main/resources/catalog/js/edit/NewMetadataController.js
=> Create record from template having categories should copy categories 

web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionsDirective.js, web-ui/src/main/resources/catalog/components/metadataactions/partials/metadatacategoryupdater.html, web-ui/src/main/resources/catalog/js/edit/EditorController.js, web-ui/src/main/resources/catalog/templates/editor/top-toolbar.html
eg. 
```
<section xpath="/gmd:MD_Metadata/gmd:identificationInfo/*/gmd:descriptiveKeywords"/>
<directive data-gn-metadata-category-updater="mdCategories"
data-metadata-uuid="gnCurrentEdit.uuid"
data-gn-mode="autocomplete"/>
```
=> Editor / Categories in editor form

web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less, web-ui/src/main/resources/catalog/views/default/less/gn_footer_default.less, web-ui/src/main/resources/catalog/views/default/less/gn_layout_default.less, web-ui/src/main/resources/catalog/views/default/less/gn_login_default.less, web-ui/src/main/resources/catalog/views/default/less/gn_map_default.less, web-ui/src/main/resources/catalog/views/default/less/gn_navbar_default.less, web-ui/src/main/resources/catalog/views/default/less/gn_result_default.less, web-ui/src/main/resources/catalog/views/default/less/gn_results_default.less, web-ui/src/main/resources/catalog/views/default/less/gn_search_default.less, web-ui/src/main/resources/catalog/views/default/less/gn_topics_default.less, web-ui/src/main/resources/catalog/views/default/less/gn_variables_default.less, web-ui/src/main/resources/catalog/views/default/templates/results.html
A new less file is introduced for storing variables that can be used throughout GeoNetwork views and other less files.
This single file for css properties is to have just one place where you can change the properties, either by changing the file directly or by settings in the admin (not yet built).
This introduction comes with colors for background, text and hover for the header menubar and the bottombar.
=> Introduction of variables less file

web-ui/src/main/resources/catalog/components/common/share/ShareService.js
Plz verify if my assumption in #2470 is correct
=> Also useradmin is allowed to assign 'all-group' to records

web-ui/src/main/resources/catalog/components/metadataactions/RelatedResourcesService.js, web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
Fix:
* description was not displayed if protocol not a well know one
* description was not displayed since it is multilingual now
=> Related / Display description properly

web/pom.xml
This filter in war build unnecessary files. #2487
=> Filter unnecessary files from war build

schemas/iso19139/src/main/resources/config-spring-geonetwork.xml, web-ui/src/main/resources/catalog/components/viewer/wfsfilter/WfsFilterDirective.js, web-ui/src/main/resources/catalog/components/viewer/wfsfilter/WfsFilterService.js, web-ui/src/main/resources/catalog/components/viewer/wfsfilter/partials/wfsfilterfacet.html, web-ui/src/main/resources/catalog/js/jsonix/OWS_1_0_0.js, web-ui/src/main/resources/catalog/js/jsonix/OWS_1_1_0.js
* JSONIX mappings have been fixed (fixes #2498)
* Minor fixes to the filtering form, inc. a text filter by field instead of globally (backports from Sextant)
=> Fixes to WFS indexing & filtering

core/src/main/java/org/fao/geonet/ContextAwareTask.java, core/src/main/java/org/fao/geonet/MergeUsersByUsernameDatabaseMigration.java, core/src/main/java/org/fao/geonet/exceptions/TaskExecutionException.java, core/src/main/java/org/fao/geonet/kernel/security/ldap/LDAPUtils.java, core/src/test/java/org/fao/geonet/AbstractCoreIntegrationTest.java, core/src/test/java/org/fao/geonet/MergeUsersByUsernameDatabaseMigrationTest.java, domain/src/main/java/org/fao/geonet/domain/User.java, domain/src/main/java/org/fao/geonet/repository/MetadataStatusRepositoryCustom.java, domain/src/main/java/org/fao/geonet/repository/MetadataStatusRepositoryImpl.java, domain/src/main/java/org/fao/geonet/repository/UserRepository.java, domain/src/main/java/org/fao/geonet/repository/UserRepositoryCustom.java, domain/src/main/java/org/fao/geonet/repository/UserRepositoryImpl.java, domain/src/main/java/org/fao/geonet/repository/UserSavedSelectionRepository.java, domain/src/main/java/org/fao/geonet/repository/specification/MetadataStatusSpecs.java, domain/src/main/java/org/fao/geonet/repository/specification/UserGroupSpecs.java, domain/src/test/java/org/fao/geonet/repository/UserRepositoryTest.java, services/src/main/java/org/fao/geonet/api/tools/migration/MigrationApi.java, services/src/main/java/org/fao/geonet/api/users/RegisterApi.java, services/src/main/java/org/fao/geonet/api/users/UsersApi.java, services/src/main/java/org/fao/geonet/services/register/SelfRegister.java, services/src/main/java/org/fao/geonet/services/user/Update.java, services/src/main/resources/org/fao/geonet/api/Messages.properties, services/src/main/resources/org/fao/geonet/api/Messages_fre.properties, services/src/test/java/org/fao/geonet/api/users/UsersApiTest.java, web/src/main/webapp/WEB-INF/config-security/config-security-core.xml
=> Don't allow the creation/update of users with case insensitive duplicated usernames

web-ui/src/main/resources/catalog/views/default/less/gn_footer_default.less, web-ui/src/main/resources/catalog/views/default/less/gn_layout_default.less, web-ui/src/main/resources/catalog/views/default/less/gn_result_default.less, web-ui/src/main/resources/catalog/views/default/less/gn_results_default.less, web-ui/src/main/resources/catalog/views/default/less/gn_topics_default.less
Added extra imports to fix the variable declaration build tests. Testing and building doesn't work with transitive imports.
=> Fix for variable declaration tests and compiling

integration-test/.gitignore, integration-test/README.md, integration-test/doc/canned_steps.md, integration-test/pom.xml, integration-test/src/main/java/env/BaseTest.java, integration-test/src/main/java/env/Env.java, integration-test/src/main/java/methods/AssertionMethods.java, integration-test/src/main/java/methods/ClickElementsMethods.java, integration-test/src/main/java/methods/ConfigurationMethods.java, integration-test/src/main/java/methods/ErrorHandlingMethods.java, integration-test/src/main/java/methods/InputMethods.java, integration-test/src/main/java/methods/JavascriptHandlingMethods.java, integration-test/src/main/java/methods/MiscMethods.java, integration-test/src/main/java/methods/NavigateMethods.java, integration-test/src/main/java/methods/ProgressMethods.java, integration-test/src/main/java/methods/ScreenShotMethods.java, integration-test/src/main/java/methods/SelectElementByType.java, integration-test/src/main/java/methods/TestCaseFailed.java, integration-test/src/test/java/stepDefintions/Hooks.java, integration-test/src/test/java/stepDefintions/PredefinedStepDefinitions.java, integration-test/src/test/java/stepDefintions/RunCukeTest.java, integration-test/src/test/java/stepDefintions/UserStepDefinitions.java, integration-test/src/test/resources/features/001.login.feature, integration-test/src/test/resources/system.properties
Following #625 , this PR introduces a selenium & cucumber environment that can be used for running multiple suits of fully automated tests that can be run against a range of browsers.
The README.md explain how to run the tests.
This test suit is separated from the maven configuration of GeoNetwork, because it must be kept and scheduled as optional. But it's still necessary to have it as a subproject, to keep the tests aligned with the branch/version.
One basic example test is in /integration-test/src/test/resources/features
=> Integration test environment

.gitignore, web/src/main/webapp/WEB-INF/data/node_less_files/gn_dynamic_style.json
Remove custom json style gn_dynamic_style.json
=> FIX: Remove custom style

web-ui/src/main/resources/catalog/style/ellipsis.less
The import is wrong and ellipsis.less doesn't use the variables less file.
=> Remove wrong less import

web-ui/src/main/resources/catalog/js/edit/EditorBoardController.js, web-ui/src/main/resources/catalog/locales/en-editor.json, web/src/main/webapp/xslt/ui-metadata/editor.xsl
=> Add editor board hotkeys

core/src/main/java/org/fao/geonet/kernel/DataManager.java
eg. while running XSL processing and when a UUID which already exists is created
(that may happen when schema define custom rule to build UUID in update-fixed-info)
a DataIntegrityViolationException is returned and stop the whole process:
```
Caused by: org.postgresql.util.PSQLException:
ERROR: duplicate key value violates unique constraint \"metadata_uuid_key\"\n
Détail : Key (uuid)=(SDN_CPRD_3471_BSBD) already exists.\n\tat
```
In order to have processing moving to the next record, run a check in DataManager
to avoid to throw the JPA at the transaction level but rather send a clear
message to user to indicate that the result of the process build an existing UUID:
```
"metadataErrors": {
"100470": [
{
"message": "Another record exist with UUID 'SDN_CPRD_3471_BSBD'. This record as …
```
=> Return application exception instead of JPA transaction errors when duplicated UUID is created.

web-ui/src/main/resources/catalog/components/common/map/mapService.js, web-ui/src/main/resources/catalog/components/utility/CORSInterceptor.js, web-ui/src/main/resources/catalog/components/viewer/wmsimport/WmsImportDirective.js
This PR contains two things:
* Improving error handling in CORS (based on 3.4.x version).
* Making sure layers that need a proxy, have a proxy.
=> Fix proxy for #2595

web-ui/src/main/resources/catalog/components/common/map/print/PrintMapDirective.js, web-ui/src/main/resources/catalog/components/common/map/print/PrintMapService.js
Adding XYZ layer to mapfish configuration (before this, those layers are ignored).
Also, fix hard-coded projection on source code.
=> Add XYZ layers to mapfish print. 

web/pom.xml
formatter folder must not be excluded !
=> Keep formatter folder in .war

services/src/main/java/org/fao/geonet/api/processing/XslProcessApi.java
Currently exceptions which may happen during processing are not displayed at all. Blank page returned and exception is not even displayed in logged because it is caught and stored in the report.
This displays the report in case of error:
=> XSL processing / Preview mode / Return error report.

schemas/dublin-core/src/main/plugin/dublin-core/extract-relations.xsl, schemas/dublin-core/src/main/plugin/dublin-core/layout/config-editor.xml, services/src/main/java/org/fao/geonet/api/records/MetadataApi.java, services/src/main/java/org/fao/geonet/api/records/MetadataUtils.java
A fix for https://github.com/geonetwork/core-geonetwork/issues/2601
* Add missing sidepanel config
* Fix NPE on relation service
* Fix wrong language code resolution (fra for fre for example)
* Fix missing multilingual URL support
@josegar74 please review and merge. Thanks
=> Fix DC relation 

web-ui/src/main/resources/catalog/components/common/map/mapService.js, web-ui/src/main/resources/catalog/components/viewer/gfi/FeaturesLoader.js, web-ui/src/main/resources/catalog/components/viewer/wfsfilter/WfsFilterDirective.js, web-ui/src/main/resources/catalog/components/viewer/wms/WmsDirective.js, web-ui/src/main/resources/catalog/components/viewer/wms/WmsService.js, web-ui/src/main/resources/catalog/components/viewer/wmsimport/WmsImportDirective.js
resolves #1354
we have >3 points in the code where a layer capabilities is retrieved, had to extend each of these to include service info
PR also has a patch for #2663
=> verify if infoformat is available before requesting it in GFI

web/src/main/webapp/xslt/base-layout.xsl
this is used by search engine crawlers, resolves issue #2652
review by deactivate javascript in browser, should display a basic page with some text and a warning to activate javascript or go to no-js interface
=> add some default text to the non-javascript homepage

web-ui/src/main/resources/catalog/components/viewer/baselayerswitcher/BaseLayerSwitcherDirective.js, web-ui/src/main/resources/catalog/components/viewer/baselayerswitcher/partials/baselayerswitcher.html
Added a button similar to the one in "Maps" panel.
https://github.com/geonetwork/core-geonetwork/issues/2605
=> Adding a map reset button in map 'Manage Layers' panel

web-ui/src/main/resources/catalog/components/metadataactions/RelatedResourcesService.js, web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
resolves https://github.com/geonetwork/core-geonetwork/issues/2553
check the link for startswith http-ftp-// before showing it as a link
=> Check link on http, then display as link

harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFsHarvesterFileVisitor.java
Set harvester privileges to metadata that comes from MEF harvesting (localfilesystem harvester)
=> MEF harvesting privileges

web-ui/src/main/resources/catalog/views/default/templates/home.html, web-ui/src/main/resources/catalog/views/default/templates/recordView.html
Small fix to stop the initialization of userfeedback directive when the function is deactivated.
=> Avoid initialization of userfeedback directive

services/src/main/java/org/fao/geonet/api/site/LogosApi.java, web-ui/src/main/resources/catalog/js/admin/UserGroupController.js, web-ui/src/main/resources/catalog/templates/admin/usergroup/groups.html
* Restore logo upload in group's admin page.
* Throws a ResourceAlreadyExistsException if logo already exists instead of a IOException.
Fixes #2609.
=>  Restore logo upload as part of group config

services/src/main/java/org/fao/geonet/api/records/MetadataApi.java
Fix to avoid the 404 Http error on empty features catalogs
=> Check for null in feature catalogs

core/src/main/java/org/fao/geonet/util/XslUtil.java, schemas/iso19139/src/main/plugin/iso19139/process/process-utility.xsl, web-ui/src/main/resources/catalog/components/edit/suggestion/partials/runprocess.html
This pull fixes two issues on the Apply Suggestion functionality in metadata editor:
1. The checkbox status is no longer ignored (fixed in web-ui/src/main/resources/catalog/components/edit/suggestion/partials/runprocess.html)
2. When a proxy using authentication is configured, the schemas/iso19139/src/main/plugin/iso19139/process/process-utility.xsl will use a java function to manage the connection
=> Fix for "apply suggestion" panel

core/src/main/java/org/fao/geonet/web/LocaleRedirects.java
This should fix https://github.com/geonetwork/core-geonetwork/issues/2225 
The idea is to force the defined catalog server host from settings, when defined.
=> Fix for create service url

web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js, web-ui/src/main/resources/catalog/templates/admin/settings/system.html
=> Don't display GeoNetwork "internal" settings in the Settings UI. Fixes #2722

web-ui/src/main/resources/catalog/js/admin/UserGroupController.js
See details in the issue #2730. Any improvement is welcome, thanks.
=> Create a new user shows the privileges of the previous user created. Fixes #2730

core/src/main/java/org/fao/geonet/kernel/DataManager.java
* wait call must be inside a synchronized block. In other cases it
throws IllegalMonitorStateException.
* Use a specific lock to synchronize the modification of indexing set.
Port of PR #2548 to 3.4.x branch.
=> Port of PR #2548. Fix deadlock threads while indexing

schemas/iso19139/src/main/plugin/iso19139/convert/OGCWxSGetCapabilitiesto19119/OGCWxSGetCapabilities-to-19119.xsl, schemas/iso19139/src/main/plugin/iso19139/convert/OGCWxSGetCapabilitiesto19119/identification.xsl, schemas/iso19139/src/main/plugin/iso19139/convert/OGCWxSGetCapabilitiesto19119/resp-party.xsl, web-ui/src/main/resources/catalog/templates/admin/harvest/type/ogcwxs.html
Add new harvester for WPS standard version 2.0.0
=> Harvesting wps2.0.0

harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet20/Aligner.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/oaipmh/Harvester.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/ogcwxs/Harvester.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/thredds/Harvester.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/webdav/Harvester.java
Bug fix: Records were not being assigned to the proper user.
Failback: harvester owner, if no user is defined.
=> Bug fix: Records were not being assigned to the proper user.

harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/webdav/Harvester.java
harvesters when "overriding" option is setup. Also, change of ownership.
Same change as in #2545 but for CSW and webdav harvesters.
=> Make sure transformations and attributes are applied on CSW and Webdav

web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
=> a condition:mandatory in labels.xml

web-ui/src/main/resources/catalog/lib/underscore/underscore.js
The GeoNetwork log is filled with wro4j exceptions with the message "Cannot build valid CacheKey from request: /geonetwork/static/underscore-min.map" because of this missing file.
=> Missing underscore.js

harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/HarvestError.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/HarvesterUtil.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Harvester.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geoPREST/Aligner.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geoPREST/Harvester.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Harvester.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/oaipmh/Harvester.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/webdav/Harvester.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/wfsfeatures/Harvester.java
ref: https://github.com/geonetwork/core-geonetwork/commit/b14415ed2c46f028eee724f851cc675bb79d9ec3#diff-627e54362a3ae3de8c7a2320627f8331
=> Harvester: persist uuid if changed by xsl transfo

web-ui/src/main/resources/catalog/style/gn_viewer.less, web-ui/src/main/resources/catalog/views/default/less/gn_footer_default.less, web-ui/src/main/resources/catalog/views/default/less/gn_map_default.less, web-ui/src/main/resources/catalog/views/default/less/gn_variables_default.less
* Fix the map height in Internet Explorer 11.
* Fix control tools (zoom plus, zoom minus, ...) not shown in IE
* Set the footer on the bottom.
Fixes #2469.
=> Problem with map in IE

core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java, estest/pom.xml, estest/src/test/java/org/fao/geonet/es/IndexationTest.java, estest/src/test/resources/nominal/index-fields/index.xsl, pom.xml
had to make temporarly a few variable public
remove two static modifiers
move variables declaration atr the beginning of a file
=> add a nominal test for indexation

harvesters/src/main/java/org/fao/geonet/kernel/harvest/AbstractAligner.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/BaseAligner.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/CswHarvester.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/fragment/FragmentHarvester.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geoPREST/Aligner.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet20/Aligner.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/oaipmh/Harvester.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/ogcwxs/Harvester.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/thredds/Harvester.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/webdav/Harvester.java
this can lead to nullPointer exception with harvester.
refactor code to allow correction at one place.
remove obsolete copied/pasted comments.
cf. https://commons.apache.org/proper/commons-lang/javadocs/api-2.6/org/apache/commons/lang/StringUtils.html#isNumeric(java.lang.String
=> apache 2.6 isNumeric("") return true

core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java, schemas/iso19139/pom.xml, schemas/iso19139/src/test/java/org/fao/geonet/schemas/XslIndexTest.java
=> rewrite toJon method

schemas/iso19139/src/main/plugin/iso19139/layout/utility-tpl.xsl, web-ui/src/main/resources/catalog/components/common/map/mapDirective.js, web-ui/src/main/resources/catalog/components/common/map/print/PrintDirective.js, web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
config that made the "add to thumbnail" on the editor fail.
=> Bug fix: Missing title on the default print-thumbnail

web/src/main/webapp/xslt/services/inspire-atom/opensearch.xsl
this improvement does not conflict with https://github.com/geonetwork/core-geonetwork/pull/2308 but improves the 'external atom' opensearchdescription
=> improve opensearch to fit download spec

web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
=> option to add selected layer from wmts to onlinesrcdirective

core/src/main/java/org/fao/geonet/kernel/EditLib.java
This PR relate to https://github.com/geonetwork/core-geonetwork/issues/2714.
=> Fix adding keyword

web-ui/src/main/resources/catalog/components/search/mdview/mdviewModule.js, web-ui/src/main/resources/catalog/locales/en-core.json
=> a generic error is displayed if full view fails due to xslt error

web-ui/src/main/resources/catalog/components/userfeedback/GnmdFeedbackDirective.js
=> check for no contacts before extracting contacts

core/src/main/java/jeeves/constants/Jeeves.java, core/src/main/java/jeeves/server/dispatchers/ServiceManager.java, web/src/main/webapp/xslt/base-layout.xsl, web/src/main/webapp/xslt/common/base-variables.xsl
ARIA requires that html's lang attribute to be a two letters language code (ISO 639-1 Language Code)
=> <html> element must have a valid value for the lang attribute

web-ui/src/main/resources/catalog/components/elasticsearch/EsService.js, web-ui/src/main/resources/catalog/views/default/templates/advancedSearchForm/defaultAdvancedSearchForm.html
Also fixed the category criteria
=> ES: implemented support for date ranges in search form

core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java, schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl, services/src/main/java/org/fao/geonet/api/site/SiteApi.java, web-ui/src/main/resources/catalog/components/catalog/CatalogService.js, web-ui/src/main/resources/catalog/components/elasticsearch/EsService.js, web-ui/src/main/resources/catalog/components/index/IndexRequest.js, web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid.html, web-ui/src/main/resources/catalog/js/admin/AdminToolsController.js, web-ui/src/main/resources/catalog/templates/admin/tools/index.html, web/src/main/webapp/WEB-INF/data/config/index/records.json
=> ES multilingual indexing.

web-ui/src/main/resources/catalog/js/admin/CategoriesController.js
=> Admin / Categories / Add notification when a category can't be removed

core/src/main/java/jeeves/server/dispatchers/ServiceManager.java, services/src/main/java/org/fao/geonet/api/records/formatters/SchemaLocalizations.java
I have tested the full view formatter from the metadata detail page and with the change in `SchemaLocalizations` works fine.
Just for the record, this issue #2747 happens with current code , not related to the change in the PR.
=> Crawlers don't work with urls provided in the sitemap, fixes #2873

harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Harvester.java
=> wildcard attribute in PropertyIsLike must be wildCard (CSW harvester)

web-ui/src/main/resources/catalog/components/search/formfields/FormFieldsDirective.js
=> Metadata import / Select first group by default (instead of the empty one added if optional is true).

web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
Angular binding was incorrect, thus iso2 code was not updated properly.
Fixes #2899
=> UI Config / Fix language iso2 bug

web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
Now it parses the capabilities and shows a list of layers.
Related to #2661
=> WMTS was not parsed on Online Resource wizard on the editor

schemas/iso19110/src/main/plugin/iso19110/layout/config-editor.xml, web-ui/src/main/resources/catalog/components/edit/directoryentryselector/DirectoryEntrySelector.js
=> ISO19110 / producer does not use directory #2942.

core/src/main/java/org/fao/geonet/kernel/metadata/DefaultStatusActions.java, services/src/main/resources/org/fao/geonet/api/Messages.properties, services/src/main/resources/org/fao/geonet/api/Messages_fre.properties
Same as https://github.com/geonetwork/core-geonetwork/pull/2948 for 3.4.x
=> Workflow / Fix invalid links in email.

schemas-test/src/test/java/iso19139/UpdateFixedInfoTest.java, schemas-test/src/test/resources/iso19139/descriptiveKeywordsUpdateFixedInfoXLinked.xml, schemas/config-editor.xsd, schemas/iso19139/doc/tpl.xml, schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml, schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields-keywords.xsl, schemas/schema-core/src/main/java/org/fao/geonet/kernel/schema/editorconfig/config-editor.xsd
Fix for https://github.com/geonetwork/core-geonetwork/issues/2882
=> Editor / inspire view / thesaurus renamed

services/src/main/java/org/fao/geonet/api/registries/CrsUtils.java
=> Editor / CRS search is case sensitive #2971.

web-ui/src/main/resources/catalog/components/search/mdview/mdviewDirective.js, web-ui/src/main/resources/catalog/components/search/mdview/partials/rate.html
Fix for https://github.com/geonetwork/core-geonetwork/issues/2974
=> Rating / When off, should not be displayed in search results #2974.

services/src/main/java/org/fao/geonet/api/mapservers/GeoServerRest.java, services/src/main/java/org/fao/geonet/api/mapservers/MapServersApi.java, services/src/main/java/org/fao/geonet/services/publisher/Do.java
My suggestion for fixing https://github.com/geonetwork/core-geonetwork/issues/2970
=> GeoPublisher / wrong html metadatalink posted to geoserver

core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java, web/src/main/webapp/xslt/common/utility-tpl.xsl
Fix for https://github.com/geonetwork/core-geonetwork/issues/2959, and also contains a minor improvement for ES indexing not related at all sorry for the mix.
=> Formatter / XSLT / Break work with some hardcoded rules

web/src/main/webapp/xslt/common/utility-tpl.xsl
Fix for https://github.com/geonetwork/core-geonetwork/issues/2959
=> Formatter / XSLT / Break work with some hardcoded rules #2959.

update-version.sh
- Fix OSX check.
- Update gn.project.version property added in https://github.com/geonetwork/core-geonetwork/pull/2793
=> Update versions release script

web-ui/src/main/resources/catalog/components/index/partials/datafilterview.html, web-ui/src/main/resources/catalog/components/viewer/baselayerswitcher/partials/baselayerswitcher.html, web-ui/src/main/resources/catalog/components/viewer/layermanager/partials/layermanageritem.html, web-ui/src/main/resources/catalog/components/viewer/legendpanel/partials/legendpanel.html, web-ui/src/main/resources/catalog/components/viewer/localisation/partials/localisation.html, web-ui/src/main/resources/catalog/components/viewer/partials/mainviewer.html, web-ui/src/main/resources/catalog/components/viewer/searchlayerformap/partials/searchlayerformap.html, web-ui/src/main/resources/catalog/components/viewer/wmsimport/partials/kmlimport.html, web-ui/src/main/resources/catalog/components/viewer/wmsimport/partials/wmsimport.html, web-ui/src/main/resources/catalog/components/viewer/wps/partials/urldiscovery.html, web-ui/src/main/resources/catalog/locales/en-core.json, web-ui/src/main/resources/catalog/locales/en-search.json
This PR focusses on the map page for users that are not logged in.
Features added and changed:
- (aria) labels to buttons and inputs
- small color changes to get enough contrast
- HTML roles
The canvas with the map is not changed.
=> Added accessibility features to the elements on the map

integration-test/src/test/resources/features/001.login.feature, integration-test/src/test/resources/features/002.create_new_user.feature, integration-test/src/test/resources/features/003.delete_new_user.feature, integration-test/src/test/resources/features/004.create_advanced_users.feature, integration-test/src/test/resources/features/098.cleanup.feature
To fix the tests failing for the new confirmation on user remove.
=> Fix for integration tests

core/src/main/java/org/fao/geonet/kernel/SchemaManager.java, services/src/main/java/org/fao/geonet/api/standards/StandardsApi.java
Mainly recompile schematron rules. Otherwise developing schematron is a pain.
=> Standard / Add API to reload standards

harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/ogcwxs/Harvester.java, schemas/iso19139/src/main/plugin/iso19139/convert/ogcwxs-info-injection.xsl
Also fix missing title for WPS2 services process description.
=> Harvester / OGC WxS / When using template mode, always synch records.

schemas/config-editor.xsd, schemas/dublin-core/src/main/plugin/dublin-core/layout/layout.xsl, schemas/iso19110/src/main/plugin/iso19110/layout/layout.xsl, schemas/iso19139/src/main/plugin/iso19139/layout/layout.xsl, web/src/main/webapp/xslt/ui-metadata/form-builder.xsl, web/src/main/webapp/xslt/ui-metadata/form-configurator.xsl
This allows you to add a mandatory flag using gn-required css class when needed.
eg. INSPIRE view > CRS
=> Editor configuration / Add class attribute to action element. 

web-ui/src/main/resources/catalog/components/viewer/gfi/FeaturesLoader.js
Try to use known formats, better and more format parsing and add a failback plan.
Failback plan is not a good plan, but may work.
=> Fixes #1554

core/src/main/java/jeeves/server/dispatchers/ServiceManager.java, core/src/main/java/org/fao/geonet/kernel/setting/SettingInfo.java, core/src/main/java/org/fao/geonet/kernel/setting/SettingManager.java, csw-server/src/main/java/org/fao/geonet/component/csw/GetCapabilities.java, services/src/main/java/org/fao/geonet/api/records/formatters/XsltFormatter.java, services/src/main/java/org/fao/geonet/api/sld/SldApi.java, services/src/main/java/org/fao/geonet/guiapi/search/XsltResponseWriter.java, web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js, web/src/main/webapp/xslt/common/base-variables.xsl, web/src/main/webapp/xslt/services/dcat/rdf.xsl
Fix for https://github.com/geonetwork/core-geonetwork/issues/2987
=> HTTPs support / Remove default port 443 when required

web/src/main/java/org/fao/geonet/DatabaseMigration.java, web/src/main/webapp/WEB-INF/classes/log4j-index.xml, web/src/main/webapp/WEB-INF/classes/log4j-search.xml
this PR improves some of the warning messages on the logs if database migration is not activated, and increases log level, so info messages are also logged
=> improve error messages in database migration

web-ui/src/main/resources/catalog/components/metadatamanager/EditorService.js, web-ui/src/main/resources/catalog/js/edit/EditorController.js
Pull request #3011 will be canceled and this pull request is the same but now on the master branch.  For the description see issue #3010 
This pull request is a bug fix for the branch 3.4.x and it should be nice to be backported on the branch 3.4.x.
=> Resolve behaviour of add button in editor #3010

web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html
in https://github.com/geonetwork/core-geonetwork/blob/62c6249fc37e24ffa37e03f692331d738bebe539/web-ui/src/main/resources/catalog/locales/en-editor.json#L114 this is lowercse
=> update description string to match translations

schemas/iso19139/src/main/plugin/iso19139/loc/eng/labels.xml, web-ui/src/main/resources/catalog/components/metadataactions/RelatedResourcesService.js, web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
Getting @pvgenuchten PR to master #2356
=> add capability to add to map for tms protocol

healthmonitor/src/main/java/org/fao/geonet/monitor/health/IndexHealthCheck.java
Related to https://github.com/geonetwork/core-geonetwork/pull/3022#issuecomment-425372500. Improve warning message in health check.
=> Remote index / Health check / Better warning.

web-ui/src/main/resources/catalog/components/metadataactions/RelatedDirective.js
=> wfs in online resource should be displayed as a 'layer protocol'

core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java, domain/src/main/java/org/fao/geonet/domain/Metadata.java, domain/src/main/java/org/fao/geonet/repository/userfeedback/UserFeedbackRepository.java
Similar to #3123 without removal of parent comment.
=> Fix record removal when having feedbacks (#3122). 

csw-server/src/main/java/org/fao/geonet/component/csw/Transaction.java, csw-server/src/main/java/org/fao/geonet/csw/common/util/Xml.java, csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/SearchController.java, csw-server/src/test/java/org/fao/geonet/component/csw/CswTransactionIntegrationTest.java
Fix #3104: CSW TransactionResponse returns bad data
Backport on 3.4.x. branch.
=> #3104: Apply csw-brief.xsl to Transaction response (3.4.x backport)

csw-server/src/main/java/org/fao/geonet/component/csw/Transaction.java, csw-server/src/main/java/org/fao/geonet/csw/common/util/Xml.java, csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/SearchController.java, csw-server/src/test/java/org/fao/geonet/component/csw/CswTransactionIntegrationTest.java
Fix #3104: CSW TransactionResponse returns bad data
=> #3104: Apply csw-brief.xsl to Transaction response

web/src/main/webapp/xsl/conversion/OGCWxSGetCapabilitiesto19119/OGCWxSGetCapabilitiesLayer-to-19139.xsl
Fix for https://github.com/geonetwork/core-geonetwork/issues/2823
=> Harvester / OGC WxS / Remove space causing match to fails #2823

web-ui/src/main/resources/catalog/components/common/multiselect/MultiselectDirective.js
Fix for this https://github.com/geonetwork/core-geonetwork/issues/3055
=> Multiselect directive bug

web-ui/src/main/resources/catalog/components/common/map/print/PrintMapDirective.js, web-ui/src/main/resources/catalog/components/common/map/print/partials/printmap.html, web-ui/src/main/resources/catalog/locales/en-core.json
=> Adding a warning on the print map tool when WMS layers with whitespaces

web-ui/src/main/resources/catalog/components/common/map/print/PrintMapService.js, web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextService.js, web-ui/src/main/resources/catalog/js/CatController.js
When restored, the layer are not displayed properly.
=> Map / Context contains layer URL with proxy

web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html, web-ui/src/main/resources/catalog/locales/en-search.json
also fixes duplicated text in wmts-links add missing tms label
=> remove capabilities parsing from wmts-links in metadata view 

web/src/main/webapp/xslt/services/thesaurus/registry-to-skos.xsl
See https://github.com/geonetwork/core-geonetwork/issues/3029#issuecomment-433328729
=> Thesaurus / Import from registry / Fix date for INSPIRE classification of services

harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java, web/src/main/webapp/xsl/xml/harvesting/common.xsl
Introduced in https://github.com/geonetwork/core-geonetwork/commit/49074582ebfa07f42139f5f9f6de03aeda3a344d#diff-e2fcd72018f3c6cbcf28b21ff38124e5
=> Harvester / Fix duplicated override UUID parameter.

web-ui/src/main/resources/catalog/components/common/map/mapsManager.js, web-ui/src/main/resources/catalog/views/default/config.js
moves projection initialisation to mapsManager
=> fixes projection undefined error by changing loading order 

harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java
Updated also the method names to be a bit more clear.
=> GeoNetwork harvester doesn't add new files when reharvesting using MEF format. Fixes #3273

web-ui/src/main/resources/catalog/components/edit/fieldduration/partials/fieldduration.html, web-ui/src/main/resources/catalog/components/edit/topiccategory/partials/topiccategory.html, web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
=> Editor / Fix alignement of field using div directive eg. topicCategory and duration.

schemas/iso19139/src/main/java/org/fao/geonet/schema/iso19139/ISO19139SchemaPlugin.java, schemas/iso19139/src/main/resources/config-spring-geonetwork.xml, schemas/schema-core/src/main/java/org/fao/geonet/kernel/schema/SchemaPlugin.java
@fxprunayre Please check, as not sure about this code: https://github.com/geonetwork/core-geonetwork/blob/master/schemas/iso19139/src/main/java/org/fao/geonet/schema/iso19139/ISO19139SchemaPlugin.java#L461-L465
Maybe requires some updates in the pull request to deal with the elements that could require processing in previous code.
=> Adding datasets to a service metadata and saving the metadata corrupts the service metadata #3283

core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java, es/es-core/src/main/java/org/fao/geonet/es/EsClient.java, es/utility/skos2essynonyms.xsl, pom.xml, schemas/dublin-core/src/main/plugin/dublin-core/index-fields/index.xsl, schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl, web-ui/src/main/resources/catalog/templates/editor/accessManager.html, web/src/main/webapp/xslt/common/index-utils.xsl
* Fix DC indexing on link
* Better JSON encoding of object types
* Add utility to create a synonym map for ES config from thesaurus
* Better usage of analysis API
=> ES / More robust indexing and update to ES6.4.2

core/pom.xml, core/src/main/java/org/fao/geonet/kernel/MetadataIndexerProcessor.java, core/src/main/java/org/fao/geonet/security/AdminUserFilter.java, core/src/main/java/org/fao/geonet/security/AuthenticathedUserFilter.java, core/src/main/resources/config-spring-geonetwork.xml, pom.xml, services/pom.xml, services/src/main/java/org/fao/geonet/api/records/MetadataIndexApi.java, services/src/main/java/org/fao/geonet/services/metadata/BatchOpsMetadataReindexer.java, services/src/test/java/org/fao/geonet/services/metadata/BatchOpsMetadatReindexerTest.java, web-ui/src/main/resources/catalog/components/admin/index/IndexingTaskDirective.js, web-ui/src/main/resources/catalog/components/admin/index/IndexingTaskModule.js, web-ui/src/main/resources/catalog/components/admin/index/partials/indexingstatus.html, web-ui/src/main/resources/catalog/components/admin/index/partials/indexingstatuscontainer.html, web-ui/src/main/resources/catalog/js/GnModule.js, web-ui/src/main/resources/catalog/locales/en-core.json, web-ui/src/main/resources/catalog/style/gn.less, web-ui/src/main/resources/catalog/templates/admin/dashboard/status.html, web/pom.xml, web/src/main/resources/jolokia-access.xml, web/src/main/webResources/WEB-INF/web.xml, web/src/main/webapp/WEB-INF/config-security/config-security-core.xml, web/src/main/webapp/WEB-INF/config-spring-geonetwork-parent.xml
This PR adds a widget to render the status of running indexing tasks.
Currently the widget is added in Admin console > Status, see:
Two directives are added:
* `IndexingTasksContainer`: will request the backend for running tasks and display one bar for each
* `IndexingTaskStatusInfo` : will render a progress bar & text for one running task
Cancelling a task might be added in the future. Also this currently does not show the status of a compelte rebuild done with `admin.index.rebuild`.
=> Indexing / Show status of running tasks

web-ui/src/main/resources/catalog/components/search/searchmanager/LocationService.js, web-ui/src/main/resources/catalog/js/edit/EditorBoardController.js, web-ui/src/main/resources/catalog/templates/editor/editorboard.html
To be able to create direct link to a set of records. This is useful for catalogues using workflow which needs to link to records by status with appropriate facets for example.
=> Editor board / Init search based on URL 

web/src/main/webapp/WEB-INF/data/config/codelist/external/thesauri/place/regions.rdf
See http://publications.europa.eu/code/en/en-370100.htm
=> Thesaurus / Czech Republic geographical short name is now Czechia

core/src/test/java/org/fao/geonet/kernel/search/LuceneQueryTest.java
=> Fixing tests for #3262

web-ui/src/main/resources/catalog/components/common/map/mapsManager.js
* Fixes #2569. Set up projections from `ui/config` setting in the angular`run` phase, making it available before any map is created by `createMap`function.
* fixjsstyle for `mapsManager.js`
=> Load projection definitions before creating maps

web-ui/src/main/resources/catalog/components/common/map/mapService.js, web-ui/src/main/resources/catalog/components/common/ows/OWSService.js, web-ui/src/main/resources/catalog/locales/en-core.json
ie. Unauthorized.
Currently the message only explains that something is wrong with the capabilities.
=> Map / Specific error message for GetCapabilities returning 401 

services/src/main/java/org/fao/geonet/api/processing/XslProcessUtils.java
It adds a new feature, if don't want to merge is ok, but the code has changes from `master` due to `DataManager` refactor and it's useful to have the pull request to merge at least manually in projects using 3.4.x.
=> Utility method to change metadata schema identifier

core/src/main/java/org/fao/geonet/kernel/setting/Settings.java, core/src/main/java/org/fao/geonet/listeners/history/GenericMetadataEventListener.java, domain/src/main/java/org/fao/geonet/domain/utils/ObjectJSONUtils.java, services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java, services/src/main/java/org/fao/geonet/api/records/MetadataSampleApi.java, services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java, services/src/main/java/org/fao/geonet/api/records/MetadataTagApi.java, services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java, web-ui/src/main/resources/catalog/locales/en-admin.json, web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql, web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v350/migrate-default.sql
Added setting to disable event recording.
To merge in https://github.com/geonetwork/core-geonetwork/pull/3209
=> WIP - Feature/record events and tasks # 5

web-ui/src/main/resources/catalog/components/metadatamanager/EditorService.js, web-ui/src/main/resources/catalog/js/edit/EditorController.js
Backport of Resolve behaviour of add button in editor (#3013).
=> [BP] Resolve behaviour of add button in editor #3010

schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
=> ISO19139 / Formatter / Advanced view / Display link on keyword using Anchor

web-ui/src/main/resources/catalog/components/search/mdview/mdviewModule.js, web-ui/src/main/resources/catalog/components/search/searchmanager/LocationService.js
Currently does nothing. 
Issue introduced by https://github.com/geonetwork/core-geonetwork/pull/3197. Some cleanup.
=> Fix back to search button. 

web-ui/src/main/resources/catalog/components/edit/datepicker/DatePickerDirective.js
Moment parsing format was wrong for date.
=> Editor / Month date / When saving year is reset to current year

pom.xml
See https://github.com/geonetwork/core-geonetwork/issues/3307
Unless someone has a better fix ?
=> UI CSS Config / When updated, the config can't take effect because WRO4J reload model API is not available

domain/src/main/java/org/fao/geonet/repository/MetadataStatusRepositoryImpl.java, web-ui/src/main/resources/catalog/components/history/GnHistoryDirective.js, web-ui/src/main/resources/catalog/components/history/partials/historyStep.html, web-ui/src/main/resources/catalog/components/history/partials/recordHistory.html
* Fix when user is not yet set (errors only in non debug mode). 
* Fix when no type are set, search return many times the same status due to missing join in query. 
* Display type filters even when no result.
=> Record history and tasks / Misc fix

web-ui/src/main/resources/catalog/js/admin/ThesaurusController.js
=> Broken Thesaurus page in the admin #3436

web-ui/src/main/resources/catalog/components/history/GnHistoryDirective.js, web-ui/src/main/resources/catalog/components/history/partials/historyStep.html, web-ui/src/main/resources/catalog/views/default/directives/directive.js, web-ui/src/main/resources/catalog/views/default/directives/partials/mdactionmenu.html
A task may be present but not visible due to invalid configuration. For example, DOI task can not be proposed if the DOI API is not configured.
Also improve the DOI creation task:
Added doc for DOI https://github.com/geonetwork/doc/blob/develop/source/user-guide/associating-resources/doi.rst
=> Tasks / Add configuration to define if a task is visible or not.

web-ui/src/main/resources/catalog/components/search/formfields/partials/schemainfocombo.html
See https://github.com/geonetwork/core-geonetwork/blob/master/schemas/iso19139/src/main/plugin/iso19139/loc/eng/codelists.xml#L27-L32
=> Editor / Codelist / Hide in edit mode when configured

web-ui/src/main/resources/catalog/style/gn_search.less, web/src/main/webapp/xslt/base-layout.xsl, web/src/main/webapp/xslt/common/render-html.xsl, web/src/main/webapp/xslt/skin/default/skin.xsl
Same as https://github.com/geonetwork/core-geonetwork/pull/3234 with the changes requested.
=> No JS mode / update html-only header/footer to match more closely the ng-header.

web-ui/src/main/resources/catalog/js/CatController.js
=> Language selector is not displayed 

web-ui/src/main/resources/catalog/js/edit/BatchEditController.js
Related to https://github.com/geonetwork/core-geonetwork/pull/3418
=> Batch editor / Display all type of updates when selection is too big

web-ui/src/main/resources/catalog/js/admin/UserGroupController.js
Change required due to changes in 109dd0b1806e32dbd1ec5394c9fd8a17ab88fab0
=> Metadata editor - empty category entry in Categories menu. Fixes #3479

services/src/main/java/org/fao/geonet/api/reports/ReportUtils.java, web-ui/src/main/resources/catalog/js/admin/AdminController.js, web-ui/src/main/resources/catalog/js/admin/ReportController.js
Administration summary page for User administrators:
Reports page displaying user groups only for User administrators:
=> Administration menu fixes for UserAdmin profile. Fixes #3486

services/src/main/java/org/fao/geonet/api/groups/GroupsApi.java, services/src/test/java/org/fao/geonet/api/groups/GroupsApiTest.java
* Fix test
* Check associated users.
Related to https://github.com/geonetwork/core-geonetwork/pull/3476
=> User administrator can delete his own group #2391

web-ui/src/main/resources/catalog/components/common/ows/OWSService.js, web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
=> Editor / Associated resource / List WMS layer group having name

web-ui/src/main/resources/catalog/components/edit/datepicker/partials/datepicker.html, web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/linktosibling.html, web-ui/src/main/resources/catalog/components/search/formfields/FormFieldsDirective.js
=> Editor / Associated resources / Indicate that association type is mandatory

web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/linktosibling.html
Currently the class is added but the button can be clicked.
=> Associated resource / Sibling / Disable button

schemas/iso19139/src/main/plugin/iso19139/index-fields/default.xsl, web-ui/src/main/resources/catalog/locales/en-search.json
Reordering JSON.
* on top
* label not translated
=> ISO19139 / Other keyword should be displayed in last position in the record view

web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
Add 'text-wrap' class to button aiming to wrap text
=> Wrap text on button

web-ui/src/main/resources/catalog/components/edit/directoryentryselector/partials/directoryentryselector.html, web-ui/src/main/resources/catalog/components/edit/recordfragmentselector/partials/rfselector.html
=> ui - change tt-dropdown-menu to tt-menu

core/src/main/java/org/fao/geonet/constants/Geonet.java, core/src/main/java/org/fao/geonet/kernel/DataManager.java, core/src/main/java/org/fao/geonet/kernel/datamanager/IMetadataUtils.java, core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataUtils.java, inspire-atom/src/main/java/org/fao/geonet/inspireatom/util/InspireAtomUtil.java, inspire-atom/src/main/java/org/fao/geonet/services/inspireatom/AtomPredefinedFeed.java, inspire-atom/src/main/java/org/fao/geonet/services/inspireatom/AtomSearch.java, schemas/iso19139/src/main/plugin/iso19139/convert/ATOM/inspire-atom-feed.xsl, schemas/iso19139/src/main/plugin/iso19139/extract-default-language.xsl, schemas/iso19139/src/main/plugin/iso19139/index-fields/default.xsl, schemas/iso19139/src/main/plugin/iso19139/index-fields/language-default.xsl, schemas/iso19139/src/main/plugin/iso19139/loc/eng/labels.xml, web/src/main/webResources/WEB-INF/urlrewrite.xml, web/src/main/webapp/WEB-INF/config-security/config-security-mapping.xml, web/src/main/webapp/xslt/services/inspire-atom/opensearchdescription.xsl
This PR is an update to latest `master` of https://github.com/geonetwork/core-geonetwork/pull/2308. Please check it fo the full documentation about fixes/improvements included. 
Hopefully having it updated to `master` help others also to test it. Current implementation of local feeds have some problems, like https://github.com/geonetwork/core-geonetwork/issues/3348, that should be solved in this PR.
@fgravin , @etj and @gvandeboel any test/feedback for the updated code would be really appreciated, thanks.
=> Inspire atom opensearch fixes

web-ui/src/main/resources/catalog/locales/en-admin.json, web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html
=> Admin / User / Add info on how to add an avatar. Fix alignement.

web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js
=> Improve visualisation of projection if codespace is undefined

web-ui/src/main/resources/catalog/components/category/CategoryDirective.js, web-ui/src/main/resources/catalog/components/category/partials/batchcategory.html, web-ui/src/main/resources/catalog/components/common/popup/PopupService.js, web-ui/src/main/resources/catalog/components/common/share/ShareDirective.js, web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js, web-ui/src/main/resources/catalog/components/utility/UtilityService.js, web-ui/src/main/resources/catalog/locales/en-core.json
See original message and the report displayed with the change in https://github.com/geonetwork/core-geonetwork/issues/3613
=> Batch actions in editor dashboard or search UI doesn't show the result report #3613

web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js
Fixes #3607.
Backport of #3609.
=> [BP] Improve visualisation of projection if codespace is undefined (#3609)

web-ui/src/main/resources/catalog/views/default/directives/partials/periodchooser.html
To test, try to set the value directly using the input
=> Search / Advanced form / Dates not updated when using input directly

events/Readme.md
Up till now there were issues with events and transactions. Not anymore.
=> Better documentation on how to use database listeners

web-ui/src/main/resources/catalog/components/edit/topiccategory/TopicCategoryDirective.js
Eg. required for iso19115-3.2018
=> Editor / Topic Category / Support extension of non ISO19139 standards

integration-test/pom.xml, pom.xml, schemas/csw-record/pom.xml, schemas/dublin-core/pom.xml, schemas/iso19110/pom.xml, schemas/iso19139/pom.xml, schemas/pom.xml, schemas/schema-core/pom.xml
Currently, the version in pom.xml for schemas is 3.5. This PR changes to 3.7.
=> Align schema version in pom.xml for master

web-ui/src/main/resources/catalog/js/admin/UserGroupController.js
Depends on how fast user is initialized. So it happens randomly.
=> Admin / User / User admin can see all groups

web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
=> ISO19115-3 / Add thumbnail does not work because of wrong parameter name

schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-tpl.xsl, schemas/iso19139/src/main/plugin/iso19139/layout/layout.xsl, web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
=> Editor / Tabled mode / Elements children of an xlink must be disabled.

web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js, web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionsDirective.js
=> Transfer ownership / Display report at the end of the process.

core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataIndexer.java
Check that the metadata status added to the index is of workflow type
=> [BUG] Index metadata status is only workflow type

web-ui/src/main/resources/catalog/js/edit/EditorBoardController.js, web-ui/src/main/resources/catalog/templates/editor/editorboard.html
Fix:
* my record only filter require double click and was reset in some cases (due to location changes)
* when reset, reset according to config.
Cf. https://github.com/geonetwork/core-geonetwork/issues/3612
=> Editor board / Fix only my record filter affected by location changes.

web-ui/src/main/resources/catalog/js/edit/EditorBoardController.js, web-ui/src/main/resources/catalog/templates/editor/editorboard.html
* Editor board / Fix only my record filter affected by location changes.
* Editor board / Reset my record only based on config.
* Code style.
Backport of #3644
=> [BP] Editor board / Fix only my record filter affected by location changes

pom.xml
[CVE-2016-1000031](https://nvd.nist.gov/vuln/detail/CVE-2016-1000031)
=> Upgrade commons-fileupload to 1.3.3

pom.xml
CVE-2018-19361
CVE-2018-19362
CVE-2018-19360
=> Upgrade jackson dependencies to 2.9.8

web/src/main/webapp/xslt/services/sitemap/sitemap.xsl
Backport of https://github.com/geonetwork/core-geonetwork/pull/3723
=> [BP 3.6.x] - 3723 - Use correct siteURL in sitemap urls

web/src/main/webapp/xslt/services/sitemap/sitemap.xsl
=> [BP 3.4.x] - 3723 - Use correct siteURL in sitemap urlsUse correct siteURL in sitemap urls (#3723)

web-ui/src/main/resources/catalog/style/gn.less, web-ui/src/main/resources/catalog/templates/top-toolbar.html, web-ui/src/main/resources/catalog/views/default/less/gn_navbar_default.less, web-ui/src/main/resources/catalog/views/default/templates/footer.html
A11y upgrade for Header and Footer:
- added `aria-role="menuitem"` to the nav bar
- more colour contrast to meet requirements
- removed `Google +`
=> A11y upgrade for the header and footer

web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid.html, web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/list.html, web-ui/src/main/resources/catalog/components/viewer/owscontext/partials/owscontext.html, web-ui/src/main/resources/catalog/style/gn_search.less, web-ui/src/main/resources/catalog/views/default/directives/partials/linksbtn.html, web-ui/src/main/resources/catalog/views/default/less/gn_results_default.less, web-ui/src/main/resources/catalog/views/default/less/gn_search_default.less, web-ui/src/main/resources/catalog/views/default/less/gn_variables_default.less, web-ui/src/main/resources/catalog/views/default/templates/home.html, web-ui/src/main/resources/catalog/views/default/templates/recordView.html
A11y upgrade:
- added `aria-roles`
- more colour contrast
- added background colours
- changed aria roles
=> A11y upgrade for the Search Result and Detail page

services/src/test/java/org/fao/geonet/services/metadata/schema/SchematronCriteriaTypeServiceTest.java
Fixes tests failing since #3692.
=> Fixes test for additional criteria type

web/src/test/java/v370/UserCustomSearchesMigrationTest.java
Settings path was changed, but not updated the migration test.
=> Fix migration test for user searches

workers/wfsfeature-harvester/src/main/java/org/fao/geonet/harvester/wfsfeatures/worker/EsWFSFeatureIndexer.java
Stripped CDATA element before tokenizing.
=> WFS Feature indexer / Tokenized field may contains CDATA

web-ui/src/main/resources/catalog/components/common/map/print/partials/printmap.html, web-ui/src/main/resources/catalog/components/search/map/partials/mapfield.html, web-ui/src/main/resources/catalog/components/viewer/wmsimport/partials/kmlimport.html, web-ui/src/main/resources/catalog/views/default/less/gn_map_default.less, web-ui/src/main/resources/catalog/views/default/templates/results.html
A11y upgrade for main map and mini map:
- more colour contrast for disabled elements
- changed toggle button (include text in button for better colour contrast)
- changed class for the upload button
- added `aria-labels`
=> A11y upgrade for main Map and mini Map

web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql
=> Settings / DOI / Move to the bottom

web-ui/src/main/resources/catalog/components/usersearches/partials/featuredusersearchesbutton.html, web-ui/src/main/resources/catalog/views/default/templates/searchForm.html
Implement change suggested by Michel (https://github.com/geonetwork/core-geonetwork/pull/3778#issuecomment-490482376)
=> User search / Improve button layout.

schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
Content info section contains relevant information to display in default view.
=> ISO19139 / Default view / Add content info section

web-ui/src/main/resources/catalog/components/usersearches/UserSearchesDirective.js, web-ui/src/main/resources/catalog/components/usersearches/partials/featuredusersearchesbutton.html
=> User searches / Sort list by label.

web-ui/src/main/resources/catalog/components/viewer/wmsimport/WmsImportDirective.js, web-ui/src/main/resources/catalog/components/viewer/wmsimport/partials/wmsimport.html
In the map, shows the list of Preferred OGC services defined in `config/ui` in the
list of available services in the "Add layer from" -> "Services" -> "Choose a service"  map tool.
=> Shows the list of Preferred OGC services in Add layer dialog

services/src/main/java/org/fao/geonet/api/users/UsersApi.java, web-ui/src/main/resources/catalog/components/search/searchmanager/partials/searchresults.html, web-ui/src/main/resources/catalog/js/admin/UserGroupController.js, web-ui/src/main/resources/catalog/style/gn.less, web-ui/src/main/resources/catalog/style/gn_editor.less
* Improve error message by listing affecting records
* Highlight all types of records including templates and subtemplates
=> User / Delete / When user own some records and can't be deleted, report records owned by the user in the error message

services/src/main/java/org/fao/geonet/api/records/InspireValidationApi.java, services/src/main/java/org/fao/geonet/api/records/editing/InspireValidatorUtils.java, services/src/test/java/org/fao/geonet/api/records/editing/InspireValidatorUtilsTest.java
This should fix this one https://github.com/geonetwork/core-geonetwork/issues/2874
=> Fix for Inspire validator behind a proxy

web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionsDirective.js, web-ui/src/main/resources/catalog/components/metadataactions/partials/transferownership.html
Backport of #3809 to 3.6.x branch
=> Improvements in transfer ownership dialog usability

schemas/iso19139/src/main/java/org/fao/geonet/schema/iso19139/ISO19139SchemaPlugin.java
This may be used when substituting elements by their matching XLinks. In such case, the XLink must contains an ordered list of language codes. This is used in geocat.ch.
=> ISO19139 / Add utility function to retrieve list of languages

csw-server/src/main/java/org/fao/geonet/component/csw/Transaction.java
A rewording of https://github.com/geonetwork/core-geonetwork/pull/3747. The CSW client can choose if the db change date needs to be modified or not by updating the date stamp in the record.
DB changedate is synchronized with record datestamp.
=> CSW-T / Update db changedate based on record datestamp.

web-ui/src/main/resources/catalog/components/common/needhelp/NeedHelpDirective.js, web-ui/src/main/resources/catalog/locales/en-core.json
Currently german version of the doc is not accessible.
=> Documentation / Test doc page exist and if not redirect to english

services/src/main/java/org/fao/geonet/guiapi/search/SearchApi.java, web-ui/src/main/resources/catalog/style/gn_search.less, web/src/main/webapp/xslt/common/functions-core.xsl, web/src/main/webapp/xslt/skin/default/skin.xsl
if a record has no hierarchylevel, consider it as dataset
fix /{node}/search url
optimise latout of no-js search page
=> some improvements for no-js search engines

web-ui/src/main/resources/catalog/locales/de-core.json, web-ui/src/main/resources/catalog/locales/de-search.json
Title says it all. Thanks for any review
=> Fix spelling of Objektartenkatalog

web-ui/src/main/resources/catalog/components/common/map/mapService.js
fixes #3887 
problem occurs on this wmts
https://geodata.nationaalgeoregister.nl/luchtfoto/rgb/wmts?request=GetCapabilities&service=WMTS
=> fixes loading of wmts, if wmts layer has no style object

schemas/iso19139/src/main/plugin/iso19139/extract-relations.xsl
gmd:protocol may contain a gmx:Anchor
=> Add support for anchors in protocol

web-ui/src/main/resources/catalog/views/default/templates/recordView.html
Same as https://github.com/geonetwork/core-geonetwork/pull/3870 but with no conflict ?
=> Remove double slash

core/src/main/java/org/fao/geonet/lib/ResourceLib.java, services/src/main/java/org/fao/geonet/api/ApiUtils.java, services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
@fxprunayre , can you please have a look ?
=> Housekeeping insert delete api

core/src/main/java/org/fao/geonet/constants/Geonet.java, core/src/main/java/org/fao/geonet/kernel/search/SearchManager.java, core/src/main/java/org/fao/geonet/kernel/search/spatial/SpatialIndexWriter.java, core/src/main/java/org/fao/geonet/util/GMLParsers.java, core/src/main/java/org/fao/geonet/util/XslUtil.java, services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java, services/src/main/java/org/fao/geonet/api/regions/metadata/MetadataRegionSearchRequest.java, services/src/main/java/org/fao/geonet/services/region/MetadataRegionDAO.java
This is for iso19115-3.2018 but also for other gml/3.2.x schemas such as apiso 19139 support
=> Add gml/3.2 support to metadata polygon indexing

web/src/main/webResources/WEB-INF/config-spring-geonetwork.xml
We may improve that for Ifremer soon. Adding the option to populate & synchronize the cache for all public records.
=> Formatter / Turn off initialization of the cache causing NPE on startup.

web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
=> Editor / Label above mode / Size full width the date component.

web-ui/src/main/resources/catalog/components/common/map/mapService.js
Ignore invalid geometries in mapService
=> feat(bbox) deal with invalid bbox geoms from md

web/src/main/webapp/xsl/conversion/import/ISO19115-3-2014-to-ISO19115-3-2018.xsl, web/src/main/webapp/xsl/conversion/import/ISO19139-to-ISO19115-3-2018.xsl
Add XSL for importing from 19115-3.2014 and 19139.
=> ISO19115-3 / Add import conversion

web-ui/src/main/resources/catalog/components/thesaurus/ThesaurusDirective.js
Switching from one to all lang, reset input to the initial value.
=> Editor / Field with autocompletion / Multilingual record 

core/src/test/java/org/fao/geonet/kernel/datamanager/DraftMetadataUtilsTest.java, services/src/test/java/org/fao/geonet/api/usersearches/UserSearchesApiTest.java
* User searches / missing portal parameter
* Draft / Too large uuid
Let's see if travis is fine with this and then please merge @josegar74
=> Test / Fix 

web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html, web-ui/src/main/resources/catalog/components/common/savedselections/SavedSelectionsDirective.js, web-ui/src/main/resources/catalog/components/common/savedselections/partials/action.html, web-ui/src/main/resources/catalog/components/common/savedselections/partials/panel.html, web-ui/src/main/resources/catalog/js/CatController.js, web-ui/src/main/resources/catalog/locales/en-admin.json
To enable or not saved selections from UI settings:
=> UI config / Add option to enable or not saved selections.

schemas/iso19139/src/main/plugin/iso19139/loc/eng/labels.xml, schemas/iso19139/src/main/plugin/iso19139/loc/fre/labels.xml, web-ui/src/main/resources/catalog/components/metadatamanager/EditorXMLService.js
* Required for INSPIRE TG2
* Better description of the link with a title
* Better support of profiles (with fallback to ISO19139)
=> ISO19139 / CRS / Encode using Anchor.

web/src/main/webapp/WEB-INF/classes/schematron/iso_svrl_for_xslt2.xsl
=> [BP] Fix error when sch:assert/@see attribute contains a URL

web-ui/src/main/resources/catalog/templates/admin/settings/logo.html
to be able to use find-on-page, if the catalog has many logo's
=> in logo management add logo name as header

services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
Related to https://github.com/geonetwork/core-geonetwork/commit/ecd979c1c1933ac36c505125661991f0925925f4#r34412515
=> Privileges / Avoid NPE if status is not yet set

services/src/main/java/org/fao/geonet/api/records/MetadataApi.java, web-ui/src/main/resources/catalog/components/search/mdview/mdviewService.js
Currently angular view is based on the search response content and does
not trigger increment of the popularity.
=> Record view / Angular view increase popularity.

domain/src/main/java/org/fao/geonet/domain/ServiceParam.java, services/src/main/java/org/fao/geonet/api/csw/VirtualCswApi.java, web-ui/src/main/resources/catalog/js/admin/CSWVirtualController.js
* JS errors
* CSW virtual service deleted on filter removed #3826
* virtual csw filter not always saved #3814
=> Virtual CSW / Misc fix

web-ui/src/main/resources/catalog/style/gn_admin.less, web-ui/src/main/resources/catalog/templates/admin/dashboard/record-links.html
especially for display when firefox.
@fxprunayre @jahow  ?
=> improve url checker table layout

web/src/main/webapp/xslt/ui-metadata/menu-builder.xsl
Related to https://github.com/geonetwork/core-geonetwork/commit/0659cb157e0fdd9bef8438fbe9ee705bb0ef830b#r34803923
=> Directory manager / Fix menu appearing below the form

web-ui/src/main/resources/catalog/components/common/map/print/partials/printmap.html, web-ui/src/main/resources/catalog/locales/en-search.json
Stuff lost in Sextant history...
@fgravin please review and squash & merge if fine. Thanks
=> Map / Print / Translate layout

core/src/main/java/org/geonetwork/map/wms/SLDUtil.java, core/src/test/java/org/geonetwork/map/wms/SLDUtilTest.java, services/src/main/java/org/fao/geonet/api/sld/SldApi.java
Remove the use of geotools WebMapServer class which handles a call to a getCapabilities. Is now faster.
Stuff lost in Sextant history...
=> WFS harvester / SLD / Send GetStyle request with direct httpClient

schemas/config-editor.xsd
=> Editor / Documentation / How to customize associated panel list of link types ?

core/src/test/resources/org/fao/geonet/kernel/valid-metadata.iso19139.xml
Error 
```
[INFO] Running org.fao.geonet.kernel.AllThesaurusTest
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.041 s <<< FAILURE! - in org.fao.geonet.XmlValidationTest
[ERROR] testBasicValidation(org.fao.geonet.XmlValidationTest)  Time elapsed: 2.998 s  <<< FAILURE!
java.lang.AssertionError
at org.fao.geonet.XmlValidationTest.testBasicValidation(XmlValidationTest.java:53)
```
Related to https://github.com/geonetwork/core-geonetwork/pull/3920
=> Test / Fix XmlValidationTest

services/src/test/java/org/fao/geonet/services/thesaurus/GetKeywordByIdTest.java, web-ui/src/main/resources/catalog/views/default/less/gn_view.less
Comment test error on less compilation.
=> Test / More robust in case the default are not the one expected

services/src/main/java/org/fao/geonet/api/records/formatters/cache/FilesystemStore.java
cf. https://github.com/geonetwork/core-geonetwork/issues/3992
=> Thread leak in api.records.formatters.cache.FilesystemStore

web/src/main/webResources/WEB-INF/urlrewrite.xml
Fix for https://github.com/geonetwork/core-geonetwork/issues/3984
=> API / Documentation / Redirect to default index.html

csw-server/src/main/java/org/fao/geonet/component/csw/GetCapabilities.java, services/src/main/java/org/fao/geonet/api/site/SiteApi.java, services/src/main/java/org/fao/geonet/guiservices/csw/Get.java, services/src/main/java/org/fao/geonet/guiservices/csw/Set2.java, services/src/main/java/org/fao/geonet/guiservices/csw/customelementset/Get.java, services/src/main/java/org/fao/geonet/guiservices/csw/customelementset/Set.java
* Replace the short name by the correct translation if available.
* Replace portal name in CSW GetCapabilities title
* Fix CSW configuration (currently returning HTTP500 - broken by multinode removal)
=> Portal / Set name depending on language in header and CSW capabilities

web-ui/src/main/resources/catalog/js/admin/AdminToolsController.js, web-ui/src/main/resources/catalog/js/admin/ReportController.js
This PR adds an icon in the tools menu and changes icons in the report menu.
**Old tools menu**
**New menu**
**Old report menu**
**New menu**
=> Added or changed menu icons in the admin sidebar

harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet20/Geonet20Harvester.java
Currently broken due to wrong XmlRequest initialization. 
Can be tested with https://metadados.ana.gov.br/geonetwork
=> Harvester / GeoNetwork 2.x / Fix

web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html
=> Add more compact interface in the UI config when main field is disabled

web-ui/src/main/resources/catalog/js/CatController.js, web-ui/src/main/resources/catalog/locales/en-admin.json, web-ui/src/main/resources/catalog/views/default/templates/index.html
=> Add settings footer

services/src/main/java/org/fao/geonet/api/processing/XslProcessApi.java, services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
Proposal: Only produce JSON for processing reports
Related to https://github.com/geonetwork/core-geonetwork/issues/3996
=> API / Xsl process reports are only returned as JSON (#3996).

csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/SearchController.java
=> if nextrecord=numrecords, nextrecord should not be set to 0

csw-server/src/main/java/org/fao/geonet/kernel/csw/services/getrecords/SearchController.java
Backport of PR #4052. Fix #4040 in 3.6.x branch.
=> [BP] CSW harverster if count=numrecords, nextrecord should not be 0

web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v390/migrate-default.sql
See https://github.com/geonetwork/core-geonetwork/pull/4077
=> SQL /  Migration / Set source types

core/src/main/java/org/fao/geonet/kernel/url/UrlChecker.java, core/src/main/java/org/fao/geonet/util/XslUtil.java
=> URL Checker / Mutualise with XSL call eg. schematron and consider http 404 on HEAD as 405

web-ui/src/main/resources/catalog/components/common/needhelp/NeedHelpDirective.js
=> Documentation links are wrong in 3.8.1

web/src/main/webapp/xslt/ui-search/portal-list.xsl
=> Portal list / Fix link to main catalogue

harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Harvester.java, web-ui/src/main/resources/catalog/components/common/map/mapDirective.js, web-ui/src/main/resources/catalog/js/admin/HarvestSettingsController.js, web-ui/src/main/resources/catalog/style/gn.less, web-ui/src/main/resources/catalog/style/gn_editor.less, web-ui/src/main/resources/catalog/templates/admin/harvest/type/csw.html, web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
A bounding box filter is available if a `BBOX` spatial operator is declared in the GetCapabilities.
=> Harvester / CSW / Bbox filter.

web-ui/src/main/resources/catalog/components/admin/harvester/partials/identification.html, web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
Related to https://github.com/geonetwork/core-geonetwork/pull/4038
=> Warn user if harvester is already taken on harvester creation only

web-ui/src/main/resources/catalog/components/common/share/ShareService.js, web/src/main/webapp/WEB-INF/classes/setup/sql/data/loc-fre-default.sql
Requested in https://github.com/georchestra/georchestra/issues/2791
=> Sharing / Change public state logo to unlock to be consistent with other UI. Improve french translations.

web-ui/src/main/resources/catalog/style/gn_pickers.less
Fix for https://github.com/geonetwork/core-geonetwork/pull/4044/files#r338396828
Before
After
=> CSS / Fix timeline missing dependency

web-ui/src/main/resources/catalog/components/common/multiselect/MultiselectDirective.js, web-ui/src/main/resources/catalog/components/common/multiselect/partials/multiselect.html, web-ui/src/main/resources/catalog/js/admin/UserGroupController.js, web-ui/src/main/resources/catalog/templates/admin/usergroup/groups.html
=> Admin / Alpha order for group list in group managment and multiselect.

web-ui/src/main/resources/catalog/locales/en-editor.json
=> i18n / Missing key

web-ui/src/main/resources/catalog/components/viewer/localisation/LocalisationDirective.js, web-ui/src/main/resources/catalog/components/viewer/localisation/partials/localisation.html
=> Gazetteer checkbox in user interface settings is not respected

web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcService.js
Fix for https://github.com/geonetwork/core-geonetwork/issues/4062
=> Editor / Online resource / Removal is broken

schemas/iso19139/src/main/plugin/iso19139/loc/fre/strings.xml
Missing/incorrect translations
=> ISO 19139  / Update a couple of FR strings

web-ui/src/main/resources/catalog/components/viewer/gfi/FeaturesLoader.js
Linky directive may create invalid link if a full HTTP
URL is provided with character like ")" in the URL
which will be considered as text separator (eg. Kibana link with filters).
After the change, when an attribute contains a full HTTP link, the link is created directly instead of parsing URL in text:
=> Map / Feature info / Bad link

pom.xml, web-ui/src/main/resources/catalog/components/common/map/print/partials/print.html, web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js, web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html, web-ui/src/main/resources/catalog/locales/en-search.json, web/src/main/webapp/WEB-INF/config-print/print-config.yaml
relates to https://github.com/geonetwork/core-geonetwork/issues/3615
=> Editor / Thumbnail creation fails due to PDF box update and conflict with mapfish print

services/src/main/java/org/fao/geonet/api/processing/XslProcessApi.java, services/src/main/java/org/fao/geonet/api/processing/XslProcessUtils.java, services/src/main/java/org/fao/geonet/api/records/MetadataProcessApi.java, services/src/main/java/org/fao/geonet/services/metadata/XslProcessing.java, services/src/main/java/org/fao/geonet/services/resources/RemoveAndProcess.java, services/src/main/java/org/fao/geonet/services/resources/UploadAndProcess.java
Similar to https://github.com/geonetwork/core-geonetwork/pull/3767
=> API / Processing / XSL / Add parameter to update or not datestamp

web-ui/src/main/resources/catalog/locales/ca-core.json, web-ui/src/main/resources/catalog/locales/cs-core.json, web-ui/src/main/resources/catalog/locales/de-core.json, web-ui/src/main/resources/catalog/locales/en-admin.json, web-ui/src/main/resources/catalog/locales/en-core.json, web-ui/src/main/resources/catalog/locales/es-core.json, web-ui/src/main/resources/catalog/locales/fi-core.json, web-ui/src/main/resources/catalog/locales/fr-core.json, web-ui/src/main/resources/catalog/locales/is-core.json, web-ui/src/main/resources/catalog/locales/it-core.json, web-ui/src/main/resources/catalog/locales/ko-core.json, web-ui/src/main/resources/catalog/locales/nl-core.json, web-ui/src/main/resources/catalog/locales/pt-core.json, web-ui/src/main/resources/catalog/locales/ru-core.json, web-ui/src/main/resources/catalog/locales/sk-core.json, web-ui/src/main/resources/catalog/views/default/templates/recordView.html
Fixed some typos (unknow and cance)
removed duplicate entries (metadata/pdfReport/headerRight-help) in en-admin.json
=> Fixed some typos and duplicates

core/src/main/java/org/fao/geonet/constants/Geonet.java, core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataIndexer.java, web-ui/src/main/resources/catalog/locales/en-core.json, web-ui/src/main/resources/catalog/templates/editor/directory.html, web/src/main/webapp/WEB-INF/config-lucene.xml, web/src/main/webapp/WEB-INF/config-summary.xml
Facet added to:
* editor board
* directory board
Cleaning:
* Removing ref to `_ownername` dump field which does not exist in master.
=> Facet / Add record owner name to easily search by username.

web-ui/src/main/resources/catalog/components/search/formfields/FormFieldsDirective.js
=> trigger query changed even if query stay '' when selected or cleared

schemas/iso19139/src/main/plugin/iso19139/convert/ATOM/iso19119ToAtomFeed.xsl, schemas/iso19139/src/main/plugin/iso19139/extract-relations.xsl, schemas/iso19139/src/main/plugin/iso19139/index-fields/language-default.xsl
According to INSPIRE applicationProfile is an Anchor. This changes handles applicationProfile in a neutral way, so it can be both CharacterString and Anchor
=> ISO19139 / Support for applicationProfile as anchor

services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
Fixes the bug where UserAdmin is not allowed to publish records due to a wrong check.
=> Fix check on permissions

web-ui/src/main/resources/catalog/js/admin/UserGroupController.js
Issue introduced with Admin / User / User admin can see all groups #3641
=> Admin / User / List not loaded in non debug mode

web-ui/src/main/resources/catalog/templates/admin/classification/categories.html, web-ui/src/main/resources/catalog/templates/admin/harvest/harvest-settings.html, web-ui/src/main/resources/catalog/templates/admin/settings/csw-virtual.html, web-ui/src/main/resources/catalog/templates/admin/settings/csw.html, web-ui/src/main/resources/catalog/templates/admin/settings/mapservers.html, web-ui/src/main/resources/catalog/templates/admin/settings/sources.html, web-ui/src/main/resources/catalog/templates/admin/settings/system.html, web-ui/src/main/resources/catalog/templates/admin/settings/ui.html, web-ui/src/main/resources/catalog/templates/admin/usergroup/groups.html, web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html, web-ui/src/main/resources/catalog/templates/editor/batchedit.html, web-ui/src/main/resources/catalog/templates/editor/import.html, web-ui/src/main/resources/catalog/templates/editor/new-metadata-horizontal.html, web-ui/src/main/resources/catalog/templates/editor/new-metadata-vertical.html
Add links for editor and admin apps:
* sub-portal
* batch-editing
* doi
* inspire
* mapserver config
* workflow
* user self registration
* csw
* ui
* new/import record
Make rendering of the button more consistent across pages.
=> Documentation / Add link when a page exist in the doc

schemas/config-editor.xsd
as suggested in https://github.com/geonetwork/doc/pull/91
=> move documentation of fields to config-editor.xsd

web/src/main/webapp/xslt/services/thesaurus/registry-to-skos.xsl
Also keep definition if title is forced.
=> Registry / Add spatial scope date

web/src/main/webapp/loc/ara/xml/strings.xml, web/src/main/webapp/loc/cat/xml/strings.xml, web/src/main/webapp/loc/chi/xml/strings.xml, web/src/main/webapp/loc/dut/xml/strings.xml, web/src/main/webapp/loc/eng/xml/strings.xml, web/src/main/webapp/loc/fin/xml/strings.xml, web/src/main/webapp/loc/fre/xml/strings.xml, web/src/main/webapp/loc/ger/xml/strings.xml, web/src/main/webapp/loc/ita/xml/strings.xml, web/src/main/webapp/loc/nor/xml/strings.xml, web/src/main/webapp/loc/pol/xml/strings.xml, web/src/main/webapp/loc/por/xml/strings.xml, web/src/main/webapp/loc/rus/xml/strings.xml, web/src/main/webapp/loc/spa/xml/strings.xml, web/src/main/webapp/loc/tur/xml/strings.xml, web/src/main/webapp/xslt/services/pdf/metadata-fop.xsl
Work supported by https://www.apur.org/
=> Search results / PDF / Add access and use constraints information

schemas/iso19139/src/main/plugin/iso19139/index-fields/default.xsl, web-ui/src/main/resources/catalog/components/catalog/CatalogService.js, web-ui/src/main/resources/catalog/components/search/mdview/mdviewDirective.js, web-ui/src/main/resources/catalog/components/search/mdview/partials/contact.html
Added for ISO19139 and 115-3.
Work supported by https://apur.org
=> Record view / Add contact website.

web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less, web-ui/src/main/resources/catalog/views/default/less/gn_map_default.less
Uniform styling for the OpenLayers attribution in all the maps
=> Fix for OpenLayers attribution styling

core/src/test/java/org/fao/geonet/kernel/url/LinkPresenterTest.java, domain/src/main/java/org/fao/geonet/domain/LinkStatus.java
@fxprunayre can you please have a look ?
=> DB / JPA / Avoid trouble with jpa model gen (setter needs to be camel case)

web-ui/src/main/resources/catalog/components/common/map/mapService.js, web-ui/src/main/resources/catalog/components/common/map/print/PrintDirective.js, web-ui/src/main/resources/catalog/components/common/map/print/PrintMapDirective.js, web-ui/src/main/resources/catalog/components/common/ows/OWSService.js, web-ui/src/main/resources/catalog/components/viewer/ViewerModule.js, web-ui/src/main/resources/catalog/components/viewer/gfi/GetFeatureInfoDirective.js, web-ui/src/main/resources/catalog/style/gn_viewer.less, web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less, web-ui/src/main/resources/catalog/views/default/less/gn_map_default.less, web-ui/src/main/resources/catalog/views/default/less/gn_search_default.less, web-ui/src/main/resources/catalog/views/default/less/gn_view.less
=> Openlayers update (part2)

core/src/main/java/org/fao/geonet/kernel/mef/MEF2Exporter.java
Probably introduced by https://github.com/geonetwork/core-geonetwork/commit/fb0ecfbc479cf36360cb11cf287b89e4a43a5dd9
=> MEF Export / Remove duplicates on each record

web-ui/src/main/resources/catalog/components/viewer/partials/mainviewer.html, web-ui/src/main/resources/catalog/style/gn_search.less, web-ui/src/main/resources/catalog/style/gn_viewer.less
This is merely a rework of https://github.com/geonetwork/core-geonetwork/pull/4273 with cleaner history & fix to make sure the icon does not change anymore (since the badge now indicates which mode we're in now).
This is ready to be merged. @MichelGabriel do you approve? Thanks
=> Extra badge indicating the 2D/3D view setting (redone)

web/src/main/webResources/WEB-INF/urlrewrite.xml
Fix the link we have in editor > associated resource panel
=> URL rewrite / Main landing page for /metadata

web-ui/src/main/resources/catalog/components/search/facets/partials/facet-multiselect.html
=> check if translation is ready using oneway binding

web/src/main/webapp/xml/csw/capabilities_inspire.xml
=> Inspire CSW is not valid XML 

core/src/main/java/org/fao/geonet/kernel/url/UrlChecker.java
@fxprunayre , @josegar74 , please
=> url checker, set timeout when ftp check, also when http get (oups)

schemas/iso19139/src/main/plugin/iso19139/formatter/jsonld/iso19139-to-jsonld.xsl
=> add only single license (and fill it with array of otherconstraints)

core/src/main/java/org/fao/geonet/kernel/datamanager/draft/DraftMetadataManager.java
partially fixes  #4240 (i guess considering current technology, there not many alternatives)
=> improve delete draft first message

services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
Avoid printing a further comma after the last value listed in CSV export function
=> remove the last comma

web-ui/src/main/resources/catalog/components/catalog/CatalogService.js
Cause issue mainly when opening thumbnail in a modal.
=> Thumbnails / A record may have only one.

core/src/main/java/org/fao/geonet/kernel/search/facet/ItemConfig.java, core/src/main/java/org/fao/geonet/spring/xml/ItemBeanDefinitionParser.java, core/src/main/resources/schemas/gn-spring.xsd, services/src/main/java/org/fao/geonet/services/search/FacetsService.java, web-ui/src/main/resources/catalog/components/search/facets/FacetDimensionDirective.js, web-ui/src/main/resources/catalog/components/search/facets/partials/dimension-facet-category.html, web-ui/src/main/resources/catalog/components/search/facets/partials/dimension-facet-list.html, web-ui/src/main/resources/catalog/locales/en-core.json, web-ui/src/main/resources/catalog/locales/en-search.json, web-ui/src/main/resources/catalog/locales/fr-core.json, web-ui/src/main/resources/catalog/style/gn_search.less, web/src/main/webapp/WEB-INF/config-summary.xml
```
diff --git a/web/src/main/webapp/WEB-INF/config-summary.xml b/web/src/main/webapp/WEB-INF/config-summary.xml
index 33beaed22c..574b76cb2d 100644
--- a/web/src/main/webapp/WEB-INF/config-summary.xml
+++ b/web/src/main/webapp/WEB-INF/config-summary.xml
@@ -139,7 +139,7 @@
translator="term:http://inspire.ec.europa.eu/theme"/>
-      <item facet="keyword" max="15"/>
+      <item facet="keyword" max="15" pageSize="3"/>
<item facet="orgName" max="25"/>
<item facet="sourceCatalog"
translator="db:org.fao.geonet.repository.SourceRepository:findOneByUuid"/>
```
will allow such a display:
=> Search facets that paginate

schemas/config-editor.xsd, schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-tpl.xsl, web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
=> Editor / Table column / Add support for directive.

web-ui/src/main/resources/catalog/js/admin/HarvestSettingsController.js, web-ui/src/main/resources/catalog/templates/admin/harvest/type/csw.html, web-ui/src/main/resources/catalog/templates/admin/harvest/type/csw.js
* Fix not saving other queriables introduced in https://github.com/geonetwork/core-geonetwork/pull/4247
* Fix coordinate reset when switching from one harvester to another one.
=> Harvesting / CSW / Fix saving of all types of parameters

web-ui/src/main/resources/catalog/components/catalog/CatalogService.js
=> Record view / Spatial representation type can contain multiple values

web-ui/src/main/resources/catalog/components/search/mdview/mdviewModule.js, web-ui/src/main/resources/catalog/views/default/templates/recordView.html
=> Record view / Disable current view in view switcher menu.

core/src/main/java/org/fao/geonet/resources/Resources.java, web/src/main/java/org/fao/geonet/Geonetwork.java
@pvalsecc , I'm not sure about what the change should be in case of s3 for the GeoNetwork startup logo init ?
Related to https://github.com/geonetwork/core-geonetwork/pull/4248
=> Logo / Fix copy op when starting the app, creating a portal or an harvester

harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/GeonetHarvester.java, web-ui/src/main/resources/catalog/js/admin/SourcesController.js, web-ui/src/main/resources/catalog/templates/admin/settings/sources.html
Some catalogues can have lots of harvesters and portals, add the possibility to filter list by type
=> Admin / Sources / Add filter by type of sources.

common/src/main/java/org/fao/geonet/exceptions/UnknownHostEx.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java
Current error message:
New error message:
=> Improve CSW harvester error message when the host is not valid

core/src/main/java/org/fao/geonet/kernel/Thesaurus.java
=> Added dcterms:title to source thesaurus title for rdf:Description element

services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
See https://github.com/geonetwork/core-geonetwork/pull/4248/files#r367951795
=> Fix metadata creation when template is not downloadable by current user

core/src/main/java/org/fao/geonet/constants/Geonet.java, core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataIndexer.java, web-ui/src/main/resources/catalog/components/utility/partials/typeinspirevalidationwidget.html, web-ui/src/main/resources/catalog/components/validationtools/GnmdInspireValidationDirective.js, web-ui/src/main/resources/catalog/components/validationtools/partials/mdValidationTools.html, web-ui/src/main/resources/catalog/locales/en-core.json, web/src/main/webapp/WEB-INF/config-lucene.xml
* Add date info to know when record was validated
* Add the last validation status to the menu in the editor
=> INSPIRE validation / Add last validation state.

web-ui/src/main/resources/catalog/locales/en-search.json
=> Fix typo in en-search.json

core/src/main/java/org/fao/geonet/kernel/datamanager/draft/DraftMetadataUtils.java, core/src/test/java/org/fao/geonet/kernel/datamanager/DraftMetadataUtilsTest.java, services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java, services/src/main/java/org/fao/geonet/api/status/StatusApi.java
* Do not create a draft is workflow is off
* Add API to delete record status
* Add API to delete all
Fix for #4369
=> Editor / Record becomes draft even with workflow disabled 

schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
=> ISO19139 / Citation / Date is last publication or revision date

web-ui/src/main/resources/catalog/js/admin/SourcesController.js
Currently only logo from the list can be selected.
=> Portal / Upload logo when one is added

web-ui/src/main/resources/WEB-INF/classes/web-ui-wro-sources.xml, web-ui/src/main/resources/catalog/components/common/openlayers/olProfileDirective.js, web-ui/src/main/resources/catalog/lib/closure/base.js
Adds missing closure methods used in openlayers directives
=> Add missing Closure functions

.gitignore, domain/src/main/java/org/fao/geonet/domain/HarvestHistory.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java, web-ui/src/main/resources/catalog/components/utility/UtilityModule.js, web-ui/src/main/resources/catalog/templates/admin/harvest/harvest-settings.html
See ticket: https://github.com/geonetwork/core-geonetwork/issues/3832
=> Address glitch with duplicate or missing logfiles

.gitignore, domain/src/main/java/org/fao/geonet/domain/HarvestHistory.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractHarvester.java, web-ui/src/main/resources/catalog/components/utility/UtilityModule.js, web-ui/src/main/resources/catalog/templates/admin/harvest/harvest-settings.html
* In some scenario service returns array of log files, take first.
* Check before creating conflicting logfile history.
* Verify logfile is available before reporting to user interface.
* Make window.encodeURIComponent available as filter.
Fix #3832.
Backport of #4432
=> [BP] Address glitch with duplicate or missing logfiles

web-ui/src/main/resources/catalog/lib/closure/base.js
=> chore(closure) add missing listen_ function

core/src/main/java/org/fao/geonet/kernel/mef/MEF2Exporter.java, core/src/main/java/org/fao/geonet/kernel/mef/MEFLib.java
Fix for https://github.com/geonetwork/core-geonetwork/issues/4425
=> MEF / Avoid exception when user do not have download privileges.

web-ui/src/main/resources/catalog/components/filestore/FileStoreService.js, web-ui/src/main/resources/catalog/components/filestore/partials/filestore.html
Also fix JS exception.
Currently filesystem store does not display any resources and visibility of files can't be updated.
=> Attachements / type is now visibility and values are uppercase on GET.

harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java
GeoNetwork type harvester create the metadata directory structure in GeoNetwork data directory even if the remote metadata doesn't have `public` or `private` folders. This can make the filesystem run out of inodes with very large catalogues.
This commit only creates the directory tree structure for the metadata record if the importe metadata has `public` or `private` files.
Since `3.10.x` versions this is already done by `FilesystemStore`: 
https://github.com/geonetwork/core-geonetwork/blob/9ca80e08d6ad29cc74bda17d5aa645cd73df1381/core/src/main/java/org/fao/geonet/api/records/attachments/FilesystemStore.java#L229
Called from 
https://github.com/geonetwork/core-geonetwork/blob/b0cc2729437427ab3bdf89ef4add0b7bac555448/harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Al …
=> Only create metadata data folder when needed (GN harvester)

harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java
GeoNetwork type harvester create the metadata directory structure in GeoNetwork data directory
even if the remote metadata doesn't have public or private folders. This can make the
filesystem run out of inodes with very large catalogues.
This commit only creates the directory tree structure for the metadata record if the imported
metadata has public or private files.
Since 3.10.x versions this is already done by FilesystemStore:
https://github.com/geonetwork/core-geonetwork/blob/3.10.x/core/src/main/java/org/fao/geonet/api/records/attachments/FilesystemStore.java#L229
Backport of #4437.
=> [BP] Only create metadata data folder when needed

web-ui/src/main/resources/catalog/components/common/needhelp/NeedHelpDirective.js
See https://github.com/geonetwork/core-geonetwork/issues/4426
=> Help / Link to trunk

harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/Aligner.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/oaipmh/Harvester.java, services/src/main/java/org/fao/geonet/api/records/formatters/FormatterApi.java, web-ui/src/main/resources/catalog/components/admin/harvester/partials/extras.html
Replace https://github.com/geonetwork/core-geonetwork/pull/4452 + fix when locale is not english.
=> PDF / Print polygon extent when record is not public

web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-variables.xsl
Refer https://github.com/metadata101/iso19115-3/issues/41
=> Default display of citation proposal to off

core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java
Fixes https://github.com/geonetwork/core-geonetwork/issues/4476
=> Set datainfo root when creating metadata from a template

web-ui/src/main/resources/catalog/components/viewer/wps/partials/processform.html
=> chore: use map projection for input geometry

web-ui/src/main/resources/catalog/components/edit/fieldduration/FieldDurationDirective.js, web-ui/src/main/resources/catalog/components/edit/fieldduration/partials/fieldduration.html, web-ui/src/main/resources/catalog/js/GnSearchModule.js
Display a duration in view mode 
Related to https://github.com/metadata101/iso19115-3.2018/pull/55
=> Period duration / Add readonly mode.

schemas/iso19139/src/main/plugin/iso19139/oasis-catalog.xml
=> Update iso19139 oasis-catalog.xml references to 2007 schema files. Fixes apiso.xsd issue described in #3836

core/src/main/java/org/fao/geonet/MergeUsersByUsernameDatabaseMigration.java
Fix for https://github.com/geonetwork/core-geonetwork/pull/2480/files#r390797822
=> DB / Migration / MergeUsersByUsernameDatabaseMigration / Flush deletion before inserting new merged user

web-ui/src/main/resources/catalog/components/edit/editorhelper/EditorHelperDirective.js
I noticed that there were two typos in this file.
This PR changes the "O" (capital OH) into "0" (zero).
=> change Oh to Zero

web-ui/src/main/resources/catalog/style/gn.less, web-ui/src/main/resources/catalog/templates/top-toolbar.html
Truncate the username, so a very long username doesn't break the UI.
Fix for https://github.com/geonetwork/core-geonetwork/issues/4517
=> Fix #4517 Truncate the username

web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
A form with hundreds of contact was terribly slow.
Same as https://github.com/geonetwork/core-geonetwork/pull/4409
=> Editor / Init country autocomplete only on focus

core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataIndexer.java
Delete all works on a database created by hibernate (because some foreign constraints are missing.
See https://github.com/geonetwork/core-geonetwork/issues/1863).
Delete all does not work on older database where operationAllowed contains references to the metadata table.
So delete one by one even if slower for now.
```sql
SELECT count(*) FROM operationallowed WHERE metadataId NOT IN (SELECT id FROM metadata);
```
may return more than 0.
=> Harvester / Delete associated records does not work when FK exists

web-ui/src/main/resources/catalog/components/edit/multilingualfield/MultilingualFieldDirective.js, web-ui/src/main/resources/catalog/components/edit/multilingualfield/partials/multilingualfield.html
This is a back-port of https://github.com/geonetwork/core-geonetwork/pull/4549 to 3.10.x
=> change order of nav-pills in multilingual fields (#4549)

schemas/iso19139/src/main/plugin/iso19139/update-fixed-info.xsl
This is a backport of https://github.com/geonetwork/core-geonetwork/pull/4562
=> backport 3.10.x -- fix multilingual save issue

web-ui/src/main/resources/catalog/locales/en-admin.json, web-ui/src/main/resources/catalog/templates/admin/settings/sources.html
=> Portal / Add info with a link to the portal and its CSW endpoint.

web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html, web-ui/src/main/resources/catalog/locales/en-admin.json
Fixes https://github.com/geonetwork/core-geonetwork/issues/4539
=> Admin / UI config / Download formatter support

schemas/iso19139/src/main/plugin/iso19139/convert/functions.xsl, schemas/iso19139/src/main/plugin/iso19139/extract-relations.xsl, schemas/iso19139/src/main/plugin/iso19139/layout/utility-tpl-multilingual.xsl, schemas/iso19139/src/main/plugin/iso19139/present/metadata-edit.xsl, schemas/iso19139/src/main/plugin/iso19139/present/metadata-utils.xsl, schemas/iso19139/src/main/plugin/iso19139/present/metadata-view.xsl, schemas/iso19139/src/main/plugin/iso19139/present/metadata.xsl, schemas/iso19139/src/main/plugin/iso19139/update-fixed-info.xsl
Re-Submission of #4207 with code cleaned up and squashed commits.
=> iso19139 / Add better support for gmd:language containing gmd:LanguageCode and gco:CharacterString (#2)

core/src/main/java/org/fao/geonet/api/records/attachments/S3Store.java, core/src/main/java/org/fao/geonet/resources/S3Credentials.java, core/src/main/java/org/fao/geonet/resources/S3Resources.java
While working on the jcloud implementation of the file store, which is based on the S3 implementation,  I came across a few bug that seem to affect the S3 implementation as well so I'm submitting a pull request with the suggested fix.
Note: I don't have access to AWS S3 account so I was not able to test this to make sure it work.
If possible maybe @pvalsecc may be able to test these changes
=> AWS S3 storage bug fix

core/src/main/java/jeeves/server/context/BasicContext.java
…
Same as https://github.com/geonetwork/core-geonetwork/pull/4553/files
=> Multi portal mode / getNodeId may be triggered outside a request scope (eg. harvesting)

web-ui/src/main/resources/catalog/components/userfeedback/GnmdFeedbackDirective.js
Introduced in https://github.com/geonetwork/core-geonetwork/blob/master/web-ui/src/main/resources/catalog/components/userfeedback/GnmdFeedbackDirective.js
=> User feedback / Fix JS error on init.

schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
Access http://localhost:8080/geonetwork/srv/api/records/78f93047-74f8-4419-ac3d-fc62e4b0477b
Before
After
=> Formatter / ISO19139 / Fix layout when email is here

web-ui/src/main/resources/catalog/js/edit/EditorController.js
following of f4af1e33394393fa94ae4ba898260a05d017555b
=> error message are now json, no need to convert them from xml

web-ui/src/main/resources/catalog/js/admin/HarvestSettingsController.js
Wait until a harvester ID is returned from create API call to send the activate call.
Fix #4004.
=> Create harvester with schedule it's stored as inactive

web-ui/src/main/resources/catalog/components/edit/FieldsModule.js, web-ui/src/main/resources/catalog/components/edit/multientrycombiner/MultiEntryCombiner.js, web-ui/src/main/resources/catalog/components/edit/multientrycombiner/partials/multientrycombiner.html
This adds a new editing directive.
See the .js documentation for details.
This requires https://github.com/geonetwork/core-geonetwork/pull/4596
=> add multientrycombiner directive

core/src/main/java/org/fao/geonet/util/XslUtil.java
Similar to https://github.com/geonetwork/core-geonetwork/pull/4578
=> Multi portal mode / getNodeId may be triggered outside a request scope (eg. formatter in background process)

web-ui/src/main/resources/catalog/style/gn_search.less
=> ES/Fix - Allow ellipsis in dropdown-menu button (mtd links)

core/src/main/java/org/fao/geonet/kernel/mef/Importer.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFilesystemHarvester.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFsHarvesterFileVisitor.java, pom.xml, web-ui/src/main/resources/catalog/components/admin/harvester/partials/extras.html, web-ui/src/main/resources/catalog/templates/admin/harvest/type/filesystem.js
UUID collision options for Directory type harvester. 
Fix #4006.
=> UUID collision options for Directory type harvester

web-ui/src/main/resources/catalog/components/edit/multientrycombiner/MultiEntryCombiner.js, web-ui/src/main/resources/catalog/components/edit/multientrycombiner/partials/multientrycombiner.html
This makes a few improvement to the Multi Entry Combiner.
a) allow a "defaultValue" section to set defaults
b) remove trailing un-specified values ("Government of Canada; ;" --> "Government of Canada")
=> improve Multi Entry Combiner

web-ui/src/main/resources/catalog/templates/signin.html, web-ui/src/main/resources/catalog/templates/top-toolbar.html
Fix display of the login form, broken by wrong check added in https://github.com/geonetwork/core-geonetwork/pull/4633
=> Fix login form display caused by https://github.com/geonetwork/core-geonetwork/pull/4633

web-ui/src/main/resources/catalog/components/edit/multientrycombiner/partials/multientrycombiner.html
Getting things aligned better with the other editors.
=> minor layout changes to multi entry combiner

web-ui/src/main/resources/catalog/components/edit/multientrycombiner/partials/multientrycombiner.html
Backport of https://github.com/geonetwork/core-geonetwork/pull/4652 to 3.10.x
=> [BP] minor layout changes to multi entry combiner (#4652)

web/src/main/webapp/loc/por/xml/i18n.xml
File i18n.xml was missing for the Portuguese language. Copied from English and translated it.
=> Added missing i18n file for por language

pom.xml, web/src/main/webResources/WEB-INF/config-node/srv.xml
Fix regression bug from #4644 
Was not able to set db_type to connect to other databases due to ${db.type} not being passed correctly.
=> Fix bug with connecting to databases other than h2

core/src/main/java/org/fao/geonet/kernel/datamanager/IMetadataUtils.java, core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataUtils.java, core/src/main/java/org/fao/geonet/kernel/datamanager/draft/DraftMetadataUtils.java, listeners/src/main/java/org/fao/geonet/listener/metadata/draft/DraftUtilities.java, web/src/main/webResources/WEB-INF/config-spring-geonetwork.xml
- Use IMetadataUtils interface in DraftUtilities
- Improve the documentation for the beans that require disabling / enabling.
=> Draft beans fixes to work fine when disabled

web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html, web-ui/src/main/resources/catalog/components/search/mdview/mdviewDirective.js, web-ui/src/main/resources/catalog/js/CatController.js, web-ui/src/main/resources/catalog/locales/en-v4.json
=> UI Config / Add more like this query configuration.

core/src/main/java/org/fao/geonet/kernel/AccessManager.java
It also aligns with the UI criteria that allows only administrators and reviewers of the metadata owner group:
https://github.com/geonetwork/core-geonetwork/blob/2a4d2132da922850beada4e2f6f0e9909ece1627/web-ui/src/main/resources/catalog/views/default/directives/partials/mdactionmenu.html#L31-L32
Additional refactoring to extract the code to check if the user is authenticated.
=> Update review permissions check to verify if the user is reviewer in the metadata groups owner, instead of checking the edit privilege. Fixes #4589

web/src/main/webapp/WEB-INF/data/data/formatter/xslt/render-layout.xsl
This link redirect to the angular app with all interactions availables - add to map, related resources, ....
=> Landing page / Display link to the portal by default.

services/src/main/java/org/fao/geonet/api/processing/XslProcessUtils.java
Related to https://github.com/geonetwork/core-geonetwork/commit/6dc42f6aa3f862fd569eb1fa53f61db6815e1105
=> Process / Fix missing thesaurusDir variable required by some processes.

web-ui/src/main/resources/catalog/templates/admin/harvest/type/oaipmh.html, web-ui/src/main/resources/catalog/templates/admin/harvest/type/oaipmh.js
The harvester already has the ability to validate the records on import.
=> Add validation option to OAI-PMH harvester UI

core/src/main/java/org/fao/geonet/kernel/url/UrlChecker.java, core/src/main/java/org/fao/geonet/util/XslUtil.java, core/src/main/resources/config-spring-geonetwork.xml, domain/src/main/java/org/fao/geonet/domain/LinkStatus.java, web/src/main/webResources/WEB-INF/config.properties, web/src/test/java/org/fao/geonet/kernel/schema/TestIso19139SchematronDefinition.java, web/src/test/resources/http-request-factory-context.xml
cf. https://github.com/geonetwork/core-geonetwork/issues/4304
A) It now configures a proxy (including hostname filtering)
B) the user agent was changed to "GeoNetwork Link Checker". (cf https://github.com/geonetwork/core-geonetwork/issues/4677)
=> add proxy for UrlChecker and change UserAgent

web-ui/src/main/resources/catalog/components/common/alert/partials/alert.html, web-ui/src/main/resources/catalog/js/edit/EditorController.js, web-ui/src/main/resources/catalog/js/edit/NewMetadataController.js
add a notification if editor fails to open
fix notification if create metadata fails
improves #3948
=> fix the display of some error messages on alerts

domain/src/main/java/org/fao/geonet/domain/HarvestHistory.java, web/src/main/webapp/WEB-INF/classes/log4j-dev.xml, web/src/main/webapp/WEB-INF/classes/log4j-index.xml, web/src/main/webapp/WEB-INF/classes/log4j-search.xml, web/src/main/webapp/WEB-INF/classes/log4j.xml
Following discussion here https://github.com/geonetwork/core-geonetwork/commit/50307396f572e73bc128dca50253c0530beb85f4#commitcomment-39781602
=> Harvester / When log file is missing, log message at debug level.

web-ui/src/main/resources/catalog/components/viewer/geometry/GeometryService.js
Similar to https://github.com/geonetwork/core-geonetwork/pull/4673
=> Map editor / use map promise to add the vector layer

web-ui/src/main/resources/catalog/components/viewer/wmsimport/WmsImportDirective.js
fixes #4395, adds notification when layer loaded successfully
=> add notification if layer was added

web-ui/src/main/resources/catalog/components/common/alert/partials/alert.html, web-ui/src/main/resources/catalog/components/viewer/wmsimport/WmsImportDirective.js
fixes comment from @josegar74 at #4395
=> present layer message as html

core/src/main/java/org/fao/geonet/kernel/Thesaurus.java, core/src/test/resources/org/fao/geonet/kernel/search/templated-keyword.iso19139.xml, schemas-test/src/test/resources/iso19139/descriptiveKeywordsUpdateFixedInfo.xml, schemas/iso19139/doc/tpl.xml, schemas/iso19139/src/main/plugin/iso19139/convert/dcat.xsl, schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml, schemas/iso19139/src/main/plugin/iso19139/present/csw/dcat-brief.xsl, schemas/iso19139/src/main/plugin/iso19139/templates/inspire_sds.xml, web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v3990/migrate-default.sql, web/src/main/webapp/WEB-INF/config-security/config-security-mapping.xml, web/src/main/webapp/xslt/services/dcat/rdf.xsl
Fix the thesaurus download link
=> Thesaurus download now use API.

services/src/main/java/org/fao/geonet/api/es/EsHTTPProxy.java, web-ui/src/main/resources/catalog/components/elasticsearch/EsClient.js, web-ui/src/main/resources/catalog/components/elasticsearch/EsFacet.js, web-ui/src/main/resources/catalog/components/elasticsearch/directives/FacetDirective.js, web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facets.html, web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js, web-ui/src/main/resources/catalog/js/CatController.js
```json
"dateStamp" : {
'userHasRole': 'isReviewerOrMore',
```
=> ES / Facet / Add configuration to display facet based on user profile. 

domain/src/main/java/org/fao/geonet/domain/Translations.java, schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl, services/src/main/java/org/fao/geonet/api/es/EsHTTPProxy.java, services/src/main/java/org/fao/geonet/api/records/CatalogApi.java, web-ui/src/main/resources/catalog/js/GnLocale.js, web-ui/src/main/resources/catalog/views/default/templates/recordView.html, web/src/main/webapp/xslt/services/pdf/metadata-fop.xsl
* Record view / Display temporal extent.
* Do not display anchor for keywords, only link to.
* DB translations can override transifex ones
* ZIP, PDF & CSV export improvements
* PDF / Fix missing labels depending on language
=> ES / Record view improvements and translation override

core/src/main/java/org/fao/geonet/kernel/GeonetworkDataDirectory.java, core/src/main/java/org/fao/geonet/resources/ResourceFilter.java
* Create image folder if not exist
* Create logo folder if not exist
* Properly copy harvesting logos
* Do not rely on a GN3.png which may not exist. Default image is the
site id logo.
Replace https://github.com/geonetwork/core-geonetwork/pull/4867
=> Data directory / Improve initialization

core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java, schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl, schemas/iso19139/src/main/plugin/iso19139/update-fixed-info.xsl, services/src/main/java/org/fao/geonet/api/records/MetadataUtils.java, web-ui/src/main/resources/catalog/js/edit/NewMetadataController.js, web/src/main/webapp/xslt/services/metadata/relation.xsl
* Fix source link
* Fix service/dataset link
* Migrate support of remote operatesOn indexing (also ported to 19115-3) - Fix error when only xlink:href is present
* Fix brotherAndSister link
=> ES / Associated record

web/src/main/webapp/xslt/common/index-utils.xsl
=> Index field which are not ISO based.

web-ui/src/main/resources/catalog/js/edit/AccessManagerController.js, web-ui/src/main/resources/catalog/locales/en-editor.json, web-ui/src/main/resources/catalog/locales/en-v4.json, web-ui/src/main/resources/catalog/templates/editor/accessManager.html
=> Editor board / Access manager / Use search API instead of proxy.

web-ui/src/main/resources/catalog/js/CatController.js, web-ui/src/main/resources/catalog/views/default/templates/home.html
* Fix suggestion.
* Improve config for facet with more examples.
* Score : boost down obsolete records.
=> ES / Home page improvements

web/src/main/webapp/xslt/common/base-variables.xsl, web/src/main/webapp/xslt/skin/default/skin.xsl
* Ensure a language is defined. Default to `eng`. 
* Fix setting location in formatter case
=> ES / Landing page / Fix links.

core/src/main/java/org/fao/geonet/api/records/attachments/AbstractStore.java, services/src/main/java/org/fao/geonet/api/mapservers/MapServersApi.java, services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
Fixed typo with the attachment text.
=> Fixed typo with attachment

web-ui/src/main/resources/catalog/js/edit/EditorBoardController.js
Related to https://github.com/geonetwork/core-geonetwork/issues/4897
=> Editor / Turn off hotkeys while editing

web-ui/src/main/resources/catalog/components/common/popup/PopupService.js
Fixes https://github.com/geonetwork/core-geonetwork/issues/4888
Unless you have a better fix ?
=> Editor / Directory / Add contact breaks scrolling

web-ui/src/main/resources/catalog/views/default/templates/recordView.html
=> Record view / Keyword / Link may be undefined or empty.

schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl, web-ui/src/main/resources/catalog/locales/en-v4.json, web-ui/src/main/resources/catalog/views/default/templates/recordView.html
ISO19115-3 support done in https://github.com/metadata101/iso19115-3.2018/pull/83
=> Index / Add keyword not related to thesaurus.

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/jsonld/iso19115-3.2018-to-jsonld.xsl, schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl, schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/fre/codelists.xml, schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/update-fixed-info.xsl
which were not part of https://github.com/geonetwork/core-geonetwork/pull/4701.
=> ISO19115-3 / Merge latest changes made in metadata101 

core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java, core/src/main/java/org/fao/geonet/kernel/search/IndexFields.java, services/src/main/java/org/fao/geonet/api/site/SiteApi.java, web-ui/src/main/resources/catalog/components/elasticsearch/EsFacet.js, web-ui/src/main/resources/catalog/js/admin/DashboardStatusController.js, web-ui/src/main/resources/catalog/templates/admin/dashboard/status.html, web/src/main/webapp/xslt/common/index-utils.xsl
Fix:
* failure detection due to ES API change
* indexing error on aggregates in some documents.
* search for indexing error due to draft filter
=> API / Add index and db count. 

core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java, services/src/main/java/org/fao/geonet/api/related/Related.java, web-ui/src/main/resources/catalog/components/elasticsearch/EsFacet.js, web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facets.html, web-ui/src/main/resources/catalog/components/metadataactions/RelatedDirective.js, web-ui/src/main/resources/catalog/components/search/resultsview/gridRelated.js, web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid.html, web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/list.html, web-ui/src/main/resources/catalog/components/search/searchfiltertag/partials/searchFilterTagsTemplate.html, web-ui/src/main/resources/catalog/components/usersearches/partials/usersearchespanel.html, web-ui/src/main/resources/catalog/js/CatController.js, web-ui/src/main/resources/catalog/locales/en-v4.json, web-ui/src/main/resources/catalog/style/gn_search.less, web-ui/src/main/resources/catalog/style/inspire/iti-i18n-code.css, web-ui/src/main/resources/catalog/templates/editor/editorboard.html, web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less, web-ui/src/main/resources/catalog/views/default/less/gn_facets_default.less, web-ui/src/main/resources/catalog/views/default/less/gn_results_default.less, web-ui/src/main/resources/catalog/views/default/less/gn_search_default.less, web-ui/src/main/resources/catalog/views/default/templates/gridRelatedList.html, web-ui/src/main/resources/catalog/views/default/templates/home.html, web-ui/src/main/resources/catalog/views/default/templates/results.html, web-ui/src/main/resources/catalog/views/default/templates/searchForm.html, web/src/test/java/org/fao/geonet/wro4j/Wro4jJsCssCompilationTest.java
* We now have 3 records per row, so adapt records per page to be multiple of 3
* Search results footer / Remove duplicated pager and replace by scroll to top (only displayed in more than 3 lines of results)
* Active filter / Reset button is only accessible from one place once one filter is set
* Facet / Consistent icons for collapse all and collapse one facet
* Font / Facet and filter now are consistent (same size, same background) and aligned
* Align filter & search results tools
* Align search box & search results
* Move admin search management box to top level (in full text search row) - only for authenticated user and if enabled
* Grid & list are using same basic principles (grey header, background change on hover, same button), Editor board use same principles too
* List mode display …
=> Search / UI improvements

web-ui/src/main/resources/catalog/components/admin/registry/RegistryDirective.js
Avoid mixed content error on https site.
=> INSPIRE / Registry is now available on https

harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/ogcwxs/Harvester.java, schemas/iso19139/src/main/plugin/iso19139/convert/OGCWxSGetCapabilitiesto19119/OGCWMTGetCapabilities-to-ISO19119_ISO19139.xsl, schemas/iso19139/src/main/plugin/iso19139/convert/OGCWxSGetCapabilitiesto19119/OGCWMTGetCapabilitiesLayer-to-19139.xsl, schemas/iso19139/src/main/plugin/iso19139/convert/OGCWxSGetCapabilitiesto19119/OGCWxSGetCapabilities-to-19119.xsl, schemas/iso19139/src/main/plugin/iso19139/convert/OGCWxSGetCapabilitiesto19119/OGCWxSGetCapabilitiesLayer-to-19139.xsl, schemas/iso19139/src/main/plugin/iso19139/convert/OGCWxSGetCapabilitiesto19119/identification.xsl, schemas/iso19139/src/main/plugin/iso19139/convert/OGCWxSGetCapabilitiesto19119/resp-party.xsl, web-ui/src/main/resources/catalog/templates/admin/harvest/type/ogcwxs.html
Create service and dataset metadata based on Capabilities information.
Tested with http://tiles.craig.fr/ortho/service?service=WMTS&request=GetCapabilities and https://tiles.emodnet-bathymetry.eu/wmts/1.0.0/WMTSCapabilities.xml
Also
* Fix missing gco:CharacterString on protocol
* Improve options in configuration panel (template selection only when supported, thumbnail option only when supported).
=> Harvester / OGC WxS / Add WMTS basic support

web/pom.xml
This is a small change to make it easier to follow and debug.
=> Preserve lastmodified during copy-schemas-ant target

core/src/main/java/org/fao/geonet/web/LocaleRedirects.java
Related to JPA migration
https://github.com/geonetwork/core-geonetwork/commit/d29e9483467d5a7668bce7287ae60de1003d218c#diff-1eb8228a295daf160dfacda89e478fedR173
=> Redirect / Fix portal redirect

web-ui/src/main/resources/catalog/js/admin/HarvestSettingsController.js, web-ui/src/main/resources/catalog/templates/admin/harvest/type/ogcwxs.html
Fixes https://github.com/geonetwork/core-geonetwork/issues/4850
=> Harvester / OGC WxS / Migrate template list to use ES search. 

web-ui/src/main/resources/catalog/components/edit/geopublisher/GeoPublisherDirective.js
Use editor map.
Fixes https://github.com/geonetwork/core-geonetwork/issues/3788
=> Editor / GeoPublisher / Fix map init

web-ui/src/main/resources/catalog/style/gn_editor.less
=> Editor / Table head label font size consistent with others

web-ui/src/main/resources/catalog/components/userfeedback/partials/mdFeedback.html, web-ui/src/main/resources/catalog/components/userfeedback/partials/userfeedback.html, web-ui/src/main/resources/catalog/components/userfeedback/partials/userfeedbackfull.html, web-ui/src/main/resources/catalog/components/userfeedback/partials/userfeedbacklasthome.html, web-ui/src/main/resources/catalog/components/userfeedback/partials/userfeedbacknew.html, web-ui/src/main/resources/catalog/locales/en-search.json, web-ui/src/main/resources/catalog/views/default/less/gn_feedback_default.less
This PR adds improvements to the accessibility (a11y) of the user feedback options and screens:
- added aria-labels
- removed collapsing panels
- order of headings
=> [a11y] Improvements to the accessibility of the user feedback options and screens

web-ui/src/main/resources/catalog/components/common/map/print/partials/printmap.html, web-ui/src/main/resources/catalog/components/viewer/draw/partials/draw.html, web-ui/src/main/resources/catalog/components/viewer/layermanager/partials/layermanageritem.html, web-ui/src/main/resources/catalog/components/viewer/legendpanel/partials/legendpanel.html, web-ui/src/main/resources/catalog/components/viewer/owscontext/partials/owscontext.html, web-ui/src/main/resources/catalog/components/viewer/wmsimport/WmsImportDirective.js, web-ui/src/main/resources/catalog/views/default/less/gn_map_default.less, web-ui/src/main/resources/catalog/views/default/templates/results.html
This PR improves the accessibility of elements on the map panels:
- added aria labels
- grouped inputs
- improved link styles
=> [a11y] Improved accessibility of map panels

web-ui/src/main/resources/catalog/js/GnLocale.js, web-ui/src/main/resources/catalog/js/GnSchemaTranslationsLoaderModule.js
Related to https://github.com/geonetwork/core-geonetwork/pull/4631
* Formatting
* Add cache to not reload already available files
This may help not having partially translated UI.
Before
After
=> Locale / Avoid double loading.

schemas/iso19139/src/main/plugin/iso19139/update-fixed-info-keywords.xsl
If a record contains keyword not attached to any thesaurus in different blocks, then they are combined by type.
```xml
<gmd:descriptiveKeywords>
<gmd:MD_Keywords>
<gmd:keyword>
<gco:CharacterString>courantométrie</gco:CharacterString>
</gmd:keyword>
<gmd:type>
<gmd:MD_KeywordTypeCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml#MD_KeywordTypeCode" codeListValue="discipline" />
</gmd:type>
</gmd:MD_Keywords>
</gmd:descriptiveKeywords>
<gmd:descriptiveKeywords>
<gmd:MD_Keywords>
<gmd:keyword>
<gco:CharacterString>halieutique</gco:CharacterString>
</gmd:keyword>
<gmd:type>
<gmd:MD_KeywordTypeCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists. …
```
=> Keywords / Group keywords by type when not part of a thesaurus

web-ui/src/main/resources/catalog/js/edit/AccessManagerController.js, web-ui/src/main/resources/catalog/templates/editor/accessManager.html
Only applies to catalog with Elasticsearch 
Follow up of https://github.com/geonetwork/core-geonetwork/pull/4947
=> Uniform look for the contribute pages / Access manager

web-ui/src/main/resources/catalog/templates/editor/editorboard.html
This was making hard to do a search not from suggestion and align it with main form.
=> Editor board / Do not focus on first suggestion.

web-ui/src/main/resources/catalog/js/admin/DashboardStatusController.js
=> Admin / Indexing error / Trigger indexing

schemas/iso19139/src/main/plugin/iso19139/layout/tpl-rdf.xsl
- introduces some dcat2 aspects
- enables some of the gmx:anchor usages as suggested by inspire tgv2
- set uri-encoding for id's
=> improvement suggestions for dcat export

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/fre/labels.xml
Some improvements for `mac` namespace.
=> Schema / 19115-3 / Translation / French

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl
=> Display contact website description and display linkage in place of missing name for 19115-3:2018 in full view

web/src/main/webapp/WEB-INF/config-security/config-security-ldap-recursive.xml, web/src/main/webapp/WEB-INF/config-security/config-security.xml
In reviewing recent changes from @davidblasby I thought it would be good to include this example in the WAR, rather than just in a test folder.
Signed-off-by: Jody Garnett <jody.garnett@gmail.com>
=> Example of configuring ldap security for recursion

web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
=> Editor / Label above input mode / Fix offset for thesaurus picker

web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid.html
=> Search results / Grid mode / Display status properly

schemas/iso19139/src/main/plugin/iso19139/extract-datasets.xsl
fixes a bug accidentally introduced in #4853
=> fix extract datasets for atom

web-ui/src/main/resources/WEB-INF/classes/web-ui-wro-sources.xml, web-ui/src/main/resources/catalog/components/common/openlayers/olDecorateLayerLoading.js, web/src/main/webapp/xslt/base-layout.xsl
resolves issue #4506
alternative is to use the solution provided by @zhuoyuezhou
=> Remove closure from production scripts (fix ie11 incompatibility)

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl, schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
Fixed in main view and side bar
Before
After
=> Formatter / Avoid empty thesaurus block

release/build.xml
Related to https://github.com/geonetwork/core-geonetwork/pull/4984
=> Build / Restore previous MD5 format.

CODE_OF_CONDUCT.md
I have listed both Jeroen and OSGeo Foundation email addresses here.
=> Adopt contributor-covenant.org code of conduct as per email discussion

healthmonitor/src/main/java/org/fao/geonet/monitor/health/IndexHealthCheck.java
=> HealthCheck / Reduce cost by only retrieving the count.

web-ui/src/main/resources/catalog/views/default/templates/recordView.html
=> Angular view / Fix missing maintenanceAndUpdateFrequency

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl, schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl, web-ui/src/main/resources/catalog/components/search/mdview/mdviewModule.js, web-ui/src/main/resources/catalog/js/CatController.js, web-ui/src/main/resources/catalog/views/default/templates/recordView.html
> 
Also index Anchor in tag field.
=> Record view / Set active filter when using keyword, topic and category links

core/src/main/java/org/fao/geonet/constants/Geonet.java, inspire-atom/src/main/java/org/fao/geonet/inspireatom/harvester/InspireAtomHarvester.java, web-ui/src/main/resources/catalog/js/admin/SystemSettingsController.js, web-ui/src/main/resources/catalog/templates/admin/settings/system.html
- Create independent log file for each Atom harvester execution and log improvements. 
- UI: use gn-click-and-spin directive
=> INSPIRE Atom improvements

schemas/iso19110/src/main/plugin/iso19110/index-fields/index.xsl, schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
=> ISO19110 / Index feature type as object.

inspire-atom/src/main/java/org/fao/geonet/inspireatom/harvester/InspireAtomHarvester.java, inspire-atom/src/main/java/org/fao/geonet/inspireatom/util/InspireAtomUtil.java, web/src/main/webapp/WEB-INF/classes/log4j-dev.xml, web/src/main/webapp/WEB-INF/classes/log4j-index.xml, web/src/main/webapp/WEB-INF/classes/log4j-search.xml, web/src/main/webapp/WEB-INF/classes/log4j.xml
- Define log level for Atom harvester in log4j configuration files.
- Improve the filter of service metadata to search by metadata type and atom protocol.
=> INSPIRE Atom feeds improvements, related to #5043

web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
=> Related / Fix error when LAN file path contains `\`

es/README.md, services/src/main/java/org/fao/geonet/api/es/EsHTTPProxy.java, web-ui/src/main/resources/catalog/components/elasticsearch/EsService.js, web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js, web-ui/src/main/resources/catalog/js/CatController.js, web-ui/src/main/resources/catalog/locales/en-v4.json, web-ui/src/main/resources/catalog/style/gn_search.less, web-ui/src/main/resources/catalog/views/default/module.js, web-ui/src/main/resources/catalog/views/default/templates/searchForm.html
Also adds:
* Error reporting / Return Elasticsearch error cause
* Error reporting / Display human friendly text and report detailed error in console
* Doc / Help to cover errors related to field exansion limit.
=> Search / Add exact match support.

core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java, core/src/main/java/org/fao/geonet/kernel/mef/Importer.java, services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java, web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js, web-ui/src/main/resources/catalog/js/edit/EditorBoardController.js
* MEF import can index immediately
* Delete / Does not need to forceRefresh. Delete are immediately refreshed
* Delete / Better reporting of errors
=> Import, Delete / Improvements

schemas/iso19139/src/main/plugin/iso19139/formatter/jsonld/iso19139-to-jsonld.xsl
this typo breaks json-ld output
=> missing comma in array in json-ld

services/src/main/java/org/fao/geonet/api/records/InspireValidationApi.java, services/src/main/java/org/fao/geonet/api/records/MetadataApi.java, services/src/main/java/org/fao/geonet/api/records/MetadataSampleApi.java, services/src/main/java/org/fao/geonet/api/records/MetadataTagApi.java, services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java, services/src/main/java/org/fao/geonet/api/registries/CrsApi.java, services/src/main/java/org/fao/geonet/api/related/Related.java, services/src/main/java/org/fao/geonet/api/selections/UserSelectionsApi.java, services/src/main/java/org/fao/geonet/api/site/LogosApi.java, services/src/main/java/org/fao/geonet/api/site/SiteApi.java, services/src/main/java/org/fao/geonet/api/sources/SourcesApi.java, services/src/main/java/org/fao/geonet/api/standards/StandardsApi.java, services/src/main/java/org/fao/geonet/api/status/StatusApi.java, services/src/main/java/org/fao/geonet/api/userfeedback/UserFeedbackAPI.java, services/src/main/java/org/fao/geonet/api/users/UsersApi.java, services/src/main/java/org/fao/geonet/api/users/transfer/TransferApi.java
=> API / Deduplicate method names to avoid _1, _2 in generated clients.

web/src/main/webapp/WEB-INF/config-security/config-security-core.xml
Related to https://github.com/geonetwork/geonetwork-ui/pull/17
=> XSRF / Not required for search service

web-ui/src/main/resources/catalog/components/usersearches/partials/featuredusersearchescards.html
=> Home / Featured searches / Styling fix

web-ui/src/main/resources/catalog/components/elasticsearch/EsFacet.js, web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js
eg. 
```json
'tag': {
'collapsed': true,
'terms': {
'field': 'tag',
'include': '.*',
'size': 10
}
},
```
will collapse the keyword facet and `more` action was returning an error:
=> Facet / More with collapse state

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl, schemas/iso19139/src/main/plugin/iso19139/formatter/xsl-view/view.xsl
=> Advanced view / Side bar / Fix link to keyword search

web-ui/src/main/resources/catalog/components/search/mdview/mdviewDirective.js, web-ui/src/main/resources/catalog/components/search/mdview/partials/morelikethis.html
* Request only required fields - reduce response size to the fields used in the template
* Add status of the similar record
=> More like this / Improvements

web-ui/src/main/resources/catalog/components/elasticsearch/EsService.js
Before that, the suggestion was sorting based on the default score. User expects the suggestion to have similar relevance ordering as the main search. So use the scoring function. Order may still slightly differ because in one case a `multi_match` is made (for partial word and phrase support), in the other a full text search on `any` field. This can be changed in the configuration if needed.
In the case below, the first 2 suggestions are the non obsolete one as define in the score config;
=> Suggestion / Apply the score function to the suggestion

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/jsonld/iso19115-3.2018-to-jsonld.xsl, schemas/iso19139/src/main/plugin/iso19139/formatter/jsonld/iso19139-to-jsonld.xsl
=> Formatter / JSON-LD / Avoid error on multiple hierarchyLevel

services/src/main/java/org/fao/geonet/api/GlobalExceptionController.java
Check details of the issue to solve in #5042
=> Global exception controller should  not return body content if requested text/html. Fixes #5042

web-ui/src/main/resources/catalog/components/viewer/heatmap/HeatmapService.js
Relates to https://github.com/geonetwork/core-geonetwork/pull/5140
=> WFS Indexing / Heat map service

web-ui/src/main/resources/catalog/js/edit/EditorController.js
=> Editor / Fix category selector

core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
Symptom: no date displayed in record view if only one defined.
=> Index / Array field / Fix name for dates

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/ISO19139/toISO19139.xsl
Was producing
```xml
<gmd:pointOfContact>
<gmd:CI_ResponsibleParty>
<gmd:individualName>
<gco:CharacterString></gco:CharacterString>
...
</gmd:CI_ResponsibleParty>
<gmd:CI_ResponsibleParty>
...
```
Tested with 
```xml
<mdb:MD_Metadata xmlns:mac="http://standards.iso.org/iso/19115/-3/mac/2.0"
xmlns:mcc="http://standards.iso.org/iso/19115/-3/mcc/1.0"
xmlns:mdq="http://standards.iso.org/iso/19157/-2/mdq/1.0"
xmlns:mri="http://standards.iso.org/iso/19115/-3/mri/1.0"
xmlns:gml="http://www.opengis.net/gml/3.2"
xmlns:mrc="http://standards.iso.org/iso/19115/-3/mrc/2.0"
xmlns:mrl="http://standards.iso.org/iso/19115/-3/mrl/2.0"
xmlns:gfc="http://standards.iso.org/iso/19110/gfc/1.1"
xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0"
xmlns:mrs="http://standards.iso.org/iso/19115/-3/mrs/1.0" …
```
=> ISO19115-3 / ISO19139 conversion / CI_Responsibility with multiple individuals creates invalid records.

web-ui/src/main/resources/catalog/js/CatController.js, web-ui/src/main/resources/catalog/views/default/directives/directive.js
Fix issue introduced by https://github.com/geonetwork/core-geonetwork/commit/df5aece9b006cb1fdee73a3bdfd95686bd6a8280.
isHarvested can be string or boolean. Properly parse value.
=> Harvested records / Editable depending on config.

web/src/main/webResources/WEB-INF/config-spring-geonetwork.xml
Co-authored-by: Marco Volpini <tabareu90@gmail.com>
=> Improve MetadataManager bean declaration (#5051)

web/src/main/webResources/WEB-INF/config-spring-geonetwork.xml
Co-authored-by: Marco Volpini <tabareu90@gmail.com>
=> [BP] Improve MetadataManager bean declaration (#5051)

domain/src/main/java/org/fao/geonet/domain/converter/JpaConverterJson.java, services/src/main/java/org/fao/geonet/api/records/MetadataWorkflowApi.java, services/src/main/java/org/fao/geonet/api/records/model/MetadataStatusResponse.java, workers/camelPeriodicProducer/src/main/java/org/fao/geonet/camelPeriodicProducer/MessageProducerController.java
Fixed missing setCurrentStatus and setPreviousStatus
Fixed API permission issues (I also noticed a hasrole in MessageProducerController.java and changed it to hasAuthority)
Fixed issues related to @Converter(autoApply = true) (same as PR https://github.com/geonetwork/core-geonetwork/pull/5198)
=> Fixed missing setCurrentStatus and setPreviousStatus

services/src/main/java/org/fao/geonet/api/records/MetadataTagApi.java, web-ui/src/main/resources/catalog/components/category/CategoryDirective.js, web-ui/src/main/resources/catalog/components/category/partials/batchcategory.html, web-ui/src/main/resources/catalog/locales/en-core.json, web-ui/src/main/resources/catalog/locales/en-v4.json, web-ui/src/main/resources/catalog/style/gn.less
=> Selection / Category / Add support to remove categories on a selection.

web-ui/src/main/resources/catalog/components/viewer/owscontext/OwsContextService.js
Can be tested with 
```xml
<ows-context:OWSContext xmlns:ows-context="http://www.opengis.net/ows-context"
xmlns:ows="http://www.opengis.net/ows"
xmlns:xlink="http://www.w3.org/1999/xlink"
version="0.3.1" id="ows-context-ex-1-v3">
<ows-context:General>
<ows:BoundingBox crs="EPSG:3857">
<ows:LowerCorner>-4364633.967048479 1788597.8727828506</ows:LowerCorner>
<ows:UpperCorner>7356525.698313588 11963895.078105513</ows:UpperCorner>
</ows:BoundingBox>
</ows-context:General>
<ows-context:ResourceList>
<ows-context:Layer name="{type=arcgis,name=0,1,2,3,4}" group="Background layers" hidden="false" opacity="1">
<ows-context:Server service="urn:ogc:serviceType:WMS">
<ows-context:OnlineResource
xlink:href="https://bio.discomap.eea.europa.eu/arcgis/rest/services/Internal/Basemap_EEA38_WM/MapServer"/> …
```
=> Map / Background / Add support for ESRI REST layers (and WMS multiple layers)

web-ui/src/main/resources/catalog/components/catalog/CatalogService.js
Field in the index is a boolean.
=> Editor board / Fix icon when record is published to all

core/src/main/java/org/fao/geonet/api/records/attachments/ResourceLoggerStore.java
After PR https://github.com/geonetwork/core-geonetwork/pull/5219 was applied and the resources were correctly loaded into the correct location.  It was noticed that there were exceptions in ResourceLoggerStore.
It was failing on the following statement
`metadataFileUpload = uploadRepository.findByMetadataIdAndFileNameNotDeleted(metadataId, resourceId);`
because it was finding more than one active metadataFileUpload.
This was because it was storing both the working copy and the approved copy MetadataFileUpload  under the approved copy metadata id.
This PR fixes this issue.
There was also an issue where certain file stores allowed a file with the same filename to be uploaded on top of another which replaced the file and increased the version number of the file.  So before adding a new …
=> Fixed issues with ResourceLoggerStore and working copy

web/src/main/webapp/WEB-INF/config-security/config-security-core.xml
Needed for monitoring tools like beats (see https://github.com/geonetwork/docker-geonetwork/pull/60)
=> Security / Allow basic auth to connect to dashboards

schemas/dublin-core/src/main/plugin/dublin-core/index-fields/index.xsl, schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl, schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl, web/src/main/webResources/WEB-INF/data/config/index/records.json, web/src/main/webResources/WEB-INF/data/config/index/records_french.json
Replace geoTag by a generic keywordType-* field. keywordType-place is the equivalent of previous geotag.
Also fix some errors indexing overview URL and fix empty resourceType for dublin core.
=> Indexing / Add keyword type field.

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/xsl-view/view.xsl
=> ISO19115-3 / Formatter / Space before unit

schemas/iso19139/src/main/plugin/iso19139/loc/dut/codelists.xml
=> add dutch translations

healthmonitor/src/main/java/org/fao/geonet/monitor/health/LuceneIndexHealthCheck.java
If no metadata records then it is OK to have 0 results from index.
Fix for issue #5074
=> Fix Lucene healthcheck for initial installation.

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
Indexing was failing for those records.
=> ISO19115-3 / Avoid error while parsing empty date

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/config/associated-panel/default.json, web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
Update record filter to new index fields and query api.
This is used in here
to list record depending on type of links.
=> ISO19115-3 / Editor / Online source link to record

web-ui/src/main/resources/catalog/components/userfeedback/partials/userfeedbacknew.html
=> User feedback / Fix placeholder

web-ui/src/main/resources/catalog/style/gn_metadata.less
=> More like this / Fix for long titles

web-ui/src/main/resources/catalog/locales/en-admin.json, web-ui/src/main/resources/catalog/locales/en-search.json, web-ui/src/main/resources/catalog/templates/admin/settings/cssstyle.html, web-ui/src/main/resources/catalog/views/default/less/gn_footer_default.less, web-ui/src/main/resources/catalog/views/default/less/gn_variables_default.less, web-ui/src/main/resources/catalog/views/default/templates/footer.html, web-ui/src/main/resources/catalog/views/default/templates/index.html
This PR adds (small) improvements to the footer of GeoNetwork
Changes:
- [a11y] add individual list items
- use Bootstrap only classes
- cleanup css
- add background on hover setting
- [a11y] use unique label for RSS feed
- [a11y] replace `<i>` with `<span>`
=> [a11y] Accessibility improvements for the footer

harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractParams.java
Same approach to unset the value on update for CSW. See https://github.com/geonetwork/core-geonetwork/blob/master/harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/CswParams.java#L119.
=> Harvester / From folder / Unable to reset XSLT once set

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/layout/layout.xsl
Probably a glitch introduced with Checkpoint project work made long time ago.
=> ISO19115-3 / Fix mdq:DQ_QuantitativeResult not displayed

web-ui/src/main/resources/catalog/components/common/map/mapService.js, web-ui/src/main/resources/catalog/components/common/ows/OWSService.js
* ESRI / Fix when layer extent is not in map projection
* WMS / Clean duplicates when same layer is found with various method
=> Map / ESRI support improvements

core/src/main/java/org/fao/geonet/api/records/attachments/FilesystemStore.java, core/src/main/java/org/fao/geonet/api/records/attachments/FilesystemStoreResource.java, core/src/main/java/org/fao/geonet/api/records/attachments/S3Store.java, core/src/main/java/org/fao/geonet/api/records/attachments/StoreUtils.java, core/src/main/java/org/fao/geonet/kernel/datamanager/IMetadataUtils.java, core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataUtils.java, core/src/main/java/org/fao/geonet/kernel/datamanager/draft/DraftMetadataUtils.java, domain/src/main/java/org/fao/geonet/domain/MetadataResource.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/geonet/Aligner.java, listeners/src/main/java/org/fao/geonet/listener/metadata/draft/DraftUtilities.java, web-ui/src/main/resources/catalog/components/filestore/FileStoreService.js
This is a backport of #5279
This backport required changes from #5118 so this PR also includes a partial backport of #5118 It mostly contains all the changes that were not related to CMIS.
=> [BP] Fix some working copy merge issues (#5279)

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/datacite/view.xsl, schemas/iso19139/src/main/plugin/iso19139/formatter/datacite/view.xsl
see https://support.datacite.org/docs/schema-optional-properties-v41.
=> Datacite / XSD validation / valueUri is valueURI.

core/src/main/java/org/fao/geonet/api/records/attachments/CMISStore.java, core/src/main/java/org/fao/geonet/resources/CMISConfiguration.java
Add the ability so have the metadata uuid added as a property to the CMIS object.
This will make it easier to identify the metadata record that the object belongs to.
There are 2 types of properties in CMIS.
To have the uuid go into the basic/standard property description (cmis:description).  The following environnement variable can be set.
`CMIS_METADATA_UUID_PROPERTY_NAME=cmis:description`
Secondary properties are generally within an aspect.
So the naming convention used for secondary properties is `{aspect}->{propertyname}`
In Alfresco, an example configuration would be to put the value into the secondaryproperty type cm:title which would show up in the default properties page in Alfresco.
`CMIS_METADATA_UUID_PROPERTY_NAME=P:cm:titled->cm:title`
This is an extension of the PR to …
=> CMIS add metadata property

core/src/main/java/org/fao/geonet/api/records/attachments/CMISStore.java, core/src/main/java/org/fao/geonet/resources/CMISConfiguration.java, core/src/main/java/org/fao/geonet/resources/CMISResources.java, core/src/main/java/org/fao/geonet/resources/CMISUtils.java, core/src/main/resources/config-store/config-cmis-overrides.properties, core/src/main/resources/config-store/config-cmis.xml
Update configuration so that it uses spring placeholders so that parameters can be passed using the -D option.
Refactor - Create a common cmisUtils.saveDocument function for saving documents.
Couple minor bug fixes.
=> Cmis spring placeholders and some refactoring.

web-ui/src/main/resources/catalog/components/search/searchmanager/LocationService.js
=> Search / Restore last search when switching from map to search

web-ui/src/main/resources/catalog/components/elasticsearch/EsFacet.js, web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facets.html, web-ui/src/main/resources/catalog/js/CatController.js, web-ui/src/main/resources/catalog/style/gn_search.less
* Add icon
* Add placeholder
* Add clear icon
* Add option to display filter even if no more values (useful for filtering long facet values set)
* Improve styling.
=> Facet / Filter improvements.

services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java
Record event was failing with NPE on subtemplate removal.
=> Events / Do not fails on subtemplate deletion

web-ui/src/main/resources/catalog/js/admin/DashboardStatusController.js, web-ui/src/main/resources/catalog/templates/admin/dashboard/status.html
=> Improve the visibility of the server logs for the admin user

web-ui/src/main/resources/catalog/components/catalog/CatalogService.js, web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facet-temporalrange.html, web-ui/src/main/resources/catalog/components/search/searchmanager/LocationService.js, web-ui/src/main/resources/catalog/components/viewer/geometry/GeometryDirective.js, web-ui/src/main/resources/catalog/components/viewer/wps/WpsDirective.js, web-ui/src/main/resources/catalog/components/viewer/wps/WpsService.js, web-ui/src/main/resources/catalog/components/viewer/wps/partials/processform.html, web-ui/src/main/resources/catalog/components/viewer/wps/partials/urldiscovery.html, web-ui/src/main/resources/catalog/locales/en-v4.json, web-ui/src/main/resources/catalog/views/default/directives/directive.js
* Process list / Add filter if more than 5 processes in the service. Sort list.
* Output / Add output results to the map if GeoJSON
* Output / Add possibility to resolve output references
* Output / Add possibility to decode base64 encoded parameters (even if does not look to work in all cases for GeoServer WPS responses)
* Input / Add point geometry detection based on parameter name
* Input / Add preferedOutputFormat when list of mime type is provided (default is WKT)
* Translate options
=> WPS / Improvements

services/src/main/java/org/fao/geonet/api/records/DoiApi.java
Operation was missing in openapi document.
=> API / DOI / DELETE operation was not displayed.

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl, schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/parent-remove.xsl
Relates to https://github.com/metadata101/iso19115-3.2018/commit/71509dae66d7cb4f4e1fec891c981cb28a4675b8
=> ISO19115-3 / Parent relationship may be encoded in a associated resource

web-ui/src/main/resources/catalog/components/search/searchmanager/LocationService.js
Related to https://github.com/geonetwork/core-geonetwork/commit/a16fd684a43f5cd22689862b469becef86337c2c
=> Search / Do not restore search when coming from home

web/src/main/webapp/xml/csw/record-to-csw-capabilities.xsl
=> Record to CSW Capabilities - extract language iso2code with twoCharLangCode function, update in date element to use the text value

add-schema.sh, schemas/pom.xml
Small improvement using `--force` for git submodule as per https://github.com/geonetwork/core-geonetwork/pull/5403
=> Quick update from testing add-schema.sh on 3.10.x branch

web-ui/src/main/resources/catalog/components/viewer/wps/WpsDirective.js, web-ui/src/main/resources/catalog/components/viewer/wps/partials/processform.html
Replace https://github.com/geonetwork/core-geonetwork/pull/5410 
dealing with multiple outputs with mime-type application/x-ogc-wms
Resets the download button after selecting a new WPS process
adds a datepicker for datetime input type
=> Map / WPS / Input improvements

web/src/main/webapp/xslt/ui-search/portal-list.xsl, web/src/main/webapp/xslt/ui-search/search-nojs.xsl
we use embedded json-ld now
fixes #5411
=> remove schema-org annotations from list pages

web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
Source, service, dataset are sorted by score. Sibling was sorted by title.
=> Editor / Associated resource / Make search sort order consistent

web-ui/src/main/resources/catalog/components/viewer/wps/WpsDirective.js
@fxprunayre 
Should use href not the value in title
=> fix(WPS): use href metadata value instead of title

web-ui/src/main/resources/catalog/js/admin/ThesaurusController.js
this patch resolves #4715, but i'm not sure if it has negative side-effects elsewhere, i tested various cases and they same working fine.
=> remove unsafe characters from thesaurus identifier / filename

web-ui/src/main/resources/catalog/components/filestore/partials/filestore.html, web-ui/src/main/resources/catalog/components/history/partials/historyStep.html, web-ui/src/main/resources/catalog/components/search/resultsview/partials/selection-widget.html, web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/editor.html, web-ui/src/main/resources/catalog/components/userfeedback/partials/userfeedbackfull.html, web-ui/src/main/resources/catalog/templates/admin/classification/categories.html, web-ui/src/main/resources/catalog/templates/admin/classification/thesaurus.html, web-ui/src/main/resources/catalog/templates/admin/dashboard/record-links.html, web-ui/src/main/resources/catalog/templates/admin/harvest/harvest-settings.html, web-ui/src/main/resources/catalog/templates/admin/metadata/formatter.html, web-ui/src/main/resources/catalog/templates/admin/metadata/metadata-identifier-templates.html, web-ui/src/main/resources/catalog/templates/admin/settings/csw-virtual.html, web-ui/src/main/resources/catalog/templates/admin/settings/logo.html, web-ui/src/main/resources/catalog/templates/admin/settings/mapservers.html, web-ui/src/main/resources/catalog/templates/admin/settings/sources.html, web-ui/src/main/resources/catalog/templates/admin/settings/ui.html, web-ui/src/main/resources/catalog/templates/admin/usergroup/groups.html, web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html, web-ui/src/main/resources/catalog/templates/editor/directory.html, web-ui/src/main/resources/catalog/templates/editor/top-toolbar.html, web-ui/src/main/resources/catalog/templates/formatter-viewer.html, web-ui/src/main/resources/catalog/views/default/templates/recordView.html
=> Changed delete icon to an trashcan icon and cancel to X when editing.

services/src/main/java/org/fao/geonet/api/userfeedback/UserFeedbackUtils.java, web-ui/src/main/resources/catalog/components/userfeedback/GnUserfeedbackDirective.js, web-ui/src/main/resources/catalog/components/userfeedback/partials/userfeedback.html, web-ui/src/main/resources/catalog/components/userfeedback/partials/userfeedbackfull.html, web-ui/src/main/resources/catalog/components/userfeedback/partials/userfeedbacknew.html, web-ui/src/main/resources/catalog/views/default/templates/recordView.html
* Fix average when only one rating (do not start with a 0 star rate). One 5 stars rate was indicating average of 2. 
Before 
After the fix
* More consistent layout/alignement with side panel structure - eg. icon before title
Before
After 
* Clear + icon to add a comment
=> User feedback improvements

services/src/main/java/org/fao/geonet/api/links/LinksApi.java, services/src/main/java/org/fao/geonet/api/records/CatalogApi.java, services/src/main/java/org/fao/geonet/api/records/editing/BatchEditsApi.java
Fix annotation errors identified in  #5431
=> Fix Open API spec document annotation errors. #5431

core/src/main/java/jeeves/transaction/TransactionManager.java
=> Log transaction manager notification failures backport to 3.10.x

web-ui/src/main/resources/catalog/js/GnLocale.js, web-ui/src/main/resources/catalog/js/edit/EditorController.js
@josegar74 
Hi Jose,
As the previous PR is merged, so I created this new PR as we discussed in https://github.com/geonetwork/core-geonetwork/pull/5423#issuecomment-787696388
This is the code I will use for encoding issue
$translateProvider.useSanitizeValueStrategy('escapeParameters');
=> User $translateProvider.useSanitizeValueStrategy('escapeParameters') for encoding sanitizing

web-ui/src/main/resources/catalog/components/elasticsearch/directives/FacetDirective.js, web-ui/src/main/resources/catalog/components/elasticsearch/directives/partials/facet-temporalrange.html, web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js, web-ui/src/main/resources/catalog/js/CatController.js, web-ui/src/main/resources/catalog/locales/en-v4.json
* Add tooltip with basic instructions for users
* Add option to select calendar min/max view. eg. years
* Legend for blue and grey series
=> Facet / Interactive date range.

schemas/csw-record/pom.xml, schemas/dublin-core/pom.xml, schemas/iso19110/pom.xml, schemas/iso19115-3.2018/pom.xml, schemas/iso19139/pom.xml, schemas/pom.xml, schemas/schema-core/pom.xml
Fix issue with schema versions.
The following contains some reasoning for the change.
https://github.com/metadata101/iso19139.ca.HNAP/issues/189
I will put this request in draft mode as I suspect that this may affect some of the versioning script.  I would like @josegar74 or @jodygarnett to review these changes.
=> Updated schema pom file to get parent version from variable.

web-ui/src/main/resources/catalog/templates/admin/admin.html
=> Admin / Hits / Missing total

web-ui/src/main/resources/catalog/js/admin/ThesaurusController.js
=> fix typo in thesaurus manager

web-ui/src/main/resources/catalog/components/utility/UtilityService.js
=> WFS Feature filter / Some user can create facet tree from value

csw-server/src/main/java/org/fao/geonet/csw/common/requests/CatalogRequest.java, web-ui/src/main/resources/catalog/components/metadataactions/partials/metadatagroupupdater.html
=> Enable preemptive for csw requests with credentials

web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js
Relates to https://github.com/geonetwork/core-geonetwork/pull/5494
@julsbreakdown fine for you?
=> Date picker / Config may be undefined. Limit may only be max or min and not both.

web-ui/src/main/resources/catalog/components/common/ows/OWSService.js
=> consider proj.worldextent not defined

web-ui/src/main/resources/catalog/components/search/mdview/mdviewDirective.js, web-ui/src/main/resources/catalog/components/search/mdview/mdviewModule.js, web-ui/src/main/resources/catalog/components/search/mdview/mdviewService.js, web-ui/src/main/resources/catalog/components/search/searchmanager/LocationService.js, web-ui/src/main/resources/catalog/views/default/templates/index.html, web-ui/src/main/resources/catalog/views/default/templates/recordView.html
=> Full view doesn't work in a draft version of a metadata record. Fixes #5373

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/jsonld/iso19115-3.2018-to-jsonld.xsl, schemas/iso19139/src/main/plugin/iso19139/formatter/jsonld/iso19139-to-jsonld.xsl
- distribution//name,url,description are now json-escaped
- distribution//url only included if starts with http or //
- license is a creativework with name (not description)
=> Fixes some challenges in google-structured-data-test

web/src/main/webResources/WEB-INF/config-node/srv.xml
../config-db/jndi-postgres-postgis.xml does not exist. Change it to ../config-db/jndi.xml to avoid confusion.
=> Update sample jndi configuration to point to correct filename

web-ui/src/main/resources/catalog/components/search/mdview/mdviewDirective.js, web-ui/src/main/resources/catalog/components/search/mdview/partials/contact.html
Without the fix:
With the fix:
=> Fix translation of roles when a contact is listed with multiple roles

web-ui/src/main/resources/catalog/components/utility/UtilityService.js, web-ui/src/main/resources/catalog/js/admin/AdminToolsController.js, web-ui/src/main/resources/catalog/js/edit/BatchEditController.js, web-ui/src/main/resources/catalog/js/edit/EditorBoardController.js, web-ui/src/main/resources/catalog/templates/admin/tools/batch.html, web-ui/src/main/resources/catalog/templates/editor/batchedit.html, web-ui/src/main/resources/catalog/templates/editor/editorboard.html, web-ui/src/main/resources/catalog/templates/gn-typeahead-match.html, web-ui/src/main/resources/catalog/views/default/templates/home.html, web-ui/src/main/resources/catalog/views/default/templates/searchForm.html
To reproduce GN 4 the  issue described in #5536  for `Steps to reproduce the behaviour as an editor`, should be applied to the title or abstract.
=> Fixes embedded Cross-Site Scripting issues in #5536 for GeoNetwork 4

services/src/main/java/org/fao/geonet/api/users/UsersApi.java, services/src/test/java/org/fao/geonet/api/users/UsersApiTest.java
=> Update user - verify user groups when updating a user by a UserAdmin. Fixes #5537

web-ui/src/main/resources/catalog/components/elasticsearch/EsFacet.js
Add list of links when user decides to add online resource - e.g. application
=> Add links when users add online resource (e.g.: application)

web-ui/src/main/resources/catalog/components/elasticsearch/EsFacet.js, web-ui/src/main/resources/catalog/components/elasticsearch/directives/FacetDirective.js, web-ui/src/main/resources/catalog/components/search/mdview/mdviewModule.js, web-ui/src/main/resources/catalog/components/search/resultsview/partials/viewtemplates/grid.html, web-ui/src/main/resources/catalog/components/search/searchmanager/LocationService.js, web-ui/src/main/resources/catalog/views/default/directives/partials/infolist.html, web-ui/src/main/resources/catalog/views/default/templates/recordView.html
* Record view & search results / Fix status display
* Was missing on search results 
* Float left in record view
* Record view / Fix link on filter by keyword (search was redirected twice to previous search)
* Home / Use large thumbnail in info list (instead of the small one)
* Interactive graphic facet / Better check of vega library load
=> UI fix & improvement

web-ui/src/main/resources/catalog/components/search/mdview/mdviewDirective.js
Fixes an issue introduced in  #5541
=> Translation of roles when a contact is listed with multiple roles - fix dependency injection, related to #5541

web-ui/src/main/resources/catalog/components/utility/partials/batchreport.html
This avoid an empty gray badge
=> Batch report / Only display stack trace if set

web-ui/src/main/resources/catalog/views/default/templates/recordView.html
Replace https://github.com/geonetwork/core-geonetwork/pull/3990
=> ISO19110 / View / Display feature cat in associated resources

web-ui/src/main/resources/catalog/components/admin/uiconfig/partials/uiconfig.html, web-ui/src/main/resources/catalog/js/CatController.js, web-ui/src/main/resources/catalog/locales/en-admin.json, web-ui/src/main/resources/catalog/locales/fr-admin.json, web-ui/src/main/resources/catalog/views/default/module.js, web-ui/src/main/resources/catalog/views/default/templates/results.html
Replace https://github.com/geonetwork/core-geonetwork/pull/5466
=> Search / Map / add option collapse map on startup

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/schema-ident.xml
Relates to https://github.com/geonetwork/core-geonetwork/pull/5457
=> ISO19115-3 / Link to the PR which allow to use contact directory

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/jsonld/iso19115-3.2018-to-jsonld.xsl, schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/common.xsl, schemas/iso19139/src/main/plugin/iso19139/formatter/jsonld/iso19139-to-jsonld.xsl
while fixing this error, i ran into an indexing error on common.xsl, 
seems featurecatalog is not multilingual ready?
fixes feature-catalog indexing in iso19115-3
=> fixes resource links if multilingual

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
Relates to https://github.com/geonetwork/core-geonetwork/pull/5558
Needs more work to support multilingual feature catalogue description in the index.
=> ISO19115-3 / Multilingual / Avoid error on feature catalogue indexing

domain/src/main/java/org/fao/geonet/domain/converter/JpaConverterJson.java
=> Remove "autoApply = true" option as it is not required. (#5182)

common/src/main/java/org/fao/geonet/exceptions/JeevesException.java
Related to https://github.com/geonetwork/core-geonetwork/commit/6c70a10ad6deb5299a2815213cafad1f3aa44f9e
Avoid NPE in some cases.
=> Admin / Harvester / No harvester in list after error

SECURITY.md
page is highly inspired on geoserver security page (thanx jody)
=> add security policy so github picks it up

web-ui/src/main/resources/catalog/components/edit/datepicker/DatePickerDirective.js, web-ui/src/main/resources/catalog/components/edit/datepicker/partials/datepicker.html, web-ui/src/main/resources/catalog/style/gn_editor.less
If UI timezone is same as server time zone, hide the option.
If dates contains a different typezone it is displayed.
=> Editor / Timezone / Hide time zone selector

web-ui/src/main/resources/catalog/components/edit/datepicker/partials/datepicker.html
Related to https://github.com/geonetwork/core-geonetwork/pull/5601
Before
After
=> Editor / Date picker / Hide timezone for year/month

CONTRIBUTING.md
Replace old branch name by `main`.
=> Update main references in CONTRIBUTING.md

code_quality/codetemplates.xml, core/src/main/java/jeeves/server/context/ServiceContext.java, software_development/DEVELOPMENT.md, software_development/ECLIPSE.md, software_development/INTELLIJ.md, software_development/SOURCE.md, software_development/TESTING.md, software_development/TOOLS.md
@josegar74 requested I write some documentation for the recent service context api work.
I ended up getting a bit lost on where to write this and ended up writing a ``DEVELOPMENT.md`` page, and testing/updating some of the other development documentation.
This is only intended as a start and I expect the content to improve over time.
This PR is made against `3.12.x` branch which contains the functionality being documented; it is expected it will be included in `main` when the two branches are better synchronized.
=> Some documentation on GeoNetwork Development

core/src/main/java/org/fao/geonet/resources/ResourceFilter.java
Fix content type header when document is XML or XSD.
=> Resources / All resources are not images

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl
=> ISO19115-3 / Indexing / Lineage

common/src/main/java/org/fao/geonet/utils/Xml.java, core/src/main/java/org/fao/geonet/kernel/EditLib.java
- Detect xml snippet with self-closing element.
- doAddFragmentFromXpath: ignore delete element
=> EditLib fixes

web-ui/src/main/resources/catalog/components/elasticsearch/EsFacet.js, web-ui/src/main/resources/catalog/locales/en-v4.json, web-ui/src/main/resources/catalog/templates/admin/dashboard/status.html
Also add local/harvested record facet to easily find local records with errors.
=> Admin / Status / Index errors as facet.

web-ui/src/main/resources/catalog/components/edit/editorhelper/EditorHelperDirective.js, web-ui/src/main/resources/catalog/components/edit/editorhelper/partials/editorhelper.html
Complementary work to https://github.com/geonetwork/core-geonetwork/pull/5465
=> Editor / List format as protocol in helper list

workers/wfsfeature-harvester/src/main/java/org/fao/geonet/harvester/wfsfeatures/worker/OwsUtils.java
=> WFS Indexing / Avoid NPE when getSuperclass is null

core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java, schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/update-fixed-info.xsl, services/src/main/java/org/fao/geonet/api/OpenApiConfig.java
See #5275
Allow to update the creation date into the xml (iso 19115-3)
=> Update creation date of duplicated record (xml) when user duplicates record (iso 19115-3)

services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java, web-ui/src/main/resources/catalog/components/common/map/mapService.js, web-ui/src/main/resources/catalog/components/viewer/ViewerDirective.js, web-ui/src/main/resources/catalog/components/viewer/partials/mainviewer.html, web-ui/src/main/resources/catalog/components/viewer/searchlayerformap/SearchLayerForMapDirective.js, web-ui/src/main/resources/catalog/components/viewer/searchlayerformap/partials/searchlayerformap.html, web-ui/src/main/resources/catalog/style/gn_viewer.less, web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v405/migrate-default.sql
* Map import / Use protocol OGC:OWS-C (like when using the editor)
* ESRI / Fix JS error when error collecting legend details
* Add layer / Do not show map tabs if there is no map in the catalogue
* Add layer / Trigger search on load
* Add layer / Add sort by
* Add layer / Improve layout
=> Map / Add layer / Search improvements

schemas/iso19139/src/main/plugin/iso19139/index-fields/index-subtemplate.xsl
* Add support for multilingual subtemplate
* Add support for extent
* Add support for format
Tested on https://www.geocat.ch/
=> ISO19139 / Subtemplate / Indexing / Multilingual support.

schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
=> Error indexing iso19139 records with 2 results in data quality reports - Fixes #5698

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/present/csw/mdb-brief.xsl, schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/present/csw/mdb-full.xsl, schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/present/csw/mdb-summary.xsl
=> ISO19115-3 / Remove geonet:info element from CSW response.

web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js
Currently on selection, only link extraction was done. Not link checks.
=> Link validation / Trigger link test when processing a selection

web-ui/src/main/resources/catalog/components/metadataactions/partials/metadatagroupupdater.html, web-ui/src/main/resources/catalog/components/search/mdview/mdviewModule.js, web-ui/src/main/resources/catalog/templates/admin/usergroup/groups.html, web-ui/src/main/resources/catalog/views/default/module.js, web-ui/src/main/resources/catalog/views/default/templates/recordView.html, web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql, web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v405/migrate-default.sql
* In record view display group logo instead of source logo when prefer group logo option is on.
* Editor / Group list / Display logo
* Admin / Group list / Display logo
=> Group / Restore possibility to use group logo.

core/src/main/java/org/fao/geonet/kernel/search/EsFilterBuilder.java
* Fix java.util.MissingFormatArgumentException: Format specifier '%d'
* Fix operation filter `-1` was excluding public record ie. not 1
* Fix combination OR/AND with isTemplate criteria
=> CSW / Fix query when user is authenticated and not admin

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/schema-ident.xml
See https://github.com/ISO-TC211/XML/issues/210
=> ISO19115-3 / XSD location change

core/src/main/java/org/fao/geonet/kernel/search/EsSearchManager.java
=> Indexing / Index extentDescription as array

SECURITY.md
* add security.md
* add improvements suggested by @jodygarnett
* added suggestions from Jody
Commit from #5489.
=> Add security policy so github picks it up 

core/src/main/java/org/fao/geonet/resources/CMISResources.java
Fixed CMIS resource bug where the wrong key function was called causing an invalid key to be generated.
=> Fixed CMIS resource bug when generating resource key.

es/README.md, es/docker-compose.yml, es/es-dashboards/README.md, software_development/BUILDING.md, software_development/README.md, web/README.md
Adding some notes to the building instructions now that Elasticsearch is required on main
=> Update instructions for local development with Elasticsearch
